### ISSUE TITLE
Cross-compilation of SkyBox.ps.slang fails

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#100]
The last statement in the Slang file is
`return gTexture.Sample(gSampler, normalize(dir), 0);`

Which is converted to the following illegal statement in GLSL
`gTexture.Sample(gSampler, normalize(dir), float(0));`

To reproduce run the Effects/EnvMap sample

**Comment by tangent-vector** [comment]
Thanks. That should be an easy fix.

**Comment by tangent-vector** [comment]
Note to self: hopefully just missing some `__intrinsic(glsl, ...)` modifiers in the stdlib.

**Comment by nbenty** [comment]
Not an issue anymore. I was about to fix it and then I noticed that what I really want to use is `SampleLevel`. It works (but we still need to add the missing flavors)

**Comment by tfoleyNV** [comment]
Cool. Let's leave this open so I can get to it sooner or later.

**Comment by tfoleyNV** [comment]
Note to self: the "sample with clamp" operations seem to be a GLSL extension (sparse textures, IIRC), and not something built-in. If we need these they will have to be tagged to enable the right extension.

**Comment by tangent-vector** [comment]
Closing. We are far past this point in cross-compilation support.
