### ISSUE TITLE
Remove or allow disabling warning 39001

### ISSUE THREAD

**Issue by ignaci** [shader-slang/slang#1003]
When targetting SPIR-V we see this warning too frequently, and it is not really necessary because what we do is allowed.

"warning 39001: explicit binding for parameter 'Float4TextureCubes' overlaps with parameter 'Float4Texture2Ds'"

Please provide a way to disable this warning, and remove it.

**Comment by someonesomewheredev** [comment]
This is an old issue but in case anyone else comes across it, the warning can be disabled by putting the attribute `[[allow("parameterBindingsOverlap")]]` on each of the overlapping bindings. It seems that this was added shortly after this issue in #1005 but not documented anywhere as far as I can tell.

**Comment by csyonghe** [comment]
We have implemented compiler options to disable warnings.
