### ISSUE TITLE
HLSL Shader Model 6.0 new intrinsic support

### ISSUE THREAD

**Issue by zsz1992418** [shader-slang/slang#1015]
Latest Slang seems to have SM6.0 support like WaveAllTrue(). But their names don't match MSFT's finalized name, like WaveActiveAllTrue(). Use either of them will cause error in front end or back end.
Please double check based on https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/shader-model-6-0 .

**Comment by tfoleyNV** [comment]
This should be addressed as of PR #1029.
