### ISSUE TITLE
Pass-through mode for CPU compilers requires a dummy entry point

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1016]
It is somewhat surprising that if I invoke `slangc` in pass-through mode on a C/C++ file:

```
slangc -pass-through clang my-file.c
```

It basically does nothing. The reason for that is that I didn't specify any entry point(s), and Slang currently only invokes output code generation per-entry-point. Even if it doesn't make sense (e.g., because I'm testing the pass-through compilation support itself) I have to make up an entry point:

```
slangc -pass-through clang -entry dummy my-file.c
```

This could be fixed with a custom solution (e.g., automatically adding just such a dummy entry point in the command-line argument parsing logic), or it could be subsumed by a more general feature that supports targets that don't require explicit entry points to be enumerated (e.g., because the target supports zero or more entry points per file natively).

**Comment by csyonghe** [comment]
We no longer care pass through mode.
