### ISSUE TITLE
Matrix-float multiplication cross-compilation fails

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#103]
```C++
float f;
mat4 a;
mat b = a*f; // This is legal in GLSL but fails compilation inside Slang
```
Looks like it's a Slang bug, since the GLSL compiler is never invoked.

We are using it for vertex-blending- `ShaderCommon.slang::59` - `getBlendedWorldMat`

**Comment by tangent-vector** [comment]
Can you copy-paste in the error message you see?

My guess is that I'm just missing some overloads of `operator*`. I hope it isn't something more serious.

**Comment by tangent-vector** [comment]
One more note-to-self issue here is that I'm realizing there could be subtle problems if cross-compilation involves scalar-to-matrix conversion. `float4x4(a)` produces a matrix with 16 elements of `a`, while `mat4(a)` produces a diagonal matrix.

There is a similar issue where I need to make sure to translate HLSL `operator*` on matrices to the appropriate `componentMul` call.

**Comment by nbenty** [comment]
![image](https://user-images.githubusercontent.com/17769755/28250872-733b406e-6a27-11e7-8cfc-31d6f9271bc4.png)

**Comment by tfoleyNV** [comment]
I think I misunderstood this error. The problem is *not* that we are giving an error on a matrix-scalar multiply in GLSL code, but rather that we are giving the error on Slang code that tries to do matrix-times-scalar.

It seems like this error shouldn't be specific to cross-compilation, then, and should occur for any Slang code that tries to do this.

**Comment by tfoleyNV** [comment]
Yep. I can repro this is a bare Slang file, so this is just a plain old screw-up on my part.

There are two reasonable ways to fix this:
- Implement implicit promotion of scalars to matrices, after which the ordinary component-wise multiply will be taken
- Implement explicit overloads of `operator*` (and probably others) for the matrix/scalar and scalar/matrix cases (and same for vector/scalar, ...)

It isn't clear to me which is the way that HLSL interprets this kind of things internally.
