### ISSUE TITLE
Handle PS `uint` inputs

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#104]
We have the following declaration in `SceneEditorCommon.slang.h`: ```uint drawID : DRAW_ID;```

HLSL implicitly assigns `nointerpolation` qualifier to it, but GLSL requires that the user define it with the `flat` qualifier.
I tried adding `nointerpolation`, but Slang didn't replace it with `flat`.

The simple solution for now would be to just replace `nointerpolation` with `flat`, but the long-term solution would be for Slang to detect `uint` outputs and assign the required qualifiers

**Comment by tangent-vector** [comment]
Spitting out `nointerpolation` as `flat` should be easy in principle. There might be an additional bug here where my "lowering" logic isn't propagating interpolation qualifiers from struct fields over to the global variables I generate in GLSL.

Doing something based on types should be easy enough too. I will try to implement both when I fix this.
