### ISSUE TITLE
Use stdlib to for C/C++ backend definitions

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1066]
The stdlib has definitions that can for example turn an HLSL intrinsic into the suitable call in glsl. 

The mechanism for describing these transformations is somewhat ad hoc - but it does allow a lot of flexibility and the ability to describe succinctly intent. 

With the C++ backend, this was dealt with in two different ways 

1) For simple scalar built in functions there implementation was pushed out to the 'prelude'
2) Built in intrinsics that were type dependent the implementation was generated on demand in when it is used

For example take

```
Matrix<float, 4, 4> mat = ...;
Matrix<float, 4, 4> sinMat = sin(mat);
```

That the `sin` scalar function will be turned into a call into a function in the prelude. In this case `F32_sin`. That the sin(mat) will cause a function `Matrix<float, 4, 4> sin(Matrix<float, 4, 4>)`  to be generated, and then at the call site just 'sin' can be output. 

The defining of the functions within the prelude has some definite pros to it, in that a client can decide what implementation they wish to use for these functions. If the only implementation is defined in the stdlib, either it would be beneficial to be able to change the stdlib defintion or clients will be stuck with whatever implementation is defined in stdlib. It's also unfortunately true, that all of the functions that would need to be defined may not be available on all compilers. That the prelude can either ignore this (as client can always just use their own prelude) and/or it's typically pretty easy (if ugly) to test such cases with preprocessor in prelude. If it's defined in stdlib and not replaceable - then potentially it won't work at all for some compilers.   

Having definitions as part of the stdlib is more in keeping with other targets, and allows for definitions to be located in a single place. Also if such definitions were replacable then perhaps you'd have the best of both worlds. Where the ones defined in the stdlib are perhaps the 'default' definition. 

For the second case, the 'sin' generation could perhaps be side stepped with templating pre generated specializations (and so a very big prelude file). One of the reasons the implementation was made to generate the functions as needed, is it allows for supporting a C backend in the future. 

That being said - there are some functions where having a simple implementation in the stdlib would be a perfectly good solution. Take `cross` for example. If that was given a default definition, that was then converted to C/C++, as part of the regular emit, it would remove a lot of code and complexity from the CPP code generation.

Other simple examples would be 'length', 'normalize', 'reflect', 'any', 'all' and vector/matrix multiplication. You could also imagine other operations (such as a swizzle converting to a construct) might be suitable.

**Comment by csyonghe** [comment]
The C++ backend is now refactored to follow the same pattern for other backends.
