### ISSUE TITLE
Function on struct can't find global function with same name

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#1088]
We had this error a while ago:

```
A.slang
    float f(int a, int b);

B.slang
    import A;
    struct S {
        int a, b;
        float f(bool b = true) { return f(a,b); }
    };

```
I get an error 39999: too many arguments to call (got 2, expected 1). It seems it can't find the g
global function f.

Is it a bug or expected to work?

**Comment by tfoleyNV** [comment]
I think this counts as a bug insofar as there needs to be a way to make it work, whether or not that exact syntax should work in this case.

My intention for name lookup in cases like that has been that as soon as one function is found during lookup, then *all* functions of the same name that are visible become candidates for overloading, but that doesn’t seem to be what the compiler implements today.

**Comment by natduca** [comment]
Fixed we think.
