### ISSUE TITLE
Convert Single-Pass Stereo from HLSL to GLSL

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#109]
The Vulkan extension is called `VK_NVX_multiview_per_view_attributes`
The extension spec is [here](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#interfaces-builtin-variables-positionperview)

`DefaultVS.slang` outputs to `NV_X_RIGHT` and `NV_VIEWPORT_MASK` which should be convert to new GLSL builting. 
When we detect that SPS is used, we need to output to `gl_PositionPerViewNV`. 
I didn't read the spec yet, the extension is more permissive then what SPS requires. For now we only need to support what's required for SPS.

**Comment by tfoleyNV** [comment]
Just to make sure I get it: `NV_X_RIGHT` and `NV_VIEWPORT_MASK` are HLSL semantics, yes? So I need to convert uses of shader outputs with those semantics into uses of the corresponding GLSL builtins.

Do we know if glslang supports the extension?

**Comment by nbenty** [comment]
Yes.

https://github.com/KhronosGroup/glslang/commits/master?author=chaoc

**Comment by tangent-vector** [comment]
I've looked into this a bit:

- The main challenge is that the mask output is a vector in HLSL, but an (unsized) array in GLSL

- A secondary challenge is that the mask is given type `uint` in HLSL and `int` in GLSL

- A tertiary challenge is that the HLSL extension just adds a second "right eye" output, and still uses `SV_Position` while the GLSL extension seems to replace `gl_Position` with an array of outputs

These are all surmountable, but require a bit more infrastructure for dealing with mapping system-value semantics to `gl_*` variables that may not match exactly in type.

**Comment by tangent-vector** [comment]
Implemented in #129

**Comment by tfoleyNV** [comment]
Reopening. My current implementing is totally bogus.

**Comment by tangent-vector** [comment]
Closing. There is no demand from current users for single-pass stereo.
