### ISSUE TITLE
Allow application to control entry-point symbol name in generated code

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1113]
Right now, the compiler has a fixed policy for how entry-point functions are emitted:

* For HLSL/DXIL/DXBC and CPU targets, an entry point is always emitted with a symbol name that matches how the original entry point function was declared.

* For GLSL/SPIR-V, and entry point is always emitted with the name `main`.

Note that on most targets (with DXBC being the outlier) the name of an entry point shows up in the output and may need to match with host code that loads generated kernels. This means that the policy for how Slang names these outputs impacts application code, and wrinkles like how we use different policies for DXIL vs. SPIR-V end up being baked into applications.

Moving forward, we should provide applications with a way to control the policy that is used. Reasonable choices for such a setting are:

* **Recommended**: always use the mangled name of the entry point (including specialization arguments)
* Always use the original function name as it was written in the input code
* Always use a fixed name of `main`

Whether this setting should be per-session or per-target is open to decide.

There would need to be a "default" mode for that setting that, at least for now, preserves the current inconsistent behavior across targets.

It would also be good to have an API that can be used to query the mangled names of entry points so that they can be saved in application-specific shader caches. This can help an application remain independent of the Slang name mangling rules and any subsequent changes we make to them.

The SPIR-V format supports entry points with names

**Comment by csyonghe** [comment]
This is already implemented now with `entryPointNameOverride`.
