### ISSUE TITLE
Add Slang language documentation

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1115]
The Slang language needs documentation.

# Motivation

Our high degree of compatiblity with existing HLSL code means that many programmers can (and do) rely on documentation for the HLSL langauge, but this has several draw-backs

1. It doesn't help in the cases where Slang extends HLSL with new features (e.g., generics)
2. It doesn't help in the cases where Slang intentionally deviates from an existing HLSL feature (e.g., not including the pervasive "splatting" behavior)
3. Many programmers are not pleased with the quality of the existing HLSL documentation

The best solution to the problem is for us to develop some better documentation of the Slang language itself, which exists separate from other similar languages.

# Scope

This issue is specifically about better documentation of the Slang language, and not the "standard library" code or the Slang compiler API.

Documenting library code is often best done through automated tools (e.g., doxygen and its ilk), so the work required to document the Slang standard library is qualitatively different from that required to document the language. We should track requirements and plans for library and/or API documentation separately.

In practice there are certain features of Slang that are technically library code, but that a user is likely to think of as part of the language (e.g., the `bool` type). A language reference will likely need to introduce these types, even if it leaves some aspects of their documentation to other references.

# Open Questions

## Specification, reference, or guide?

There are many different categories of documentation we could aspire to write, with different levels of formality. To clarify what I mean by these terms:

* The [C++ specification](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) tries to pin down the exact syntax and semantics of the language as little ambiguity and "wiggle room" as possible, even if doing so makes the document hard for anybody but an expert to follow.

* The [Rust reference](https://doc.rust-lang.org/stable/reference/introduction.html) attempts to introduce all the elements of the language using a taxonomic top-down organization. It doesn't try to formalize things, but it is also more concerned with covering all the details than with providing a gentle ramp.

* The first major section of [The Swift Programming Language](https://docs.swift.org/swift-book/) is a language guide that tries to teach aspects of the language in a good order for learning, by way of many examples.

There is some wiggle room on these terms (e.g., I'd claim that the GLSL "specification" is really a reference, but that's just me), but hopefully the examples make some of the differences clear.

Given that we are unlikely to have bandwidth to produce multiple documents describing the Slang language right away, we need to pick which level of formality to aim at first.

My personal take is that a good reference-level document on the language is the most important thing to have. A specification is really only valuable if there are going to be multiple implementations of the language, and guide-level documentation is not as important when most programmers coming to Slang will already be familiar with C/C++, HLSL/GLSL, or other similar languages and won't need a very gentle ramp.

## Presentation

When somebody goes to read this documentation, what should they be faced with? A few option that seem reasonable to me:

* The language reference could just be presented as some Markdown (or similar) files under the `docs/` directory in GitHub, such that people can browse them easily while looking at the repository.

* We could try to produce a PDF language reference that gets exported as part of the deployment process, so that ever binary package of Slang includes a self-contained reference document

* We could try to export language reference information to be readable via GitHub Pages (which could be driven using HTML or any GitHub-supported markup)

It might be that multiple of these can be achieved, but each involves some level of effort. The first option, which could amount to just checking in some Markdown files in the existing repository, might be a good starting point.

## Authoring

The choice of how to author the documentation intersects heavily with the choice of how to present it. LaTeX might be a reasonable choice if we primarily care about PDF output, but it seems far more likely that we'd want to use a GitHub-friendly markup format.

While Markdown is often the natural choice (being one of the most humane markup formats), it also might be more limited than other options if we *do* want to collate things into a nicely formatted PDF. Formats like AsciiDoc and ReStructured Text are seemingly better suited to complex documents.

# Summary

I'm creating this issue in the hopes of fostering discussion about how to proceed with some better documentation of the Slang language. Hopefuly we can agree on an initial plan and get started building out the skeleton of what we want to see.

**Comment by tfoleyNV** [comment]
PR #1279 represents a first step toward a language reference under our `docs/` directory.

**Comment by csyonghe** [comment]
We have a user-guide now.
