### ISSUE TITLE
Support for input attachments in vulkan

### ISSUE THREAD

**Issue by Dynamitos** [shader-slang/slang#1150]
Here i am again, thanks again for the help with tangent space. Anyways, this time I'm doing a simple forward renderpass with a Z-Prepass. For now i just want to render the depth in the prepass, then use it as an input in the main renderpass and just do a grayscale of the scene.

Now my depth buffer is used as an input attachment for the main pass, but there is no such concept in Direct X, and thus also not in HLSL. Now would it be possible to make some kind of tag of sorts to directly pass it to glslang, or is there already something that i have overlooked?

**Comment by tfoleyNV** [comment]
If would certainly be possible, and consistent with the design of Slang, to introduce a type `InputAttachment` or similar that can be used to declare a shader input of the correct type for Vulkan, and which isn’t allowed/valid for D3D targets.

Unfortunately, the current contributors to Slang are unlikely to have time to prioritize adding that type. Most of our current users/customers are writing code that they want to use on both Vulkan and D3D so Vulkan-only features are the highest priority.

That said, pull requests are always welcome and I’d be happy to give guidance to somebody on where to look if they wanted to try adding this feature to the compiler.

**Comment by Dynamitos** [comment]
Ok thanks for clarifying, maybe i will look into it later.
