### ISSUE TITLE
Varying location computation with multiple entry points

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#116]
The layout computation for global-scope varying data is messed up because Slang tries to merge data across entry points (and translation units). This needs to be fixed so that each TU (or entry point) computes locations for global-scope varying independently.

One saving grace here is that a TU can either have global-scope varyings, or entry-point-parameter varyings, but not both.

**Comment by tfoleyNV** [comment]
Either fix this for SIGGRAPH, or give an error when a varying doesn't have an explicit location.

**Comment by tfoleyNV** [comment]
Should be fixed by #118, but probably warrants more testing.

**Comment by tfoleyNV** [comment]
Users seem to be using #118 successfully, so I'm going to close this.
