### ISSUE TITLE
survey `assert()` and `throw` sites and provide diagnostics

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#117]
A Slang user shouldn't be forced to contend with an assert-fail or crash when Slang runs into an implementation issue.

These cases should all try to emit a diagnostic if possible (even just an `unimplemented: foo` message would help, and even better if it has a reasonable location), and then exit as gracefully as possible. For right now, "gracefully" probably means throwing an exception that propagates up to `spCompile` and gets caught there.

In cases where a diagnostic isn't possible, we can try to `throw` anyway, and have some way to inform `spCompile` of what is going on (that is, `spCompile` should add the diagnostic on our behalf).

**Comment by tangent-vector** [comment]
I made a first pass at this. Closing.
