### ISSUE TITLE
Constants nested in structs

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#1173]
This is a feature request for making `static const` work nested inside structs:

```
struct SomeInfo
{
    static const uint kInvalidIndex = 0xfffffffff;
    uint index = kInvalidIndex;
}
```

In code we can then also use `SomeInfo::kInvalidIndex`.

`sizeof(SomeInfo) == 4` is still expected to be true.

**Comment by csyonghe** [comment]
This is supported now.
