### ISSUE TITLE
Dynamic operator[] for vector/array types

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1179]
Some targets/compilers do not appear to support dynamic index values. For example

```
[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint idx = dispatchThreadID.x;
    float3 f = {...};
    f[idx] = 7.0f;
}
```

This works when idx is a compile time constant. 

On CUDA/C++ this works without a problem. With HLSL and fxc this does not compile. For GLSL (or perhaps glslang) this also appears to not work. 

Potential ways to fix might be a transformation like 

```
float3 f = { ... }
float tmp[] = {f[0], f[1], f[2]};
tmp[idx] = 7.0f;
f = float3(tmp[0], tmp[1], tmp[2]);
```

Another option might be

```
f[0] = (idx == 0) ? 7.0f : f[0];
f[1] = (idx == 1) ? 7.0f : f[1];
f[2] = (idx == 2) ? 7.0f : f[2];
```
Or alternatively we could make this a limitation for certain targets - but if we do that we should have Slang detect that scenario and report to users, rather than rely on the downstream compiler error, which could be significantly more confusing.

**Comment by natduca** [comment]
We're doing a bug bankrupcy --- please file a new bug or reopen if you see a specific thing we should do.
