### ISSUE TITLE
Double intrinsic support

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1180]
It appears as if both fxc and dxc do not support double intrinsics (such as sin or cos etc). That when such functions are called a warning is produced to say that the type has been narrowed to a float. 

With glslang, it appears as if it can in principal generate spir-v that tries to invoke double versions of intrinsics. On our test harness, when using the spir-v on vulkan it complains that double version of the intrinsic is unavailable as part of a validation. 

Finally on CUDA and C++, double intrinsics are available and work correctly.

**Comment by csyonghe** [comment]
We have double types now.
