### ISSUE TITLE
Hit kind constants

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#1212]
I get an undefined identifier error when trying to use these builtin values:

`HIT_KIND_TRIANGLE_FRONT_FACE` (254)  
`HIT_KIND_TRIANGLE_BACK_FACE` (255)

I'm using Slang 0.13.7

**Comment by tfoleyNV** [comment]
We must have missed those because they are poorly documented on MSDN (only being mentioned in the documentation for the `HitKind()` built-in function).

We can certainly add them.

**Comment by tfoleyNV** [comment]
These were added in #1221.
