### ISSUE TITLE
Typedef with an array does not support HLSL syntax

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1280]
Using a `typedef` to define a type that is an array has the following syntax in HLSL (and other C/C++ derived languages).

```
typedef int Thing[10];
```
Creates a type 'Thing' that is an alias for `int[10]`. 

In Slang such a definition does not work and produces the error.

```
error 20001: unexpected integer literal, expected identifier
```

It does appear possible to define this in Slang, but with different syntax, that is incompatible with HLSL.

```
typedef int[10] Thing;
```

**Comment by natduca** [comment]
We're doing a bug bankrupcy --- lets attack this when a customer needs it and it hits the threshold for !/$
