### ISSUE TITLE
Documentation Generation

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1281]
The command-line `slangc` tool should support emitting formatted documentation for a module.

Documentation for declarations should be extracted from leading comments using one of the common conventions (e.g., triple-slash `///` comment lines). The lexer should produce a unique token type for comments that follow documentation-comment conventions, and the parser should look for these comments when they appear before declarations and combine them into a `Modifier` attached to the declaration.

The actual documentation comments should probably be written in Markdown (that seems to be the way the wind is blowing, as opposed to more specialized syntax like Doxygen has used historically), which would allow us to pretty much just copy them verbatim into the output for a first pass (and eventually integrate a proper markdown parser if/when we need more advanced features).

There is a lot of prior art here both in Doxygen, and in the documentation-comment systems for Rust and Swift.

**Comment by csyonghe** [comment]
We already have some kind of doc gen.
