### ISSUE TITLE
Support for struct in struct

### ISSUE THREAD

**Issue by savage309** [shader-slang/slang#1282]
Even nesting it only 1 time would be helpful 
```
struct A {
float f;
};

struct B {
A a;
float f;
};
```

I have not thought though about the effects this might have on the alignment tbh.

**Comment by tfoleyNV** [comment]
I believe that examples like the one about should already work fine in Slang.

If there are specific cases you've found not to work, please let us know. Otherwise we will close out this issue as already implemented.

**Comment by tfoleyNV** [comment]
Closing, as it appears the desired use case works already.
