### ISSUE TITLE
loop-unroll.slang doesn't work on DX12 with DXIL

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1292]
PR #1291 expands the tests on loop-unroll.slang test. 

In order to confirm coverage, the test was expanded to use dxc by adding the -use-dxil parameter. The test ran correctly using fxc and DXBC on our DX12 backend, but if dxc/dxil is used the tests crashes. 

```
ComPtr<ID3D12PipelineState> pipelineState;
    SLANG_RETURN_ON_FAIL(m_device->CreateComputePipelineState(&computeDesc, IID_PPV_ARGS(pipelineState.writeRef())));
```
In 'createComputePipelineState'. 

Note that although this test is testing [unroll] - that this can be removed and the problem still happens.

On looking at the shader itself it is somewhat unusual in our tests in that it has 

```
RWStructuredBuffer<int> buffers[3];
```

If I turn this into 3 buffers independent buffers, and access them in the loop with an if everything works on all targets.

**Comment by csyonghe** [comment]
Fixed.
