### ISSUE TITLE
Missing <T> args in an error message when passing Texture2D as argument

### ISSUE THREAD

**Issue by pkristof** [shader-slang/slang#1296]
Slang (slang.dll module timestamp 12/9/2019) is missing <T> args in a following error message:

> error 30019: expected an expression of type 'Texture2D', got 'Texture2D'

============================
Repro:
float3 reproErrorMsg(Texture2D tex, SamplerState bilinearClamp, float2 samplePos)
{
    return tex.SampleLevel(bilinearClamp, samplePos, 0).xyz;
}

SamplerState BilinearClamp;
Texture2D<float3> tex;
float3 value =  reproErrorMsg(tex, BilinearClamp, samplePos);

**Comment by csyonghe** [comment]
Fixed.
