### ISSUE TITLE
GLSL layout rules for `uniform` and `buffer` blocks

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#13]
There is code in `TypeLayout.cpp` that tries to implement the `std140` and `std430` rules, but I have little confidence that it is being invoked correctly.

Tasks:

- Set up some reflection-generation tests for GLSL, so we can see how layouts are being computed
  - Need to be careful when defining the expected output here; should probably run the same input through `glslang` when generating baselines to double-check offsets

- Ensure that we are picking up the rules specified as a `layout` attribute and applying them correctly.

- Ensure that given GLSL source we are picking appropriate rules by default when nothing is specified (e.g., `std140` for all `uniform` blocks, and `std430` for all `buffer` blocks)

- Make sure to emit downstream code that reflects the layout choices we make, either by applying a `layout` attribute to the block, or by applying `layout(offset=...)` to each member. We should be conservative and try not to require too many extended features that could make it harder to output portable OpenGL GLSL later.

**Comment by tangent-vector** [comment]
Pull requests #56 and #58 covered this. Closing for now. New issues can be filed if anything else comes up.

**Comment by tangent-vector** [comment]
Pull requests #56 and #58 covered this. Closing for now. New issues can be filed if anything else comes up.
