### ISSUE TITLE
Namespace support breaks Reflection::FindTypeByName

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#1357]
`FindTypeByName("ParameterBlock<MyStruct>")` returns `ErrorType` since #1304 

It seems that lookup for `ParameterBlock` failed when type-checking the parsed expression tree.

**Comment by tfoleyNV** [comment]
Interesting. I wonder if this is somehow related to constructing the `Scope`s for these kinds of programmatic lookup incorrectly, so that they don't include the standard library types. It might be that looking up `int` would also fail.
