### ISSUE TITLE
Regression in multi-level associated type lookup

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#1377]
```
// assoctype-nested.slang

// Confirm that an associated type can be correctly looked up.

//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute -cpu
//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute
//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute -dx12
//TEST(compute, vulkan):COMPARE_COMPUTE_EX:-vk -compute

interface IBoneWeightSet
{
    associatedtype PackedType;
};

struct StandardBoneWeightSet : IBoneWeightSet
{
    struct PackedType
    {
        uint boneIds : BONEIDS;
        uint boneWeights : BONEWEIGHTS;
    };
    PackedType field;
};

interface IVertexFormat
{
    associatedtype BoneWeightSet : IBoneWeightSet;
};

struct VertexFormat<TBoneWeightSet : IBoneWeightSet> : IVertexFormat
{
    typedef TBoneWeightSet BoneWeightSet;
    TBoneWeightSet.PackedType weightSet;
};

struct OutputType
{
    VertexFormat<StandardBoneWeightSet>.BoneWeightSet.PackedType field;
};

int test(int val)
{
    OutputType rs;
    rs.field.boneIds = 256;
    return rs.field.boneIds;
}

//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):out,name=gOutputBuffer
RWStructuredBuffer<int> gOutputBuffer;

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint tid = dispatchThreadID.x;
    int inputVal = tid;
    int outputVal = test(inputVal);
    gOutputBuffer[tid] = outputVal;
}
```

Expected result: outputs 256.
Actual result: compilation failed, error mesesage: "tests/compute/assoctype-lookup.slang(38): error 30027: 'PackedType' is not a member of 'overload group'."

**Comment by tfoleyNV** [comment]
This is representative of a general class of cases where lookup finds both a declaration inherited through an interface and the concrete declaration that satisfies the interface requirement.

We’ve gone back and forth on how to handle this kind of lookup over time, but my current thinking has been that we want to form the overloaded reference to both declarations and then filter them down to a single declaration at use sites by picking the one that is “better” by virtue of being more derived.

It might just be the case that (static) member lookup is one more case that needs to handle this kind of disambiguation.
