### ISSUE TITLE
Remove need for "hack" sampler in GLSL cross-compilation

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#138]
There are operations like `Texture2D.Load` that don't require a sampler in HLSL, but do in GLSL. The thing is, SPIR-V doesn't have this constraint, so it is strictly a glslang limitation (and one that seemingly wasn't imposed at an earlier point).

We should fork glslang and implement the better behavior we want. If we can upstream the changes, great, but if not we can maintain a fork of glslang for now.

**Comment by tfoleyNV** [comment]
The right fix for this isn’t adding anything to glslang. It is implanting our own SPIR-V output and dropping both glslang as a back-end and GLSL as an input language.

When we can do both of those things depends on when Falcor can drop GLSL support.

**Comment by tfoleyNV** [comment]
This issue is biting users. See #646.

**Comment by tfoleyNV** [comment]
There is now an extension `GL_EXT_samplerless_texture_functions` that resolves the original issue, and current glslang should support it.

I will try to integrate that extension into the Slang compiler.
