### ISSUE TITLE
Add support for Sampler Feedback

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#1406]
DX Spec:
https://microsoft.github.io/DirectX-Specs/d3d/SamplerFeedback.html

Vulkan extension doesn't exist yet. The closest thing is an NV extension
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_shader_image_footprint.html

**Comment by csyonghe** [comment]
This is supported now.
