### ISSUE TITLE
Make string type easier to view in debugger

### ISSUE THREAD

**Issue by tangent-vector-personal** [shader-slang/slang#141]
Right now the `String` type holds a single pointer to a reference-counted copy-on-write payload of type `StringBuffer`. To minimize the number of allocations, the `char` data of the string is stored directly after the bytes of the `StringBuffer`.

This works well enough, but it means that when debugging (without a custom `.natvis` file) the text content of a string isn't visible without either calling a method on it, or doing a messy `(char*) (str.buffer.pointer + 1)`

A better design (for debugging) would make the `String` type point to the storage directly, and then access the extra fields in the buffer as `((StringBuffer*) ptr) - 1`.

The big change here would be doing all the reference-count update logic directly, rather than relying on `RefPtr` to do it.

**Comment by tangent-vector** [comment]
Note: I thought this could potentially be solved using `.natvis` files, but even though they can be embedded in a `.pdb`, visual studio will not load them in a project that links against Slang. It is worth it to improve this as much as possible.
