### ISSUE TITLE
Exposing CUDA gridDim and blockDim

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1421]
Introduction
========

D3D compute shaders can make use of various system-value (`SV_*`) inputs to determine where the current thread is situated in the overall dispatch. These values provide the location of the thread within its block/group (`SV_GroupThreadID`) and the location of the group within the dispatch/grid (`SV_GroupID`).

The values provided by D3D HLSL can be mapped to CUDA using the built-in `threadIdx` and `blockIdx` built-in variables, and Slang does exactly that when compiling to CUDA.

There are two values that CUDA provides that don't have equivalents in D3D:

* `gridDim` provides the size/shape/extents/dimensions of the dispatch/grid along the X, Y, and Z axes
* `blockDim` provides the size/shape/extents/dimensions of each block/group along the X, Y, and Z axes

A programmer using HLSL on D3D or Vulkan who needs access to these values from within shader code would usually:

* Pass the equivalent of `gridDim` in using root/push constants
* Bake the value of `blockDim` into their entry point since it needed to be provided with `[numthreads(...)]` anyway

The problem that arises is that a programmer who uses one of these options and then compiles Slang->CUDA ends up with non-idiomatic code. In particular, passing `gridDim` in via a root constant buffer in HLSL maps to CUDA code that passes that value in via a buffer in global memory, leading to the overhead of fetching from global memory whenever `gridDim` is accessed.

The design challenge is then to find a way that developers can both implement the necessary workarounds when targeting D3D/VK but also take advantage of the built-in `blockDim` and `gridDim` for CUDA.

Options
=====

Expose new built-in functions
--------------------------------

We could define CUDA-specific built-in functions `cuda_blockDim()` and `cuda_gridDim()` that return the value of `blockDim` and/or `gridDim`.

A programmer could then manually `#if` their code to make use of the built-in values when compiling for CUDA, and their own user-space values when compiling for D3D/VK.

This option has the (theoretical?) advantage of working even when the kernel wants to access `blockDim` or `gridDim` in a subroutine rather than the top-level kernel function. We could in principle expose similar functions for `threadIdx` and `blockIdx` that allow access in subroutines, so that developers can avoid manually threading them down in user-space.

The biggest down-side to this approach is that it requires writing preprocessor constructs to yield code that is both portable and performant.

Expose new system-value semantics
---------------------------------------

We could conceivably define new system-value semantics with names like `SV_DispatchDimensions` and `SV_GroupDimensions` (we'd need to workshop those names...), that map to `gridDim` and `blockDim` respectively.

Mapping those new system-value semantics to CUDA would be the easy part, of course, but then we'd still have the problem of how to provide those values for D3D/VK.

The `SV_GroupDimensions` semantic could be replaced in an IR pass, given that for D3D/VK targets we always have a `[numthreads(A, B, C)]` attribute, and the value of `SV_GroupDimensions` should always be `uint3(A, B, C)`.

The `SV_DispatchDimensions` semantic would be more work to deal with, since there is no built-in way to access it in D3D/VK. We'd either need to make that semantic CUDA-specific *or* have logic that implicitly treats `SV_DispatchDimensions` as a `uniform` shader parameter for D3D/VK, and thus users would be required to pass it explicit when they specify it.

Something else?
------------------

Neither of the above options is great. It could be argued that a better answer is to avoid the overhead that arises when users pass them via a root/push constant buffer today. If curren code is written like:

```hlsl
[[vk::push_constant]] cbuffer Dims { uint3 gridDim; uint3 blockDim; }
...
void myKernel(uint3 threadIdx : SV_GroupThreadID, ...)
{
    ...
}
```

Then we could argue that it is better to express the same intent as:

```
void myKernel(
    uniform uint3 gridDim,
    uniform uint3 blockDim,
    uint3 threadIdx : SV_GroupThreadID,
    ...)
{
    ...
}
```

The latter expression is cleaner and more idiomatic for a compute programmer (we want to discourage use of the global scope where possible). If we declare by fiat that uniform entry-point parameters map to push constants on VK, then we can make this latter form semantically equivalent to the former on both VK and D3D, while also potentially giving us a path toward a more direct expression of the intent for CUDA.

**Comment by jsmall-nvidia** [comment]
The "Expose new system-value semantics" with semantics seems to be the best at communicating what is going on. 

In the last example - I'm assuming the intent is on CUDA they will be the built in variables, and not passed. Having the semantic makes it clear that at least on some targets something 'special' is happening. Having uniform entry point parameters map to push constants seems reasonable. Does that mean these values are added to a [[vk::push_constant]] marked struct, or it's one or the other?

**Comment by csyonghe** [comment]
We have platform specific `cudaThreadIdx()` `cudaBlockIdx()` and `cudaBlockDim()` for now. This is not cross-platform, but useful as a workaround when user needs it.
