### ISSUE TITLE
Move KernelContext wrapping form emit to IR

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#1422]
Introduction
========

Right now the emit logic for CPU and CUDA C++ handles the issue of global shader parameters by wrapping all the code it emits for a program inside the body of a global "context" type.

To a first approximation, we take input HLSL like the following:

```hlsl
RWStructuredBuffer<Stuff> gStuff;
...
void someFunc() { let s = gStuff[...]; ... }
...
[shader("compute")]
void myKernel() { ... }
```

and transform it into something like the following:

```c++
struct KernelContext
{
    RWStructuredBuffer<Stuff> gStuff;
    ...
    void someFunc() { let s = gStuff[...]; ... }
    ...
    void myKernel() { ... }
}
extern "C" void myKernel(void* uniformData)
{
    ((KernelContext*) uniformData)->myKernel();
}
```

Using the context as a wrapper type means that ordinary functions can access things that were declared at global scope in the input HLSL (e.g., `gStuff` in this example) without those being global variables in the output CPU/CUDA C++ (since those platforms use global variables for *globals* instead of *parameters*). Then we have a single global function that is exposed externally that dispatches into the member-function-ified world.

Problems
======

Code Complexity
-------------------

Emitting things into a `KernelContext` type complicates the emit logic in a few places (e.g., when dealing with access to things that used to be global uniforms, the result isn't as simple as I had made it out to be).

Performance
--------------

When emitting code for CUDA, the entire `KernelContext` is passed around as a pointer to global memory, and all the "top-level" shader parameters are accessed through that pointer. This adds a level of indirection through global memory on top of what a more traditional CUDA translation would look like (e.g., with `gStuff` being a parameter to the kernel function itself).

Modularity
------------

An important issue with the `KernelContext` type here is that it cannot by synthesized until we know about *all* of the global-scope shader parameters that are linked into a program. This has a few consequences:

* First, we cannot emit CPU/CUDA code for a linked program and its kernels until things are fully linked; there is no (easy) way to support separate compilation in this model

* Second, because different linked programs will yield different `KernelContext` types, there is no way to re-use compilation results or subroutines across programs with different global parameters.

Interoperability
-----------------

A final issue with the `KernelContext` approach (strongly related to the previous one) is that if a module of Slang code defines a subroutine that is "just a function," then that function cannot be exposed with linkage and then called from code written in another language (e.g., linking Slang-generated CUDA C++ with hand-written CUDA C++), because the generated code for a subroutine like `someFunc()` above is not just a global C/C++ function, but rather a member function of a type with very specific layout constraints.

Proposed Solution
============

The solution I'm going to propose has a two pieces that together try to address the full problem space.

Introduce the context in an explicit IR pass
----------------------------------------------

Rather than make the introduction of `KernelContext` be the responsibility of the emit logic, we should have an explicit IR pass that captures the global shader parameters into a `struct` and then threads it through all the functions in a linked program. The emit logic will then be able to emit the contents of an IR module more directly, so that global-scope functions in the IR become global-scope functions in the output. This change should directly address the code-complexity problems in the emit logic.

In addition, we can make the explicit context parameter that is introduced by the IR be a by-value parameter instead of a pointer (at least for CUDA), so that it can more easily be promoted to registers rather than being accessed via global memory loads.

Skip introducing the context parameter if no global parameters are used
--------------------------------------------------------------------------------

Our experience has taught us again and again that global-scope shader parameters in HLSL are anti-modular, and many of our goals around modularity and interoperability are best achieved in the case where there are no global parameters to contend with.

We should make sure that in the specific case where there are no global parameters involved in a compile (including the case where a module is being separately compiled), we can generate code that doesn't include the implicit context parameter at all, so that the signatures of functions don't have to change.

We can either have this be an all-or-nothing check (if there are any global parameters, then introduce a context for them; otherwise don't) or something at the granularity of individual functions (if a given function accesses a global parameter, add the context parameter to it, and repeat for any functions that call it). Each of those options involves trade-offs.

Note that if programmers rewrite their code to not depend on global shader parameters (as we'd like to encourage) then they automatically end up in this space where there is no explicit content parameter (and there can therefore be no performance questions around it).

**Comment by jsmall-nvidia** [comment]
There still might be difficulties around functions that are exposed (say as part of heterogeneous effort) - the problem being knowing what the calling signature is. If the function or anything it *can* call has access to these variables then they need this struct, passed in. That the requirement would need to be exposed in reflection presumably. 

Not having global variables and having to be explicitly pass would avoid a lot of this mess. On the other hand global variables are useful (I don't have to pass loads of parameters, or wrap up in structs). That there is modularity in having globals too as it allows state to be an implementation detail.

**Comment by tfoleyNV** [comment]
The kernel context wrapping was moved to an IR pass in #1440.
