### ISSUE TITLE
Policy for entry-point uniform parameters when targeting SPIR-V

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1423]
Background
========

Slang allows for uniform shader parameters to be specified either at global scope or entry-point scope.

A programmer might write something like:

```hlsl
struct Stuff { float4 f; }
ConstantBuffer<Stuff> stuff;
Texture2D t;

void myShader() { ... }
```

They can instead write the following using `uniform` entry-point parameters:

```hlsl
void myShader(
    uniform Stuff stuff,
    uniform Texture2D t)
{ ... }
```

The resulting code more narrowly scopes access to the parameters to where they are needed, eliminating a lot of potential confusion when multiple entry points are placed in the same file.

Note that in this example the `stuff` parameter has changed from a `ConstantBuffer<Stuff>` to just a `Stuff`. This is because Slang supports implicitly aggregating `uniform` entry-point parameters with "ordinary" types into an implicit constant buffer (the same thing should work at global scope, but hasn't been implemented yet).

One potential concern when transforming a shader in this manner is that by losing the explicit `ConstantBuffer` we potentially lose the ability to add the `[[vk::push_constant]]` attribute:

```hlsl
[[vk::push_constant]] ConstantBuffer<Stuff> stuff;
```

Similarly, when targeting Vulkan ray tracing, we might have a constant buffer that is marked as the "shader record," again using an attribute.

Proposal
======

I would like to make our logic for binding entry-point `uniform` parameters add the following policy choice for Vulkan/SPIR-V code generation:

When an entry point has one or more `uniform` parameters of "ordinary" types, then they will be collected into a `struct` and

* If the entry point is for a ray-tracing stage, that `struct` will be used to define the shader record for the entry point
* Otherwise, that struct will be used to define a push-constant buffer for the entry point

Discussion
=======

The intention of this choice is to make the default behavior be the most desirable one. If you are defining a Vulkan compute shader using a bunch of `uniform` parameters, then you probably want all those to be passed via push constants by default. Similarly, for a ray-tracing shader you probably want those parameters to sit in the shader record rather than be indirected into a buffer.

In each case, the user can override this default behavior very easily and explicitly:

```hlsl
void myShader(
    uniform ConstantBuffer<Stuff> stuff, // explicitly request indirection
    ...)
{ ... }
```

The only users who could be adversely impacted by this policy change would be users who:

1. Are heavily using entry-point `uniform` parameters of "ordinary" type
2. Are using Vulkan
3. Have deeply baked in the assumption that those parameters are passed via an ordinary constant buffer

I am not aware of any current Slang users who meet the first criterion.

**Comment by csyonghe** [comment]
I don't have a strong opinion on this, and the proposal seems reasonable to me. I doubt any existing users would sense the change, but It could be useful to expose a compiler flag to specify the behavior.

**Comment by tfoleyNV** [comment]
The bar for adding a new compiler flag to control behavior like this should be pretty high. The risk is that the number of de facto language dialects rises exponentially with the number of flags, which complicates both testing and reproducing customer issues.

In this case, I don't think any existing users will be affected, the new behavior seems like the best possible default, and it will be trivial for users who don't like that default to write code that gives the behavior they want.

**Comment by natduca** [comment]
Think this is done
