### ISSUE TITLE
Don't translate HLSL/Slang `const` to GLSL `const`

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#145]
Most uses of `const` in GLSL code mean something close to C++ `constexpr`, while HLSL/Slang `const` is supposed to mean something closer to C/C++ `const` ("this variable is immutable"). Right now Slang translates uses of `const` in HLSL/Slang code over to GLSL `const`, which doesn't seem right.

My understanding of the GLSL spec is that since version 4.20, it is okay to have a `const` variable with an initializer that is not a compile-time constant (or a `const` function parameter, etc.) and that this means something close to the C `const` semantics. However, on code that had used `const` pervasively. we saw issues when blinding translating that over to GLSL `const` (on a single target platform - see #144).

In any case, Slang should be better about this, and recognize that the `const` keyword means very different things in the different input/output languages we have to deal with. They should not all be represented by the same modifier class.

**Comment by tfoleyNV** [comment]
This issue should be resolved once cross-compilation is entirely based on the IR, since we would then only output an AST again if we are in "rewrite" mode.

**Comment by tangent-vector** [comment]
Closing this since the IR will hopefully make it a non-issue.
