### ISSUE TITLE
Move "access" for texture/buffer types into the type system

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1484]
HLSL has a bunch of similar declarations for buffer/texture types that only differ in a prefix that marks how they are to be accessed. E.g., we have both `StructuredBuffer<T>` and `RWStructuredBuffer<T>`

Right now we model these families of types as being unrelated, but there are times where a user wants to be able to abstract over the choice of read-only vs. read-write types. One option is to declare a common interface (e.g., `IStructuredBuffer<T>`) that both `StructuredBuffer<T>` and `RWStructuredBuffer<T>` conform to.

The interface-based approach makes some sense, but requires people to write a generic function when intuitively they might just want to write a function that takes a `StructuredBuffer<X>` and call it with either a read-only or read-write buffer. What the user intuitively wants is that `RWStructuredBuffer<T>` is a subtype of `StructuredBuffer<T>`.

A more implementation-oriented issue is that the type hierarchies for the buffer and texture types repeat this pattern of prefixing in several places, so we have a cross-produce space `{, RW, RasterizerOrdered, Append, Consume}{Texture2D, StructuredBuffer, ...}` and sometimes we want to abstract over all resources with the same "shape" and other times over all resources with the same "access," but the AST `Type` hierarchy can only enshrine one or the other as the primary decomposition.

A counterpoint here is the Metal shading language, where there is a single type for 2D textures, which is instead parameterized (via templates) on an access level:

```c++
enum class access { sample, read, write, read_write };
struct texture2d<T, access a = access::sample> { ... };
```

Thus a simple `texture2d<float4>` is by default given the `sample` access level and corresponds to an HLSL `Texture2D<float4>`, while a `texture2D<float4, access::read_write>` corresponds to an HLSL `RWTexture2D<float4>`.

Given that Slang supports generics with value parameters, we could implement something very similar:

```hlsl
typedef int Access;
static const Access kAccess_Sample = 0;
...
struct Texture2D<T, let access : Access = kAccess_Sample> { ... }

typealias RWTexture2D<T> = Texture2D<T, kAccess_ReadWrite>;
```

Ignoring some ugly syntax details there, such an approach recreates the same basic idea as the Metal SL equivalent. Under that model, we could change the `RW`, `RasterizerOrdered`, etc. variants of most texture/buffer types into helper `typealias` declarations. Because all 2D textures would share a single type declaration, it would be possible to write code that is abstracts over `Texture2D<T,A>` for all `A`.

(To make the above approach work, we'd need to use `extension` declarations to add all the methods appropriate to texture types based on their access. Doing all this for buffers first might prove much easier.)

Using an explicit generic parameter to convey the access level of a texture or other resource type would remove the need to use the "extra" bits in the "magic type" encoding for this, and could simplify our modelling of stdlib types.

Just using a generic value parameter doesn't give us the desired subtyping relationship though: we can't cast a `RWStructuredBuffer<X>` to a `StructuredBuffer<X>`. To get that step to work, we'd need to model the access levels as types that have a subtyping relationship:

```hlsl
interface IBufferAccess {]
struct kBufferAccess_Read : IBufferAccess {}
struct kBufferAccess_ReadWrite : kBufferAccess_Read {}

struct StructuredBuffer<T, in Access : IBufferAccess = kBufferAccess_Read> { ... }
```

In this case the access is a type parameter, and we are using the `in` modifier in the same way that C# does, to indicate that it is a covariant type parameter (so if `X` is a subtype of `Y`, then `StructuredBuffer<..., X>` is a subtype of `StructuredBuffer<..., Y>`).

Adding covariance support in this way would achieve many of the same benefits as the value-based approach, but also enables the subtyping relationship that users expect. Using the subtyping relationship would create extra burdens on the IR an emit logic, though, in that we'd have to specialize called functions to have both `RW` and read-only variants, if they were declared using the read-only type but then called with the `RW` type.

In the limit, we could also decide to encode the "shape" of texture types as generic parameters, so that we can fully abstract over textures (both in user code an in the AST/IR):

```hlsl
interface ITextureShape { associatedtype Coords; }
struct TextureShape_2D : ITextureShape { typealias Coords = float2; }
...
struct Texture<T, S : ITextureShape, A : ITextureAccess> { ... }
```

One nice benefit of a definition like this is that there would be only a single base texture type in the AST `Type` hierarchy (same for the IR). When new kinds of texture shape or access come out, we could just add the relevant shape/access types to the stdlib, add the ops appropriate to those cases in `extension`s, and be done.

Of course all of the above is greatly over-simplifying. I mostly wanted to write this out so that we have it documented for later in case we decide to go in this direction.

**Comment by csyonghe** [comment]
Fixed.
