### ISSUE TITLE
Fix lookup for enum "tag type"

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1491]
A declaration like:

```hlsl
enum Flavor : uint { Chocolate, Other }
```

is supposed to introduce an `enum` type `Flavor` with a "tag type" of `uint`.

Parsing and semantic checking for that feature is largely implemented, but users who try it out have been running into problems.

The root cause of the problems seems to be that our name lookup process will treat the `InheritanceDecl` that represents `Flavor : uint` like any other inheritance relationship, so that `Flavor` ends up inheriting all the members of `uint`. This is explicitly *not* what a "tag type" for an `enum` should do, and it also leads to errors when trying to convert `uint` values to the `enum` type, because there ends up being an apparent ambiguity between the `init(uint)` already defined in `uint`, vs. the `init(uint)` defined for `enum` types.

The simplest fix is probably to define a `Modifier` that we can attach to `InheritanceDecl`s to indicate that lookup should ignore them, and then to attach that modifier to the "tag type" inheritance clause for `enum`  types at an early part of semantic checking.

**Comment by natduca** [comment]
Fixed
