### ISSUE TITLE
Support reentrant/multithreaded use

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#150]
Currently Slang has a few global variables that really need to be stored on the session. Moving these into per-session storage should enable a user to have one session per thread.

Ideally we'd be able to use the same session across multiple threads, and only require that a particular compile request be locked to a thread, but that is harder to achieve with the current design, because we end up with reference-counted pointers from per-request data to per-session data.

We could "fix" that by making the reference-counted pointers use atomics, but that would slow down the 99% case. The right long-term fix is to not use "smart" pointers for that stuff.

For now, it is easiest to support one session per thread.

**Comment by tfoleyNV** [comment]
Usage of global variables has been removed in #153, so basic usage of Slang from multiple threads should now be possible. Each thread still needs to use its own `SlangSession`, though, which could slow things down a lot if clients aren't careful.

I'm going to close this issue for now, while recognizing that the larger technical-debt issue remains.
