### ISSUE TITLE
Support a binary output that includes reflection data

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#151]
Right now the command-line tool can be used to create binaries, but these don't include all our reflection information.

For Falcor use cases, it would be good to support offline compiles that output binary code and reflection data.

This needs some design consideration, and probably overlaps with any kind of separate compilation support we might add.

**Comment by tfoleyNV** [comment]
The compiler supports a "bytecode" format at this point, although there is plenty of work still to be done on it. 

This specific issue doesn't make sense to keep around.
