### ISSUE TITLE
Shader debugging in PIX

### ISSUE THREAD

**Issue by TheGoozah** [shader-slang/slang#1628]
Hi,

At this moment I am using the Nvidia Falcor Framework, which uses slang. Not sure if I am missing something, but I didn't find a way to generate .pdb files of the compiled slang shader files, to be able to perform shader debugging in PIX. Is this something that is not supported by the slang library?

Thank you in advance!

**Comment by csyonghe** [comment]
We support specifying `DebugInfoType` now. By default we will invoke dxc with `-Zi` option to enable debug symbols.
