### ISSUE TITLE
cpu hello world

### ISSUE THREAD

**Issue by ib00** [shader-slang/slang#1630]
I try to run cpu-hello-world example on Mac OSX. It compiles,
but get the following error:

(0): error 52002: Could not find a suitable pass-through compiler for 'Unknown'.

**Comment by tangent-vector** [comment]
Thanks for letting us know about this issue. Unfortunately, MacOS isn't currently a plaform we officialy support right now. We'd like to change that eventually, and contributions in that direction would be welcome.

Currently our compilation to CPU code is done by generating C++ code and then compiling it to a shared library using an installed C++ compiler on the machine (gcc or clang for Unix-derived platforms). It is likely that the logic we use for detecting an installed compiler is not working correctly on MacOS.

The fact that the error message prints `Unknown` is seemingly another issue.
