### ISSUE TITLE
Support Sample instructions with lodClamp

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#1710]
I'm trying to use the `SampleGrad` variant that accepts the lod-clamp argument [(see here)](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/samplegrad-s-float-float-float-int-float-).

Slang doesn't appear to support this - 
![image](https://user-images.githubusercontent.com/17769755/108109133-5b7ef280-7046-11eb-9ce3-8dd61304bbe5.png)

**Comment by nbentyNV** [comment]
The GLSL equivalents are in https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_sparse_texture_clamp.txt

**Comment by tfoleyNV** [comment]
This problem should be fixed (for `SampleGrad()`) in `v0.18.10`.

If other `Sample*()` operations need support for lod-clamp, then please open a new issue to track the additional overloads needed.
