### ISSUE TITLE
Add support for sparse texture queries

### ISSUE THREAD

**Issue by nsubtil** [shader-slang/slang#1712]
It's often useful for debugging to have access to info on whether a sparse texture fetch landed on an unmapped page.

HLSL does this using variants of Sample* functions that return an opaque uint, which can be used with CheckAccessFullyMapped. The GLSL path would go through the various sparseTexture* functions in GL_ARB_sparse_texture2.

**Comment by csyonghe** [comment]
`CheckAccessFullyMapped` is added to stdlib.
