### ISSUE TITLE
IR: How to handle `out` and `in out` parameters?

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#182]
I'm starting to plug away at more complete IR features, and one important question I'm running into is how to encode `out` and `in out` function parameters (and corresponding arguments) in the IR.

Current Approach
-------------------

The current approach is a simple one, and probably qualifies as the first thing somebody would think of:

1. An `out` or `in out` function parameter with type `T` in the AST becomes an IR-level parameter of type `T*`
2. Code within the body of the function that references the parameter does so via loads and stores
3. A caller passes the address of a temporary for any argument that matches with an `out` or `in out` parameter

Choice (3) there is necessitated by tricky cases where an `in out` parameter might otherwise alias other storage:

```hlsl
static float someGlobal = 0;
void foo(in out float x) {
    x += 1;
    someGlobal += x;
}
void main() {
    foo(someGlobal);
    // what is the value of `someGlobal` now?
}
```

Naively treating HLSL `in out float` like C++ `float&` would yield `2` while a proper copy-in/copy-out semantics would yield `1`.

Choice (2) adds complication to optimization because naively treating `out` parameters as general pointers means that aliasing concerns can inhibit optimizations, even though we know (because of (3)) that no other inputs to the function can alias such a parameter.

We could fix up some of the issues around (2) by emitting a function prologue that allocates a temporary for `out` and `in out` parameters (with loads to initialize the temps in the `in out` case) and then an epilogue to copy from those temporaries back into the parameters. The temporaries would then be something we can clean up without needing *a priori* alias information. But at that point we are copying twice - once in the callee and once at each call site. We can potentially eliminate the call-site temporaries if we know that callees are responsible for making copies.

All told, this seems to add a lot of complexity, and most worryingly it makes `out` arguments very different from function results when it comes to optimization.

Alternatives?
--------------

The main alternative I can see is, instead of using pointers, to desugar an `out` parameter into an additional return value from a function:

```
float foo(out int x) { x = 1; return 2.0f; }
// desugars to, more or less:
Tuple<float, int> foo() { int x; x = 1; return tuple(2.0f, x); }
```

An `in out` parameter would then desugar into an ordinary (by-value, non-pointer) function parameter plus an additional output.

At some level this alternative is just a different way of codifying the copy-in/copy-out behavior described above, but it does so in a way that makes the data flow more uniform between ordinary return values and `out` parameters.

This approach seems superficially more appealing, but it also has down-sides:

* The various intrinsics (operations that map one-to-one to HLSL library functions) will probably still need to be handled as using pointer-type arguments for `out` and `in out`, or else there will be a lot of extra temporaries introduced when converting from the IR back to HLSL.

* The IR either needs to have a notion of tuple types, or a native idea of functions with multiple return values. Tuple types aren't too bad in the IR, but then we need to deal with how they translate to HLSL/GLSL. Multiple return values are harder in a simple SSA IR, but possibly have an obvious translation to HLSL/GLSL.

* Whatever we choose as the IR representation, there will need to be a conversion step to get back to HLSL/GLSL, and it is hard to imagine this step preserving much of the original look of a function written with `out` parameters, so producing debuggable output may be harder.

**Comment by tfoleyNV** [comment]
The current IR implementation makes the following decisions about the representation of `out` and `in out`:

- The argument appears as a pointer at the IR level, but we have specialized subclasses of `PtrType` that are intended to capture the semantics of "a pointer that only exists to implement an `out` or `in out` parameter"

- We *always* use a fresh temporary at call sites for the argument to an `out` or `in out` parameter, with copy-in or copy-out as needed.

- We *never* create a local temporary to store the parameter value, because we assume that the above transformation was made at call sites.

When it comes time to actually do SSA generation, we'll need to take these decisions into account, because they mean we can assume that the pointers for `out` and `in out` parameters cannot alias any other locations.

I'm going to close this issue for now, since there is a design in place, even if it isn't perfect.

**Comment by devshgraphicsprogramming** [comment]
Is there a proper way to "pass by reference" in GLSL?

Really gets in the way of modularising my GLSL code, since every function runs the potential risk of grinding my shader to halt (especially if SSBO value/struct becomes an `in` parameter).

**Comment by tfoleyNV** [comment]
> Is there a proper way to "pass by reference" in GLSL?

If you actually mean in GLSL, then the answer is "no," unless you are ready to consider something like `VK_buffer_device_address`. The workaround in the GLSL case would be to pass down an index and then fetch from the SSBO inside the callee function (which means you need a different copy of the callee function for each global SSBO you want to use it with).

If you mean in Slang, when targetting GLSL, the answer is currently "no," but we'd like to eventually handle this as an optimization we apply when generating GLSL output.

Right now when using Slang to target GLSL you could write a function like:

```
void doSomething(RWStructuredBuffer<Foo> foos, int index)
{
    ... use foo[index] here
}
```

and when we generate output GLSL you will find that you end up with a distinct copy of `doSomething()` for each distinct global `RWStructuredBuffer` that gets passed in (that is, the Slang compiler does some of the boilerplate expansion that GLSL makes you do by hand).

In the long run we'd like to support it so that if you write:

```
void doSomething(Foo foo) { ... }
```

and then call it like:

```
RWStructuredBuffer<Foo> gFoos;
...
doSomething(gFoos[someIndex]);
```

we would automatically create a specialized version of `doSomething` in GLSL that doesn't take the `Foo` as an `in` parameter and instead references `gFoo` directly in the function body.

I believe that such an optimization would be enough for the 99% case of what most users want, but if there ends up being a lot of demand for something that is more like real by-reference parameter passing, we might consider it.
