### ISSUE TITLE
Downstream Option Mechanism

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1847]
Downstream Option Mechanism
====================

During a Slang compilation work may be performed by multiple other stages including downstream compilers and linkers. It isn't possible in general or perhaps even desirable to provide Slang equivalents of every option available at every stage of compilation. It is useful to be able to set options specific to a particular complation stage - to alter code generation, linkage and other options. 

## Prior art

The [gcc toolchain](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html) has a somewhat analagous issue around passing options to the downstream linker. The solution used there is 

```
-Xlinker option
```

The mechanism requires -Xlinker to be used in front of every option. If an option and value are separate it requires two -Xlinker options. 

```
-Xlinker someOption -Xlinker someOptionsValue
```

It suggests using the `=` style setting which makes the setting a parameter somewhat less painful.

```
-Xlinker -someOption=someOptionValue
```

This is an improvement. Unfortunately Slang command line processing does not currently support = style.

Gcc also has the `-Wl` option which allows a comma-separated list of tokens to be passed to the linked.  

> Pass option as an option to the linker. If option contains commas, it is split into multiple options at the commas. You can use this syntax to pass an argument to the option. For example, -Wl,-Map,output.map passes -Map output.map to the linker. When using the GNU linker, you can also get the same effect with -Wl,-Map=output.map. 

The option presumably exists to work around the verbosity of having to write every option with the preceeding `-Xlinker`. A nice property of the `-Xlinker` style is that it's pretty clear what's going on. It also allows for easy extension around other kinds of downstream tools by having different names other than `linker`.  

(Clang)[https://clang.llvm.org/docs/ClangCommandLineReference.html#linker-flags] is similar but we also have `--for-linker`.

```
-X
-Xlinker <arg>, --for-linker <arg>, --for-linker=<arg>
```

If there are multiple options using this mechanism could get somewhat monotonous. You could imagine an extension such that all of the parameters up to the next '-X' are taken to go to the target so the above option would become

```
-Xlinker -someOption someOptionValue
```

That an empty `-X` could be used to indicate return to normal command line processing. This is somewhat appealing except the behavior deviates from the -X in gcc/clang, so the additional behavior needs to be a slightly different mechanism. 

Discussion
==========

In the Slang scenario it could be argued that there were more 'stages' than just linking.

* Source generation 
* Source compilation (typically but not necessarily) via a downstream compiler
* Assembly generation
* Linking 

There is a desire that it be possible to compile to many targets in a single invocation. Even if this wasn't the case it could be argued useful to be able to target specific options for stages of compilation even if those stages are not invoked, because the options then only need to specified once. 

This being the case we probably want a mechanism to be able to target options for specific stages. For example

```
-Xfxc someFxcOption
```

That the Slang front end will not perform any parsing of these options. 

# Parsing

Some downstream tools might may have command line parsing, but the way that Slang interfaces with them that command line parsing isn't available - for example GLSLANG doesn't have a command line parsing interface via our shared library interface. There is GLSLANG (command line interface)[https://github.com/KhronosGroup/glslang/blob/master/StandAlone/StandAlone.cpp] implementation though.  

There may be work to implement downstream command line option parsing to make them available and targettable through the mechanism. It may be useful to look at some downstream compiler implementations to see if their native command line parsing can be used as is in some way. Looking at GLSLANGs implementation it doesn't seem it's in a form that is directly usable because of the use of global variables. 

# Overlapping options

Slang may have options that are also available via regular Slang command line parameters to downstream compilers. What should happen if these values supplied to Slang and the downstream option are inconsistent? Is it necessary to implement parsing for a downstream compiler to access an option that is already available through a standard Slang option?

The simplest solution in the short term is to *only* allow settings via the Slang options to be set that way, and not to put in any effort into repeating functionality into downstream compiler functionality. Doing so is less effort, but also removes an ambiguity around the inconsistency.

A perhaps more subtle scenario is where an option is not explicitly set on the Slang side, but is on the downstream options. Again here we probably have to go with an option not explicitly set is *implicitly* set, and that implicit option should be the one used. 

Some options perhaps shouldn't be considered as a single setting. Take for example macro definitions. They can be set via multiple options on a command line. Additionally it is easy to imagine scenarios where adding some macro definitions for a particular downstream compiler could be quite useful. It could also provide a mechanism to control options in downstream compiler prelude for example. 

There is perhaps another scenario - where we want to set some setting for a downstream compiler using the *Slang* standardized options. This is probably something useful to support and implies that we would potentially allow Slang command line parsing on command lines that were for downstream compilers. The problem now is that it needs to be unambigous to the downstream compiler that that is the case. 

Yet another scenario is that some options are 'generated' as part of a compilation. Take for example the shader model for CUDA - on performing a compilation of Slang source, intrinsics indicate what CUDA SM is required. If we are compiling in the pass through mode - then this isn't possible, and the user will need to be able to specify what shader model they want. If this is implemented (currently it's possible that it's not possible to set SM from Slang command line) then there is the potential for a clash. Do we want the slang command line option to override the the one determined by compiling the source? Should the higher value be taken? 

We have the capability system as a mechanism to be able to indicate if a specific capability is required - allowing a use of a feature that is only on available on a later shader model. Should this mechanism work for pass through mode?

# Other tools

With the render test tool there is a similar issue - that sometimes we want to specify options to the *tool* and other options to some system (often Slang) that will be used in the test. 

Ideally any mechanism we use would work well in this scenario also. 

# Other issues

Slang does not support a mechanism to document command line options as part of the runtime. 

With extra downstream options it would seem to be beneficial to be able to document them - especially if they are somehow different from the downstream tools usage, or there is no equivalent on a downstream tool. 

Options could documented via `.md` files - but as can be seen with the slang command line options documentation this generally means not all options are covered or covered completely. 

# Multiple parameter syntax

For supporting multiple parameters the syntax, one option might be `-X-` 

An example in use might be... 

```
slang file -X-fxc -O3 -DFXC -X -Iinclude
```

The idea here is to make it distinct but a kind of an extension to the standard mechanism. That it is still possible to use the `-Xfxc` for a single arg. The list can be terminated by the next -X. There is perhaps an open question about how to support parsing -X to a downstream compiler (say with -Xlinker). Or perhaps it can only be terminated via `-X-`. This would allow -Xlinker to be passed appropriately.

Another style might be `-Xfxc...`

The idea here is to use the -X syntax but use a trailing ellipsis to indicate that multiple arguments after the -X will be passed to the named item.

We could indicate the end with 

* `-X...` - the idea is to keep similar syntax, but this seems to indicate an *ongoing* ellipsis
* `-Xend` - perhaps clearer. Perhaps we allow `-Xfxc-start` instead of or as well as?
* `-X.` - just the dot is indicate the 'end'. Allows other -X to go through to downstream

Some examples of the options

```
// Ellipsis style
slang file -Xfxc... -O3 -DFXC -X. -Iinclude -Xdxc... -DDXC -Invapi
// Start end style
slang file -Xfxc-start -O -DFXC -Xend -Iinclude -Xdxc-start -DDXC -Invapi
// Dash style
slang file -X-fxc -O -DFXC -X- -Iinclude  -X-dxc -DDXC -Invapi
```

Proposal
========

* Support the `-Xthing` mechanism for sending parameters to downstream tools
** `thing` can be the names of downstream tools, and we can have some standardized names such as `linker`, `downstream`, `slang`, `cpp` (say for any downstream C++ compiler) etc.
* Make the render-tool support the same mechanism/s (it seems to currently seems to support `-xslang`)
* Support multiple listed arguments (some discussion on style below)
* Support a mechanism to use Slang style argument parsing for downstream compilers (where appropriate) - this is probably the case but should be confirmed
* We report a warning for any named downstream entity that is unknown. Those parameters will be discarded. 
* Parameters are *ignored* without warning if the downstream entity isn't used in a compilation.
* If there are params that are passed to downstream compiler in a way that is incompatible with Slang command line parsing, if it is a desired parameter, it will be made available in a way close to the original mechanism but in a compatible way.

In terms of initial work - downstream compilers command line parsing will only be supported when there is a user need. In general we should prefer options that are part of the Slang option processing. Such options must also be honored by the pass though mode. 

# Future work

* Use SourceLoc/SourceManager mechanism 
** Provides a mechanism to support other languages
** Provides a standard mechanism to provide parameters to a message
** Provides a mechanism to highlight visibly where the issue is on a command line
* Add support for the `--param=` and `-param=` styles 
* Command line parsing toolkit/framework
* Runtime documentation
* Mechanism to produce offline documentation

**Comment by tfoleyNV** [comment]
IIUC, both glslang and fxc have the problem that users think of them as having specific command-line options, but our current compiler code can't easily emulate the parsing of those options.

Given that we are building glslang from source, it is reasonable to expect that we could eventually update the `slang-glslang` shared library interface to include additional string options and then parse those using the same logic as the command-line `glslangValidator` executable would use.

For fxc, we have the harder issue that there isn't (to my knoweldge) any programmatic interface that can be used to parse command-line arguments in a way that matches command-line `fxc.exe` and then feed them to `D3DCompile`. I expect that in practice we'd need to implement that options parsing by hand, and that it could be complicated by the way that `fxc.exe` uses traditional DOS/Windows style option syntax (e.g., `/h` for help instead of `-h` or similar).
