### ISSUE TITLE
Standardizing Types

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1883]
The following is based on a conversion with @tfoleyNV, @csyonghe and @jsmall-nvidia. There are perhaps two aspects - the types to use in C++ code and perhaps how that applies to the Slang language. Here the main thrust is around C++ code. In Slang code we can define types that match the behavior without worrying about distinguishing from built in C++ types (ie `int` in Slang language can be equivalent to `Int`/`SlangInt`).

Desirable basic features are

* Integer types are *signed* by default
* Standardized names for common uses to distinguish use
* Unsigned types prefixed with U
* Types defined in Slang namespace, and aliased with Slang prefix in global namespace

So something like...

```
namespace Slang {

typedef int32_t Int;
typedef uint32_t UInt;
typedef Int Count;
typedef Int Index;
typedef int64_t FileSize;
// etc...

} // Slang

typedef Slang::Int SlangInt;
typedef Slang::UInt SlangUInt;
typedef Slang::Count SlangCount;
typedef Slang::Index SlangIndex;
typedef Slang::FileSize SlangFileSize;
// etc...

```

That within the Slang codebase/API the non prefixed types should generally be used - this is arguably more readable and requires less typing. When not in Slang namespace, using the prefixed style is reasonable.

For other fixed size types in C++ code we can use `uint8_t`, `int16_t` etc as necessary.

# Names

* Int - general integer. Is `int32_t` 
* Size - integer size of an amount of bytes `intptr_t` 
* Offset - integer size of a difference in an amount of bytes (Size)
* Index - index into an array. (Int)
* Count - integer amount items in a container (such as Array/List/Map etc) (Int)
* FileSize - the size of file on the file system (`int64_t`)

# Unsigned types

* UInt - general unsigned integer. Is `uint32_t`.
* USize - unsigned memory size. `size_t`
* UFileSize - unsigned file size. `uint64_t`

# Int/UInt 

UInt and Int are defined above as 32 bit sized types - `int32_t` and `uint32_t`. This is probably fine and it matches GPU usage. 

It is probably unwise to write code *assuming* they are and always will be 32 bit. Whilst for current CPU targets making them 32 bit is sensible - for performance of operations and reducing memory footprint - it may not always be the case. In the future it may be the case that 64 bit types on some CPUs might be significantly faster. This has been *very* significant in some previous processors and has had a small effect in some current generation CPUs.

For a particular target this difference may not matter much - the size will be different and the API will reflect this. For systems that span across targets - like serialization - it *is* important if the serialization is desired to work cross platform. If a specific size integer is needed it should be *explicitly* specified. 

`Int` and `UInt` shouldn't be assumed to always be 32 bit.

# Char

`char` is somewhat problematic - in that it is typically 8 bits (although it doesn't have to be in the standard), it's signedness is implementation dependent. That a `character` in unicode is a code point, and probably wants to be 32 bit.

We could define `Char` as signed 8 bit character. `UChar` is unsigned 8 bit character. `Char32` as `int32_t` and Char16 as `int16_t`. 

How should we handle utf8? Does `Cha`r imply ascii? Should we have `Utf8` or `UtfChar8` or `CharUtf8` or `Utf8Char`. Or?

Also note that `char` has special meaning in C++ around aliasing. So perhaps we also want `Byte` and `UByte`. They make it clear these aren't 'characters', and should be used for for these kinds of scenarios. It's not 100% clear if `uint8_t` and `int8_t` are guaranteed to have the special aliasing behavior. If they do they could be used instead. Using `Byte` perhaps is preferable in that it conveys that these shouldn't be interpreted as integer values - it's a sequence of `Byte`s.

So as a suggestion...

### For (whole) characters

* `Char`/`UChar` - 8 bit char (ASCII)
* `Char32`/`UChar32` 32 bit char 

### For Utf encodings 

* `Utf8` - Single 8 bit value of a Utf8 encoding. 
* `Utf16` - Single 16 bit value of a Utf16 encoding.

### For bytes and byte streams

* `Byte`/`UByte` - 8 bit - will honor aliasing

## Questions

* Do we have native integer types?

C# has `nint` and `nuint`.

Which would be `NInt` and `NUInt` if we follow the general convention. I suppose if you wanted this one can just use `int` and `unsigned int` and there is nothing to define. This is perhaps fine for C++ but we might want a native integer type in the Slang language. 

You could argue `nint`/`unint` is preferable as in `natural int` and `unsigned natural int`, fits more closely with the design above.

If we want to match with Slang language having `nint`/`unint` then we probably should define for Slang codebase. 

* Int/Count/Index are all the same size, why not just have Int?

That it is supposed to convey in the code what something is to be used for, without the need of a comment. It additionally means that one *could* alter one and not the other if necessary. That is arguably not a desirable situation though.

There is no type enforcement around these uses, so that using `Count` or `Index` a programmer if free to convert to `Int` and back in a calculation as appropriate. That the usage is really by convention. 

* What about unsigned versions of the other types?

If we are pretty sure `Int`/`Index`/`Count` are always going to be the same size, then we can cast to `UInt` and back. So we don't need `UCount`, `UIndex` etc. `Offset` and `Size` can cast to `USize` without loss. 

* Do we need `Offset`?

In principal no because `Size` is signed so typically they will be the same type. C++ does make the distinction with `ptrdiff_t` and `ssize_t`

[Difference between ssize_t and ptrdiff_t](https://stackoverflow.com/questions/8649018/what-is-the-difference-between-ssize-t-and-ptrdiff-t) has some interesting observations. That it claims 

> In other words, ssize_t is signed, but the set of negative values it can represent may be limited to just {-1}.

Is that what we mean by `Size`? My guess is probably not. So perhaps `Size` is really best as `intptr_t`. Or perhaps more specifically it a signed integer with the same size as `USize` which is well defined. 
 
This being the case `Offset` is akin to `Index`/`Count` in that it's main purpose is to convey usage - as it will be the same as `Size`. 
 
* Undefined behavior

Presumably signed types have (at least on some targets) undefined behavior in overflow/underflow.

Moreover unsigned types should have defined twos compliment wrap around behavior.

**Comment by tangent-vector** [comment]
Update: we have been having some discussion about this issue as there is desire to get these types right for the GFX API sooner rather than later.

The above proposal is sound and should still work as our guidelines, but based on the discussion for GFX, I am inclined to go with the "native int" concept (in the sense of making our `Index`, etc. just map to the C `int` type) rather than specifically binding to `int32_t`. This choice won't affect anything in practice on the main CPU targets we focus on (Windows and Linux x86-64), and it would seem more in keeping with Principle of Least Surprise for users of our API(s) who traffic in "ordinary" `int`s.

I am inclined to say that we should still have `slang::Int` and `slang::UInt` as `typedef`s, even if they just map to `int` and `unsigned int`, since that will make it easier for us to change our minds down the line if ever needed.

One detail worth noting is that for right now, the Slang language itself has been mapping its `int` type over to `int32_t` directly, and thus giving a guarantee that a Slang `int` is 32-bit. I am inclined to say that we will eventually want the `int` type in a `.slang` source file to map to a `slang::Int` in all cases, whether or not that results in a 32-bit value. This would call for us to have an explicit 32-bit integer type in the Slang language eventually.

**Comment by natduca** [comment]
Bankrupcy, can re-create when customer use case appears.
