### ISSUE TITLE
Cross-compilation of entry points

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#19]
The initial cross-compilation goals for Slang only apply to "library" code: files full of types, functions, and *maybe* some global shader parameters. This is an intentional prioritization choice.

Longer term we'd like to support more complete cross-compilation, in which the user can just throw an HLSL or Slang file at the compiler and get back GLSL for each entry point. That is a crowded field, though, so there would be little reason for somebody to pick our tool over another. Thus it makes sense to put this on the backlog until we've got a more interesting feature set to win over users.

**Comment by tangent-vector** [comment]
This feature turned out to be needed for Falcor, so initial support is now in place. For an example, see the `cross-compile-entry-point` test.

Closing this issue because the basics are in place. Further requirements can come in as new issues.
