### ISSUE TITLE
Swift Shader support

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1900]
[Swift Shader](https://github.com/google/swiftshader) is a CPU based implementation of the Vulkan API. 

This may be useful to the slang project in several ways

* Allow Vulkan testing on CI for targets that don't have GPUs or Vulkan 
* Provide a more optimized CPU backend (with some caveats)
* Provide a way to execute CPU code without dll/shared library/C++ compiler

On the first point, I didn't seem to find anywhere where we can just grab the official binaries. I did find some unofficial places that had binaries, but they seemed rather out of date. This probably means if we want to integrate into CI, we want to build binaries and make available through the [slang-binaries](https://github.com/shader-slang/slang-binaries). To do this we probably want to have a TC project to build the binaries - although not necessary initially. We need a mechnism in gfx to be able to load the Swift Shader dll. 

On the second point - the perceived performance issue is around the CPU code produced via the C++ emit and compilation. For a variety of reasons it is unlikely that especially efficient SIMD code will be produced. One advantage of using Swift Shaders implementation is that it can more straight forwardly, produce superior SIMD optimized code. It remains to be seen if in practice the dividend is significant or at all.

 On the third point -  currently if CPU execution of Slang code is wanted C++ code must be compiled via an available C++ compiler. A C++ compiler is a fairly onerous requirement, especially if shipping a product. The compilation is typically somewhat slow as it requires compiling in a separate process. Finally if the code is to be directly executed, currently this is achieved by producing a shared/library dll. 

This all seems good - faster compilation, easier /less fragile/esoteric execution, potentially significantly faster execution. Unfortunately the problem is that because the execution requirement is vulkan, the *binding* is not documented the CPU style.

To make this work for our 'host executable' option therefore is somewhat complicated. What to reflect? How to translate the CPU bindings to Vulkan? Presumably we would use gfx vulkan implementation? Presumably that would be available through having gfx shared libraries available.

**Comment by tfoleyNV** [comment]
Thanks for writing up all this.

> To make this work for our 'host executable' option therefore is somewhat complicated.

I think this is an understatement. I would worry that trying to leverage Swift Shader as a system for CPU codegen would end up being more of a detour than a shortcut.

I think Swift Shader integration would be valuable just to get more of our Vulkan tests running under CI. That alone would justify some level of effort. If individual developers want to use that same approach as a way to run their compute shaders on CPU, then that's great. I just don't see anything practical we can do at the level of the Slang implementation/API to support/enable that without tons of compromises.

I'm still bought into the idea that an LLVM-based codegen path (plus a SIMDization pass that goes from Slang IR to Slang IR) is the Right Way forward for our CPU plans.

**Comment by csyonghe** [comment]
I agree that the generating SIMD code in our CPU backend is the more appropriate direction here.

As for selecting SwiftShader, we should include a `requestSoftwareDevice` flag/field in `IDevice::Desc` to inform the implementation what dll to load.

**Comment by csyonghe** [comment]
#1906 enables Vulkan testing on Github CI with swiftshader.
