### ISSUE TITLE
loadModule crashes on syntax error in slang file, slangc doesn't

### ISSUE THREAD

**Issue by danchia** [shader-slang/slang#1941]
I have a slang file where I accidentally used a variable `mvp` without declaring it, like so

```
  out.position = mul(mvp, float4(vertexIn.position, 1.0));
```

Compiling this slang file via `loadModule` results in an AbortCompilationException with no useful message as far as I can tell, while using `slangc` gives me a useful error:

```
.\debug.slang(18): error 30015: undefined identifier 'mvp'.
  out.position = mul(mvp, float4(vertexIn.position, 1.0));               
```

Is there a way to get similar helpful information from loadModule?

**Comment by csyonghe** [comment]
If you ignore the `AbortCompilationException` and continue execute the code until after the `loadModule` call, were you able to get any diagnostic message in the `outDiagnostics` blob?

**Comment by danchia** [comment]
I'll try and check again later, but I don't think `AbortCompilationException` is something that gets thrown across the COM boundary? It gets picked up as an uncaught except in the slang dll file.

I also am not sure where I would get it's definition, since it's not included via slang.h, and I don't thing I'm meant to include core/slang-exceptions.h

**Comment by csyonghe** [comment]
Hmm, if you see `AbortCompilationException` leaking through COM boundary then that is definitely a bug. We'll take a look at this.

**Comment by csyonghe** [comment]
I am able to confirm this issue and has fixed it in the linked PR. The fix will be available in the next release. Thanks for reporting the issue!
