### ISSUE TITLE
Direct descriptor heap indexing from SM6.6

### ISSUE THREAD

**Issue by curldivergence** [shader-slang/slang#1947]
Hello, I've been curious - is there any intention to support descriptor heap indexing by SM6.6 via `ResourceDescriptorHeap`/`SamplerDescriptorHeap` intrinsics somewhere in future? Unfortunately, I haven't found this feature on `Target Compatibility` page. Thanks!

**Comment by csyonghe** [comment]
Yes, we do intend to support. Let us know if you need it immediately so we prioritize our work on that.

The main challenge is to come up with a story for the Vulkan equivalent of this, as it would require an application level policy being made on how to supply the array of descriptors as explicit shader parameters in SPIRV.

**Comment by curldivergence** [comment]
Hi, I’m definitely interested in it, but since I’m asking about it with regard to a personal toy renderer, I don’t think it’s enough for you to reprioritize it :)
And on the same note (not to spam with another issue) - is there any kind of ETA for mesh shaders support, by any chance?
Thank you!

**Comment by csyonghe** [comment]
It is definitely on our todo list. We'll make sure to keep you updated on the progress.

I believe Slang already has Mesh shader support. If you notice any issues please let us know and we'll make sure to fix them.

**Comment by curldivergence** [comment]
>It is definitely on our todo list. We'll make sure to keep you updated on the progress.

Thanks a lot, I'd highly appreciate that :)

>I believe Slang already has Mesh shader support. If you notice any issues please let us know and we'll make sure to fix them.

Oh, I see, it just that [this page](https://github.com/shader-slang/slang/blob/master/docs/target-compatibility.md) says "No+" about mesh shader support, so probably it's worth updating? :)
