### ISSUE TITLE
CI: `ir/factorial` test randomly fails on Travis

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#198]
I haven't been able to repro this consistently, but sometimes the `ir/factorial` test fails on they Travis CI build. I need to narrow this down at some point, but VM execution path isn't currently high priority, so the bug will have to wait for when I have the cycles to spare on chasing it down.

**Comment by tangent-vector** [comment]
I haven’t seen this issue for quite a while. No reason to keep the bug sitting here, since I can re-open if we get it to repro again.
