### ISSUE TITLE
RWTexture2D<uint64_t> emits layout(r32f) for GLSL

### ISSUE THREAD

**Issue by AlexAUT** [shader-slang/slang#1997]
Example shader:
```
RWTexture2D<uint64_t> gTex;

void main()
{
    gTex[uint2(0,0)] = 1;
}
```
Command: `slangc test.slang -profile cs_6_0 -o test.glsl`

Partial Output:
```
#line 1 0
layout(r32f)
layout(binding = 0)
uniform u64image2D gTex_0;
```

I think the layout should me `r64ui` instead of `r32f`. If anyone can give me a hint where the mapping happens inside the codebase I could work on a pull request :).

**Comment by csyonghe** [comment]
Thanks @AlexAUT! I believe the related logic is in slang-emit-glsl.cpp line 450.
