### ISSUE TITLE
Reflection: validate information for varying input/output

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#20]
We do a basic job of enumerating varying inputs/outputs for GLSL, because the global-scope block declarations are just sitting there and it is hard to ignore them. I'm pretty sure we don't deal with declarations using `double` and related types correctly, so there is still work to do there.

We also walk through the varying inputs/outputs for HLSL entry points, so that we can find fragment-shader outputs and properly account for them, but I don't think we currently add any actual `TypeLayout` information for reflection to use.

A further issue is that we probably need to distinguish between general varying input/output and the specific cases of "vertex input" and "fragment output." The API here is a bit messy right now, and conventions need to be defined.

**Comment by tangent-vector** [comment]
Varying input/output definitely shows up in reflection data, and also now exposes the stage it belongs to. That is sufficient for now (we will probably need a bit more work if we tackle tessellation shaders).
