### ISSUE TITLE
Parser: generics syntax

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#201]
The current syntax for generic declarations is (intentionally) a bit ugly since it is only supposed to be used for the standard library:

```
__generic<T, let N : int = 3>
T doTheThing(vector<T,N> v) { ... }
```

That is obviously not acceptable for user-facing syntax, and the expectation of most users would be something closer to the C# approach:

```
T doTheThing<T>(T x);
```

or something using a "modern" declaration style:

```
func doTheThing<T>(T x) -> T { ... }
```

I left the non-type parameter off of those, because most existing languages with cleaned-up generics (read: not C++) don't support them, so there is no established precedent for syntax. I think the current hack of using `let` to introduce value parameters in Slang is good enough, so I don't plan to change it.

The challenge, of course, is actually implementing this syntax, especially given that we probably can't force "modern" declarations on users (they would be nice as a choice).

We need to be able to parse the return type of a function *before* we see the generic parameters, which means we don't know the names introduced in the parameter list (or which are types vs. values). We can't even reliably use contextual information from the enclosing scope, because in-scope names might get shadowed by generic parameters.

This all implies that in "Slang mode" we should use a completely context-free strategy to parse types, including their generic argument lists. This isn't too bad, given the strategy that C# demonstrates of scanning ahead and then disambiguating based on the token after the closing `>`, although our support for value parameters to generics makes things a bit trickier.

There are even more sources of ambiguity if we start allowing generic declarations to be nested in statement contexts, but we can probably ignore those issues for now.

**Comment by tfoleyNV** [comment]
PR #319 implemented this.
