### ISSUE TITLE
Getting shader stages for shader paramters

### ISSUE THREAD

**Issue by septag** [shader-slang/slang#2033]
How can I get shader stage(s) that use a particular shader parameter ? Is it possible ?
I'm writing shaders in HLSL and translate them to spirv/etc.. but when I use `VariableLayoutReflection::getStage()` it returns `SLANG_STAGE_NONE`

thanks

**Comment by csyonghe** [comment]
We currently don't support this. Would you let us know why you need this feature? We can consider support it in a future release if there are good reasons. One possible use I can think of is to set up Vulkan descriptor set where you have opportunity to specify shader stage visiblities. However we are not aware any concerete scenarios where this flag leads to actual performance differences.

Also note that Slang never removes parameters based on usage, and will ensure parameters are assigned binding indexes as if they are always referenced from all stages.

**Comment by septag** [comment]
yes. actually, like you said, I wanted it for vulkan to comply with it's explicitness and thought that would make a difference on some drivers.
if it's trivial, then please ignore this. thank you
