### ISSUE TITLE
Compile errors on linux

### ISSUE THREAD

**Issue by ib00** [shader-slang/slang#2069]
I am trying to build slang on Linux (with gcc-11.1) in release mode and I get the following error:

../../../source/slang/slang-ir.h:607:27: error: ‘this’ pointer is null [-Werror=nonnull]
  607 |         return getOperands()[index].get();

If` I use clang (version 13.0), I get the following error:

../../../source/slang/slang-emit-spirv.cpp:2512:22: error: variable 'baseArrayType' set but not used [-Werror,-Wunused-but-set-variable]
        IRArrayType* baseArrayType = nullptr;
                     ^
../../../source/slang/slang-emit-spirv.cpp:2543:22: error: variable 'baseArrayType' set but not used [-Werror,-Wunused-but-set-variable]
        IRArrayType* baseArrayType = nullptr;

**Comment by jsmall-nvidia** [comment]
Thank you for leaving this issue. It revealed a real error due to a typo in CLikeSourceEmitter. Will have a PR shortly.

**Comment by jsmall-nvidia** [comment]
Believe this is now fixed in TOT. I checked on clang and gcc 11.1.
