### ISSUE TITLE
Make "operator comma" a warning

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#2079]
A very common "beginner" mistake (that many experienced people continue to make to this day), is to assume that input shader code like:

    float3 r = (a, b, c) / 3;

is equivalent to something like:

    float3 r = float3(a, b, c) / 3;

whereas it is actually equivalent to:

    a;
    b;
    float3 r = c / 3;

The obvious culprit here is the "comma operator" inherited from C. A very simple solution to this problem would be to remove the comma operator from Slang, or to just make it a warning by default. Ideally we will have a separate feature to allow turning specific warnings into errors.

We almost certainly need a way for the user to disable that warning, because there can be valid reasons to use the comma operator in C-like code (especially when writing a code generator that emits C/HLSL/whatever). It might be possible to invest in detecting specific subsets of comma-operator usage that are likely to represent a mistake vs. cases that tend to be indicative of generated code. I don't expect we'd be able to invest in that kind of detailed pattern-matching for a first-pass warning.

One other option to consider is allowing "operator comma" in `.hlsl` files by default (perhaps still warning), while making it a hard error in `.slang` files (indicating that Slang deprecates this "legacy" HLSL feature).

**Comment by natduca** [comment]
Ergonomics/ease of use. Bankrupcy, can re-create when customer use case appears.
