### ISSUE TITLE
Broader generic value types

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2086]
Currently Slang supports int as a generic value type. Having support for 

* bool
* integral types u/int8/16/32/64_t types
* enums

Would be a good addition in adding clarity to interfaces and use sites. Not having these types can be worked around by using int values and casting in the implementation - doing so works but is not type safe, so undesirable.

If I try to use bool today I get

```HLSL
int doThing<let v : bool>(int a)
{
    if (v)
    {
        return a + 1;
    }
    else
    {
        return a * a; 
    }
}
```

> slang(62): error 39999: expression does not evaluate to a compile-time constant
>   let v = doThing<true>(tid);

Which is perhaps not a great message - as the real problem is lack of support for bool.

Also confusingly perhaps is that I can specify v is uint, but when used inside the impl it isn't.

```HLSL
int doThing<let v : uint>(int a)
{    
    let shifted = (v >> 31);
    
    if (shifted & 0x8000000)
    {
        return a + 1;
    }
    else
    {
        return a * a; 
    }
}
```

In output code v is *actually* an int, leading to incorrect behavior.

**Comment by natduca** [comment]
Bankrupcy, can re-create when customer use case appears.
