### ISSUE TITLE
Using an interface breaks type lookup in a cast

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2091]
A test that demonstrates this is in tests/experiments/generic/type-scope.slang

Take the source...

```HLSL
interface IIntegral
{
    associatedtype Unsigned;
};

struct Thing : IIntegral
{
    typedef uint Unsigned;
};

// ...
// Doesn't work
let v = (Thing::Unsigned)10;
```
This produces the error

>.slang(19): internal error 99999: unexpected condition encountered in Slang compiler: should not appear in input syntax
>    let v = (Thing::Unsigned)10;

Using . instead of :: produces the same result.

If Thing *doesn't* derive from IIntegral, the problem disappears.

The problem may be related to casting, because the following does compile

```HLSL
Thing::Unsigned b = 10;
```

**Comment by csyonghe** [comment]
This is now fixed.
