### ISSUE TITLE
Associating a Type with a Type 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2105]
Its straightforward to associate a type with a struct directly by including a typedef in the definition. Similarly for interfaces we can use associatedtype.

Here the desire is to associate a type with a type such that

* It doesn't need to be within the definition
* Usable on types that don't allow embedding (for example enums)
* Usable on built in types

We can do this with extensions 

```HLSL
extension int 
{
    typedef uint UnsignedType;
};

// Works
int.UnsignedType u = 10;

// Also works
int.UnsignedType v = (int.UnsignedType)10;
```

This works. It is perhaps somewhat worrying that *only* the name UnsignedType that identifies the 'operation'. This could clash if there are are different desired implementations for the name, perhaps across modules.

Note that having an interface define this releationship, then int.UnsignedType no longer works. This is discussed elsewhere.

**Comment by jsmall-nvidia** [comment]
@tfoleyNV observes:

There's some details and nuance worth discussing:

You talk about it maybe being useful to have an operator like GetUnsigned. We can support that by allowing for generic typealiases, which should not be a difficult addition given our current architecture:

```HLSL
typealias GetUnsigned<T : IIntegral> = T.Unsigned;

// Now I can write `GetUnsigned<int>`
```

obviously if you really want C++-ish syntax you could just do the following today and it should Just Work:

```
struct GetUnsigned<T : IIntegral>
{
    typealias Type = T.Unsigned;
}
// Now I can write GetUnsigned<int>.Type, if that makes me happy
```

The naming issue is a bigger deal.

Having extensions always dump names into the scope of the existing type isn't always what we want. But usually it is what we want. 

One thing that is important to remember is that (I think we've implemented this now...) when you are writing code, the only members that can be looked up with int.Whatever are declarations of Whatever introduced into int by the original declaration or extensions that have been imported into the current module

So if you import A  and A has extension int { ... } then, yes, you will be able to see all A might have added to int, but the hope is that they did that on purpose, and that you imported their code on purpose. What won't happen is that if A happens to do import GrossImplementationStuff and that module puts all kinds of items into the scope of int, then you code that just does import A won't see those names, because they weren't things you imported.

The big missing piece here, though, is visibility control with public/internal/etc.

It should be possible for A to have an extension int { ... } that it needs in order to get its job done, but that it doesn't want to cause pollution for clients of A.

**Comment by jsmall-nvidia** [comment]
Just a note to confirm that `GetUnsigned` did work as expected.

**Comment by csyonghe** [comment]
Closing the issue since there isn't an obvious todo item here.
