### ISSUE TITLE
Diagnose attempts to define generic value parameters without `let`

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2107]
Take the following code...

```HLSL
int doThing<V : int>(int b) { return V + b; }
```

This doesn't work because (surprisingly) V isn't determined to be a int *value*.

> .slang(3): error 39999: no overload for '+' applicable to arguments of type (typeof(V), int)
> int doThing<V : int>(int b) { return V + b; }

This can be fixed around with `let`

```Slang
int doThing<let V : int>(int b) { return V + b; }
```

Leaving aside the requirements/benefits of having let, not having let gives a confusing error message that could be improved upon.

**Comment by jsmall-nvidia** [comment]
@tfoleyNV observes:

This is a messy one. I definitely think we can at least give a good diagnostic when the user does something fishy with the current setup. The more fundamental thing is that for generic parameter, we need a way to distinguish the two cases:

* A type parameter (currently T : Whatever), where T is constrained to be a subtype of some interface/existential type Whatever
* A value parameter (currently let N : Whatever), where N is constrained to be an instance of some type Whatever

The "obvious" thing to do here is to have the compiler just allow T : Whatever and N : Whatever and then disambiguate whether a type parameter or a value parameter was meant based on whether Whatever is an interface or existential type, or a concrete type like int or MyStruct.

I will claim that the disambiguation there would be fraught, and would only get worse if/when Slang grows to support things like class types with inheritance and more traditional OOP behavior. In that case, does a parameter X : SomeType logically represent a type parameter that is constrained to be a subtype (perhaps SomeType is a class, and we wnat our generic to work with any subclass X of SomeType?), or a value parameter that is constrained to be a value of SomeType (perhaps SomeType is some kind of constexpr struct type that we are using to bundle together specialization parameters?).

C++ is able to avoid this because of some nuance:

For old-school templates, you have either int X with a type preceding the identifier, or you have class X or typename X, which make it clear that X is a type parameter. The old-school case would suggest <T : typename, N : int> where Slang currently has <T, let N : int>, so the keyword burden in C++ has just shifted from value parameters (the less common case) to type parameters (the more common case)

For concept-based templates, you have either int X or SomeConcept X. I expect this could cause some confusion because type parameters are no longer as easily distinguished visually (good naming rules could help), but this is not as big of an issue for C++ as it would be for Slang (or Rust, Swift, C#, etc.) because in C++ SomeConcept can never be a type (although I think you can use it as if it was a type in your function parameter list? so maybe it masquerades as a type sometimes?). The fact that C++ makes concepts and abstract base classes ("interfaces") be completely distinct is a pretty baked-in choice at this point, but it is telling that almost everything that has come since makes the other choice (use a single construct to express both concept-like type constraints and dynamic-dispatch-able base types).

**Comment by natduca** [comment]
QoL, lets wait for a customer to hit it
