### ISSUE TITLE
Assorted internal compiler errors

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2111]
The following are assorted internal compiler errors, based on tests in tests/experiments

generic-int-controlled.slang

> slang(28): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: could not resolve target declaration for call

built-in-extension.slang

> .slang(22): internal error 99999: unexpected condition encountered in Slang compiler: should not appear in input syntax
>    int.Unsigned v = (int.Unsigned)10;
 
byte-address-ptr.slang

> tests/current-bugs/generic/byte-address-ptr.slang(77): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: assert failure: witnessTableVal->getOp() != kIROp_StructKey

byte-address-ptr-2.slang

> tests/current-bugs/generic/byte-address-ptr-2.slang(75): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: assert failure: witnessTableVal->getOp() != kIROp_StructKey

constraint.slang

> .slang(23): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unimplemented: value lowering

param-specialize-2.slang

> .slang(25): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: ErrorType

return-generic-2.slang

> .slang(20): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: ErrorType

scope-type.slang

> .slang(19): internal error 99999: unexpected condition encountered in Slang compiler: should not appear in input syntax
> let v = (Thing::Unsigned)10;
 
type-inference-3.slang

> .slang(5): internal error 99999: unimplemented feature in Slang compiler: swizzle on vector of unknown size
>    return val.x;

generic-int-controlled.slang

> slang(28): note 99999: an internal error threw an exception while working on code near this location
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: could not resolve target declaration for call

**Comment by tangent-vector** [comment]
Next step here is to either break these down into individual bug reports, or triage and root-cause them.

**Comment by natduca** [comment]
This is old enough that the findings are probably not relevant, and we'd need to re-do all the experiemnts. Lets get tot his through thorughough testing.
