### ISSUE TITLE
`SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY` is currently broken.

### ISSUE THREAD

**Issue by spnda** [shader-slang/slang#2116]
When setting `SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY` on a target with `spSetTargetFlags` the compiler throws a `Slang::Misc::TextFormatException` while compiling.

Running with a debug build of slang:
```
(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: assert failure: !"Invalid ASM format."
```

I'm trying to compile a slang shader to SPIR-V. I'm using a pretty barebones setup and am only setting `SLANG_MATRIX_LAYOUT_COLUMN_MAJOR`, otherwise everything is default. From my understanding that flag should still allow this but instead bypass `glslang` and generate the SPIR-V IR itself. The source of the shader I'm compiling is available [here](https://pastebin.com/8MTt9ARp).

**Comment by jsmall-nvidia** [comment]
The 'direct' SPIR-V Slang features is a work in progress and not ready for use in most shader scenarios. 

The Slang->SPIR-V via slang-glslang path is far more mature and feature rich and should be the default way for generating SPIR-V from slang currently.
