### ISSUE TITLE
Why not support Android iOS and Mac 

### ISSUE THREAD

**Issue by qianqians** [shader-slang/slang#2121]
Is there a plan to support Android ios and mac?

**Comment by tangent-vector** [comment]
Hello. We do not currently have any developers working on adding Android, iOS, or Mac support. Some work has been done in the past to try to get our premake-based build to work on Mac, but that work was not completed.

We would accept pull requests that help to get our build into better shape on/for these platforms. Ideally, we would want to have a story for continuous build/test/deployment on any platform we officially support, but we would accept build fixes independent of the (harder) work on CI.

It is worth noting for iOS/Mac that Slang does not currently have a back-end that produces Metal-compatible code. Some users have done things like take the SPIR-V output from Slang and use spirv-cross to transpile it for Metal, but we do not officially support that use case. A proper Metal SL back-end for Slang would be a valuable contribution that we would be happy to coordinate with somebody on.

If you'd like to discuss your use case and requirements in more detail, let me know and I'd be happy to converse more directly and help you determine if the Slang compiler/system could be a good fit for your needs.

**Comment by qianqians** [comment]
I was planning to develop an exercise game engine. when i choosing between glsl and hlsl as a shader language, i discovered slang. I want to try slang but it doesn't support android ios and mac.

**Comment by tangent-vector** [comment]
Unfortunately the current Slang contributors don't have a lot of focus on Android, iOS, and MacOS, so I can't promise that those platforms will happen in the near future. We fully intend to support them in the long run, but would need help from an interested contributor to help make it happen.
