### ISSUE TITLE
Macro Expansion Bug

### ISSUE THREAD

**Issue by WeakKnight** [shader-slang/slang#2134]
![image](https://user-images.githubusercontent.com/12985760/154415186-52d3c30f-595f-4712-8633-04de3931e3ca.png)
![image](https://user-images.githubusercontent.com/12985760/154415318-ed0ad0a0-6720-47cd-9547-575e5c956ecc.png)

```MESSY_PAD(3)``` is expanded to ```uint3 padVar11``` but it should be ```uint3 padVar14```.

**Comment by jsmall-nvidia** [comment]
Can confirm this is a problem. It appears to be taking __LINE__from the macro definition rather than from the macro expansion point.

**Comment by tangent-vector** [comment]
I can try to take this one. It would be helpful to get a sense of timeline and/or urgency.

**Comment by WeakKnight** [comment]
For me it is not very urgent.  I currently use something like PAD(number, __LINE__) as a workaround instead of PAD(number).

**Comment by natduca** [comment]
Developer breakage, Q2 low, Q3 medium
