### ISSUE TITLE
Defining the same namespace in 3(+) places will result in a compile error

### ISSUE THREAD

**Issue by taxmancw** [shader-slang/slang#2175]
```
namespace Foo
{
	// Content A
}

namespace Foo
{
	// Content B
}

namespace Foo
{
	// Content C
}
```
In the following example, trying to compile a shader that uses a namespace 3 or more times (e.g. including functions from difference sources to extend a namespace) will result in compile error `error 20001: unexpected '{', expected ';'`

Using the namespace only once or twice will work as expected.

**Comment by jsmall-nvidia** [comment]
Can confirm the issue, and just testing a fix.

**Comment by jsmall-nvidia** [comment]
Fix has been merged. Thanks for bringing this issue to our attention!
