### ISSUE TITLE
Performance loss around SIMD-like intrinsics

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2202]
The motivating issue behind this issue is around performance issues on Vulkan with `f32tof16` producing 

```GLSL
uvec2 f32tof16_1(vec2 value_1)
{
    int i_1;
    uvec2 result_1;
    i_1 = 0;
    for(;;)
    {
        if(i_1 < 2)
        {
        }
        else
        {
            break;
        }
        uint _S27 = (packHalf2x16(vec2((value_1[i_1]),0.0)));
        result_1[i_1] = _S27;
        int _S28 = i_1 + 1;
        i_1 = _S28;
    }
    return result_1;
}
````

Which is correct but slower than it needs to be because packHalf2x16 is called twice and the result combined, whereas the same result could be achieved by calling packHalf2x16 once and then repacking the result into uvec2. 

The reason this occurs is because the f32tof16 is generated from the stdlib by using the scalar types. This transformation does not know anything about using SIMD like intrinsics.

@tangent-vector writes

> On f32tof16(), there also seem to be two things here:
> 
> *  The reason the output code looks like that is understandable (well, at least I will excuse it), but not ideal. The indexed writes into result_1 are of course worrying for performance, so we are really counting on downstream compilers to unroll the loop fully. The actual control-flow structure is not unlike a typical for loop, but it is possible/probable that it doesn't get pattern-matched by downstream loop-unrolling optimizations. The ideal fix here is probably for the Slang compiler to implement its own loop unrolling that can optimize cases like that out of existence.
> 
> * (There's an alternative for part (2) there which is for us to define a distinct syntax node in the Slang AST to represent what the macro-based VECTOR_MAP_UNARY etc., lower that to custom IR, and then have custom lowering logic for that form late in our IR that generates more optimal code in the case where the element count of the vector is known)

I think it would be a useful feature for these scenarios to be able to write the desired code sequence for a specific target. This isn't trivial here, because I want to write 'GLSL' code, using those types inside the implementation. Also ideally the implementation would only be placed in the output if used. Lets say it's something like __asm()

```GLSL
__target_intrinsic(glsl)
half2 f32to16(vec2 v)
{
     __target_block(glsl) 
    {
        uint t = packHalf2x16(v);
        return uvec2(t & 0xffff, t >> 16);
    }
}
```

Everything in the block after __target_block only appears output for that target.  The idea here is that anything in the block can be ignored from the parsers point of view between the matching { }. Perhaps the __target_block syntax could be used on the function itself. So...

```GLSL
__target_block(glsl)
half2 f32to16(vec2 v)
{
        uint t = packHalf2x16(v);
        return uvec2(t & 0xffff, t >> 16);
}
```

(Perhaps __target_intrinsic is implicit in this scenario).

There is a problem here also that if f32to16 isn't available for the specific target (and types), I'd want the generic option to be used instead. That being the case some more syntax is probably needed around this.

**Comment by natduca** [comment]
f32to16 is available in the spirv direct backend so this should work now
