### ISSUE TITLE
Mechanisms around Name Lookup 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2205]
When referencing a declaration by name it can sometimes be useful to:

* Have the ability to specify the declarations modules name explicitly
* Rename how the modules is identified 
* Specify explicitly where a declaration comes from
* Partial paths and/or limiting search
* Import a module without polluting the global scope

## Specifying a Module Name

Slang allows the importing of modules. 

> An import declaration searches for a module matching the name given in the declaration, and brings the declarations in that module into scope in the current source unit.

A simple way to specify the module for a declaration might be to use it's name.

In some_module.slang
```HLSL
int calcThing(int a) { return a * a; }
```

```HLSL
import some_module;
// This imports from a subdirectory
import subdir.another_module;

/// 

int someFunc(int a)
{
    int r0 = calcThing(a);

    // Lets say there is calcThing in another module - how to I access it?
    // Use dot?
    int r1 = some_module.calcThing(a);
    // Currently scope does pretty much the same thing as . although 
    // it does make it clear that scoping is the optionation (not calling a mathod on a variable)
    int r2 = some_module::calcThing(a);
    
    // To access the other module
    int r3 = subdir.another_module.calcThing(a);
    
    // Presumably with scoping it should work too   
    int r3 = subdir::another_module::calcThing(a);
}
```

This seems reasonable, but raises questions. In C++, with namespaces using a scoped name like `some_module::calcThing` will lead to it searching from the current scope for a match, of the "path". This could lead to calcThing being from a different scope than fixed from the global scope. In C++ the scoping operator can be placed at the front to make clear the path is "rooted" to the global scope.

```
// No ambiguity
int r4 = ::some_module::calcThing(a);
```

This could be used within slang, but perhaps shows a problem using `.` style. As this would lead to a somewhat odd syntax. It's also worth noting there are already issues around . (issue #2104)

```
// No ambiguity, if a little odd....
int r4 = .some_module.calcThing(a);
```

# Naming an import 

It can be useful to rename an import

* Produce a more concise name (less typing for example)
* Use a name that is more appropraite for usage in module (more explicit - perhaps even longer)
* Allows use of module using conventions in the module
* Perhaps be used to limit lookup

An example syntax might be

```HLSL
import subdir.another_module as Another;

int someFunc(int a)
{
    return Another::calcThing(a);
}
```

For the last point, the behavior could be when using `as`, the declarations inside of the module can *only* be accessed via explicit qualification.  

# Partial Path

In C++ when a name path is given it could be seen as a partial search path. The normal scope search ordering is applied, and the user specified path is used for lookup.

A position could be taken that this is somewhat confusing. Another take could be names are only singular or absolute. If using an absolute name is too long, an alias can be defined, to shorten it.

# How to access `stdlib`

It makes sense that by default stdlib declarations are available in all translation units "as if" imported. Sometimes it's useful to be able to explicitly specify - presumably via one of the previously described mechanism. The main questions here are what should that name here, and more broadly what should be the Slang naming convention around modules?

Questions
=========

How do we specify an absolute path (if we allow absolute name paths)?

The dot operator seems to be used for too many disperate things. Do we want to use `::` for scoping? 

Would it be useful to have way to be explicit about looking in a module?

It's not clear how modules should be named. We have in our examples the use of _ (I guess because of the naming convention of `-`), but that looks a little odd. Perhaps it's useful in so far as it makes it perhaps more clear (?) that it is specifying a module/directory? But then that *implies* something about directory naming - not everybody is going to (or should) use our dash naming convention. 

In `nim` theres a mechanism where different conventions can be used interchangably. Perhaps that idea could be applied to just modules, such that "thing-blah.slang", "thingBlah.slang", "ThingBlah.slang",  "thing_blah.slang", can be imported by any style interchangably. This would require checking multiple module names, when importing a module, once a hit was found additional cost would be minimal. 

Do we want a mechanism to have a *relative* path to a declaration? For example

```HLSL
namespace SomeReallyLongNameThatMightChange { 
struct SomeType {};

namespace AnotherPointlesslyLongName { 

struct SomeType {};

void someFunction()
{
    SomeReallyLongNameThatMightChange::SomeType a;
    
    // It can be useful to just specify the relative path. Doing so would mean I could do something like
    // There's perhaps a question about syntax. Here I'll use ParentScope in the place of perhaps something 
    // more concise.
    
    ParentScope::SomeType b;
}

} }
``` 

A perhaps similar argument could be made around modules. If I wanted to import a module in the 'directory' above current translation unit 

```HLSL

// It's not clear how the syntax to do this would work. In C++ it's not a problem because it specified as a path (although a path in the host filesystems
// format - which without care makes code not platform independent. 
//
// With Slangs use of ., it means that `.` or `..` are out of the picture. If `::` was used we could do
//
// Alternatively we could standardize the filesystem conventions such that they are platform independent.

import ..::SomeModule as Thing;
```

**Comment by natduca** [comment]
Language topics but bankrupcy, prioritizing language footguns and or brokenneess
