### ISSUE TITLE
Support querying whether shader parameter is used post-optimization

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#2213]
Because of the way shader compilers have traditionally operated, many applications that rely on reflection of shader parameters need to be able to query whether or not a shader parameter is "used." Slang does not currently support such queries, but it should.

# Background

A few key choices in the design of the Slang compiler make this kind of query more subtle/challenging than it might appear.

Many other shader compilation systems assign registers/bindings to shader parameters only *after* performing optimizations, which can include the elimination of shader parameters that are unused by a particular entry point. Slang instead assigns registers/bindings *before* all non-trivial optimization steps, in order to ensure that we generate a deterministic result (will not change when lines inside function bodies get `#if`ed in/out). In practice, the Slang compiler assigns registers/bindings based on its AST structures (before IR code generation), and has no facilities at present for performing that task after optimization (where it would need to operate on the Slang IR).

The Slang API for reflection and runtime compilation is carefully designed to support scenarios where a program (or type) is loaded and compiled through the Slang front-end, and then reflection/layout information is queried *before* any particular variants of that code are linked, specialized, and emitted. This again means that the point in compilation where reflection currently takes place doesn't have access to the kinds of information that would be required to answer a query like "is this parameter used?".

# Insight

The key insight that unblocks a path forward is that we don't need to be able to use the Slang IR to answer the full query "is parameter `foo` used?". Instead, we can break that query into two distinct steps:

1. What `register`/`space` (or `binding`/`set`, etc.) was assigned to `foo`?
2. Is that `register`/`space` (etc.) used in some particular optimized kernel, or not?

The first step is something the current reflection API can answer just fine, and the second step is something that the IR is equipped to be able to answer (it just requires the plumbing work to surface it).

# API

The key thing to get right for now is the user-facing API for the feature. At the simplest, we could imagine an operation like:

```
SLANG_API bool spIsParameterLocationUsed(
    SlangCompileRequest* request,
    int entryPointIndex,
    int targetIndex,
    SlangParameterCategory category, // is this a `t` register? `s` register?
    int spaceIndex,      // `space` for D3D12, `set` for Vulkan
    int registerIndex);  // `register` for D3D12, `binding` for Vulkan
```

This would check if the kernel code that gets compiled for the given entry point and target ends up including (after optimization) a parameter that overlaps the given category, `space`, and `register`. A matching operation on `IComponentType` would probably also be needed:

```
virtual SLANG_NO_THROW boolSLANG_MCALL isParameterLocationUsed(
    int entryPointIndex,
    int targetIndex,
    ParameterCategory category,
    int spaceIndex,
    int registerIndex);
```

We can start with whichever of these is needed first by applications requesting the feature (probably the C-style `sp*` version).

Other options at the API level are certainly possible, but the above at least seems like a reasonable place to start.

# Implementing the Query

The above proposed functions are similar in style to the existing `spGetEntryPointCodeBlob` operation, and we can follow the flow of that operation to get to where the meat of the work probably needs to get done. The surface-level API stuff for that operation bottlenecks through the `TargetProgram` type, which owns a demand-generated set of `CompileResult`s, one for each entry point.

If we can extend the `CompileResult` type to include a field that refers to usage information about shader parameters, then we can try to initialize that information on the code paths that produce `CompileResult`s. This is primarily handled in `CodeGenContext::emitEntryPoints()`. In the simplest case, the functions that `emitEntryPoints()` dispatches down to can be modified to return additional data via an output parameter, and that additional data can be packaged up into the `CompileResult`.

In terms of the actual representations, it should be possible to store something like a `List<UsedRange>` where each `UsedRange` is something like:

```
struct UsedRange
{
    LayoutResourceKind kind; // `LayoutResourceKind` is the same as `ParameterCategory` in the public API
    int spaceIndex;
    int registerIndex;
    int registerCount; // 0 for unsized
};
```

If those entries are stored in sorted order, then the `isParameterLocationUsed` query would seemingly just require a binary search to find the appropriate range (if any).

The next step is to figure out how to generate that information. 

# A Temporary Workaround

For back-end targets that provide their own reflection APIs (e.g., the fxc- and dxc-based compilation paths) we could in principle use the reflection API of the downstream compiler to enumerate and collect the information on used binding ranges. Similarly, for the SPIR-V target, we could take the output SPIR-V and use some ad-hoc logic to scan for the appropriate set and binding decorations.

Doing this work per-back-end is probably *not* a good long-term answer, but would allow us to get precise information for a few targets in the short term, with relatively simple logic.

# Using the Slang IR

All of our code generation targets make use of the Slang IR, and produce the IR that will drive back-end compilation with the `linkAndOptimizeIR` function. That operation could return additional information in the `LinkedIR` type that it already produces.

The `linkAndOptimizeIR` function performs a lot of different passes on the IR, and it should be a simple matter to add an additional step after all the optimization is complete to scan the `irModule` in that function to identify shader parameters and their binding information.

To a first approximation, a pass to look up this information would do something like:

* Iterate over the global-scope instructions in the module: `for(auto inst  : irModule->getGlobalInsts())`
* Identify those that are global shader parameters: `if(auto param = as<IRGlobalParam>(inst)`
* Get the layout information for that parameter: `auto varLayout = as<IRVarLayout>(param->findDecoration<IRLayoutDecoration>())`
* Iterate over the kinds of layout resources the parameter uses: `for(auto sizeAttr : varLayout->getTypeLayout()->getSizeAttrs())`
* The resource kind used is: `auto kind = sizeAttr->getResourceKind()`
* Find the offset of the parameter for each kind: `auto offsetAttr = varLayout->findOffsetAttr(kind)`
* The space for the range is: `auto spaceIndex = offsetAttr->getSpace();`
* The register/binding for the range is `auto registerIndex = offsetAttr->getOffset();`
* The number of registers/bindings in the range is `auto count = sizeAttr->getSize();`

We can accumulate (and then sort) all the ranges found this way, or we can strip out all but the ones users will actually care about.

Because the enumeration of the parameters will be done *after* optimization of the Slang IR, it should only include parameters that appear to be used in the HLSL output that Slang will generate. It is possible that some parameters that Slang thinks are used will be optimized away by a downstream compiler (perhaps because it is better at detecting unreachable code), but hopefully that won't break the kinds of applications we are concerned with here.

**Comment by csyonghe** [comment]
Closing as fixed.
