### ISSUE TITLE
warning level

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#229]
We need to decide which VC warning level to stick to. Currently x86 builds are at level 3 and x64 are level 4. x64 builds are generating a lot of warning messages. We should decide whether we want to switch back to level 3 or fix all the level 4 warnings.

**Comment by tfoleyNV** [comment]
I hadn’t noticed the settings didn’t match, but I know I’ve been sloppy about leaving warnings in the code, so I can take the task of scrubbing for them.

In principle it would be good to build with warnings as errors, but I’m nervous about checking anything with those settings in as the default, as it seems to be one more thing that could go wrong for somebody who. He is out the code and tries to plug it into their build...

**Comment by csyonghe** [comment]
This is already fixed. Both MSVC and G++ are reporting no warnings. Next step is to fix all clang warnings.
