### ISSUE TITLE
Sampling from combined image samplers

### ISSUE THREAD

**Issue by NickDriscoll** [shader-slang/slang#2295]
Hello.

I'm trying to use Slang to author shaders for Vulkan, but I'm confused as to how to sample from combined image samplers.
I tried searching online, but I can only find ways to sample that require you to pass in a SamplerState in the shader.

Can combined image samplers be used in this language?

Thank you.

**Comment by jsmall-nvidia** [comment]
Slang does have support for combined image samplers in the language and for Vulkan. There is a sample showing the usage [here](https://github.com/shader-slang/slang/blob/master/tests/type/texture-sampler/texture-sampler-2d.slang)

The type is `Sampler` with texture related subscripts of `1D`/`2D`/`3D`/`Cube`/`1DArray` ... etc, followed by the contained type. In the example

```HLSL
Sampler2D<float> t2D;
``` 

It has the same methods as the Texture of the same type without requiring the SamplerState parameter. The functionality available can be seen by looking at the [stdlib docs](https://raw.githubusercontent.com/shader-slang/slang/master/docs/stdlib-doc.md).

On some targets, such as CUDA and C++ textures and samplers are combined anyway. The feature should work for D3D and Vulkan targets. That said this feature has not been extensively tested, so we would value any feedback about problems or (hopefully) if it all works to plan.

**Comment by NickDriscoll** [comment]
I was able to successfully translate my small crop of GLSL shaders to Slang today, so it looks like Sampler2Ds are working fine at least for my use case.
