### ISSUE TITLE
host-callable/double/llvm/x86 has problems

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2315]
On testing with `slang-llvm` with host callable, the following tests fail 

* "tests\hlsl-intrinsic\scalar-double.slang"
* "tests\hlsl-intrinsic\matrix-double.slang"

PR #2314 works around this by disabling these tests via a category.

The issue needs digging into to resolve and fix the root issue.

**Comment by csyonghe** [comment]
Can this be related to the _chkstk issue we recently fixed?

**Comment by natduca** [comment]
Yong indicates this is fixed.

**Comment by jsmall-nvidia** [comment]
They are still disabled in the test files and has the workaround in slang-test-main. This is x86 32 bit.
