### ISSUE TITLE
Actually clean up after IR

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#234]
Right now the IR codegen path is leaky - we construct multiple `IRModule`s but then never free them or the values they contain. Right now we are a little bit careful to release instructions when they are eliminted during optimization, but that doesn't help when the instructions that *are* used still leak.

My plan going in had been that the IR would not contain any "expensive" types, so we could just allocate everything out of a simple pool of pages, and then free that memory en masse when we are done.

Unfortunately, we now have IR nodes that hold `DeclRef`s, as well as having `IRGlobalValue` nodes that hold `String`s, so it would be tricky to fully eliminate reference-counted storage from the IR.

At this point is seems like the Right Answer for now may to be making the IR use a traditional inheritance hierarchy and a `virtual` destructor. The one big gotcha there is that it is currently a nice design point that if we want to load the IR from serialized bytecode, we don't actually need to know the concrete type of the instruction we are loading - we can just `malloc` an `IRInst` with the right number of operands and move along. I'd love to retain this property, but maybe it isn't a big enough benefit.

**Comment by csyonghe** [comment]
How about adding a StringPool to IRModule and replace all String to StringView.
For DeclRefs we can also pool it in IRModule.

**Comment by tfoleyNV** [comment]
That would be a good solution, so long as we are okay with `String`s and `DeclRef`s created during IR processing only being freed when we are 100% done with the module (whereas we might be able to pool and reclaim storage for individual instructions, by building free lists for power-of-two sizes within a certain range).

One other design point that needs to be decided is whether *all* `IRValue`s should be part of a parent/child hierarchy, so that we can always exhaustively scan all the "alive" values (whether or not they have uses). As it stands right now the `IRValue` cases for decl-refs and integer/float literals are just free-floating, and if we drop their last use they get lost (right now they leak; with a pool they'd get reclaimed later).

**Comment by csyonghe** [comment]
Yeah, it is probably not worth the trouble and performance overhead trying to free them in-time either. These are small objects that won't take up a serious amount of memory.

**Comment by tfoleyNV** [comment]
I believe Yong has implemented the cleanup for the IR data structures, so this issue can be closed.
