### ISSUE TITLE
Khronos Vulkan ValidationLayers Debug Printf not properly supported 

### ISSUE THREAD

**Issue by Qubaef** [shader-slang/slang#2353]
I want to use Debug Printf extension available in Vulkan Validation Layers, described [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/debug_printf.md).

GL_EXT_debug_printf seems to be unsupported by slangc.exe.

In HLSL with glslangValidator.exe, following should work:
```
void main() {
float myfloat = 3.1415;
printf("My float is %f", myfloat);
}
```
but in slang it is not supported.

I am aware that such feature will take time to implement and I am not expecting it to appear anytime soon.
Are there any possible workarounds to enable the vulkan extension (capability) manually? Maybe something like inlining glsl/SPIR-V, or importing glsl/SPIR-V module in the slang file?

**Comment by tangent-vector** [comment]
This is a good request. I see no reason why we can't map the built-in HLSL `printf` over to this extension.

This seems like a reasonable feature for a first-time contributor to work on. The approach for adding new intrinsic functions to Slang, or mapping existing functions to GLSL/SPIR-V extensions, is fairly easy to do (although not well documented).

The one big thing that can make a `printf`-like function tricky is the variable number of arguments. Slang doesn't currently support varargs, so `printf()` would need to be defined with multiple overloads.

**Comment by Qubaef** [comment]
Support for the native printf hlsl capability got merged to master. It can now be used with GL_EXT_debug_printf Vulkan extension.
