### ISSUE TITLE
slang-tag-version.h doesn't get updated for windows releases

### ISSUE THREAD

**Issue by spnda** [shader-slang/slang#2403]
All the `slang-tag-version.h` headers have `#define SLANG_TAG_VERSION "unknown"` in the windows builds on the GH release page. The Mac and Linux contain the correct header.

**Comment by jsmall-nvidia** [comment]
Thanks for heads up, will look to fix now.

**Comment by jsmall-nvidia** [comment]
On checking packages built with #2429 it looks the files are now being set on windows.
