### ISSUE TITLE
Support a `ParameterBlock<T>` type

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#242]
Vulkan and D3D12 both allow shader parameters to be grouped in to descriptor sets/tables, to enable efficient binding of parameters that change at different rates. The grouping used by the application needs to be matched up with the shader parameters declared in GLSL/HLSL, and each of the APIs uses a slightly different convention for this:

- Vulkan GLSL takes parametes that have `layout(binding=AAA, set=BBB)` qualifiers, and groups them into sets according to `BBB`. The `VkDescriptorSetLayout`s created must match the bindings for the `AAA`s, and any `VkPipelineLayout`s must match the sets chosen for the `BBB`s.

- D3D12 HLSL allows parametesr to be qualified with both a `register` and a `space`. Rather than directly interpret these similarly to Vulkan's `binding` and `set`, the API for creating pipeline states uses a data structure to specify the decomposition into tables/slots, and then map those to the ranges of registers used. This means that `space` usage doesn't need to be planned in advance, and can instead just be used to deal with unsized arrays (which logically consume an infinite number of registers). The extra degree of freedom isn't *that* useful, though, because root signatures with the same physical layout, but which map to different registers are considered distinct (so you still need to swap and rebind).

Both of these designs suffer from the fact that there is no easy way for the shader programmer to specify both the shader parameters and their grouping conveniently; they must always use at least two mechanisms (and sometimes have participation from engine-side API usage).

Contrast this with the case of constant buffers, where both languages use a simple syntactic construct to represent the nesting of parameters inside blocks (`cbuffer C { ... }` or `uniform C { ...}`). For a user, there is almost no chance of getting confused about what these constructs mean, or how to use them.

Aside: D3D12 HLSL adds a concrete notion of a `ConstantBuffer<T>` type, which conveys the same meaning as a `cbuffer` declaration, but which can be used in more places (e.g., passed to functions, grouped into arrays, etc.).

Slang should provide the same benefit that `cbuffer` declarations provide, when dealing with parameter binding at granularities more coarse than single constant buffers. The concrete proposal is:

- Add a `ParameterBlock<T>` type that can be used to express a group of parameters represented by the fields of the `struct` type `T`.

- A `ParameterBlock<T>` will be laid out as follows:
  - If there are any "uniform" fields, or fields with uniform data, then they will be grouped into a `ConstantBuffer<...>` that comes first in the layout
  - Any resource-type fields are then allocated space in order, following the usual algorithm
  - The entire `ParameterBlock<T>` will be allocated a "fresh" binding space/set

- Note that if `T` contains a mix of field types, then it may not map to a single descriptor table in D3D12 (e.g., a single table cannot mix samplers and textures).

- If a `ParameterBlock<T>` is made when `T` (transitively) contains a `ParameterBlock<U>`, then the nested block will gets its own space/set allocated. Ditto for any unsized arrays in `T` (for the HLSL case). This is similar to our handling when a constant buffer contains another constant buffer.

- Lower a `ParameterBlock<T>` (in the IR) to individual parameters for each of the fields (along with a constant buffer for the fields of uniform type), and output HLSL/GLSL with the appropriate `space`/`set` declarations on each parameter.

- Reflection data should probably expose `set`s/`space`s as a distinct resource kind, with `ParameterBlock<>`s consuming them (but not exposing the details of resource usage for sub-fields, just as a constant buffer does not expose the uniform data consumed by its contents).

- A Vulkan engine should map the `ParameterBlock<>` to zero or more descriptor sets; if desired it might use a "dynamic offset" for the constant-buffer part.

- A D3D12 engine should map the `ParameterBlock<>` to zero or more descriptor tables. It can optionally also map the constant buffer part of the block to a root constant buffer, rather than put it inside a descriptor table (the engine should define this policy).

We could conceivably also define a `DescriptorTable<T>` or `DescriptorSet<T>` type that more directly maps to the underlying API concept, but it isn't clear to me that it would be very useful to do so.

**Comment by tfoleyNV** [comment]
PR #245 adds a first-pass version of parameter blocks that works for some small test cases, and lays the groundwork for a more complete implementation.

**Comment by tfoleyNV** [comment]
I'm back at work on this, with the following goals:

- Ensure that parameter blocks are correctly plumbed through to codgen by adding a compute test for them

- Ensure that parameter blocks are supported on the AST-to-AST path, so that Falcor can start using them ASAP

- Add support for uniform data inside parameter blocks (should map to a constant buffer)

**Comment by tangent-vector** [comment]
The `ParameterBlock<T>` implementation is now good enough to pass a few tests and also to work under both D3D12 and Vulcan when used in Falcor. I’m closing this issue, and we can open more specific ones as bugs surface.
