### ISSUE TITLE
Sampler2D.SampleCmp() has confusing parameters

### ISSUE THREAD

**Issue by NickDriscoll** [shader-slang/slang#2455]
First, let me say thank you for addressing my previous issue re: SV_ViewID so quickly.

Now, I am trying to do hardware PCF for my shadows by utilizing the SampleCmp method of Sampler2DArray, but for that and even for Sampler2D's the first parameter is a SamplerComparisonState. All state referenced by that structure is defined in the combined image sampler itself, so I don't understand why this struct needs to be passed.

Is this just one of the things that's incomplete regarding Sampler types in slang or am I missing something?

Thank you.

**Comment by tangent-vector** [comment]
That definitely sounds like a bug (or missing feature) in our implementation of `SampleCmp` in the Slang standard library. Our support for combined texture image/sampler pairs has not yet been put into heavy use in the field, since most of our current users/customers write code that uses separate textures and samplers.

If anybody in the community wants to dive in and help to fix these issues in the context of a codebase that needs combined texture image/sampler pairs, we would appreciate those contributions. I would be happy to set aside time to help get somebody oriented in the codebase in order to help them get started.

**Comment by NickDriscoll** [comment]
So I know next to nothing about spirv compilers, but my intuition makes me think that this shouldn't be so hard to implement considering it's the same work as Texture2D.SampleCmp() except some of the data comes from "inside the sampler"

I forked the repo and can build all projects but one through VS. My email is in my profile if you want to reach out and point me in the right direction.

**Comment by csyonghe** [comment]
core.meta.slang:1590 is where we need to fix. Add a `if(prefixInfo.combined)` there and define the function differently for `SamplerXXX.SampleCmp`

**Comment by NickDriscoll** [comment]
I'm working on this now. I see the following error when I try to compile, but a slangc.exe is generated no matter what so I wonder if it even matters:

Error	MSB3073	The command "IF EXIST ..\..\..\external\slang-llvm\bin\windows-x64\release\slang-llvm.dll\ (xcopy /Q /E /Y /I ..\..\..\external\slang-llvm\bin\windows-x64\release\slang-llvm.dll ..\..\..\bin\windows-x64\release > nul) ELSE (xcopy /Q /Y /I ..\..\..\external\slang-llvm\bin\windows-x64\release\slang-llvm.dll ..\..\..\bin\windows-x64\release > nul)
IF EXIST ..\..\..\external\slang-glslang\bin\windows-x64\release\slang-glslang.dll\ (xcopy /Q /E /Y /I ..\..\..\external\slang-glslang\bin\windows-x64\release\slang-glslang.dll ..\..\..\bin\windows-x64\release > nul) ELSE (xcopy /Q /Y /I ..\..\..\external\slang-glslang\bin\windows-x64\release\slang-glslang.dll ..\..\..\bin\windows-x64\release > nul)
:VCEnd" exited with code 4.	slang	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Msbuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	155

**Comment by csyonghe** [comment]
You need to run `.\premake.bat vs2019 --deps=true` to pull prebuilt llvm binaries.

**Comment by NickDriscoll** [comment]
Thank you. Not sure how I skipped over that paragraph of the instructions.

I put this in the relevant places:
```
sb << "float SampleCmp(";
if (!prefixInfo.combined)
    sb << "SamplerComparisonState s, ";
```
but it doesn't appear to do anything. I still see the typical
```no overload for 'SampleCmp' applicable to arguments of type (vector<float,3>, float)```
when I try building my own code.

I will continue trying things.

**Comment by csyonghe** [comment]
This is now fixed.
