### ISSUE TITLE
request: support for vulkan specific attributes, like [vk::builtin("PointSize")]

### ISSUE THREAD

**Issue by nerditation** [shader-slang/slang#2461]
in searching for `gl_PointSize` equivalence, I find there was a `PSIZE` semantic in DirectX 9, but later removed. see [msdn](https://learn.microsoft.com/en-us/windows/uwp/gaming/glsl-to-hlsl-reference#porting-glsl-pre-defined-global-variables-to-hlsl)

then I find out the documented way is to use an vulkan specific attribute: [`vk::builtin("PointSize")`](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#builtin-variables), see also [this discussion](https://github.com/KhronosGroup/glslang/issues/1154)

then I tried it in slang, but it didn't work:

    vk.slang(3): error 31000: unknown attribute 'vk_builtin'
        [vk::builtin("PointSize")]
         ^~

searching related issues, I only find #2242 , and this very old #853

I would like to suggest: please add support for more vulkan specific attributes (e.g. those listed [here](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#vulkan-specific-attributes))

**Comment by csyonghe** [comment]
We support `SV_PointSize` semantics.
