### ISSUE TITLE
Internal compiler error when lowering generics

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#247]
The following test case crashes the compiler:
The compiler crashes at visitGenericDecl() during lowering. It seems that Lowering does not expect to see a GenericDecl.

```
//TEST(smoke, compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out

RWStructuredBuffer<float> outputBuffer;

__generic<T:__BuiltinFloatingPointType>
T test(T v0, T v1)
{
    return T(3.0);
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    float outVal = test<float>(1.0, 2.0);
    outputBuffer[dispatchThreadID.x] = outVal;
}
```

**Comment by tfoleyNV** [comment]
I can't see a difference between the code you posted here and the code for #248. Did you include the wrong example? I certainly didn't see a crash at the location you specify given this code (which should work fine once PR #249 lands).

**Comment by csyonghe** [comment]
Oh, yeah, they are supposed to be slightly different ones. Here test() should just be `return v0;`
They do seem to stem from the same cause.

**Comment by tfoleyNV** [comment]
Okay, I made that change and it looks like #249 will fix this too.
