### ISSUE TITLE
No type conformances are found when placed in other modules

### ISSUE THREAD

**Issue by Dynamitos** [shader-slang/slang#2513]
The documentation for `loadModule()` states:

> Executing loadModule("MyShaders") in host C++ code is similar to using import MyShaders in Slang code. The session will search for a matching module (usually in a file called MyShaders.slang) and will load and compile it (if it hasn’t been done already).

Now I'm trying to create an interface and place a struct conforming to that interface in a different (potentially generated) file, and load it with `loadModule()`. I have created a sample reproducing the issue:

Mat.slang:

    interface IMaterial
    {
        float4 sample(float2 texCoord);
    }

    ParameterBlock<IMaterial> gMaterial;

Simple.slang:

    import Mat;

    struct SimpleMaterial : IMaterial
    {
        float4 sample(float2 texCoord)
        {
            return float4(1, 0, 1, 1);
        }
    }

shaders.slang

    import Mat;

    [shader("fragment")]
    float4 fragmentMain(float2 texCoord)
    {
        return gMaterial.sample(texCoord);
    }

main.cpp

    #include <slang.h>
    #include <slang-com-ptr.h>
    #include <map>
    #include <array>

    struct ShaderCreateInfo
    {
        std::string mainModule;
        std::vector<std::string> additionalModules;
        std::string name; // Debug info
        std::string entryPoint;
        std::vector<const char*> typeParameter;
        std::map<const char*, const char*> defines;
    };

    int main()
    {
        ShaderCreateInfo createInfo =
        {
            .mainModule = "shaders.slang",
            .additionalModules = { "Simple" },
            .name = "TestCompile",
            .entryPoint = "fragmentMain",
            .typeParameter = { "SimpleMaterial" }
        };
    
        thread_local Slang::ComPtr<slang::IGlobalSession> globalSession;
        if(!globalSession)
        {
            slang::createGlobalSession(globalSession.writeRef());
        }
        slang::SessionDesc sessionDesc;
        sessionDesc.defaultMatrixLayoutMode = SLANG_MATRIX_LAYOUT_COLUMN_MAJOR;
        sessionDesc.flags = 0;
        std::vector<slang::PreprocessorMacroDesc> macros;
        for(auto define : createInfo.defines)    
        {
            macros.push_back(slang::PreprocessorMacroDesc{
                .name = define.first,
                .value = define.second
            });
        }
        sessionDesc.preprocessorMacroCount = macros.size();
        sessionDesc.preprocessorMacros = macros.data();
        slang::TargetDesc vulkan;
        vulkan.profile = globalSession->findProfile("glsl_vk");
        vulkan.format = SLANG_SPIRV;
        sessionDesc.targetCount = 1;
        sessionDesc.targets = &vulkan;
        std::array<const char*, 3> searchPaths = {"shaders/", "shaders/lib/", "shaders/generated/"};
        sessionDesc.searchPaths = searchPaths.data();
        sessionDesc.searchPathCount = searchPaths.size();

        Slang::ComPtr<slang::ISession> session;
        globalSession->createSession(sessionDesc, session.writeRef());

        Slang::ComPtr<slang::IBlob> diagnostics;
        std::vector<slang::IComponentType*> modules;
        Slang::ComPtr<slang::IEntryPoint> entrypoint;
    
        for (auto moduleName : createInfo.additionalModules)
        {
            modules.push_back(session->loadModule(moduleName.c_str(), diagnostics.writeRef()));
            if(diagnostics)
            {
                std::cout << (const char*)diagnostics->getBufferPointer() << std::endl;
            }
        }
        slang::IModule* mainModule = session->loadModule(createInfo.mainModule.c_str(), diagnostics.writeRef());
        modules.push_back(mainModule);

        if(diagnostics)
        {
            std::cout << (const char*)diagnostics->getBufferPointer() << std::endl;
        }
        mainModule->findEntryPointByName(createInfo.entryPoint.c_str(), entrypoint.writeRef());
        modules.push_back(entrypoint);

        Slang::ComPtr<slang::IComponentType> moduleComposition;
        session->createCompositeComponentType(modules.data(), modules.size(), moduleComposition.writeRef(), diagnostics.writeRef());
        if(diagnostics)
        {
            std::cout << (const char*)diagnostics->getBufferPointer() << std::endl;
        }

        //slang::ProgramLayout* reflection = moduleComposition->getLayout(0, diagnostics.writeRef());
        //if(diagnostics)
        //{
        //    std::cout << (const char*)diagnostics->getBufferPointer() << std::endl;
        //}
        //std::vector<slang::SpecializationArg> specialization;
        //for(auto typeArg : createInfo.typeParameter)
        //{
        //    specialization.push_back(slang::SpecializationArg::fromType(reflection->findTypeByName(typeArg)));
        //}
        //Slang::ComPtr<slang::IComponentType> specializedComponent;
        //moduleComposition->specialize(specialization.data(), specialization.size(), specializedComponent.writeRef(), diagnostics.writeRef());
        //if(diagnostics)
        //{
        //    std::cout << (const char*)diagnostics->getBufferPointer() << std::endl;
        //}
        Slang::ComPtr<slang::IBlob> kernelBlob;
        moduleComposition->getEntryPointCode(
            0,
            0,
            kernelBlob.writeRef(),
            diagnostics.writeRef()
        );
        if(diagnostics)
        {
            std::cout << (const char*)diagnostics->getBufferPointer() << std::endl;
        }
        return 0;
    }

Running this gives me the following error

> shaders/Mat.slang(1): error 50100: No type conformances are found for interface 'IMaterial'. Code generation for current target requires at least one implementation type present in the linkage.
interface IMaterial
              ^~~~~~~~~

Notice that the code for creating a specialized Component is commented out, as it gives me different error:

>(0): error 38025: expected 0 specialization arguments (1 provided)

This hints that the ParameterBuffer<IMaterial> is not recognized as a type parameter so I tried explicitly introducing it in Mat.slang:

    type_param TMaterial : IMaterial;
    ParameterBuffer<TMaterial> gMaterial;

This still gives the error about no specialization arguments being expected, and crashes the kernel code generation entirely at `lowerCallToInterfaceMethod()` in file `slang-ir-lower-generic-call.cpp:285`

I guess I'm using the API incorrectly, so help would be much appreciated. Thanks in advance.

**Comment by csyonghe** [comment]
You need to create a type conformance `ComponenType` and include it in your composed program for every type implementation that you want to use in the shader code.

```
ComPtr<ITypeConformance> typeConformance;
const int conformanceID_SimpleMaterial_IMaterial = 1; // an integer value to represent "SimpleMaterial" type.
session->createTypeConformanceComponentType(simpleMaterialType, IMaterialType, typeConformance.writeRef(), conformanceID_SimpleMaterial_IMaterial);

modules.add(typeConformance); // add type conformance to the final composed program.

session->createCompositeComponentType(modules.data(), modules.size(), moduleComposition.writeRef(), diagnostics.writeRef());


```

**Comment by Dynamitos** [comment]
Where do I get the `simpleMaterialType` from? Neither the mainModule, nor the additionalModule nor the composed Program is able to find it in its `ProgramLayout`

**Comment by csyonghe** [comment]
It should be discoverable by calling `findTypeByName` on the composed program (without the conformance in it).

**Comment by csyonghe** [comment]
If not, try to find it from a post-linked program.
```
moduleComposition->link(linkedProgram.writeRef(), diagnosticBlob.writeRef());

auto layout = linkedProgram->getLayout(0);
auto simpleMaterialType = layout->findTypeByName("SimpleMaterial");


```

**Comment by Dynamitos** [comment]
It seems that just linking the moduleComposition was the fix, thanks a lot. However it generates code with a matrix layout of `row_major`, even though i explicitly set the opposite at session creation, any ideas?

**Comment by csyonghe** [comment]
That might be a bug because non of our users use column major layout these days. Our CPU backend also only support row_major.  See the reasoning for using row_major here: https://shader-slang.com/slang/user-guide/a1-01-matrix-layout.html

We can take a look into the bug if you can create a repro.

**Comment by Dynamitos** [comment]
It seems that it uses the correct matrix layout, but generates `vector * matrix` in GLSL from `mul(matrix, vector)` in Slang, and then inverts the matrix layout so in the end the result is the same. I just saw in RenderDoc that the matrices were listed as `row_major` and thought that was a problem, but since it inverts both the layout and the multiplication order it works.
