### ISSUE TITLE
Disambiguate generics application

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#252]
The current implementation uses simple lookup to determine whether an var expression refers to a generics, and use this information to disambiguate between a potential genApp expr or normal comparison expr.

However, when we want to add generic methods, the simple lookup will not work.

For example,
```
__generic<TPattern : IBRDFPattern, TInterpolant: IVertexInterpolant>
float test(TPattern pattern, TInterpolant vertInterps)
{
    float rs = pattern.evalPattern<TInterpolant>(vertInterps);    
    return rs;
}
```
Since lookup of evalPattern will not return any result (because we are not in the right scope looking for `evalPattern`, the parser will just treat the `<` as comparison operator.

We need to figure out a systematic method for such disambiguations. It seems that the easiest way is to use a two-pass parser. A hacky way is to just record all seen generic names, and check if the last encountered token has a previously recorded generics name. This will work for most cases but is not actually correct.

**Comment by csyonghe** [comment]
@tfoleyNV, what is your opinon on this? I would like to go ahead and turn our parser into a two pass parser. The executeActionInner() logic needs to change to invoke a coarseParser first, then use CoarseParsingResult to existing Parser to get the final AST.

**Comment by tfoleyNV** [comment]
See this link for a discussion of the disambiguation logic that goes on in C#:

https://books.google.com/books?id=g6axWRRpJZwC&lpg=PA79&ots=HAYnnpNu3O&dq=C%23%20generic%20parser%20disambiguation&pg=PA78#v=onepage&q=C%23%20generic%20parser%20disambiguation&f=false

I've implemented this kind of approach multiple times (including in an HLSL "compatible" compiler) and never had users run into the ambiguous cases.

**Comment by csyonghe** [comment]
PR #251 introduces speculative parsing that addresses this issue.
