### ISSUE TITLE
Q: OpenCL support?

### ISSUE THREAD

**Issue by ib00** [shader-slang/slang#2533]
Any plans to support OpenCL (via SPIR-V)?

**Comment by jsmall-nvidia** [comment]
We don't have any current plans around OpenCL with SPIR-V support. We are looking at beefing up our SPIR-V output. 

Could you elaborate on your use case? 

We would happily accept contributions to the project. Once we have our improved SPIR-V path, it would probably make adding support relatively straightforward.

**Comment by ib00** [comment]
Thanks.

I've been looking a bit into this and there are problems that are probably not easily overcome: 
1. Spirv is arbitrarily segmented into kernel spriv and shader spirv. They don't have compatible pointer semantics. So shader spriv (vulkan) doesn't work with kernel spriv (opencl)
2. Opencl 3.x does not mandate spirv support.

There's 'clspv' project that runs OpenCL kernels on Vulkan, but there are limitations.

> Could you elaborate on your use case?

I have some investment in OpenCL (and existing, optimized kernels) that I don't want to abandon.
But, I do want to use slang as a shading language as I can potentially share kernels, but I would
want to be able to use old kernels and new kernels (generated from slang).

**Comment by csyonghe** [comment]
Closing the issue for now since we currently do not have any available resource to implement OpenCL backend. 

We welcome community contributions to add more backends. If anyone is interested, we are happy to work with them and provide necessary guidance.

**Comment by ib00** [comment]
Any plans to revisit OpenCL backend now that this is a Khronos project?

**Comment by TheRedXD** [comment]
I think this issue should be reopened. Would very much like for Slang to have an OpenCL backend.

**Comment by gmeeker** [comment]
If anyone is thinking of working on this, DM me if sponsorship would help. I could use this but don't have time myself.
