### ISSUE TITLE
Shall we turn on "treat warnings as errors"

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#254]
@tfoleyNV  Now that we have all the MSVC warnings fixed, shall we turn on "Treat Warnings as Errors" in visual studio project file to help preventing future warnings from slipping through? I think it is useful too keep the codebase warning-free and I don't want those useful warnings being burried by a swarm of other useless warning messages.

**Comment by tfoleyNV** [comment]
Probably worth if for now, and if we clean up the clang/gcc warnings we can turn on `-Werror` I the Makefile.

Longer term I’d like our source releases to *not* include such flags, so we don’t have to worry if people try to build using compiler versions we hadn’t accounted for. For right now nobody is building from our sources but us, so it isn’t as important.

**Comment by csyonghe** [comment]
Already turned this on in #266.
