### ISSUE TITLE
struct forward declarations  and non-inline method definitions

### ISSUE THREAD

**Issue by chrislu** [shader-slang/slang#2557]
Hi,
I am moving code from a DXC compiled base to Slang. I ran into the following problems making porting the shader code an issue for code readability.

1. struct forward declarations not working
2. non-inline method definitions are not working

The following is valid DXC code that does not compile using Slang:

```
struct PSInput
{
	float4 color : COLOR;
};

class SDR;

class SDR
{
    float4 do_smth();
};

float4 SDR::do_smth()
{
    return float4(1.0, 0.0, 1.0, 1.0);
}

float4 PSMain(PSInput input) : SV_TARGET
{
    const SDR sdr;
	return sdr.do_smth();//input.color;
}
```

Is this by design? With a larger shader code base I find it _very_ important to have a good overview of struct interfaces and data members and the implementation details separate.

**Comment by csyonghe** [comment]
Hi @chrislu, thank you for your feedback! Slang supports out of order define-use so declarations aren't needed. We agree that such ability would allow codebases to present a cleaner outline, and the feature may not be difficult to add. However we are currently resource limited and most likely are not going to have the cycles to add this support. We hope that the document outline feature in our VSCode extension can help with that.

**Comment by natduca** [comment]
We totally hear that this is convenient, however for now we're prioritizing keeping our backlog tidy and things we're going to get to, and our priorities for now are hardening the language. So, this one doesn't quite make the cut for now --- if we encounter more users who need this , there's a good possibility down the road that we might reopen, so again, closing more to keep our backlog tidy.

Thanks for filing this bug!
