### ISSUE TITLE
Leaked AppleID account password

### ISSUE THREAD

**Issue by qianqians** [shader-slang/slang#2575]
{
    "apple_id": {
        "username" : "yongh@outlook.com",
        "password":  "@env:AC_PASSWORD"
    },
    "notarize" :{
        "path": "slang-macos-dist.zip",
        "bundle_id": "shader-slang.slang",
        "staple": false
    }
}

https://github.com/shader-slang/slang/tree/master/extras

**Comment by csyonghe** [comment]
Right, all passwords are configured as GitHub secrets referenced by these kind of tokens.
