### ISSUE TITLE
Multiply defined declarations across modules cause ambiguity

### ISSUE THREAD

**Issue by jsmall-zzz** [shader-slang/slang#2579]
This issue was motivated by a problem with 

```
float2 v = ...;
float2 uv = saturate(v);
```

Where there is a definition of `vector<T,N> saturate(vector<T,N> x)` which is identical to the stdlib version. This causes an error on the call site, with slang reporting 

```
error 39999: ambiguous call to 'saturate' with arguments of type (vector<float,2>)
``` 

This issue can be repeated on current slang and back to at least 0.24.20.

If we write 

```
T doThing<T>(T t) { return t; }
T doThing<T>(T t) { return t; }
```

We  get the error 

```
tests/check.slang(6): error 30201: function 'doThing' already has a body
T doThing<T>(T t) { return t; }
```

Which is appropriate. I would note that in a previous version of Slang 0.24.20 - this doesn't cause an error.

So the problem here seems to stem from there being two definitions that have the same signature in different modules. When doing lookup when there is an import to a multiple definition becomes a problem.

It doesn't seem inappropriate that we can have modules that have identical signature definitions exported. It's also appropriate to report the ambiguity in this scenario. The error message is helpful in that it does list the candidates, and it can be seen they are in different files.

```
tests/check.slang(41): error 39999: ambiguous call to 'saturate' with arguments of type (vector<float,2>)
    v = saturate( (v + 1) / v);
                ^
tests/check.slang(25): note 39999: candidate: func saturate<float, 2>(float2) -> float2
hlsl.meta.slang(3247): note 39999: candidate: func saturate<float, 2>(float2) -> float2
```

If the modules were 'namespaced' could suggest constraining scope perhaps.

**Comment by natduca** [comment]
Closing, its hard to construct a case where this would be a high priority need for a customer.
