### ISSUE TITLE
Statically verify `anyValueSize` limitation regardless of whether dynamic dispatch is used

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#2580]
Currently if the user defines a type that exists the `anyValueSize` limitation defined in an interface, we will silently allow that to proceed until we are actually generating dynamic dispatch code. This can cause confusion. We should change the behavior to always statically check against the size limit during type check.

**Comment by natduca** [comment]
We have changed our design since this was filed to allow compiler to go above this limit. Obsolete.
