### ISSUE TITLE
Add semantics for explicit specialization control

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#2581]
Our users are reporting that seemly unrelated changes in their code suddently trigers dynamic dispatch on code that was originally specialized. We need to start developing the `some`/`any` semantics on our existential types to provide a more explicit control on what is allowed to be dynamic dispatched.

**Comment by expipiplus1** [comment]
An alternative would be to allow the user to explicitly specialize at sites.

Being able to decorate a function with a warning "please warn if this ever isn't specialized" would be welcome I think.

**Comment by csyonghe** [comment]
Just decorating the functions won't be sufficient. We also need a way to tell if a value (used as argument in a call) can be specialized or not. This would require us to introduce a systematic mechanism in the type system.

The `some` and `any` are distinct types on values to indicate if the value can be specialized. A `some` value means it will come from a specialized source and use it as argument in a call is treated as a specialized call. The `any` value means the compiler will try its best to specialize but specialization isn't guaranteed. With these, we can decorate a function by putting `some` on the parameters, and detect error when the user is trying to call a value with a type that cannot coerce to the `some T` type.

**Comment by expipiplus1** [comment]
How about:

```
func myCall<specialize MyMustBeSpecialized, MyMayNotBeSpecialized>(int maybeSpecialized, specialize int definitelySpecizlied) -> int;
```

here the `specialize` keyword instructs the compiler to fail (or warn in some permissive mode) if it is unable to specialize the type parameter `MyMustBeSpecialized` or the value parameter `definitelySpecizlied`. 

The current constraint syntax might make it tricky to require specialization of a dictionary but not a type, but that's obviously a very niche case.

**Comment by csyonghe** [comment]
Duplicate of #2210
