### ISSUE TITLE
More general obfuscation support

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2591]
In #2588 @csyonghe and @expipiplus1 appear to advocate for a more general obfuscation support.

As currently constructed, obfuscation is an all or nothing proposition. Either all of the modules are compiled with obfuscation enabled or none, with the exception of the stdlib which is always compiled without obfuscation. A limitation is it not possible to mix and match, at a module level or perhaps some other level of granularity. For common usage scenarios the all or nothing approach does provide what is commonly desired.

Adding a more generalized mechanism could be achieved fairly straightforwardly if there was an easy way to identify if a linkage symbol was obfuscated (such as some part of the encoding indicated as such). Additionally perhaps a module would mark if it had one or more items obfuscated. If there is any obfuscation in any (potential) module then linking would 

1) Try to lookup with the symbol it has, if it matches we are done
2) If the symbol is obfuscated, we require all non obfuscated symbols (if not already) to be added to lookup table and the lookup tried again 
3) If the symbol is not obfuscated, we obfuscate it and lookup tried again

Other than the more flexibility such an approach provides, it's added complexity does add some simplicity in not requiring special casing around stdlib.

**Comment by natduca** [comment]
Dropping for focus on things that harden the language. Can reopen if a specific customer requires.
