### ISSUE TITLE
Macro expansion location diagnostic

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2607]
Take the code section

```
#define DoFunc DoThing

//TEST_INPUT:ubuffer(data=[0 0 0 0 0], stride=4):out,name=outputBuffer
RWStructuredBuffer<uint> outputBuffer;

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{    
    int idx = int(dispatchThreadID.x);
    
    int r = DoFunc(idx);
    
    outputBuffer[idx] = r;
}
```

This code has a problem because `DoFunc` is a macro, that will be replaced with `DoThing`. So in effect `int r = DoFunc(idx);` is actually ` int r = DoThing(idx);` which doesn't exist so causes an error. The actual error displayed is 

```
thing.slang(46): error 30015: undefined identifier 'DoThing'.
#define DoFunc DoThing
               ^~~~~~~
```

Which is confusing, and loses important information - that the site of the problem is on the `int r = DoFunc(idx);` line. 

The macro expansion presumably inserts the location of the replacement into the token stream. That might be more helpful in some scenarios, although the application location would likely be more useful in most? Ideally we'd be able to produce a clang like diagnostic describing the macro replacement origin. Given that is probably a fair amount of effort, it may be preferable to make our default the macro application location.

**Comment by natduca** [comment]
Quality of life, but not a footgun. We are mostly prioritizing quality of life things that are footguns, so for now, closing as not planned
