### ISSUE TITLE
IRFunc objects referenced in witness tables are not guaranteed to be in the same module

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#262]
`getSpecializedFunc` assumes the function being specialized (`genericFunc` parameter) exists in the current module (as defined by `sharedContext`), and used this assumption to guarantee the specialized function is placed at the correct place.

```
        // Put the function into the global sequence right after
        // the function it specializes.
        //
        // TODO: This shouldn't be needed, if we introduce a sorting
        // step before we emit code.
        specFunc->removeFromParent();
        specFunc->insertAfter(genericFunc);
```

However, this assumption does not hold. When cloning symbols over to a new module in `specializeIRForEntryPoint`, the value references to witness tables are directly copied over without modification. However, a witness table entry may store a reference to an IRFunc, which may be generic and need to be specialized, thus passed to `getSpecalizedFunc()`.  But this is still an old reference to the IRFunc in the original module and not the one in the newly cloned module.

**Comment by tfoleyNV** [comment]
We definitely need to correctly clone witness tables and forward references from the old table to the new one! I hadn't realized we weren't doing that correctly.

The intention right now is that every `IRModule` is completely self-contained, and we should never be constructing modules that refer to values in another module. We currently violate that assumption a bit by sharing `IRValue`s for things like literals, but we really need to fix that too...

**Comment by tangent-vector** [comment]
This all seems to be working these days.
Closing.
