### ISSUE TITLE
SlangResourceShape missing constant-buffer

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#264]
Looks like it includes any type of resource except for CB. Is that intentional?

**Comment by tfoleyNV** [comment]
As things are implemented right now, `SlangResourceShape` is only meaningful if the type in question has the kind `SLANG_TYPE_KIND_RESOURCE`. That covers all the HLSL `*Texture*` and `*Buffer` types.

Constant buffers (whether GLSL `uniform` block, HLSL `cbuffer, or HLSL SM6 `ConstantBuffer<T>`) are currently reflected as a distinct "kind" of type (`SLANG_TYPE_KIND_CONSTANT_BUFFER`). The similar cases of HLSL `tbuffer` declarations and GLSL `buffer` declarations are similar in that they have their own distinct "kind."

I'm not saying the API is perfect, but it seems to provide the info you need, so I'm hesitant to change it unless we can identify a far better design.

**Comment by tfoleyNV** [comment]
@nbenty Okay to close this?
