### ISSUE TITLE
necessary changes to allow users to use custom filesystem.

### ISSUE THREAD

**Issue by WeakKnight** [shader-slang/slang#2672]
ISlangFileSystem is:
``` cpp
struct ISlangFileSystem : public ISlangCastable
    {
        virtual SLANG_NO_THROW SlangResult SLANG_MCALL loadFile(
            char const*     path,
            ISlangBlob** outBlob) = 0;
    };
```

To implement it, users need to create a Blob instance. However, we do not have interfaces like:
``` cpp
SLANG_API ISlangBlob* spCreateBlob(void* data, size_t size);
```

**Comment by csyonghe** [comment]
Exposing functions to create a blob can be useful. But it is still possible for the user to implement `ISlangBlob` themselves, the interface is also compatible with a `ID3DBlob` so they can use a d3d blob to serve as a `ISlangBlob` too.

**Comment by WeakKnight** [comment]
Implementing ISlangBlob is actually what I try to do at the beginning, but I do not know how to implement ISlangUnknown. Finally I solved my problems via compiling slang by myself and adding this interface.

**Comment by csyonghe** [comment]
Great to know you find out a solution! We will welcome a pull request from you if you feel like sharing your changes.

**Comment by csyonghe** [comment]
Btw, ISlangUnknown is fully compatible with the COM IUnknown interface so the same convention used to implement a COM interface will apply here.

**Comment by WeakKnight** [comment]
Thx, I am not familiar with Windows API and D3D API so I can not follow the context about COM. I will read more docs about COM.
