### ISSUE TITLE
Does Buffer.Load function expect an Int as location?

### ISSUE THREAD

**Issue by WeakKnight** [shader-slang/slang#2685]
![image](https://user-images.githubusercontent.com/12985760/222086731-fd7d2e12-ec31-4ef1-8031-85e114b6a778.png)
In Slang, if we do not use int type for Buffer.Load function, compiler will throw a warning "implicit conversion from 'uint' to 'int' is not recommended". I want to know whether it  is a design or a bug.

**Comment by csyonghe** [comment]
Closing this issue now. For now users can supress this warning with `-Wno-unrecommendedImplicitConversion` option. In the future we will add a level system for warnings and classify this into a lower-level warning that is disabled by default.
