### ISSUE TITLE
Crash when referring to a variable declared later in same function

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#274]
A Slang user ran into the issue that the following code leads to Slang crashing with an exception:

```
float dist = length(L);
float3 L = normalize(lightDir);
```

The code is erroneous, because the first line tries to reference `L` before it is declared, but that is obviously no excuse for us crashing.

I haven't triaged this yet, but given that the problem is a `Slang::KeyExistsException`, I wonder if checking `length(L)` is triggering `EnsureDecl()` on `L`, so that we end up checking it twice (explaining why a key is getting inserted into a dictionary when it already exists).

Cleaning up that issue would be easy given that we have `DeclCheckState` (we just need to check it for a `DeclStmt` - actually called `VarDeclrStmt` IIRC), but it doesn't really resolve the fundamental issue which is that the lookup table for a function's local variable scope has already been populated (by parsing) by the time we go to do semantic checking, so name lookup can find names declared later in the same function.

A crude way to solve this would be to force semantic checks to run as part of parsing (this is technically required to parse a C-like language, but we've been successfully flaunting this so far), so that we don't insert `L` for lookup until *after* we've checked `length(L)` here. Then we'd need to delay parsing of function bodies so that we can deal with out-of-order declarations (we've discussed this before). I suspect we may have to do that kind of two-phase parsing eventually, but it is a lot of complexity to solve a small issue.

Another option that I've considered in other projects, but haven't actually implemented (so this may not work) is that instead of having a `VarExpr` track a `RefPtr<Scope>` we would have it store both the `RefPtr<Scope>` and an integer for the "version" of the scope (we could make a compose `ScopeVersion` type that stores these).

In the simplest case, the "version" of a scope could be the number of declarations that have been added to the corresponding `ContainerDecl`. Every time a new declaration is added, that implicitly bumps the "version" on the container.

When doing lookup, we then specify a `ScopeVersion` instead of just a `Scope`. Lookup based on a `ScopeVersion` would ignore any declarations that are later in the list of members than the specified version.

Note: a simpler way to achieve a similar result is to have every new declaration in a function body introduce a new `Scope`. This has the down-side of turning lookup for local variables into a linear search, unless you get into really clever data structures.

The other benefit of something like a `ScopeVersion` is that instead of *ignoring* declarations that come later in the same scope, you could just emit a diagnostic that says "you are trying to refer to this variable that was defined later." We'd need to be careful with that because of HLSL/C rules around local variables shadowing function parameters with the same name, so that might be a Slang-only feature.

Just to close the loop on the design: when dealing with "unordered" scopes (e.g., a whole translation unit when writing Slang) you can just set the version on a `ScopeVersion` to `MAX_INT` and ensure that it can see everything that ever gets added. This would let us use more or less the same code for lookup across Slang and HLSL, while still preserving the need for in-order declarations in HLSL.

**Comment by tfoleyNV** [comment]
I implemented a bit of hacky workaround for this in #385, so most cases will now run into an error rather than a crash for code like this.

What my current solution doesn't get right is the scoping rules when a local variable "shadows" a variable from an outer scope:

```hlsl
float L = 1.0f;
{
  float N = L;
  float L = 2.0f;
}
```

In this example, the reference to `L` in the definition of `N` will be resolved to the *second* definition, because it is the one that is in the same scope where `N` is declared. A conventional C-like compiler would of course use the definition from the outer scope, because it hasn't "seen" the declaration of `L` yet.

There is still work to be done to get the expected behavior here, so #385 is only a fix for the crashing issues.
