### ISSUE TITLE
String and Char support in Kernels

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2775]
Slang offers some string behaviors. On GPU string literals are turned into hashes. On the CPU via the native_string type and via String it is possible to pass strings to functions. On CPU it is also possible to do some processing on strings, in the form of a character array, or perhaps stored in a resource.

For GPU not all targets support 8 bit types - in particular D3D doesn't. 

The kinds of situations that are motivating this issue  could be described as

1) Ability to do simple string based operations (like as atoi)
2) Ability to create new strings

If we have a large amount of small strings that need such processing this could lead to performance and convenience.

One feature that should be easy to add would be support for character literals. A starting point could be via `''` quoting, of ascii characters, with normal escaping. A more sophisticated approach would allow for unicode codepoints Although this implies a 32 bit "rune"-like type. Since `char` or `int8_t` aren't available on all targets it may make sense to just make our processing work on 32 bit values.

So 

```
uint c = 'a';
unit b ='\U0010FFFF`;
uint a = '\n';
unit d = 'utf8';
```

Where utf8 is some valid utf8 codepoint.

Next we need a way to process strings. This could perhaps be handled at least in some scenarios in user space. 

```
struct SmallAsciiString<let maxChars : int> 
{
    int getLength() { return m_length; }
    __subscript(uint index) -> uint
    {
        // Perhaps some kind of assert?
        if (index >= length) 
        {
            return 0;
        }   
        uint v = m_storage[index >> 2];
        v >>= ((index & 3) << 3);
        return v & 0xff;
    }
    
    [mutable] void setAt(uint index, uint c) { /* ... */} 
    
    bool equals(...) { /* ... */ }

    [mutable] void append(uint c)
    {
        // Etc...
    }

    int m_length;  
    uint m_storage[numWords];
};
```

Such strings *could* be passed via a buffer, and be directly compatible with C++ if host is little endian.

Another option is if strings are just being passed in to a kernel, this could be achieved via two resource buffers. One defines the start offset, and the other defines the characters. The characters could be encoded as ascii bytes using something similar to SmallString. The offsets can be the byte offsets. Accessing could be mainly a user space issue.

Other questions:

* How for a GPU kernel should we represent an actual string literal?
  * Ideally we could initialize SmallString with some literal in the kernel (ie not a hash)
* How to make this work across CPU/GPU ?
* How to make this work with strings of significantly different sizes?
* Do we need a rune/char type ?
  * Does it not automatically convert?

**Comment by jsmall-nvidia** [comment]
When discussed @csyonghe brought up that it might be a good idea to have some IR support for the access of byte chars such that the operation can be abstracted. 

Presumably that would look like a byte access on something that was backed by 32 bit integer type on a target.

Additionally this implies a type or decoration that identifies this is the desired access. The simplest situation from user language use is the use of char8/uint8_t/int8_t types. It would be possible to make that work on D3D that doesn't support this. 

```
struct SomeType
{
    char c;
};
``` 

On D3D could be turned into 

```
struct SomeType
{
    int c;
};
```

And 
`
```
struct SomeType
{
    char c[7];
};
```

Into (on D3D)

```
struct SomeType
{
   uint c[2];
}
```

And then when byte access occurs on D3D it will do the packing/extraction. 

This would of course impact layout. It implies a future version of D3D/HLSL that did support chars would use directly. This seems somewhat conceptually simple. And/or is there a need for a mechanism to mark that this style of emulation is required, such that it would be used *even if* available on D3D?

**Comment by jsmall-nvidia** [comment]
In more discussions it seems that what was being advocated for is a Slang supported SmallString type. That it would be generic on the maximum amount of characters it could hold. Having such a type would allow

* Varying behavior between the capabilities of targets
* Allow converting form (say) string literals
* Allow operations that could work at the string level (say such as concatenation)

Access to the string type could be through the index operator. On targets that supported char8 types the chars can be stored as such, on ones that can't the information could be encoded into 32 bit integer types. On a target that doesn't have char8 this would make the element return type presumably u/int32. On targets that support bytes it can be a byte.

Layout would need to handle the type. The types behavior could (?) change depending on the capabilities of the target. Lets say since the string is "small" the maximum N is 256, then we can store the length in a byte. If that is the case then emulation would vary the alignment and the overall size of a type. Perhaps to avoid layout altering on targets where emulation is available the alignment is fixed at 4 bytes regardless.

It

**Comment by natduca** [comment]
This is a great feature, but we need to do this when we have a customer to motivate and prioritize it. Marking closed for bankrupcy purposes.

**Comment by fknfilewalker** [comment]
> Slang offers some string behaviors. On GPU string literals are turned into hashes. On the CPU via the native_string type and via String it is possible to pass strings to functions. On CPU it is also possible to do some processing on strings, in the form of a character array, or perhaps stored in a resource.
> 
> For GPU not all targets support 8 bit types - in particular D3D doesn't.
> 
> The kinds of situations that are motivating this issue could be described as
> 
> 1. Ability to do simple string based operations (like as atoi)
> 2. Ability to create new strings
> 
> If we have a large amount of small strings that need such processing this could lead to performance and convenience.
> 
> One feature that should be easy to add would be support for character literals. A starting point could be via `''` quoting, of ascii characters, with normal escaping. A more sophisticated approach would allow for unicode codepoints Although this implies a 32 bit "rune"-like type. Since `char` or `int8_t` aren't available on all targets it may make sense to just make our processing work on 32 bit values.
> 
> So
> 
> ```
> uint c = 'a';
> unit b ='\U0010FFFF`;
> uint a = '\n';
> unit d = 'utf8';
> ```
> 
> Where utf8 is some valid utf8 codepoint.
> 
> Next we need a way to process strings. This could perhaps be handled at least in some scenarios in user space.
> 
> ```
> struct SmallAsciiString<let maxChars : int> 
> {
>     int getLength() { return m_length; }
>     __subscript(uint index) -> uint
>     {
>         // Perhaps some kind of assert?
>         if (index >= length) 
>         {
>             return 0;
>         }   
>         uint v = m_storage[index >> 2];
>         v >>= ((index & 3) << 3);
>         return v & 0xff;
>     }
>     
>     [mutable] void setAt(uint index, uint c) { /* ... */} 
>     
>     bool equals(...) { /* ... */ }
> 
>     [mutable] void append(uint c)
>     {
>         // Etc...
>     }
> 
>     int m_length;  
>     uint m_storage[numWords];
> };
> ```
> 
> Such strings _could_ be passed via a buffer, and be directly compatible with C++ if host is little endian.
> 
> Another option is if strings are just being passed in to a kernel, this could be achieved via two resource buffers. One defines the start offset, and the other defines the characters. The characters could be encoded as ascii bytes using something similar to SmallString. The offsets can be the byte offsets. Accessing could be mainly a user space issue.
> 
> Other questions:
> 
> * How for a GPU kernel should we represent an actual string literal?
>   
>   * Ideally we could initialize SmallString with some literal in the kernel (ie not a hash)
> * How to make this work across CPU/GPU ?
> * How to make this work with strings of significantly different sizes?
> * Do we need a rune/char type ?
>   
>   * Does it not automatically convert?

You say string literals are turned into hashes, can you show me the syntax for this.

**Comment by csyonghe** [comment]
Here's an example:
```
RWStructuredBuffer<int> output;

void main()
{
    output[0] = getStringHash("abcd");
}
```

**Comment by csyonghe** [comment]
Which can be queried from API with:
```
ProgramLayout::getHashedStringCount()
ProgramLayout::getHashedString()
```

**Comment by fknfilewalker** [comment]
Awesome, thank you
