### ISSUE TITLE
Specialization failure fails silently for DX11

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#2805]
Imagine

- maybeSpecializePipeline fails https://github.com/shader-slang/slang/blob/68c7d5cda2d6f2eb7bfb3a7e15860eb3ded25424/tools/gfx/d3d11/d3d11-device.cpp#L1426
- soon after, we set a null compute shader https://github.com/shader-slang/slang/blob/68c7d5cda2d6f2eb7bfb3a7e15860eb3ded25424/tools/gfx/d3d11/d3d11-device.cpp#L1240

Annoyingly, there's no Result return value from these immediate mode functions

**Comment by natduca** [comment]
This seems like dx11 so lets mark bankrupcy for now, can reopen if someone hits it.
