### ISSUE TITLE
Consider making SlangResult [[nodiscard]]

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#2806]
There are many places in the code where we silently ignore return values from functions returning `Result` or `SlangResult`. C++17 has the `[[nodiscard]]` attribute which encourages the compiler to warn when any value of an annotated type (or return value of an a annotated function) is discarded without being examined. 

This would necessitate making `SlangResult` its own type, rather than a typedef.

**Comment by natduca** [comment]
We considered putting this in q3 which tends to be where we've been putting core language cleanup topics. However, the ones we've put there so far are footguns where the language breaks in a bad way for the developer. This is a bit more borderline case so for favor of focus, putting as closed for bankrupcy reasons.
