### ISSUE TITLE
Make asserts more consistent

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#2858]
Our use of SLANG_ASSERT seems a little inconsistent; sometimes we're treating it as just a debug print and making efforts (returning `SlangResult::Fail` and handling that later for example), while other times we're treating it as "the program has gotten into an inconsistent or unreasonable state, so abort".

We should do a cleanup and split these into 

- SLANG_ASSERT, which aborts in debug builds and is `std::unreachable` in release builds
- `outputDebugMessage` for the case where we feel we can continue

**Comment by expipiplus1** [comment]
See also https://github.com/shader-slang/slang/issues/2858

**Comment by natduca** [comment]
I understand some actions have been taken. Probably lets close this for now, reopen when we have a forcing function to do this.
