### ISSUE TITLE
Shader resource views for multisample textures

### ISSUE THREAD

**Issue by kopaka1822** [shader-slang/slang#2881]
The shader resource views for multisample textures are not created correctly. Currently the D3D12_SRV_DIMENSION_TEXTURE2D enum will be used as view dimension instead of the D3D12_SRV_DIMENSION_TEXTURE2DMS, which results in device removal.

I fixed it and prepared a pull request here: https://github.com/shader-slang/slang/pull/2880

**Comment by csyonghe** [comment]
The PR looks good is and merged in. Thank you for fixing the issue!
