### ISSUE TITLE
Document Slang's behavior of enum/enum class being scoped

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2894]
Slang makes enums behave in a way akin to enum class irrespective to if defined as enum or enum class. DXC in contrast follows a similar behavior to C++, where enum makes values scope in the outer scope, and are convertible to integral types. 

```
enum Check : int { V = 1 };

// Works in DXC, fails in Slang first saying no V is found. If we scope we get an error no operator+ for type Check
int a = V + 1;
```

Since slang treats an enum like enum class this does work on both.

```
enum class Check : int { V = 1 };
int a = (int)Check::V + 1;
```

It could (?) be argued this is ok, but its a difference that isn't documented.

**Comment by natduca** [comment]
Proposing that this be resolved by documenting this as a feature-by-language design, eg we think its good that enums are scoped. Retitling to reflect, putting priority low for q2 as related to language refence

**Comment by csyonghe** [comment]
Our documentation already mentions this, so closing.
