### ISSUE TITLE
Expanded atomic support

### ISSUE THREAD

**Issue by jsmall-zzz** [shader-slang/slang#2926]
It would be useful to add support for

* Atomics in different kinds of memory (for example group shared memory)
* Atomic support for F32/F16 

For CUDA this would expose intrinics described [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions)

For D3D12 implementation can use NVAPI with `NvInterlockedAddFp16x2` and the like for F16. D3D12 [supports](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/interlockedadd) regular atomics on group shared memory variables. CUDA it seems needs intrinsics to distinguish.

On GLSL, there seem to be a variety of limitations around atomics. For example in `atomics-buffer.slang` claims atomics don't work on RWBuffer for VK.  

I also don't see any group shared memory atomics being tested in `tests`.

We could also consider implementing the CAS loop for targets that don't support atomic intrinsics directly.

**Comment by natduca** [comment]
putting in Q3, nice to have
