### ISSUE TITLE
Stdlib files cause language server to crash

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2931]
This was reported as a stack error onloading into VSCode, so I'm assuming this is the problem.

On the one hand this isn't super important, or perhaps surprising, because the slang meta files have C++ code, and $ expansions. Perhaps the simplest answer is to make the .meta.slang extension files not use the language server?

**Comment by csyonghe** [comment]
I can't reproduce the crash with TOT. It is probably triggered by typing something or some other interactions? Simply opening all the .meta.slang files doesn't seem to cause any crashes.

**Comment by csyonghe** [comment]
Close for now until we can find a way to consistently reproduce the crash.
