### ISSUE TITLE
Some CLI options get ignored

### ISSUE THREAD

**Issue by farnoy** [shader-slang/slang#2934]
I'm having an issue compiling slang to glsl/spv. It's ignoring switches like `-force-glsl-scalar-layout -matrix-layout-column-major` and they do not affect the output in any way.

Quick `repro.slang`:

```hlsl
struct CameraMatrices {
    float4x4 position;
};

ConstantBuffer<CameraMatrices> camera;

[shader("vertex")]
float4 main() : SV_Position {
    return float4(camera.position._11);
}
```

Compiled with

`$ slangc -force-glsl-scalar-layout -matrix-layout-column-major repro.slang -matrix-layout-column-major -o repro.glsl-matrix-layout-column-major -entry main -matrix-layout-column-major`

`$ slangc -force-glsl-scalar-layout -matrix-layout-column-major repro.slang -matrix-layout-column-major -o repro.spv-asm -matrix-layout-column-major -entry main -matrix-layout-column-major`

(I tried multiple positions just in case)

Produces GLSL & SPIR-V that happily uses row major, std140 laid-out structures.

```glsl
#version 450
layout(row_major) uniform;
layout(row_major) buffer;

#line 1 0
struct CameraMatrices_0
{
    mat4x4 position_0;
};


#line 5
layout(binding = 0)
layout(std140) uniform _S1
{
    mat4x4 position_0;
}camera_0;

#line 8
void main()
{

#line 8
    gl_Position = vec4(float(camera_0.position_0[0][0]));

#line 8
    return;
}
```

This is on version `v0.28.2`

**Comment by tangent-vector** [comment]
Hello. Thank you for posting your question here.

Matrix layout in the context of a cross-platform shading language is actually a bit of a thorny topic. In fact, we ended up writing a whole document to help explain what is going on in Slang:

https://github.com/shader-slang/slang/blob/master/docs/user-guide/a1-01-matrix-layout.md

The long/short of things is that matrix layout is one of the many cases where the conventions of HLSL/D3D and GLSL/Vulkan/SPIR-V/OpenGL differ. By far the simplest way to both understand and deal with the mismatch is to internalize that:

* What HLSL and Slang call "row major" is what GLSL/SPIR-V calls "column major"
* What HLSL and Slang call "column major" is what GLSL/SPIR-V calls "row major"

If you want GLSL and SPIR-V output with what that ecosystem calls "column major" layout, then you will want to request "row major" layout from Slang (or dxc, or even the HLSL front-end that was added to glslang).

**Comment by farnoy** [comment]
Thanks for the quick response.

I had not seen that documentation page, thank you. In that case, I want to use `-matrix-layout-row-major` with Slang, which outputs `layout(column_major) uniform;` in GLSL that matches the defaults I've been using in my previous shaders.

What about the scalar layout issue? I've seen the `-force-glsl-scalar-layout` switch working with a compute shader once, but it's not being applied in this repro case for a vertex shader.

**Comment by natduca** [comment]
Closing because I think from this exchange the documentation that exists actually covers this. If I'm missing something, and folks here see something that we should improve in docs/etc, free to reopen.
