### ISSUE TITLE
DXC handles compile time constant scenario that Slang does not

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2937]
Take the following code

```
Texture2D g_texture;
SamplerState g_sampler;
RWStructuredBuffer<float> outputBuffer;

float4 sample(float2 uv, float ofsX, float ofsY ) 
{ 
    return g_texture.SampleLevel(g_sampler, uv, 0.0, int2(ofsX, ofsY)); 
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
	uint tid = dispatchThreadID.x;
        float4 v = sample(float2(tid, tid + 1), 1, -1);
	outputBuffer[tid] = v.x;
}
```

This will compile on DXC, even though `SampleLevel` requires the offsets (ofsX, ofsY) to be compile time constant. This doesn't compile on slang as is, reporting that ofsX and ofsY have the requirement. If we change those params to be `constexpr` then compilation does work on DXC. If compilation is to SPIR-V though the GLSL output outputs a similar error about requiring the offsets to be compile time constants.

This issue can be somewhat worked around by making the function `[ForceInline]`.

**Comment by csyonghe** [comment]
The right behavior for Slang would be to require the `ofsX` and `ofsY` parameters to be declared as `constexpr`, and the compiler should fold the constants at call sites. For functions with `constexpr` parameters, we should specialize them with folded in constant values when emitting GLSL code.

**Comment by csyonghe** [comment]
#3139 fixes this issue by allow constexpr propagation to recognize loop counters and will automatically make the loop `ForceUnroll` and the callee `[ForceInline]`. So the following code should just work now:

```
float4 sample(float2 uv, float ofsX, float ofsY ) 
{ 
    return g_texture.SampleLevel(g_sampler, uv, 0.0, int2(ofsX, ofsY)); 
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
	uint tid = dispatchThreadID.x;
        for (int i = 0; i < 10; i++)
        {
              float4 v = sample(float2(tid, tid + 1), i+1, i-1);
              outputBuffer[tid] += v.x;
        }
}
```
