### ISSUE TITLE
Initializing group shared variables fails GLSL output 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2964]
Take the slang code...

```
groupshared uint someValue2 = 0 ;
```

When emitted to GLSL it appears as something like

```
uint someValue2_init()
{
    return 0U;
}

shared uint someValue2 = someValue2_init();
```

Which fails to compile on GLSLANG with the error 

```
glslang:  (249): error :  'shared' : initializer can only be a null initializer ('{}')
```

**Comment by expipiplus1** [comment]
We should move any initialization to the entry point and insert a call to `memoryBarrierShared`

**Comment by natduca** [comment]
We think this might also show up in the direct to spirv backend. So flagging as important to fix in context of spirv backend

**Comment by natduca** [comment]
@expipiplus1  are you actively driving this or should we unassign so others can take it?

**Comment by csyonghe** [comment]
@expipiplus1 can you let us know if you still plan to work on this?

**Comment by expipiplus1** [comment]
@csyonghe @natduca  I'll do this this week, should just be more or less a matter of selectively applying the existing global raising pass

**Comment by expipiplus1** [comment]
Looks like this was fixed anyway, I added a test.
