### ISSUE TITLE
Short circuit behavior for `&&` & `||`

### ISSUE THREAD

**Issue by jsmall-zzz** [shader-slang/slang#2969]
A previous PR #2733 changed `?:` to short circuit.

HLSL has `&&` and `||` as [not short circuiting](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-operators)

This is perhaps unfortunate in so far as it stops being able use these operators being used to guard evaluation.

**Comment by laurooyen** [comment]
According to [the release blog post for HLSL 2021](https://devblogs.microsoft.com/directx/announcing-hlsl-2021/#logical-operator-short-circuiting), they changed the behaviour of `&&`, `||` and `?:` to be short circuiting. They also introduced the `and()`, `or()` and `select()` intrinsics to get the old behaviour.

Having these operators short circuit would indeed be very usefull to guard evaluation.

**Comment by natduca** [comment]
We already do short cuircuiting of ternary operator, but we don't do it for && and or.
And, if we're supporting some aspects of glsl as input, we should at least this quarter decide which subset of this we want to support.
So putting in Q1 to at least poke at this enough to identify our opinion on how to do this directionally in the language.

**Comment by csyonghe** [comment]
Done.

**Comment by peterkutz** [comment]
Hello! What's the current state of short-circuiting for `&&` and `||`?

I noticed that the documentation still says it's not supported:
https://github.com/shader-slang/slang/blob/135610cf5a18290a120bccb8af90f4d1bb3cb1cb/docs/user-guide/02-conventional-features.md?plain=1#L394

However I also noticed that @csyonghe said "Done" above and that there seems to be a command-line option to _disable_ short-circuiting:
https://github.com/shader-slang/slang/blob/135610cf5a18290a120bccb8af90f4d1bb3cb1cb/docs/command-line-slangc-reference.md?plain=1#L345
