### ISSUE TITLE
Warning in scenarios where SampleState is ignored

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2983]
On some targets it is not possible to allow the separation of a texture from a sampler. The HLSL language supports `SamplerState` that allows a texture to be used with multiple sampler states. When using a target that doesn't allow separation we in effect ignore SamplerState. Ignoring is perhaps fine assuming there is only one SampleState ever used with the texture. The assumption being the programmer knows for that target the texture is in effect a combined texture sampler. 

In the scenario when there is more than one SamplerState being used with a texture, it would be useful to at least give a warning that, that is indeed the scenario. 

This could happen when the target is known. Another path might be to have a "compatibility" mode which provides a lowest common denominator compatibility.

**Comment by natduca** [comment]
Move this to bankrupcy for now, unless we have a user request to bring it back into priority.
