### ISSUE TITLE
Binding shifts not applied on HLSL variables with no explicit register

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#2986]
Using slang v2023.0.6 I am finding that binding shifts are not applied to samplers/textures/etc that do not have an explicit register syntax.

For example, using the command-line:

`slangc.exe test.hlsl -o test.hlsl.spv -profile glsl_450 -entry MainPs -enable-effect-annotations -stage fragment  -fvk-b-shift 0 0 -fvk-s-shift 14 0 -fvk-t-shift 30 0 -fvk-u-shift 158 0`

with the attached shader, g_sColor and g_tTexture will be assigned unshifted bindings:
```
               OpDecorate %g_tColor_0 DescriptorSet 0
               OpDecorate %g_tColor_0 Binding 3
               OpDecorate %g_sColor_0 DescriptorSet 0
               OpDecorate %g_sColor_0 Binding 4
```

However, if I change for example:

```
SamplerState g_sColor;
Texture2D g_tColor; 
```
to:
```
SamplerState g_sColor : register(s0);
Texture2D g_tColor : register(t0); 
```

The correct binding is applied:
```
               OpDecorate %g_tColor_0 DescriptorSet 0
               OpDecorate %g_tColor_0 Binding 30
               OpDecorate %g_sColor_0 DescriptorSet 0
               OpDecorate %g_sColor_0 Binding 14
```
This works with DXC and unfortunately is required for a lot of our shaders.

[test.hlsl.zip](https://github.com/shader-slang/slang/files/12050721/test.hlsl.zip)

**Comment by csyonghe** [comment]
Fixed by #3000 and #3004.
