### ISSUE TITLE
Attempting to backwards differentiate causes a Slang::InternalError

### ISSUE THREAD

**Issue by saada2006** [shader-slang/slang#2995]
I am working on a fork of Falcor and I need to backwards differentiate a function. Unfortunately, when I do so, it causes a Slang::InternalError.

This is the line that causes the error: https://github.com/saada2006/Falcor/blob/master/Source/RenderPasses/SVGFPass/SVGFReproject.ps.slang#L279

When I comment out this line, the shader compiles fine. Forward differentiation also works fine.

**Comment by csyonghe** [comment]
This should have been fixed with top of tree.
