### ISSUE TITLE
Support -fvk-invert-y (and possibly -fvk-use-dx-position-w)

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3006]
When using HLSL from DirectX the value of clip space y is inverted relative to Vulkan.  In DXC, there is the option `-fvk-invert-y` that:

"Negates (additively inverts) SV_Position.y before writing to stage output. Used to accommodate the difference between Vulkan's coordinate system and DirectX's. Only allowed in VS/DS/GS."

Without this option, I need to manually insert y negation into all of our vertex and geometry shaders.  The other option that was added to DXC was -fvk-use-dx-position-w.  This makes it so SV_Position.w matches the DirectX definition rather than gl_FragCoord.w which is inverted.

**Comment by csyonghe** [comment]
This is now supported.
