### ISSUE TITLE
[[vk::push_constant]] on global variables is ignored.

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3007]
I am finding that a push constant that I have in attached HLSL ends up being relocated as a regular constant into the global cbuffer.

Compiling the attached shader with:
`slangc.exe %1 -o %1.spv -profile glsl_450 -entry MainPs -enable-effect-annotations -stage fragment  -fvk-b-shift 0 0 -fvk-s-shift 14 0 -fvk-t-shift 30 0 -fvk-u-shift 158 0 -dump-intermediates`

You will see in the HLSL there is:
```
struct ExternalTestCB2_t 
{ 
    float2 g_vScaleBias ; 
    float2 g_vPad0 ; 
} ; 
[ [ vk::push_constant ] ] ExternalTestCB2_t ExternalTestCB2 ; 
```
In the intermediate GLSL this ends up being just a member of the global cbuffer instead of a push constant:
```
layout(binding = 0)
layout(std140) uniform _S2
{
    int g_nValue_0;
    vec3 g_vModulationColor2_0;
    vec3 g_vModulationColor3_0;
    float g_flPinch_0;
    ExternalTestCB2_t_0 ExternalTestCB2_0;
}globalParams_0;
```

[test_0_0_preprocessed_ps.zip](https://github.com/shader-slang/slang/files/12123729/test_0_0_preprocessed_ps.zip)

**Comment by csyonghe** [comment]
Our supported syntax for push constants is:
```
struct S
{
	float4 v;
}

[[vk::push_constant]]
ConstantBuffer<S> x;
```
The compiler only recognizes `[[vk::push_constant]]` when it is on a `ConstantBuffer`.

**Comment by danginsburg** [comment]
I can workaround this using the ConstantBuffer<S> syntax so it's fine if this is low priority, but as far as I know ConstantBuffer<S> is slang syntax and not HLSL, right?  Shouldn't an aim be to support the cbuffer syntax eventually for HLSL compatibility?

**Comment by danginsburg** [comment]
Ah, sorry, my mistake - DXC allows [[vk::push_constant]] with cbuffer syntax and I couldn't find in the docs where `ConstantBuffer<T>` was defined in HLSL.  Thanks for the pointer.
