### ISSUE TITLE
HLSL problem with binding shifts and global constant buffer

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3032]
Given I need a binding shift applied to the global constant buffer, there is no way I can figure out to do so without having overlapping descriptor bindings unless explicit register syntax is used.

For example:
```
float4 g_vGlobalValues; // This ends up in globals

cbuffer CBufferTest_t 
{
	float4 g_vCBuffer0Values;
};

struct VS_INPUT
{
	float3 vPositionWs : POSITION;
};

struct PS_INPUT
{
	float4 vColor;
};

PS_INPUT MainVs( VS_INPUT i )
{
	PS_INPUT o;
	o.vColor.rgba = g_vCBuffer0Values + g_vGlobalValues;
	return o;
}
```

If this is compiled without `-fvk-bind-globals 14 0` like this then both the `globalParams_0` will not get a binding shift applied and incorrectly get binding of 0:

```
slangc.exe test_vs.hlsl -o test_vs.hlsl.spv -profile glsl_450 -entry MainVs -enable-effect-annotations -stage vertex  -fvk-b-shift 14 0 -fvk-s-shift 58 0 -fvk-t-shift 218 0 -fvk-u-shift 482 0 -dump-intermediates
```

Will result in GLSL like:
```
layout(binding = 15)
layout(std140) uniform _S1
{
    vec4 g_vCBuffer0Values_0;
}CBufferTest_t_0;

#line 3
struct GlobalParams_0
{
    vec4 g_vGlobalValues_0;
};


#line 3
layout(binding = 0)
layout(std140) uniform _S2
{
    vec4 g_vGlobalValues_0;
}globalParams_0;
```
This is almost correct, if the binding shift had been applied to `globalParams_0 `it would be what I want.  So then I try to workaround it by explicitly giving a binding to global params with `-fvk-bind-globals 14 0`:
```
slangc.exe test_vs.hlsl -o test_vs.hlsl.spv -profile glsl_450 -entry MainVs -enable-effect-annotations -stage vertex  -fvk-b-shift 14 0 -fvk-s-shift 58 0 -fvk-t-shift 218 0 -fvk-u-shift 482 0 -fvk-bind-globals 14 0 -dump-intermediates
```
and now I get:
```
layout(binding = 14)
layout(std140) uniform _S1
{
    vec4 g_vCBuffer0Values_0;
}CBufferTest_t_0;

#line 3
struct GlobalParams_0
{
    vec4 g_vGlobalValues_0;
};


#line 3
layout(binding = 14)
layout(std140) uniform _S2
{
    vec4 g_vGlobalValues_0;
}globalParams_0;

```
Now globalParams_0 is at the right binding, but `CBufferTest_t_0` was given the same binding.

Ideally the behavior would be:
* Binding shift is applied to the global cbuffer if not explicitly specified
* If `-fvk-bind-globals` is specified, then that binding is used explicitly, but no other binding should overlap with it (i.e. in this case `CBufferTest_t_0` would be automatically placed at 15).

**Comment by csyonghe** [comment]
#3033 Partially fixes this issue by making global constant buffer binding subject to `-fvk-b-shift` when `-fvk-bind-globals` is not present. However it does not fix the desired behavior when both `-fvk-b-shift` and `-fvk-bind-globals` exists. This requires us to reimplement the shifting logic. 

@jsmall-nvidia Currently we allocate the bindings, then apply the shift. To implement the desired behavior here, we need to take vulkan shift into account when we allocate the bindings.

**Comment by danginsburg** [comment]
#3033 fixes my problem, I think this can be closed.  In any case where `-fvk-bind-globals` would be used, I think it's safe to assume everything will have explicit descriptor bindings.

**Comment by csyonghe** [comment]
OK, closing now. We can work on a full fix later if is required.
