### ISSUE TITLE
Support for SPIR-V/Vulkan specialization constants

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#3044]
SPIR-V has support for specialization constants. These constants allow for the changing of behavior of a SPIR-V kernel without having the source available, which can be important for some use cases. 

There is support in HLSL/DXC via

```
[[vk::constant_id(0)]] const int someConstant = 0;
```

So presumably we would want to support the HLSL syntax, and this would be a Vulkan/SPIR-V only feature.

The emitted GLSL should use `constant_id` layout as below  

```
layout(constant_id = 0) const int someConstant = 0;
```

Other links:

* [DXC/HLSL support](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#specialization-constants)
* [KHR_vulkan_glsl specialization constant](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt)
* [Discussion on stackoverflow](https://stackoverflow.com/questions/66433585/vulkan-array-of-specialization-constants)

**Comment by csyonghe** [comment]
The reason we haven't really ramped up our support for global generic consts is that if they are used to declare a global array parameter, they can affect the layout and makes reflection tricky.

However, many use cases are really irrelevant to that, when they are just using the constant in bodies of the functions and expect the compiler to specialize out `if` branches. We should definitely make sure we support that use case first.

Perhaps we should consider also adding a first class syntax in addition to the attribute syntax to make it a more native part of the language.

**Comment by natduca** [comment]
We will treat this as a feature we'll do when we have a customer blocked on it.

**Comment by SelfishOlex** [comment]
Is this still not planned to support specialization constants for Vulkan/Spir-V generation? It's an odd feature to drop support for.

**Comment by csyonghe** [comment]
@SelfishOlex This is already implemented in latest release. You can use [vk::constant_id(0)] or [SpecializationConstant] on a global const variable to make it a specialization constant.
