### ISSUE TITLE
ParameterBlock reflection

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#305]
I'm wondering if it will make sense to explicitly expose the variables in the block as a ConstantBuffer type (instead global variables inside the block).

Currently in the code I just convert `Kind::ParameterBlock` to 'Type::ConstantBuffer`.

It would also help to get the block type (i.e. `Material`)

**Comment by tfoleyNV** [comment]
> I'm wondering if it will make sense to explicitly expose the variables in the block as a `ConstantBuffer` type (instead global variables inside the block).

Hmm... I think the right mental model here is to think of `ParameterBlock<T>` and `ConstantBuffer<T>` as being two subclasses of a common base class (I suppose `TextureBuffer<T>` would be another sibling, but so far we've never run into anybody using HLSL `tbuffer` declarations...). So it isn't that you want to get at the stuff inside a block as a constant buffer - you just want to treat the entire block *as* a constant buffer.

I'm not sure what you mean by "global variables inside the block" - the fields of the element type of a parameter block are no different from the fields of a CB, so if you'd reflect `SomeCB.diffuse` then why wouldn't you also reflect `gSomeParameterBlock.diffuse`?

> It would also help to get the block type (i.e. `Material`)

This should be what `getElementTypeLayout()` gives you on a `ParameterBlock<Material>`. The fact that it isn't returning the type name seems to be a bug.

**Comment by tangent-vector** [comment]
I think parameter block reflection is working now. I need to double check reflection of type names is working, but that should be a different issue.
