### ISSUE TITLE
HLSL matrices fetched from ByteAddressBuffer are transposed

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3084]
When I move data from being stored in a ConstantBuffer into a ByteAddressBuffer, all of the matrices are transposed.  We encountered this same issue in DXC originally, although it was eventually fixed, I believe as part of this https://github.com/microsoft/DirectXShaderCompiler/issues/3370.

**Comment by csyonghe** [comment]
Is the matrix typed field decorated with `column_major`?

**Comment by danginsburg** [comment]
> Is the matrix typed field decorated with column_major?

No, it is `row_major`.  I'll try to gather more info from you once we get shader debugging sorted, it will help me understand the problem better.

**Comment by csyonghe** [comment]
Fixed by #3101.
