### ISSUE TITLE
HLSL SV_InstanceId not supported in pixel shader

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3087]
The following shader fails to compile:
```
struct PSInput
{
    uint vInstance : SV_InstanceID;
	float4 color : COLOR;
};

float4 MainPs(PSInput input) : SV_TARGET
{
	return input.color + float(input.vInstance).xxxx;
}
```

with output:

```
slangc.exe sv_instance.hlsl -o sv_instance.hlsl.spv -profile glsl_450 -entry MainPs -enable-effect-annotations -stage fragment -fvk-b-shift 0 0 -fvk-s-shift 14 0 -fvk-t-shift 30 0 -fvk-u-shift 158 0 -dump-intermediates
glslang:  sv_instance.hlsl(7): error :  'gl_InstanceIndex' : undeclared identifier
glslang:  sv_instance.hlsl(7): error :  '' : compilation terminated
glslang: note : ERROR: 2 compilation errors.  No code generated.
```

This can be worked around by passing the SV_InstanceID from VS -> PS.

**Comment by csyonghe** [comment]
This is a GLSlang limitation, and we will need to wait until the SPIRV backend is ready before we can fix this issue.

**Comment by natduca** [comment]
Putting in Q2 since we're trying to get spirv backend stable in Q1, then we can get to this after

**Comment by csyonghe** [comment]
DXC generates this:
```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %MainPs "MainPs" %in_var_SV_InstanceID %in_var_COLOR %out_var_SV_TARGET
               OpExecutionMode %MainPs OriginUpperLeft
               OpSource HLSL 600
               OpName %in_var_SV_InstanceID "in.var.SV_InstanceID"
               OpName %in_var_COLOR "in.var.COLOR"
               OpName %out_var_SV_TARGET "out.var.SV_TARGET"
               OpName %MainPs "MainPs"
               OpDecorate %in_var_SV_InstanceID Flat
               OpDecorate %in_var_SV_InstanceID Location 0
               OpDecorate %in_var_COLOR Location 1
               OpDecorate %out_var_SV_TARGET Location 0
```

There is no special `Builtin` decoration applied, so my understanding is that the vertex shader still needs to write instanceID explicitly as a vertex output for this shader to work. So this is not really simplifying anything in the user code. 

@danginsburg Am I missing anything here?

**Comment by danginsburg** [comment]
> There is no special Builtin decoration applied, so my understanding is that the vertex shader still needs to write instanceID explicitly as a vertex output for this shader to work. So this is not really simplifying anything in the user code.

Right, it's just that DXC/fxc allow SV_InstanceID to be used as a PS input semantic when it is passed from the VS.  It's something HLSL allows, but I worked around it locally by changing:

```
struct PS_INPUT
{
	float4 vPositionPs : SV_Position;
	float3 vPositionWs : TEXCOORD0;
	uint nInstanceID : SV_InstanceID;
};
```

to:

```
struct PS_INPUT
{
	float4 vPositionPs : SV_Position;
	float3 vPositionWs : TEXCOORD0;
	nointerpolation uint nInstanceID : TEXCOORD1;
};
```

It's not an important feature but is something HLSL allows.
