### ISSUE TITLE
HLSL [[vk::builtin("PointSize")]] not supported, does slang have another syntax for it?

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3088]
In DXC, there is a way to specify Vulkan built-in variables that don't have an HLSL analogue:

https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#builtin-variables

One of our shaders in particular is using `[[vk::builtin("PointSize"]]`.  Using it yields:

```
error 31000: unknown attribute 'vk_builtin'
```

Is there another way to specify this in slang?  If not, could the HLSL syntax be adopted?

**Comment by csyonghe** [comment]
You can use `SV_PointSize` semantics.

**Comment by danginsburg** [comment]
OK, that should work.  Shaders coming from DXC will need to change to that syntax if you don't support vk::builtin.  That's fine for us, feel free to close.
