### ISSUE TITLE
Output user defined error in program linkage error message

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#310]
The user-specified error string from an HLSL #error macro doesn't show up in the error message later.

For example:
`#error Function A is not implemented`
generates:

```
Program Linkage failed.

Program with Shaders:
Framework/Shaders/TextRenderer.vs.slang/*main*/
Framework/Shaders/TextRenderer.ps.slang/*main*/

C:\Work\GIT\Falcor\Bin\x64\Debug\Data\Framework\Shaders\TextRenderer.vs.slang(28): error 15900: #error: user-defined warning
```

**Comment by tfoleyNV** [comment]
This is something I've been meaning to get back to eventually, as part of the fit and finish on the preprocessor, but just haven't had the time. Thanks for getting it into the issue tracker.

Is this something you want fixed ASAP, or just a nice-to-have?

**Comment by nbenty** [comment]
It's more a nice-to-have feature, the filename and line are accurate.
