### ISSUE TITLE
Warning 39001 can't be fully disabled, also it's a bit of a questionable warning

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3108]
Given a shader like the following: https://shader-playground.timjones.io/bf04ddc45bbb59ea22e72ae44b975cbb

You will get the following warnings:
```
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(3): warning 39001: explicit binding for parameter 'g_bindlessTexture3D' overlaps with parameter 'g_bindlessTexture2D'
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(3): warning 39001: explicit binding for parameter 'g_bindlessTexture3D' overlaps with parameter 'g_bindlessTexture2D'
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
```

Even after adding `-warnings-disable 39001`, slang will still output messages even though the warning was disabled:

```
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
[[vk::binding(1,0)]] Texture3D g_bindlessTexture3D[];
                               ^~~~~~~~~~~~~~~~~~~
C:\local\Temp\18e3445b-3ae1-4599-b168-0ed57a2ccf1d.slang(2): note: see declaration of 'g_bindlessTexture2D'
```

I also think this warning is slightly questionable in the case of bindless resources - I think having overlapping bindings is the normal way one implements bindless texturing, having a descriptor for each texture type.  

That being said, this bug is really just about the fact that disabling this warning still produces output when it shouldn't.

**Comment by tangent-vector** [comment]
In the past we have had customers insist this warning is useful to them, but it might be reasonable to revisit whether that is still the case. Certainly as user-space bindless idioms become more and more common, it seems more likely to give false positives than to diagnose actual issues.

At the very least, we will work to make sure that disabling the warning actually works as it should. In the best case, maybe we can just eliminate this warning or make it opt-in.

**Comment by danginsburg** [comment]
> In the past we have had customers insist this warning is useful to them, but it might be reasonable to revisit whether that is still the case. 

I agree that the warning can be useful in general.  Maybe there should be a syntax to declare a resource as purposely having overlapping bindings so that in the cases where developers have done this intentionally they can tell the compiler?  It is frankly somewhat counter intiuitive to me that the way bindless texturing works is that you have to declare multiple arrays of the same type at single binding.  Marking them as "bindless" or "overlapping" or something might make it more clear to the reader in addition to the compiler.
