### ISSUE TITLE
Dynamic Resources And Texture Footprint Queries

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#3110]
In https://github.com/shader-slang/slang/pull/2970 support was added for texture footprint queries. 

On D3D this is implemented using NVAPI. The NVAPI feature requires supplying the binding (register/space) of the resource to be queried to be passed in as integer values. The original implementation achieved the appropriate behavior by looking for IRBindingQuery derived instructions. It introduces parameters of the bindings from the call site that then are passed down and are available at the footprint intrinsic. As it stands it does so looking for the static global binding that is associated with the originating call.

This means as it stands a shader that dynamically references a resource, cannot compile. Take the example below...

```
uniform Texture2D textures[] : register(t2, space10);
uniform SamplerState sampler;
uniform RWStructuredBuffer<uint> outputBuffer;

Texture2D getTexture2d(uint texIdx)
{
    return textures[NonUniformResourceIndex(texIdx)];
}

cbuffer Uniforms
{
    uniform float2 coords;
    uniform uint granularity;
};

void fragmentMain(
    float v : VARYING)
{
    uint index = uint(v);
   TextureFootprint2D f = getTexture2d(index).queryFootprintCoarse(granularity, sampler, coords);
   
    outputBuffer[index] = f.mask.x;
} 
```

What is needed here is for *index* to be taken into account when calculating the binding. In this example this is relatively straight forward in that it is `(2 + index, 10)`. This calculation can be produced by working out the path the the resource, and then using layout to determine how to calculate the binding. 

Ideally an implementation would allow this and more complicated dynamic resource usage to work, at least until there is parity with VK.

**Comment by csyonghe** [comment]
This should be fixed with the recent texture intrinsics clean up. We no longer inline the call so the texture remain used.
