### ISSUE TITLE
Incorrect OpDecorate usage for RowMajor

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#3119]
> error: line 9: RowMajor can only be applied to structure members
>   OpDecorate %mat4v4float RowMajor

To reproduce:

- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/column-major.slang`
- Observe that the OpDecorate ... RowMajor instruction doesn't have anywhere to apply to, we'll need to synth a struct and apply it to a member of that :/

Other failing tests:

- tests/compute/column-major.slang
- tests/compute/row-major.slang
- tests/compute/non-square-column-major.slang
- tests/compute/non-square-row-major.slang
- tests/compute/kernel-context-threading.slang
- tests/compute/texture-sample-grad-offset-clamp.slang
- tests/compute/structured-buffer-of-matrices.slang

**Comment by csyonghe** [comment]
Fixed by #3137.
