### ISSUE TITLE
Correct cross compile tests for SPIR-V

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#3124]
- tests/compute/comma-operator.slang, the glsl comparison fails to compile with `unexpected: no matching IR symbol`

Cross compile tests:

- tests/compute/half-texture.slang

**Comment by csyonghe** [comment]
@expipiplus1 are there any additional work to be done here? Looking at the mentioned tests it seems all tests are enabled now?

**Comment by csyonghe** [comment]
Closing as I no longer see any actionable items.
