### ISSUE TITLE
Some missing intrinsics for SPIR-V

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#3125]
We should diagnose on this also instead of asserting

To reproduce:

Parse failures:

- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/half-rw-texture-convert.slang`
- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/half-rw-texture-convert2.slang`
- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/rw-texture-simple.slang`
- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/texture-simple.slang`
- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/texture-simpler.slang`
- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/ray-tracing-inline.slang`

Predicate failures:

- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/half-vector-compare.slang`
- `./bin/linux-x64/debug/slangc -entry computeMain -stage compute -target spirv tests/compute/vector-scalar-compare.slang`

**Comment by csyonghe** [comment]
These are all fixed.
