### ISSUE TITLE
Improve barrier lowering to GLSL

### ISSUE THREAD

**Issue by farnoy** [shader-slang/slang#3152]
https://github.com/shader-slang/slang/blob/ef4c9f1f1c297f1a33be95795a7a7561e0cc3bde/source/slang/hlsl.meta.slang#L2504

https://github.com/shader-slang/slang/blob/ef4c9f1f1c297f1a33be95795a7a7561e0cc3bde/source/slang/hlsl.meta.slang#L1036

I believe these can be consolidated into one statement each with [GL_KHR_memory_scope_semantics](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_memory_scope_semantics.txt).

So ` __target_intrinsic(glsl, "memoryBarrier(), groupMemoryBarrier(), memoryBarrierImage(), memoryBarrierBuffer()") ` would become ` __target_intrinsic(glsl, "memoryBarrier()") `, which is equivalent to the following, written more explicitly:

```
__target_intrinsic(glsls, "memoryBarrier(gl_ScopeQueueFamily,
                                         gl_StorageSemanticsBuffer | gl_StorageSemanticsShared | gl_StorageSemanticsImage,
                                         gl_SemanticsAcquireRelease")
```

I'm compiling slang -> glsl -> spirv, and I end up with a combo of `OpMemoryBarrier` and `OpControlBarrier` when using `GroupMemoryBarrierWithGroupSync()`, which produces two stalls in nsight - MEMBAR & THDBAR. Seems suboptimal.

**Comment by csyonghe** [comment]
Using just `memoryBarrier` will result in only a single `OpMemoryBarrier` being generated. Is the `OpControlBarrier` not needed here? `GroupMemoryBarrierWithGroupSync` has the sync semantics also.

**Comment by farnoy** [comment]
For `GroupMemoryBarrierWithGroupSync()` specifically, I believe it should just be a `barrier()`, or the same thing explicitly: `controlBarrier(gl_ScopeWorkgroup, gl_StorageSemanticsShared, gl_SemanticsAcquireRelease)`. This would then translate to a single `OpControlBarrier` (but it includes the memory barrier naturally)
