### ISSUE TITLE
Basic amplification shader not compiling

### ISSUE THREAD

**Issue by Dynamitos** [shader-slang/slang#3182]
I want to try out the new mesh shading extensions and compile a basic amplification shader for meshlet culling.

For now i want to compile it though the cli tool to get a simple example to compile before integrating it into the renderer.

However, the following shader doesn't compile:

    struct Payload
    {
	    uint num;
    };
    
    [shader("amplification")]
    [numthreads(32, 1, 1)]
    void taskMain(uint threadID: SV_DispatchThreadID)
    {
	    Payload p;
	    p.num = threadID;
	    DispatchMesh(1, 1, 1, p);
    }

When compiling with `.\slangc.exe .\test.slang -profile sm_6_6 -target spirv -capability spirv_1_5 -entry taskMain`, the error reads

    glslang:  ./test.slang(12): error :  'DispatchMesh' : no matching overloaded function found
    glslang:  ./test.slang(12): error :  '' : compilation terminated
    glslang: note : ERROR: 2 compilation errors.  No code generated.

From this i guess that the hlsl `DispatchMesh` function is passed through to glslang without being resolved, so i tried to skip glsl with `-emit-spirv-directly`, which resulted in

    hlsl.meta.slang(5569): error 29000: unable to parse target intrinsic snippet: DispatchMesh
    hlsl.meta.slang(5569): error 29000: unable to parse target intrinsic snippet: DispatchMesh
    hlsl.meta.slang(5569): error 29000: unable to parse target intrinsic snippet: DispatchMesh

As far as I can tell there is not handling for the `DispatchMesh` hlsl intrinsic, which should probably be translated to `EmitMeshTasksEXT`, though there are some differences since the payload is handled differently.

Is there some command line option I'm missing, since I also had to add `-capability spirv_1_5` before, or some sort of workaround? Thank you in advance.

**Comment by expipiplus1** [comment]
Thank you for the report.

[I've implemented amplification shader support](https://github.com/shader-slang/slang/pull/3190), an example/test is here: https://github.com/shader-slang/slang/blob/09854a4596019ddb3bb315b8836b5c88e718cdc7/tests/pipeline/rasterization/mesh/task-groupshared.slang

The direct SPIR-V backend is still under construction, but it should all be working with the glslang and dxc backends.
