### ISSUE TITLE
Support use of specialized type as generic argument

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#325]
The following code triggers an unimplemented case at `findWitnessTable`, where `irVal->op == kIROp_specialize`. Also need to handle such uses in other places such as `IRSpecContext::maybeCloneValue`.
```
// TODO: We might eventually have cases of `specialize` called
// on a witness table...
```
Test case:

`generic-struct-with-constraint.slang`:

```
//TEST(smoke,compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out
// Confirm that generics syntax can be used in user
// code and generates valid output.

RWStructuredBuffer<float4> outputBuffer;

interface IElement
{
    float4 getValue();
};

struct SingleElement : IElement
{
    float4 value;
    float4 getValue()
    {
        return value;
    }
};

struct ListElement<THead : IElement> : IElement
{
    THead head;
    float4 getValue()
    {
        return head.getValue();
    }
};

float4 test<T : IElement>(T val)
{
	return val.getValue();
}


[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    ListElement<SingleElement> list;
    list.head.value = float4(1.0);
    float4 outVal = test(list);
	outputBuffer[0] = outVal;
}
```

**Comment by csyonghe** [comment]
Never mind, this is actually because I need to call `test<ListElement<SingleElement>>(list)` instead of `test(list)`.
We need to add automatic witness argument deduction some time.
Closing this issue for now.

**Comment by csyonghe** [comment]
Well, changing it to `test<ListElement<SingleElement>>(list)` still crashes the compiler. I need to track further.

**Comment by csyonghe** [comment]
OK, this is because we currently have not implemented the case where the declRef points to a specialization instead of a simple struct type in `findWitnessTable`.

**Comment by tfoleyNV** [comment]
Ah yes. I think that in this case we need to support something like a generic witness table, and then specialize the witness table (which means make a clone of it with specialized methods).

We should probably first search for a witness table using the mangled name of the specialized type, and then I’d that search fails do another lookup using the unspecialized type name do find a table we can specialize.

**Comment by tfoleyNV** [comment]
Your point about needing to support witness tables when doing implicit generic specialization is also correct: we can’t really have usable syntax without it. Let’s open a separate issue for that (if we don’t already have it).

**Comment by csyonghe** [comment]
Working on this now, almost there.

**Comment by tfoleyNV** [comment]
Great! And obviously while I’m away feel free to do your own reviews and use admin permissions to check in as needed.
