### ISSUE TITLE
Cuda support on a non-cuda system causes non-cuda apis to be marked as not supported

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#3255]
- Compile with `--cuda-sdk-path` and `--optix-sdk-path` set to enable cuda support
- Be in an environment without `libcuda.so.1`
- Run slang-test
- Observe that it marks every API as Not Supported

`LD_DEBUG=all` shows us that it's because `librender-test-tool.so` fails to load because it can't locate `libcuda.so.1`. Because we can't even load `librender-test-tool.so`, every api is deemed unavailable.

**Comment by natduca** [comment]
The test harness is fragile. But we can work around this for now with contributing guide and longer term we'll beef up our efforts on the test harness that should rediscover this issue. For now, closing.
