### ISSUE TITLE
`frexp` in CUDA accepts `int *` as the second argument

### ISSUE THREAD

**Issue by chenzhekl** [shader-slang/slang#3282]
Unlike `frexp` in HLSL where both parameters are of the same type. `frexp` in CUDA accepts only `int *` as the second argument.

```
__device__​ float frexpf(float x, int* nptr)
__device__​ double frexp(double x, int* nptr)
```

This is the incorrect CUDA code slang generated:

```
float exp_0;
float _S1 = frexp(12.00000000000000000000, &exp_0);
```

for

```
float exp;
frexp(12.0f, exp);
```

**Comment by csyonghe** [comment]
@chenzhekl Slang v2023.4.3 is now available, which includes the fix.

**Comment by chenzhekl** [comment]
@csyonghe Thank you so much for you work! I can confirm that it works flawlessly.

**Comment by csyonghe** [comment]
Thanks for confirming!
