### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#3283]
I am surprised that there is no CMake support, It would be really nice to have CMake scripts for slang.

**Comment by LesleyLai** [comment]
Agreed. Lack of CMake support (and thus hard to build it on multiple platforms) is the main reason I haven't tried this project yet.

**Comment by csyonghe** [comment]
@fknfilewalker @LesleyLai We do provide binary releases for both Windows and Linux. Which platforms are you on? 
We can certainly consider providing CMake build files if that is blocking adoption.

**Comment by LesleyLai** [comment]
Windows and Linux cover my needs, though I generally find building from sources much easier to deal with compared to prebuilt binary.

I see that there is also a [vcpkg port of slang](https://vcpkg.roundtrip.dev/ports/shader-slang) though I am not sure how well maintained it is

**Comment by natevm** [comment]
+1.

CMake is the industry standard when it comes to C++ development. It has its faults for sure, but still, it’s ubiquitous, especially in computer graphics.

If slang were to have some official CMake support, even if it were just a guideline on how to incorporate slang into an existing CMake project, that would probably help adoption quite a bit.

**Comment by natduca** [comment]
Ellie is on this so setting assignee, and since its in progres putting it onto Q1 but also putting the priority to low to reflect that this might get preempted if something more urgent for this quarter comes up.

**Comment by gdianaty** [comment]
+1

Regarding @LesleyLai's comment about vcpkg, the current port downloads binaries from GitHub and unzips them into the installed packages directory. Obviously this prevents project-specific dependency wrangling (e.g. slang-gfx library is unconditionally imported). If dependency wrangling is handled via CMake, much of the current Premake complexity in Slang can be reduced as well.
