### ISSUE TITLE
Missing compiler warning when attempting to autodiff code that uses shared memory

### ISSUE THREAD

**Issue by NBickford-NV** [shader-slang/slang#3289]
Hi Slang team! I've been appreciating Slang's errors when I attempt to add `[BackwardDifferentiable]` to code that uses non-differentiable functions, but I think I ran into a case where a warning or error is missing.

Here's a function that broadcasts a value from thread 5 to all other threads in the group using shared memory (note: this code assumes there aren't reads of `s_shared` pending when thread 5 enters this function; otherwise it has a RaW hazard and needs an extra `GroupMemoryBarrierWithGroupSync()` at the top of the function):

```hlsl
groupshared float s_shared;

[BackwardDifferentiable]
float get_thread_5_value(float v, uint group_thread_id)
{
  if(5 == group_thread_id)
  {
    s_shared = v;
  }
  GroupMemoryBarrierWithGroupSync();
  return s_shared;
}
```

I'm calling it using a kernel that looks like this:

```hlsl
[shader("compute")]
[numthreads(128, 1, 1)]
void example_kernel(uint3 group_thread_id : SV_GroupThreadID, uint3 dispatch_thread_id : SV_DispatchThreadID)
{
  DifferentialPair<float> value = diffPair(g_in[dispatch_thread_id.x], 0.f);
  
  bwd_diff(get_thread_5_value)(value, group_thread_id.x, 1.0f);
  
  g_out[dispatch_thread_id.x] = value.d;
}
```

When compiled for CUDA (I haven't tested other targets), Slang 2023.4.1 produces code that always returns a differential of 0, without warnings or errors:

```cuda
__device__ void s_bwd_prop_get_thread_5_value_0(DiffPair_float_0 * dpv_1, uint group_thread_id_1, float _s_dOut_0)
{
    DiffPair_float_0 _S1 = *dpv_1;
    if(5U == group_thread_id_1)
    {
        *(&s_shared_0) = _S1.primal_0;
    }
    __syncthreads();
    dpv_1->primal_0 = (*dpv_1).primal_0;
    dpv_1->differential_0 = 0.0f;
    return;
}
```

I think the correct backward derivative looks something like this; since this is complex and uses more shared memory than the original function, maybe it would be good for now to produce a warning or an error if someone tries to autodiff a function that accesses shared memory?

```hlsl
// For a variable x, let x_i be the value of x in the i'th thread in the group.
// Suppose we have y_i = v_5 and dR/dy_i = dResult_i.
// What's dR/dx_i?
// Well, it's sum(dR/dy_j dy_j/dx_i, j)
//         == sum(dResult_j (1 if i==5 else 0), j)
//         == sum(dResult_j, j) if i==5, else 0

// Used to compute the sum of dResult across all threads
// Side note: it would be nice if there was an intrinsic like WaveActiveSum for
// the whole group, but this isn't too much work to implement.
// Supposing the input has 128-thread groups and the GPU uses 32 threads/warp:
static const uint warps_per_group = 128/32;
groupshared float s_sum_shared[warps_per_group];

[BackwardDerivativeOf(get_thread_5_value)]
void get_thread_5_value_bwd(inout DifferentialPair<float> v, uint group_thread_id, float dResult)
{
  float warp_sum = WaveActiveSum(dResult);
  if((group_thread_id & 31) == 0)
  {
    s_sum_shared[group_thread_id/32] = warp_sum;
  }
  GroupMemoryBarrierWithGroupSync();
  if(5 == group_thread_id)
  {
    float group_sum = 0.0f;
    for(uint i = 0; i < warps_per_group; i++)
    {
      group_sum += s_sum_shared[i];
    }
    v = diffPair(v.p, group_sum);
  }
}
```

I've attached a few test .slang files and the results of transpiling them on Slang 2023.4.1 with `-target cuda`.

Thanks!

[test-autodiff-shared-memory.zip](https://github.com/shader-slang/slang/files/13172147/test-autodiff-shared-memory.zip)

**Comment by csyonghe** [comment]
I agree that there should at least be a warning when a differentiable function is attempting to access a shared memory location.

We can support something like `no_diff(g_shared = value);` to allow the user to suppress the warning.
