### ISSUE TITLE
Can't get list of used uniforms in constant buffer via spIsParameterLocationUsed

### ISSUE THREAD

**Issue by n3b** [shader-slang/slang#3296]
I might be missing something, but can't figure out how do I do that. 

It seems like the scope of the `spIsParameterLocationUsed` is not expressive enough to describe the query. I tried different combinations of the category (none/cbuffer/uniform), space (none/offset), index (none/register), but neither of those returned true for the query. Technically I get false even for the cbuffer var itself, which I think is definitely wrong.

Am I missing something or is it designed this way?

**Comment by natduca** [comment]
@tangent-vector  to respond
