### ISSUE TITLE
HLSL: way to treat discard as OpDemoteToHelperInvocation without requiring SPIR-V 1.6/Vulkan 1.3

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#3297]
In DXC, there is an option to treat discard as OpDemoteToHelperInvocation `-fspv-extension=SPV_EXT_demote_to_helper_invocation`.  This is needed because OpKill can lead to undefined behavior in derivatives following the kill if it's executed outside of uniform flow control (OpKill is basically broken and has been deprecated).  Could we get an option like `-fspv-extension=SPV_EXT_demote_to_helper_invocation` so that that even for example for SPIR-V 1.3 we use the extension, i.e.:

```
               OpExtension "SPV_EXT_demote_to_helper_invocation"

...
               %7118 = OpLabel
               OpDemoteToHelperInvocation
               OpBranch %19382
```

Also, I noticed that DXC treats `clip(x)` as OpKill even under this option.  I'm not sure if that's a bug with DXC, but it seems like probably clip and discard should be treated the same?

Some background: https://github.com/microsoft/DirectXShaderCompiler/issues/2823

**Comment by danginsburg** [comment]
I also filed an issue on DXC for the clip question: https://github.com/microsoft/DirectXShaderCompiler/issues/5937

**Comment by natduca** [comment]
Putting q2 actually b/c we want to do it in Q1 but likely blocked on capability system...

**Comment by csyonghe** [comment]
This is now implemented. You can opt in to this behavior with
`-profile spirv_1_4+SPV_EXT_demote_to_helper_invocation`.
