### ISSUE TITLE
slang.h is not a valid C header

### ISSUE THREAD

**Issue by Helco** [shader-slang/slang#3298]
For generating bindings I have tried to parse `slang.h` as C header, supported by the API User's guide stating "the header exposes a pure C interface", however despite some ifdefs e.g. around `extern "C"` there are a lot of C++ declarations left unmarked, non-exhaustive:

- [L540](https://github.com/shader-slang/slang/blob/1ac6638cf618a7f2bf761ac6ca57e7e7f4c754dc/slang.h#L540) usage of `bool`
- [L708](https://github.com/shader-slang/slang/blob/1ac6638cf618a7f2bf761ac6ca57e7e7f4c754dc/slang.h#L708) usage of `constexpr`
- [starting L1002](https://github.com/shader-slang/slang/blob/1ac6638cf618a7f2bf761ac6ca57e7e7f4c754dc/slang.h#L1002) the COM-like types using inheritance and (virtual) methods

Am I missing something, e.g. is the C interface deprecated?
If not I am open to helping transform the header. Also maybe adding a smoke test by trying to compile an empty C object including the library would be useful.

**Comment by csyonghe** [comment]
Yes, we are considering deprecating the C interface and moving entirely to the new COM based interface soon.

**Comment by Helco** [comment]
Okay, that is understandable.
