### ISSUE TITLE
`__requirePrelude` is unimplemented

### ISSUE THREAD

**Issue by chenzhekl** [shader-slang/slang#3300]
I would like to inject a `#pragma` for a compute shader that is about to be used in Unity. So I placed the following statement inside the entry function.

```
__prelude("#pragma kernel fooKernel")
```

but `slangc` complaiend

```
internal error 99999: unimplemented feature in Slang compiler: unexpected IR opcode during code emit
    __requirePrelude("#pragma kernel fooKernel");
```

It seems that the directive has not been implemented yet, but is already in the documentation.

Mention of `__requirePrelude` in the documentation: https://shader-slang.com/slang/user-guide/a1-04-interop.html

**Comment by csyonghe** [comment]
This is likely a bug. If you can share your code or provide a repro, I can take a look.

**Comment by csyonghe** [comment]
One reason I can think of is that the function with `__requirePrelude` is marked as an entrypoint, `public` or other attributes that makes it an export symbol. Otherwise if it is just an ordinary function, this error shouldn't occur.

**Comment by chenzhekl** [comment]
Hi @csyonghe, these are the two code snippets that could reproduce the error.

(Snippet 1)
```
[shader("compute")]
[numthreads(128, 1, 1)]
void entry()
{
    __requirePrelude("#pragma kernel entry");
}
```

(Snippet 2)
```
void markEntry()
{
    __requirePrelude("#pragma kernel entry");
}

[shader("compute")]
[numthreads(128, 1, 1)]
void entry()
{
    markEntry();
}
```

Both were compiled with 

```
slangc a.slang -target hlsl -o a.compute -entry entry
```

And this is the error message

```
a.slang(3): internal error 99999: unimplemented feature in Slang compiler: unexpected IR opcode during code emit
    __requirePrelude("#pragma kernel entry");
```

**Comment by csyonghe** [comment]
Hi @chenzhekl, currently `__requirePrelude` is only usable in intrinsic functions. Intrinsic functions are functions whose body contains exactly one `__intrinsic_asm` statement. You can use `__requirePrelude` in the following way:
```
void preludeIntrinsic()
{
      __requirePrelude("#pragma ...");
     __intrinsic_asm "";
}

// ...
void main()
{
     preludeIntrinsic();  // call intrinsic to pull in prelude.
    // rest of your code.
}
```

**Comment by chenzhekl** [comment]
Thanks! @csyonghe .  My bad for misunderstanding `__requirePrelude`'s usage. I will close the issue then.
