### ISSUE TITLE
Allow binding each scalar shader parameter separately

### ISSUE THREAD

**Issue by chenzhekl** [shader-slang/slang#3301]
Currently, slang compiles the following shader parameters

```
uniform float a;
uniform float b;
```

into the following layout

```
struct GlobalParams_0
{
    float a_0;
    float b_0;
};

cbuffer globalParams_0 : register(b0)
{
    GlobalParams_0 globalParams_0;
}
```

However, as Unity does not support binding struct to cbuffer, this poses some difficulties in using Slang with unity. I am wondering if it would be possible to add an option to prevent `slangc` from grouping all scalar parameters into a struct for cbuffer binding?

https://forum.unity.com/threads/use-of-struct-in-computeshader-cbuffer.905591/

**Comment by csyonghe** [comment]
This is doable, but will involve non-trivial amount of work. Given the limited engineering resources of the team, it is unlikely we can get to it soon. If you want to work with unity, you can consider using __intrinsic_asm + requirePrelude for now:
```
float getA()
{
     __requirePrelude("uniform float global_uniform_a;");
    __intrinsic_asm "global_uniform_a";
}

void main()
{
    float a = getA();
   // ...
}
```

**Comment by chenzhekl** [comment]
This is clever! The only drawback might be that the defined `uniform` is not explicitly assigned to any register. But I guess it is fine with Unity.

> This is doable, but will involve non-trivial amount of work. Given the limited engineering resources of the team, it is unlikely we can get to it soon. If you want to work with unity, you can consider using __intrinsic_asm + requirePrelude for now:
> 
> ```
> float getA()
> {
>      __requirePrelude("uniform float global_uniform_a;");
>     __intrinsic_asm "global_uniform_a";
> }
> 
> void main()
> {
>     float a = getA();
>    // ...
> }
> ```

**Comment by chenzhekl** [comment]
Ah, the above workaround seems to have another problem. Given the following Slang code, 

```
float getA()
{
    __requirePrelude("uniform float global_uniform_a;");
    __intrinsic_asm "global_uniform_a";
}

[shader("compute")]
[numthreads(128, 1, 1)]
void entry()
{
    float a = getA();
}
```

It is compiled to 

```
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif
#pragma warning(disable: 3557)

uniform float global_uniform_a;

#line 9 "a.slang"
[numthreads(128, 1, 1)]
void entry()
{

#line 11
    float _S1 = global_uniform_a();
    return;
}
```

where `global_uniform_a` is recognized as a function, which is undesired.

**Comment by csyonghe** [comment]
use __intrinsic_asm "(global_uniform_a)"; prevents the compiler from adding the trailing parenthesis.
