### ISSUE TITLE
Warn on marking function with known side-effects with `[PreferRecompute]` 

### ISSUE THREAD

**Issue by saipraveenb25** [shader-slang/slang#3303]
Right now, its possible to accidentally mark a method that relies on global/shared memory side-effects with `[PreferRecompute]`. The additional calls for recomputation will produce inconsistent output, and cause seemingly random gradients. 

We should throw a warning if the compiler data-flow analysis detects a method with side-effects being marked recompute, and provide a way to suppress it if it is intentional (the user may be collecting statistics on how many times the method is recomputed, etc..)

**Comment by natduca** [comment]
Autodiff quality of life, putting in Q2 to reflect that
