### ISSUE TITLE
Missing SPIRV intrinsics

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3305]
Going through hlsl.meta.slang, these following intrinsic functions/types have glsl implementation but not spirv:

- [x] - fwidth
- [x] - modf
- [x] - faceforward
- [x] - mul(vector, vector)
- [x] - NonUniformResourceIndex
- [x] - printf
- [x] - transpose
- [x] - WaveMaskMatch (N/A in SPIRV)
- [x] - WaveMultiPrefix* (N/A in SPIRV)
- [x] - struct __TextureFootprintData$(ND)
- [x] - TextureFootPrint related intrinsics
- [x] - struct ConstBufferPointer

**Comment by natduca** [comment]
@expipiplus1 can you share status on this issue?
