### ISSUE TITLE
Robust value extraction for floating-point literals

### ISSUE THREAD

**Issue by tangent-vector-personal** [shader-slang/slang#332]
The current code I wrote for extracting the value of a floating-point literal is extremely naive, and only works when both the significand and ten to the exponent are exactly representable as doubles. It is also potentially susceptible to double rounding since we are using doubles, but most literals will be typed as `float`.

The main reason for writing this code by hand (instead of using the platform `strtod`) was to deal with hexadecimal literals. One simple fix would be to use `strtod` (or an open-source implementation thereof, to guarantee consistency) for the decimal case, and a hand-rolled version for hex (where the power-of-two nature should simplify getting precise/correct results).

Aside: the other thing we might have to deal with is separator characters in the literal, or backslash-escaped new lines. Both of those are probably best handled by “scrubbing” the string before extracting its value.

Longer term we really need arbitrary-precision integers and floats and that will require a dedicated string-to-number implementation (and number-to-string as well...). This is the kind of situation where just using the existing support types in LLVM starts to look attractive, even if it greatly complicates our dependencies.

**Comment by tfoleyNV** [comment]
The simplest solution here might be the `double-conversion` library from Google: https://github.com/google/double-conversion
