### ISSUE TITLE
Descriptor Aliasing

### ISSUE THREAD

**Issue by Cons-Cat** [shader-slang/slang#3330]
When I write this code:
```
[vk::binding(0, 0)]
ByteAddressBuffer buffer;

[vk::binding(0, 0)]
Texture2D textures;

[shader("vertex")]
int vertex_main() {
    var tex = textures[0];
    return 1;
}
```
I get this error:
```
shaders.slang(35): warning 39001: explicit binding for parameter 'textures' overlaps with parameter 'buffer'
Texture2D textures;
          ^~~~~~~~
shaders.slang(32): note: see declaration of 'buffer'
ByteAddressBuffer buffer;
                  ^~~~~~
shaders.slang(35): warning 39001: explicit binding for parameter 'textures' overlaps with parameter 'buffer'
Texture2D textures;
          ^~~~~~~~
shaders.slang(32): note: see declaration of 'buffer'
ByteAddressBuffer buffer;
                  ^~~~~~
```
This makes it difficult to write bindless shaders. As far as I can tell, descriptor aliasing is supposed to be a supported use case in GLSL and HLSL. Imo, it would be very nice to easily pun storage buffers this way.

EDIT: I just realized the example shader is incorrect, but I don't think it's incorrect in a way that matters to this issue.

**Comment by natduca** [comment]
Marking Q3 just for triage purposes --- maybe we can get to this faster but being careful

**Comment by csyonghe** [comment]
Update: this warning was added because there are existing users depending on this behavior. So the current advice is for users to disable this warning if they don't need it.
