### ISSUE TITLE
Additional intrinsics ideas

### ISSUE THREAD

**Issue by Cons-Cat** [shader-slang/slang#3332]
It's hard to find HLSL libraries that provide basic utilities. Everyone seems to have an in-house core library, or they're using Unity or Unreal. This has been a big pain point for me. It could be nice if Slang had intrinsics covering more of the basics even if there isn't specifically support for these features in the GPU bytecode targets. What I'd personally like are:

- quaternion types, which can ergonomically rotate vectors and matrices and maintain their own normalization while being rotated.
- matrices with typed-majorness. Many libraries and now some languages have this concept to prevent user error from mixing column and row major affine transformation matrices improperly.
- `cbrt` function. There is already a `sqrt`, and cube roots are important for very many algorithms, and not very easy to implement on your own.
- a generic `identity<T>` to generate an identity vector or matrix. Many libraries have something like this, which is very nice.

**Comment by csyonghe** [comment]
Quaternions and other arithmetic libraries should be trivial to add.

Slang is already handling matrix layouts as part of the type. However we took a different approach by assuming row-majorness everywhere except in buffers. Whenever matrices are loaded from buffer, they are converted to row-major matrices, so the user can't shoot their feet with layouts.

Regarding `identity<T>`, Slang already uses interfaces to organize the builtin types. For example, both float and vector<float,N> conforms to `IFloat`, which inherits from `IArithmetic`. We could add a new requirement in `IArithmetic` called `static const This identity;`, so the user can do `float.identity` or `vector<int, 3>.identity`.

**Comment by Cons-Cat** [comment]
Being able to generate geometry as static arrays inside a Slang shader might also be nice. If Slang had something like const generics (non-type template parameters in C++), a generic argument could specify the winding order and stride of vertices in the static array. Generating triangles or cubes inside the shader at compile time could be very nice for rapidly setting up demos.

**Comment by csyonghe** [comment]
We welcome contributions like this, but for now we cannot prioritize this task with the limited resource of the team. Closing the issue now.

**Comment by Cons-Cat** [comment]
> We welcome contributions like this, but for now we cannot prioritize this task with the limited resource of the team. Closing the issue now.

I'm having trouble implementing a `cbrt()`. I've put this below `sqrt()` in `hlsl.meta.slang`, and I can see that it is emitted in the `hlsl.meta.slang.h` file:
```hlsl
[__readNone]
float cbrt(float x)
{
    // ...
    return answer;
}
```
But when I compile a trivial shader, I get this error:
```sh
$ ./bin/linux-x64/debug/slangc demo.slang -entry demo -o demo.glsl
demo.slang(5): error 30015: undefined identifier 'cbrt'.
    cbrt(1.f);
    ^~~~
```
I've messed around with the attributes, tried generating both GLSL and HLSL, looked through a lot of the documentation, and read commits which added standard library features, but I'm struggling to see what I'm missing. Is there C++ code somewhere that must be added to make the compiler aware of non-intrinsic stdlib identifiers? Or is there a document I've missed which explains the process for writing these?
