### ISSUE TITLE
`NonUniformResourceIndex` not working in direct-to-spirv backend.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3338]
The logic to attempt to emit the `OpDecoration` is executed but the resulting SPIRV still does not have the decoration inst. To repro, use the existing test `vk-texture-indexing.slang` with the following setting:

```
// vk-texture-indexing.slang

//TEST:SIMPLE(filecheck=CHECK):-target spirv -entry main -stage fragment
//TEST:SIMPLE(filecheck=CHECK):-target spirv -entry main -stage fragment -emit-spirv-directly
// CHECK: OpDecorate %{{.*}} NonUniform
```

**Comment by csyonghe** [comment]
The current fully user-space implementation also risks losing the decoration with implicit type casts.
For example, if the user have something like:
```
uint8_t index = NonUniformResourceIndex(...);
array[index] = ...
```
Then we could be generating the following code:
```
a = NonUniformResourceIndex(i)
b = IntCast<uint> a
resPtr = GetElementPtr arr b
```
Where the value that is used to index the array isn't properly marked as `NonUniformResourceIndex`.
To address this issue, the safest solution for now is to introduce a dedicated inst for `NonUniformResourceIndex`, and have a pass to promote `NonUniformResourceIndex` to the top of the operator[] arguments, so we can transform the above code into:
```
b' = IntCast<uint> i
c = NonUniformResourceIndex(b')
resPtr = GetElementPtr arr c
```

**Comment by pmistryNV** [comment]
Looking into the bug.

**Comment by pmistryNV** [comment]
Bug fixed with https://github.com/shader-slang/slang/pull/3417 closing the bug
