### ISSUE TITLE
`RWBuffer` compiling as `imageBuffer`

### ISSUE THREAD

**Issue by Cons-Cat** [shader-slang/slang#3344]
When I compile this shader:
```hlsl
[vk::binding(0,0)]
RWBuffer<float4> buffer;

// Generate a demo triangle.
[shader("vertex")]
float4 demo_vertex_main(in uint32_t id : SV_VertexID, out float3 color : SV_Target0)
: SV_Position {
    color = buffer[0].xyz;
    return {0,0,0};
}
```
` slangc shaders.slang -target glsl -entry demo_vertex_main -o demo_vertex.glsl`
I get this GLSL:
```glsl
#version 450
#extension GL_EXT_samplerless_texture_functions : require
layout(row_major) uniform;
layout(row_major) buffer;

#line 96 0
layout(rgba32f)
layout(binding = 0)
uniform imageBuffer buffer_0;

layout(location = 0)
out vec3 _S1;


#line 100
void main()
{


    vec4 _S2 = (imageLoad((buffer_0), (0)));

#line 104
    vec3 _S3 = _S2.xyz;

#line 104
    gl_Position = vec4(0.0, 0.0, 0.0, 0.0);

#line 104
    _S1 = _S3;

#line 104
    return;
}
```
The `buffer` binding is an `imageBuffer`, but I expected a `buffer`. Is this a bug, or am I misunderstanding the way Slang works?

**Comment by csyonghe** [comment]
This is expected. The HLSL `Buffer` type is actually a image/texture, where the element types are limited to texel types with optional format specifier. The HLSL equivalent of `buffer` is `[RW]ByteAddressBuffer` or `[RW]StructuredBuffer`.
