### ISSUE TITLE
Investigate test failures on SLANG-WIN-4 and SLANG-WIN-5.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3347]

**Comment by natduca** [comment]
@csyonghe  can you please add a few details on how to get started on this bug so that when someone gets assigned to this they'll know what to do?

**Comment by csyonghe** [comment]
They need to talk to me first to gain access to the CI machines. Then they will build and run the tests manually on that machine and see what error comes out and we can take actions with further knowledge.

**Comment by csyonghe** [comment]
The root cause seems to be that we are forcing windows SDK 19041, which caused device removal when running on Win 11 and build using VS2022. Removing that argument to MSBuild seem to fix the issue.
