### ISSUE TITLE
Support GLSL builtin variables that maps to different semantics depending on stage.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3354]
Some of the GLSL builtin variables maps to different HLSL semantics depending on the current stage. For those builtins, we can define them as global properties where the getter/setter routes to internal declarations based on stage.

For example, 
```
uint __builtinControlPointID : sv_outputcontrolpointid;
uint __builtinGSInstanceID : sv_gsinstanceid;

property uint gl_InvocationID
{
     get
     {
         __target_switch
        {
        case geometry:
               return __builtinGSInstanceID;
        case hull:
              return __builtinGSInstanceID;
        }
     }
}
```

This requires us to expand our `target_switch` mechanism to support stage-based specialization. Currently, there is a dedicated specialization pass to remove all `__target_switch` in the IR by selecting the path suitable for the current compilation target. In the case of  a compilation of mixed entry points, the stage of each invocation might be different, depending on where the call is initiated from.

We need to expand this pass to:
1. Identify all function bodies that has a stage dependent `__target_switch`, and mark such functions as `StageSpecializable`.
2. Propagate `StageSpecializable`  tag on the call graph, such that a function is stage specializable if it transitively calls a stage specializable function.
3. Traverse the call graph from entry points, and specialize `StageSpecializable` callees with the stage of the entry point.
4. Fully remove `__target_switch` by combining the stage the function is specialized to and other capability flags of the current compilation request.

**Comment by bmillsNV** [comment]
No plans to support GLSL syntax beyond basic shaders at this time. Closing.
