### ISSUE TITLE
Using `-emit-spirv-directly` and a `SV_VertexID` produce incorrect Spir-V code

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3358]
If the shader uses `SV_VertexID` in the vertex shader and the compiler uses the `-emit-spirv-directly` option, shader module creation will fail.

```
vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: Vulkan spec doesn't allow BuiltIn VertexId to be used.
  %gl_VertexID = OpVariable %_ptr_Input_int Input
```

If the option `-fvk-use-entrypoint-name` is used instead of individual entries, the error is different:

```
vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: [VUID-StandaloneSpirv-Flat-04744] Fragment OpEntryPoint operand 15 with Input interfaces with integer or float type must have a Flat decoration for Entry Point id 48.
  %gl_VertexID = OpVariable %_ptr_Input_int Input
``` 

Here is an example of of the shader and the command line to reproduce the issue.

[slang-gl_VertexID.zip](https://github.com/shader-slang/slang/files/13487988/slang-gl_VertexID.zip)

**Comment by pmistryNV** [comment]
Looking into the bug

**Comment by pmistryNV** [comment]
In the failing case vertex ID is decorated as VertexId
OpDecorate %gl_VertexID BuiltIn VertexId

In the passing case vertex ID is decorated as VertexIndex
OpDecorate %gl_VertexIndex BuiltIn VertexIndex


Vulkan supports VertexIndex and even DXIL emits the same. Replacing the decoration will fix the bug.

**Comment by mklefrancois** [comment]
This makes sense, the Vulkan built-in is gl_VertexIndex. 

https://github.com/KhronosGroup/GLSL/blob/a14f1f11fa632d3db797fcf28b83bd2a44cd49fa/extensions/khr/GL_KHR_vulkan_glsl.txt#L548

**Comment by pmistryNV** [comment]
Fixed with PR https://github.com/shader-slang/slang/pull/3419

**Comment by mklefrancois** [comment]
I've tested the fix, but there is a new validation error

```
 --> Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282 | vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: [VUID-StandaloneSpirv-Flat-04744] Fragment OpEntryPoint operand 24 with Input interfaces with integer or float type must have a Flat decoration for Entry Point id 69.
  %gl_VertexIndex = OpVariable %_ptr_Input_int Input
```

I have attached the shader:
[raster.zip](https://github.com/shader-slang/slang/files/13859027/raster.zip)

Compilation command 
```
slangc.exe -profile glsl_460 -target spirv -emit-spirv-directly -force-glsl-scalar-layout -fvk-use-entrypoint-name -g3 -D__slang -source-embed-style text -source-embed-name rasterSlang -o raster_slang.h raster.slang
```

SlangC version `1704706527`
