### ISSUE TITLE
Issue with `-emit-spirv-directly` and ray-trace shader

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3359]
When using the `-emit-spirv-directly` option with the attached shader, there will be an issue when creating the shader module.

The error that is returned is: 
```
vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: End of input reached while decoding OpLoad starting at word 5381: expected more operands after 3 words.
```

But when this options isn't there, there is a new error showing up, only for the raygeneration and closesthit, but not for the miss shader:

```
vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: Id is 0.
```
Interestingly, the shader work despite the error.

And if we are using the in combination the option `-fvk-use-entrypoint-name` instead of  `-entry ...`, the error is similar, but differs in the OpLoad position :

``` 
vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: End of input reached while decoding OpLoad starting at word 3277: expected more operands after 3 words. 
```` 

Command line 
```
slangc.exe -emit-spirv-directly -entry rgenMain -target spirv -g3 -line-directive-mode glsl -profile glsl_460 -D__slang -force-glsl-scalar-layout -source-embed-style text -source-embed-name raytrace_rgenMain -o raytrace_rgenMain.spirv raytrace.slang
```
[slang-raytrace.zip](https://github.com/shader-slang/slang/files/13489807/slang-raytrace.zip)

**Comment by csyonghe** [comment]
The first step here is to try to reproduce the issue with the attached shader and get a sense of what exactly is going wrong.

**Comment by mklefrancois** [comment]
I have updated [nvpro-core](https://github.com/nvpro-samples/nvpro_core) and [vk_mini_samples](https://github.com/nvpro-samples/vk_mini_samples) which have what it needs to reproduce the issue.

**Steps**
* Clone both nvpro-core and vk_mini_samples. 
* With CMake GUI, check the option USE_SLANG and hit Generate
* Under the ray_trace project, open `ray_trace.cpp` and set USE_SEPARATE_SLANG to 0
```
#define USE_SEPARATE_SLANG 0
```

The Separate version compiles each entrypoint separately and is not using the `-emit-spirv-directly` option and this is working. When the define is set to 0, it is using `"_autogen/raytrace_slang.h"`, which is the result of the compilation using `-emit-spirv-directly` and `-fvk-use-entrypoint-name`.

**Comment by pmistryNV** [comment]
Started looking into the bug.

**Comment by pmistryNV** [comment]
@mklefrancois can you confirm if the PR fixes the bug.
