### ISSUE TITLE
Automatically enable glsl compatibility mode.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3369]
Currently GLSL mode is enabled by the -allow-glsl flag. This isn't necessary because when know a file is in GLSL if we see a `#version` line. We should change the way we parse the derivatives to parse them as a syntax node instead of handling them in the preprocessor, and automatically enable glsl mode in the parser.

**Comment by csyonghe** [comment]
We should use the existing -lang compiler option instead of using -allow-glsl.

**Comment by pmistryNV** [comment]
Reassigning the bug as I will like to fix it as part of https://github.com/shader-slang/slang/issues/3476. During the integration I was not able to sett the allow GLSL flag on ISession and am adding an hack to the ISession interface. However will fix it as part of this bug.

**Comment by csyonghe** [comment]
#3531 adds the logic to detect input file extension and automatically enable glsl mode.

We should go ahead and remove the `-allow-glsl` flag (and Linkage::setAllowGLSL) since it is superseded by `-lang glsl`.
