### ISSUE TITLE
Update contributing guide

### ISSUE THREAD

**Issue by natduca** [shader-slang/slang#3372]
We have some notes scattered on how to set up for building/contributing to slang but we need to freshen them up.

**Comment by natduca** [comment]
We will want to be able to support new joiners by having a great contributing guide, so marking Q1 and high priority

**Comment by natduca** [comment]
Now that this is drafted, Jae, are you goign to commit to the wiki? Lets get this done.

**Comment by jkwak-work** [comment]
Yes I will be able to commit next week.
I am still trying to iron out the last steps around "Pull Request".
