### ISSUE TITLE
Support SM6.6 WaveSize

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3385]
The `WaveSize` keyword introduced in SM6.6 does not yet seem to be supported in Slang. 

```
[WaveSize(<numLanes>)]
void main() ...
```

**Comment by csyonghe** [comment]
Assigning to @jkwak-work as it seems this is critical to get the UE shader's performance right.

**Comment by jkwak-work** [comment]
Fix is merged.
Closing.
