### ISSUE TITLE
Derivative type deduction for generic `DifferentialPair` fails for a function's `T`

### ISSUE THREAD

**Issue by Cons-Cat** [shader-slang/slang#3390]
The following code appears to work:
```hlsl
float foo(float x)
{
    return x * 2.f;
}

[[ForwardDerivativeOf(foo)]]
DifferentialPair<float> dfoo(DifferentialPair<float> x)
{
    return diffPair(
        x.p,
        0.f
    );
}
```
However, making the type generic rather than `float`, like so, fails:
```hlsl
T foo<T : IFloat>(T x)
{
    return x * T(2);
}

[[ForwardDerivativeOf(foo)]]
DifferentialPair<T> dfoo<T : IFloat>(DifferentialPair<T> x)
{
    return diffPair(
        x.p,
        T(0.f)
    );
}
```
The error is:
```hlsl
./demo.slang(12): error 30019: expected an expression of type 'T.Differential', got 'T'
        T(0.f)
         ^
```
(Please disregard that the provided derivative value `0.f` is nonsense, only its data type is important here)

While `diffPair` can deduce that `DifferentialPair<float>.Differential` is `float`, it seems unable to deduce that `DifferentialPair<T>.Differential` is also `T`. I cannot seem to find a workaround that makes this compile in a generic context. Calling a `DifferentialPair` constructor directly has the same issue as `diffPair`.

**Comment by Cons-Cat** [comment]
There is a test case in `tests/diagnostics/custom-derivative-generic.slang` which seemed to miss this by not evaluating a generic differential r-value:
```hlsl
// CHECK-DAG: {{.*}}(30): error 31152
[ForwardDerivativeOf(IFoo.bar)]
DifferentialPair<float> dd1(DifferentialPair<float> x)
{
    return x;
}
```
By simply returning `x` rather than using `x` to make a new derivative, it type-checks.

**Comment by natduca** [comment]
@csyonghe to triage

**Comment by csyonghe** [comment]
@Cons-Cat As we discussed, this is currently a language limitation that we cannot express things like `T.Differential == T` to the compiler. For now, we use `__slang_noop_cast` to work around it. 

Closing this issue now.
