### ISSUE TITLE
Update vcpkg version

### ISSUE THREAD

**Issue by Dynamitos** [shader-slang/slang#3399]
I started using the library through vcpkg, and noticed that the version there is only 0.27.0. I updated the version on my local vcpkg, and wanted to know how this is handled, who does the updates or if there even is a process for that.

The update is quite trivial, fix the version number in the portfile, update the hashes of the .zip and .tar.gz files, so I could probably do the pull request myself if that is fine with you.

**Comment by csyonghe** [comment]
We do not own and maintain vcpkg distributions, would you contact the owner for updates there?
