### ISSUE TITLE
Support for `GL_EXT_buffer_reference2`

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3404]
It would be essential for Slang to support the Vulkan/Spir-V `GL_EXT_buffer_reference2` extension.  Many shaders that deal with complex scene structures use this to access elements in the scene. This is especially true for raytracing, where many elements of the scene are often needed.

**Comment by csyonghe** [comment]
The way Slang is going to support buffer_reference is to allow pointers. There is currently a `ConstBufferPointer<T>` type that you can use today. It provides a `T ConstBufferPointer<T>::get()` method that loads the whole thing it points to, and is only supported in the glslang path, not the direct spirv backend.

**Comment by csyonghe** [comment]
This issue can be closed once we close #3305.
