### ISSUE TITLE
Struct initializer-list with visibility control

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3406]
Now that we have visibility control, we need to cleanup the initialization part as well:
```
struct S
{
     private int m;
     public int n;
}

void test()
{
     S s = {1,2}; // Initializing private member here seems wrong.
}
```

We should be synthesizing constructors for structs and have initialization list syntax calling into the constructors instead.
This way, our constructor synthesis will fail for `S` because it can't default init `m`. And then that will surface to the user as an error in `test` because it is trying to call a constructor that does not exist.

**Comment by ArielG-NV** [comment]
Tentative Plan:
1. For an initialization list of a struct to be legal, it must match up to a constructor. 
2. We will only auto-gen a constructor with a parameter-list ordered 1:1 to public struct members
3. We won't auto-gen constructors if an already valid constructor exists. We will use the valid constructor instead

Todo this we will have a priority of initialization list usage->autogen-constructor:


1. assume
```
struct S
{
     private int m1;
     public int m2;
}

S test()
{
     S s = {1,2};
     return s;
}
```
This will error, there are more init list elements than public variables 


2. assume
struct S
{
     private int m1;
     public int m2;
     __init(int in1, int in2)
     {
         m1 = in1;
         m2 = in2
     }
}

S test()
{
     S s = {1,2};
     return s;
}
```
This will work, user made constructor has priority


3. assume
struct S
{
     public int m1;
     public int m2;
}

S test()
{
     S s = {1,2};
     return s;
}
```
This will work, 2 public int members, 2 elements inside the parameter-list


4. assume
struct S
{
     private int m1;
     public int m2;
     private int m3;
     public int m4;
}

S test()
{
     S s = {1,2};
     return s;
}
```
This will work, 2 public int members, 2 elements inside the parameter-list

5. assume
struct S
{
     private int m1;
     public int m2;
     private int m3;
     public int m4;

     __init(int in1, int in2)
     {
          m1 = in1;
          m2 = in2;
     }
}

S test()
{
     S s = {1};
     return s;
}
```
This will work, user made constructor has priority

**Comment by csyonghe** [comment]
We should make 6 an error, because private members must have an explicit initializer for implicit generation of ctor. If we have uninitialized private members, do not generate a ctor, or generate a ctor that will result an error message if it is ever called.

**Comment by ArielG-NV** [comment]
updated 👍  (also changed the example numbers to make more sense)

**Comment by csyonghe** [comment]
Just want to add that 
```

struct S
{
     private int m1 = 0;
     public int m2;
}

S s = {1}; // works.

```

**Comment by csyonghe** [comment]
struct S
{
     internal int m1;
     public int m2;
}
 S s  = {1,2}; // works from the same module.

S s = {1,2}; // does not work if called from a different module, because ctor is not visible.

**Comment by ArielG-NV** [comment]
I have a question about when an initializer-list is a partial-completion to the member list:
```
struct S
{
     private int m1 = 0;
     public int m2;
     private int m3 = 1;
     public int m4;
}

S test()
{
     S s = {1};
     return s;
}
```

This would error since no user-ctor && not 1:1 for each public member?

**Comment by csyonghe** [comment]
I think we just don't allow this for now.

**Comment by jkwak-work** [comment]
It seems like Ariel already considered this case well enough.
But I like to just share more information that the following C++ code is valid.
```
#include <cstdio>

struct MyStruct1
{
        int v1;
        int v2;

        MyStruct1(int a, int b)
        {
                v1 = a + 1;
                v2 = b + 1;
        }
};

struct MyStruct2
{
        int v1;
        int v2;
};

int main()
{
        MyStruct1 s1 = { 11, 12 };
        MyStruct2 s2 = { 11, 12 };
        printf("%d\n", s1.v1); // prints 12
        printf("%d\n", s2.v1); // prints 11
        return 0;
}
```
As soon as I put `private:` keyword, the list-initializer didn't work; probably I need to explicitly declare a constructor with a list-initializer as a parameter in this case.

**Comment by ArielG-NV** [comment]
> As soon as I put private: keyword, the list-initializer didn't work; probably I need to explicitly declare a constructor with a list-initializer as a parameter in this case.

This is a good point to bring up.

I think Slang's approach is to treat visibility differently than C++ (in respect to constructors and initializer-lists).
The following code is not valid in C++:
```
struct MyStruct2
{
private:
        int v1;
        int v2;
public:
    static MyStruct2 make()
    {
        return {11, 12};
    }
};
```

The following code (with the new system) should be valid in Slang.
```
struct MyStruct2
{

    private int v1;
    private int v2;
    public static MyStruct2 make()
    {
        return {11, 12};
    }
};
```

The plan seems to be that Slang should be more lenient than C++ if casting an initializer-list into a constructor.

Note: @csyonghe, If this is not the correct plan, please ping me so I can adjust code accordingly.

**Comment by ArielG-NV** [comment]
Additions and some design planning:
1. Inheritance
```
struct MyStruct1
{
        private int v1;
        public int v2;
};
struct MyStruct2 : MyStruct1
{
        private int v1;
        public int v2;
        
        static MyStruct2 make()
        {
            return {1, 2, 3} // base.v2 = 1, v1 = 2, v2 = 3
        }
};
....
MyStruct2 val = {1, 2}; // base.v2 = 1, v2 = 2
```

**Comment by csyonghe** [comment]
For inheritance, it is fine to have base appear as a single parameter appears at the beginning of the parameter list.

Note that if a type has `private` fields without a default expr, we should NOT be synthesizing any ctors.

**Comment by ArielG-NV** [comment]
Additional planning:

Syntax for constructor:
1. Only a struct that is made by a 'synthesized-ctor' and is a 'base type' may be treated as if its not a separate object from a parent when being used inside an initializer list. This means the following with code as an example:

```
struct S1
{
	public int val1;

}

struct S2
{
	public S1 val2;
	public int val3;
}

struct S3 : S1
{
	
	public int val4;
}

void main()
{
	S2 val = {1, 1} // error

	S3 val = {1, 1} // allowed
}
```

**Comment by ArielG-NV** [comment]
Breaking change:
If a base type struct has no members we no longer require accepting as a parameter into a initializer list the base-type

**Comment by ArielG-NV** [comment]
Update:
Flattened initialization lists for structs are allowed if:
1. user did not define a ctor
2. Internally Slang only auto-generated 1 ctor for a user (Internal-only struct's can be init-list initialized)
    * Internally that means: "if user defines 0 synth ctor, IOArgIndex for init-list resolution must be equal to 0 and param count must be exactly matched
    
Note: defaults should not affect init list logic
