### ISSUE TITLE
Create a direct spirv backend compile time perf test

### ISSUE THREAD

**Issue by natduca** [shader-slang/slang#3413]
We would like to be able to monitor the performance of end to end spirv compilation time  --- both slang side and driver side combined. This will allow us to know if we're making headawy [and or regressing] on compilation performance.

The scrappy start we think is right for this is
1. Take the 2 shaders from Falcor that have previously encountered compile time and get them to run standlone (2 shaders in material image test, @csyonghe can give specifics to whomever takes this task
2. Wrap a perf runner around that (this will require to designing a perf runner as we don't have one thats meaningful, suggest pulling best practices from other projects that have done this in the past)
3. Get the CL merged
4. Verify repeatability // amount of variance in the test results and ensure it gives clean signal

We can add more shaders to that runner after those two exist.

**Comment by csyonghe** [comment]
This is done.
