### ISSUE TITLE
Slangc.exe error messages from spvtools not redirected to standard error

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#3423]
This is related to issue #3422 

When I run into an issue with slang which causes the compiler to crash internally, error messages do not go to standard error. This makes these bugs very difficult to catch, because the error goes undetected until the resulting IR is consumed by the driver.

For example, take the following shader code (using slang v2023.5.4): 

```
[shader("closesthit")]
void TriClosestHit(inout float3 payload, in float2 bc) {
    float3 color = float3(1.f - bc.x - bc.y, bc.x, bc.y);

    // This causes slangc.exe to crash...
    float3x4 transform = ObjectToWorld3x4();
    payload = mul(transform, float4(color, 1.f));
}
```

The above silently fails. I would expect using `slangc.exe <source.slang> <flags> -o output.spv 2>  error.log` to work, but nothing is output to standard error. Further, slang *does* generate output.spv, which tricks me into assuming all is fine. 

The only clue I get to determine that slang is actually crashing is that `vkCreateRayTracingPipelines` report an internal driver failure. It isn't until I disassemble the SPIRV with spirv-dis that I finally see what the problem is:

```
; SPIR-V
; Version: 1.5
; Generator: Khronos; 40
; Bound: 29
; Schema: 0
               OpCapability RayTracingKHR
               OpCapability Shader
               OpExtension "SPV_KHR_ray_tracing"
               OpMemoryModel Logical GLSL450
               OpEntryPoint ClosestHitNV %TriClosestHit "TriClosestHit" %28 %9 %20
               OpSource Unknown 1
               OpName %mat "mat"
               OpName %TriClosestHit "TriClosestHit"
               OpDecorate %20 BuiltIn ObjectToWorldNV
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v2float = OpTypeVector %float 2
%_ptr_HitAttributeNV_v2float = OpTypePointer HitAttributeNV %v2float
    %float_1 = OpConstant %float 1
    %v3float = OpTypeVector %float 3
%mat4v3float = OpTypeMatrix %v3float 4
%_ptr_Input_mat4v3float = OpTypePointer Input %mat4v3float
    %v4float = OpTypeVector %float 4
%mat3v4float = OpTypeMatrix %v4float 3
%_ptr_IncomingRayPayloadNV_v3float = OpTypePointer IncomingRayPayloadNV %v3float
          %9 = OpVariable %_ptr_HitAttributeNV_v2float HitAttributeNV
         %20 = OpVariable %_ptr_Input_mat4v3float Input
         %28 = OpVariable %_ptr_IncomingRayPayloadNV_v3float IncomingRayPayloadNV
%TriClosestHit = OpFunction %void None %3
          %4 = OpLabel
          %7 = OpLoad %v2float %9
         %10 = OpCompositeExtract %float %7 0
         %11 = OpFSub %float %float_1 %10
         %13 = OpLoad %v2float %9
         %14 = OpCompositeExtract %float %13 1
         %15 = OpFSub %float %11 %14
         %17 = OpCompositeConstruct %v3float %15 %10 %14
error: 34: End of input reached while decoding OpLoad starting at word 141: expected more operands after 3 words.
```

So, I suppose this is a feature request more than anything, but it would be very helpful to have slangc output error messages like these to standard error so that I can more quickly determine the root cause of bugs as I find them and report compiler crashes here

**Comment by natevm** [comment]
Digging into the issue a bit deeper, this error message seems to appear in spvtools, possibly here? 

https://github.com/shader-slang/SPIRV-Tools/blob/8994351e58e45e1f067733966628383c50341de9/source/binary.cpp#L161
or here? 
https://github.com/shader-slang/SPIRV-Tools/blob/8994351e58e45e1f067733966628383c50341de9/source/binary.cpp#L364

I'm not familiar with how spirv tools is integrated into slang, other than that it's a dependency. Perhaps that's a good starting point though to determine why error messages aren't properly being reported.

**Comment by csyonghe** [comment]
Slang does not run spirv validation as a part of compilation by default for performance reasons, that's why you are not seeing an error message. If you need to be certain, you can always run spirv-val yourself after slangc. For now closing this issue since there is a user workaround.
