### ISSUE TITLE
Differential types do not match principle type despite all members being differentiable

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#3425]
If I have a structure like this, which implements IDifferentiable:

```
struct Ray: IDifferentiable {
    float3 Origin;
    float3 Direction;
    float TMin, TMax;
}
```

Then I would expect the Differential type for "Ray" to also be "Ray". However, the differential type is instead a "Ray.Differential". 

There appears to be some missing logic in the synthesis to use the existing type as differential if all its members' differential type are the same as their original type.

**Comment by pmistryNV** [comment]
As part of the bug will add test cases to turn on the IR validation in spirv only path.

**Comment by natevm** [comment]
> As part of the bug will add test cases to turn on the IR validation in spirv only path.

That would be very helpful. I had a similar issue related to slang SPIRV not being validated. 

For compiler perf reasons, it might be worth considering disabling validation though (or conditionally including via a flag?) I’m not sure how long validation takes, but I could see it being a problem if we’re always doing it.
