### ISSUE TITLE
Optix Code Compilation Issue

### ISSUE THREAD

**Issue by half-potato** [shader-slang/slang#3427]
I'm trying to compile the Optix example code from the [here](https://github.com/shader-slang/optix-examples).

I'm getting the following error:
```
 /usr/local/bin/slangc /home/amai/optix-examples/example02_pipelineAndRayGen/devicePrograms.slang -o embedded_ptx_code.ptx -dump-intermediates -line-directive-mode none
nvrtc 12.2: default_program(32): error : cannot open source file "optix.h"
nvrtc 12.2: note :   #include <optix.h>
nvrtc 12.2: note :                     ^
```

The optix location is `/opt/optix` and yes, I have set it in the CMake, as well as an environment variable. Here is my current workaround:

Create a file at `/opt/optix/preamble.h` with the following contents:
```
#define SLANG_CUDA_ENABLE_OPTIX
#include <optix.h>
#include <optix_function_table_definition.h>
#include <optix_stubs.h>
```

Change the macro command `slang_compile_and_embed` in `configure_slang.cmake`
```
    COMMAND ${SLANGC} ${slang_file} -o ${intermediate_file1} -dump-intermediates -line-directive-mode none && cat /opt/optix/preamble.h ${intermediate_file1} > ${intermediate_file2} && nvcc -I${OptiX_INSTALL_DIR}/include --ptx ${intermediate_file2}
```

**Comment by csyonghe** [comment]
Can you try adding `-Xnvrtc... -I${OptiX_INSTALL_DIR}/include  -X.` to the slangc args? This will pass the `-I` option to nvrtc so it can discover the header files.

**Comment by half-potato** [comment]
This works, thanks.
