### ISSUE TITLE
(GLSL/SPirV) Code generation - Inlining breaks shader

### ISSUE THREAD

**Issue by Paul-Hi** [shader-slang/slang#3429]
While cleaning up one of my projects, I stumbled across something that seems like a bug to me.

I factored out functionality to the function `getIntersectionInfo` - which led to a significant drop in performance. So I looked at the generated output and realized that the problem is the missing inlining of the function, and tried to force the compiler to do so via [ForceInline]. The compiler then inlines the function, but ignores the condition for two other function calls with global buffer access in the conditional branches, which leads to crashes (probably an out-of-bounds access, since `getTriangle` and `getSphere` access information with their primitiveId in different buffers).

Shader compilation is done with `-profile glsl_460 -target glsl -o ${OUTPUT_SPIRV_FILE} -entry main -O3`. No difference could be determined for other optimization levels.

```
[ForceInline]
IntersectionInfo getIntersectionInfo(const RayPayload payload)
{
  IntersectionInfo iInfo;  
  if(payload.hitInfo.hitKind == EHitKind::triangleMesh)
  {
    DeviceTriangle triangle = getTriangle(payload.hitInfo.primitiveId, payload.hitInfo.instanceCustomIndex, ...);
    iInfo.material = gMaterials[triangle.materialId];
    iInfo.uv = triangle.interpolatedUV;
    iInfo.lightId = triangle.lightId;
    iInfo.space = CoordinateSpace(triangle.interpolatedNormal, ...);
  }
  else if(payload.hitInfo.hitKind == EHitKind::proceduralSphere)
  {
    DeviceSphere sphere = getSphere(payload.hitPoint, payload.hitInfo.primitiveId, ...));
    iInfo.material = gMaterials[sphere.materialId];
    iInfo.uv = sphere.uv;
    iInfo.lightId = sphere.lightId;
    iInfo.space = CoordinateSpace(sphere.normal, true);
  }
  return iInfo;
}

...

{

...

IntersectionInfo iInfo = getIntersectionInfo(payload); // compiler should inline here

...

}
```

The expected output for the call would look something like that:

```
bool _S170 = payload_1.hitInfo_0.hitKind_0 == 0U;
bool _S171 = payload_1.hitInfo_0.hitKind_0 == 1U;

...

IntersectionInfo_0 iInfo_0;
if(_S170)
{
  DeviceTriangle_0 triangle_0 = getTriangle_0(payload_1.hitInfo_0.primitiveId_0, payload_1.hitInfo_0.instanceCustomIndex_0, ...);
  iInfo_0.material_0 = gMaterials_0._data[triangle_0.materialId_1];
  iInfo_0.uv_11 = triangle_0.interpolatedUV_0;
  iInfo_0.lightId_6 = triangle_0.lightId_1;
  iInfo_0.space_1 = CoordinateSpace_x24init_1(triangle_0.interpolatedNormal_0, ...);
}
else
{
  if(_S171)
  {
    DeviceSphere_0 sphere_2 = getSphere_0(payload_1.hitPoint_0, payload_1.hitInfo_0.primitiveId_0, ...);
    iInfo_0.material_0 = gMaterials_0._data[sphere_2.materialId_2];
    iInfo_0.uv_11 = sphere_2.uv_3;
    iInfo_0.lightId_6 = sphere_2.lightId_2;
    iInfo_0.space_1 = CoordinateSpace_x24init_0(sphere_2.normal_4, true);
  }
}
```

But it actually looks roughly like that:

```
bool _S170 = payload_1.hitInfo_0.hitKind_0 == 0U;
DeviceTriangle_0 triangle_0 = getTriangle_0(payload_1.hitInfo_0.primitiveId_0, payload_1.hitInfo_0.instanceCustomIndex_0, ...);
bool _S171 = payload_1.hitInfo_0.hitKind_0 == 1U;
DeviceSphere_0 sphere_2 = getSphere_0(payload_1.hitPoint_0, payload_1.hitInfo_0.primitiveId_0, ...);
CoordinateSpace_0 _S172 = CoordinateSpace_x24init_0(sphere_2.normal_4, true);

...

IntersectionInfo_0 iInfo_0;
if(_S170)
{
  iInfo_0.material_0 = gMaterials_0._data[triangle_0.materialId_1];
  iInfo_0.uv_11 = triangle_0.interpolatedUV_0;
  iInfo_0.lightId_6 = triangle_0.lightId_1;
  iInfo_0.space_1 = CoordinateSpace_x24init_1(triangle_0.interpolatedNormal_0, ...);
}
else
{
  if(_S171)
  {
    iInfo_0.material_0 = gMaterials_0._data[sphere_2.materialId_2];
    iInfo_0.uv_11 = sphere_2.uv_3;
    iInfo_0.lightId_6 = sphere_2.lightId_2;
    iInfo_0.space_1 = _S172;
  }
}
```

This should not be allowed because the primitiveId and some other parameters are not valid for both function calls at the same time and the validity depends on the condition.
Is this to be expected since I forced the compiler to inline the function?

**Comment by Paul-Hi** [comment]
I took a closer look and created a smaller example + repro. Might be easier to work with as the source for the code above is a bit more extensive.
It seems to generally move out the function calls if there is a buffer access in it, which would be fine if access was safe.
For example, if you use a PushConstant to tell the shader how far the buffer is filled, this validity might not be given - this reproduces the behavior.
In spirv this is also broken (judging by the crashes), it would of course be possible that this is broken with every target, since the inlining probably runs before the target code generation.

[slang_issue_repro.zip](https://github.com/shader-slang/slang/files/13871481/slang_issue_repro.zip)

**Comment by csyonghe** [comment]
Thank you for the repo, this is now fixed.
