### ISSUE TITLE
slangc when compiled with option "-validate-ir" and "-emit-spirv-directly" causes validation error

### ISSUE THREAD

**Issue by pmistryNV** [shader-slang/slang#3432]
Running any slang file that emits spirv causes below validation error 

hlsl.meta.slang(3001): internal error 40007: IR validation failed: def must be ancestor of use

Bug can be replicated for example by running below command:
slangc.exe -target spirv -entry main -stage fragment -emit-spirv-directly tests\cross-compile\vk-sampler-getdimension.slang -validate-ir

**Comment by pmistryNV** [comment]
@csyonghe filed as discussed. Replicated it on  spirv path.

**Comment by pmistryNV** [comment]
Kindly refer to the updated changes

**Comment by csyonghe** [comment]
Fixed.
