### ISSUE TITLE
Full SSBO support for SPIRV/GLSL targets

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#3435]
Lowering directly to ssbo, so no compatibility issues but also no dx support.

See also https://github.com/shader-slang/slang/issues/3348

**Comment by csyonghe** [comment]
@expipiplus1 Can you provide us an estimate on when this can be done?

**Comment by natduca** [comment]
@expipiplus1 how's this going?

**Comment by expipiplus1** [comment]
Should be done here, as well as the ability to run functional tests on glsl input now https://github.com/shader-slang/slang/pull/3446

I think there's a failing test I'll need to fix before merging

**Comment by csyonghe** [comment]
This is done.
