### ISSUE TITLE
Issue with ConstBufferPointer

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3440]
I would like to convert a GLSL shader that uses `buffer_reference` to Slang. However, the result I am getting is incorrect. I have the impression that there is a missing indirection, but I have a hard time seeing where the problem is. 

Can you see if something is wrong in the following code?

| GLSL | Slang| 
| --- | --- |
| ![fCm9YktJcx](https://github.com/shader-slang/slang/assets/38076163/51ecbbb0-9f63-4ebd-8930-dff7e6e9794c) | ![OnFIE4OPjV](https://github.com/shader-slang/slang/assets/38076163/43e8d429-a9e9-4359-8ed0-45683ba6f8e7) |

In GLSL the layout looks like this:
````
struct PrimMeshInfo
{
  uint64_t vertexAddress;
  uint64_t indexAddress;
};

struct SceneDescription
{
  uint64_t materialAddress;
  uint64_t instInfoAddress;
  uint64_t primInfoAddress;
  Light    light;
};

layout(buffer_reference, scalar) readonly buffer Materials { Material m[]; };
layout(buffer_reference, scalar) readonly buffer InstanceInfos { InstanceInfo i[]; };
layout(buffer_reference, scalar) readonly buffer PrimMeshInfos { PrimMeshInfo i[]; };
layout(buffer_reference, scalar) readonly buffer Vertices { Vertex v[]; };
layout(buffer_reference, scalar) readonly buffer Indices { uvec3 i[]; };

layout(set = 0, binding = B_tlas) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = B_outImage, rgba32f) uniform image2D image;
layout(set = 0, binding = B_frameInfo, scalar) uniform FrameInfo_ { FrameInfo frameInfo; };
layout(set = 0, binding = B_sceneDesc, scalar) readonly buffer SceneDesc_ { SceneDescription sceneDesc; };
```` 

Which was converted to Slang 

````
struct PrimMeshInfoSlang
{
    ConstBufferPointer<Vertex> vertexAddress;
    ConstBufferPointer<uint3> indexAddress;
};
    
struct SceneDescriptionSlang
{
    ConstBufferPointer<Material> materialAddress;
    ConstBufferPointer<InstanceInfo> instInfoAddress;
    ConstBufferPointer<PrimMeshInfoSlang> primInfoAddress;
    Light light;
};

// Bindings
[[vk::push_constant]]  ConstantBuffer<PushConstant> pushConst;
[[vk::binding(B_tlas)]] RaytracingAccelerationStructure topLevelAS;
[[vk::binding(B_outImage)]] RWTexture2D<float4> outImage;
[[vk::binding(B_frameInfo)]] ConstantBuffer<FrameInfo> frameInfo;
[[vk::binding(B_sceneDesc)]] StructuredBuffer<SceneDescriptionSlang> sceneDesc;
```` 

To retrieve the material, in GLSL the syntax would be like:
````
Materials   materials = Materials(sceneDesc.materialAddress);
InstanceInfos iInfo_ = InstanceInfos(sceneDesc.instInfoAddress);
InstanceInfo  iInfo  = iInfo_.i[payload.instanceIndex];
Material    mat  = materials.m[iInfo.materialID];
````

In Slang, it was converted to 
````
InstanceInfo instInfo = sceneDesc[0].instInfoAddress[payload.instanceIndex];
Material mat = sceneDesc[0].materialAddress[instInfo.materialID];
````

But mat does not contain the expected values in Slang. 

In the following ZIP, I've added all shader versions, including the HLSL which is working.
 
[ray_query.zip](https://github.com/shader-slang/slang/files/13877114/ray_query.zip)

**Comment by csyonghe** [comment]
It appears to be a data stride / layout issue. I recommend double check the address computation in the generated glsl code and look for how strides are calculated. I suspect something like `indexAddress` is having a 16 bytes stride instead of 12, or somewhere inside `Vertex` we are following a different layout than what the data is assumed.

**Comment by csyonghe** [comment]
In this particular case, it is worth checking the stride for `InstanceInfo` and `Material`.
Make sure `instInfo.materialID` is at least correct.

**Comment by mklefrancois** [comment]
I'm using `emit-spirv-directly`,  do you suggest using `SpirV-cross' to generate the GLSL code? In case the stride is different, isn't there a flag in SpirV to do things the same way as GLSL?

Tomorrow I will check if `instInfo.materialID` contains the right values.

**Comment by csyonghe** [comment]
Yes, the easiest way is to use spirv-cross to generate glsl and examine the pointer offset.

**Comment by mklefrancois** [comment]
I tested spriv-cross on the output, but it generated an error.

```
SPIRV-Cross threw an exception: VariablePointers capability is not supported in GLSL.
````

I decided to use `-target glsl` and not using `-emit-spirv-directly` . This is generating the same visual error, but I could extract the GLSL code for it.

Here is the GLSL layouts from the Slang output 
```` 
layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer BufferPointer_Material_0_3
{ _735 _data; };

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer BufferPointer_InstanceInfo_0_4
{ layout(row_major) _753 _data; };

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer BufferPointer_PrimMeshInfoSlang_0_8
{ _771 _data; };

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer BufferPointer_Vertex_0_5
{ _779 _data; };

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer BufferPointer_S6_7
{ uvec3 _data; };
````

and some structs
```` 
layout(buffer_reference, std430) buffer _779
{
    vec3 position_1;
    vec3 normal_0;
    vec2 t_0;
};

layout(buffer_reference, std430) buffer _735
{
    vec3 albedo_0;
    float roughness_0;
    float metallic_0;
};
``` 

In the original GLSL code, no `buffer_reference_align` were defined, so I compiled the GLSL shader to SpirV and spriv-cross back to see how it looks.

Here are the layouts from the working GLSL

````
layout(buffer_reference, buffer_reference_align = 16, scalar) readonly buffer Vertices
{
    _807 v[];
};

layout(buffer_reference, buffer_reference_align = 4, scalar) readonly buffer Indices
{
    uvec3 i[];
};

layout(buffer_reference, scalar) buffer _807
{
    vec3 position;
    vec3 normal;
    vec2 t;
};

layout(buffer_reference, buffer_reference_align = 16, std430) readonly buffer PrimMeshInfos
{
    _1025 i[];
};

layout(buffer_reference, std430) buffer _1025
{
    uint64_t vertexAddress;
    uint64_t indexAddress;
};

layout(buffer_reference, buffer_reference_align = 4, scalar) readonly buffer Materials
{
    _1129 m[];
};

layout(buffer_reference, buffer_reference_align = 4, scalar) readonly buffer InstanceInfos
{
    _1177 i[];
};

layout(buffer_reference, std430) buffer _1177
{
    mat4 transform;
    int materialID;
};

layout(buffer_reference, std430) buffer _1129
{
    vec3 albedo;
    float roughness;
    float metallic;
};
```

I can see two things
* buffer_reference_align = 4 : sometimes it is 4 instead of 16
* scalar : uses `scalar` instead of `std430`, but the `-force-glsl-scalar-layout` was set when compiling 


But the biggest difference is how the data get retrieve

This is the GLSL (spirv-cross from original GLSL)
```
    Vertices vertices = Vertices(pinfo.vertexAddress);
    Indices indices = Indices(pinfo.indexAddress);
    vec3 barycentrics = vec3((1.0 - barycentricCoords.x) - barycentricCoords.y, barycentricCoords.x, barycentricCoords.y);
    uvec3 triangleIndex = indices.i[primitiveID];
    _807 _851;
    _851.position = vertices.v[triangleIndex.x].position;
    _851.normal = vertices.v[triangleIndex.x].normal;
    _851.t = vertices.v[triangleIndex.x].t;
    _807 v0 = _851;
    _807 _858;
    _858.position = vertices.v[triangleIndex.y].position;
    _858.normal = vertices.v[triangleIndex.y].normal;
    _858.t = vertices.v[triangleIndex.y].t;
    _807 v1 = _858;
    _807 _865;
    _865.position = vertices.v[triangleIndex.z].position;
    _865.normal = vertices.v[triangleIndex.z].normal;
    _865.t = vertices.v[triangleIndex.z].t;
    _807 v2 = _865;
    vec3 pos0 = v0.position;
    vec3 pos1 = v1.position;
    vec3 pos2 = v2.position;
````


And this is how Slang does it. Note the arithmetic instead of data access. 
 
````
    float _S9 = barycentricCoords_0.x;
    float _S10 = barycentricCoords_0.y;
    float _S11 = (1.0 - _S9) - _S10;
    uint64_t _S12 = uint64_t(sceneDesc_0._data[0].primInfoAddress_0);
    BufferPointer_PrimMeshInfoSlang_0_8 _S13 = BufferPointer_PrimMeshInfoSlang_0_8(_S12 + uint64_t(int64_t(16 * meshID_0)));
    _771 _848;
    _848.vertexAddress_0._data.position_1 = _S13._data.vertexAddress_0._data.position_1;
    _848.vertexAddress_0._data.normal_0 = _S13._data.vertexAddress_0._data.normal_0;
    _848.vertexAddress_0._data.t_0 = _S13._data.vertexAddress_0._data.t_0;
    _848.indexAddress_0._data = _S13._data.indexAddress_0._data;
    _771 _S14 = _848;
    uint64_t _S15 = uint64_t(_S14.indexAddress_0);
    BufferPointer_S6_7 _S16 = BufferPointer_S6_7(_S15 + uint64_t(int64_t(12 * primitiveID_0)));
    uvec3 _S17 = _S16._data;
    int _S18 = int(_S17.x);
    uint64_t _S19 = uint64_t(_S14.vertexAddress_0);
    BufferPointer_Vertex_0_5 _S20 = BufferPointer_Vertex_0_5(_S19 + uint64_t(int64_t(32 * _S18)));
    _779 _923;
    _923.position_1 = _S20._data.position_1;
    _923.normal_0 = _S20._data.normal_0;
    _923.t_0 = _S20._data.t_0;
    _779 _S21 = _923;
    int _S22 = int(_S17.y);
    uint64_t _S23 = uint64_t(_S14.vertexAddress_0);
    BufferPointer_Vertex_0_5 _S24 = BufferPointer_Vertex_0_5(_S23 + uint64_t(int64_t(32 * _S22)));
    _779 _958;
    _958.position_1 = _S24._data.position_1;
    _958.normal_0 = _S24._data.normal_0;
    _958.t_0 = _S24._data.t_0;
    _779 _S25 = _958;
    int _S26 = int(_S17.z);
    uint64_t _S27 = uint64_t(_S14.vertexAddress_0);
    BufferPointer_Vertex_0_5 _S28 = BufferPointer_Vertex_0_5(_S27 + uint64_t(int64_t(32 * _S26)));
    _779 _993;
    _993.position_1 = _S28._data.position_1;
    _993.normal_0 = _S28._data.normal_0;
    _993.t_0 = _S28._data.t_0;
    _779 _S29 = _993;
    vec3 pos0_0 = _S21.position_1;
    vec3 pos1_0 = _S25.position_1;
    vec3 pos2_0 = _S29.position_1;
````

It is unclear whether the `scalar` would solve the issue, as there is a disagreement between stride and alignment. While modifying all structs to be aligned to 16 is possible, it is not always feasible or recommended due to padding constraints. For instance, the indices are packed as `uvec3`, and changing this would require modifying the data access method.

**Comment by csyonghe** [comment]
Alignments can be explicitly specified in ConstBufferPointer type as `ConstBufferPointer<T, alignment>`.
Perhaps try explicitly specify the alignments to 4 in the shader code?

**Comment by mklefrancois** [comment]
I tried, by doing the following

````
    ConstBufferPointer<Material, 4> materialAddress;
````

But I can see two layouts spitting out for the material, one with an alignment of 4 and one with 16

``` 
layout(buffer_reference, std430, buffer_reference_align = 4) readonly buffer BufferPointer_Material_0_3
{
    Material_0 _data;
};

layout(buffer_reference, std430, buffer_reference_align = 16) readonly buffer BufferPointer_Material_0_9
{
    Material_0 _data;
};
```

and unfortunately, it is using the wrong one
```
        BufferPointer_Material_0_9 _S66 = (BufferPointer_Material_0_9((_S65 + uint64_t(20 * _S60.materialID_0))));
```

**Comment by csyonghe** [comment]
I am adding true/complete pointer support to SPIRV, and will take care of this issue along the way.

**Comment by csyonghe** [comment]
General pointer type (T*) is now supported.

Currently this is only support on the direct-to-spirv backend. GLSL backend to come.

**Comment by alexmcain** [comment]
Sorry to jump in this one that seems to be closed but I have the same issue and if I try to use pointers as suggested still not working for me, I have the same case as the first post just struct of uint64_t vertexAddress, what would be the equivalent with the new pointer implementation? I tried to cast it to (Vertex*) but seems not correct, still the code compiles but in screen the cube is broken as show in the example, the padding is correct only to mat4 before the address declaration. Any help is appreciated.

**Comment by csyonghe** [comment]
You can declare Vertex* vertices directly in a uniform buffer. Casting uint64 to Vertex* should also work.

everything accessed through a buffer is laid out using std430 rules by default. I suggest double checking the generated spirv to make sure the offsets match what your host code expects.

If you find Slang generates any code that doesn’t seem to be correct, please share a reproducer and we can take a look.

**Comment by alexmcain** [comment]
Thank you so much for the fast reply, I will do again with the latest version and check. I will let you know.  Jic I left my code attached including the glsl that works.
[meshSlangTest.zip](https://github.com/user-attachments/files/17797880/meshSlangTest.zip)
[originalGLSL.mesh.txt](https://github.com/user-attachments/files/17797882/originalGLSL.mesh.txt)

**Comment by maxime-modulopi** [comment]
> everything accessed through a buffer is laid out using std430 rules by default. I suggest double checking the generated spirv to make sure the offsets match what your host code expects.

From my attempts at compiling raw pointers to SPIR-V, they are using the `natural` layout variant of the type, which is equivalent to `scalar` in GLSL.

Also, [this comment](https://github.com/shader-slang/slang/blob/ebfbe5886f273e0492321c5ff0c9c2671583a648/source/slang/slang-ir-layout.h#L14-L16) says that the natural layout matches how types are stored in storage buffers and structured buffers, which I believe is (at least partly) wrong.
The GLSL specs state that storage buffers use `std430` by default when targetting SPIR-V (with `scalar` added by the `GL_EXT_scalar_block_layout` extension):
> The initial state of compilation when generating SPIR-V is as if the following were declared:
> 
> layout(std140, column_major) uniform;
> layout(std430, column_major) buffer;
> 
> However, when push_constant is declared, the default layout of the buffer will be std430. There is no method to globally set this default.

For the strucured buffers part, I'm not sure as I'm not familiar enough with D3D/HLSL.
