### ISSUE TITLE
Missing rayQueryGetIntersectionTriangleVertexPositionsEXT method from RayQuery

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3450]
The method `rayQueryGetIntersectionTriangleVertexPositionsEXT` is missing from `RayQuery`. 

Since `RayQuery` is a struct, with `rayQueryEXT` member in the struct, it doesn't seem possible to implement the spirv code injection with `__target_switch`. 

Deriving doesn't work either. For example, this is not legal.

```
struct myRayQuery<let rayFlagsGeneric : RAY_FLAG = RAY_FLAG_NONE> :  RayQuery<rayFlagsGeneric>
{
    __glsl_extension(GL_EXT_ray_query)
    __glsl_version(460)
    [__NoSideEffect]
    float3[3] CommittedTriangleVertexPositions()
    { /* ... code ... */ }
}
```

**Comment by kaizhangNV** [comment]
Code is merged, close the issue.

**Comment by mklefrancois** [comment]
Tested, it works as expected. Thanks
