### ISSUE TITLE
Integrate SLANG into VK-GL-CTS

### ISSUE THREAD

**Issue by pmistryNV** [shader-slang/slang#3476]
Currently VK-GL-CTS uses GLSANG to generate SPIRV.
Replace this interface with SLANG and run the CTS to see the compliance rate.

**Comment by pmistryNV** [comment]
@csyonghe fyi

**Comment by pmistryNV** [comment]
@akolheNV @natduca i will be working on this as highest priority.

**Comment by pmistryNV** [comment]
ISession interface for compiling glsl has following issues:
1. There is no way to set glsl compatibility. For current work I added explicity API's. But this needs to be fixed
2. There is no way explicitly to configure the Entrypoint before compilation. ISession when compiling looks for [shader("compute")] to determine the entrypoint. Which is not present in a GLSL or a HLSL shader. This also needs fixing.


For current integration hence I switched to ICompileRequest which slangc the offline compiler uses. That interface was more stable. We will also need to decide which interface to keep as final one.

**Comment by csyonghe** [comment]
The `ISession` interface is what we want to eventually move onto. It is more flexible in terms of specifying how specialization shall take place. But like you discovered, it still has a lot of holes compared to the legacy interface. We should fix all these holes.

**Comment by akolheNV** [comment]
@csyonghe @pmistryNV please file issue for `ISession` interface. As I understand from this conversation, it's not a blocker. So perhaps it's a Q2/Q3 item. Also note that @pmistryNV will have follow up work for `iSession` to make it compatible with VK-CTS (about 1-2 weeks of effort)

**Comment by pmistryNV** [comment]
@csyonghe after the CTS merge I am closing this bug. And I will be opening 2 bugs, one for server/client implementation and the ISession interface cleanup

**Comment by pmistryNV** [comment]
Created bugs 3576 and 3575 for follow up work.

For present work a fork of VK-GL-CTS https://github.com/shader-slang/VK-GL-CTS has been created and SLANG integration was done with https://github.com/shader-slang/VK-GL-CTS/pull/1.
Two ways to test with CTS
1.Users can fetch the pre-built binary from https://github.com/shader-slang/VK-GL-CTS/releases/tag/vulkan-cts-slang-0.0.1
2. Users  can build the CTS and put slang.dll and slang-llvm.dll in the same folder where deqp-vk.exe is generated and test it out.
