### ISSUE TITLE
Outdated documentation for spAddEntryPoint

### ISSUE THREAD

**Issue by chloekek** [shader-slang/slang#3483]
The [API users guide](https://github.com/shader-slang/slang/blob/master/docs/api-users-guide.md#entry-points) reads:

```c
SlangProfileID profileID = spFindProfile(session, "ps_5_0");

int entryPointIndex = spAddEntryPoint(
    request,
    translationUnitIndex,
    "main",
    profileID);
```

However, the API takes a stage, not a profile ID:

https://github.com/shader-slang/slang/blob/4e7e820c3dda716334ccbe9854379e46d8d332bb/slang.h#L1726-L1730

It seems that the shader stage and the target profile must be specified separately, but the guide does not explain how.

**Comment by tangent-vector** [comment]
We intend to deprecate the C API for Slang (the `sp*` entry points), so documentation bugs related to that API are realistically not going to get fixed unless an external contributor wants to put up a PR.

Closing as will-not-fix.
