### ISSUE TITLE
AutoPyBindCUDA issues on CUDA 12.3 / 545.23.08

### ISSUE THREAD

**Issue by nihofm** [shader-slang/slang#3484]
First of all thank you very much for differentiable Slang, it has been extremely helpful in my project so far and I've already got some colleagues to try it as well.

However, I've ran into an issue which took me quite a while to track down. After our cluster updated the system-wide graphics driver to 545.23.08 and CUDA 12.3 (latest on Ubuntu 22.04) I got invalid memory access or invalid program counter CUDA errors seemingly at random.

I am executing OptiX, standard PyTorch and differentiable Slang kernels in sequence and some (but not all) configurations threw these errors. I could finally track it down to kernels using `[AutoPyBindCUDA]` on 545.23.08 / CUDA 12.3 while the identical code ran fine on CUDA 12.0/1 and graphics driver (whatever version comes installed with the CUDA toolkit on Ubuntu).

Not sure what caused this, it might be a driver bug, or related to stream synchronization, I did not dive deep enough to confirm. A simple `torch.cuda.synchronize()` or `cudaStreamSynchronize(...)` did not solve this problem, however. When re-writing the respective kernels with manual plumbing instead of `[AutoPyBindCUDA]` the errors disappeared on both systems.

It might be worth looking into this in case someone else runs into the issue. Automatic kernel bindings are an extremely helpful QoL feature for small differentiable kernels.

I just managed to resolve this after a long debugging session and wanted to report, please let me know if I should look into a minimal example.

**Comment by csyonghe** [comment]
Please note that the officially supported CUDA version for PyTorch is 11.8 or 12.1 according to their documentation on the Getting Started page. So this is a PyTorch problem not a slang issue. Closing now.
