### ISSUE TITLE
[Slang VK CTS] Uber issue to track progress

### ISSUE THREAD

**Issue by akolheNV** [shader-slang/slang#3501]
All VK CTS shader based tests can be found here - https://docs.google.com/spreadsheets/d/1J-gLbTbLNytr8tqJeUWGrNyA3p-kvJncMz3PRAlQF7o/edit#gid=1161893048

**Comment by akolheNV** [comment]
@pmistryNV once Slang is integrated with VK-CTS, post the baseline pass rate here.

**Comment by swoods-nv** [comment]
Is this bug actually being used?

**Comment by akolheNV** [comment]
Not needed anymore. We have separate bugs to track each category. Closing
