### ISSUE TITLE
Array-of-structs with textures are getting assigned wrong texture registers

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#351]
I added the following struct to `LightData`:
```C++
struct LightTextures
{
    // Textures for light-probes. #OPTME If the textures was filtered using linear-filtering then the spec and diffuse term is the same texture and we can save a fetch. The default is pre-integration, so that probably doesn't matter much
    Texture2D diffuseProbe2D;
    Texture2D specularProbe2D;
    SamplerState samplerState;
};
```

When I compile it, Slang generates the following lines:
```C++
Texture2D<vector<float,4> >  SLANG_parameterGroup_InternalPerFrameCB_gLights_textures_diffuseProbe2D[16]: register(t0);
Texture2D<vector<float,4> >  SLANG_parameterGroup_InternalPerFrameCB_gLights_textures_specularProbe2D[16]: register(t1);
```

 `specularProbe2D` is getting register `t1` which conflicts with the registers assigned for `diffuseProbe2D`

**Comment by tfoleyNV** [comment]
I have what should be a fix for this in the works. Or at least it is a fix for the invalid code that gets emitted (it should give the arrays in your example non-conflicting register ranges).

What *isn't* fixed yet in the change I'm working on (#352) is the reflection information on the "stride" of such an array. I'll need to figure out the math for that first, so it will probably be a follow-on. Hopefully just having the basic code emit working can unblock you for now.
