### ISSUE TITLE
[Slang Unit Tests] Pilot unit test for compiler verification to understand Slang unit test infra

### ISSUE THREAD

**Issue by akolheNV** [shader-slang/slang#3513]

**Comment by akolheNV** [comment]
That's great! Do we have a pilot unit testing working that's authored by @tgrimesnv?

**Comment by tgrimesnv** [comment]
> That's great! Do we have a pilot unit testing working that's authored by @tgrimesnv?

https://github.com/shader-slang/slang/pull/3583
