### ISSUE TITLE
Missing Flat decoration (spirv direct)

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3515]
I'm trying to pass the instanceIndex from Vertex to Pixel shader

```
// Vertex
output.stage.id = InstanceIndex();

// Pixel
uint particleID = stage.id;
```

It compiles, it works, but Vulkan complains
```
Fragment OpEntryPoint operand 35 with Input interfaces with integer or float type must have a Flat decoration for Entry Point id 165.
  %gl_InstanceID = OpVariable %_ptr_Input_uint Input
```
The id was decorated with nointerpolation
```
struct PSin
{
  nointerpolation uint id : DRAW_ID;
  float2 uv : TEXCOORD;
};
```

In attachment the shader and the SPIRV result.
[raster.zip](https://github.com/shader-slang/slang/files/14050496/raster.zip)

**Note**: in the Spirv output, there are 52 repeated lines of:
```
               OpExecutionMode %fragmentMain DepthReplacing
```

**Comment by csyonghe** [comment]
#3558 should fix this. The problem is not with missing flat decoration, it is that `gl_InstanceID` / InstanceId is no longer a supported builtin on Vulkan. It should be gl_InstanceIndex / InstanceIndex.

**Comment by csyonghe** [comment]
`InstanceIndex` is for ray tracing stages only.
To get vertex instance id, you need to use SV_InstanceId semantic:
```
VertexOut vertexMain(int instanceId : SV_InstanceId)
{
}
```

**Comment by mklefrancois** [comment]
This make no difference with the current issue. 
The problem might be that the compilation uses: `-emit-spirv-directly -fvk-use-entrypoint-name` and both vertex and fragment are in the same file. 

The validation error appears when the value of instanceID is transmitted to the fragment, 

Here is how this looks like, the `particleID` need to be made available to the fragment shader. But if `particleID` == `instanceId` or `InstanceIndex()`, there will be an error.

```
// Per-vertex attributes to be assembled from bound vertex buffers.
struct VSin
{
  [[vk::location(0)]] float3 position : POSITION;
  [[vk::location(1)]] float2 uv : TEXCOORD;
};

// Output of the vertex shader, and input to the fragment shader.
struct PSin
{
  nointerpolation uint id : DRAW_ID;
  float2 uv : TEXCOORD;
};

// Output of the vertex shader
struct VSout
{
  PSin stage;
  float4 sv_position : SV_Position;
};

// Output of the fragment shader
struct PSout
{
  float4 color : SV_Target;
};

VSout vertexMain(VSin input, int instanceId: SV_InstanceId)
{
  uint particleID = instanceId;
  float2 particle = input.position.xy * frameInfo.radius + (particles[particleID].position * frameInfo.scale * 2);

  VSout output;
  output.sv_position = mul(frameInfo.proj, float4(particle, 0.0, 1.0));
  output.stage.uv = input.uv;
  output.stage.id = particleID;

  return output;
}

// Fragment Shader
[shader("pixel")]
PSout fragmentMain(PSin stage, float4 fragCoord : SV_Position)
{
  uint particleID = stage.id;
...
}
```


In GLSL, to transfer the information, we use the layout, like this: 

```
raster.vert
-----------
layout(location = 0) out vec2 outUv;
layout(location = 1) out flat int outParticleID;

main()
{
...
outParticleID = gl_InstanceIndex;
...
}

raster.frag
-----------
layout(location = 0) in vec2 inUv;
layout(location = 1) in flat int inParticleID;
layout(location = 0) out vec4 outColor;

// inParticleID can be used anywhere
```

So, the Slang code still current emit the error
```` 
[VUID-StandaloneSpirv-Flat-04744] Fragment OpEntryPoint operand 35 with Input interfaces with integer or float type must have a Flat decoration for Entry Point id 165.
  %gl_InstanceIndex = OpVariable %_ptr_Input_int Input
```

Tested with SLANGC version: 1707300689

**Comment by csyonghe** [comment]
The error is confusing since instanceId is never defined as a fragment shader parameter, but somehow the validation layer complains that it is a fragment shader input.

**Comment by csyonghe** [comment]
Can you attach the full apirv here?

**Comment by mklefrancois** [comment]
I reverted my changes and back using `uint particleID = InstanceIndex();` and the error is gone with SLANGC version: 1707300689

The error is present in 2024.0.3

**Comment by csyonghe** [comment]
It is incorrect to use InstanceIndex by spirv and Vulkan spec. InstanceIndex map to the built in gl_InstanceID or the InstanceId spirv built in, which is removed from the glsl spec / Vulkan. If you update to latest Vulkan sdk you should see the validation error.

**Comment by csyonghe** [comment]
On my test machine, I can't reproduce the validation error you mentioned. Probably because we use different sdk version?

**Comment by mklefrancois** [comment]
The sample can be found under https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/realtime_analysis

The shader is [raster.slang](https://github.com/nvpro-samples/vk_mini_samples/blob/main/samples/realtime_analysis/shaders/raster.slang).

The Vulkan SDK is 1.3.275

Here is the SPIRV output
[raster_slang.spv.zip](https://github.com/shader-slang/slang/files/14196855/raster_slang.spv.zip)

**Comment by csyonghe** [comment]
Will take a look. Thanks!
