### ISSUE TITLE
Missing equivalent GLSL Group/Subgroup built-in in Slang 

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3522]
Regarding Subgroup, Slang have only those direct functions
* WaveGetLaneCount() : gl_SubgroupSize
* WaveGetLaneIndex() : gl_SubgroupInvocationID

But many other are missing for Group and Subgroup, such as:
* gl_NumWorkGroups
* gl_SubgroupID
* gl_WorkGroupID

The `gl_WorkGroupID` can be retrieved by adding a parameter to the compute shader with the `SV_GroupID` decoration, but wouldn't it be possible to have a function similar to the WaveGetLane function? 

Similarly, the `gl_SubgroupID` can be computed, but first it needs to get the `gl_LocalInvocationID` with an extra parameter to the compute shader and with the `SV_GroupThreadID` decoration. Then `gl_SubgroupID = gl_LocalInvocationID/WaveGetLaneCount()`. But I think a Slang function would be nicer.

But the big missing one is `gl_NumWorkGroups`, which in Slang, it requires to pass this information through a buffer.

**Comment by csyonghe** [comment]
gl_NumWorkGroups isn't available in HLSL, so even if we provide it, we won't be able to compile to HLSL. Due to our limited engineering resources and that this is unlikely a blocking issue, we are not planning to support it now. If you feel strongly that we must add it now, please reopen the issue.

**Comment by mklefrancois** [comment]
HLSL backend had very little interest at the moment and was hoping that Slang could be a modern replacement for the dated but still very much alive GLSL. Or should I say SPIRV, as this is the language for Vulkan. 

One suggestion, if it's not part of the language itself, would it be possible to have all these useful built-in in a separate header? That way, someone using Slang for the intended SPIRV would have access to all the useful features, and it would be clear that it's not intended for CUDA or HLSL. I'm just thinking out loud about ways to make the transition from GLSL to SPIRV as easy as possible.

**Comment by csyonghe** [comment]
Actually, if we just want to support this for Vulkan/Spirv, this is easy. You can even write your own intrinsics using spriv_asm syntax. I can certainly add that in for now without HLSL support.

**Comment by csyonghe** [comment]
int3 GetWorkgroupCount()
{
__target_switch
{
case glsl: __intrinsic_asm “gl_NumWorkGroups”;
case spirv: return spirv_asm {
        result:$$int3 = OpLoad builtin(NumWorkgroups:int3);
   };
}
}

**Comment by mklefrancois** [comment]
Thanks for the example, I guess there would be a way to make for spirv all the missing built-ins.
