### ISSUE TITLE
Slang Test Plan First Draft

### ISSUE THREAD

**Issue by akolheNV** [shader-slang/slang#3527]
Slang Test Plan details can be found in this doc
https://docs.google.com/spreadsheets/d/1b91Ctu5-cgsIoaxRJl7JMWnJBdQnRxGGHrlL4ZZwh90/edit#gid=0

**Comment by akolheNV** [comment]
Assigning to @ychenNV for now. Yuan, we might want to get @dzysk started on this.

**Comment by ychenNV** [comment]
Assigning to @dzysk

**Comment by dzysk** [comment]
I have a first draft of the Verification Overall SLANG Test Plan here: https://docs.google.com/document/d/19yRCzUJgFbE-BccONBQWI7T6J_24qrCREs-CoNd8Fkw/edit

**Comment by dzysk** [comment]
In order to better fit into a sprint, I'm going to call this completion of the first draft. I opened issue [https://github.com/shader-slang/slang/issues/3887](url) to track the review and sign off effort.

**Comment by dzysk** [comment]
The first draft is ready for review. Closing this as we move on to the next phase of addressing review comments in issue: [https://github.com/shader-slang/slang/issues/3887](url)
