### ISSUE TITLE
[SPIR-V] StructuredBuffer packing control

### ISSUE THREAD

**Issue by HansKristian-Work** [shader-slang/slang#3534]
In D3D, this shader has stride of 12, i.e. scalar layout:

```
[vk::binding(2, 3)] RWStructuredBuffer<float3> buffer0;

[shader("compute")]
[numthreads(1,1,1)]
void computeMain(uint3 threadId : SV_DispatchThreadID)
{
	buffer0[1] = buffer0[0];
}
```

but slang treats this as std430 in GLSL:

```
#version 450
layout(row_major) uniform;
layout(row_major) buffer;

#line 1 0
layout(std430, binding = 2, set = 3) buffer StructuredBuffer_float3_t_0 {
    vec3 _data[];
} buffer0_0;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{

#line 7
    buffer0_0._data[1U] = buffer0_0._data[0U];
    return;
}
```

Is there a way to get control over which packing rules are used? Ideally, it should be possible to have control over array stride and offsets for all structs that are emitted to SSBOs.

GLSL currently has a major restriction that layout(offset) can only be used on top-level members of a block, but not any struct type.

**Comment by csyonghe** [comment]
You can pass the -force-glsl-scalar-layout option to force scalar layout in all buffer blocks.

**Comment by HansKristian-Work** [comment]
> You can pass the -force-glsl-scalar-layout option to force scalar layout in all buffer blocks.

Is there a way to control this per buffer?

**Comment by csyonghe** [comment]
We don't have this control yet, but we are likely going to support them soon as part of the GLSL compatibility work.

**Comment by csyonghe** [comment]
Slang now supports:
```
StructuredBuffer<float3, ScalarDataLayout> scalarBuffer;
```
