### ISSUE TITLE
Automatic coercion from CB/block type when specializing generic

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#354]
We support implicit conversion from the "pointer-like" types `ConstantBuffer<T>` and `ParameterBlock<T>` to their element type T. For example, given a type `LightEnv` and a function `getAmbient` on that type:

```hlsl
struct LightEnv { float3 ambient; }
float3 getAmbient(LightEnv env);
```

we can declare a `ConstantBuffer<LightEnv>` variable, and call `getAmbient()` directly on the CB (it will implicitly extract the single value in the buffer):

```hlsl
ConstantBuffer<LightEnv> gLightEnvCB;
float3 x = getAmbient(gLightEnvCB);
```

However, if we start using generics and interfaces to define our type/functions:

```hlsl
interface ILightEnv { float3 getAmbient(); }
struct DefaultLightEnv : ILightEnv { float3 ambient; ... }

float3 getAmbient<L : ILightEnv>(L env) { return env.getAmbient(); }
```

we no longer get the same convenience when calling `getAmbient` with a CB:

```hlsl
ConstantBuffer<DefaultLightEnv> gLightEnvCB;
float3 x = getAmbient(gLightEnvCB);
```

The compiler complains in this case, because it cannot infer a valid type for the generic parameter `L`. It tries to use `ConstantBuffer<DefaultLightEnv>`, but that fails because the CB type doesn't conform to the `ILightEnv` interface.

It would be desirable in a case like this for the compiler to infer that the type `DefaultLightEnv` should be used as the argument for the generic parameter `L`. Once this generic argument is inferred, the existing implicit conversion picks up the slack.

Note that the user can explicitly request the specialization they want, and make things work:

```hlsl
float3 x = getAmbient<DefaultLightEnv>(gLightEnvCB);
```

That workaround isn't viable in cases where we are trying to refactor an existing library function to be more generic (e.g., it used to require a specific concrete type, but is now generic on any type supporting a given interface), since it would require existing call sites to change.

The only gotcha we need to be careful of here is whether there are cases where the user might actually *want* the substitution with `L = ConstantBuffer<DefaultLightEnv>`. That is, should we always do implicit dereference like this when doing inference, or should we only do it as a fallback in cases where substitution would fail without it?

**Comment by csyonghe** [comment]
Fixed.
