### ISSUE TITLE
Implement ray tracing extensions for GLSL in glsl.meta.slang and bring the parity to HLSL

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3560]
This task is a subtask from the other issue #3362 , which is a big task.
This issue is to cover a smaller portion of it so that we can work with other people together.

We have "ray-tracing" functionality implemented for HLSL but it is not implemented for GLSL.
The goal of this task is to bring the parity to GLSL as much as slangc already does for HLSL.

The description for the "ray_query" extension can be found from [here](https://github.com/KhronosGroup/GLSL/blob/main/extensions/ext/GLSL_EXT_ray_query.txt)

The description for the "shader_invocation_reoder" extension can be found from [here](https://github.com/KhronosGroup/GLSL/blob/main/extensions/nv/GLSL_NV_shader_invocation_reorder.txt)

The description for the "ray_tracing_motion_blur" extension can be found from [here](https://github.com/KhronosGroup/GLSL/blob/main/extensions/nv/GLSL_NV_ray_tracing_motion_blur.txt)

**Comment by ArielG-NV** [comment]
note: need to add GL_EXT_ray_tracing to the implementation (a 4th raytracing ext)
