### ISSUE TITLE
Add uniformity analysis to the compiler

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3562]
Some developers are experiencing unexpected performance issues when they accidently access an array with non-uniform index.

The compiler can help analyze the code for potential performance issues linked with this and issue a performance warning for such cases. There should also be a way to allow the developer to silence the warning by clarifying their intend in code.

This can be implementing by propagating a `__uniform` tag in a data flow pass, much like how we handle differentiability.
The user can always clarify a use site with a `__treat_as_uniform(x)` wrapper to silence any warnings.

**Comment by natduca** [comment]
Moving back into Q1 per our chat in 3/5 bug scrub

**Comment by csyonghe** [comment]
Done in #3704.
