### ISSUE TITLE
Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [shader-slang/slang#3577]
**Describe the feature**
@csyonghe,
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd video cards if cuda code is optimized, and speed up work on amd.

**Comment by csyonghe** [comment]
What kind of work are you looking for in the Slang project? As a compiler we cared mostly about generating cuda code as output and less about running that code. One can always use Slang to generate cuda, and run that code with ZLUDA without needing to change Slang.

**Comment by swoods-nv** [comment]
Marking as wontfix; please reopen if specific action is required.
