### ISSUE TITLE
<tex_object>.SampleLevel doesn't work with CPU when using the Offset parameter

### ISSUE THREAD

**Issue by tgrimesnv** [shader-slang/slang#3584]
When executing SampleLevel using Offset parameters in slang-test, we get a failure with the CPU profile.

Example calls:

val += t1D.SampleLevel(samplerState, u, 0, 1);
val += t2D.SampleLevel(samplerState, float2(u, u), 0, int2(1, 1));
val += t3D.SampleLevel(samplerState, float3(u, u, u), 0, int3(1, 1, 1));
val += t1DArray.SampleLevel(samplerState, float2(u, 0), 0, 1);
val += t2DArray.SampleLevel(samplerState, float3(u, u, 0), 0, int2(1, 1));

Where val and u are a float.

**Comment by csyonghe** [comment]
Textures on CPU are not fully implemented so this is expected. Let's focus on other issues first.
