### ISSUE TITLE
<tex_object>.SampleCmpLevelZero gives compile errors with Vulkan

### ISSUE THREAD

**Issue by tgrimesnv** [shader-slang/slang#3585]
Examples:
(val and u are float)
SamplerComparisonState shadowSampler;

val += t1D.SampleCmpLevelZero(shadowSampler, u, 0);
val += t2D.SampleCmpLevelZero(shadowSampler, float2(u, u), 0);
val += tCube.SampleCmpLevelZero(shadowSampler, normalize(float3(u, 1 - u, u)), 0);

// Offset variant
val += t1D.SampleCmpLevelZero(shadowSampler, u, 0, 0);
val += t2D.SampleCmpLevelZero(shadowSampler, float2(u, u), 0, int2(0, 0));

Errors:
glslang:  (58): error :  'textureLod' : no matching overloaded function found
glslang:  (58): error :  '' : compilation terminated
glslang: note : ERROR: 2 compilation errors.  No code generated.

**Comment by csyonghe** [comment]
Hmm, this is also expected I guess. We need to verify that the direct to spirv backend is correct on this.
To use the direct to spirv backend, pass -emit-spirv-directly in the arguments.

**Comment by tgrimesnv** [comment]
Still has issues with that option. But I have it now ifdef'd out and can re-enable vulkan for the rest of the test.

**Comment by csyonghe** [comment]
OK, then that's something we need to fix as a separate issue.

**Comment by swoods-nv** [comment]
Marking for current milestone bc it sounds like this is preventing test passage; feel free to push to later milestone if this is not a priority.

**Comment by pmistryNV** [comment]
@kaizhangNV as per discussion with @csyonghe assigning this to myself.

**Comment by pmistryNV** [comment]
@tgrimesnv I have re-enabled the tests. They were passing, just needed updating the results.

**Comment by tgrimesnv** [comment]
I guess it may have been indirectly fixed since I opened this. Good to hear all is well now. Closing.
