### ISSUE TITLE
TextureCube.SampleGrad is defined with float2 for DDX/DDY when it should be float3

### ISSUE THREAD

**Issue by tgrimesnv** [shader-slang/slang#3586]
Example:
float _ddx = 0.0f, _ddy = 0.0f;
val = tCube.SampleGrad(samplerState, normalize(float3(u, 1 - u, u)), float3(_ddx, _ddx, _ddx), float3(_ddy, _ddy, _ddy));

This is how it's supposed to be called, but the slang extension for VS Code shows an error saying "expected an expression of type 'vector<float,2>', got 'vector<float,3>'(30019)" but this is wrong according to the Microsoft docs here: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-samplegrad

Executing this with float3 or float2 (even though that's wrong) both gives an assert in slang-test, but no error message in stdout.

**Comment by csyonghe** [comment]
I believe this is fixed in top of tree, can you merge and retest?

**Comment by tgrimesnv** [comment]
It does look like it has been fixed.
