### ISSUE TITLE
Invalid code generation for uint matrices with glslang backend

### ISSUE THREAD

**Issue by skallweitNV** [shader-slang/slang#3592]
`uintNxM` matrices in slang are converted to `umatNxM` matrices through the glslang backend. However, it seems glsl only supports floating-point matrices. The compiler should probably emit some error when using non-floating-point matrices with the glslang backend.

Are non-floating-point matrices supported with the direct SPIR-V backend?

**Comment by skallweitNV** [comment]
Just tested with the SPIR-V backend, and the uint matrix types seem to work.

**Comment by csyonghe** [comment]
We are deprecating the glsl path so we are not going to fix this.
