### ISSUE TITLE
Crash when raytracing used on cuda/ptx

### ISSUE THREAD

**Issue by jeroen-van-schijndel-otoy** [shader-slang/slang#3593]
building one of the following raytracing examples :
https://github.com/shader-slang/slang/blob/master/examples/ray-tracing-pipeline/shaders.slang
https://github.com/shader-slang/slang/blob/master/examples/ray-tracing/shaders.slang

segfault when trying to do so with the following commandline
`./slangc.exe -target cuda shaders.slang`
no other useful output is given

this happens on latest master but also in this release https://github.com/shader-slang/slang/releases/download/v2024.0.6/slang-2024.0.6-win64.zip

Building for target spirv glsl or hlsl works fine.

**Comment by csyonghe** [comment]
We don't support compiling vertex and fragment shaders to CUDA, which is present in the file.

**Comment by jeroen-van-schijndel-otoy** [comment]
A error informing the user of that would be appreciated

**Comment by natduca** [comment]
Hey, @csyonghe  why not convert this bug to being a non-crash so that this doesn't trip people up, instead of closing it?

**Comment by csyonghe** [comment]
Yes, we should fix any crashes, sorry for closing this prematurely.

**Comment by bmillsNV** [comment]
@ArielG-NV can you take a look at this next sprint?

**Comment by ArielG-NV** [comment]
Sure, should be a small issue.
