### ISSUE TITLE
More slang  OptiX compilation issues with finding nvrtc

### ISSUE THREAD

**Issue by half-potato** [shader-slang/slang#3597]
Despite passing the location of nvrtc to slangc when compiling ptx using `-Xnvrtc... -I${OptiX_INSTALL_DIR}/include`, I'm still getting the following error on certain machines:
```
(0): error 100: failed to load downstream compiler 'nvrtc'
(0): note 99999: failed to load dynamic library 'nvrtc'
(0): error 52002: could not find a suitable pass-through compiler for 'nvrtc'.
```
nvcc is able to compile to ptx still.

**Comment by csyonghe** [comment]
That's not passing the location of nvrtc, the `-I` command is passing a downstream compiler option to specify additional include path. nvrtc must be discoverable from `CUDA_PATH` or `PATH`.

**Comment by csyonghe** [comment]
Please make sure you have CUDA SDK installed and CUDA_PATH environment variable available.
