### ISSUE TITLE
Register and space are ignored for ParameterBlocks and ConstantBuffers of interface types.

### ISSUE THREAD

**Issue by VladSerhiienko** [shader-slang/slang#3602]
I've tried to slightly modify the model viewer example - https://github.com/shader-slang/slang/blob/master/examples/model-viewer/shaders.slang#L356 - and see how reflection looks like in this case:
```
ConstantBuffer<PerView> gViewParams : register(b3, space0); // Reflection reports expected values.
ConstantBuffer<PerModel> gModelParams : register(b2, space1); // Same.
ConstantBuffer<ILightEnv> gLightEnv : register(b1, space2); // Reflection reports zeros.
ConstantBuffer<IMaterial> gMaterial : register(b0, space3); // Also zeros.
```
It appears that if ConstantBuffers are declared with interface types, registers and spaces are ignored. `getBindingSpace` and `getBindingIndex` return zeros. I've also tried setting only a space. The program is fully specified with `DirectionalLight` and `SimpleMaterial`.

When I specify types in shader (as below), reflection looks good:
```
ConstantBuffer<DirectionalLight> gLightEnv : register(b1, space2); // Register and space are correct.
ConstantBuffer<SimpleMaterial> gMaterial : register(b0, space3);
```

Note: I've tried to set only space for interface constant buffers and use `SLANG_TARGET_FLAG_PARAMETER_BLOCKS_USE_REGISTER_SPACES` (because it's unclear how it potentially compiles if resources are present in a specified type) but got the same results - zeros. I'd expect: all values collected into a constant buffer and sequentially indexed resources in the specified space (descriptor set).

Seems like a bug.

**Comment by csyonghe** [comment]
ParameterBlock of interface types is still an under-used feature. Due to constrained engineering resources we won't be able to fix this soon. Please let us know if this is a blocking issue for you and we can reprioritize. But for now we need to close this.
