### ISSUE TITLE
`[[vk::push_constant]]` and `layout(push_constant)` are ignored for DXIL target.

### ISSUE THREAD

**Issue by VladSerhiienko** [shader-slang/slang#3603]
Push constants should be reported as constant buffers with `PUSH_CONSTANT` category even for DXIL target because they are directly translatable to 32-bit root constants in D3D12 and `set[Stage]Bytes` on Metal. Otherwise, there is no way to know for a developer how to map such declarations correctly, and it might be an important optimization depending on context.

**Comment by csyonghe** [comment]
Whether or not a constant buffer is placed into root constant is a decision that only affects the creation of root signature and does not affect the resulting HLSL shader code. As a result, Slang allows the user to define arbitrary attributes on the shader parameter and use reflection API to query if a shader parameter has a certain attribute. The application can then use this info to create their root signatures.

**Comment by csyonghe** [comment]
See d3d12-shader-object-layout.cpp:38:
```
    if (rootParameterAttributeName)
    {
        if (auto leafVariable = typeLayout->getBindingRangeLeafVariable(bindingRangeIndex))
        {
            if (leafVariable->findUserAttributeByName(globalSession, rootParameterAttributeName))
            {
                isRootParameter = true;
            }
        }
    }
```

Here we are iterating the fields of a type and check if the field is decorated with an attribute named `rootParameterAttributeName`, and if so the gfx layer will put it in root constant.
