### ISSUE TITLE
Support extensions

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#361]
1. extend a concrete type to make it implement an additional interface. The front-end need to be able to pass those subtype witnesses as arguments in generic substitution.
2. when looking for decls that satisfying conformance, include search in extensions (may not do it now)
3. when generating code for a method in an extension, make sure to get the correct type for `this` parameter.
4. be careful when assuming the parent of an inheritance decl is the `AggTypeDecl`, it could be an extension decl, and we need to use the target type.

Allow extensions to interfaces
5. when checking conformance of `C:IFoo`, consider all extensions of `IFoo` that could make it inherit from `IBar` (so to check `C:IBar`).
6. allow default implementations of interface methods in such extension.

**Comment by tfoleyNV** [comment]
The majority of this work has been done, and it makes sense to address the remaining limitations as separate issues.

Implementing the full feature set that we want for extending interfaces (that is, allowing/requiring a default implementation for the base interface) will probably rely on the IR-level type system to be completed.
