### ISSUE TITLE
Nested generics

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#362]
Trying to call a generic method inside a generic type leads to a failure. It seems like we are only using the outer-most layer of generic arguments for specialization/substitution.

**Comment by csyonghe** [comment]
```
interface IBRDF
{
    float getF();
}

interface ILight
{
    float illum<B:IBRDF>(B b);
};

struct B0 : IBRDF
{
    float getF() { return 1.0; }
};

struct L0 : ILight
{
    float illum<B:IBRDF>(B b) { return b.getF(); }
};

struct L1<L:ILight> : ILight
{
    L l;
    float illum<B:IBRDF>(B b)
    { 
       // the following line contains type eval error
        return l.illum<B>(b); 
    }
};
```
In the marked line, `b` has type `DeclRefType(B, generic_subst=null)`, but the parameter type of `illum` is `DeclRefType(B, generic_subst=L)` which seems wrong. I am confused why there is such a divergence.

**Comment by csyonghe** [comment]
Seems like a bug I have introduced in my substitution refactor branch. This should be the last issue preventing the shader example to compile. Will resume debugging tomorrow.
