### ISSUE TITLE
Setting passthrough to DXC causes Access Violation Reading location.

### ISSUE THREAD

**Issue by Stanlyhalo** [shader-slang/slang#3625]
If I set the request's passthrough to use DXC (reason is due to FXC compiler error with ByteAddressBuffer Load function), I get an Access Violation Reading Location runtime error when calling `spGetEntryPointCodeBlob`.

Here's some code just for reference:
```cpp
SlangSession* session = spCreateSession(nullptr);
SlangCompileRequest* request = spCreateCompileRequest(session);

ISlangBlob* compiled = nullptr;

int targetIndex = spAddCodeGenTarget(request, SLANG_DXBC);
//spSetCodeGenTarget(request, SLANG_DXBC);
spSetPassThrough(request, SLANG_PASS_THROUGH_DXC);
spAddSearchPath(request, "/"); // TODO: Add search paths & macro defines into config.
int translationUnitIndex = spAddTranslationUnit(request, SLANG_SOURCE_LANGUAGE_SLANG, "");
spAddTranslationUnitSourceString(request, translationUnitIndex, "", (char*)data);
SlangProfileID profileID = spFindProfile(session, "vs_5_1");
spSetTargetProfile(request, targetIndex, profileID);
int entryIndex = spAddEntryPoint(request, translationUnitIndex, _entry, SLANG_STAGE_VERTEX);

int anyErrors = spCompile(request);
char const* diagnostics = spGetDiagnosticOutput(request);
if (anyErrors) std::cout << diagnostics << std::endl; // TODO: Pass over to debugger callback.
spGetEntryPointCodeBlob(request, entryIndex, targetIndex, &compiled);

spDestroyCompileRequest(request);
spDestroySession(session);
```

Any known reason or work around? I could just use the `spGetEntryPointCode` function however I do want it as a blob (if someone has a temporary way to manually input the data into the blob, that would be much appreciated).

**Comment by csyonghe** [comment]
Pass through means the Slang will not process your file and will handle pass your source directly into the downstream compiler. This mode is deprecated and we no longer support them. If you want Slang to use dxc for the downstream compiler, specify a profile that is sm_6_0 or higher, or use SLANG_DXIL target instead of DXBC.

**Comment by Stanlyhalo** [comment]
Thank you, I just switched it to DXIL with sm_6_0, however I now get an Access Violation Reading Location if I return the blob (that code is within a compile function) and try to call `getBufferSize`.

**Comment by Stanlyhalo** [comment]
Is the blob going out of scope or something? Because returning it and trying to call any functions will cause an error however calling the functions inside the same scope won't throw any runtime errors.

**Comment by Stanlyhalo** [comment]
Interesting, so for some reason I can access the buffer pointer & size from the blob inside the scope, but outside the scope, I get a read access violation error. But if I return just the pointer and size instead of the blob, I can use it (as reading it seems to output the same data as the scope inside), however if I try to use the data as the inputs for both vertex/fragment in my pipeline, I get the following errors:
![image](https://github.com/shader-slang/slang/assets/36088749/c780f76c-1f3c-449f-aedb-5f3f12fd92f3)

**Comment by Stanlyhalo** [comment]
Alright, figured it out, I needed the dxil.dll inside my working directory for slang to compile it correctly. Here's the link to the official download: https://github.com/microsoft/DirectXShaderCompiler/releases.

Closing the post now.
