### ISSUE TITLE
Make debugging easier by shipping releases relwithdeb and pdbs

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#3661]
I am finding my self in a lot of situations where slang crashes/ dereferences a nullptr instead of giving me error messages for faulty code.
Building slang is quite painful as its premake.
Shipping slang with pdbs and a relwithdeb info in releases would make error reporting and making repros much easier.

**Comment by csyonghe** [comment]
pdbs are really big so that's why we don't include them in the release packages.
If you need pdb, we do recommend building it locally. If you find building difficult, let us know how we can improve it.

**Comment by Ipotrick** [comment]
Understandable. I will build from source to try and debug.
