### ISSUE TITLE
Add documentation for pointers to user guide

### ISSUE THREAD

**Issue by natduca** [shader-slang/slang#3666]
We're hearing from a lot of people about whether we support pointers. We do in vk, but its not in the user guide ... maybe time to add it, with the appropriate asterisks for which backends it works in?

EG
https://github.com/nvpro-samples/vk_mini_samples/blob/03746e7a1d85d08b54642d28d3b0504632b017a9/samples/ray_query/shaders/ray_query.slang#L38

**Comment by csyonghe** [comment]
Done.
