### ISSUE TITLE
Compile hlsl exported from unreal to CUDA or Pytorch CPU code 

### ISSUE THREAD

**Issue by FishWoWater** [shader-slang/slang#3700]
Hi, I am doing a survey on differentiable rendering. I have gone through your introductory docs but still can't get the points well, as a beginner in this field.

I am wondering one thing: whether it's possible to compile HLSL code exported from the Unreal engine (e.g. the shader graph) to CUDA or Pytorch CPU code, which is differentiable and can be executed on my Linux server?

Thank you very much for your efforts!

**Comment by swoods-nv** [comment]
Slang currently supports compiling HLSL compute shaders to CUDA or CPU code, but only a limited subset of intrinsics are supported, so we don't expect that all shaders from Unreal can be compiled through this pipeline.
