### ISSUE TITLE
Add documentation to note that compiler internal constructs should not be expected to get full error checking

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3740]
Hi,

I am trying to write some bindings for the C++ backend and found that adding the `[mutating]` decorator to a function unexpectedly generates a call on a pointer to the object:

```c++
__target_intrinsic(cpp)
struct Foo
{
    [mutating]
    __target_intrinsic(cpp)
    void bar() {
        __requirePrelude(R"(#include <this is not being ignored>)");
        __intrinsic_asm "$0->bar()"; // using __target_intrinsic renders this being ignored without error/warning!
    }
};

[shader("compute")]
[numthreads(4, 1, 1)]
void computeMain()
{
    Foo f;
    f.bar();
}
```
generates this using slang 2024.1.0:
```c++
#include <this is not being ignored>

void _computeMain(void* _S1, void* entryPointParams_0, void* _S2)
{
    Foo f_0;
    (&f_0).bar(); // <- error
    return;
}
```
The code then fails to compile.

I expected that the mutating annotation is mere a hint for the compiler to potentially optimize accesses to the members of `Foo`, I did not expect it to change code generation.

So I think I am facing two problems here:
* The usage of `[mutating]` inside a struct in combination with `__target_intrinsic(cpp)` generates wrong C++ code.
* Using `__intrinsic_asm` inside a `__target_intrinsic(cpp)` function is ignored. If this is intended behavior, I'd wish there was a warning or an error hinting at the problem.

The workaround is to leave `__target_intrinsic(cpp)` out and to write the call myself using `__intrinsic_asm`.

Thanks for having a look!

**Comment by csyonghe** [comment]
We are deprecating `__target_intrinsic` for functions and we recommend all future interop code to be written in the form of `__target_switch` and `__intrinsic_asm`. As you noticed, `__require_prelude` and `__intrinsic_asm` does not work when `__target_intrinsic` is present.

**Comment by swoods-nv** [comment]
Tentatively assigned labels-- Yong, please advise if this is a "we should add a warning" or something else.

**Comment by csyonghe** [comment]
`__target_intrinsic` is still considered as compiler internal construct and we probably won't plan to add too much comprehensive checking logic around it. We may want to expose something different to the user that will undergo more checking. My suggestion is to close this issue because we don't want to invest too much checking in internal constructs for performance and implementation simplicity considerations.

**Comment by swoods-nv** [comment]
That sounds reasonable -- do we need to add any documentation?

**Comment by swoods-nv** [comment]
Thanks! Updated title, lowered priority, moved to backlog.

**Comment by pborsutzki** [comment]
> We are deprecating `__target_intrinsic` for functions

Is there a list of deprecated things? I thought as it was part of the [User Guide](https://shader-slang.com/slang/user-guide/a1-04-interop.html#defining-intrinsic-types) I was supposed to use it.

> we recommend all future interop code to be written in the form of `__target_switch` and `__intrinsic_asm`

I can also use this.

Generally, what is the suggested way to extend on already existing types that are already in place for spir-v or hlsl but not for C++? I tried to write C++ bindings for the `RayQuery` struct. Currently it works by redefining the type in case I am compiling for C++, as inheriting from the already existing `RayQuery` struct is forbidden (sealed type). But I have the feeling that this is not the right way to go as this approach relies on preprocessor logic instead of actual language features. Can you give me some guidance on this? Is there documentation or examples somewhere that I missed?
