### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3742]
Hi,

I just stumbled upon a compiler crash when compiling this using slang 2024.1.0 by calling `slangc.exe -entry computeMain -stage compute -target cpp`:
```c++
struct Foo {
    __target_intrinsic(cpp)
    void bar();
};

[shader("compute")]
[numthreads(4, 1, 1)]
void computeMain()
{
    Foo f;
    f.bar();
}
```
I guess the code does not really make sense as `Foo` is not marked as a C++ specific type, so I think this code should produce some kind of error, still it should not crash.

Thanks for having a look!

**Comment by csyonghe** [comment]
This is in the same category as #3740, and we are not able to do much with internal constructs for now other than adding cautionary comments to the documentation.
