### ISSUE TITLE
Report errors for unsupported calls in target backend

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3744]
Hi,

when experimenting with slang and ray queries I noticed that the code containing ray queries "simply compiles" also for the C++ backend. But the generated C++ code is simply missing the ray query function calls. I am not expecting you to plug a ray intersection library into the compiler or the generated code, but I'd at least expect an error to be reported in this case, instead of a "silent omission" of the relevant calls.

This behavior makes me question the generated C++ code by slang in general, as I have no indication of what else it might omit when generating code. So I think a fix should not only report errors when using ray queries, but in general, when using other unsupported features.

Thanks for taking this suggestion into consideration!

---

Using slang 2024.1.0 by calling `slangc.exe -entry computeMain -stage compute -target cpp` on this code:
```c++
RWStructuredBuffer<float> io;
RaytracingAccelerationStructure bvh;

[shader("compute")]
[numthreads(1, 1, 1)]
void computeMain()
{
    RayDesc ray;
    ray.Origin = float3(0);
    ray.TMin = 0;
    ray.Direction = float3(1);
    ray.TMax = 1;
    RayQuery q;

    q.TraceRayInline(bvh, RAY_FLAG_NONE, 0xff, ray);
    q.Proceed();
    if (q.CommittedStatus() == COMMITTED_TRIANGLE_HIT) {
        io[0] = q.CommittedRayT();
    }
}
```
Generates this C++ code:
```c++
struct RayDesc_0
{
    Vector<float, 3>  Origin_0;
    float TMin_0;
    Vector<float, 3>  Direction_0;
    float TMax_0;
};

void _computeMain(void* _S1, void* entryPointParams_0, void* _S2)
{
    RayDesc_0 ray_0;
    (&ray_0)->Origin_0 = (Vector<float, 3> )0.0f;
    (&ray_0)->TMin_0 = 0.0f;
    (&ray_0)->Direction_0 = (Vector<float, 3> )1.0f;
    (&ray_0)->TMax_0 = 1.0f;
}
```

**Comment by csyonghe** [comment]
The work for this feature is in progress. See this PR: https://github.com/shader-slang/slang/issues/3455

When this PR lands, we will be able to report errors for this case. Closing this issue as duplicate.
