### ISSUE TITLE
Scope out - Improve documentation around intrinsics

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang#3766]

**Comment by bmillsNV** [comment]
We need someone to scope this out and come up with a plan. Will be multiple tasks.

**Comment by jkwak-work** [comment]
It is little unclear to me how to define `intrinsics`.
@csyonghe , would it be enough to say Slang intrinsics for the documentation purpose here is any keywords or functions that are not implemented in the frontend but implemented in the backend or C++ side?

**Comment by csyonghe** [comment]
Intrinsics means stdlib. Every type and function that the user can use that is provided by the builtin std lib, i.e. core/hlsl/diff.meta.slang.

**Comment by jkwak-work** [comment]
Oh! I see.
The goal of this task will be grouping the functions in stdlib into a few categories so that we can create multiple of subtasks.

**Comment by jkwak-work** [comment]
I didn't have a chance to work on this for this sprint.
I am moving to the next sprint.

**Comment by jkwak-work** [comment]
I think it is worth noting that different shading languages use different ways to categorize and organize the list of intrinsic functions.

HLSL lists all functions without grouping.
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-intrinsic-functions

GLSL uses 19 categories for "Built-in functions" in the section 8.
https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf

Metal uses 19 categories for the standard library in the section 16.
https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf

As an update for my progress, I came up with a few categories as following so far.
1. Common Functions
clamp lerp saturate sign smoothstep step

1. Relational Functions
all any equal greaterThan isfinite isinf isnan lessThan notEqual

1. Bitwise Functions
countbits firstbithigh firstbitlow not or shl shr xor

1. Math Functions
rcp reversebits abs acos acosh asin atan2 atan atanh ceil cos cosh degrees determinant exp10 exp2 exp floor fma fmax fmin fmod frac frexp ldexp log10 log2 log mad max min modf mul pow radians round rsqrt sin sincos sinh sqrt tan tanh transpose trunc

1. Geometric Functions
cross distance dot faceforward length lit normalize reflect refract

1. Vertex Shader Functions
clip

1. Pixel (Fragment) Shader Functions
ddx ddy discard fwidth

1. Hull (Tessellation Control) Shader Functions
HSControlPointPhase HSForkPhase HSJoinPhase OutputControlPoints

1. Domain (Tessellation Evaluation) Shader Functions
EvalTessellationCoord PatchConstantFunc

1. Geometry Shader Functions
EmitVertex EndPrimitive StreamOutput

1. Compute Shader Functions
Barrier Dispatch GroupShared atomicAdd atomicSub

1. Mesh Shader Functions (DirectX 12)
DispatchMesh EmitMeshTasks SetMeshOutputCounts SetMeshOutputTopology

1. Amplification Shader Functions (DirectX 12)
DispatchMeshTasks EmitTask

1. Texture Functions
gather sample sampleBias sampleGrad sampleLevel tex2D tex3D textureGrad textureLod

1. Image Functions
imageAtomicAdd imageAtomicAnd imageAtomicMax imageAtomicMin imageAtomicOr imageAtomicSub imageAtomicXor load store

1. Conversion Functions
asdouble asfloat asint asuint f16tof32 f32tof16

1. Pack and Unpack Functions
packHalf2x16 packSnorm2x16 packUnorm2x16 unpackHalf2x16 unpackSnorm2x16 unpackUnorm2x16

1. Atomic Functions
InterlockedAdd InterlockedAnd InterlockedCompareExchange InterlockedMax InterlockedMin InterlockedOr InterlockedSub InterlockedXor

1. Synchronization Functions
AllMemoryBarrier AllMemoryBarrierWithGroupSync DeviceMemoryBarrier DeviceMemoryBarrierWithGroupSync GroupMemoryBarrier GroupMemoryBarrierWithGroupSync

1. Ray-Tracing Functions
AcceptHitAndEndSearch IgnoreHit ReportHit TraceRay

Currently the functions listed above are based on HLSL functions.

Initially I thought the stage-specific functions could be useful but there aren't many functions for those categories so I may put them into "common" or "misc".

I noticed that there are many functions in "Math function" section and GLSL broke it down to "trigonometry", "exponential" and so on. I think I should do that too.

**Comment by bmillsNV** [comment]
Will be able to close this once Yong's change #5232
