### ISSUE TITLE
matrix-matrix multiplication is broken in auto-diff

### ISSUE THREAD

**Issue by aroidzap** [shader-slang/slang#3772]
Issue encountered and tested in slang **v2024.1.1** and **v2023.5.1**.

When using built-in `mul(a, b)` for matrix-matrix multiplication, auto-diff give wrong results. Matrix-vector multiplication seems ok.

Workaround is a simple matrix-matrix multiplication implementation:
```hlsl
[Differentiable]
[PreferRecompute]
float2x2 mul_(float2x2 a, float2x2 b) {
    return float2x2(
        a[0][0] * b[0][0] + a[0][1] * b[1][0], a[0][0] * b[0][1] + a[0][1] * b[1][1],
        a[1][0] * b[0][0] + a[1][1] * b[1][0], a[1][0] * b[0][1] + a[1][1] * b[1][1]
    );
}

[Differentiable]
[PreferRecompute]
float3x3 mul_(float3x3 a, float3x3 b) {
    return float3x3(
        a[0][0] * b[0][0] + a[0][1] * b[1][0] + a[0][2] * b[2][0], a[0][0] * b[0][1] + a[0][1] * b[1][1] + a[0][2] * b[2][1], a[0][0] * b[0][2] + a[0][1] * b[1][2] + a[0][2] * b[2][2],
        a[1][0] * b[0][0] + a[1][1] * b[1][0] + a[1][2] * b[2][0], a[1][0] * b[0][1] + a[1][1] * b[1][1] + a[1][2] * b[2][1], a[1][0] * b[0][2] + a[1][1] * b[1][2] + a[1][2] * b[2][2],
        a[2][0] * b[0][0] + a[2][1] * b[1][0] + a[2][2] * b[2][0], a[2][0] * b[0][1] + a[2][1] * b[1][1] + a[2][2] * b[2][1], a[2][0] * b[0][2] + a[2][1] * b[1][2] + a[2][2] * b[2][2]
    );
}
```

Hint: In a language server (VSCode extension) there are swapped left/right matrices:
![image](https://github.com/shader-slang/slang/assets/4784332/7d030591-990c-4e13-9c8e-a1b4e5587307)
![image](https://github.com/shader-slang/slang/assets/4784332/1fcdd867-bccc-45bb-ac04-d2dab79afac3)

**Comment by aroidzap** [comment]
Actually to fix derivatives and keep the current behavior, the workaround implementation needs swapped left/right matrices as well.

```hlsl
[Differentiable]
[PreferRecompute]
float2x2 mul_(float2x2 right, float2x2 left) {
    return float2x2(
        left[0][0] * right[0][0] + left[0][1] * right[1][0], left[0][0] * right[0][1] + left[0][1] * right[1][1],
        left[1][0] * right[0][0] + left[1][1] * right[1][0], left[1][0] * right[0][1] + left[1][1] * right[1][1]
    );
}

[Differentiable]
[PreferRecompute]
float3x3 mul_(float3x3 right, float3x3 left) {
    return float3x3(
        left[0][0] * right[0][0] + left[0][1] * right[1][0] + left[0][2] * right[2][0], left[0][0] * right[0][1] + left[0][1] * right[1][1] + left[0][2] * right[2][1], left[0][0] * right[0][2] + left[0][1] * right[1][2] + left[0][2] * right[2][2],
        left[1][0] * right[0][0] + left[1][1] * right[1][0] + left[1][2] * right[2][0], left[1][0] * right[0][1] + left[1][1] * right[1][1] + left[1][2] * right[2][1], left[1][0] * right[0][2] + left[1][1] * right[1][2] + left[1][2] * right[2][2],
        left[2][0] * right[0][0] + left[2][1] * right[1][0] + left[2][2] * right[2][0], left[2][0] * right[0][1] + left[2][1] * right[1][1] + left[2][2] * right[2][1], left[2][0] * right[0][2] + left[2][1] * right[1][2] + left[2][2] * right[2][2]
    );
}
```

**Comment by saipraveenb25** [comment]
This looks like a case of legacy code using flipped operands to follow GLSL convention. 
The labels are incorrect now. 
On my end, pretending that `right` is `left` and `left` is `right` seems to provide the correct behavior for both multiplication and its derivative.

Will issue a fix to swap the labels

**Comment by aroidzap** [comment]
Maybe it could be problem with overrides, when matrices are square?

This code fixes the derivatives for me (while keeping current Slang matrix-matrix multiplication behavior):
```hlsl
__generic<T : __BuiltinFloatingPointType, let N : int>
[ForceInline]
[PreferRecompute]
[Differentiable]
[ForwardDerivative(mul_fdiff_)]
[BackwardDerivative(mul_bdiff_)]
matrix<T, N, N> mul_(matrix<T, N, N> right, matrix<T, N, N> left) {
    return mul(right, left);
}

__generic<T : __BuiltinFloatingPointType, let N : int>
[ForceInline]
DifferentialPair<matrix<T, N, N>> mul_fdiff_(DifferentialPair<matrix<T, N, N>> right, DifferentialPair<matrix<T, N, N>> left)
{
    return mul(left, right);
}

__generic<T : __BuiltinFloatingPointType, let N : int>
[ForceInline]
void mul_bdiff_(inout DifferentialPair<matrix<T, N, N>> right, inout DifferentialPair<matrix<T, N, N>> left, matrix<T, N, N>.Differential dOut)
{
    return mul(left, right, dOut);
}
```

Changing the behavior of `mul` would be more intuitive, but would probably break other Slang users code.

**Comment by aroidzap** [comment]
Just a note, I'm using CUDA target.

**Comment by aroidzap** [comment]
Please reopen this issue, #3777 is not solving this.

**Comment by csyonghe** [comment]
Can you clarify what you refer to as "slang matrix behavior"?

The `mul(A, B)` is always take a RxN matrix A and multiply it with NxC matrix B to produce `A*B`. There is no swapping or transposition.

**Comment by csyonghe** [comment]
In order for us to understand what the issue is, we will need a self-contained code that produces the wrong result, as well as the expected correct result. There are many existing users who are using these intrinsic functions, so I am not sure what we are doing wrong here.

**Comment by csyonghe** [comment]
Also: there is only one `mul()` overload for matrix-matrix multiplication that handles both square and non-square case. On CUDA, matrices are always row major.

**Comment by aroidzap** [comment]
I tried to create minimal reproducible example, but unfortunately I was not able to replicate the issue from my former code.
