### ISSUE TITLE
Investigate why UE TSR runs slow with Slang

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3794]
When UE TSR is compiled with Slang, the FPS was about 30% lower; 0.54ms vs 0.69ms
We need to investigate why it is the case.

**Comment by csyonghe** [comment]
This is a good opportunity for us to improve our performance story. Possible causes:
1. A single mis-translated intrinsic can lead to significant slow down like this.
2. Compare all the buffer accesses and make sure we are not producing less efficient buffer access.
3. We should check the shader register usage and make sure we are not producing shaders that uses more reigsters. Can try to disable some of our optimization passes, especially `removeRedundancy` to see if it changes anything.

**Comment by jkwak-work** [comment]
The issue turned out to be on one specific compiler permutation setting.
When TSRRejectShading.usf is compiled for WaveSize=32, the compile-time and the runtime becomes much longer.

I am going to close this issue and open a new issue for the specific compile permutation setting.
