### ISSUE TITLE
generic interface cannot be used as a generic argument

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3804]
When an interface uses "__generic", the interface cannot be used as a part of the __generic argument.

It is easier to explain the problem with an example.
The following code gives us a compile error,
```
__generic<T:__BuiltinFloatingPointType> // <== This is the problem
interface IOperation
{
  static bool Equals(T lhs, T rhs);
};
 
__generic<T:__BuiltinFloatingPointType, OpType:IOperation<T>> // <= Not sure if this is a right way
bool Equals(T lhs, T rhs)
{
  return OpType::Equals(lhs, rhs);
}
```
The error message is following,
```
a.slang(8): note 99999: an internal error threw an exception while working on code near this location
bool Equals(T lhs, T rhs)
    ^~~~~~
(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: Generic type/value shouldn't be handled here!
```

The following alternative approach didn't work either,
```
__generic<T:__BuiltinFloatingPointType>
interface IOperation
{
   bool Equals(T lhs, T rhs);
};

__generic<T:__BuiltinFloatingPointType>
struct JKWAK_test
{
    __generic<OpType:IOperation<T>>
    bool Equals(OpType op, T lhs, T rhs)
    {
       return op.Equals(lhs, rhs);
    }
}
```
The error message is identical to the first example.

**Comment by csyonghe** [comment]
This is due to some fundamental limitation we have in our IR. Supporting this is likely something we cannot afford in the short term. Let's try:
```
__generic<T:__BuiltinFloatingPointType>
struct JKWAK_test
{
    bool Equals(IOperation<T>op, T lhs, T rhs)
    {
       return op.Equals(lhs, rhs);
    }
}
```
If this doesn't work, we may be able to fix it.

**Comment by jkwak-work** [comment]
Oh. I got it wrong.
The suggested workaround seems to be working.
Let me try it on UE.

**Comment by jkwak-work** [comment]
This issue was closed as WNF due to the low bang for the buck.
But we should track it as an unfinished feature like https://github.com/shader-slang/slang/issues/4236
