### ISSUE TITLE
SLANG_COMPILE_FLAG_NO_MANGLING doesn't work as expected

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3813]
When SLANG_COMPILE_FLAG_NO_MANGLING is used, the variable names are expected to have no mangling.
But they appear to be mangled.

**Comment by csyonghe** [comment]
For now, when the option is set, let's leave local variables mangled and only keep the original name for:
1) global variables
2) struct fields
3) synthesized cbuffer struct types.
