### ISSUE TITLE
Spirv out mesh shader per primitive varrings are broken

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#3826]
With this Config:
```
pc platform: x86-64msvc windows11
slang::TargetDesc::format: SlangCompileTarget::SLANG_SPIRV
slang::TargetDesc::profile: glsl_460+spirv_1_4
slang::TargetDesc::flags: SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY
slang::SessionDesc::defaultMatrixLayoutMode: SLANG_MATRIX_LAYOUT_COLUMN_MAJOR
```
and this repro:
```hlsl
const static uint MAX_VERTS = 6;
const static uint MAX_PRIMS = 2;

const static float2 positions[MAX_VERTS] = {
  float2(0.0, -0.5),
  float2(0.5, 0),
  float2(-0.5, 0),
  float2(0.0, 0.5),
  float2(0.5, 0),
  float2(-0.5, 0),
};

struct Vertex
{
  float4 pos : SV_Position;
};

struct Primitive
{
  [[vk::location(0)]] float3 color;
}

[outputtopology("triangle")]
[numthreads(MAX_VERTS, 1, 1)]
[shader("mesh")]
void entry_mesh(
    in uint tig : SV_GroupThreadID,
    OutputVertices<Vertex, MAX_VERTS> verts,
    OutputIndices<uint3, MAX_PRIMS> triangles,
    OutputPrimitives<Primitive, MAX_PRIMS> primitives)
{
    const uint numVertices = MAX_VERTS;
    const uint numPrimitives = MAX_PRIMS;
    SetMeshOutputCounts(numVertices, numPrimitives);

    if(tig < numVertices) {
        verts[tig] = {float4(positions[tig], 0, 1)};
    }

    if(tig < numPrimitives) {
        triangles[tig] = uint3(0,1,2) + tig * 3;
        primitives[tig] = { float3(1,0,0) };
    }
}

struct FragmentOut
{
    [[vk::location(0)]] float3 color;
};

[shader("fragment")]
FragmentOut entry_fragment(in Primitive prim)
{
    FragmentOut frag_out;
    frag_out.color = prim.color;
    return frag_out;
}
```

I expect to see a rectangle made up of two red triangles on screen.

Instead this is what i see with `SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY` enabled:
Two triangles, one is red with a fade to black in one vertex, the other triangle is completely black.
Investigating in renderdoc shows, that the per primitive data seems to be passed at a per vertex rate. The first two vertices have the color value, all others have 0s.
![image](https://github.com/shader-slang/slang/assets/36523140/6bee7942-4452-423e-b4e7-53f05f220ccb)

With `SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY` disabled, i see two red triangles, both are red towards the first vertex, black towards the other vertices. This would indicate that its still passed per vertex but with a stride of a triangle (3).
![image](https://github.com/shader-slang/slang/assets/36523140/55ea8e75-6c90-4d7f-8234-e981e112ab6b)

I believe per primitive should pass one value per primitive to all vertices, so both results are wrong.

**Comment by csyonghe** [comment]
I think the result from non direct spirv backend may be correct. The fragment shader input need to be marked as `noninterpolate` to disable per-vertex interpolation.

**Comment by Ipotrick** [comment]
Thank you!
