### ISSUE TITLE
Initializing interface type with empty initializer results in invalid HLSL code

### ISSUE THREAD

**Issue by tomas-davidovic** [shader-slang/slang#3831]
When you have a interface type `IHitInfo` and try to empty initialize it directly as `IHitInfo hit = {};` or indirectly by storing it in `struct PathState` and then empty initialize that `PathState path = {}`, Slang generates an invalid HLSL code dxc errors out.

Ideally Slang compiler would report an error, to make it easier to address.

**Comment by swoods-nv** [comment]
There's a workaround currently, so it's not currently blocking, but should be tightened up for quality purposes.

**Comment by csyonghe** [comment]
Working on this now.
