### ISSUE TITLE
Support warnings on uninitialized variables.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3832]

**Comment by sriramm-nv** [comment]
might be a breaking change for OV.

**Comment by sriramm-nv** [comment]
AI Sriram: split this up into pieces that can be addressed in sprint 5.

**Comment by venkataram-nv** [comment]
At this point, the bulk of this feature has been implemented. Remaining parts are more specialized, and are likely better off being smaller, specialized issues.
