### ISSUE TITLE
"const" variable loses const-ness inside of a generic function

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3834]
I found that "const"-ness is removed inside of a generic function.
See the following example,
```
//#define USE_GENERIC 1

uniform sampler2D uniform_sampler2D;
RWStructuredBuffer<float> outputBuffer;

#if USE_GENERIC
__generic<T:__BuiltinArithmeticType>
#endif
vec4 MyFunc()
{
    const ivec2[4] offsets = { ivec2(0,0), ivec2(0,0), ivec2(1,1), ivec2(1,1) };
    return textureGatherOffsets(uniform_sampler2D, vec2(0), offsets);
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
#if USE_GENERIC
    vec4 result = MyFunc<float>();
#else
    vec4 result = MyFunc();
#endif

    outputBuffer[0] = result[0];
}
```
When the file is saved as "const_with_generic.slang", you can generate two GLSL source files with following commands:
```
slangc.exe -target glsl -lang glsl -entry computeMain -allow-glsl -stage compute -DUSE_GENERIC=0 -o const_without_generic.glsl const_with_generic.slang
slangc.exe -target glsl -lang glsl -entry computeMain -allow-glsl -stage compute -DUSE_GENERIC=1 -o const_with_generic.glsl const_with_generic.slang
```
When "USE_GENERIC=0", the "const" is preserved; see the following result code:
```
vec4 MyFunc_0()
{
    const ivec2 _S1 = ivec2(0, 0);

#line 11
    const ivec2 _S2 = ivec2(1, 1);
    const vec2 _S3 = vec2(0.0);

#line 12
    vec4 _S4 = (textureGatherOffsets((uniform_sampler2D_0), (_S3), ivec2[]((_S1), (_S1), (_S2), (_S2)), (0)));
```
But when "USE_GENERIC=1", the "const" modifier is lost; see the following result code:
```
vec4 MyFunc_0()
{
    ivec2 _S1 = ivec2(0, 0);

#line 11
    ivec2 _S2 = ivec2(1, 1);
    vec2 _S3 = vec2(0.0);

#line 12
    vec4 _S4 = (textureGatherOffsets((uniform_sampler2D_0), (_S3), ivec2[]((_S1), (_S1), (_S2), (_S2)), (0)));
```
Because of the difference, when textureGatherOffsets() is called from a generic function, it always results in a compile error.
It is because the offset value to "textureGatherOffsets()" is required to be a compile-time constant.
```
$ slangc.exe -target spirv -lang glsl -entry computeMain -allow-glsl -stage compute -o const_without_generic.spirv -DUSE_GENERIC=1 const_with_generic.slang
glslang:  const_with_generic.slang(12): error :  'textureGatherOffsets(...)' : must be a compile-time constant: offsets argument
glslang:  const_with_generic.slang(12): error :  '' : compilation terminated
glslang: note : ERROR: 2 compilation errors.  No code generated.
```

**Comment by swoods-nv** [comment]
Moving this to next sprint-- it's important, but less critical than work you already have assigned for this sprint.

**Comment by jkwak-work** [comment]
I like to share an update.

The cause of the issue is that `propagateConstExpr()` is not applied to the generic function.
The function iterates global IR instances except generic functions.

For the given repro example, when `USE_GENERIC` is not defined, the following code adds 42 functions to `workList`.
When `USE_GENERIC` is defined, it adds 41 functions.
The missing one is "MyFunc", which is the generic function in question.
```
void propagateConstExpr(IRModule* module, DiagnosticSink* sink)
{
...omit...
    for( auto ii : module->getGlobalInsts() )
    {
        maybeAddToWorkList(&context, ii);
    }
```

I need to figure out how to include the generic functions to the workList so that it gets processed by `propagateConstExpr()`.
