### ISSUE TITLE
variable created inside scope, then used outside of it

### ISSUE THREAD

**Issue by GDBobby** [shader-slang/slang#3838]
!flag is set to a variable inside the loop, which is fine, but then it uses that variable outside of the scope it was created in, which causes an error
`
glslang:  OceanFFT.slang(70): error :  '_S14' : undeclared identifier
`
`
glslang:  OceanFFT.slang(70): error :  '' : compilation terminated 
`
Line 150 and 183 in the generated glsl file
Error happens when compiling to spirv directly from slangc, in both optimization level 0 and 3
[OceanFFT_slang.txt](https://github.com/shader-slang/slang/files/14752995/OceanFFT_slang.txt)

[OceanFFT_slang_glsl.txt](https://github.com/shader-slang/slang/files/14752996/OceanFFT_slang_glsl.txt)

**Comment by csyonghe** [comment]
Does it work if you compile with
-emit-spirv-directly?

**Comment by GDBobby** [comment]
yes, it compiles, thank you
