### ISSUE TITLE
Generated SPIRV code fails validation with -O3

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3844]
Hi,

the generated SPIRV code for this slang shader fails vulkan validation:
```c++
struct Foo
{
    uint64_t address;

    int load() {
        return *((int *)(address));
    }
};

struct Bar {
    Foo foo;
    float3x4 baz; // removing this changes the error message
};

uniform StructuredBuffer<Bar> bar;
uniform RWStructuredBuffer<int> out;

[shader("compute")]
[numthreads(1, 1, 1)]
void computeMain()
{
    out[0] = bar[0].foo.load();
}
```
with this error message:
```
error: line 124: Expected Constituent type to be equal to the corresponding member type of Result Type struct
  %72 = OpCompositeConstruct %Bar %48 %71
```
when compiling it using slangc 2024.1.5 with the command line `slangc -entry computeMain -stage compute -target spirv -emit-spirv-directly -O3`. Validation was done using `spirv-val` from the Vulkan SDK 1.3.280.

_Using `-O1` instead of `-O3` generates code that passes validation. `-O2` still fails validation._

As I am not proficient with SPIRV assembly, I can't really tell if the assembly code is correct or not, so I also can't tell who is to blame here - slangc or the validation.

So can you have a look into the issue? Thanks!

---
Not sure if it is relevant, but the error message differs when removing `baz` from the struct:
```
Result type (OpTypeStruct) does not match the type that results from indexing into the composite (OpTypeStruct).
  %39 = OpCompositeExtract %Foo %36 0
```

**Comment by csyonghe** [comment]
If -O0 passes validation but -O3 fails, then this is a spirv-opt bug and should be filed in the official spirv-tools repo. Please attach the spirv generated with -O0 in that bug, and include the command line to run spirv-opt that can reproduce the crash in spirv-opt.
