### ISSUE TITLE
Allow typedef from global scope

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3845]
Hi,

I am trying to typedef a type from a global namespace into a non-global namespace by writing:
```c++
struct Foo {};

namespace foo {
    typedef ::Foo Foo; // unexpected '::', expected identifier; works in dxc/hlsl
    //typedef Foo Foo; // cyclic reference 'Foo'; allowed in dxc/hlsl
}
```
Unfortunately it gives me this error in slang 2024.1.5:
```
shader.slang(4): error 20001: unexpected '::', expected identifier
    typedef ::Foo Foo;
            ^~

```
Is it possible to support the global scope syntax `::` for namespaces? Thanks!

**Comment by csyonghe** [comment]
This may just be a syntax problem. Can you try: typealias Foo=::Foo; ?

**Comment by pborsutzki** [comment]
Using `typealias Foo=::Foo;` still gives me this error:
```
shader.slang(6): error 20001: unexpected '::', expected identifier
    typealias Foo=::Foo;
                  ^~
```

**Comment by csyonghe** [comment]
The PR should allow both `typedef ::Foo Foo` and `typedef Foo Foo;` now.
