### ISSUE TITLE
Allow __requirePrelude for a type or globally for files.

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3846]
Hi,

currently the `__requirePrelude` seems to only be supported in functions. This breaks for type definitions when generating C++ code. This slang code:
```c++
// 2024.1.5: slangc.exe -entry computeMain -stage compute -target cpp

__target_intrinsic(cpp, "Foo")
//__requirePrelude("#include <Foo.hpp>"); // not allowed
//__requirePrelude(cpp, "#include <Foo.hpp>"); // also not allowed
struct Foo {
    __init() {
        __requirePrelude("#include <Foo.hpp>"); // only works when actually initializing Foo
        __intrinsic_asm ";";
    }
};

struct Bar {
    int bar;
    Foo foo;
};

uniform StructuredBuffer<Bar> bar;
uniform RWStructuredBuffer<int> out;

void workaround() {
    __requirePrelude("#include <Foo.hpp>");
    __intrinsic_asm "";
}

[shader("compute")]
[numthreads(1, 1, 1)]
void computeMain() {
    //workaround(); //<- fix
    out[0] = bar[0].bar;
}
```
generates C++ code containing this struct:
```c++
struct Bar_0
{
    int32_t bar_0;
    Foo foo_0; // <- unknown type
};
```
but is missing the definition for `Foo` which would come from `Foo.hpp`. The only workaround I can currently see is to call dummy functions from every slang entry point to make sure my includes are generated (see `workaround()` function). I think supporting the `__requirePrelude` for type definitions or globally in slang files would fix the issue more elegantly.

Thanks for taking this into consideration!

**Comment by csyonghe** [comment]
You can workaround this by having something like:

```
int addPrelude()
{
    __requirePrelude(...);
    return 0;
}

export int _addPrelude=addPrelude();

```

`export` makes the global variable marked as something that has to exist in the output code even if they are not used. This should cause the function call to be included in the code and prelude to be taken.

**Comment by csyonghe** [comment]
I think just
export void addPrelude() { __requirePrelude(…);}
May work.
________________________________

**Comment by pborsutzki** [comment]
Does not work for me either. Without adding `__intrinsic_asm "";` I am getting an `unimplemented feature in Slang compiler: unexpected IR opcode during code emit` error. When adding it, the prelude is still not present in the resulting cpp file:
```c++
export void addPrelude() {
    __requirePrelude(#include <Foo.hpp>);
    __intrinsic_asm "";
}
```

**Comment by csyonghe** [comment]
I played around and this seemed to work:
```
void addPrelude() {
    __requirePrelude("#include <Foo.hpp>");
    __intrinsic_asm "";
}
export void aaa() { addPrelude(); }
```

**Comment by csyonghe** [comment]
The idea is get the compiler to emit a call to a function (`addPrelude`) that has the `__requirePrelude`.

**Comment by csyonghe** [comment]
Closing since dedicated compiler support is not necessary.

**Comment by pborsutzki** [comment]
That seems to work, though it does not seem bring any additional benefit compared to the version using `__global`. _It will still generate a global symbol with the same name in each translation unit that conflicts when linking to multiple slang compiled cpp's_.

So I'd really like to have dedicated compiler support for this. Is that possible @csyonghe?

**Comment by csyonghe** [comment]
OK, I'll take a look.
