### ISSUE TITLE
Target agnostic data layout

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3854]
Hi,

the [layout](https://github.com/shader-slang/slang/blob/master/docs/layout.md) document states `Layout is always done with respect to a chosen target, and different targets might compute the resource usage for types differently, or apply different alignment.`.

_Is there a way to circumvent this to get the exact same layout when e.g. targeting C++ and Vulkan?_

I have been unsuccessfully looking for a while now for such an option in slang - which would be a big help when using the same host code to run on different targets: I could simply use the same includes to define types in both host and shader code without using cumbersome reflection APIs. Did I miss the option for this or do you expect slang users to always use specific data layouts that differ per target?

I understand that not all targets support all kinds of layouts and that some layouts may be inefficient on some targets. Still I think that at least the C++ target should be able to use any kind of layout (and I think the same should also apply to Vulkan).

Thanks for any hints!

**Comment by csyonghe** [comment]
Yes, you can use the `-force-glsl-scalar-layout` option to force all constant buffers and storage buffers to `scalar` layout, which is mostly aligned with the c++ layout.
