### ISSUE TITLE
Would it make sense to introduce syntax compatibility modes for different language frontends

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#3860]
If one would want to share code between slang and c++, rust, ...  a flag like `-cpp-syntax-compatibility-mode` could be added which would change some syntax:

In case of c++ this could change: 
`module X;` to `export module X;`
`implementing X;` to `module X;`

In case of rust this could change:
`float add(float lhs, float rhs)` to `fn add(lhs: float, rhs: float) -> float`

Types could be excluded as they can easily be converted via typealiases. This feature would be purely limited to syntax and would not add/change features. 

These examples should just provide an initial idea.

**Comment by csyonghe** [comment]
We already support the modern func syntax:

func a(p: float)->float 

So things like what you mentioned can be achieved with #define.

Note that supporting compatibility with other languages can have long term consequences. We do not want to provide official features like this to avoid confusing users with the illusion that we intend to stay consistent with any existing languages in future language design, and that has never been one of the goals of the project.

**Comment by fknfilewalker** [comment]
Interesting, totally overlooked that. Only tried it with fn...

I can understand that such a feature could easily get confused with potential proper language support. Defines seem fine, though one of the problems GLSL and HLSL had was that extensive usage of defines was basically a necessity. The context here though is a bit different. Depending on how Slang but also its underlying target feature set is evolving, multiple frontent/syntax flavors could make sense. Maybe it is not even necessary to hide/separate them at all and just add them to the current syntax like you already did. I can understand that other features have priority and this issue should just be food for thought anyway.

**Comment by csyonghe** [comment]
The higher level philosophy here is that Slang needs to be its own language. C++/Rust/Swift/C# does not add keywords or alternate syntax just to make themselves compatible with each other. Slang has historically been trying to be compatible with legacy HLSL to make adoption easy, but we have not promised or intend to stay compatible with newer HLSL versions, or with other languages like C++. This is especially true for new features that are not existent in HLSL, we want to stay as a truly independent language by defining one syntax that defines what Slang is. Supporting alternate syntax may seem to be a trivial engineering task, but it can have long term consequences that affect or restrict how we can revolve the language in the future, and it invites users to ask for more compatibility support, eventually leading to us losing our independence to evolve as a new language and doing everything exactly like the other languages.

**Comment by fknfilewalker** [comment]
I get the philosophy behind slang now and the decisions make sense, thanks for explaining
