### ISSUE TITLE
Device Lost when writing `SV_PrimitiveID` to `OutputPrimitives<T, N>`

### ISSUE THREAD

**Issue by LVSTRI** [shader-slang/slang#3872]
The following shader produces a DEVICE_LOST error 
```hlsl
const static let color: float3[] = {
  float3(1.0, 0.0, 0.0),
  float3(0.0, 1.0, 0.0),
  float3(0.0, 0.0, 1.0),
};

const static let position: float3[] = {
  float3( 0.5,  0.5, 0.0),
  float3( 0.0, -0.5, 0.0),
  float3(-0.5,  0.5, 0.0),
};

struct SVertexOutput {
  float4 Position: SV_Position;
  float3 Color;
};

struct SPrimitiveOutput {
  uint PrimitiveId: SV_PrimitiveID;
};

[shader("mesh")]
[numthreads(1, 1, 1)]
[outputtopology("triangle")]
func MainMesh(
  OutputVertices<SVertexOutput, 3> outputVertices,
  OutputPrimitives<SPrimitiveOutput, 1> outputPrimitives,
  OutputIndices<uint3, 1> outputIndices,
) -> void {
  SetMeshOutputCounts(3, 1);
  outputVertices[0] = { float4(position[0], 1.0), color[0] };
  outputVertices[1] = { float4(position[1], 1.0), color[1] };
  outputVertices[2] = { float4(position[2], 1.0), color[2] };
  outputIndices[0] = uint3(0, 1, 2);

  // This next line causes the DEVICE_LOST error
  outputPrimitives[0] = { 0 };
}

[shader("pixel")]
func MainPixel() -> void {}
```

I have attached a sample application for further testing, building steps:
```
cd extracted_folder
mkdir build
cd build
cmake ..
cmake --build .
```
Building requires a C++ compiler that supports at least C++14

If untouched, executing the application will produce `VK_ERROR_DEVICE_LOST`, this was tested on the following configurations:
- Windows 11
- NVIDIA RTX 3070 - 551.86, NVIDIA RTX 4070 Super - 551.86

[bug.zip](https://github.com/shader-slang/slang/files/14838685/bug.zip)

**Comment by csyonghe** [comment]
Is there a SPIRV validation error coming out from the spirv?

**Comment by csyonghe** [comment]
Even with --env=vulkan1.3?

**Comment by csyonghe** [comment]
If no validation errors, this is likely a driver bug, or missing validation checks in spirv-Val, or missing validation rules in the Vulkan spec.

**Comment by csyonghe** [comment]
This seems like something we should fix. `PerPrimitiveNV` is required by spec for `PrimitiveId` builtin. @pmistryNV

**Comment by pmistryNV** [comment]
> > Even with --env=vulkan1.3?
> 
> Yes
> 
> > If no validation errors, this is likely a driver bug, or missing validation checks in spirv-Val, or missing validation rules in the Vulkan spec.
> 
> After testing on an AMD Radeon RX 6750 XT - RADV NAVI 22 it does appear to be working, but an equivalent GLSL shader compiled to SPIR-V works fine on my GPU (RTX 3070 - 551.86), I'll investigate more.

Can you share the equivalent GLSL shader?

**Comment by csyonghe** [comment]
Everything passed via `OutputPrimitive<T>`  is automatically decorated with PerPrimitive currently. The fact that this builtin isn't decorated is a bug.

**Comment by csyonghe** [comment]
To summarize the TODOs here:
- Slang is missing PerPrimitive decoration, we should fix it.
- spirv-val is missing the validation check, and we need to add validation rules for that.
- The NVIDIA driver is probably not handling this correctly, so we may need to fix the driver.

**Comment by pmistryNV** [comment]
Below is the excerpt from the SPIRV i dumped
```
OpDecorate %gl_PrimitiveID BuiltIn PrimitiveId
%gl_PrimitiveID = OpVariable %_ptr_Output__arr_int_int_1 Output

```
It needs an additional decoration
`OpDecorate %gl_PrimitiveID PerPrimitiveNV`

 Corresponding SPIRV-Validation rule that is missing from the validator. I will fix that too.
VUID-PrimitiveId-PrimitiveId-07040
The variable decorated with PrimitiveId within the MeshEXT Execution Model must also be decorated with the PerPrimitiveEXT decoration

**Comment by pmistryNV** [comment]
[MeshShader.zip](https://github.com/shader-slang/slang/files/14859403/MeshShader.zip)

I am having difficulties running the test. @LVSTRI can you verifiy with the modified MeshShader.spv file and see if the issue is resolved?

**Comment by pmistryNV** [comment]
> Testing on an RTX 3070 (551.86) the issue seems solved, let me know if I can help with the test I provided

Thanks then let me make the fix in SLANG. Also added a comment on https://github.com/KhronosGroup/SPIRV-Tools/issues/4919 that i am working on to fix the validation of ext_mesh_shader.

**Comment by pmistryNV** [comment]
> I just wanted to add that the same bug (PerPrimitiveEXT decoration missing) happens for SV_CullPrimitive and every other builtin in `OutputPrimitives<T, N>`, I just found this out.

https://github.com/shader-slang/slang/pull/3895 this is the PR for fixing the bug.

**Comment by pmistryNV** [comment]
> > I just wanted to add that the same bug (PerPrimitiveEXT decoration missing) happens for SV_CullPrimitive and every other builtin in `OutputPrimitives<T, N>`, I just found this out.
> 
> #3895 this is the PR for fixing the bug.

Can you give it a try and let me know if this fixes the issues that you are seeing

**Comment by pmistryNV** [comment]
```
const static let color: float3[] = {
  float3(1.0, 0.0, 0.0),
  float3(0.0, 1.0, 0.0),
  float3(0.0, 0.0, 1.0),
};

const static let position: float3[] = {
  float3( 0.5,  0.5, 0.0),
  float3( 0.0, -0.5, 0.0),
  float3(-0.5,  0.5, 0.0),
};

struct SVertexOutput {
  float4 Position: SV_Position;
  float3 Color;
};

struct SPrimitiveOutput {
  uint PrimitiveId: SV_PrimitiveID;
  bool cull : SV_CullPrimitive;
};

[shader("mesh")]
[numthreads(1, 1, 1)]
[outputtopology("triangle")]
func MainMesh(
  OutputVertices<SVertexOutput, 3> outputVertices,
  OutputPrimitives<SPrimitiveOutput, 1> outputPrimitives,
  OutputIndices<uint3, 1> outputIndices,
) -> void {
  SetMeshOutputCounts(3, 1);
  outputVertices[0] = { float4(position[0], 1.0), color[0] };
  outputVertices[1] = { float4(position[1], 1.0), color[1] };
  outputVertices[2] = { float4(position[2], 1.0), color[2] };
  outputIndices[0] = uint3(0, 1, 2);

  // This next line causes the DEVICE_LOST error
  outputPrimitives[0] = { 0, false };
}

```

As pointed out by @LVSTRI something like below shader will still fail
