### ISSUE TITLE
Slang miscompiles NonUniformResourceIndex when targeting SPIR-V

### ISSUE THREAD

**Issue by nanokatze** [shader-slang/slang#3876]
```hlsl
[[vk::binding(0, 0)]] SamplerState samplers[];

[[vk::binding(1, 0)]] Texture2D sampledImages[];

struct Push {
	float2 *pos;
	uint sampler;
};

[[vk::push_constant]] Push push;

struct VSToFS {
	uint a;
};

struct VSOut {
	float4 pos : SV_Position;
	[[vk::location(0)]] VSToFS vsToFS;
};

[shader("vertex")]
VSOut vertMain(uint vertexID : SV_VertexID) {
	VSOut output = {};
	output.pos = float4(push.pos[vertexID], 0.0, 1.0);
	output.vsToFS.a = vertexID / 3;
	return output;
}

struct FSOut {
	float4 color0 : SV_Target0;
};

[shader("fragment")]
FSOut fragMain([[vk::location(0)]] VSToFS vsToFS) {
	FSOut output = {};
	output.color0 = sampledImages[NonUniformResourceIndex(vsToFS.a)].Sample(samplers[push.sampler], float2(0.0, 0.0));
	return output;
}
```

Compiling fragMain produces SPIR-V where `NonUniform` decoration is attached to the wrong value:
```llvm
         %18 = OpLoad %uint %vsToFS_a
         %21 = OpCopyObject %uint %18 // gets decorated with NonUniform, which is incorrect
         %29 = OpAccessChain %_ptr_PushConstant_uint %push %int_1
         %30 = OpLoad %uint %29
         %36 = OpAccessChain %_ptr_UniformConstant_32 %samplers %30
         %37 = OpLoad %32 %36
         %63 = OpAccessChain %_ptr_UniformConstant_47 %sampledImages %21
         %64 = OpLoad %47 %63
         %65 = OpSampledImage %53 %64 %37 // the thing that actually should be decorated with NonUniform
         %66 = OpImageSampleImplicitLod %v4float %65 %38 None
```
in the above, decorating `%21` `NonUniform` actually achieves nothing. Consulting Vulkan specification we can see that:
> VUID-RuntimeSpirv-NonUniform-06274
> If an instruction loads from or stores to a resource (including atomics and image instructions) and the resource descriptor being accessed is not dynamically uniform, then **the operand corresponding to that resource (e.g. the pointer or sampled image operand) must be decorated** with NonUniform

(emphasis mine)

**Comment by Honeybunch** [comment]
Hey sorry to dig up a closed issue but I've hit an assert in the compiler when trying to use `NonUniformResourceIndex` in a fragment shader

```
[build] (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unimplemented: Unhandled global inst in spirv-emit:
[build] let  %1	: _	= nonUniformResourceIndex(<null>)
```

Looks like `emitGlobalInst` in `slang-emit-spirv.cpp` doesn't have a case that handles `kIROp_NonUniformResourceIndex`. I'm no compiler whisperer so I'm not sure what a correct implementation would do here.

**Comment by sriramm-nv** [comment]
> Hey sorry to dig up a closed issue but I've hit an assert in the compiler when trying to use `NonUniformResourceIndex` in a fragment shader
> 
> ```
> [build] (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unimplemented: Unhandled global inst in spirv-emit:
> [build] let  %1	: _	= nonUniformResourceIndex(<null>)
> ```
> 
> Looks like `emitGlobalInst` in `slang-emit-spirv.cpp` doesn't have a case that handles `kIROp_NonUniformResourceIndex`. I'm no compiler whisperer so I'm not sure what a correct implementation would do here.

It is possible that some of the corner cases were not tested and as a result we are seeing this error. Could you kindly open an issue with a reproducing shader and assign it to me. I will work on it shortly.
