### ISSUE TITLE
Designated struct initializers

### ISSUE THREAD

**Issue by nanokatze** [shader-slang/slang#3878]
Designated initializers offer a more concise struct initialization syntax and allow the user to skip declaring a variable when passing a struct-typed value to a function. At least C, C++, Rust and Go offer a mechanism like this, although each one differing in semantics from the other in the more "interesting" cases.

I found https://github.com/shader-slang/slang/issues/504 which covers the problems that arise with designated init but it's not clear to me why it was closed. While I can definitely see the problems that arise trying to make designated init be friends with other language features, it seems to me like a lot of problems listed can be addressed by forbidding them. Such a "reduced" designated initializer would still be an ergonomic improvement for struct initialization, and if desired, more "interesting" cases could be assigned meaning and allowed in the future.

**Comment by csyonghe** [comment]
We have a new issue created for this: https://github.com/shader-slang/slang/issues/3738
We plan to support it in this quarter.

The previous issue was closed as an attempt to clean up our backlog and start a more organized approach to manage issues.

**Comment by csyonghe** [comment]
For now you can use the more verbose constructor syntax:
```
struct MyType
{
    int v;
    __init() { v = 0; }
}

void test(MyType t) { ... }
void f()
{
      test(MyType());
}
```

**Comment by nanokatze** [comment]
Oh whoops, thanks
