### ISSUE TITLE
Investigate and fix non-determinsitc Falcor test issue on SLANGWIN5.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3894]
We've been experiencing non-determinstic failures when running Falcor test on SLANGWIN5, it often crashes on test_PathTracer_D3D12 and test_PathTracer_Dieletric_D3D12 tests.

We try to figure out the cause (e.g. try update the drivers), and if none works, we should disable these two tests.

See example build logs here:
https://github.com/shader-slang/slang/actions/runs/8542730013/job/23404999936

**Comment by ArielG-NV** [comment]
seems that [SLANGWIN5](https://github.com/shader-slang/slang/actions/runs/8544210310/job/23409728385), and additionally [SLANGWIN4](https://github.com/shader-slang/slang/actions/runs/8542730013/job/23404999936) so far have failed the test inconsistently.

**Comment by csyonghe** [comment]
Update: Simon discovered that the PathTracerAdpative test case that uses SER maybe the reason for the inconsistencies. I have updated the Falcor checkout on our CI servers that disables SER on the test case. Let's see if this helps making things more stablized.
