### ISSUE TITLE
Remove most uses of `__target_intrinsic` and `__specialize_for_target`

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#3906]
There are a few cases where `__target_intrinsic` and `__specialize_for_target` is required: 1. edge cases 2. types 3. `[[vk::.*]]`. 

Other than these scenarios (and possibly a few others), we should be removing all uses of these attributes since they are incompatible with the capabilities system and are not needed anymore in most cases.

**Comment by swoods-nv** [comment]
Ariel - can you provide an estimate for this one? I've also labeled it as a quality & prod issue, is that the correct category? And how would you suggest prioritizing?

**Comment by ArielG-NV** [comment]
I suppose it should only take a day-two (depending on how many bugs are found

**Comment by ArielG-NV** [comment]
Priority is likely 1 since it is to be done after the initial capability system implementation

**Comment by jkwak-work** [comment]
Re-opening because it is not done yet.
