### ISSUE TITLE
Initialization of link-time specialized groupshared array

### ISSUE THREAD

**Issue by kevinboulain** [shader-slang/slang#3909]
I have this `32.slang` file (it's enough to work around #3581 since the possible subgroup sizes are well known):
```hlsl
export static const uint subgroup_size = 32;
```

That I compile to a module like this:
```
slangc 32.slang -o 32.slang-module
```

I then have a compute shader that I need to specialize given a subgroup size (alongside `VK_EXT_subgroup_size_control`, of course):
```hlsl
static const uint workgroup_size = 256;
extern static const uint subgroup_size;
static const uint workgroup_subgroups = workgroup_size / subgroup_size;

groupshared uint totals[workgroup_subgroups];

[shader("compute")] [numthreads(workgroup_size, 1, 1)] void compute(void) {}
```

It's compiled to a module like this:
```
slangc compute.slang -o compute.slang-module
```

And the two modules are linked together like this:
```
slangc 32.slang-module compute.slang-module -target spirv -o compute.spv -emit-spirv-directly -force-glsl-scalar-layout -fvk-use-entrypoint-name -matrix-layout-column-major
```

It works, but what I would like to do instead is:
```patch
-groupshared uint totals[workgroup_subgroups];
+groupshared uint totals[workgroup_subgroups] = {};
```

But the module won't compile:
```
slangc compute.slang -o compute.slang-module
compute.slang(5): error 30501: cannot use initializer list for array of statically unknown size 'int(256/subgroup_size)'
groupshared uint totals[workgroup_subgroups] = {};
```

There's probably some context in #693 or #899 but given that I can actually declare the array but not initialize it, it could be an oversight or there's a real blocker. I guess I expect it to behave like `GL_EXT_null_initializer` would in this case.

Edit: forgot to say I'm using v2024.1.6.

**Comment by csyonghe** [comment]
Our front-end currently don't allow empty initializing arrays whose size is not known at compile time. But it seems that you can work around this by initializing the array explicitly in the entrypoint. Or you can try something like:
```
groupshared uint totals[workgroup_subgroups] = __makeArrayFromElement<workgroup_subgroups>(0);

__intrinsic_op(makeArrayFromElement)
Array<uint, N> __makeArrayFromElement<let N:int>(uint element);
```

**Comment by csyonghe** [comment]
Note that initialization of groupshared variable is not a currently supported feature. The compiler currently generates in-efficient code in that every thread will try to assign to the variable at the begining of the entrypoint.

**Comment by kevinboulain** [comment]
If it weren't for the `extern` length, the initialization would have compiled. Is the link phase (when `extern`/`export` is resolved) not considered compile time?
Though, as you said, it would have resulted in inefficient code. Should initialization of `groupshared` memory be disallowed by default then (to avoid a potential surprise if nothing better can be done)?

(Feel free to close by the way, especially if you judge nothing is really broken here.)

**Comment by csyonghe** [comment]
Yeah, I think we need to work on the diagnostic to disallow initialization of groupshared variables as a separate issue.

Closing this one.
