### ISSUE TITLE
Are combined sampler/texture objects supported?

### ISSUE THREAD

**Issue by pema99** [shader-slang/slang#3917]
I see there is a `Sampler2D` type, but attempting to use it:

```hlsl
Sampler2D bar;

void frag()
{
}
```
With
```
slangc test.slang -stage fragment -entry frag -o test.hlsl
```
Results in:
```
(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: unhandled shader parameter kind
```
Version v2024.1.6

**Comment by csyonghe** [comment]
They are not yet supported when targeting HLSL.
Currently we just directly translate them to GLSL/SPIRV.

**Comment by swoods-nv** [comment]
Is Sampler2D targeting HLSL critical to your use case?

**Comment by pema99** [comment]
@swoods-nv yeah. I'm trying to run some existing shader code through slang. I unfortunately don't control this source code, so can't change it. It's rather old and uses combined sampler objects. Other than that, the majority of the code seems to work fine, which is quite promising.

**Comment by pema99** [comment]
To give a little more info: The source code is base includes / built in shader code for shaders targeting the Unity game engine. I'd like to use Slang for user code which includes said source code, in order to make use of some of Slangs nice features such as autodiff.
