### ISSUE TITLE
Ambiguous operators when multiplying half by integer literal

### ISSUE THREAD

**Issue by pema99** [shader-slang/slang#3918]
I'm attempting to run some old HLSL code through Slang (if you are interested, it's some of Unity's default shader include files). I came across an issue with some functions that multiply halfs by literals. Here is a small repro:

```hlsl
void foo(half bar)
{
    half res = bar * 2 - 1;
}
```
```
> slangc test.slang
test.slang(3): error 39999: ambiguous call to '*' with arguments of type (half, int)
    half res = bar * 2 - 1;
                   ^
core.meta.slang(1946): note 39999: candidate: func *(double, double) -> double
core.meta.slang(1938): note 39999: candidate: func *(float, float) -> float
```

**Notes:**
- Same thing happens with other arithmetic operators (-, /, etc.).
- If you change both occurrences of `half` to `float`, the issue doesn't reproduce.

I heard that Slang was backwards compatible with HLSL. Microsoft's HLSL compiler accepts this without issue, so I figured I'd report it.

**Comment by csyonghe** [comment]
I am not able to reproduce this error:
```
void foo(half bar)
{
    half res = bar * 2 - 1;
}

[numthreads(1,1,1)]
void main()
{
    foo(2);
}
```

`slangc test.slang -target spirv  -emit-spirv-directly`
generates spirv output without errors. Can you provide a full repro file?

**Comment by pema99** [comment]
Hmm.. just that text in a file was enough to repro it for me, just using `slangc <file>` with no additional arguments. I'll try what you posted later today

**Comment by pema99** [comment]
When I try compiling the exact snippet you posted, using the last main release of slang (v2024.1.6), with the same command, I get this output:
```
> slangc test.slang -target spirv  -emit-spirv-directly
test.slang(3): error 39999: ambiguous call to '*' with arguments of type (half, int)
    half res = bar * 2 - 1;
                   ^
core.meta.slang(1946): note 39999: candidate: func *(double, double) -> double
core.meta.slang(1938): note 39999: candidate: func *(float, float) -> float
test.slang(9): warning 30081: implicit conversion from 'int' to 'half' is not recommended
    foo(2);
        ^
```

**Comment by pema99** [comment]
So I suppose your hunch is correct, that this was fixed since last release.
