### ISSUE TITLE
Explicit binding for vulkan is not correctly assigned for AppendStructuredBuffer

### ISSUE THREAD

**Issue by obhi-d** [shader-slang/slang#3923]
Hello,

This code does not compile:
https://shader-playground.timjones.io/c077cc3bbce720f5f53e1da2feb7a542

The automatic binding counters are also not correct, for example here:
https://shader-playground.timjones.io/80ba8fb6b7d9c412db0aba00c9f97786

-> Why is inBuffer assigned binding = 12?

Thanks for looking into it.

**Comment by csyonghe** [comment]
The first code compiles fine from the shader playground link. By default it is showing diagnostic outputs and you need to select "Output" to see the glsl.

Can reproduce the binding on the second code, working on a fix.

**Comment by obhi-d** [comment]
Thanks, my bad. The warning seems invalid though.

**Comment by csyonghe** [comment]
@obhi-d The root cause for the invalid warnings and the bad bindings are the same. They are all fixed now.
