### ISSUE TITLE
Investigate why `sp*` API does not produce any result when compiling to binary module.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3927]
When using the legacy sp* api to compile a slang module into a binary module, the spGetContainerCode function did not return any code.

**Comment by swoods-nv** [comment]
Kai, do you have an estimate for this one?

**Comment by kaizhangNV** [comment]
> Kai, do you have an estimate for this one?

I have the fix for this one. The fix change actually fixes more issues than this one.
