### ISSUE TITLE
Error while specializing generic entrypoint with different types

### ISSUE THREAD

**Issue by il1aster** [shader-slang/slang#3928]
Hi,

I can confirm #3896 fixed specialization of a generic function with multiple copies of a same type, but I still get a crash while having different types in the specialization list. Adding a dummy generic parameter in the `shader-toy` example:
```hlsl
interface IDummy
{
    float getValue();
};
struct DummyEffect : IDummy
{
    float getValue() { return 0.0; }
}

float4 fragmentMain<T : IShaderToyImageShader, U : IDummy>(
    float4 sv_position : SV_Position)
    : SV_Target
{ ... }
```
and adding the dummy effect to the specialization list:
```c++
        slang::SpecializationArg dummyTypeArg;
        dummyTypeArg.kind = slang::SpecializationArg::Kind::Type;
        dummyTypeArg.type = effectModule->getLayout()->findTypeByName("DummyEffect");
        specializationArgs.add(dummyTypeArg);
```

...crashes the program with the following diagnostics:
```bash
shader-toy.slang(114): error 38029: type argument 'DummyEffect' does not conform to the required interface 'IShaderToyImageShader'
float4 fragmentMain<T : IShaderToyImageShader, U : IDummy>(
                        ^~~~~~~~~~~~~~~~~~~~~
shader-toy.slang(114): error 38005: expected a type as argument for specialization parameter '3'
float4 fragmentMain<T : IShaderToyImageShader, U : IDummy>(
                                                   ^~~~~~
```

Am I doing something wrong? I have code that could specialize generic entrypoints with multiple parameters through the API without trouble on previous versions, at least until v2023.1.1.

Thank you for looking into this.

**Comment by csyonghe** [comment]
No, you are not doing anything wrong. Sorry for the churn I will give this another look.
