### ISSUE TITLE
Two same "struct" are generated with different names when an arithmetic math is applied to the generic-argument

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3935]
**Problem Description**
While integrating Slang to UE 5.3, the following issue was encountered.

It appears that there is a bug on the deduplication of the generic arguments when the generic argument got an arithmetic math.

**Goal**
The generic arguments should be uniquely identified even when there are any arithmetic math applied to it.

**Repro-steps***
It is easier to show the problem than explaining it.
```
RWStructuredBuffer<float> output;

__generic<let ArraySize:int>
struct MyStruct
{
  int elems[ArraySize];
};

__generic<let ArraySize:int>
MyStruct<ArraySize / 2> Reduce(MyStruct<ArraySize> o)
{
  MyStruct<ArraySize / 2> result;
  result.elems[0] = o.elems[0];
  return result; // <==== Error happens here
}

[numthreads(4, 1, 1)]
void computeMain(int3 dispatchThreadID : SV_DispatchThreadID)
{
  MyStruct<4> a;
  output[0] = Reduce(a).elems[0];
}
```
When HLSL is generated from the Slang shader above, the function "Reduce" looks like following.
```
MyStruct_0 Reduce_0(MyStruct_1 o_0)
{
    MyStruct_2 result_0;
    result_0.elems_0[int(0)] = o_0.elems_0[int(0)];
    return result_0;
}
```
Note that the return type is "MyStruct_0" and it is trying to return a different type, "MyStruct_2".
Their implementations are same as you can see below,
```
struct MyStruct_0
{
    int  elems_0[int(2)];
};
struct MyStruct_2
{
    int  elems_0[int(2)];
};
```
This causes the compilation to fail.

**Comment by swoods-nv** [comment]
Jay, is there an estimate for this one?

**Comment by jkwak-work** [comment]
This is probably an easy one but I don't have much confidence.
I put 3 days for now.

**Comment by csyonghe** [comment]
The issue is usually because we failed to identify the two specializations are the same thing.

In IR, we usually deduplicate `specialize` insts. When we specialize the `Reduce` function, we want to make sure we didn't create duplicated specialized structs. To trace this down, you can set a breakpoint after specialization pass, and inspect the IR for duplicate struct types. Find the duplicate struct type with the bigger UID, and try to track down why it gets created. There is a lookup process before creating the specialized struct type to see if a specialization is already created. Check why that lookup failed to determine the case.

**Comment by csyonghe** [comment]
Set a breakpoint on the call to `specializeModule` in slang-emit.cpp:424 and start from there.
Then `specializeGeneric` will be called on everything that needs specialization, this include the generic functions and the generic struct type. Try to set a break point in this function when we are trying to specialize a struct type, and see why the lookup failed in slang-ir-specialize.cpp:238.

**Comment by swoods-nv** [comment]
Jay, is this issue still blocking you?

**Comment by jkwak-work** [comment]
Yes it blocks my UE task.
I will start working on this tomorrow.

**Comment by jkwak-work** [comment]
I am having some trouble reproducing the issue.
When I target "HLSL", it is easy to reproduce.
But when I use gfx with slang-test, both dxc and fxc don't print the error and everything works fine.
I am little puzzled.
The bug might be in the code where HLSL gets emitted.

**Comment by jkwak-work** [comment]
It appears that the issue stems from the fact that the duplication detecting logic uses hash values.
And the hash values are calculated from the memory pointer values rather than the values the pointers point to.
```
HashCode IRSimpleSpecializationKey::getHashCode() const
{
    auto valCount = vals.getCount();
    HashCode hash = Slang::getHashCode(valCount);
    for( Index ii = 0; ii < valCount; ++ii )
    {
        hash = combineHash(hash, Slang::getHashCode(vals[ii])); // <== This generates a hash value from memory pointer values; not the value kIROp_IntLit represents.
    }
    return hash;
}
```
When this happens, the following is where the issue happens.
```
    IRInst* specializeGeneric(
        IRGeneric* genericVal,
        IRSpecialize* specializeInst)
    {
        // First, we want to see if an existing specialization
        // has already been made. To do that we will construct a key
        // for lookup in the generic specialization context.
        //
        // Our key will consist of the identity of the generic
        // being specialized, and each of the argument values
        // being pased to it. In our hypothetical example of
        // `specialize(g, a, b, c)` the key will then be
        // the array `[g, a, b, c]`.
        //
        Key key;
        key.vals.add(specializeInst->getBase());
        UInt argCount = specializeInst->getArgCount();
        for (UInt ii = 0; ii < argCount; ++ii)
        {
            key.vals.add(specializeInst->getArg(ii));
        }

        {
            // We use our generated key to look for an
            // existing specialization that has been registered.
            // If one is found, our work is done.
            //
            IRInst* specializedVal = nullptr;
            if (genericSpecializations.tryGetValue(key, specializedVal)) // <== This didn't properly work
                return specializedVal;
        }

```

**Comment by jkwak-work** [comment]
I found another problem regarding this issue.
When I wrap the generic argument, which is a compile-time constant, with "int", it becomes not-compile-time constant.
```
tests/bugs/gh-3935.slang(14): error 39999: expression does not evaluate to a compile-time constant
MyStruct<int(ArraySize / 2)> Reduce(MyStruct<ArraySize> o)
```
Note that the error message above shows "int(ArraySize /2)".
It compiles fine when I just did "MyStruct<ArraySize / 2> Reduce..."

**Comment by jkwak-work** [comment]
Fix is merged.
Closing the issue.
