### ISSUE TITLE
Support __LINE__ macro for the caller of a macro

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang#3940]
[Posted on behalf of a user without GH account]

We are using the `__LINE__` macro in combination with GPU printing to implement an assert in shader code. The assert roughly looks like this:

```
#define STR2(X) # X
#define STR(X) STR2(X)
#define CARB_ASSERT(X) \                     //<-- let's say this is line 100 in our file
if (!(X)) { \
        println_assert("Assertion triggered in " __FILE__ ":" STR(__LINE__) ", expression : " #X); \
}
```

this assert is used just as expected

```
void main(dispatchIdx...)
{
    float3 radiance = compute();
    CARB_ASSERT(!isNanOrInf(radiance)); ///< will show line 100 from different file, not this line
}
```

I browsed tests\preprocessor\special-macro-complex.slang but didn't find a matching test for it. I did find this comment which shows the usage of __LINE__ in a macro but probably expects a different result:
```
// LINE number will be for the macro invocation, not the expansion
```

**Comment by csyonghe** [comment]
This is duplicate with #2134

**Comment by swoods-nv** [comment]
Should we raise the priority / pull it in to Q2, in that case? It affects a current client, but they have a workaround.

**Comment by csyonghe** [comment]
Yes, we can try to fix this in Q2.
