### ISSUE TITLE
tests/cpu-program/gfx-smoke.slang causes slang compiler to assert

### ISSUE THREAD

**Issue by tgrimesnv** [shader-slang/slang#3953]
Using the command line for slang-test: 
tests/cpu-program/gfx-smoke -use-test-server -server-count 1

Gives this:
error: ERROR:
EXPECTED{{{
result code = 0
standard error = {
}
standard output = {
0.0
1.0
2.0
3.0
}
}}}
ACTUAL{{{
result code = -1
standard error = {
**(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: assert failure: modifiers.isEmpty()**
}
standard output = {
}
}}}

FAILED test: 'tests/cpu-program/gfx-smoke.slang (cpu)'

===
0% of tests passed (0/1)
===

failing tests:
---
tests/cpu-program/gfx-smoke.slang (cpu)
---

**Comment by jkwak-work** [comment]
This is regression caused from
```
commit c28a22fb8b505ff48ca0814ca290ee4f698aa38b
Author: Yong He <yonghe@outlook.com>
Date:   Wed Mar 20 13:33:13 2024 -0700

    Fix namespace parsing. (#3803)

    * Fix namespace parsing.

    * Fix.
```
It works if I revert the change.

**Comment by bmillsNV** [comment]
@tgrimesnv can you please summarize where we are at with this issue?

**Comment by tgrimesnv** [comment]
This would be a question for @csyonghe

**Comment by bmillsNV** [comment]
Not an urgent issue for now. We'll put this back on the backlog.
