### ISSUE TITLE
"Ambiguous reference to This" in extension method returning This

### ISSUE THREAD

**Issue by raphlinus** [shader-slang/slang#3960]
I'm trying to do something like this:

```slang
interface Monoid {
    static const This identity;

    This combine(This b);
}

extension Monoid {
    This wave_reduce() {
        // TODO: actual logic to do wave reduction
        return This.identity;
    }
}
```

The idea is to implement it for the addition monoid using WaveActiveSum, but let it fall to the generic implementation for monoids that don't have such a specialization. When I compile this, I get:

```
monoid.slang(25): error 39999: ambiguous reference to 'This'
```

I'm not sure if this is a real limitation in the language's type system, or just a case not well handled. In Rust, the extension wouldn't be in a separate block, it would just be a default implementation of the method in the trait.

**Comment by csyonghe** [comment]
Looks like this is just a bug in the type system.

**Comment by swoods-nv** [comment]
@raphlinus Does this issue block work for you? It sounds like there's a bit more than a simple bug here, and I'm not sure we can prioritize this in the very near term. We may also be able to identify a workaround if you can share what issue you're attempting to solve.

**Comment by bmillsNV** [comment]
@raphlinus we plan to address this issue in Q3 2024. Please let us know if that timeline doesn't work for you.

**Comment by raphlinus** [comment]
Thanks for the update! I should clarify, this isn't really blocking me, it came up while I was exploring. I'm still doing almost all my shader work in WGSL, but would like to move to Slang when that becomes practical.
