### ISSUE TITLE
Pointer support requires clarification in user-guide

### ISSUE THREAD

**Issue by cheneym2** [shader-slang/slang#3970]
https://shader-slang.com/slang/user-guide/conventional-features.html indicates that pointers are not supported.

> Note
> Slang does not currently support pointer types as in C/C++. Pointers cannot be implemented robustly and completely on many of the target platforms Slang currently supports.

Though there is also a section describing support for pointers in SPIRV and Cuda:
https://shader-slang.com/slang/user-guide/convenience-features.html#pointers

The documentation should be updated, probably removing the statement about pointers not being supported.

I believe the section in convenience-features should be marked "(limited)" similarly to the inheritance section below it, along with a "Limitations" subsection explaining the limitations of using pointers.  As I understand, pointers work for global memory, but not shared or local memory.  That should be clarified.

**Comment by swoods-nv** [comment]
Adam, would you mind following up and adding this to the docs? Thank you for identifying and filing it!
