### ISSUE TITLE
Multiple entry points in a single invocation of slangc doesn't seem to work?

### ISSUE THREAD

**Issue by pema99** [shader-slang/slang#3973]
I have a simple test file, `test.slang`:
```
void vert ()
{
}

float4 frag () : SV_Target
{
    return 1;
}
```
When I try to compile 2 entry points in one invocation ([based on this info](https://github.com/shader-slang/slang/blob/4b3f554a58e4224806c31d66874fbe60f1f09332/docs/command-line-slangc.md#multiple-entry-points)), I get a surprising error:
```
> slangc test.slang -entry vert -stage vertex -o vert.hlsl -entry frag -stage fragment -o frag.hlsl
(0): error 70: the output path 'vert.hlsl' is not associated with any entry point; a '-o' option for a compiled kernel must follow the '-entry' option for its corresponding entry point
(0): error 70: the output path 'frag.hlsl' is not associated with any entry point; a '-o' option for a compiled kernel must follow the '-entry' option for its corresponding entry point
```
If I split the command in 2, it works fine:
```
> slangc test.slang -entry frag -stage fragment -o frag.hlsl
> slangc test.slang -entry vert -stage vertex -o vert.hlsl
```
slangc v2024.1.7

**Comment by csyonghe** [comment]
For complicated use cases like this, we highly recommend using our compilation API instead of the `slangc` interface. There you can specify the compilation in a flexible and non-ambiguous way.

**Comment by pema99** [comment]
I'll keep that in mind. Regardless, this is a bug, no?

**Comment by swoods-nv** [comment]
@pema99 - I think these two issues both stem from restrictions in current support. I'm going to close this bug and consolidate tracking to #3974 .
