### ISSUE TITLE
Narrowing bit_cast fails vulkan validation

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3983]
Hi,

the following program fails vulkan validation when compiled using slang 2024.1.7 with the command `slangc.exe -entry computeMain -stage compute -target spirv -O0 -emit-spirv-directly -o shader.spv && spirv-val.exe shader.spv`:
```c++
uniform StructuredBuffer<uint64_t> in;
uniform RWStructuredBuffer<uint32_t> out;

[numthreads(4, 1, 1)]
[shader("compute")]
void computeMain() {
    out[0] = bit_cast<uint32_t>(in[0]);
}
```

Gives me the following SPIRV validation error (using spirv-val from the 1.3.280.0 Vulkan SDK):
```
error: line 50: Expected input to have the same total bit width as Result Type: Bitcast
  %23 = OpBitcast %uint %22
```

I'd rather have the warning already in slang's frontend instead of only during SPIRV validation.

Thanks for having a look!

**Comment by csyonghe** [comment]
There is a missing check on this, and this is a known issue to us.

This is the same issue with #3331.
