### ISSUE TITLE
Pointer deref inside mesh shader results in compiler error on spirv 

### ISSUE THREAD

**Issue by BeastLe9enD** [shader-slang/slang#3991]
I have the following mesh shader:

```Slang
struct MeshOutput {
    float4 position: SV_Position;
    float3 color: COLOR0;
};

[[vk::push_constant]] struct PushConstants {
    float4x4 view_projection_matrix;
    uint *my_ptr;
} push_constants;

[shader("mesh")]
[outputtopology("triangle")]
[numthreads(1, 1, 1)]
void mesh_main(out indices uint3 triangles[1], out vertices MeshOutput vertices[3]) {
    SetMeshOutputCounts(*push_constants.my_ptr, 1);
    triangles[0] = uint3(0, 1, 2);
    
    vertices[0].position = mul(push_constants.view_projection_matrix, float4(-0.5, 0.5, 0.0, 1.0));
    vertices[0].color = float3(1.0, 0.0, 0.0);

    vertices[1].position = mul(push_constants.view_projection_matrix, float4(0.5, 0.5, 0.0, 1.0));
    vertices[1].color = float3(0.0, 1.0, 0.0);

    vertices[2].position = mul(push_constants.view_projection_matrix, float4(0.0, -0.5, 0.0, 1.0));
    vertices[2].color = float3(0.0, 0.0, 1.0);
}
```

when I compile the code with `slangc.exe .\test.slang -profile glsl_450 -target spirv -o hello_world.spv -entry mesh_main | spirv-cross.exe -V .\hello_world.spirv`, I get the following error:

`(0): internal error 99999: unexpected condition encountered in Slang compiler: unhandled type`

From what I read I thought buffer pointers are supported on spirv, so I wonder what I'm doing wrong here. When I just have the pointer inside `push_constants` and I do not deref it, its working fine.

The version I'm using is slang-2024.1.7-win64

**Comment by csyonghe** [comment]
You need to add -emit-spirv-directly.

The glsl backend does not support pointers, only spirv direct backend allows it, which is enabled with this option.

**Comment by BeastLe9enD** [comment]
thanks, that worked for me. Maybe the compiler error message could me more clear like `Pointers are only allowed when using the following backends: spirv ....

**Comment by csyonghe** [comment]
Thanks for confirming! We are in the process of deprecating the glsl path and move to direct to spirv backend by default so it will no longer be required to pass -emit-spirv-directly in the future. Closing this issue now.
