### ISSUE TITLE
Spirv validation and __ref with atomics

### ISSUE THREAD

**Issue by pborsutzki** [shader-slang/slang#3997]
Hi,

I am trying to implement atomics for the C++ backend, while wrapping the ones for spirv using this code:

```c++
float atomicAdd(__ref float value, float amount)
{
    __target_switch
    {
    case cpp:
        __requirePrelude("#include <atomic>");
        __intrinsic_asm "std::atomic_ref(*$0).fetch_add($1)";
    case spirv:
        return __atomicAdd(value, amount);
    }
}

RWStructuredBuffer<float> outputBuffer;

[numthreads(4, 1, 1)]
[shader("compute")]
void computeMain(int3 dispatchThreadID : SV_DispatchThreadID) {
    atomicAdd(outputBuffer[0], 1);
}
```
The code seems to work "somewhat" but it fails spirv validation (1.3.280.0) when compiling it with `-g` and `-O0` (using slangc 2024.1.8 and `slangc.exe -target spirv -emit-spirv-directly -g -O0` as parameters):
```
error: line 95: OpFunctionCall Argument <id> '49[%49]'s type does not match Function <id> '56[%_ptr_Function_float]'s parameter type.
  %54 = OpFunctionCall %float %atomicAdd %49 %float_1
```

Not sure if I am doing something wrong, if slang generates bad spirv or if spirv val is wrong. I still find it interesting that the problem is "resolved" when omitting `-g` or using at least `-O1`.

Can you have a look into this?

**Comment by csyonghe** [comment]
For now, all functions that takes `__ref` needs to be [ForceInline]'d.

`__ref` is still considered an internal feature and the user is advised to use with caution.

To fully support this scenario, we need to make sure we specialize the function based on the pointer address space of the argument.

**Comment by csyonghe** [comment]
@ArielG-NV I believe we have logic to automatically inline functions with `__ref` parameters, and we need to investigate why that didn't happen. Perhaps the `-O0` option mistakenly disables the inlining.

**Comment by ArielG-NV** [comment]
I will investigate what is happening here.

**Comment by ArielG-NV** [comment]
> Hi,
> 
> I am trying to implement atomics for the C++ backend, while wrapping the ones for spirv using this code:
> 
> ```c++
> float atomicAdd(__ref float value, float amount)
> {
>     __target_switch
>     {
>     case cpp:
>         __requirePrelude("#include <atomic>");
>         __intrinsic_asm "std::atomic_ref(*$0).fetch_add($1)";
>     case spirv:
>         return __atomicAdd(value, amount);
>     }
> }
> 
> RWStructuredBuffer<float> outputBuffer;
> 
> [numthreads(4, 1, 1)]
> [shader("compute")]
> void computeMain(int3 dispatchThreadID : SV_DispatchThreadID) {
>     atomicAdd(outputBuffer[0], 1);
> }
> ```
> 
> The code seems to work "somewhat" but it fails spirv validation (1.3.280.0) when compiling it with `-g` and `-O0` (using slangc 2024.1.8 and `slangc.exe -target spirv -emit-spirv-directly -g -O0` as parameters):
> 
> ```
> error: line 95: OpFunctionCall Argument <id> '49[%49]'s type does not match Function <id> '56[%_ptr_Function_float]'s parameter type.
>   %54 = OpFunctionCall %float %atomicAdd %49 %float_1
> ```
> 
> Not sure if I am doing something wrong, if slang generates bad spirv or if spirv val is wrong. I still find it interesting that the problem is "resolved" when omitting `-g` or using at least `-O1`.
> 
> Can you have a look into this?

@pborsutzki in the meantime as a workaround, `[ForceInline]` can be added to the function definition.
