### ISSUE TITLE
Compute shader with derivative intrinsic's do not compile correctly on direct-to-spirv backend. 

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#4000]

**Comment by ArielG-NV** [comment]
what does broken imply here?

**Comment by ArielG-NV** [comment]
I will look into this problem as well.

This is quite odd since every target shares the same capability list.

**Comment by ArielG-NV** [comment]
2 problems:
1. capabilities are partially incorrect.
2. we do not enable ComputeDerivativeQuad/ComputeDerivativeLinear when using derivative functions inside a compute shader.

a pr will solve both of these.
