### ISSUE TITLE
ForceInline atomic operations on all resources

### ISSUE THREAD

**Issue by sriramm-nv** [shader-slang/slang#4011]
Follow-up change request to support inlining of atomic operations on all resources. 

This prevents any decorations applied on the Atomic operation, since it is encapsulated by the call.
The goal is to ForceInline the atomic operations so that the decorations can be applied to the appropriate instruction.

**Comment by swoods-nv** [comment]
Sriram, are you currently working on this item? Do you have an estimate and a goal category for it?
