### ISSUE TITLE
Slang fails to parse file with BOM

### ISSUE THREAD

**Issue by pema99** [shader-slang/slang#4046]
When compiling a file that has a byte order mark, Slang chokes. Happens both with `slangc` and the native API (for example when #include'ing a file with a BOM).

I've attached a simple file with a BOM (.txt because github won't let me upload a .hlsl tile)
[repro.txt](https://github.com/shader-slang/slang/files/15140008/repro.txt)

Observe:
```
>file repro.txt
repro.txt: C source, Unicode text, UTF-8 (with BOM) text, with CRLF line terminators

>slangc -lang hlsl repro.txt
repro.txt(1): error 10000: illegal character (0xEF)
∩╗┐void main()
^
repro.txt(1): error 10000: illegal character (0xBB)
∩╗┐void main()
 ^
repro.txt(1): error 10000: illegal character (0xBF)
∩╗┐void main()
  ^
```

**Comment by cheneym2** [comment]
I've reproduced the issue and am working on a fix.
