### ISSUE TITLE
"$G0" keyword doesn't work when used in __target_switch

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4053]
**Problem description**
"$G0" keyword works when used in __target_intrinsic.
But it doesn't work when used in __target_switch.

**Repo steps**
The following function exists in core.meta.slang, and works as it is.
```
__generic<T>
__target_intrinsic(cuda, "SLANG_ALIGN_OF($G0)")
__target_intrinsic(cpp, "SLANG_ALIGN_OF($G0)")
[__readNone]
[require(cpp_cuda)]
int __alignOf();
```
But when it is converted to use __target_switch, it fails on one of tests, "tests/cuda/cuda-layout.slang".
```
__generic<T>
[__readNone]
[require(cpp_cuda)]
int __alignOf()
{
    __target_switch
    {
    case cpp: __intrinsic_asm "SLANG_ALIGN_OF($G0)";
    case cuda: __intrinsic_asm "SLANG_ALIGN_OF($G0)";
    }
}
```

The same problem is observed with the following functions as well,

- __sizeOf()
- Ptr<T> TensorView::data_ptr();
- Ptr<T> TensorView::data_ptr_at();
- T TensorView::load(uint x);
- T TensorView::load(uint x, uint y);
- T TensorView::load(uint x, uint y, uint z);
- T TensorView::load(uint x, uint y, uint z, uint w);
- void TensorView::store(uint x, T val);
- void TensorView::store(uint x, uint y, T val);
- void TensorView::store(uint x, uint y, uint z, T val);
- void TensorView::store(uint x, uint y, uint z, uint w, T val);

When ran with a debug build, it fails on the following assertion,
```
const char* IntrinsicExpandContext::_emitSpecial(const char* cursor)
{
...omit...
        case 'G':
        {
            // Get the type/value at the index of the specialization of this generic

            Index argIndex = parseNat() + m_argIndexOffset;
            
            IRSpecialize* specialize = as<IRSpecialize>(m_callInst->getCallee());
            SLANG_ASSERT(specialize);
```
"specialzie" is supposed to be `kIROp_Specialize`, but it is `null_ptr` when the issue is reproduced.

**Comment by csyonghe** [comment]
If `sizeof` and `alignof` are the only intrinsics using this `G0` thing, we should turn them into instructions and get rid of the `G0` logic.

**Comment by csyonghe** [comment]
e.g. add a `kIROp_SizeOf` and `kIROp_alignof` instruction that takes a value of T type.
```
__intrinsic_op($(kIROp_SizeOf))
int __sizeof_impl<T>(T val);

[ForceInline]
int __sizeof<T>()
{
      return __sizeof_impl<T>(__default<T>());
}
```

**Comment by csyonghe** [comment]
And then we can simply fold sizeof and alignof instructions in `peepholeOptimize` pass by replacing them with the result of `getNaturalSizeAndAlignment`.
