### ISSUE TITLE
Attributes not working in entry point parameters

### ISSUE THREAD

**Issue by skallweitNV** [shader-slang/slang#4055]
Trying to use user attributes on entry point parameters results in an error:

```c#
[__AttributeUsage(_AttributeTargets.Var)]
struct rootAttribute
{ };

[shader("compute")]
[numthreads(32, 1, 1)]
void copy_byte_address_buffer(
    uint tid: SV_DispatchThreadID,
    [root] ByteAddressBuffer src
)
{
}
```
results in a compiler error `attribute 'root' is not valid here (31002)`

**Comment by kaizhangNV** [comment]
The fix is merged as https://github.com/shader-slang/slang/pull/4067.
Will close the issue after I will submit a new test as well.

**Comment by skallweitNV** [comment]
@kaizhangNV can we also define the attribute to be useable both for variables and function parameters?

**Comment by kaizhangNV** [comment]
Not in current implementation.

**Comment by kaizhangNV** [comment]
Are you talking about this?
`attribute_syntax [format(format : String)] : FormatAttribute;`

This is different from the user attribute.

**Comment by skallweitNV** [comment]
Yes. I realize that's a built-in and has different rules.
How hard would it be to make user attributes allow to use multiple attribute targets?

**Comment by kaizhangNV** [comment]
It's not that hard, but seems not very necessary.
@csyonghe for visibility.

**Comment by skallweitNV** [comment]
In Falcor (Slang/GFX) we use a `root` user attribute for marking resources to be bound as root descriptors in D3D12. In Falcor we only ever bound global resources but in my new framework we support passing entry point arguments, and allowing the `[root]` attribute to be used on those would be nice.

**Comment by kaizhangNV** [comment]
We can potentially drop the new "Param" target, and keep using "Var" target for all the variables.
Seems no harm for the design.

**Comment by kaizhangNV** [comment]
// The attribute declaration will have one or more `AttributeTargetModifier`s
        // that each specify a syntax class that the attribute can be applied to.
        // If any of these match `attrTarget`, then we are good.

Reading this comment, it looks like we can use more target for one attribute declaration. But don't know how to do it exactly.

**Comment by kaizhangNV** [comment]
We can actually use multiple AttributeTargetModifier to decorate the attribute declaration according to the comment and implementation, 

```
        bool validTarget = false;
        for(auto attrTargetMod : attrDecl->getModifiersOfType<AttributeTargetModifier>())
        {
            if(attrTarget->getClass().isSubClassOf(attrTargetMod->syntaxClass))
            {
                validTarget = true;
                break;
            }
        }
```

but in the searching implementation, it only search for the first one. I think this could also be a potential bug.
SemanticsVisitor::lookUpAttributeDecl() ::

```
        AttributeTargetModifier* targetModifier = m_astBuilder->create<AttributeTargetModifier>();
        targetModifier->syntaxClass = attrUsageAttr->targetSyntaxClass;
        targetModifier->loc = attrUsageAttr->loc;
        addModifier(attrDecl, targetModifier);
```

**Comment by csyonghe** [comment]
@kaizhangNV It seems the simplest fix is just to turn the search into a loop.

**Comment by kaizhangNV** [comment]
Yes, that's exactly what I'm doing.
https://github.com/shader-slang/slang/pull/4087

**Comment by csyonghe** [comment]
Closing since it is fixed.
