### ISSUE TITLE
VKCTS nightly runs start failing on run #38

### ISSUE THREAD

**Issue by dzysk** [shader-slang/slang#4071]
The VKCTS nightly runs use a test list of tests that are known to pass. So, they should not being failing.

Run #37 they're all passing: https://github.com/shader-slang/slang/actions/runs/8717827062/job/23913806415

Run #38 starts showing failing tests: https://github.com/shader-slang/slang/actions/runs/8733880185/job/23963413998

Run #40 the tests start getting canceled part way through: https://github.com/shader-slang/slang/actions/runs/8763407183/job/24052256260

**Comment by cheneym2** [comment]
I've reproduced the bug locally.

**Comment by cheneym2** [comment]
Quick repro:

C:\Users\acheney\Downloads\VK-GL-CTS_WithSlang-0.0.3-win64\VK-GL-CTS_WithSlang-0.0.3-win64>deqp-vk.exe --deqp-case "dEQP-VK.glsl.texture_functions.textureclamp.sparse_samplercube_bias_fixed*"
Writing test log into TestResults.qpa
dEQP Core vulkan-cts-1.3.8.0-68-gca98e86bcb8d06f8891758fa4a0e416e2d43117b (0xca98e86b) starting..
  target implementation = 'Default'

Test case 'dEQP-VK.glsl.texture_functions.textureclamp.sparse_samplercube_bias_fixed_fragment'..
spawinAndWaitTestServerThread: #1 thread is active
#2 spawinAndWaitTestServerThread: Thread launching test-server
#3 spawinAndWaitTestServerThread: thread succeded to launch server
Failed to generate SPIRV ouptput from test-server results: 80004005
  InternalError (Compiling GLSL to SPIR-V failed at vkPrograms.cpp:701)

DONE!

Test run totals:
  Passed:        0/1 (0.0%)
  Failed:        1/1 (100.0%)
  Not supported: 0/1 (0.0%)
  Warnings:      0/1 (0.0%)
  Waived:        0/1 (0.0%)

C:\Users\acheney\Downloads\VK-GL-CTS_WithSlang-0.0.3-win64\VK-GL-CTS_WithSlang-0.0.3-win64>

**Comment by cheneym2** [comment]
From test-server.exe, I see a failing call to compile this shader:

```
#version 450
#extension GL_ARB_sparse_texture2 : require
#extension GL_ARB_sparse_texture_clamp : require
layout(location = 0) out mediump vec4 o_color;
layout(location = 0) in highp vec3 v_texCoord;
layout(location = 1) in highp float v_lodBias;
layout(set = 0, binding = 0) uniform highp samplerCube u_sampler;
layout(set = 0, binding = 1) uniform buf0 { highp vec4 u_scale; };
layout(set = 0, binding = 2) uniform buf1 { highp vec4 u_bias; };

void main()
{
        vec4 texel;
        int success = sparseTextureClampARB(u_sampler, v_texCoord, float(4), texel, v_lodBias);
        if (sparseTexelsResidentARB(success))
                o_color = vec4(texel * u_scale + u_bias);
        else
                o_color = vec4(0.54117647058, 0.16862745098, 0.8862745098, 1.0);
}
```


Running the same through slangc shows this error:

```
c:\Users\acheney\Documents\git\slang>build\Release\bin\slangc.exe test.slang.frag -target spirv -stage fragment -entry main -allow-glsl
test.slang.frag(14): error 30015: undefined identifier 'sparseTextureClampARB'.
    int success = sparseTextureClampARB(u_sampler, v_texCoord, float(4), texel, v_lodBias);
                  ^~~~~~~~~~~~~~~~~~~~~
test.slang.frag(15): error 30015: undefined identifier 'sparseTexelsResidentARB'.
    if (sparseTexelsResidentARB(success))
        ^~~~~~~~~~~~~~~~~~~~~~~

c:\Users\acheney\Documents\git\slang>
```

**Comment by cheneym2** [comment]
Regression is in:

5dd27a26da9b6b6191f3b1eba0f38f85714c1ae3 Support combined texture sampler when targeting HLSL. (#3963)
https://github.com/shader-slang/slang/pull/3963

**Comment by cheneym2** [comment]
C:\Users\acheney\Downloads\VK-GL-CTS_WithSlang-0.0.3-win64\VK-GL-CTS_WithSlang-0.0.3-win64>type test.slang.vert
```
#version 450 core
layout(location = 0) in highp vec4 a_position;
layout(location = 4) in highp vec2 a_in0;
layout(location = 0) out mediump vec4 v_color;
layout(set = 0, binding = 0) uniform highp isampler2D u_sampler;
layout(set = 0, binding = 1) uniform buf0 { highp vec4 u_scale; };
layout(set = 0, binding = 2) uniform buf1 { highp vec4 u_bias; };
out gl_PerVertex {
        vec4 gl_Position;
};

void main()
{
        gl_Position = a_position;
        v_color = vec4(texture(u_sampler, a_in0))*u_scale + u_bias;
}
```

C:\Users\acheney\Downloads\VK-GL-CTS_WithSlang-0.0.3-win64\VK-GL-CTS_WithSlang-0.0.3-win64>slangc test.slang.vert
```
test.slang.vert(15): error 39999: no overload for 'texture' applicable to arguments of type (Sampler2D<vector<int,4>>, vector<float,2>)
    v_color = vec4(texture(u_sampler, a_in0))*u_scale + u_bias;
                          ^
glsl.meta.slang(1723): note 39999: candidate: public func texture(__TextureImpl<float, __Shape2D, 1, 0, 0, 0, 1, 1, 0>, float4) -> float
public float texture(sampler2DArrayShadow sampler, vec4 p)
             ^~~~~~~
glsl.meta.slang(1710): note 39999: candidate: public func texture(__TextureImpl<float, __Shape1D, 1, 0, 0, 0, 1, 1, 0>, float3) -> float
public float texture(sampler1DArrayShadow sampler, vec3 p)
             ^~~~~~~
glsl.meta.slang(1697): note 39999: candidate: public func texture(__TextureImpl<float, __ShapeCube, 0, 0, 0, 0, 1, 1, 0>, float4) -> float
public float texture(samplerCubeShadow sampler, vec4 p)
             ^~~~~~~
glsl.meta.slang(1684): note 39999: candidate: public func texture(__TextureImpl<float, __Shape2D, 0, 0, 0, 0, 1, 1, 0>, float3) -> float
public float texture(sampler2DShadow sampler, vec3 p)
             ^~~~~~~
glsl.meta.slang(1671): note 39999: candidate: public func texture(__TextureImpl<float, __Shape1D, 0, 0, 0, 0, 1, 1, 0>, float3) -> float
public float texture(sampler1DShadow sampler, vec3 p)
             ^~~~~~~
glsl.meta.slang(1638): note 39999: candidate: public func texture<float, 4, __Shape2D, 0, 0, 0>(Sampler2D<vector<float,4>>, float2) -> float4
public vector<T,4> texture(__TextureImpl<
                   ^~~~~~~
glsl.meta.slang(1624): note 39999: candidate: public func texture<float, 4>(Sampler1D<vector<float,4>>, float) -> float4
public vector<T,4> texture(Sampler1D<vector<T,N>> sampler, float p)
                   ^~~~~~~

```
C:\Users\acheney\Downloads\VK-GL-CTS_WithSlang-0.0.3-win64\VK-GL-CTS_WithSlang-0.0.3-win64>

**Comment by jkwak-work** [comment]
Looking at the error message, the given code is trying to use int4 type sampler and it couldn't find one. The closest one showing is float4 sampler.

If this is not going to be an easy fix, we can simply disable this test from the CTS test list until we have a proper fix. I assume that we run only a few tests out of all CTS test.

**Comment by jkwak-work** [comment]
Or if you can make a simpler repro case, please create a new issue and assign it to me.

**Comment by cheneym2** [comment]
@jkwak-work What is the issue that you filed to deal with the regression we uncovered here?

**Comment by cheneym2** [comment]
I found it here: https://github.com/shader-slang/slang/issues/4196
