### ISSUE TITLE
-emit-spirv-via-glsl is missing in slang API compilation

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4072]
The option '-emit-spirv-via-glsl' is missing in the slang API compilation. But it has no issue when using 'slangc'.

**Comment by csyonghe** [comment]
This can be indirectly specified by `spSetTargetFlag(req, targetIndex, 0)`.
There is a bug in `spSetTargetFlag` though, but it is being fixed in #4069.

**Comment by kaizhangNV** [comment]
Close the issue as the fix #4073 is merged.
