### ISSUE TITLE
Check for use of uninitialized variables

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#408]
The SSA generation pass currently inserts `undefined` instructions to represent the value of a local variable if it is used before it is initialized. The front-end should diagnose an error if any of these instructions are still present/live after the "mandatory" optimization passes have been applied.

There are some complications around doing a high quality version of this pass:

* We also need to support variables that couldn't be promoted to SSA temporaries. In that case, checking for undefined-ness involves checking if there are any `load`s from the variable that are not dominated by a `store` or other definite initialization (e.g., passing the variable as an argument for an `out` parameter).

* The above point hints that passing a value as an argument for an `inout` parameter needs to count like a `load`, in that it would see an undefined value.

* It is possible that an SSA value like a block parameter is undefined on entry to a loop, so that there is a use of the `undefined` for a phi at the start of the loop, but then either (1) the variable is always initialized inside the loop body, before any possible `break`, or (2) the variable is always initialized in the loop body, and any preceding `break` statements are unreachable on the first iteration.

* When using an aggregate or array-type temporary, it is possible that it could be initialized "piece-by-piece" by initializing individual fields/elements. Ideally we would *either* scalarize such types so that the definite-initialization logic can look at each field/element in isolation, *or* make the analysis understand "partially initialized" states so that it can give reasonable error messages.

We need to figure out a reasonable strategy for detecting things that rules out most cases (so that we don't get errors from the downstream compiler), but also doesn't annoy users who write code where they "obviously" initialize a variable prior to use.

Note: one strategy for eliminating errors from downstream compilers would be to always generate output HLSL/GLSL where all variables are fully initialized when declared, using default values. This might mask some uninitialized-variable issues in the users code, so we'd need to be careful about this.

**Comment by expipiplus1** [comment]
We should also make sure to check `out` parameters when they are "used" at each `return` statement.
