### ISSUE TITLE
Warnings emitted during link time are not filtered by diagnostic settings

### ISSUE THREAD

**Issue by skallweitNV** [shader-slang/slang#4081]
I see lots of `notEqualReinterpretCastSize` warnings being generated even though they are disabled using

```
spOverrideDiagnosticSeverity(pSlangRequest, 41203, SLANG_SEVERITY_DISABLED);
```

Is this expected behavior or a bug?

**Comment by csyonghe** [comment]
There is the new `DisableWarning` compiler option, can you try that instead?

**Comment by westlicht** [comment]
Will do, thanks

**Comment by bmillsNV** [comment]
Closing this issue. Fixed.
