### ISSUE TITLE
Prefer vector operations over unary operations for various GLSL/SPIRV/HLSL functions

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4085]
Prefer vector operations over unary operations for `roundEven` and `isfinite`.

**Comment by jkwak-work** [comment]
`roundEven` is already covered in this PR.
https://github.com/shader-slang/slang/pull/4080/files

**Comment by csyonghe** [comment]
I went over hlsl.meta.slang and discovered these additional functions:

`asuint16`/`asfloat16` (vector version) can just be `OpBitcast`.

`f16tof32`/`f32tof16` (vector version) can be `OpFConvert(OpBitCast())`.

`rcp` vector version can be vector div.

**Comment by bmillsNV** [comment]
@jkwak-work what are you doing w/this one? Looks like low priority. Should we push it out of the current iteration?

**Comment by jkwak-work** [comment]
I think this is pretty easy one.
I will give a try and see if I can get it done today.
