### ISSUE TITLE
Introduce a more refined notion of "profiles"

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#410]
The compiler currently has a few different notions of "profiles" that aren't implemented very completely:

* There are the front-end enumerations wrapped up in the `Profile` type that correspond to what the user specifies on the command line (e.g., `-profile vs_5_1`).

* There are the front-end notions of code-generation target (e.g., `-target dxbc`) which are not quite orthogonal from the above.

* There is a back-end notion of functions being "target intrinsic" or "target specialized" that uses the fixed strings `hlsl` and `glsl`.

* There are the `__glsl_version` and `__glsl_extension` modifiers, which specify that code using a particular function requires a particular version of GLSL, or a particular GLSL extension.

There really isn't a consistent, systematic approach here, and that means that we don't actually enforce anything related to these modifiers in the way that the user would like. We should replace all of the ad-hoc methods described above with a single consistent representation.

A "profile" is conceptually a set of capabilities. When a function is tagged with a profile, we are saying that it can only be called when all of the capabilities in the set are available. When the user specifies a profile on the command line, they are saying that they want to compile under the assumption that all of those capabilities are available.

When compiling a function, we can infer a required profile (set of capabilities) by taking the union of the profiles for everything it calls/uses (types might have requirements as well...). When compiling an entry point, we will want to validate that the required profile for the entry-point function is a subset of the actual profile the user specified.

A profile (or rather, the capabilities inside a profile) might represent:

* A particular target stage (e.g., `vertex`, `fragment`, etc.)
* A shader model or feature level (e.g., `sm_4_0`, `glsl_430`)
* A target language/format (e.g., `hlsl`, `spriv`)

Profiles should be defined in the standard library, possibly with some support to hook them up to the AST classes that will represent them. A simple profile declaration would be:

```
__profile glsl;
```

This example defines the `glsl` profile to be a singleton set, with a single capability in it, that would also be named `glsl`.

We would also allow the definition of a sub-profile:

```
__profile glsl_100 : glsl;
```

This line defines the `glsl_100` profile to be a capability set that contains all of the capabilities in `glsl` as well as a new capability called `glsl_100`.

We would also allow profiles to be defined as a combination of existing profiles:

```
__profile glsl_vertex = glsl & vertex;
```

In this case, the `&` operator is going to combine requirements, which is a *union* of the underlying set representation, so that `glsl_vertex` is a set containing everything in `glsl` and everything in `vertex`.

(In an ideal world we'd also have an `|` operator on profiles, but there are reasons why that gets complicated.)

When defining a function or type, we should allow it to be restricted to a particular profile:

```
[profile(glsl_vertex)] void doSomething();
```

Multiple `[profile(...)]` attributes should be allowed on a single function, and they should more or less act like an `|` or the profiles ("my function works with these capabilities *OR* those capabilities").

When compiling a function, we should infer a "required" profile based on the operations the function performs (basically take the profile(s) of anything it uses/calls, and `&` them together). If the function also has an explicit `[profile(...)]` we should enforce that the inferred profile is a subset of the explicit profile.

When a function doesn't have an explicit profile given, the behavior probably needs to differ between "application" and "library" code:

* In application code (e.g., some user's random `.hlsl` file), the compiler should treat the function as if it were declared with the inferred profile as its explicit profile, and then proceed through the rest of compilation.

* In library code, a function without an explicit profile should be treated as using a "default" profile that was specified as part of the compile action. Errors should be generated for code that can't compile using the default profile, and which didn't have an explicit profile.

When checking an entry point, we'd check it against the profile specified on the command line for that entry point, and give an error if it requires capabilities beyond what the user specified.

The standard library should include a set of profile declarations that covers:

* Different target stages: `vertex`/`vs`, `fragment`/`fs`, etc.

* Different target platform families: `d3d`, `d3d11`, `d3d12`, `vulkan`, etc.

* Different target code formats: `dxbc`, `dxil`, `spirv`, `hlsl`, `glsl`, etc.

* Different platform-specific shader models: `sm_4_0`, `glsl_330`, etc.

* GLSL extensions: `GL_ARB_derivative_control`

* Combinations of the above: `vs_5_0`

The profile names that the user specifies via command line or API should be looked up in these standard library declarations. Different profiles might be specified by different options (e.g., `-target` vs. `-profile`, and maybe a future `-extension` option). The effective profile to use should be the `&` of the specified profiles.

One important detail in all of the above is that we should have a notion that certain profiles are "disjoint" so that they cannot be used together. For example, the compiler should recognize that `vertex & fragment` is an impossible profile. If the user writes a function that requires that profile, or specifies it on the command line, they should get an error message.

A good default behavior is that if two profiles "inherit" from a common base (but neither one inherits from the other), then they are assumed to be disjoint from one another:

```
__profile __shader_stage; // should ideally be a `private` profile in the stdlib
__profile vertex : __shader_stage;
__profile fragment : __shader_stage;
...
```

Aside: there are some similar rules for assuming disjointness in the Julia type system, and we should look into how those rules are defined.

IR functions would store the profile(s) for which they are defined. During back-end specialization of code for a particular target, we should have a profile for the chosen code generation target (which will include the chosen stage, etc.) and that should inform our choice of which version of an IR function to select. The basic rules would be:

* Dismiss any IR function definitions with requirements not in our chosen target's capabilities

* When considering two functions that are applicable (and thus represent subsets of the target's capabilities), one function is "better" than another if it requires strictly more capabilities (that is, its profile is a proper subset of the other).

**Comment by tfoleyNV** [comment]
Based on further discussion, it seems like trying to define profiles/capabilities purely in the stdlib isn't actually the best plan, since other systems need ways to access and work with them that might not want to instantiate a full AST:

* The command-line processing and API need ways to turn a string name of a capbility or version of a feature into a value they can manipulate.

* The IR needs a way to reference a capbility/version in a decoration, without having the IR stay around.

It is probably for the best to just have a single file somewhere that defines all the capabilities (both atomic and derived) that the compiler will understand (so that adding new capabilities requires modifying and rebuilding the compiler - no chance of user-defined capabilities...) and then any simple capability can be referenced by a single enumeration value (fixed size, no allocation). Determining whether one capability implies another could then be handled via data-driven routines based on tables derived from the raw declarations of the capabilities.

The existing `slang-profile-defs.h` is perhaps a starting point showing what that system could look like.

**Comment by tangent-vector** [comment]
Note that we have the `CapabilityAtom` and `CapabilitySet` types now. The next step on this issue would be to:

* expand the set of capabilities defined in that system
* allow AST declarations to be tagged with required capabilities
* introduce logic to translate the current "profiles" over to equivalent capability sets
* add semantic checking to validate that capabilities are being respected
* ensure that all the `__target_intrinsic`, etc. modifiers use capabilities instead of bare strings

**Comment by csyonghe** [comment]
Superceeded by #3371.
