### ISSUE TITLE
Derivative for `clamp(val, a, b)` does not match `max(min(val, b), a)`

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#4109]
I'd expect the derivatives for both these setups to match, but the clamp produces zero gradient when forward differentiated...

**Comment by csyonghe** [comment]
Shouldn't it be max(min(val,b),a)?

**Comment by natevm** [comment]
Yes, sorry, max(min(val, b), a)

What I am finding is that the max min pattern gives correct results, but clamp does not.

**Comment by csyonghe** [comment]
@saipraveenb25 would you take a look at this?

**Comment by saipraveenb25** [comment]
I'm not able to reproduce this result. I've tested the `float` and `float3` variants, which seem to give expected results and match the derivative of `max(min(val, b), a)`. 

Can you give me some more context for this bug? Maybe the surrounding function in which it is used? That would help us narrow the issue.

**Comment by saipraveenb25** [comment]
Closing for now after adding some tests to check for correctness. 

@natevm please re-open if the mismatch still occurs.

**Comment by natevm** [comment]
If I find a better reproducer I’ll submit an update here. I’m not able to access the code to reproduce, but I’m wondering if this might have something to do with higher order differentiation.

Thanks for the additional tests! In either case, good to have the increased coverage. 

We might also consider adding tests to cover “saturate”, which serves a similar purpose as clamp
