### ISSUE TITLE
Missing LICENSE and README.md in release assets

### ISSUE THREAD

**Issue by dg0yt** [shader-slang/slang#4117]
While reviewing the vcpkg port, I noticed that the windows and osx release assets don't include the top-level README.md and LICENSE which is present in the linux and source assets.

If license information matters, the slang-macos-dist assets also don't have it.

**Comment by chaoticbob** [comment]
Was examining the release assets to see how they'd might be used with other projects and noticed the same thing. 
The contents of the zip and tar.gz files are a bit inconsistent. I spot checked a few releases back just to make sure that the latest release wasn't a one off.

The following files contains a **README.MD** and a **LICENSE** whereas the others do not:
```
slang-*-linux-aarch64.zip
slang-*-linux-aarch64.tar.gz
slang-*-linux-x86_64.zip
slang-*-linux-x86_64.tar.gz
slang-*-linux-x86_64-glibc-2.17.zip
slang-*-linux-x86_64-glibc-2.17.tar.gz
slang-2024.1.21.1-source.zip
```

The following files are missing both **README.md** and **LICENSE**:
```
slang-*-macos-aarch64.zip
slang-*-macos-x64.zip
slang-*-win32.zip
slang-*-win64.zip
slang-*-win-arm.zip
slang-macos-dist-aarch64.zip
slang-macos-dist-x64.zip
```

At the very least, the **LICENSE** file should appear in every zip and tar.gz file.

**Comment by cheneym2** [comment]
[4:08 PM] Ariel Glasroth
To modify the Slang vcpkg loader it looks like we need to make a PR to microsoft's publicly hosted [vcpkg/ports/shader-slang at 18842caa55f4c367e3dc0c8c7d137fe24a7e881d · microsoft/vcpkg (github.com)](https://github.com/microsoft/vcpkg/tree/18842caa55f4c367e3dc0c8c7d137fe24a7e881d/ports/shader-slang)
vcpkg/ports/shader-slang at 18842caa55f4c367e3dc0c8c7d137fe24a7e881d · microsoft/vcpkg
C++ Library Manager for Windows, Linux, and MacOS. Contribute to microsoft/vcpkg development by creating an account on GitHub.

**Comment by cheneym2** [comment]
It looks like vcpkg doesn't need updating since it just downloads assets from our github release packages. The zip and tarball creation on Slang side needs fixing.

**Comment by cheneym2** [comment]
https://github.com/shader-slang/slang/blob/d5d03d1510f45f5ed7864031244713d87fc82b87/.github/workflows/release-windows.yml#L82 README is added only to source archive not binary

**Comment by cheneym2** [comment]
https://github.com/shader-slang/slang/pull/4535

**Comment by jkwak-work** [comment]
I am little confused by we have two PRs for the same issue.
It looks like what Adam did is adding the files with 7z as a part of github action.
And what Elli did is copying the files with CMake.
Do we still need both changes?
