### ISSUE TITLE
hlsl syntax 64 bit buffer and image atomics for spirv

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#4120]
I am currently porting some code to be slang from glsl for a vulkan renderer and need 64 bit image and 64 bit buffer atomics.
When i try to use interlocked ops. Example:
```hlsl
[[vk::binding(0,0)]] RWTexture2D<uint64_t> tex;

[shader("compute")]
[numthreads(1, 1, 1)]
void main()
{
    InterlockedAdd(tex[uint2(0,0)], uint64_t(0));
}
```
i get the following error:
```hlsl
SLANG [test] D:/repos/Daxa/tests/3_samples/1_mandelbrot/shaders/compute.slang(66): error 36107: entrypoint 'main' requires capability 'hlsl', which is incompatible with the current compilation target 'spirv_1_5 + compute'.
void main()
     ^~~~~~~~~~~~~~~~
D:/repos/Daxa/tests/3_samples/1_mandelbrot/shaders/compute.slang(68): note: see using of 'InterlockedAdd'
    InterlockedAdd(tex[uint2(0,0)], uint64_t(0));
    ^~~~~~~~~~~~~~
hlsl.meta.slang(7038): note: see definition of 'InterlockedAdd'
```

**Comment by ArielG-NV** [comment]
`InterlockedAdd` for 64bit types with images looks to only have a hlsl implementation:
```
[ForceInline]
void InterlockedAdd(__ref  int64_t dest,  int64_t value)
{
    __target_switch
    {
    case hlsl: __intrinsic_asm "InterlockedAdd";
    }
}
```

For now the glsl syntax variant of the operation should work as a workaround if only a spir-v target is needed: `imageAtomicAdd`.

**Comment by Ipotrick** [comment]
How would i use imageAtomicAdd in the example code i have above? I dont understand.

**Comment by ArielG-NV** [comment]
I believe the following should work: `imageAtomicAdd(tex, ivec2(0,0), uint64_t(0));`

**Comment by Ipotrick** [comment]
slang does not recognize imageATomicAdd nor ivec2. Do i need to import a specific module for this to work?

**Comment by ArielG-NV** [comment]
the compiler flag `allow-glsl` should enable GLSL syntax with HLSL syntax

**Comment by Ipotrick** [comment]
slang crashes when i try to use glsl syntax 😨

**Comment by ArielG-NV** [comment]
That is not the expected result.

**Comment by csyonghe** [comment]
`import glsl;` is another (preferred) way to use glsl flavored intrinsics. But we should look into the crash.

**Comment by ArielG-NV** [comment]
This probably should be broken into 2 issues:
1 for the crash
1 for merging glsl.meta<->hlsl.meta image atomic operations
