### ISSUE TITLE
Make slangc commandline documentation more accessible.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#4124]
- Include a link to the documentation from main README.
- Point to the documentation from the intro page of the user guide.
- Add more examples on how to use the commandline tool.

**Comment by cheneym2** [comment]
* Point to the documentation from the intro page of the user guide.

In order to include the slangc command-line options to the user guide introduction, the slangc application itself needs to be mentioned.

My WIP change doesn't yet add a link to slangc command-line from the user-guide intro page.

**Comment by cheneym2** [comment]
The relationship between these pages is muddy:

https://shader-slang.com/slang/user-guide/compiling.html#command-line-compilation-with-slangc
https://github.com/shader-slang/slang/blob/master/docs/command-line-slangc.md
https://github.com/shader-slang/slang/blob/master/docs/command-line-slangc-reference.md
