### ISSUE TITLE
Document all capability atoms and profiles.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#4125]
We need a reference chapter in the user guide to document all supported capability atoms and their meanings.

Start a chapter at the end of user guide with the hierarchy "Reference -> Capability Profiles"

**Comment by ArielG-NV** [comment]
Discussion from another issue about this topic:

> @ArielG-NV , do we have a way to dump the name strings of profiles?
> As far as I can see, there isn't a way to do it currently.

There currently is no way todo this.

> Since there are a lot of profile names, I don't think we can list all of them on the document.
> We should refer to a command-line option that can print out all the available profile name strings.

I believe we could do both options.

The idea I have in mind for documenting every capability/profile:
1. inside `tools\slang-capability-generator\capability-generator-main.cpp` we could add logic to require a `///` comment above the line with the definition of a capability. 
2. store this string inside `slang\build\source\slang\capability\slang-generated-capability-defs-impl.h`.
3. Add build step to Slang (or CI) to autogenerate a user-doc with all capabilities using `slang\build\source\slang\capability\slang-generated-capability-defs-impl.h`
4. output the auto-generate code from '.3' as a a command-line output with slangc if `slangc -help capabilities` is added (or something similar)

Related issue: #4125

**Comment by csyonghe** [comment]
Parsing and storing the comments is a good idea, but for now let's just make sure the comments are in place first.
