### ISSUE TITLE
Support `-fvk-use-dx-layout`.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#4126]
We already have `-force-glsl-scalar-layout` that causes all buffers to follow the scalar layout in the resulting spirv. We also need `-fvk-use-dx-layout` to make them follow the dx layout.

**Comment by csyonghe** [comment]
From Hai:

Here's all the resources that I could scrounge up for this.

For DXC, the selection for the layout rules begins here based on what options were passed in:
[https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/lib/SPIRV/SpirvEmitter.cpp#L605-L609](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FDirectXShaderCompiler%2Fblob%2Fmain%2Ftools%2Fclang%2Flib%2FSPIRV%2FSpirvEmitter.cpp%23L605-L609&data=05%7C02%7Cyhe%40nvidia.com%7C1abcdaf37e554073f1da08dc6ee38239%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638507170692078715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=W5vTLZW%2BcJJyPn0vJ3dwRGNJqJWu0%2FRZePtyMJKfbX8%3D&reserved=0)

Looking through this reminded me it was actually the FXC rules that we had to follow, so that's why the enums are prefixed with Fxc.
cbuffer/ConstantBuffer/tbuffers all use the FxcCTBuffer rules.
StructuredBuffer/RWStructuredBuffer + all their variants use the FxcSBuffer rules.
Amplification shader payloads also use FxcSBuffer rules.

The rules (FxcCTBuffer and FxcSBuffer) are spelled out and implemented in this file:
[https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/lib/SPIRV/AlignmentSizeCalculator.cpp#L245-L261](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FDirectXShaderCompiler%2Fblob%2Fmain%2Ftools%2Fclang%2Flib%2FSPIRV%2FAlignmentSizeCalculator.cpp%23L245-L261&data=05%7C02%7Cyhe%40nvidia.com%7C1abcdaf37e554073f1da08dc6ee38239%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638507170692088742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YU7QgTj1iiNqTrvFwrW5oT3WRQv2AOxBX9fEuWB2iJ0%3D&reserved=0)


DXC's documentation also spells out these rules although it takes a bit parsing:
[https://github.com/microsoft/DirectXShaderCompiler/wiki/Buffer-Packing](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FDirectXShaderCompiler%2Fwiki%2FBuffer-Packing&data=05%7C02%7Cyhe%40nvidia.com%7C1abcdaf37e554073f1da08dc6ee38239%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638507170692096153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=R7DV5Z6ARTqAUBwuqaosk4oC5ThhlA%2FDoN7hejF3gR4%3D&reserved=0)

Microsoft's documentation on HLSL packing rules is pretty simplistic:
[https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-packing-rules](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fdirect3dhlsl%2Fdx-graphics-hlsl-packing-rules&data=05%7C02%7Cyhe%40nvidia.com%7C1abcdaf37e554073f1da08dc6ee38239%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638507170692102772%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=C1EoMZl6hM60dQwm2Iqfh4t1J08OGrUQHeiV3DgxQG8%3D&reserved=0)


This is a pretty awesome visualizer that someone wrote to illustrate the HLSL Constant Buffer Packing Rules:
[https://maraneshi.github.io/HLSL-ConstantBufferLayoutVisualizer/](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaraneshi.github.io%2FHLSL-ConstantBufferLayoutVisualizer%2F&data=05%7C02%7Cyhe%40nvidia.com%7C1abcdaf37e554073f1da08dc6ee38239%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638507170692111970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=fLDdX2hdAZ%2FFTxnmgvXwdyM3AWeMA5dAkHvmZbZPMSw%3D&reserved=0)

**Comment by bmillsNV** [comment]
Not sure if we've got capacity for this one in Q2 or not. Marking for Q2 for now. Need to do another scrub of issues in Q2 to see how this one ranks.

**Comment by bmillsNV** [comment]
Marking for Q3. Planning to tackle this request in July to support Siggraph.

**Comment by bmillsNV** [comment]
@ArielG-NV  can you take a look at this one?

**Comment by ArielG-NV** [comment]
I can take a look at this issue
