### ISSUE TITLE
reverse while loop will could cause issue when loop inversion is turned off

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4153]
This is probably not a real issue. But when we  turn the loop inversion off, 
this test will crash on Vulkan:
tests/autodiff/reverse-while-loop-2.slang

technically, turning off loop inversion should not crash anything. But maybe because our loop reversion is assuming the loop inversion in default, so the unexpected behavior is expected.

Open this issue to remind us that we should fix the https://github.com/shader-slang/slang/issues/4151 as soon as possible.

**Comment by saipraveenb25** [comment]
Looks like a direct SPIRV emit issue. The error goes away if we use `-emit-spirv-via-glsl`.
