### ISSUE TITLE
Cannot disable warning 41203

### ISSUE THREAD

**Issue by skallweitNV** [shader-slang/slang#4155]
Falcor has many reinterpret casts from a large to a smaller struct and we therefore get many warnings like:
```
warning 41203: reinterpret<> into not equally sized types: '' with size '4' casted into 'DynamicType' with size '0'
```

Disabling the warnings with either `spOverrideDiagnosticSeverity` or through the "new" `CompilerOptionEntry` mechanism doesn't seem to work.

**Comment by csyonghe** [comment]
This is now fixed with PR #4156. You need to add the setting in `createSlangCompileRequest`.
