### ISSUE TITLE
Capability System: adjust the capabilities of all versions and profiles to include implied extensions 

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4164]
currently version/profile capabilities are not correct. Capabilities like `GLSL_450` should be defined with implied extensions.

Furthermore, `glsl450` profile should be defined with capability `GLSL_450`

**Comment by csyonghe** [comment]
Currently we use _GL_EXT_FOO to represent the real glsl extension EXT_FOO,
L then we also define a user facing alias GL_EXT_FOO = _GL_EXT_FOO|_SPV_EXT_FOO to mean either the glsl extension or the equivalent spv extension depending on whether the user is targeting glsl or spirv. This setup makes it possible for our users to specify:
-profile spirv+GL_EXT_FOO and we will be able to resolve it to spirv+SPV_EXT_FOO.

We should maintain this setup. I was simply asking us to define GLSL_450 profile such that it implies all extensions for 450:
def glsl450:glsl440, _GL_EXT_FOO, _GL_EXT_BAR, ...

This means that when the user has specified -profile glsl450 they will be able to use ext_foo without having to explicitly specify it again even in restrictive mode. But if they are targeting 430 they will need to do -profile glsl430+_Gl_EXT_FOO.

What is important here is that the canonical representation of glsl450 will contain the _GL_EXT_FOO atom. But we can also know that the atom is implicitly inferred by seeing that the ext atom does not exist in the compacted set.
