### ISSUE TITLE
Capabilities System: If a profile is set and implicitly upgraded, we should emit a warning.

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4165]
Currently if we do: `-profile _GLSL_150` we won't error if we implicitly upgrade the capability to `_GLSL_400` (or if adding extensions). This should be a warning.

**Comment by csyonghe** [comment]
To clarify the behavior: we should introduce a restrictive mode enabled with -restrictive-capability-check option. In this mode, we diagnose an error whenever an upgrade is needed.

**Comment by ArielG-NV** [comment]
Question about behavior: 
* No warning or error will be thrown if a user does not set a CompilerOptionName::Capability or CompilerOptionName::Profile. 
    * Else a user clearly not trying to use capabilities beyond the convince features will be subject to hundreds of warnings/errors.
