### ISSUE TITLE
How to link together generated CPP and CUDA code

### ISSUE THREAD

**Issue by aroidzap** [shader-slang/slang#4171]
I'm trying to link together CPP and CUDA code. I tried to wrap generated CPP and CUDA code in different namespaces, but this does not work. Using namespaces inside slang (depending on target platform) also does not work, because __extern_cpp ignores namespaces. There are also macro redefinition issues, when trying to use preludes as headers (where StructuredBuffer and other things are defined).

Is my only option is to build my app separately for CPP and CUDA, or does anyone have some idea how to link CPP and CUDA together to have runtime based CUDA implementation?

**Comment by csyonghe** [comment]
I think the cleanest way would be to build separate libraries and have the libraries interact with each other through a clearly defined C interface.

**Comment by aroidzap** [comment]
But basically I need at least to build two separate dynamic libraries (one for CUDA and one for CPU) and load them dynamically during runtime based on some switch for example. Because due to the symbol clashes I won't be able to link statically those two separate libraries generated from Slang source.

What about some slang compiler option to prefix all symbols with some namespace (or at least some prefix), so we can statically link together multiple implementations generated from the same slang source?

It could be useful to link together CUDA and CPU implementation or just multiple implementations with some -D flags passed to the Slang compiler.

**Comment by aroidzap** [comment]
Also it is not currently possible to include both `slang-cpp-prelude.h` and `slang-cuda-prelude.h` in a single file, to use them as headers for internal types like `StructuredBuffer`.

**Comment by csyonghe** [comment]
Cpp and Cuda are treated like distinct targets, and we have not architected the preludes and the compiler to support using them in a single program. It may be possible to rename the preludes and use some name mangling logic to avoid the name clashes, but it is going to be a pervasive and potentially breaking change that I am not sure we are ready to make right now.

Is it possible for you to wrap the entire generated source inside a namespace in your application?

**Comment by aroidzap** [comment]
There were some issues with wrapping the code in a namespace. I would probably have to add some code wrapper with a custom interface and make all other Slang symbols hidden using --visibility=hidden.

It would be nice in a future, if we can have possibility to link multiple targets together and create single app that can switch backend based on the available hardware.

**Comment by csyonghe** [comment]
It should be possible to have both cpu and CUDA code in your application if you use CUDA driver api to load the recompiled PTX modules, right? That way you won't have any c++ linker problem.
