### ISSUE TITLE
Capability System: Redesign how failed capability providence is described to a user

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4172]
Currently in the capabilities system, erroring once we reach a stage of checking EntryPoints<->compileTarget (Diagnostics::entryPointUsesUnavailableCapability) produces assumptions of what went wrong.

These assumptions assumes based on providence of a single Decl that any incompatible capability may be the problem. This erroring works well when the problem is straight-forward or the function has little capabilities defined. When the problem is within a function with many overlapping capabilities the current "providence" tracking provides little assistance in erroring due to only tracking a single "providence". 

One solution to this would be to redesign the approach to store UIntSets of `callee` and `parent` functions that remove a target
* It would be faster to save debug data but slower to emit debug information.

**Comment by ArielG-NV** [comment]
example of why this needs fixing:
```
#4443 should also help solve this problem.
```

**Comment by jkwak-work** [comment]
I think this issue needs a "repro steps".
Once we have a repro steps, anybody can pick it up and work on it.
And we can also verify the fix later by running the repro steps again.

**Comment by ArielG-NV** [comment]
Repro: #4443
