### ISSUE TITLE
Lower CMake version requirement

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4194]
**Problem description**
For the better user experience, it will be nice to support an older version of CMake.
It is not too hard to upgrade CMake but it will be better if everything works out of the box.

Currently Slang requires CMake version 3.25.
This version is available for most of platforms, if not all.
I was able to upgrade to 3.26 even on Raspberry pi.

But most of Linux distributions use an older version of CMake by default.

**Goal**
We need to figure out what version of CMake could be a reasonably older version we can support.
If we cannot lower, we need to understand what prevents us from lowering the version requirement.

**Comment by csyonghe** [comment]
CMake 3.25 is the first version that supports --workflow. We do use --workflow in our cmake configuration so it is probably worth to require 3.25. Closing the issue now.
