### ISSUE TITLE
Fix memory leak in slang.dll

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4208]
When we run "slangc.exe", `_CrtDumpMemoryLeaks()` reports the memory leaks on Windows platform.
The memory leak has been reported for a while but it has been ignored.
It is because the messages are printed to the "debug output", which is visible only if you ran slangc.exe from VisualStudio.

Memory leak is never a good thing and we should fix it.
We should also setup CI to prevent it from happening in the first place.

**Comment by jkwak-work** [comment]
When the change #4210 is merged, the issue can be reproduced by just running slangc.exe.
Here is an example,
```
$ build/Debug/bin/slangc.exe
Detected memory leaks!
Dumping objects ->
{1319712} normal block at 0x0000021ACE6BE010, 48 bytes long.
 Data: <`\&             > 60 5C 26 C4 1A 02 00 00 00 00 00 00 00 00 00 00
{3949} normal block at 0x0000021AC4265C60, 48 bytes long.
 Data: <          k     > 00 00 00 00 00 00 00 00 10 E0 6B CE 1A 02 00 00
{3948} normal block at 0x0000021AC425F420, 32 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00
{3947} normal block at 0x0000021AC4201C50, 1024 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD
{3921} normal block at 0x0000021AC420B4C0, 904 bytes long.
 Data: <X a             > 58 D1 61 F5 FA 7F 00 00 01 00 00 00 00 00 00 00
{234} normal block at 0x0000021AC41DBED0, 1024 bytes long.
 Data: < 7              > 80 37 92 F5 FA 7F 00 00 D4 A6 A7 F5 FA 7F 00 00
{215} normal block at 0x0000021AC41DBA90, 1024 bytes long.
 Data: <                > 10 AC 91 F5 FA 7F 00 00 C0 BE A7 F5 FA 7F 00 00
{200} normal block at 0x0000021AC41DB650, 1024 bytes long.
 Data: <                > FC A6 91 F5 FA 7F 00 00 B4 A6 A7 F5 FA 7F 00 00
{190} normal block at 0x0000021AC41DB210, 1024 bytes long.
 Data: <                > E0 A1 91 F5 FA 7F 00 00 D0 A6 A7 F5 FA 7F 00 00
{169} normal block at 0x0000021AC41DADD0, 1024 bytes long.
 Data: <                > 90 9B 91 F5 FA 7F 00 00 B4 A6 A7 F5 FA 7F 00 00
{168} normal block at 0x0000021AC41DAB80, 528 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 90 AB 1D C4 1A 02 00 00
{163} normal block at 0x0000021AC41BF030, 128 bytes long.
 Data: <                > 00 00 00 00 00 00 00 FC FF 00 00 00 00 00 00 00
{161} normal block at 0x0000021AC41BF7B0, 128 bytes long.
 Data: <                > FC 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Object dump complete.
```
The message above shows 13 objects were still using memory when slangc.exe was about to exit.

**Comment by csyonghe** [comment]
We can use _crtBreakAlloc to track down where those allocations are made. I suspsect they may just be the global dictionary used in our profiler.

**Comment by expipiplus1** [comment]
Valgrind gives significantly more useful output that this also

**Comment by jkwak-work** [comment]
I think ASAN will be a good method to check this type of problems and Venki was able to use it.

@venkataram-nv , can you describe how you enable it?
We should also consider running ASAN on our CI if it isn't too slow.

**Comment by venkataram-nv** [comment]
We can enable ASAN through the CMake option `SLANG_ENABLE_ASAN`. A problem that I had with this though, was that in `cmake/CompilerFlags.cmake` it would ignore the `-fsanitize=address` flag because it supposedly was not supported by the compiler. What I did to fix this was to skip the `check_cxx_compiler_flag` check on line 29. Interestingly even with ASAN there are no leaks reported, and I believe its because ASAN cannot track leaks with global variables.
