### ISSUE TITLE
Create the breakdown profiling of slang

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4209]
Currently we only profile the total compile time and downstream compile time of slang. But we really need a way to have a breakdown the front-end, link, back-end compile time.

Also, we noticed that there is performance regression on the latest slang version comparing to v0.24.x, so we need to back-port the profiler to the older version such that we can have a reliable comparison.

**Comment by jkwak-work** [comment]
There are two command-line arguments for slangc.exe: `-report-downstream-time` and `-report-perf-benchmark`.
It sounds like this task will be to improve `-report-perf-benchmark`, is it?
Or do we need a new compiler option for this task?

**Comment by jkwak-work** [comment]
Just FYI, here is how it looks like when I used `-report-perf-benchmar`,
```
$ build/Release/bin/slangc.exe -report-perf-benchmark tests/glsl-intrinsic/intri
nsic-basic.slang -allow-glsl
(0): note 103: compiler performance benchmark:
loadStdLib:     1       198
checkAllTranslationUnits:       2       1039
generateIRForTranslationUnit:   2       155
performMandatoryEarlyInlining:  7       9

Type Dictionary Size: 2575
```
