### ISSUE TITLE
Return ptr of new Object out of Slang DLL

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#4229]
```c#
export __extern_cpp Ptr<PointLight<float>> __create() {
    Ptr<PointLight<float>> light = new PointLight<float>();
    return &light;
}
```
When I do this I get `explicit conversion from 'Ptr<Ptr<PointLight<float>>>' to 'Ptr<PointLight<float>>' is possible`

```c#
export __extern_cpp Ptr<PointLight<float>> __create() {
    Ptr<PointLight<float>> light = new PointLight<float>();
    return light;
}
```
When I do it the correct way I get `expected an expression of type 'Ptr<PointLight<float>>', got 'PointLight<float>'`

For some reason the Ptr type gets lost when doing the `correct` thing

So the question is, is this an error or am I doing something wrong. How can I allocate a heap object in a Slang DLL and return it to the caller?

**Comment by csyonghe** [comment]
The type of `new PointLight<float>` is `PointLight<float>`, and is valid only when `PointLight` is a `class`.

A value of class type is always by-reference, so there is no need to wrap it with `Ptr<PointLight<float>>`.

**Comment by csyonghe** [comment]
Note: all of these C++/COM features are highly experimental and incomplete. At this time we don't have the capacity to provide support around these functionalities. The only intended way to return a heap allocated object from a Slang DLL is to expose a COM interface, define a class that implements the interface, and define a function that returns the COM interface, where inside the function you return an instance of the class. See `tests\cpu-program\class-com.slang` for more details.

**Comment by fknfilewalker** [comment]
What I am doing right now is that I create a byte array outside slang and pass it in via ptr and then fill it with the data but the com interface way sounds way better. Do you know why the macOS bins are missing the slang-rt lib?

Is it possible to have a templated COM interface. When I do that I get
`No type conformances are found for interface 'IDifferentiable'. Code generation for current target requires at least one implementation type present in the linkage.` Does this work when I provide type conformances?

**Comment by fknfilewalker** [comment]
There is another problem
I can write `return new PointLight();`  and it works but when I save it to a var and return that it does no longer work, like
```c#
export __extern_cpp Light __create() {
    PointLight light = new PointLight();
    return light;
}
```

**Comment by fknfilewalker** [comment]
I got everything working with the __requirePrelude and __intrinsic_asm feature
