### ISSUE TITLE
Fix CTS tests failures.

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4233]
We created a CTS waiver list to skip those already known failure tests, and this issue is used to track for the fix.
The waitver list can be checked here: https://github.com/shader-slang/VK-GL-CTS/blob/main/test-lists/slang-waiver-tests.xml

**Comment by jkwak-work** [comment]
@kaizhangNV , I cloned VK-GL-CTS repository.
But I cannot figure out how to locally run the test.
I think we have a document about how to run it but I cannot figure out where it is.
Can you give me some help on how to run it locally.

I also like to know how to trigger CI so that I can run a test manually.

**Comment by jkwak-work** [comment]
I found the instruction of how to run the test,
https://github.com/shader-slang/VK-GL-CTS/releases/tag/VK-GL-CTS_WithSlang-0.0.3-win64

**Comment by jkwak-work** [comment]
It appears that some of the tests are failing if I enable the validation layer,
```
set SLANG_RUN_SPIRV_VALIDATION=1
```
We probably should enable this for CTS CI too.

**Comment by jkwak-work** [comment]
With the integer texture support, CTS can pass 32% of the skipped tests but not all.
280 tests are passing and 583 tests are still failing.
```
  Passed:        280/863 (32.4%)
```
I will see what they are failing for.

**Comment by jkwak-work** [comment]
When the validation check is enabled, the failing 583 tests falls into one of four types of validation errors,

```
error: line {num}: If OpTypeBool is stored in conjunction with OpVariable, it can only be used with non-externally visible shader Storage Classes: Workgroup, CrossWorkgroup, Private, Function, Input, Output, RayPayloadKHR, IncomingRayPayloadKHR, HitAttributeKHR, CallableDataKHR, IncomingCallableDataKHR, or UniformConstant

error: line {num}: OpEntryPoint Entry Point <id> '{num}[%main]'s callgraph contains function <id> '{num}[%main]', which cannot be used with the current execution model:

error: line {num}: Opcode ImageQueryLod requires one of these capabilities: ImageQuery

error: line {num}: [VUID-StandaloneSpirv-Flat-{num}] Flat decoration on target <id> '{num}[%in{num}]' storage class must be Input or Output
error: line {num}: [VUID-StandaloneSpirv-Flat-{num}] Flat decoration on target <id> '{num}[%out{num}]' storage class must be Input or Output
error: line {num}: [VUID-StandaloneSpirv-Flat-{num}] Flat decoration on target <id> '{num}[%vtx_out_coords]' storage class must be Input or Output
error: line {num}: [VUID-StandaloneSpirv-Flat-{num}] Flat decoration on target <id> '{num}[%vtx_out_result{num}]' storage class must be Input or Output
```

**Comment by jkwak-work** [comment]
I created two more issues to address the remaining tests.
#4357, #4356

**Comment by jkwak-work** [comment]
[280 tests are re-enabled](https://github.com/shader-slang/VK-GL-CTS/pull/6), and the [CTS test last night](https://github.com/shader-slang/slang/actions/runs/9478325376) was passing.
