### ISSUE TITLE
Add documentation for Metal target

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang#4262]
Support for Metal should be documented as in prototype stage. Documentation must be added to docs/user-guide/09-targets.md to indicate that Metal is available as a work in progress (e.g. see note below CUDA and OptiX section). Additionally, it would be nice to document the format of the profile strings used by findProfile() in the appropriate places in docs/user-guide/08-compiling.md

**Comment by swoods-nv** [comment]
Want to land before SIGGRAPH, but not critical for EOQ2

**Comment by swoods-nv** [comment]
There's more detailed documentation needed here than I'd realized-- I'm going to need one of the authors of the Metal backend to assist. @ArielG-NV @jkwak-work @csyonghe

**Comment by ArielG-NV** [comment]
> it would be nice to document the format of the profile strings used by findProfile() in the appropriate places in docs/user-guide/08-compiling.md

We also should allow a [user to choose the metal version being compiled with](https://github.com/shader-slang/slang/issues/4543)

**Comment by jkwak-work** [comment]
> > it would be nice to document the format of the profile strings used by findProfile() in the appropriate places in docs/user-guide/08-compiling.md
> 
> We also should allow a [user to choose the metal version being compiled with](https://github.com/shader-slang/slang/issues/4543) if we are to add `findProfile` documentation for all targets (otherwise profiles are quite useless with `metal`)

@ArielG-NV , do we have a way to dump the name strings of profiles?
As far as I can see, there isn't a way to do it currently.

Since there are a lot of profile names, I don't think we can list all of them on the document.
We should refer to a command-line option that can print out all the available profile name strings.

**Comment by ArielG-NV** [comment]
> @ArielG-NV , do we have a way to dump the name strings of profiles?
> As far as I can see, there isn't a way to do it currently.

There currently is no way todo this.

> Since there are a lot of profile names, I don't think we can list all of them on the document.
> We should refer to a command-line option that can print out all the available profile name strings.

I believe we could do both options.

The idea I have in mind for documenting every capability/profile:
1. inside `tools\slang-capability-generator\capability-generator-main.cpp` we could add logic to require a `///` comment above the line with the definition of a capability. 
2. store this string inside `slang\build\source\slang\capability\slang-generated-capability-defs-impl.h`.
3. Add build step to Slang (or CI) to autogenerate a user-doc with all capabilities using `slang\build\source\slang\capability\slang-generated-capability-defs-impl.h`
4. output the auto-generate code from '.3' as a a command-line output with slangc if `slangc -help capabilities` is added (or something simmilar)

**Comment by swoods-nv** [comment]
Metal documentation is still very incomplete.
