### ISSUE TITLE
Refactor of obfuscateModuleLocs

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4265]
We found out that `obfuscateModuleLocs` cause the performance regression by 30 times on Windows. So we will need to refactor this function.

This function not is optional selected by the input parameter "-disable-source-map" implemented by #4260 .

And some initial refactor is done by change: #4261. 

We will need further refactor to this function.

**Comment by bmillsNV** [comment]
Not priority for now. Shifting to Q4 for now.

**Comment by bmillsNV** [comment]
Closing this one. No substantial gains w/this refactor.
