### ISSUE TITLE
`Sampler2D` crashes the compiler when targeting host

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#4267]
Things like
```csharp
Sampler2D sampler;
```
```csharp
Sampler2DArray samplerArray;
```
crash the compiler when targeting the host
e.g., `slangc.exe __.slang -o out.cpp`

```csharp
Texture2D texture;
```
```csharp
Texture2DArray textureArray;
```
on the other hand works

Slang version 2024.1.20

**Comment by csyonghe** [comment]
I think we are simply missing the implementation for combined texture samplers when targeting cpp/cuda.

**Comment by jkwak-work** [comment]
I can probably work on this next sprint.
