### ISSUE TITLE
Introduce a distinct IR-level type representation

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#427]
The current IR uses AST-level types for the types of IR values, and also uses AST-level representations like `DeclRef` as operands. This has several down-sides, at different levels of severity.

Perhaps the most serious issue is that we've ended up in a messy situation where sometimes we have to wrap up an AST-level value (like a `DeclRef`) in an `IRValue` to be able to pass it as an operand (e.g., to a `specialize` call), and then in other cases we have to wrap up an IR-level value (like a witness table) as an AST-level value so that we can construct a specialized AST-level type. This ends up meaning that there are multiple representations of the same information that the IR needs to be ready to handle (e.g., both IR witness tables and AST-level `SubtypeWitness` values).

A related issue is that we've realized several times that the IR could be a lot simpler if it encoded type-level operations more directly. In particular, the `specialize` operation should directly take the type-level arguments to the generic to be specialized (rather than a single decl-ref that encodes those arguments), and IR-level generics should have explicit IR-level type parameters. Achieving this would require being able to treat types as IR values, which would exacerbate the problems above.

Next down the chain is the memory-management side of things, where because the AST-level types and decl-refs require reference-counting, we end up having to store reference-counted pointers in IR nodes, which forces us to allocate them as C++ objects with destructors, and carefully free them when we are done (rather than just allocate them from a simple pool).

Finally there are some basic aesthetic objects to having the IR and AST representations mixed together. I'm listing this last because I think this is not a good enough reason on its own to pursue any ambitious splitting up of the representations.

At a high level, my understanding of the goal here is as follows:

* The type of an `IRValue` should be an `IRType`, which is itself an `IRValue` (so that types have full use-def information)
  * In fact, the type of an `IRValue` should probably be stored as an `IRUse` itself, so that the type of an instruction is an implicit "operand -1" - which means that all `IRValue`s will be `IRUser`s

* Generics should be encoded more explicitly in the IR. At the very least type and witness-table parameters should be `IRValue`s

* The `specialize` instruction should directly take the types, witness tables, etc. to be used as arguments

* IR witness tables should be able to contain `specialize` instructions, and not just entries. This *probably* means that witness tables either are (or hold) basic blocks, and their entries become instructions

* Type legalization will probably work entirely on the level of IR types

* The role of a "decl-ref" in the IR is largely subsumed by values that either point to the function/type/whatever in question, or to a `specialize` instruction in the generic-with-arguments case.

I *think* that all of the above is pretty much what we are agreed on, and I will submit distinct comments for the stuff that is just my opinion on how best to proceed.

**Comment by tfoleyNV** [comment]
Now that I've gotten the basic covered, I wanted to go over the stuff that is just my opinion (or more open-ended questions):

### Everything should be an instruction.

We are already going to need to support more flexibility in where instructions can appear. E.g., we need to allow `specialize` instruction to appear inside witness tables, and if we are going to be able to call `specialize`, we also need to be able to do other type level computation so that we can specialize something to `vector<T,N+1>` (which involves computing `N+1` at the type level). Generics require similar capabilities, and I suspect that the presence of global generic type parameters means we've need to support `specialize` at the global scope too.

At that point I'd claim there is almost no benefit to having a distinction between instructions and other IR values, and we should instead say that *everything* is an instruction, where every instruction has a parent and prev/next siblings. At that point we might decide that the parameters of a block are just ordinary instructions at the start of the block (rather than a distinct linked list), so that we can have a unified notion of a "parent instruction" that has a list of child instructions (and zero operands). Blocks, functions, and the module itself would all be parent instructions.

When building the IR, we'd probably want to do some careful value numbering for things like types, so that when we construct something like a `specialize` instruction, we place it inside of the outer-most parent where it is legal (e.g., float it up to global scope if all it depends on are globals; float it up to the body of a generic if it depends on generic parameters, but nothing else, etc.).

### Instructions should be fully defined by their operands whenever possible

Each basic type should get is own opcode, rather than hiding a `BaseType` field inside the IR value. Instructions that represent vector/matrix types should have ordinary IR operands for the base type, element count, etc.

Ideally, there should only be a small fixed set of instructions that include "extra" data not present in their operand list: literals, parent instructions, ... and maybe that is it.

### Should vector/matrix/array/etc. types be constructed by their own ops, or via `specialize`?

I don't have a strong opinion here, but we either need to have dedicated ops for these (and they had better take full `IRUse` operands for element type/count as described above), or there should be a single value representing the abstract generic type and then actual vector/matrix/array types are represented as `specialize` calls on that generic. (So you'd recognize a vector type as a `specialize` that specializes the `vector` generic).

It is probably going to be easier to read the IR if we give these cases real opcodes of their own, but then that starts to lead down the road of whether every resource type gets its own opcode or if we represent some of them as `specialize` calls to what mount to ordinary `struct` types in the standard library...

An important intersection of the above two things is how we handle resource types. Right now the AST type system has this "flavor" stuff which would either need to be encoded as distinct opcodes for different resource types, or as one ore more additional operands to the `TextureType` instruction, which encode the same information.

### The AST and IR representations should be isomorphic when possible

In the far-flung future, I'd really like it if we had a single enumeration that defined all the opcodes we support, and then the AST and IR are just two different representations using the same set of opcodes. The main difference at that point would be that the AST does not include use-def information, while the IR does.

What this means for the IR type system is that I ideally want us to have the exact same class hierarchy rooted at `Type` and at `IRType`, just differing in representation (and then I'd really like it if we can generate them from the same description).

This is me getting *way* ahead of myself, though.

**Comment by csyonghe** [comment]
I agree with everything here. Making both front-end and IR types generated from a single meta definition seems challenging. For now I will probably just make them duplicate copies and figure out everything else.

**Comment by csyonghe** [comment]
For Vector/Matrix/Array and all the resource types, I plan to make them separate ir op codes, as they are represented in the current front-end type system. Will need to see if that is the right decision.

**Comment by csyonghe** [comment]
And for memory allocation, if our IR type system relies on virtual function tables, we still need to make sure we call their constructors even if we may get by with not calling destructors.

**Comment by tfoleyNV** [comment]
> And for memory allocation, if our IR type system relies on virtual function tables, we still need to make sure we call their constructors even if we may get by with not calling destructors.

My hope is that the IR representation becomes completely uniform, and ban any types that might need destructors from use, because there would only be three cases of instructions:

* Ordinary instructions have operands, and cleaning them up just involves cleaning up their operands (along with the base instruction stuff)

* Literal instructions have zero operands, and cleaning them up just involves the base instruction cleanup (the extra data for a literal needs to be "POD")

* Parent instructions have zero operands, and we just have special-case logic to handle their cleanup specially based on a fixed set of known opcodes that need such cleanup

**Comment by tfoleyNV** [comment]
The first pass at an IR-level type system was introduced in #481.
