### ISSUE TITLE
Remove extraneous legacy glsl target names

### ISSUE THREAD

**Issue by Raildex** [shader-slang/slang#4271]
Slang has three glsl targets:

`glsl`
`glsl-vulkan`
`glsl_vulkan-one-desc`

I would expect `glsl` to be OpenGL GLSL, but it spits out `gl_VertexIndex` instead of `gl_VertexId` for example, which is Vulkan GLSL. So all three targets are actually Vulkan GLSL

**Comment by csyonghe** [comment]
The Vulkan flavored glsl is the only GLSL we officially support. We will need a glsl-legacy to profile to support old OpenGL glsl.

**Comment by Raildex** [comment]
so why do 3 glsl targets exist then?

**Comment by csyonghe** [comment]
They exist for legacy reasons, and we need to clean them up.

**Comment by bmillsNV** [comment]
@Raildex is this a blocker for you if we don't fix this? We'll plan to clean up the targets and clarify that only the Vulkan style GLSL is supported. Any concerns with this approach?

**Comment by swoods-nv** [comment]
Proceeding with treating as cleanup.
