### ISSUE TITLE
Add support for RWStructuredBuffer with 64bit index

### ISSUE THREAD

**Issue by aroidzap** [shader-slang/slang#4274]
For the CUDA and CPP targets, the prelude-part is ok (uses size_t), but it is limited by slang having int/uint index only, see:
https://github.com/shader-slang/slang/blob/master/source/slang/hlsl.meta.slang#L4908
https://github.com/shader-slang/slang/blob/master/source/slang/hlsl.meta.slang#L4914

**Comment by bmillsNV** [comment]
@jkwak-work can you take this one? Also need to include a test case so we don't hit issues like this again.

**Comment by jkwak-work** [comment]
Yes, I will work on it
