### ISSUE TITLE
Metal: Failing compute tests

### ISSUE THREAD

**Issue by skallweitNV** [shader-slang/slang#4291]
The following tests in the `compute` category currently fail to compile with Metal.

All failing tests are disabled using:
```
//DISABLE_TEST(compute):COMPARE_COMPUTE:-slang -shaderobj -mtl
```

This should make it easy to find them.

Some of these are failing to compile due to #4288 

For reference and marking fixed tests, here is the full list:

- [x] `tests/autodiff-dstdlib/determinant.slang`
- [x] `tests/autodiff-dstdlib/dstdlib-mul-mat-mat.slang`
- [x] `tests/autodiff-dstdlib/dstdlib-mul-mat-vec.slang`
- [x] `tests/autodiff-dstdlib/dstdlib-mul-vec-mat.slang`
- [x] `tests/autodiff-dstdlib/dstdlib-sqrt.slang`
- [x] `tests/autodiff/custom-intrinsic.slang`
- [ ] `tests/autodiff/global-param-hoisting.slang`
- [x] `tests/autodiff/reverse-matrix-ops.slang`
- [x] `tests/bindings/nested-parameter-block-2.slang`
- [x] `tests/bugs/atomic-coerce.slang`
- [ ] `tests/bugs/buffer-swizzle-store.slang`
- [ ] `tests/bugs/dxbc-double-problem.slang`
- [ ] `tests/bugs/frexp-double.slang`
- [x] `tests/bugs/frexp.slang`
- [x] `tests/bugs/generic-default-matrix.slang`
- [x] `tests/bugs/generic-groupshared.slang`
- [x] `tests/bugs/generic-member-method.slang`
- [x] `tests/bugs/generic-type-duplication.slang`
- [x] `tests/bugs/gh-2959.slang`
- [x] `tests/bugs/gh-3980.slang`
- [x] `tests/bugs/interface-type-self-ref.slang`
- [x] `tests/bugs/mutating/buffer-write-dce.slang`
- [x] `tests/bugs/mutating/mutating-call-in-loop-dce.slang`
- [x] `tests/bugs/mutating/mutating-generic-method.slang`
- [x] `tests/bugs/mutating/resource-specialization-inout.slang`
- [x] `tests/bugs/negative-literal.slang`
- [x] `tests/bugs/nested-existential-dyndispatch.slang`
- [x] `tests/bugs/nested-switch.slang`
- [ ] `tests/bugs/op-assignment-unify-mat.slang`
- [x] `tests/bugs/operator-overload.slang`
- [x] `tests/bugs/specialize-existential-in-generic.slang`
- [x] `tests/bugs/ssa-loop.slang`
- [x] `tests/bugs/static-method.slang`
- [ ] `tests/bugs/type-legalize-bug-1.slang`
- [x] `tests/bugs/vec-compare.slang`
- [x] `tests/compute/array-param.slang`
- [x] `tests/compute/assoctype-nested.slang`
- [ ] `tests/compute/atomics-buffer.slang`
- [x] `tests/compute/atomics-groupshared.slang`
- [x] `tests/compute/atomics.slang`
- [x] `tests/compute/buffer-layout.slang`
- [ ] `tests/compute/buffer-type-splitting.slang`
- [x] `tests/compute/byte-address-buffer.slang`
- [x] `tests/compute/cast-zero-to-struct.slang`
- [x] `tests/compute/cbuffer-legalize.slang`
- [x] `tests/compute/column-major.slang`
- [x] `tests/compute/compile-time-loop.slang`
- [x] `tests/compute/constexpr.slang`
- [x] `tests/compute/discard-stmt.slang`
- [x] `tests/compute/entry-point-uniform-params.slang`
- [x] `tests/compute/enum.slang`
- [x] `tests/compute/frem.slang`
- [x] `tests/compute/interface-param.slang`
- [ ] `tests/compute/interface-shader-param-in-struct.slang`
- [ ] `tests/compute/interface-shader-param.slang`
- [x] `tests/compute/interface-static-method.slang`
- [x] `tests/compute/logic-short-circuit-evaluation.slang`
- [ ] `tests/compute/loop-unroll.slang`
- [x] `tests/compute/matrix-layout-structured-buffer.slang`
- [x] `tests/compute/matrix-layout.hlsl`
- [x] `tests/compute/modern-syntax.slang`
- [x] `tests/compute/mutating-and-inout.slang`
- [x] `tests/compute/mutating-methods.slang`
- [x] `tests/compute/non-square-column-major.slang`
- [x] `tests/compute/non-square-row-major.slang`
- [ ] `tests/compute/parameter-block.slang`
- [x] `tests/compute/semantic.slang`
- [x] `tests/compute/simple.slang`
- [x] `tests/compute/static-const-array.slang`
- [x] `tests/compute/static-const-matrix-array.slang`
- [x] `tests/compute/static-const-vector-array.slang`
- [x] `tests/compute/struct-make.slang`
- [x] `tests/compute/structured-buffer-of-matrices.slang`
- [x] `tests/compute/texture-get-dimensions.slang`
- [x] `tests/compute/texture-sampling.slang`
- [x] `tests/compute/texture-simple.slang`
- [x] `tests/compute/texture-simpler.slang`
- [ ] `tests/compute/texture-subscript-multisample.slang`
- [ ] `tests/compute/texture-subscript.slang`
- [x] `tests/compute/transcendental-double.slang`
- [x] `tests/hlsl-intrinsic/bit-cast-double.slang`
- [x] `tests/hlsl-intrinsic/bit-cast.slang`
- [x] `tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang`
- [x] `tests/hlsl-intrinsic/classify-double.slang`
- [x] `tests/hlsl-intrinsic/f16tof32.slang`
- [x] `tests/hlsl-intrinsic/f32tof16.slang`
- [ ] `tests/hlsl-intrinsic/matrix-float.slang`
- [ ] `tests/hlsl-intrinsic/matrix-int.slang`
- [ ] `tests/hlsl-intrinsic/scalar-double-simple.slang`
- [x] `tests/hlsl-intrinsic/scalar-float.slang`
- [x] `tests/hlsl-intrinsic/size-of/align-of-2.slang`
- [x] `tests/hlsl-intrinsic/size-of/align-of-3.slang`
- [x] `tests/hlsl-intrinsic/size-of/align-of-generic.slang`
- [x] `tests/hlsl-intrinsic/size-of/align-of.slang`
- [x] `tests/hlsl-intrinsic/size-of/size-of-2.slang`
- [x] `tests/hlsl-intrinsic/size-of/size-of-3.slang`
- [x] `tests/hlsl-intrinsic/size-of/size-of-generic.slang`
- [x] `tests/hlsl-intrinsic/size-of/size-of.slang`
- [x] `tests/hlsl-intrinsic/vector-float.slang`
- [x] `tests/hlsl/packoffset.slang`
- [x] `tests/ir/scalar-truncate.slang`
- [x] `tests/language-feature/bit-cast/struct-bit-cast.slang`
- [x] `tests/language-feature/bitfield/sizeof.slang`
- [x] `tests/language-feature/constants/constexpr-loop.slang`
- [x] `tests/language-feature/constants/static-const-in-interface.slang`
- [x] `tests/language-feature/constants/static-const-in-struct.slang`
- [x] `tests/language-feature/constants/type-cast-const.slang`
- [x] `tests/language-feature/constants/type-cast-truncate.slang`
- [x] `tests/language-feature/enums/enum-bit-ops.slang`
- [x] `tests/language-feature/enums/enum-equality.slang`
- [x] `tests/language-feature/enums/enum-generic-arg.slang`
- [x] `tests/language-feature/enums/nested-enum.slang`
- [x] `tests/language-feature/extensions/extension-method-simple.slang`
- [x] `tests/language-feature/extensions/interface-extension.slang`
- [x] `tests/language-feature/generics/arithmetic-ops.slang`
- [x] `tests/language-feature/generics/generic-interface-1.slang`
- [x] `tests/language-feature/generics/generic-interface-2.slang`
- [x] `tests/language-feature/generics/generic-value-constant-folding.slang`
- [x] `tests/language-feature/generics/iarray.slang`
- [x] `tests/language-feature/generics/partial-generic-argument-inference.slang`
- [x] `tests/language-feature/generics/struct-generic-value-param.slang`
- [x] `tests/language-feature/generics/typealias.slang`
- [x] `tests/language-feature/higher-order-functions/simple.slang`
- [x] `tests/language-feature/inheritance/derived-struct-init-list.slang`
- [x] `tests/language-feature/inheritance/struct-inherit-interface-requirement.slang`
- [x] `tests/language-feature/inheritance/struct-inheritance.slang`
- [x] `tests/language-feature/interfaces/interface-conjunction.slang`
- [x] `tests/language-feature/modules/include/main.slang`
- [x] `tests/language-feature/multi-level-break-switch.slang`
- [x] `tests/language-feature/namespaces/multiple-namespace.slang`
- [x] `tests/language-feature/namespaces/namespace-import/test.slang`
- [x] `tests/language-feature/namespaces/namespace-include/a.slang`
- [x] `tests/language-feature/namespaces/namespace-using/b.slang`
- [x] `tests/language-feature/namespaces/simple-namespace.slang`
- [x] `tests/language-feature/namespaces/using-namespace.slang`
- [x] `tests/language-feature/non-copyable-return.slang`
- [x] `tests/language-feature/operators/subscript-multi-dimension.slang`
- [x] `tests/language-feature/parameters/generic-func-param-default-arg.slang`
- [x] `tests/language-feature/pointer/const-ref.slang`
- [x] `tests/language-feature/properties/property-decl.slang`
- [x] `tests/language-feature/shader-params/entry-point-uniform-params.slang`
- [ ] `tests/language-feature/shader-params/interface-shader-param-ordinary.slang`
- [x] `tests/language-feature/simple-inline.slang`
- [x] `tests/language-feature/struct-in-func.slang`
- [x] `tests/language-feature/swizzles/matrix-swizzle-write-array.slang`
- [x] `tests/language-feature/swizzles/matrix-swizzle-write-single.slang`
- [x] `tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang`
- [x] `tests/language-feature/swizzles/matrix-swizzle-write.slang`
- [x] `tests/language-feature/swizzles/matrix-swizzles.slang`
- [ ] `tests/language-feature/types/opaque/inout-param-opaque-type-in-struct.slang`
- [x] `tests/language-feature/types/opaque/inout-param-opaque-type.slang`
- [ ] `tests/language-feature/types/opaque/out-param-opaque-type-in-struct.slang`
- [x] `tests/language-feature/types/opaque/out-param-opaque-type.slang`
- [ ] `tests/language-feature/types/opaque/return-opaque-type-in-struct.slang`
- [x] `tests/language-feature/types/opaque/return-opaque-type.slang`
- [x] `tests/optimization/func-resource-result/func-resource-result-complex.slang`
- [x] `tests/optimization/func-resource-result/func-resource-result-simple.slang`
- [x] `tests/pipeline/compute/compute-system-values.slang`

In addition, the following tests generate wrong/unexpected results:

- [x] `tests/autodiff/swizzled-store.slang.2 syn (mtl)`
- [x] `tests/autodiff/struct-this-parameter.slang.2 syn (mtl)`
- [x] `tests/autodiff/loop-init.slang.3 syn (mtl)`
- [x] `tests/autodiff/material2/diff-bwd-falcor-material-system.slang.2 syn (mtl)`
- [x] `tests/autodiff/material2/diff-falcor-material-system.slang.2 syn (mtl)`
- [x] `tests/autodiff/geometry/ray-triangle-intersect.slang.2 syn (mtl)`
- [x] `tests/autodiff/material/diff-bwd-falcor-material-system.slang.2 syn (mtl)`
- [x] `tests/autodiff/material/diff-falcor-material-system.slang.2 syn (mtl)`
- [x] `tests/autodiff-dstdlib/dstdlib-dot.slang.2 syn (mtl)`
- [x] `tests/autodiff-dstdlib/dstdlib-clamp.slang.2 syn (mtl)`
- [x] `tests/autodiff-dstdlib/dstdlib-pow.slang.2 syn (mtl)`
- [x] `tests/autodiff-dstdlib/vector-length.slang.2 syn (mtl)`
- [x] `tests/autodiff-dstdlib/dstdlib-max.slang.2 syn (mtl)`
- [x] `tests/bugs/gh-518.slang.2 syn (mtl)`
- [x] `tests/compute/write-structured-buffer-field.slang.1 syn (mtl)`
- [x] `tests/compute/func-param-legalize.slang.1 syn (mtl)`
- [x] `tests/compute/cast-zero-to-struct.slang.2 syn (mtl)`
- [x] `tests/compute/ssa-reduce-bug.slang.2 syn (mtl)`
- [x] `tests/language-feature/operators/subscript-multi-dimension.slang.2 syn (mtl)`
- [x] `tests/language-feature/constants/constexpr-loop.slang.2 syn (mtl)`

**Comment by swoods-nv** [comment]
Marking for Q2 initially, but completion within the milestone is a stretch goal.

**Comment by ArielG-NV** [comment]
*Issue Triage*

Needs further triage/fixing:

Missing implementation or wrong capabilities for matrix operations
{
* tests/hlsl-intrinsic/matrix-float.slang
* tests/hlsl-intrinsic/matrix-int.slang
}

Legalize input/output shader semantic used with struct [#4487]
{
* tests/compute/compile-time-loop.slang
* tests/compute/constexpr.slang
* tests/compute/discard-stmt.slang
* tests/compute/texture-sampling.slang
}

`intN` is invalid type for [[thread_position_in_grid]]
{
* tests/compute/buffer-type-splitting.slang
* tests/language-feature/shader-params/entry-point-uniform-params.slang
* tests/language-feature/shader-params/interface-shader-param-ordinary.slang
}

Array of buffers is not valid (?) input semantics
{
* tests/compute/loop-unroll.slang
}

Test has incorrect syntax `RWTexture2DMSArray` instead of `RWTexture2DArrayMS`
{
* tests/compute/texture-subscript-multisample.slang
}

Atomics need rework/fixes
{
* tests/compute/atomics-buffer.slang
}

Compiler silently fails
{
* tests/bugs/op-assignment-unify-mat.slang
}

Code compiles but test is disabled, unknown if they work or do not work
{
* tests\bugs\buffer-swizzle-store.slang
* tests/bugs/generic-default-matrix.slang
* tests/bugs/type-legalize-bug-1.slang
* tests/compute/column-major.slang
* tests/compute/semantic.slang
* tests/compute/texture-subscript.slang
* tests/hlsl/packoffset.slang
}

Wrong results
{
* tests/compute/column-major.slang
}

GFX backend:
param block missing
{
* tests/autodiff/global-param-hoisting.slang
* tests/compute/interface-shader-param-in-struct.slang
* tests/compute/interface-shader-param.slang
* tests/compute/parameter-block.slang
* tests/language-feature/types/opaque/inout-param-opaque-type-in-struct.slang
* tests/language-feature/types/opaque/out-param-opaque-type-in-struct.slang
* tests/language-feature/types/opaque/return-opaque-type-in-struct.slang
}

Needs no additional work but requires comment:
no double support in MSL
{
* tests/bugs/dxbc-double-problem.slang
* tests/bugs/frexp-double.slang
* tests/compute/transcendental-double.slang
* tests/hlsl-intrinsic/bit-cast-double.slang
* tests/hlsl-intrinsic/classify-double.slang
* tests/hlsl-intrinsic/scalar-double-simple.slang
}

**Comment by jkwak-work** [comment]
I think we should have an issue for each group so that they can be assigned to multiple people.

**Comment by ArielG-NV** [comment]
I did not make any issues but having 1 per group would be a good idea

**Comment by ArielG-NV** [comment]
"`matrix<int,N,M>` is not allowed in MSL" might be an exception since there was a bigger plan around emulating `matrix<>` types

**Comment by csyonghe** [comment]
Closing this issue since we have determined that the remaining issues are out-of-scope for our metal support.
