### ISSUE TITLE
"DerivativeGroupLinear" not working when compiled with glslang

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4305]
**Problem description**
The extension for a keyword, "DerivativeGroupLinear", appears to require the group size to be declared before.
```
layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in; // <== must appear first
layout(derivative_group_linearNV) in;
```
I didn't see any mention about the ordering on [the document](https://registry.khronos.org/OpenGL/extensions/NV/NV_compute_shader_derivatives.txt).
And it could be a bug in glslang.

**Repro step**
The following test can reproduce the issue.
```
//TEST:SIMPLE(filecheck=GLSL): -stage compute  -entry computeMain -target glsl
//TEST(compute, vulkan):COMPARE_COMPUTE(filecheck-buffer=BUF):-vk -compute -entry computeMain -output-using-type -emit-spirv-via-glsl

//TEST_INPUT: ubuffer(data=[0], stride=4):out,name outputBuffer
RWStructuredBuffer<float> outputBuffer;

//TEST_INPUT: Texture2D(size=4, content = one):name t2D
Texture2D<float> t2D;

//TEST_INPUT: Sampler:name samplerState
SamplerState samplerState;

// "local_size_x" must appear before "derivative_group_linearNV"
//GLSL:local_size_x
//GLSL:derivative_group_linearNV

[DerivativeGroupLinear]
[numthreads(4, 1, 1)]
void computeMain()
{
    //BUF:1
    outputBuffer[0] = t2D.Sample(samplerState, float2(0.5, 0.5));
}
```
Note that the issue cannot be reproduced when using "-emit-spirv-directly".
The issue appears to be more related to glslang.

**Goal**
Emit "local_size_x" before "derivative_group_linearNV".
Or figure out if it is a bug in glslang.

**Comment by ArielG-NV** [comment]
This issue is likely a bug with glslang validation, specification says nothing about order (https://github.com/KhronosGroup/GLSL/blob/main/extensions/nv/GLSL_NV_compute_shader_derivatives.txt). Regardless, we need a fix for the glslang bug or not because else the code won't compile.
