### ISSUE TITLE
There is no way to keep unused descriptor bindings when compiling to SpirV

### ISSUE THREAD

**Issue by gan74** [shader-slang/slang#4340]
Hi ! 

I am currently investigating porting a Vulkan codebase from glslc+spirv-opt to slang, but I am hitting a snag.

There doesn't seem to be a way to tell slang to not eliminate bindings that are not used in the shader (equivalent to `--preserve-bindings` with spirv-opt).  Dead binding elimination is still performed with `-O0`.

For example, the SpirV compiled from this:

	[[vk::binding(0)]] Sampler2D in_color; // declared, but never used
	[[vk::binding(1)]] RWTexture2D out_color;

	[shader("compute")]
	[numthreads(1, 1)]
	void main() {
		out_color[int2(0, 0)] = float4(1.0);
	}

Will have no mention of binding 0.

**Why would we ever want that?**

We use SpirV reflection to generate pipeline layouts at load time. This allows us to not have to search/create layouts per draw call. Pipeline layouts have to match descriptor sets pretty much exactly, which is fine when you can just declare the layout of your descriptor sets in a file and `#include` it where needed, but a massive problem when the compiler kills unused bindings. 

For example: A unlit shader might not read the light list from eg. descriptor set 0 binding 2. Having the binding be eliminated means that this shader will now generate a pipeline layout that isn't compatible with the descriptor set 0 (which might be frame global).

**Why not hardcode pipeline layouts on the cpp side?**

Doing this for a lot of shaders is a lot of work.

**Comment by csyonghe** [comment]
@gan74 I agree with you that the parameter binding should be stable across different pipeline/programs. We thought that just preserving the binding indices is sufficient to keep things compatible so you don't have to use different pipeline layouts, so Slang actually preserves the binding indices when binding is left implicit even without the use of explicit binding attributes.

If you are running into problems on pipeline layout compatibility because of Slang's behavior, we can change the behavior to not eliminate the  parameter declaration in the resulting spirv.

**Comment by gan74** [comment]
> We thought that just preserving the binding indices is sufficient to keep things compatible so you don't have to use different pipeline layouts.

Sadly this isn't true in Vulkan. The spec states that descriptors must match, even the unused ones. 
Even if we ignore the spec, there are platforms where all descriptor sets live in the same contiguous memory space and where missing the last binding of a set will reduce its size, and potentially shift the next set over. This can cause the GPU to read the wrong descriptor, even if the sets and binding indices are correct.

> we can change the behavior to not eliminate the parameter declaration in the resulting spirv.

That would be awesome! This need to be a flag though, as some people might rely on the current behavior for optimizations. (The current behavior should probably be the default)

**Comment by csyonghe** [comment]
I added `-preserve-params` option that will work with `-O0` to preserve the parameter declarations.

Let me know if you still run into problems.

**Comment by gan74** [comment]
I just tried it, it solves the problem!
Thank you
