### ISSUE TITLE
Validation error, "Flat decoration on target XX storage class must be Input or Output"

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4345]
**Problem description**
Regression is observed while investigating CTS failures.
The regression is from a following commit,
```
38c0bacc Fix SPIRV emit for `Flat` decoration and TessLevel builtin. (#4318)
```
When the issue is observed, the error message looks like following,
```
error: line 39: [VUID-StandaloneSpirv-Flat-04670] Flat decoration on target <id> '150[%out0]' storage class must be Input or Output
  OpDecorate %out0 Flat
```
Due to the regression, 98 CTS tests fail if the validation is enabled.
I am attaching the list of failing CTS tests for this, [ctslist.Flat.decorator.txt](https://github.com/user-attachments/files/15796169/ctslist.Flat.decorator.txt)

Note that the issue is observed with #4339.

**Repro step**
The following shader code is from the CTS test, "dEQP-VK.glsl.opaque_type_indexing.sampler.const_literal.vertex.isampler1d".
When ran, it reproduces the validation error.
```
//TEST:SIMPLE:-target spirv-asm -entry main -stage fragment -allow-glsl

#version 450
layout(set = 1, binding = 0) uniform highp isampler1D texSampler[8];

layout(location = 0) in highp vec4 a_position;
layout(location = 1) in highp float a_coords;
layout(location = 0) flat out highp ivec4 vtx_out_result0;
layout(location = 1) flat out highp ivec4 vtx_out_result1;
layout(location = 2) flat out highp ivec4 vtx_out_result2;
layout(location = 3) flat out highp ivec4 vtx_out_result3;

void main (void)
{
        gl_Position = a_position;
        gl_PointSize = 1.0;
        highp float coords = a_coords;
        highp ivec4 result0;
        highp ivec4 result1;
        highp ivec4 result2;
        highp ivec4 result3;
        result0 = texture(texSampler[3], coords);
        result1 = texture(texSampler[2], coords);
        result2 = texture(texSampler[7], coords);
        result3 = texture(texSampler[2], coords);
        vtx_out_result0 = result0;
        vtx_out_result1 = result1;
        vtx_out_result2 = result2;
        vtx_out_result3 = result3;
}
```
The validation error is following,
```
error: line 30: [VUID-StandaloneSpirv-Flat-04670] Flat decoration on target <id> '51[%vtx_out_result0]' storage class must be Input or Output
  OpDecorate %vtx_out_result0 Flat
```

**Comment by csyonghe** [comment]
This shader is not a valid fragment shader and glslang will report an error when compiled as fragment.

However it can be compiled as a vertex shader by glslang.

Compiling with slang as a vertex shader, we get a spirv that tries to use `OpImageSampleImplicitLod`, which is not allowed in vertex shader. We need to generate `OpImageSampleExplicitLod` with 0 as lod.

**Comment by jkwak-work** [comment]
Aha. Your explanation makes sense.
I will double check if CTS is compiling it as a vertex shader. But I guess it must be the case.

**Comment by jkwak-work** [comment]
Indeed, the shader was compiled for vertex shader.
The shader code is inside of the following XML tag.
```
<Section Name="vert" Description="Program: vert">
```

**Comment by csyonghe** [comment]
I am able to fix the `Flat` decorator issue, but there is a remaining issue on the `texture` call in this shader.

We will need the ability to compile `texture` call differently based on which shader stage is calling the intrinsic.

This means that we need `__target_switch` to be able to switch on different stages. This has not been implemented yet, and we need to support that first.

**Comment by jkwak-work** [comment]
> Compiling with slang as a vertex shader, we get a spirv that tries to use `OpImageSampleImplicitLod`, which is not allowed in vertex shader. We need to generate `OpImageSampleExplicitLod` with 0 as lod.

I am gonna need to create an issue for this.
