### ISSUE TITLE
`[[vk::builtin("DrawIndex")]]` is not supported.

### ISSUE THREAD

**Issue by Cons-Cat** [shader-slang/slang#4352]
https://docs.vulkan.org/guide/latest/high_level_shader_language_comparison.html

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/DrawIndex.html

The `DrawIndex` decorator is important for using `vkCmdDrawIndexedIndirectCount` ([vkCmdDrawIndexedIndirectCount.html](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndexedIndirectCount.html)). I've tried working around this absence with `[[KnownBuiltin("DrawIndex")]]` and `spirv_asm`, but so far I haven't figured out how to get this value into my shader.

Ideally imo, the semi-official syntax in vulkan.org's HLSL documentation could be supported.

**Comment by csyonghe** [comment]
You can use this function to get the builtin:
```
uint getDrawIndex()
{
    return spirv_asm
    {
        OpExtension "SPV_KHR_shader_draw_parameters";
        OpCapability DrawParameters;
        result:$$uint = OpLoad builtin(DrawIndex:uint);
    };
}
```

**Comment by csyonghe** [comment]
Closing this issue since the solution should work.

**Comment by csyonghe** [comment]
Reopening this issue, we need to properly expose the builtin through the language.
