### ISSUE TITLE
Invalid code-gen when nesting resource specialization

### ISSUE THREAD

**Issue by tomas-davidovic** [shader-slang/slang#4379]
When I have an object of this type:
```
struct Grid
{
    uint bufSize;
    StructuredBuffer<uint> buf;
};
```

which is stored inside a structure that is inside another structure like so:
```
struct GridGeo
{
    Grid grids[GRID_COUNT];

    void getGrid(uint index, out Grid grid)
    {
        grid = grids[index];
    }
};

struct Scene
{
    GridGeo gridGeo;

    void getGrid_BAD(uint index, out Grid grid)
    {
        gridGeo.getGrid(index, grid);
    }

    void getGrid_GOOD(uint index, out Grid grid)
    {
        grid = gridGeo.grids[index];
    }
};
```

Then trying to access it via `getGrid_BAD` results in invalid code (see bad.hlsl), while `getGrid_GOOD` works.
This is on 2024.1.21, and obviously a problem. (attaching the generated HLSL, the slang test code, and the falcor unit test that invokes it)

[bad.hlsl.txt](https://github.com/user-attachments/files/15825577/bad.hlsl.txt)
[good.hlsl.txt](https://github.com/user-attachments/files/15825578/good.hlsl.txt)
[test.slang.txt](https://github.com/user-attachments/files/15825579/test.slang.txt)
[test_falcor.cpp.txt](https://github.com/user-attachments/files/15825580/test_falcor.cpp.txt)

**Comment by ArielG-NV** [comment]
Update: 
problem has todo with resource specialization
This means somewhere here:
```
    specializeResourceUsage(codeGenContext, irModule);
    specializeFuncsForBufferLoadArgs(codeGenContext, irModule);
```
