### ISSUE TITLE
Slang 0.9.x doesn't copy struct correctly

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#438]
```hlsl
ParameterBlock<MyData> gData;

void main()
{
MyData d = gData;
...
}
```

Only textures/samples in MyData gets copies, not constants.

**Comment by tfoleyNV** [comment]
Closing this as "won't fix" because we'd like to focus our efforts on Slang 0.10.*. My hope is that the next major release of Falcor will be using the new Slang, and issues like this won't be a priority.

We can reopen this if I turn out to be wrong.
