### ISSUE TITLE
`SV_Targetn` semantics not properly translated in Metal

### ISSUE THREAD

**Issue by na2axl** [shader-slang/slang#4384]
Hey there,

I came across an issue when trying to do multi-target rendering (usually with a G-buffer) on Metal. Basically, my _targets_ struct looks like this:

```hlsl
struct Output
{
  float4 Diffuse  : SV_Target0;
  float4 Normal   : SV_Target1;
  float4 Material : SV_Target2;
}
```

But it generates this struct in Metal:

```metal
struct Output
{
  float4 Diffuse   [[user(SV_Target0)]];
  float4 Normal    [[user(SV_Target1)]];
  float4 Material  [[user(SV_Target2)]];
}
```

Which is wrong because Metal is expecting this instead:

```metal
struct Output
{
  float4 Diffuse   [[color(0)]];
  float4 Normal    [[color(1)]];
  float4 Material  [[color(2)]];
}
```

**Comment by swoods-nv** [comment]
Hi @na2axl - Please note that Metal support is not yet complete.
