### ISSUE TITLE
Reflection API reports 0 entry points in v2024.1.22

### ISSUE THREAD

**Issue by dubiousconst282** [shader-slang/slang#4388]
`IModule::getDefinedEntryPointCount()` and related APIs are returning 0 in the latest release / master branch. I have a minimal repro:

```cpp
#include <slang.h>
#include <slang-com-ptr.h>

int main() {
    Slang::ComPtr<slang::IGlobalSession> globalSession;
    slang::createGlobalSession(globalSession.writeRef());

    slang::TargetDesc targetDesc = {
        .format = SLANG_SPIRV,
        .profile = globalSession->findProfile("glsl_460"),
        .flags = SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY,
        .forceGLSLScalarBufferLayout = true,
    };
    slang::SessionDesc sessionDesc = {
        .targets = &targetDesc,
        .targetCount = 1,
        .defaultMatrixLayoutMode = SLANG_MATRIX_LAYOUT_COLUMN_MAJOR,
    };

    // Parsing
    Slang::ComPtr<slang::ISession> session;
    globalSession->createSession(sessionDesc, session.writeRef());

    Slang::ComPtr<slang::IBlob> diagnostics;

    const char* source = R"(

RWByteAddressBuffer output;

[numthreads(1)]
void ComputeMain(int tid : SV_DispatchThreadID) {
    output.Store(tid, 123);
}
)";
    slang::IModule* module = session->loadModuleFromSourceString("Repro", "Repro.slang", source, diagnostics.writeRef());

    Slang::ComPtr<slang::IEntryPoint> ep;
    auto res = module->findEntryPointByName("ComputeMain", ep.writeRef());
    printf("#EP: %p %08x %d\n", ep.get(), res, module->getDefinedEntryPointCount());
    
    return 0;
}
```

Output in v2024.1.22:
#EP: 00000256B939EF40 80070057 0

Output in v2024.1.21:
#EP: 000001F4D9DF0160 00000000 1

**Comment by natevm** [comment]
I don't suppose this relates at all to the flag `-fvk-use-entrypoint-name`, does it?

I usually have to add that flag into slangc in order to have entrypoint names "stick".

**Comment by dubiousconst282** [comment]
I don't think so, this happens before even linking and codegen. It's weird that looking up the entrypoint by name returns a non-null pointer, but an error result.

**Comment by csyonghe** [comment]
You can always use `findAndCheckEntryPoint` to make any function treated as an entrypoint, even when they don't have `[shader]` attribute.

**Comment by csyonghe** [comment]
It looks like a regression,. I recently touched this logic in https://github.com/shader-slang/slang/pull/4336/files#diff-81b3d1428af174af2fd0c7a42eef8d9b7e0fd4b239851472649fd51df063add6, not sure if that is the cause for the regression.

**Comment by dubiousconst282** [comment]
This was actually caused by a linking error, as I was just replacing the DLLs in my app folder 🤦. My apologies.

**Comment by TACIXAT** [comment]
If anyone else comes across this. I thought I was building as a static library (I was not), I was linking against the DLL symbols. Instead of getting a DLL not found error, it was pulling a different version from the Vulkan install.
