### ISSUE TITLE
Unsupported 1-dimensional matrix types

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4395]
HLSL has 1-dimensional matrix types that DXC accepts. Metal does not have them.

I think for on ramping it might be just to have them in case someone uses them. 

I don't know if they have specific load/store ordering dependencies. But the DXC has SPIR-V opcodes:
https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/test/CodeGenSPIRV/binary-op.arith-assign.matrix.hlsl

```
void main() {

    float1x1 a, b;
    b += a;

    {

        float1x2 c, d;
        d -= c;

        float1x3 e, f;
        f *= e;

        float1x4 g, h;
        h *= h;
    }
    
    {
        float2x1 c, d;
        d -= c;

        float3x1 e, f;
        f *= e;

        float4x1 g, h;
        h *= h;
    }    
}
```

**Comment by chaoticbob** [comment]
NOTE: This applies to other types besides float as well.

**Comment by jkwak-work** [comment]
On my first attempt, HLSL seems fine but SPIR-V validation errors it out.
```
error: line 32: Illegal number of components (1) for TypeVector
  %v1float = OpTypeVector %float 1
```
I will see how to avoid it.

**Comment by jkwak-work** [comment]
I like to leave a quick update.
HLSL seems fine with 1-dimensional matrix types.
But GLSL and SPIR-V don't support natively.
Slang will be able to handle them as a vector type; not matrix type.
