### ISSUE TITLE
Interface as `out Foo` in method of another interface leads to slang internal error.

### ISSUE THREAD

**Issue by tomas-davidovic** [shader-slang/slang#4400]

**Comment by jkwak-work** [comment]
> (0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unimplemented: assignment

It must be from [here](https://github.com/shader-slang/slang/blob/c00f461aad3d997a2e1c59559421275d6339ae6f/source/slang/slang-lower-to-ir.cpp#L7267).

I guess something might be wrong with an assignment.
We will need a repro case.

**Comment by tomas-davidovic** [comment]
I've spent like 2 hours trying to come up with a smaller example than "here is Falcor build that fails", then talked to @csyonghe about it and he told me to just put up a Falcor branch that fails (with run instructions), which is good enough as a repro if smaller one can't be made. So, that's the branch up there.
