### ISSUE TITLE
Create documentation for HLSL/GLSL onramp path

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang#4406]
I ran into trouble trying to set up a toy project that uses Slang to ingest existing GLSL shaders. It would be good to provide a section of documentation for on-ramp compatibility which covers the way to set up compiler options to read a GLSL (and presumably HLSL) shader as-is. (At least for the compilation API; it may be sufficiently documented for the command line.)

**Comment by bmillsNV** [comment]
There should be a user guide page talking about compat w/HLSL and GLSL.

**Comment by bmillsNV** [comment]
duplicate. Closing this one.
