### ISSUE TITLE
`tbuffer` or `TextureBuffer` use causes silent failure due to layout rules 

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4428]
The shader below results in `NULL` pointer access since the rules for texture buffer objects are not implemented:
```
// slang-type-layout.cpp:
LayoutRulesImpl* GLSLLayoutRulesFamilyImpl::getTextureBufferRules()
{
    return nullptr;
}
```
Call chain starts in `slang-type-layout.cpp:createParameterGroupTypeLayout()`.

This is causing a silent failure, should return an error message at the very least if not implemented.

**Shader**
```
tbuffer MyTBuffer {
    float4 tb_val;
}

float4 main() : SV_Target {
    return tb_val;
}
```

**Comment by ArielG-NV** [comment]
I suppose there are 2 problems to address here:
1. An error should be more clear here (`Error: unimplemented layout rules for object XYZ`)
2. add layout rules to `tbuffer`

**Comment by chaoticbob** [comment]
I agree. Apologies, I was going for the least amount of work needed to address the current behavior. But you're right, would be good to have the functionality.

**Comment by chaoticbob** [comment]
This also applies to `TextureBuffer` (note: it's much less used based on memory from previous experience).

**Comment by ArielG-NV** [comment]
a seperate issue was made to implement spirv and metal (significant changes required): #4435

hlsl and glsl should both work with the linked PR.
