### ISSUE TITLE
Missing SM 6.6 function: `IsHelperLane()`

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4444]
Compiling the shader below results in this error message:
```
shader.hlsl(8): error 30015: undefined identifier 'IsHelperLane'.
    if (IsHelperLane()) ret = 2.0;
        ^~~~~~~~~~~~
```

**CMD**
```
slangc.exe -target spirv -lang slang -D__spirv__ -emit-spirv-directly -profile ps_6_6 -entry main
```

Would be useful to have this function to ease porting of advanced shaders.

**Shader**
```
float4 main() : SV_Target {
    float ret = 1.0;

    if (IsHelperLane()) ret = 2.0;

    return (float4)ret;
}
```

**Comment by jkwak-work** [comment]
This looks like a good first bug for @venkataram-nv .
I am assigning it to him.

**Comment by chaoticbob** [comment]
Just FYI...for both DXC emulates this function starting in SM 6.0 and before SM 6.6.
