### ISSUE TITLE
`Load(in int Location,  out uint Status)` missing from `Buffer/RWBuffer`?

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4445]
It looks like the `status` of the `Load` for `Buffer` and `RWBuffer` might be missing:
```
hlsl.meta.slang(15024): error 29000: unable to parse target intrinsic snippet: .Load
hlsl.meta.slang(15024): error 29000: unable to parse target intrinsic snippet: .Load
hlsl.meta.slang(15024): error 29000: unable to parse target intrinsic snippet: .Load
```

I couldn't find anything that looked like int `hlsl.meta.slang`.

**Shader**
```
Buffer<float>    floatbuf;
RWBuffer<float2> float2buf;

void main() {
  	int address;
    uint status;
    float  r1 = floatbuf.Load(address, status); 
    float2 r2 = float2buf.Load(address, status); 
}
```

**Comment by csyonghe** [comment]
None of our users are using this function and there is no way we can convert this into spirv. 

We can add the overload but it will only be implemented for HLSL and is not meaningful for other targets. I am not sure how important this is though.

**Comment by chaoticbob** [comment]
Hard to gauge the current importance of it currently. At least one person used it to justify a test for it. Probably should just back burner until someone comes asking for it.

**Comment by jkwak-work** [comment]
We now have an umbrella issue for this.
https://github.com/shader-slang/slang/issues/4495

**Comment by jkwak-work** [comment]
HLSL spec for Load with status can be found in the following link.
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/t2d-load-float-int-uint-

**Comment by jkwak-work** [comment]
Just a leaving a note for future reference.
`status` is known to be not supported for Buffer types when targeting SPIR-V.

It says that,
>[Unsupported HLSL Features](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#unsupported-hlsl-features)
Since StructuredBuffer, RWStructuredBuffer, ByteAddressBuffer, and RWByteAddressBuffer are not represented as image types in SPIR-V, using the output unsigned integer status argument in their Load* methods is not supported. Using these methods with the status argument will cause a compiler error.
