### ISSUE TITLE
Unable to use vectors in initialization list of other vectors

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4460]
Using `float2` vars in initialization list for `float3` and `float4` fails to compile. Using `float3` in initialization list for `float4` fails to compile.
Error msg:
```
shader.hlsl(14): error 30019: expected an expression of type 'float', got 'vector<float,2>'
    float3 h0 = {v2, 1};
                 ^~
shader.hlsl(15): error 30019: expected an expression of type 'float', got 'vector<float,2>'
    float3 i0 = {1, float2(0, 1)};
                          ^
shader.hlsl(23): error 30019: expected an expression of type 'float', got 'vector<float,2>'
    float4 r0 = {input.foo[0], input.bar[1].yz};
                          ^
shader.hlsl(24): error 30019: expected an expression of type 'float', got 'vector<float,2>'
    float4 r1 = {v2, v2};
                 ^~
shader.hlsl(25): error 30019: expected an expression of type 'float', got 'vector<float,2>'
    float4 r2 = {v2, 0, 1};
                 ^~
shader.hlsl(26): error 30019: expected an expression of type 'float', got 'vector<float,3>'
    float4 r3 = {h0, 1};
                 ^~
shader.hlsl(27): error 30019: expected an expression of type 'float', got 'vector<float,3>'
    float4 r4 = {0, float3(g0.x, h0.x, i0.x)};
```

Was expecting that whatever I can pass into a vector's constructor, I should be able to pass into an initialization list.

**CMD**
```
slangc.exe -target spirv -lang slang -D__spirv__ -emit-spirv-directly -profile ps_6_0 -entry main shader.hlsl
```

**Shader**
```
struct PSInput
{
    float2 foo[4] : A;
    float3 bar[2] : B;
};

float4 main(PSInput input) : SV_TARGET
{
    float2 v2  = input.foo[0];

    float3 g0 = float3(v2, 1);
    float3 h0 = {v2, 1};
    float3 i0 = {1, float2(0, 1)};
    
    float4 s0 = float4(input.foo[0], input.bar[1].yz);
    float4 s1 = float4(v2, v2);
    float4 s2 = float4(v2, 0, 1);
    float4 s3 = float4(h0, 1);
    float4 s4 = float4(0, float3(g0.x, h0.x, i0.x));

    float4 r0 = {input.foo[0], input.bar[1].yz};
    float4 r1 = {v2, v2};
    float4 r2 = {v2, 0, 1};
    float4 r3 = {h0, 1};
    float4 r4 = {0, float3(g0.x, h0.x, i0.x)};
    
    return s0 + s1 + s2 + s3 + s4 +
           r0 + r1 + r2 + r3 + r4;
}
```

**Comment by ArielG-NV** [comment]
Note: Likely should be a special intrinsic to mix and match making vectors from a list of vectors to avoid creating a few dozen `__init()` expressions for `struct vector`

**Comment by jkwak-work** [comment]
It appears that this is a duplicate issue to #4461.
I am closing this as a duplicate and it will be followed up by #4461.

All lines in the given shader works except ones that uses the list-initializer.
The following two lines are supposed to call the same constructor but the second one fails to call the constructor,
```
    float3 g0 = float3(v2, 1); // WORKS
    float3 h0 = {v2, 1}; // FAILS
```
The error message is following,
```
a.slang(12): error 30019: expected an expression of type 'float', got 'vector<float,2>'
    float3 h0 = {v2, 1};
                 ^~
```
It looks like that the list-initializer is trying to assign the values to the member variables directly rather than calling the constructor.

**Comment by ArielG-NV** [comment]
> It looks like that the list-initializer is trying to assign the values to the member variables directly rather than calling the constructor.

This is correct, `list-initializer` in Slang do not call a constructor:
1. if `{}`, they set all member variables to their respective initExpr, all other variables are zeroed (does not always zero values)
2. if non empty initializer list, the initializer list tries to map values 1:1 with member variables for initialization.

**Comment by ArielG-NV** [comment]
I think this is actually a bug in `_readAggregateValueFromInitializerList`.

Specifically the `else if (auto toVecType = as<VectorExpressionType>(toType))` part of code which should allow vector initialization.

**Comment by jkwak-work** [comment]
> > It looks like that the list-initializer is trying to assign the values to the member variables directly rather than calling the constructor.
> 
> This is a correct analysis on how initializer-lists in Slang work, they (unlike C++) do not call a constructor:

@ArielG-NV , can you see if the user guide has a correct example?
https://shader-slang.com/slang/user-guide/convenience-features.html#initializers
Particularly for the following example code,
```
MyType instance = {1, 2};
```
The document says the list-initializer will call the constructor, isn't it?

**Comment by ArielG-NV** [comment]
> The document says the list-initializer will call the constructor, isn't it?

The documentation is wrong since initializer list does not follow how C++ works.

From what I understand though, this is an implementation error which was kept.

**Comment by ArielG-NV** [comment]
> @ArielG-NV , can you see if the user guide has a correct example?
https://shader-slang.com/slang/user-guide/convenience-features.html#initializers
Particularly for the following example code,

The example is wrong, I checked just now.

**Comment by ArielG-NV** [comment]
As per code comments and the documentation, initializer lists *should* work like C++, but instead, they do not have a way of calling constructors
