### ISSUE TITLE
Will Slang support `using` for type aliasing?

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4474]
I saw in the tests that Slang supports `typedef` for type aliasing. But I couldn't find anything about `using` in the docs or the tests. Curious if `using` will be supported?

**Comment by dubiousconst282** [comment]
I think this is already covered by `typealias A = B;`

**Comment by jkwak-work** [comment]
I think the user can alias `using` to `typealias` with define macro like this,
```
#define using typealias
```

**Comment by bmillsNV** [comment]
@chaoticbob looks like this has been answered. Need anything else?

**Comment by chaoticbob** [comment]
Thanks!

Aliasing and aliasing directive. I love it. 

@bmillsNV All good to go, closing!
