### ISSUE TITLE
Unexpected ambiguous call.

### ISSUE THREAD

**Issue by tomas-davidovic** [shader-slang/slang#4476]
In code like this:
```
uniform uint gData;

uint getData()
{
    return gData;
}

struct DataObtainer
{
    uint data;
    uint getData()
    {
        return data;
    }

    uint getValue()
    {
        return getData(); /// This is ambiguous call
    }
}

[numthreads(16, 1, 1)]
void testGetData(uint3 threadID: SV_DispatchThreadID)
{
    DataObtainer obtainer;
    output[0] = getData();
    output[1] = obtainer.getData();
    output[2] = obtainer.getValue();
}
```
The call to `getData()` inside `getValue()` is reported as an ambiguous call. This is incosistent with C/C++, where the compiler will automatically prefer the member function `getData()`, without needing to explicitly specify `this.getData()` or `::getData()`.

**Comment by ArielG-NV** [comment]
I don't know if this is intentional behavior, but the solution should be simple. Overload resolution would just need to prefer functions with equal parents.

**Comment by csyonghe** [comment]
Yes this is just an oversight and we should fix it.
