### ISSUE TITLE
There is no way to emit WGSL

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4477]
For the reasons described in [issue 2454](https://github.com/shader-slang/slang/issues/2454) (closed), it would be desirable to be able to emit WGSL ([WebGPU Shading Language](https://www.w3.org/TR/WGSL/)).

**Comment by aleino-nv** [comment]
I opened this issue since we've now decided to experiment with a WGSL back-end, and I'm now working on it.

**Comment by swoods-nv** [comment]
Anders, do you have smaller tasks to break this out into? And can you provide an estimate (in effort-days, not including time for review, etc) for how long this will take?

**Comment by aleino-nv** [comment]
> Anders, do you have smaller tasks to break this out into? And can you provide an estimate (in effort-days, not including time for review, etc) for how long this will take?

Yeah, I filed these two, which are "sub-tasks" of this issue:

- #4484 
- #4483 

Currently the sum for those tasks is about 3*8 hours of work

**Comment by bmillsNV** [comment]
Closing will use 4807 to track implementation.
