### ISSUE TITLE
tests/cpu-program/gfx-smoke.slang fails on local test

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4489]
**Problem description**
One of the slang-test tests started failing as a regression.
```
tests/cpu-program/gfx-smoke.slang
```
This test is disabled on CI but when you run it on a local machine, it fails.
The regression started happening from the following commit,
```
b7e82434 Wed Jun 12 12:46:24 2024 -0400 Add slangc flag to `-zero-initialize` all variables (#3987) 
```
Note that there was a build break that causes the specific commit to have a compile error.
You will need to cherry-pick the right next commit.

**Repro step**
Checkout the commit that caused the regression and cherry-pick to fix the compile error,
```
git checkout b7e82434
git cherry-pick 8bf7d11
build slang-test.exe
slang-test.exe tests/cpu-program/gfx-smoke.slang
```

When the issue is reproduced, the error looks like following,
```
tests/cpu-program/gfx-smoke.slang(7): note 99999: an internal error threw an exception while working on code near this location
    gfx.DeviceDesc deviceDesc = {};
                   ^~~~~~~~~~
(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: InitializerListType
```

**Comment by ArielG-NV** [comment]
```
    void SemanticsDeclBodyVisitor::visitAggTypeDecl(AggTypeDecl* aggTypeDecl)
	
	//...
        ensureDecl(m->getDefaultDeclRef(), DeclCheckState::DefaultConstructorReadyForUse); // crash is introduced indirectly from this line
	//...
```

**Comment by ArielG-NV** [comment]
detailed explanation of the problem: https://github.com/shader-slang/slang/pull/4491#issuecomment-2194872824
