### ISSUE TITLE
Improve organization of release assets

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4528]
**Header Files**
Can the header files that's located in the root of all the release asset zip and tar.gz files be moved into an `include` or `inc` or maybe even a `include/slang` or `inc/slang`? There's not a strong technical argument for this but for project setups this makes it more obvious what the path entry is doing.

**Binaries**
Currently, the binaries are located a few directories down from the root itself: `bin/<platform>/release/[slangc, *.so, *.dll]`. Is possible to trim down a bit? Since the release assets already have the platform name, can the binary content just be in `bin` directory?

**Comment by bmillsNV** [comment]
if we make a change - some concerns about backwards compatibility. Maybe just put in the release notes? @ArielG-NV to propose something, then we can get alignment and move forward in the next sprint.

**Comment by expipiplus1** [comment]
This should be fixed by https://github.com/shader-slang/slang/pull/3703

**Comment by ArielG-NV** [comment]
> if we make a change - some concerns about backwards compatibility. Maybe just put in the release notes? @ArielG-NV to propose something, then we can get alignment and move forward in the next sprint.

Seeing what @expipiplus1 said
> This should be fixed by https://github.com/shader-slang/slang/pull/3703

It seems this task is already being handled.
