### ISSUE TITLE
Metal: Implement non member function atomic texture support

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4538]
Related to: #4291
`tests/compute/atomics-buffer.slang` fails to compile with Metal target.

Problem:
HLSL allows `InterlockedAdd(RWBuffer[INDEX]...);`. Metal does not allow "magic destinations" as input for atomics. Due to this, `__getMetalAtomicRef` was added to cast values into an appropriate atomic value. 

Texture objects cannot use this same logic of `__getMetalAtomicRef` casting. [Texture objects mandate use of member functions](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#Texture%20Functions).

**Comment by ArielG-NV** [comment]
`texture_buffer` is being read with a `[]` operator

`atomic_fetch_add_explicit` parameter is not a pointer

**Comment by ArielG-NV** [comment]
Few problems with how we currently manage atomics: https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#Texture%20Functions

RWBuffer is a texture_buffer. We may use atomics with textures but only through member functions.

to use `Interlocked.*(srcTexture...)` we must check if we have a srcTexture, if so, use a different atomic

**Comment by ArielG-NV** [comment]
The way this can be done:
note: `imageSubscript` has coordinates for atomic access
(inside `__metalInterlocked_compare_exchange`)
```
if(isTextureAccess(atomicVal))
{
   ForceToTextureType(atomicVal).Interlocked_Compare_Exchange(ExtractCoordFromImageSubscript(atomicVal), ...)
}
else
{
    __metalInterlocked_compare_exchange(dest, compare_value, value);
}
```

**Comment by jkwak-work** [comment]
This issue might be a duplicate to an issue #4481

**Comment by ArielG-NV** [comment]
it is a duplicate

**Comment by ArielG-NV** [comment]
@jkwak-work would it be fine if I take over the task (I see it was not yet started)

**Comment by ArielG-NV** [comment]
I was reading over the issue and I realized that https://github.com/shader-slang/slang/issues/4481 is actually not a duplicate

My issue is about `texture_buffer` not working with atomics
