### ISSUE TITLE
Metal GFX Backend: `RWTexture*` causes compute tests to fail

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4541]
Related to [#4291](https://github.com/shader-slang/slang/issues/4291)
`RWTexture*` use in Metal compute tests causes a failure. This is likely a cause of the Metal GFX Backend.

Affects the following tests:
* tests\bugs\buffer-swizzle-store.slang
* tests/compute/texture-subscript.slang

**Comment by csyonghe** [comment]
This is fixed.
