### ISSUE TITLE
Metal GFX backend: cbuffer/uniform related syntax for `slang-test` is not working as expected

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4545]
* tests/compute/entry-point-uniform-params.slang --> returns 0 in all cases, only possible if shader fails, or if data is not uploaded correctly. Uses uniforms.
* tests/hlsl/packoffset.slang --> returns 0 in all cases, only possible if shader fails, or if data is not uploaded correctly. Uses `set OBJECT` syntax.

**Comment by csyonghe** [comment]
`tests/hlsl/packoffset.slang` fail because there is no way in metal to specify the byte offset of a field, so it is out of scope.
 #4644 Fixes the entry-point-uniform-param test.

**Comment by ArielG-NV** [comment]
> fail because there is no way in metal to specify the byte offset of a field

Out of curiosity, could we do this by just inserting 4-byte members in-between to force offset?
