### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by ashpil** [shader-slang/slang#4553]
Hi there,

I'm looking at converting [a project of mine](https://github.com/ashpil/moonshine) to use slang rather than HLSL.

I use unicode extensively in my math code, as I believe it is clearer to write e.g., `α` instead of `alpha`, or `Λ` instead of `lambda`.

Looks like Slang fails on this: 

```hlsl
shaders/hrtsystem/material.hlsl(32): error 10000: illegal character (0xB1)
        float α2 = pow(α, 2);
                         ^
```
(and many more)

Is this an intentional design choice? Or is there a plan to support unicode in the future?

**Comment by swoods-nv** [comment]
This isn't an intentional design choice, but not something we've allocated time to addressing. It's a plausible feature to add but we don't currently have a timeline for doing so.

**Comment by jkwak-work** [comment]
The variable name should start with one of alphabet characters or an underscore character, '_'.
The unicode, `α`, is not one of them.

The request here sounds more like "Allow special characters from the Unicode character sets as a variable name".
