### ISSUE TITLE
Metal: Array of device buffers is not allowed for input into an entry-point

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4555]
Related to: #4291 

Following issue breaks the following (metal) tests:
* tests/compute/loop-unroll.slang
* tests/compute/buffer-type-splitting.slang

Problem:
`array<int device*, ...>` is an invalid input declaration for an entry-point.

**Comment by csyonghe** [comment]
There isn't a way for us to meaningfully translate a StructuredBuffer array into metal. They maybe allowed in a parameter block. I'm fine with us ignoring these tests for now.
