### ISSUE TITLE
IR: Improve readability of generated output

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#457]
The current output from `emit.cpp` when using the IR is hard to read for a variety of reasons:

* It tries to reproduce line/column information from the original code, but that isn't done especially well, and it mostly just obscures the structure of the code

* It uses mangled names for global symbols, instead of the names the user originally wrote

* It uses many temporaries, with generated names, and no effort it made to:

    * Re-construct larger expressions from multiple IR-level instructions

    * Use the original names for temporaries that represent local variables

We should resolve these issues and make the IR output as readable as possible, for when users (or those of us on the development team) need to diagnose something that went wrong.

Our first priority should be to make the output readable on its own, and not necessarily to maintain a perfect mapping back to the original code with `#line` directives. We should also support a `-g` debug flag that makes the compiler output code with `#line` directives to hopefully make the generated code work with step-through debuggers (although the built-in VS graphics tools get confused by `#line` directives in HLSL code...).

I will start by trying to get the indentation and so forth under control.

**Comment by tfoleyNV** [comment]
PR #458 simplified the indentation I’d generated code, and turned off the generation of `#line` directives by default.

Probably the next biggest improvement would come from trying go use the original names for temporary variables in the generated code.

**Comment by tfoleyNV** [comment]
PR #547 changed our output to use names based on the names the user originally wrote, so a variable like `a` will often come through as `a_0`. Further work is still needed to just use `a` in the cases where that is valid to do.

PR #552 should allow us to reconstruct compound expressions in some (but not all) cases. Further work will be needed to make sure it outputs minimal parentheses to keep the output readable.

**Comment by tangent-vector** [comment]
Closing. We've made a lot of steps here (although our output isn't 100% as good as it could be).
Further cleanups are going to be possible, but the spirit of this issue has been dealt with.
