### ISSUE TITLE
Use slang examples as initial test cases for the capture/replay system

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4570]
We need to add some test cases for the capture/replay system when it's done.
Currently, the slang examples are the good test cases because they all implemented by using new slang API.
And it's relative easy to integrate to our CI.

**Comment by bmillsNV** [comment]
2 samples we'll focus on are: gpu printing, cpu hello world

**Comment by kaizhangNV** [comment]
#4898 implement the basic infrastructure that making porting those examples easier. And added two examples: hello world, triangle.

In the follow up patches, I will add more tests and integrate the test flow into slang-unit-test.

**Comment by kaizhangNV** [comment]
cpu-com-example also needs migration to new slang API.

**Comment by kaizhangNV** [comment]
Found a slang bug when running `autodiff-texture`, the fix is by PR: https://github.com/shader-slang/slang/pull/4925.

**Comment by kaizhangNV** [comment]
### Latest status:
Only 3 examples are not done yet.
 - gpu-printing: blocked by #4918
 - shader-toy: blocked by #4918
 - cpu-com-example: Didn't find corresponding API for `ICompileRequest::getTargetHostCallable`.
