### ISSUE TITLE
slang-torch: `inline-mlp` example fails to compile

### ISSUE THREAD

**Issue by saipraveenb25** [shader-slang/slang#4599]
Trying to compile this file: https://github.com/shader-slang/slang-torch/blob/main/examples/inline-mlp-example/inline-mlp.slang
results in `(0): error 99999: Slang compilation aborted due to an exception of class Slang::InternalError: unexpected: Generic type/value shouldn't be handled here!` with top-of-tree 

Related issue: https://github.com/shader-slang/slang-torch/issues/11

**Comment by jkwak-work** [comment]
Should we have a CI to check the examples regularly?

**Comment by jkwak-work** [comment]
I assume that the example was working before but it started not working.
Is this a regression?

**Comment by saipraveenb25** [comment]
@jkwak-work. Yes! This is something we had discussed before but never implemented. 

We need to run the tests in the slang-torch repository regularly with the CI, but it does require a somewhat more complex setup than our current tests. They need a python 3.9 + torch 2.3 environment set up.
