### ISSUE TITLE
`shared` should only be allowed on global variables

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#462]

**Comment by tfoleyNV** [comment]
In general, Slang's checking of modifiers/qualifiers is fairly lax right now, so doing this enforcement would be a good chance to tighten some of that up.

**Comment by nbenty** [comment]
We also need to make sure that if the same resource is declared in multiple places, it uses the same modifier

**Comment by tfoleyNV** [comment]
> We also need to make sure that if the same resource is declared in multiple places, it uses the same modifier

Slang should be able to enforce that within a single `Program`, but it seems to be that there is a bigger issue here, where all the different RT programs you are going to bind at once need to agree on what the global root signature will be (the `shared` parameters and their layout), and checking that would be at a scope larger than what Slang typically sees at one time.

The context for anybody who is following along at home: the DirectX Raytracing (DXR) API introduces a distinction between a "global" and "local" root signature, where the global signature is for parameters that will be shared by all RT programs (so the arguments get passed via the ordinary root binding slots), while the local signature is potentially different for each entry point and determine which arguments get stored in the shader table alongside the entry points.

Slang is exposing the `shared` modifier (which used to be a hint for the D3D effect system) to serve as a hint to the user about which parameters are supposed to go into the global root signature (with the implication that all others should go into the local one).

From a language perspective, it would be nice if we could have a more "clean" way to specify multiple entry points that will all share some global parameter blocks. I don't see anything particularly easy to do without major changes to the HLSL entry point syntax, though.

**Comment by nbenty** [comment]
Falcor verifies that `ParameterBlock` definitions match between different shader stages

**Comment by tfoleyNV** [comment]
It's not about that part (and Slang now checks parameter block definitions between stages of a single `Program`).

I'm talking about the case where you bind two different hit groups (each an `RtProgram`, IIRC), and they disagree about which parameter blocks are `shared` (or just disagree about what goes inside a `shared` parameter block). Do you do that kind of checking on the entire RT "scene" or "program collection" or whatever the abstraction is for "all the programs you might call together."

**Comment by nbenty** [comment]
The way Falcor handles it is:
(a) For each collection of programs (RtProgram) we go over all the internal programs and create a single ProgramReflection object from the `shared` resources
(b) The programs has to agree on bind-locations and layout (that's the tricky part to manage)

I think the best option is to force people to create an `RtProgram` object from a single file. They can then use `#include` to share code between different programs

**Comment by tangent-vector** [comment]
Closing. The `shared` keyword is now deprecated/legacy.
