### ISSUE TITLE
`row_major`/`column_major` modifier is disallowed on a variable with an initExpr

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4633]
Problem:
` row_major float3x3 xyz = ...;` does not compile

Expected:
` row_major float3x3 xyz = ...;` should compile

Note:
```
row_major float3x3 xyz;
xyz = ...;
```
compiles

**Comment by csyonghe** [comment]
Note: declaring `row_major`/`column_major` on a local variable doesn't have a meaning, so we should just ignore them and issue a warning.
