### ISSUE TITLE
Most of Falcor's Vulkan samples fail to run due to internal compiler error [URGENT]

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#466]
Note that Falcor now uses VK SDK 1.1.70.1
`VulkanFixes` branch:
- AmbientOcclusion
- HashedAlpha
- SimpleDeferred
- HDRToneMapping
- Shadows
- SkyBoxRenderer
- ModelViewer
- ForwardRenderer
- SceneEditor

**Comment by tfoleyNV** [comment]
I'll look into it. All of these were working at the time I first created the PR to integrate Slang v0.10.*, so there must have been a regression at some point.

**Comment by nbenty** [comment]
Everything works with 0.10.3, except for:
* ComputeShader 
* MultiPassPostProcess (load an image, enable GuassianBlur and Grayscale. It complains about `static` being a reserved word).
