### ISSUE TITLE
[MDL:3/5] Benchmark compilation times

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4661]
Time saving needs to be measured between the monolithic compilation slang-module based compilation.

The idea is for there to be at least one slang-module that’s a reusable library, for example, MDL team’s experiments defined a “libbsdf” DXIL library, and for the other slang-module to represent the material permutation, which is recompiled every time.  Re-using the library module and only recompiling and linking the base module should be faster.  Later in the project, the difference will again be measured when utilizing precompiled embedded DXIL/SPIRV.

**Comment by jkwak-work** [comment]
This is a subtask from #4582.

**Comment by venkataram-nv** [comment]
These are the results for SPIRV compilation (averaged over 100 compilations per step):

```
slangc: ..\..\build\Release\bin\slangc.exe
target: spirv
samples: 100
¡ compiled buffers.slang.
¡ compiled common.slang.
¡ compiled enumerations.slang.
¡ compiled environment.slang.
¡ compiled hit.slang.
¡ compiled material.slang.
¡ compiled mdl.slang.
¡ compiled runtime.slang.
¡ compiled shading.slang.
¡ compiled types.slang.
¡ compiled closeshit (module).
¡ compiled anyhit (module).
¡ compiled shadow (module).
¡ compiled closesthit (mono).
¡ compiled anyhit (mono).
¡ compiled shadow (mono).
results:
    module precompilation    1.553s
    module whole compilation 0.220s
        closeshit 0.122s
        anyhit    0.049s
        shadow    0.049s
    monolithic compilation   0.608s
        closeshit 0.250s
        anyhit    0.179s
        shadow    0.179s
    speed up factor          2.77x
        closeshit 2.06x
        anyhit    3.67x
        shadow    3.62x
```

**Comment by venkataram-nv** [comment]
Also please see [this script](https://github.com/venkataram-nv/slang/blob/mdl-benchmark/tests/mdl/compile.py) to see how this benchmark is done.

**Comment by jkwak-work** [comment]
Judging by the script, the timing number presented is based on `spCompile`.
But what does it include? And what doesn't it include?
This seems to be the source of the confusion.

We also want to know how much DXC takes to do the same as the monolithic case.

**Comment by venkataram-nv** [comment]
>  But what does it include? And what doesn't it include?

I will check this out in more detail shortly.

> We also want to know how much DXC takes to do the same as the monolithic case.

Here are the benchmarks which include DXC compilation to SPIRV.

```
slangc: ..\..\build\Release\bin\slangc.exe
target: spirv
samples: 16

[...]

results:

    module precompilation    1.556s

    module whole compilation 0.219s
        closeshit 0.119s
        anyhit    0.050s
        shadow    0.050s

    monolithic compilation   0.611s
        closeshit 0.252s
        anyhit    0.180s
        shadow    0.179s

    speed up (vs mono)       2.80x
        closeshit 2.12x
        anyhit    3.62x
        shadow    3.58x

    dxc compilation of hlsl  0.385s
        closeshit 0.129s
        anyhit    0.128s
        shadow    0.128s

    speed up (vs dxc)        1.76x
        closeshit 1.09x
        anyhit    2.57x
        shadow    2.56x
```

**Comment by venkataram-nv** [comment]
Same benchmarks, but with the target now being DXIL:

```
slangc:  ..\..\build\Release\bin\slangc.exe
target:  dxil
samples: 64

¡ compiled buffers.slang.
¡ compiled common.slang.
¡ compiled enumerations.slang.
¡ compiled environment.slang.
¡ compiled hit.slang.
¡ compiled material.slang.
¡ compiled mdl.slang.
¡ compiled runtime.slang.
¡ compiled shading.slang.
¡ compiled types.slang.
¡ compiled closeshit (module).
¡ compiled anyhit (module).
¡ compiled shadow (module).
¡ compiled closesthit (mono).
¡ compiled anyhit (mono).
¡ compiled shadow (mono).
¡ compiled closeshit (dxc).
¡ compiled anyhit (dxc).
¡ compiled shadow (dxc).
¡ generated shader for closesthit
¡ generated shader for anyhit
¡ generated shader for shadow
¡ compiled closeshit (dxc & gen).
¡ compiled anyhit (dxc & gen).
¡ compiled shadow (dxc & gen).

results:

    module precompilation    1.772s

    module whole compilation 0.231s
        closeshit 0.127s
        anyhit    0.051s
        shadow    0.053s

    monolithic compilation   0.638s
        closeshit 0.263s
        anyhit    0.186s
        shadow    0.189s

    speed up (vs mono)       2.76x
        closeshit 2.07x
        anyhit    3.62x
        shadow    3.56x

    dxc for original hlsl    0.217s
        closeshit 0.073s
        anyhit    0.072s
        shadow    0.072s

    speed up (vs dxc)        0.94x
        closeshit 0.57x
        anyhit    1.41x
        shadow    1.36x
```

**Comment by venkataram-nv** [comment]
# DXIL Compilation

**module precompilation: 1.592s**

**module whole compilation: 0.232s**
|    Entry    | Total  | Link & Optimize  | Semantic Checking |  DXC Downstream  |
| :---------: | :----: | :--------------: | :---------------: | :--------------: |
| Closest Hit | 0.128s | 0.069s *(54.5%)* |  0.000s *(0.0%)*  | 0.049s *(38.2%)* |
|   Any Hit   | 0.052s | 0.033s *(64.7%)* |  0.000s *(0.0%)*  | 0.013s *(25.9%)* |
|    Shadow   | 0.053s | 0.034s *(65.0%)* |  0.000s *(0.0%)*  | 0.013s *(25.5%)* |

**monolithic compilation: 0.639s**
|    Entry    | Total  | Link & Optimize  | Semantic Checking |  DXC Downstream  |
| :---------: | :----: | :--------------: | :---------------: | :--------------: |
| Closest Hit | 0.262s | 0.071s *(27.1%)* |  0.126s *(48.2%)* | 0.048s *(18.5%)* |
|   Any Hit   | 0.189s | 0.034s *(18.0%)* |  0.130s *(68.7%)* | 0.014s *(7.2%)*  |
|    Shadow   | 0.188s | 0.034s *(18.1%)* |  0.129s *(68.5%)* | 0.014s *(7.3%)*  |

**dxc for original hlsl: 0.233s**
|    Entry    | Total  |
| :---------: | :----: |
| Closest Hit | 0.078s |
|   Any Hit   | 0.077s |
|   Shadow    | 0.077s |

**Speed up factors**
|    Entry    | vs. Monolithic | vs. DXC |
| :---------: | :------------: | :-----: |
|    Total    |     2.755x     |  1.004x |
| Closest Hit |     2.051x     |  0.612x |
|   Any Hit   |     3.660x     |  1.499x |
|    Shadow   |     3.575x     |  1.470x |

# SPIRV Compilation (Direct)

# SPIRV Compilation (Via GLSL)

**Comment by venkataram-nv** [comment]
New benchmarks here, now using much larger MDL shaders (specifically `OmniSurface_BrushedMetal`). Compile times cross the one second mark. At this point the Link & Optimize stage takes the majority of compile time.

# DXIL

**Module precompilation (6.457s)**

**Module whole compilation (2.159s)**
|    Entry    | Total  | Link & Optimize  | Semantic Checking |  DXC Downstream  |
| :---------: | :----: | :--------------: | :---------------: | :--------------: |
| Closest Hit | 1.472s | 0.862s *(58.5%)* |  0.000s *(0.0%)*  | 0.577s *(39.2%)* |
|   Any Hit   | 0.338s | 0.244s *(72.2%)* |  0.000s *(0.0%)*  | 0.081s *(24.1%)* |
|    Shadow   | 0.350s | 0.254s *(72.6%)* |  0.000s *(0.0%)*  | 0.083s *(23.7%)* |

**Monolithic compilation (3.043s)**
|    Entry    | Total  | Link & Optimize  | Semantic Checking |  DXC Downstream  |
| :---------: | :----: | :--------------: | :---------------: | :--------------: |
| Closest Hit | 1.837s | 0.949s *(51.6%)* |  0.255s *(13.9%)* | 0.590s *(32.1%)* |
|   Any Hit   | 0.601s | 0.247s *(41.1%)* |  0.253s *(42.1%)* | 0.081s *(13.5%)* |
|    Shadow   | 0.605s | 0.248s *(41.0%)* |  0.255s *(42.2%)* | 0.083s *(13.7%)* |

**DXC for original HLSL (1.936s)**
|    Entry    | Total  |
| :---------: | :----: |
| Closest Hit | 0.646s |
|   Any Hit   | 0.650s |
|   Shadow    | 0.641s |

**Speed up factors**
|    Entry    | vs. Monolithic | vs. DXC |
| :---------: | :------------: | :-----: |
|    Total    |     1.409x     |  0.897x |
| Closest Hit |     1.248x     |  0.439x |
|   Any Hit   |     1.777x     |  1.921x |
|    Shadow   |     1.732x     |  1.833x |

**Comment by venkataram-nv** [comment]
Closed until perhaps further benchmarks are requested.
