### ISSUE TITLE
[MDL:5/5] Add support for embedded precompiled library feature

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4663]
This should initially amount to using the “-embed-dxil” and “-embed-spirv” options in slangc when compiling the slang-modules. The performance benefit/cost needs to be quantified for compilation and runtime.

A complication with this phase of the project is that the feature is still in development.

**Comment by jkwak-work** [comment]
This is a subtask from #4582.

**Comment by venkataram-nv** [comment]
Ran into this issue: #4823
