### ISSUE TITLE
IR: propagate through explicit interpolation modifiers

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#468]
Explicit interpolation modifiers on varying input/output currently get dropped as part of lowering to the IR. We need to preserve these as `IRDecoration`s so that we can reproduce them appropriately in output code.

Interpolation modifiers have the same annoying issue as semantics where we can't just store them in a `VarLayout` separate from the IR, and then use that information when emitting, because these modifiers are allowed on the fields of `struct` types, and those types might get emitted without any particular layout.

**Comment by tfoleyNV** [comment]
One solution to the annoying issue I note would be to perform the same scalarization of varying inputs that we do for GLSL on HLSL code as well. This runs the risk of changing varying signatures when AOS<->SOA situations arise, but it would provide a more general fix.

**Comment by tangent-vector** [comment]
This has worked for a while.
