### ISSUE TITLE
DXIL validation errors with uninitialized fields

### ISSUE THREAD

**Issue by venkataram-nv** [shader-slang/slang#4698]
Compiling the following shader results in problems at the DXIL validation stage.

```hlsl
struct RadianceHitInfo { int x; };
struct Attributes      { float2 bary; };
struct ShadingState    { float4 tex; };

RWStructuredBuffer<float4> result;

void mdl_init(inout ShadingState state) {}

[shader("closesthit")]
void closesthit(inout RadianceHitInfo payload, Attributes attrib)
{
    ShadingState mdl_state;
    mdl_init(mdl_state);
    result[0] = mdl_state.tex.xyzw;
}
```

When compiling with `slangc [file] -target dxil -stage closesthit -entry closesthit` the following error is displayed:

```
dxc 1.7: hlsl.hlsl(52): error :  Assignment of undefined values to UAV.
dxc 1.7: note : note: at 'call void @dx.op.rawBufferStore.f32(i32 140, %dx.types.Handle %4, i32 0, i32 0, float undef, float undef, float undef, float undef, i8 15, i32 4)' in block '#0' of function '?closesthit@@YAXURadianceHitInfo_0@@UAttributes_0@@@Z'.
dxc 1.7: note : Validation failed.
```

These errors can be resolved by initializing the `tex` field of `mdl_state`.

The proposed two-step solution is as follows:
1. Emit warnings for never assigning to `out` / `inout` / `__ref` parameters. For `inout` we can request the user to fallback to `in` if necessary.
2. Transition uninitialization warnings to errors when emitting DXIL.

**Comment by jkwak-work** [comment]
Are `payload` and `attrib` unrelated to the issue?

**Comment by csyonghe** [comment]
This gets into another tricky detail about dxc. If the uninitialized variable is never used, then dxc will allow that code to pass compilation. This means that if we emit errors, we can potentially break existing code that worked fine, so this may need to stay as a warning for now. We can implement a `-validation-level=strict/relaxed` compiler option that makes this an error under `strict`, and for now we make `relaxed` as default but switch to `strict` some time in the future with enough advance notice.

**Comment by venkataram-nv** [comment]
> Are payload and attrib unrelated to the issue?

Yes, its only there so I can have a raytracing shader entrypoint which I can compile to DXIL.
