### ISSUE TITLE
`ConstantBuffer<T[...]>` struct member access causes a segfault

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4704]
Problem:
if the provided shader is compiled with `-target spirv -stage compute -entry computeMain` there will be a crash.
```
[[vk::binding(0, 0)]] uniform ConstantBuffer<uint64_t[1000]> addresses;
[[vk::binding(0, 0)]] uniform ConstantBuffer<uint64_t[1000]> addresses1;

[shader("compute")]
[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID: SV_DispatchThreadID, uint groupIndex: SV_GroupIndex) {
    printf("\nfrom gpu: %llu", addresses1[0]);
    printf("\nfrom gpu: %llu", addresses1[1]);
}
```

**Comment by ArielG-NV** [comment]
```
    void processFieldAddress(IRFieldAddress* inst)
    {
        if (auto ptrType = as<IRPtrTypeBase>(inst->getBase()->getDataType()))
        {
            if (!ptrType->hasAddressSpace())
                return;
            auto oldResultType = as<IRPtrTypeBase>(inst->getDataType());
            auto oldValueType = oldResultType->getValueType();
            auto newValueType = translateToStorageBufferPointer(oldValueType);
```

expects the field address member to be a pointer. `ConstantBuffer` is not a pointer (and is not lowered), this causes a segfault.

**Comment by ArielG-NV** [comment]
This is an issue with `lowerBufferElementTypeToStorageType`.

This seems to not be a regression (shows up in early june build).

**Comment by ArielG-NV** [comment]
The problem: 
Some inst's store the type of a variable, these inst's were not legalized.

As a result `ConstantBuffer<T>` will legalize into a `struct { ConstantBuffer<T> data; };` and then a `GetFieldAddress` will store a invalid ConstantBuffer<T> type

**Comment by jkwak-work** [comment]
Can you update the description with what is an expected behavior and what command line arguments are used for the repro?
