### ISSUE TITLE
[NumThreads(x,y,z)] should be case-insensitive

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4746]
While playing with [a work-graph example](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12HelloWorld/src/HelloWorkGraphs/D3D12HelloWorkGraphs.hlsl), I found that the function attribute keywords are case-insensitive to DXC.exe but it is case-sensitive to Slang.

All of the following should work:
`[numthreads(x,y,z)]`, `[NumThreads(x,y,z)]` and `[NuMtHrEaDs(x,y,z)]`.

Also note that this is not limited to "numthreads".
All the other attribute keywords should be case-insensitive.

**Comment by csyonghe** [comment]
I am not sure if we want to implement this. Attributes are looked up through the same mechanism we lookup any other type of identifiers. I don't think this corner case behavior is worth the additional complexity in our lookup logic.

**Comment by csyonghe** [comment]
We can define an alias for [`NumThreads()]` in addition to `[numthreads]`, but probably no more than that.

**Comment by csyonghe** [comment]
It is fine to define these `CamelCase` naming as aliases, we do not need to support full case-insensitive lookup.

**Comment by csyonghe** [comment]
For the new attributes, we don't even need any aliases, just define them in CamelCase.

**Comment by jkwak-work** [comment]
Sounds good.
