### ISSUE TITLE
Slang C API Deprecation - Step 1

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#4758]
We need to start deprecate all `sp*` functions for shader compilation (not for reflection).
The first step is to create a `slang-deprecated.h` in `include/` directory, make `slang.h` `#include` `slang-deprecated.h`, and move all compilation related `sp*` functions + the `ICompileRequest` interface to the `slang-deprecated.h` file so new users don't get to see them in `slang.h`. We can't move `IGlobalSession::createCompileRequest` because it is inside an interface, so we may just mark the function as `[[deprecated]]` now.

This issue tracks this first step.

The next step is then to mark all functions in slang-deprecated.h as `[[deprecated]]` so users will start to receive compiler warnings. We may do this some time in 2025.

The final step is to remove everything in slang-deprecated.h, but this depends on how our users are migrated out of the C API. This will happen after 2026.

**Comment by expipiplus1** [comment]
I've confirmed that OV are no longer using any of the to-be-deprecated functions, with the exception of `spGetBuildTagString` which I think is reasonable to keep.
