### ISSUE TITLE
specializeResourceUsage emit invalid IR code

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#4763]
specializeResourceUsage could generate invalid IR code in some corner cases.

Test code is as follow:

```
RWStructuredBuffer<uint> globalBuffer[] : register(t0, space0);
RWStructuredBuffer<uint> outputBuffer;

int func(RWStructuredBuffer<uint> buffer)
{
    buffer[0] += 10;
    return buffer[0] * 2;
}

[shader("compute")]
[numthreads(1, 1, 1)]
void main(in uint2 id : SV_DispatchThreadID)
{
    uint bufferIdx = id.x;
    uint nonUniformIdx = NonUniformResourceIndex(bufferIdx);

    RWStructuredBuffer<uint> buffer = globalBuffer[nonUniformIdx];

    uint a = func(buffer);

    int bufferIdx2 = id.y;
    RWStructuredBuffer<uint> buffer2 = globalBuffer[NonUniformResourceIndex(bufferIdx2)];

    uint b = func(buffer2);

    outputBuffer[0] = a;
    outputBuffer[1] = b;
}
```
Compile the code with
`-stage anyhit -entry main -target spirv-asm -O0 -dump-ir -o test.spv.asm`.

This test code can expose 2 issues  when we legalize resource type for a function parameter:

1. The function `func` will finally be legalized to `uint func(int)`, however we didn't make the type cast from `uint` to `int` for variable `nonUniformIdx`. This will finally emit invalid spirv code because of the type mismatch. This can be easily observed by running `spirv-val` on the spirv code.
2. In the IR code,  we evaluate the `NonUniformResourceIndex()` right before the call site of `func()`, this will bring an issue that we will not be able to decorate the correct inst to `NonUniform` inside the function of `func()`. So we should evaluate the `NonUniformResourceIndex()` inside  `func()` function, such that the emit logic will know which inst to decorate to `NonUniform`.

**Comment by csyonghe** [comment]
Can you further simplify down this repro to the minimum?

**Comment by kaizhangNV** [comment]
Sure, simplify it.
