### ISSUE TITLE
Default implementation of interface methods and extensions of interfaces

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#480]
The current front-end checking allows an `extension` of an interface type, but we wr missing some details required to make things work:

* When looking for conformance requirement witnesses during checking of a concrete type, we should allow the defaults from an interface extension to apply it and only if the concrete type (or an extension of it) doesn’t provide an implementation.

* During IR code generation we need to lower concrete method implementations on an interface into generic methods (with generic paramteters for the `ThisType` and its witness table for conformance to the interface)

* When lowering a concrete witness table, any entry that refers to a default implementation needs to lower to a `specialize` of the generic method described above.

The biggest catch in all of this is that we need to distinguish between a reference to the declaration of an interface *requirement* an a reference to a default *implementation* or that requirement. So long as we only allow default implementations to be introduced by `extension`s, then we can hopefully tell the two apart: requirement decls are on the `interface` and implementations are on `extension`s.

A `ThisTypeSubstitution` has all the information we need in order to fill in the generic parameters of a default implementation, so the main thing is to figure out which of the above cases we are in and either emit a `lookup` or a `specialize`.

(We could in principle emit even an interface requirement as a generic method that is a “dispatcher,” and thus simplify code gen at call sites, at the cost of more functions in the call chain to the code that does the real work)

If we ever allow for more general notions of “virtual” declarations, then a `virtual` method would need a way to distinguish between the method as a requirement (a key for lookup) and as an implementation (to be referenced in a witness table).

A more subtle challlenge when it comes to defaults is how to handle defaults for associated types. If an interface extension provides defaults for an associated type plus related methods, then a concrete implementation that “overrides” the associated type would also need to override those methods to get the signature right.

This implies that conformance checking needs to “lock in” the associated types first, so that their concrete realization can be used to check method signatures. Of course, the flip side would be that it is really convenient if the front-end can infer the right associated type from the method declarations.

All of this is dependent on finishing up the IR-level type system, but it seems to be a high priority when that work is complete.

**Comment by tfoleyNV** [comment]
As I dig into the problem of getting `extension`s of an interface to apply to concrete types implementing that interface, I’m realizing that we kind of want to treat an extension of an interface:

```
extension IFoo : IBar { ... }
```

as if it were a generic extension for any type that conforms to the interface:

```
extension<F:IFoo> F : IBar { ... }
```

In the latter case it is immediately clear why methods in the `extension` would lower to generic functions in the IR. It is also more clear how a decl-ref to the `extension` (or a member in it) would include the information about the concrete type doing the conforming.

The catch is that we can’t easily desugar a non-generic declaration into a generic one with the way we handle semantic checking today.

Possibly the easiest way to handle this is by allowing a `ThisTypeSubstitution`, or something like it, to be used when referring to an `ExtensionDecl`, to clarify the exact target type.

**Comment by tfoleyNV** [comment]
The ability to write an `extension` that applies to an `interface` type is coming up as an important feature, and without it the demand for things like inheritance will only be higher.

As per the most recent comment in this thread, there is a question of how to interpret an extension of an interface type: is it an extension of the existential type for the interface, or a generic extension of all types that implement the interface (or both!)?

Allowing an `extension` of an `interface` to provide implementations of interface requirements is perhaps a secondary concern right now, compared to allowing utility functions to be retroactively added to interface types.

**Comment by natduca** [comment]
Putting this in summer where we've put some other language cleanup topics

**Comment by csyonghe** [comment]
extensions to interface types is already supported. Should open new issue for any further improvements.
