### ISSUE TITLE
Readme updates?

### ISSUE THREAD

**Issue by dg0yt** [shader-slang/slang#4806]
https://github.com/shader-slang/slang/blob/9b580e58417a77109617804362be872f05885f23/README.md?plain=1#L39-L40

32 bit seems to be gone. arm64 and macOS is present.

https://github.com/shader-slang/slang/blob/9b580e58417a77109617804362be872f05885f23/README.md?plain=1#L103

The linked repo is archived.

**Comment by expipiplus1** [comment]
Thank you for noticing these.
