### ISSUE TITLE
Add initial support for WGSL output

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4807]
This is meant to start addressing issue #4477.

Add support for generating some valid WGSL code for a few very simple shaders, e.g. the ones [here](https://aleino-nv.github.io/issues/4483/results2.html).

Broadly go through the Slang spec (looking at the HLSL spec where Slang detail is missing), and make sure that all of the basic language constructs generate ok WGSL.

**Comment by aleino-nv** [comment]
@csyonghe Any opinions on what we should do with int8_t and uint8_t? WGSL doesn't support 8 bit integer types.

**Comment by csyonghe** [comment]
We should extend our capability system to report errors when trying to uses these types on wgsl. For now just diagnose an error during emit when you see these opcodes.

**Comment by aleino-nv** [comment]
@csyonghe There is also f16, which requires an [extension](https://www.w3.org/TR/WGSL/#extension-f16) in WGSL.
Extensions are enabled in WGSL source using the `enable` directive.

- How should we deal with this in Slang?
  - Should we have a f16 capability that the user must opt in to?
  - Do we silently generate the `enable` directive if `f16` is generated anywhere?

**Comment by csyonghe** [comment]
Yes, we will silently emit that enable directive for now. Check for how this is handled in glsl emit, and we should be able to follow the same technique.

**Comment by aleino-nv** [comment]
I haven't pushed anything to the main branch yet -- I'm still rebasing stuff as the initial WGSL support matures in [my local branch](https://github.com/aleino-nv/slang/tree/aleino/wgsl). I'd say this task is done, at least locally.

I don't want to close the task before I commit, so I will leave it open for now.

**Comment by aleino-nv** [comment]
Another issue is that WGSL [doesn't support matrices with entries of integer type](https://www.w3.org/TR/WGSL/#matrix-types).

**Comment by aleino-nv** [comment]
This has been split into issues #4930, #4931, #4932, #4933, #4934, #4935, #4936, #4937, #4938 and #4939 for more fine-grained tracking.
