### ISSUE TITLE
Harden WGSL emitter

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4810]
This is meant to be completed before closing issue #4477.

The task is to go through the whole WGSL syntax specification carefully and try to find input Slang code that would generate broken WGSL code.
For each case of broken WGSL code, we should either forbid some parts of that Slang input (with nice error messages), or else fix the WGSL emitter.

**TODO:** Go through the WGSL spec and add more to this list of potentially broken WGSL here

- Possible to break at the character decoding stage?
- Possible to break at the tokenization stage? 
- Possible to break due to WGSL-reserved keywords?
- Can Slang generate non-constexpr case selectors? That's [not allowed in WGSL](https://www.w3.org/TR/WGSL/#syntax-switch_body)
- WGSL doesn't support int8_t, uint8_t, and double (f64), so we should catch and report use of these types _using the capability system_.
- Deal with [limits](https://www.w3.org/TR/WGSL/#limits)
- Array access expressions on vec types. Seems to be allowed in Slang but not WGSL https://www.w3.org/TR/WGSL/#array-access-expr

**Comment by bmillsNV** [comment]
@aleino-nv can we close this one now? I think you broke down WGSL already?

**Comment by aleino-nv** [comment]
@bmillsNV None of these items have really been investigated. 

These are issues of the sort "I haven't seen these issues, but I'd expect them to be possible to trigger".
I've been adding items to this list as they randomly occur to me while working on other things.

I can track this kind of thing somewhere else instead, if it's just adding noise in the issue tracker. Feel free to close if you want, or add some appropriate label.

**Comment by bmillsNV** [comment]
Let's close this and open issues for individual items as they come up and we need to address.
