### ISSUE TITLE
"macos-aarch64" package from the release works for Intel chip but not for M3 chip.

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4812]
**Problem description**
When I download the binary release package for macos-aarch64, slang-test passes on all tests even when they should fail.
This was due to the fact that slang-llvm was not actually working; and tests are reported passing incorrectly.

It turned out that the release binary works fine for MacBook Pro 2019 that uses an Intel chip.
But it doesn't work when the chip is M3.

A workaround for this is to locally rebuild slang-llvm when the hardware uses M3 chip.

The issue appears to be limited only to slang-llvm binary; not slangc or other binaries in the release package.

**Goal**
Because the package name has "aarch64" suffix, the binary package should run on M3 chip.

**Comment by jkwak-work** [comment]
@expipiplus1 , do you have any guesses of why this is happening?

**Comment by expipiplus1** [comment]
This should be fixed by https://github.com/shader-slang/slang/pull/4847 If you could give this a test please :)
