### ISSUE TITLE
Slang emits non-constant case expressions

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4834]
Slang doesn't seem to catch non-constant case expressions, as in the following example.

`slangc -o output.glsl -target glsl -stage compute -entry computeMain input.slang`

**input.slang:**

    StructuredBuffer<int2> buffer;
    RWStructuredBuffer<int2> result;

    [shader("compute")]
    [numthreads(1,2,3)]
    void computeMain()
    {

        int2 r = int2(0,0);
        switch(buffer[0].x)
        {
    
        default:
        {
           r.x++;        
        } break;

        case buffer[0].y: // Non-constant case expression `buffer[0].y`
        {
           r.y--;        
        } break;

        }

        result[0] = r;
    }

**output.glsl:**

    #version 450
    layout(row_major) uniform;
    layout(row_major) buffer;
    
    #line 1 0
    layout(std430, binding = 0) readonly buffer StructuredBuffer_vectorx3Cintx2C2x3E_t_0 {
        ivec2 _data[];
    } buffer_0;
    
    #line 2
    layout(std430, binding = 1) buffer StructuredBuffer_vectorx3Cintx2C2x3E_t_1 {
        ivec2 _data[];
    } result_0;
    
    layout(local_size_x = 1, local_size_y = 2, local_size_z = 3) in;
    void main()
    {
        ivec2 r_0 = ivec2(0, 0);
        switch(buffer_0._data[uint(0)].x)
        {
        case buffer_0._data[uint(0)].y:
            {
    
    #line 20
                r_0[1] = r_0[1] - 1;
                break;
            }
        default:
            {
    
    #line 15
                r_0[0] = r_0[0] + 1;
                break;
            }
        }
    
    #line 25
        result_0._data[uint(0)] = r_0;
        return;
    }

**Comments**

The output `case buffer_0._data[uint(0)].y` is the problem. Having non-constant case expressions like `buffer_0._data[uint(0)].y` makes no sense, and Slang should probably catch this with some backend-agnostic check.

**Comment by bmillsNV** [comment]
P2 for now, not blocking anyone. Q4

**Comment by csyonghe** [comment]
I believe this is already fixed.
