### ISSUE TITLE
Default visibility not always working

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#4946]
The docs say "internal is the default visibility", but it seems like in this case I still get an ambiguous reference error. Adding internal to the typealias fixes this.

```cpp
// header.h
#pragma once
typealias int_type = int;

// mymodule.slang
#include "header.h"

// main.slang
import mymodule;
#include "header.h"
StructuredBuffer<int_type> inputBuffer; // error 39999: ambiguous reference to 'int_type'
```

For some reason adding another definition with a visibility of internal like the following to the header fixes the problem, even though the first is unchanged. This even works when the second one is set to public. Seems like there needs to be at least one entry with the visibility set to something for this to work correctly.
```cpp
// working
typealias int_type = int;
internal typealias int_type2 = int;
```

**Comment by csyonghe** [comment]
Note that visiblity is related to module boundary, and not file boundary.

#include is just string pasting, so the compiler will always see duplicate definitions.

Users are avdvised to avoid #include whenever possible, and use `import` instead.

**Comment by csyonghe** [comment]
And also, modules should always begin with a `module name;` declaration.
Without it, Slang treats the module as it is written in "legacy language".

In "legacy language", everything is `public`.

If you used any visiblity modifiers in the module, that also makes slang treat it as non-legacy.

**Comment by fknfilewalker** [comment]
I thought, since `#include` in the module just pastes the code, the visibility should be the default module visibility in this example. Also thought that `.slang` on its own means it is a slang module. Your explanation makes total sense to me though.

I need the #include for preprocessor defines (not aware of a way to do this with modules) and stumbled upon this since, even though I had a #pragma once in the beginning of the header I got this collision with some typealiases.
