### ISSUE TITLE
AbortCompilationException doesn't include an error message

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#495]
I had an exception thrown due to a "function redefintion" error, but no error message was reported out the the caller. See diagnostics.cpp:221

Also for the error "function redefinition" it'd be useful to include the function name in the message...

The error was due to missing include guards on a .hlsli file included from two different other include files.

**Comment by tfoleyNV** [comment]
The exception is usually thrown in cases where a code path is unimplemented/unhandled behavior, so the exact message isn’t always meant to be consumable by the user. Still, it would be good to include that but in the output anyway, to help isolate bugs.

In this case of course, the message should have been a real error.

**Comment by tfoleyNV** [comment]
PR #517 should have improved the messages we give when compilation is aborted, and those changes should be live in `v0.10.13` and later.
