### ISSUE TITLE
Vulkan CTS passing rate is not 100%

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#4959]
Currently we are running only small portion of the Vulkan CTS tests every day.
When ran for the full tests, the passing rate is currently at 31.00%.

We probably want to aim for 100% in a long term.
[vk-cts-passing.xlsx](https://github.com/user-attachments/files/16789538/vk-cts-passing.xlsx)

![image (1)](https://github.com/user-attachments/assets/66716bc1-dbcf-45dd-8685-a03cc5f28dac)

Note that each group has different number of tests.

**Comment by csyonghe** [comment]
As of now, Slang's GLSL support is aimed only at helping users to migrate from existing codebase, not to provide 100% compliance with glsl spec. This means that we have never set our goal to reach 100% in Vulkan CTS. However we should at some point do a round of triaging and identify all the low hanging fruits to improve the passing rate a bit more.

**Comment by bmillsNV** [comment]
We'll use #3998 to track CTS expectations for GLSL in Slang. Closing this issue.
