### ISSUE TITLE
Dynamic Resources?

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#4969]
Is there a way to use dynamic resources in slang?
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_DynamicResources.html

Or aliasing e.g.,
```rust
[vk_binding(0, 0)] Texture2D<float> inputTexture[];
[vk_binding(0, 0)] Sampler2D<float> inputSampler[];
```
though this gives me warnings:
```
warning 39001: explicit binding for parameter 'inputTexture2' overlaps with parameter 'inputTexture'
[vk_binding(0, 0)] Sampler2D<float> inputSampler[];
                                    ^~~~~~~~~~~~~
textures_test.slang(4): note: see declaration of 'inputTexture'
[vk_binding(0, 0)] Texture2D<float> inputTexture[];
```

Is there a better way? I saw that there are these types in slang `__DynamicResource, __IDynamicResourceCastable, __DynamicResourceKind` maybe they can be used for this, but I can not find anything about them?

My goal is to just have a single image array which contains all the different image types e.g., sampler2d, texture2d, cube... and can then be later casted to one of these types.

Edit: Just tried this
```rust
outputBuffer[0] = reinterpret<Texture2D<float>>(inputSampler[0]).Load(int3(0, 0, 0));
```
but this gives me
```
internal error 99999: unimplemented feature in Slang compiler: unexpected IR opcode during code emit
```

Edit2: I did come up with something that seems to work
```rust
[vk_binding(0, 0)] RWStructuredBuffer<float> outputBuffer;
[vk_binding(1, 0)] __DynamicResource<__DynamicResourceKind::General> inputResources[];

[shader("compute")]
[numthreads(1, 1, 1)]
void main(uint3 dispatchThreadID: SV_DispatchThreadID)
{
    float a = Texture2D<float>(inputResources[0]).Load(int3(0, 0, 0));
    int b = Texture2D<int>(inputResources[1]).Load(int3(0, 0, 0));
    outputBuffer[0] = a + b;
}
```

**Comment by csyonghe** [comment]
Yeah, you discovered `__DynamicResource`, which what we are currently at in supporting dynamic resources. We plan to expand that into full bindless support, but you can certainly just use __DynamicResource for now.
