### ISSUE TITLE
IR type system is failing to handle RayDesc properly

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#497]
Somehow, a local variable with the `RayDesc` type is ending up with a null type (or rather, a pointer type with a null operand). This needs to be fixed, but if hilights a gap in the IR type system work in cases where a “built-in” type is actually a for-real `struct`.

We ideally want such a type to be represented as an IR struct, with decorations that identify it as s builtin. At that point, however, I start to wonder again about whether we are making the right call giving most builtin types their own IR opcodes instead of encoding them as IR struct types just like ordinary user-defined types (these are ones that just happen to be provided by the standard library).

**Comment by pclarberg** [comment]
There is also BuiltInTriangleIntersectionAttributes, HLSL supports using that without having a struct declaration in the code

**Comment by tfoleyNV** [comment]
This should be fixed by #498.
