### ISSUE TITLE
Invalid Slang Code-Generation

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4971]
Problem:
With the provided shader attached below, when compiled, the following is observed: 
1. Slang will compile invalid HLSL.
`static RWStructuredBuffer<int > test_val_0;` is created and assigned to nothing.

2. Slang will compile invalid SPIR-V.
```
error: line 24: In Logical addressing, variables may not allocate a pointer type
  %test_val = OpVariable %_ptr_Private__ptr_StorageBuffer_RWStructuredBuffer Private
```

3. Slang will ASSERT when compiling GLSL.
ASSERT while attempting to emit `IRHLSLStructuredBufferTypeBase`, which is invalid for GLSL targets.

Expected:
if this the repro-shader is an incorrect use-case: Slang warns/errors without creating invalid code-gen.
if this the repro-shader is a correct use-case: Slang should compile the code correctly.

To Repro:
1. Compile the shader below 3 times, 1 for each target: `-target glsl -entry computeMain -stage compute myTestShader.slang` and `-target hlsl -entry computeMain -stage compute myTestShader.slang` and `-target spirv -entry computeMain -stage compute myTestShader.slang` 

```
// myTestShader.slang
struct Test {
    RWStructuredBuffer<int> val;
    __subscript(int x, int y)->int
    {
        get { return val[x * 3 + y]; }
        set { val[x * 3 + y] = newValue; }
    }
}
Test test;

[shader("compute")]
[numthreads(32, 1, 1)]
void main(uint3 dispatchThreadID: SV_DispatchThreadID) {
    test[1,1] = 1;
}
```

**Comment by csyonghe** [comment]
We already have the logic in the compiler to say that if a global or entrypoint parameter is resource-typed, then we mark it as `uniform`.

We need to extend the logic to cover both resource-typed and structure-typed (with resource elements) parameters.

**Comment by csyonghe** [comment]
For structure-typed parameters, we should just make it an error if it contains resource fields.
