### ISSUE TITLE
WGSL: Handle arrays of global shader parameters

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4987]
Global parameters like `RWStructuredBuffer<int> buffers[3];` (found in e.g. tests/compute/loop-unroll.slang) currently translate to `var buffers : array<ptr<storage, array<i32>, read_write>, i32(3)>;` in WGSL.

However, arrays of pointers [aren't allowed in WGSL](https://www.w3.org/TR/WGSL/#array-types).

**Comment by aleino-nv** [comment]
I ran into this while investigating #4932.

**Comment by aleino-nv** [comment]
It seems you can't have ptr's in structs in WGSL either...

@csyonghe Do you have ideas on how to work around this?

I suppose one could always "unroll" the array as follows...

    // unrolled RWStructuredBuffer<int> foo[3]
    var<storage, read_write> foo_0 : array<i32>;
    var<storage, read_write> foo_1 : array<i32>;
    var<storage, read_write> foo_2 : array<i32>;

...and then pass around integer "arrayIDs" instead of arrays-of-pointers, and write functions taking two integers (one array ID and one element index) to access the array elements...

**Comment by csyonghe** [comment]
Buffers are not allowed in structs for all most all targets we support. You need to make sure the type legalization and resource legalization passes are run for wgsl like it is for spirv to hoist these things out of structs first.

**Comment by aleino-nv** [comment]
> Buffers are not allowed in structs for all most all targets we support. You need to make sure the type legalization and resource legalization passes are run for wgsl like it is for spirv to hoist these things out of structs first.

Yes, I'm pretty sure that is happening.

Yong, do you have suggestions on how to deal with `RWStructuredBuffer<int> buffers[3];`?

**Comment by csyonghe** [comment]
all of these is handled by our legalizeResourceTypes pass.

You can try this with our glsl/hlsl backend to see how it is handled there.

**Comment by csyonghe** [comment]
The tldr is I don't think you need any additional logic for wgsl, just make sure wgsl backend runs the same set of legalization passes we were running for spirv/glsl.

**Comment by csyonghe** [comment]
See source/slang/slang-emit.cpp:949 and all the other legalization passes around those lines and make sure they are also enabled for web gpu.

**Comment by aleino-nv** [comment]
Oh I see, thanks! I may not get to this immediately but I'll have a look when I get some time.

**Comment by bmillsNV** [comment]
We're pretty sure that this isn't possible in WGSL. Closing for now. Please reopen if there is a way to support arrays of buffers.

**Comment by aleino-nv** [comment]
This now also affects `tests/compute/buffer-type-splitting`
