### ISSUE TITLE
Handle type conversion on `out` and `inout` arguments

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#499]
Right now if you have code like this:

```hlsl
void test(out uint a) { a = 3; }
void broken()
{
    int b = 0;
    test(b);
}
```

The Slang compiler crashes during lowering, because it applies implicit conversion to the `b` argument, yielding something like `uint(b)` and then in order to handle the `out` argument, it needs to assign from the function output value to `uint(b)` and at that point it recognizes that the expression isn't an l-value.

A quick fix would be to make the front-end checking for l-values actually catch this case (it seems like our l-value checking must be lax right now). That would diagnose an error and avoid the crash, but that isn't the semantics an HLSL user expects.

The better fix requires recognizing this case and introducing something like a "bidirectional cast" expression into the AST (or an "output cast" expression in this case). Such an expression would be usable as an l-value, but would apply conversion on the output side. This is a more complex fix, of course, but it would also enable us to handle things like compound assignment operators with conversion more cleanly.

**Comment by csyonghe** [comment]
Closing the issue since we already diagnose on type conversion.
We can open another issue if we need to support type conversion on calls.
