### ISSUE TITLE
Support HLSL's default initialization idiom

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#500]
It is gross and makes no sense, but it is idiomatic HLSL to default-initialize a `struct` type as follows:

```hlsl
SomeStructType s = (SomeStructType)0;
```

We can try to special-case this by detecting a cast expression where the argument is a literal zero, and the target type is a `struct` without explicit initializers.

I'd like to diagnose a warning in these cases and push users towards better idioms, but such better idioms would mostly rely on additional compiler support from Slang.

**Comment by pclarberg** [comment]
I'd prefer if it issues a warning/error, and supports: StructType s = {} without a warning.

**Comment by csyonghe** [comment]
Closing because this is implemented.
We still need to diagnose a warning.
