### ISSUE TITLE
Compilation Warning Related to Uninitialized Variable

### ISSUE THREAD

**Issue by karel-tomanec** [shader-slang/slang#5005]
**Issue Summary:**
The provided code produces the following compilation warnings:
`warning 41016: use of uninitialized variable ''  tanTransform = GetNormalTangentSpaceMat(normal, inRay);`

Code Snippet:
```
struct TanSpace
{
    static const float3 localN = {0,1,0};
    float4x4 tanTransform;
    float3 geometryNormal;
	
    __init(in float3 normal, in float3 inRay)
    {
        tanTransform = GetNormalTangentSpaceMat(normal, inRay);
        geometryNormal = localN;
    }

    float4x4 GetNormalTangentSpaceMat(in float3 normal, in float3 inRay)
    {
        // Implementation omitted for simplicity
        return float4x4(0.f);
    }
}
```

**Workaround:** 
If I change the method `GetNormalTangentSpaceMat` to `static`, the warning disappears.

**Comment by csyonghe** [comment]
The implicit `this` variable should be considered as initialized inside a constructor.
We can make this work by having a `IRTreatAsInitialized(x)` inst, whose purpose is to mark `x` as initialized, and then we make sure to emit this inst during lower to ir for implicit `this` variable inside a ctor.
