### ISSUE TITLE
Allow implicit vector truncation (with a warning)

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#502]
There is enough code at there that expects `float4` to implicitly convert to `float3` that we need to either support it, or include a very detailed diagnostic that says something like "implicit vector truncation is not supported" (which would involve doing 99% of the work required in supporting the feature).

**Comment by pclarberg** [comment]
I think it should be supported, but issuing a warning (not error) to the user.

**Comment by pema99** [comment]
Any chance this could be revisited, but perhaps put behind an opt-in flag? Especially with float4->float3 conversion, there's a lot of HLSL code out there that does it.
