### ISSUE TITLE
Incorrect specialization for modulo operator

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#5026]
In this example, the `%` operator is being specialized as `frem` when it's actually operating on `int`, it should be translated to `srem`

```hlsl
//TEST(compute):COMPARE_COMPUTE(filecheck-buffer=CHECK):-vk -output-using-type

// CHECK: type: int32_t
// CHECK-NEXT: 0
// CHECK-NEXT: 0
// CHECK-NEXT: 0
// CHECK-NEXT: 0

//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):out,name=outputBuffer
RWStructuredBuffer<int> outputBuffer;

T myMod<T : __BuiltinArithmeticType>(T x, T y)
{
    return x % y;
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    int c = 1;
    int d = 1;
    outputBuffer[dispatchThreadID.x] = myMod(c,d);
}
```

```lua
[readNone]
[nameHint("myMod")]
func %myMod     : Func(Int, Int, Int)
{
block %19(
                [nameHint("x")]
                param %x        : Int,
                [nameHint("y")]
                param %y        : Int):
        let  %20        : Int   = frem(%x, %y)
        return_val(%20)
}
```

**Comment by jkwak-work** [comment]
Isn't frem correct?
What is the expected behavior for this?

In HLSL, operator% is same as `fmod`, which returns a remainder not modulo.
Doesn't Slang follow the same rule of operator% in HLSL?

**Comment by jkwak-work** [comment]
I think this issue contradicts to one of already resolved issue.
https://github.com/shader-slang/slang/issues/1059

**Comment by expipiplus1** [comment]
> Isn't `frem` correct?...

This isn't about that difference, it's that we're emitting a floating point operation for integer types, compare to just using the `%` operator not in a generic function
