### ISSUE TITLE
Support default initialization via initializer list syntax

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#503]
We currently support initializer list syntax, as long as the list has as many elements as the destination has elements/fields. We should extend this to support leaving off elements from the initializer list to indicate that any elements/fields after that point should be default-initialized (where “default-initialized” is just zero-initialization for now).

One instance of the above rule is that an empty initializer list (`{}`) should be usable to default-initialize any `struct` or array type.

Two issues to contend with in the long run:

1. What should the behavior be for types with either explicit initializers operations, or per-field initializers? When should initializer lists be supported if the user has started to define the behavior of a type more tightly?

2. What should default initialization mean for opaque types like `Texture2D` or composite types that transitively contain opaque types? We can either give an error when an attempt is made to default-initialize them, or we can say that their default value is “uninitialized”.

**Comment by jsmall-nvidia** [comment]
We may want to support the hlsl style initialization of (TypeName)0; This isn't great syntax and perhaps should only be accepted if hlsl is the source language, on slang input it could display a warning. 

The slang preferred style is probably = {}, unfortunately this is currently not supported on dxc or fxc. So making it slang happy would mean source wouldn't compile on fxc, or dxc without the (TypeName)0 syntax.

**Comment by csyonghe** [comment]
This is already implemented.
