### ISSUE TITLE
Extending __subscript with set fails

### ISSUE THREAD

**Issue by tunabrain** [shader-slang/slang#5034]
It looks like it's not possible to extend `__subscript` to add e.g. a `set` portion conditionally.

Say I had the following interfaces for abstracting things that allow reading/writing at an index:
```
interface Readable<T>
{
    T read(int i);
}
interface Writable<T> : Readable<T>
{
    void write(int i, T t);
}
```
For convenience I want to support `[]` access that internally calls read/write. I can't put code in the interface, but I can use an extension like this:
```
__generic<S, T : Readable<S>>
extension T
{
    __subscript(int i)->S
    {
        get { return read(i); }
    }
}
__generic<S, T : Writable<S>>
extension T
{
    __subscript(int i)->S
    {
        set { return write(i, newValue); }
    }
}
```
This works for reading:
```
T readAtZero<T>(Readable<T> x)
{
    return x[0];
}
```
But not writing:
```
void writeAtZero<T>(Writable<T> x)
{
    // ambiguous call to 'operator[]' with arguments of type (int)
    x[0] = 1.0f;
}
```
I think this is because `__subscript` as a whole is treated as a function, and not `get` / `set` individually. The extension then adds a competing `__subscript` rather than supplying a complementary `set` method.

Extensions involving `__subscript` are a useful pattern, is it possible to support this case?

**Comment by csyonghe** [comment]
Yes, it should be possible to support this.
