### ISSUE TITLE
Generic associatedtype

### ISSUE THREAD

**Issue by tunabrain** [shader-slang/slang#5036]
This is a feature request for generic `associatedtype`s.

The simplified use case looks something like this: I have an interface with a method that returns an interface type, but with different parameters:
```
interface IStack<let D : int>
{
    IStack<D-1> pop();
}
```
However, I'd like to know the concrete return type of `pop`, rather than just the interface type `IStack`.

For these kinds of use cases, Slang supports the `This` keyword in interfaces, which can refer to the concrete type that implements the interface. However, (for obvious reasons) I can't do e.g. `This<D-1> pop();` to say "The same concrete type but with different generic params".

However, I can solve this with an `associatedtype`:
```
interface IStack<let D : int>
{
    associatedtype PoppedStack : IStack<D - 1>;
    PoppedStack pop();
}

struct StackImpl<let D : int> : IStack<D>
{
    typealias PoppedStack = StackImpl<D - 1>;
    PoppedStack pop() { /* ... */ };
}
```
This is useful e.g. when `IStack` shows up as a generic parameter for something else:
```
struct StackHaver<let D : int, S : IStack<D>>
{
    S stack;
    StackHaver<D - 1, S::PoppedStack> pop()
    {
        return { stack.pop() };
    }
}
```
However, I can't do this if I want pop itself to be generic to specify e.g. the number `N` of elements to remove. I would need something like a generic `associatedtype`:
```
interface IStack<let D : int>
{
    // associatedtype is not allowed here
    __generic<let N : int>
    associatedtype PoppedStack : IStack<D - N>;

    __generic<let N : int>
    PoppedStack<N> popN();
}
```
The context for this is that I have a tensor interface that is generic in the number of dimensions `D`. I want to be able to slice tensors, i.e. index a `D`-dimensional tensor with an `N`-dimensional index to return a `D-N` dimensional slice of the tensor. However, specifying this in the `ITensor` interface is difficult.

**Comment by csyonghe** [comment]
There shouldn't be any reason why this can't be supported. I'll investigate a bit on how it may be implemented.

**Comment by csyonghe** [comment]
After some prototyping, I find this is going to add too much complexity to the compiler so the decision is not to add this right now. Let us know if you run into situations that can't be solved without generic associated types.
