### ISSUE TITLE
slang-test: Add support for WGSL

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5051]
We should be able to run slang-test targeting wgpu and wgsl-spirv-asm

**Comment by aleino-nv** [comment]
Blocked on #5052

**Comment by jkwak-work** [comment]
I like to say this is only partially blocked by #5052.
slang-test should still be able to invoke the downstream compiler without running the shader on the HW.
Basically we need a compiler target, "-target wgsl-asm" for WGSL like what Metal has with "-target metallib".

**Comment by aleino-nv** [comment]
Yeah, I wasn't aware of the wgsl-asm option... In any case, we do need RHI for full testing that runs shaders.

**Comment by aleino-nv** [comment]
The CI part of this is now tracked in https://github.com/shader-slang/slang/issues/5233
