### ISSUE TITLE
Testing of geometry shaders

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#506]
We've had multiple regressions over time in the Falcor `Shadows` sample, and a big cause for this is that the sample uses geometry shaders and none of our testing covers them, so it is often the first thing to run into any issues. The `Shadows` app in really complicated, though, so it isn't a great place to go about diagnosing and fixing bugs.

We ideally need some configuration in `render-test` that can drive a GS in both D3D and Vulkan, and give us some confidence we are translating them correctly.

**Comment by natduca** [comment]
This should come up in our testing scoping discussion in a more directed way so closing this as dropped.
