### ISSUE TITLE
`uint64_t4` missing from Metal backend

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#5062]
According to the [Metal spec](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf), there is no uint64_tN type. However, there are `ulong4`'s which are 32 bytes total (8 bytes per component). 

At the moment, Slang appears to map `vec<uint64_t, 4>` to `uint64_t4`, which is causing certain shaders to generate compilation errors. This is causing the tests for PR #5020 to fail. 

Could we have vectors of 64-bit integers map to Metal's ulongN types?

**Comment by natevm** [comment]
Looks like we can fix this by adding a little logic to slang-emit-metal.cpp: https://github.com/shader-slang/slang/pull/5020#issuecomment-2350105204

I'll should be able to fix this.

**Comment by natevm** [comment]
PR #5020 has a fix for this issue as part of the bitfield intrinsics. Once that’s merged, we can close this issue.

**Comment by csyonghe** [comment]
This is fixed. We now always emit `long` for `int64_t` and `ulong` for `uint64_t` on metal.
