### ISSUE TITLE
Missing return function causes compiler crash

### ISSUE THREAD

**Issue by Ipotrick** [shader-slang/slang#5063]
This code compiles but should not:
```
struct ReproPush
{
    daxa_u32 some_value;
};
[[vk::push_constant]] ReproPush p;
[[vk::binding(0, 0)]] RWTexture2D<float4> texture;

func inner() -> float4
{
    switch (p.some_value)
    {
        case 0: return texture[uint2(0,0)];
    }
}

[shader("compute")]
[numthreads(1,1,1)]
func entry_repro()
{
    texture[uint2(0,0)] = inner();
}
```
As you can see there is no return in the case that "some_value" is not equal to 0.
This code also generates a driver compiler crash on the latest nvidia ada gpu driver.

Config:
```
Slang Version: 2024.9
pc platform: x86-64msvc windows11
gpu: RTX 4080
nvidia driver version: 560.94 (game ready, not studio driver)
slang::TargetDesc::format: SlangCompileTarget::SLANG_SPIRV
slang::TargetDesc::profile: glsl_450+spirv_1_4
slang::TargetDesc::flags: SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY
slang::TargetDesc::forceGLSLScalarBufferLayout = true
slang::SessionDesc::defaultMatrixLayoutMode: SLANG_MATRIX_LAYOUT_COLUMN_MAJOR
```

I know it can be very tricky to analyse and find all the missing returns but i think this is a particularly simple case that fails.

**Comment by csyonghe** [comment]
In this case slang already issues a warning:
```
tt.slang(8): warning 41010: control flow may reach end of non-'void' function
func inner() -> float4
     ^~~~~
```
If you wish to make it an error, you can use `-warnings-as-errors 41010` option to `slangc`.

**Comment by csyonghe** [comment]
Closing this issue since we have a warning that users can enable as error.
We can't make it an error by default for now since it could break existing code on platforms where this isn't a hard error.
