### ISSUE TITLE
WGSL: Memory layout

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5066]
Define the WGSL memory layout properly, so that Slang introspection can provide proper layout description to applciations

- Memory layout:
  - Two cases:
    - Uniform buffers
    - Storage buffers
- Parameter layouts (assigning bindings)
  - Look at how it's done in GLSL

**Comment by bmillsNV** [comment]
Can likely be closed. Should be tested by Compute test cases already.
