### ISSUE TITLE
WGSL: Intrinsics: texture

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5082]
15 functions

**Comment by aleino-nv** [comment]
@jkwak-work The texture-related functionality seems pretty complex and looks like it's leaning on a lot of Slang-specific functionality. I'm assigning this to you since you're in Yong's timezone -- I have a feeling this will require some amount of consultation.

**Comment by jkwak-work** [comment]
No worries, I spend good amount of time working on texture side things for Metal and GLSL.
I will be a good fit for this task.
