### ISSUE TITLE
Compile Slang to web assembly.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#5092]

**Comment by jkwak-work** [comment]
What would take to get this working?

**Comment by csyonghe** [comment]
1. Setup emscripten build toolchain and use it to build the slang.dll
2. Fix all compile errors and system library dependencies so things to work. Mostly we need some work on the filesystem calls.
3. Figure out how to export slang.dll symbols as web assembly interfaces. C functions should work just fine but we need a way to export all of our COM interfaces to something callable from javascript.
4. Integrate this into CI and make our releases include webassembly builds.
5. Figure out how to reduce our stdlib to not include decls not needed for webgpu so the total binary size is small, targetting <5MB.

**Comment by tangent-vector** [comment]
For (5) in the list there, we could conceivably walk the decl hierarchy and strip out any public API that isn’t usable on that target based on capabilities. We should be able to strip the IR for the stdlib the dams basic way.

**Comment by aleino-nv** [comment]
This all makes sense but why is this in the current sprint? This is needed for WGSL/MS4 and we are working on MS1 now.

**Comment by csyonghe** [comment]
We put it in current sprint because we think the intrinsic work would be done soon with Jay and me helping, so we can free you to work on this early.

**Comment by csyonghe** [comment]
@aleino-nv After you've done with the misc intrinsics, the only pieces left are just textures and atomics, which will be implemented by Jay and me. There isn't much we can do about testing without rhi, and I consider vertex/fragment support to be lower risk than web-assembly compilation, so let's try to derisk things early.

**Comment by aleino-nv** [comment]
Split into #5115 #5116 #5117 #5118
