### ISSUE TITLE
WGSL: Add Tint as downstream compiler

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5104]
This is required for "wgsl-asm testing"

**Comment by jkwak-work** [comment]
I am going to continue on the branch @aleino-nv had worked on.
https://github.com/aleino-nv/slang/tree/aleino/tint

**Comment by aleino-nv** [comment]
The plan is to create a slang-tint repo, and do a build of slang-tint.dll with a minimal downstream compiler interface, so as to not have to pull in the recursive git repos needed for Tint.

**Comment by jkwak-work** [comment]
I think it will be similar to how we generate slang-llvm.dll.

**Comment by aleino-nv** [comment]
I did a release of Tint from our existing Dawn repo. This corresponds to the same Tint baked into the webgpu_dawn.dll release from the same repo.

https://github.com/shader-slang/dawn/releases/tag/tint-0

**Comment by aleino-nv** [comment]
@csyonghe Can you describe a bit about how I would test this at the current moment? Can I invoke slangc with some WGSL code and have it use the Tint compiler?

**Comment by csyonghe** [comment]
You can create a test in tests/wgsl that starts with 
//TEST:SIMPLE(filecheck=CHECK): -target wgsl-asm
// CHECK: OpEngryPoint
