### ISSUE TITLE
Add LICENSE to slang-binaries repo

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5108]
The [slang-binaries repo](https://github.com/shader-slang/slang-binaries) currently doesn't have any license statement.

We should create a proper "LICENSE" file in the repo and combine all the license statements from binaries used in the repo.

As an example, DXC github has [a license](https://github.com/microsoft/DirectXShaderCompiler?tab=License-1-ov-file#readme) containing multiple license statements from different parts in the repo.

**Comment by bmillsNV** [comment]
@jkwak-work can you help to add the license file? Thank!

**Comment by jkwak-work** [comment]
A PR is ready for review.
https://github.com/shader-slang/slang-binaries/pull/53

**Comment by jkwak-work** [comment]
closing as completed because the PR 53 is merged.
