### ISSUE TITLE
Retrieving information from slang module

### ISSUE THREAD

**Issue by obhi-d** [shader-slang/slang#5109]
Hi,

I had a question regarding if it was possible to partially parse a .slang module and get some reflection data, specifically user attributes from some declared types ?
My end goal is to write a rasterizer shader module that can, for example, load vertex data either from an SSBO or from bindful vertex specification. I would like to use specialization constants in conjugation with an abstract interface for the vertex data to resolve the final vertex data. The idea is given a mesh + shader combination, when loading from an **StructuredBuffer**, the mesh's vertex declaration (vertex buffer slot, stride, data offset, etc) are passed through specialization constant. This makes my engine pipeline very easy to manage.
I can imagine a struct defining vertex data like so:
```hlsl
struct VertexData
{
  [binding("position")
  float3 position;
  [binding("normal")]
  uint normal;
};

[VertexShader]
void processVertex(VertexData data)
{
  // .. transform and write to SV_Position, etc.
}
```

Given that I want to have one shader for both the bindless and bindful case, I need to generate some code that, depending upon the current engine runtime, will *fill* the geometry structure.
My idea was to generate the entry point for vertex processing and read the bindings from VertexData struct, generate code inside this entry point to populate the struct and pass it to processVertex, but since this means parsing an incomplete shader, is this possible ? The alternative I have in mind is to do manual parsing of the file for all declarations, but that sort of defeats the purpose of user attributes, and increases the shader parsing cost. Another possibility, that I am currently using with glsl, is to have all declarations defined in a meta-language which I then parse.

Lastly, the idea applies not just to vertex data, but for material data too, I would like to have a way to compile both bindless and bindful path from the same shader.

Thanks for any advice.

**Comment by csyonghe** [comment]
The short answer is yes, Slang provides reflection API to query functions, types and attributes declared on these decls.
Unfortuantely we haven't write up documentation on these APIs, but you can take a look at the slang.h header to find the related functions.

**Comment by obhi-d** [comment]
Thanks, I will have a look.

**Comment by csyonghe** [comment]
Closing this issue assuming the question is answered. If you have any further questions, feel free to open new issues.

**Comment by obhi-d** [comment]
Yes, I am able to traverse the tree for a module that I parsed and retrieve all information.
