### ISSUE TITLE
Wasm build: export slang.dll symbols to Wasm interfaces

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5116]
Figure out how to export slang.dll symbols as web assembly interfaces. C functions should work just fine but we need a way to export all of our COM interfaces to something callable from javascript.

EDIT: Exporting all of our COM interfaces is neither realistic nor what we want for this task. It was agreed that we'd expose a simplified subset of the interface for WGPU, depending on the needs of the demo app.

**Comment by aleino-nv** [comment]
@csyonghe I think we have this figured out in https://github.com/shader-slang/try-slang now.

It's far from complete `slang.h` interface, but we can easily elaborate on this approach as needed in order to make our demo.

Can we call this done now?

**Comment by csyonghe** [comment]
Yes, let's close.

**Comment by aleino-nv** [comment]
Re-opening and adding one day of estimated work.
We changed our minds and decided that we want to also do the following as well:

- move what was agreed on above into the slang repo, and take another look at it there in a review
- and at the same time, not just elaborate on the above approach as needed in order to make our demo, but rather expose something more serious right away
