### ISSUE TITLE
Some problems in matrix vector product code.

### ISSUE THREAD

**Issue by GraphZou** [shader-slang/slang#5132]
I am trying to make slang compatible with older devices.
First, use Slang to generate SPIR-V, then use spirv-cross to generate a lower version of GL or GLES code.
But there is a problem with the mat4 constructed from 4 vec4s, which similar to the issue #4316 .
In older devices, we prefer to obtain mat4s rather than an array of vec4s.

**Comment by GraphZou** [comment]
Another option is to use __intrinsic_asm to generate uniforms without packing, but this compromises cross-platform capability. This can be particularly inconvenient when generating SPIR-V.

**Comment by bmillsNV** [comment]
GLES is not currently a supported target. Translating mat4 into an array of vec4 is a way to work around many restrictions in SPIR-V and we don't currently see an easy way to remove this work around. Will revisit if GLES becomes a supported target.
