### ISSUE TITLE
Wasm demo: Look into forking some existing app

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5153]
We want to use slang to emit WGSL and then show some rendering using WebGPU.

It's a bonus if the app is based on VSCode since we have some tooling that we could then leverage.

Interesting examples to consider forking:
 - https://compute.toys/ 
 - https://webgpu.github.io/webgpu-samples/
 - https://google.github.io/tour-of-wgsl/
 - https://shi-yan.github.io/webgpuunleashed/

**Comment by aleino-nv** [comment]
@swoods-nv I added a bunch of shadertoy-like apps I found. Please feel free to add more to this list if you've found some others.

**Comment by aleino-nv** [comment]
@bmillsNV Closing this one now. I think we decided to try out compute.toys.

**Comment by kaizhangNV** [comment]
Add a task: https://github.com/shader-slang/slang/issues/5293.
We need to develop functionality to compile slang shaders by using Rust if we are going to use compute toys as our playground.
