### ISSUE TITLE
Fix github release build failure

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#5183]
Need to fix the rhi/dawn issue:
```
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: _deps/dawn-src/lib64/libdawn.so: error adding symbols: file in wrong format
```
We should consider just build libdawn.so for aarch64.

Please note that this issue needs to be fixed as P0 since it is blocking us from creating a release.

**Comment by aleino-nv** [comment]
Why don't we just disable WebGPU for non-Windows platforms, for the time being? I thought that was the original plan?

**Comment by aleino-nv** [comment]
Also, I had the impression that @skallweitNV was working on this. (?)

**Comment by aleino-nv** [comment]
@skallweitNV Tells me the plan is to disable WebGPU backend on Linux, for now.

**Comment by westlicht** [comment]
Yes, that's the immediate fix in #5186. However, the correct fix will be to use a proper cmake toolchain file to cross-compile slang for linux/aarch64. This will correctly set the `CMAKE_SYSTEM_PROCESSOR` variable that `slang-rhi` depends on to select the correct dawn library. I have already setup the full build matrix for dawn binaries. So once the slang side is fixed, we can enable all builds again.

**Comment by aleino-nv** [comment]
Given

> We should consider just build libdawn.so for aarch64.

and 

>  I have already setup the full build matrix for dawn binaries

I'll assign this to @skallweitNV, then.

**Comment by csyonghe** [comment]
Slang's current cmake support already include Linux aarch64 builds.

**Comment by bmillsNV** [comment]
@skallweitNV what's left for this one? Do we still have a build failure?

**Comment by skallweitNV** [comment]
The release build works. For now WebGPU is disabled for Linux builds. In `slang-rhi` everything is done to support Linux for both x86_64 and aarch64 platforms. To get it all working the slang project needs to setup proper cmake cross-compilation for linux/aarch64 using a cmake toolchain file. Then we can re-enable WebGPU for Linux by removing this block: https://github.com/shader-slang/slang/blob/master/external/CMakeLists.txt#L74

**Comment by bmillsNV** [comment]
@aleino-nv could you add the the cmake item to your list?

**Comment by aleino-nv** [comment]
@bmillsNV This stuff is usually a bit of a time sink, at least for me -- is this really a priority?

That is to say, do we really need to support running Slang natively on mobile devices right now? At least this should have no impact on the demo we're working on.

**Comment by csyonghe** [comment]
@westlicht we use native asrch64 machine in the ci to create a slang release for Linux aarch64. Doesn't slang-rhi support native aarch64 build?

**Comment by csyonghe** [comment]
Closing as done.
