### ISSUE TITLE
Invalid HLSL generated when function is marked [Differentiable]

### ISSUE THREAD

**Issue by tunabrain** [shader-slang/slang#5218]
The following code:
```
struct ContainsBuffer
{
    StructuredBuffer<float> buffer;
    int dummy;
}
ParameterBlock<ContainsBuffer> call_data;
[Differentiable]
void takesBuffer(ContainsBuffer x)
{
}
[shader("compute")]
void main()
{
    ContainsBuffer cloned = { call_data.buffer, call_data.dummy };
    takesBuffer(cloned);
}
```
generates invalid HLSL (`no known conversion from 'ContainsBuffer_0' to 'ContainsBuffer_1'`). It looks like slang generates two different implementations of `ContainsBuffer`.

This seems to be connected with auto-diff: The bug goes away when removing `[Differentiable]` from `takesBuffer`, or changing the first line to `struct ContainsBuffer : IDifferential`.

**Comment by saipraveenb25** [comment]
@tunabrain: I'm not able to reproduce this issue with top-of-tree Slang. Can you check if the issue persists in the latest build here from 3 days ago? https://github.com/shader-slang/slang/releases/tag/v2024.13 

We fixed a related issue in that build.

This is the output I'm seeing with **v2024.13**
```csharp
#pragma pack_matrix(column_major)
#ifdef SLANG_HLSL_ENABLE_NVAPI
#include "nvHLSLExtns.h"
#endif

#ifndef __DXC_VERSION_MAJOR
    // warning X3557: loop doesn't seem to do anything, forcing loop to unroll
    #pragma warning(disable: 3557)
#endif

struct ContainsBuffer_0
{
    int dummy_0;
};

cbuffer call_data_0 : register(b0)
{
    ContainsBuffer_0 call_data_0;
}
RWStructuredBuffer<float > call_data_buffer_0 : register(u1);

void takesBuffer_0(ContainsBuffer_0 x_0, RWStructuredBuffer<float > x_buffer_0)
{
    x_buffer_0[int(0)] = 1.0;
    return;
}

[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID_0 : SV_DispatchThreadID)
{
    ContainsBuffer_0 _S1 = { call_data_0.dummy_0 };
    takesBuffer_0(_S1, call_data_buffer_0);
    return;
}
```

**Comment by tunabrain** [comment]
Can confirm that switching from v2024.11.1 to v2024.13 fixed the issue, thank you!
