### ISSUE TITLE
Make sure texture sampling builtins properly truncate results for Vulkan

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#522]
If the user writes HLSL like:

```hlsl
Texture2D<float> gTex;
...
float f = gTex.Sample(...);
```

then the equivalent GLSL output needs to look like:

```glsl
texture2d gTex;
...
float f = texture(sampler2d(gTex, ...), ...).x;
```

Note the addition of `.x` on the end of the operation there.

Our setup for defining GLSL translations of intrinsics is already supposed to handle this with the `$z` custom formatting op, but not all of the builtins have been decorated with it.

We need to survey the other texture operations and add `$z` where it is appropriate, and then also devise tests to cover this functionality (e.g, a texturing test that uses explicit element types of various vector widths, plus scalars).

**Comment by natduca** [comment]
Putting in q1 with glsl support at least to triage further.

**Comment by csyonghe** [comment]
This is already done.
