### ISSUE TITLE
WGSL: Missing capability for InterlockedAdd

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5220]
This issue was split from #5172.

In WGSL, this corresponds to [`atomicAdd`](https://www.w3.org/TR/WGSL/#atomic-add).
I think the problem is that the `atomic<T>` type is needed. (I don't think it's possible to implement equivalent of `__getMetalAtomicRef` for WGSL).

Affected tests under `tests/compute` (currently disabled):
- atomics-buffer
- atomics-groupshared
- atomics

Output from `slang-test`:

    ...
    tests/compute/atomics-buffer.slang(32): error 36107: entrypoint 'computeMain' does not support compilation target 'wgsl' with stage 'compute'
    void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
         ^~~~~~~~~~~
    tests/compute/atomics-buffer.slang(26): note: see using of 'InterlockedAdd'
        InterlockedAdd(outputBuffer[val],       val,        originalValue);
        ^~~~~~~~~~~~~~
    hlsl.meta.slang(9975): note: see definition of 'InterlockedAdd'
    hlsl.meta.slang(9974): note: see declaration of 'require'
    ...

Tasks:
- Find a way to implement InterlockedAdd for WGSL (probably similar to Metal)
- Try to enable the tests listed above

**Comment by aleino-nv** [comment]
@csyonghe Is the fix just to use `atomic<T>` in the above tests?

**Comment by csyonghe** [comment]
There is no way to support InterlockedXxx functions on wgsl. These tests should be permanently disabled on wgsl.

**Comment by aleino-nv** [comment]
> There is no way to support InterlockedXxx functions on wgsl. These tests should be permanently disabled on wgsl.

Wouldn't https://www.w3.org/TR/WGSL/#atomic-add work?

**Comment by csyonghe** [comment]
How do you convert an element in `ptr<array<int>, storage> `to `atomic<int>`?

**Comment by csyonghe** [comment]
Atomic<T> is already implemented for wgsl and we have no way to support the free form InterlockedAdd function, so we will close this issue.

**Comment by aleino-nv** [comment]
> How do you convert an element in `ptr<array<int>, storage> `to `atomic<int>`?

I thought we had some idea of creating aliased buffers for atomic access, or possibly just changing the type. Was there some flaw with that?
