### ISSUE TITLE
WGSL: There is no texture_1d_array type in WGSL

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5223]
This issue was split from https://github.com/shader-slang/slang/issues/5172.

Affected tests under `tests/compute` (currently disabled):
- texture-get-dimensions
- texture-sampling
- texture-simple

Output from slang-test for `texture-simple`:

    ...
    WGPU error: Error while parsing WGSL: :11:40 error: unresolved type 'texture_1d_array'
    @binding(4) @group(0) var t1DArray_0 : texture_1d_array<f32>;
    ...

Tasks:
- conditionally compile out the affected parts of the test case
- Try to enable the tests listed above

**Comment by csyonghe** [comment]
We should disable the texture 1D portion of the test for wgsl, and still enable other parts of the test.

**Comment by aleino-nv** [comment]
> We should disable the texture 1D portion of the test for wgsl with some #define logic in the test file, and still enable other parts of the test.

Ok but we should also not generate `texture_1d_array`, right?
I'd assume usage of 1d texture arrays should be caught by capability system and then reported nicely to the user at compile time.
(Right now we just generate broken WGSL that contains `texture_1d_array`.)

**Comment by csyonghe** [comment]
This shall be done in the same effort to disallow other types such as uint8 etc. We need to extend the capability system to be able to check on type usage. I consider this not directly within the scope of wgsl work.

**Comment by csyonghe** [comment]
The focus should be to get all tests that can work on wgpu to pass, and we can defer more restrict checking to the next phase of development.

**Comment by aleino-nv** [comment]
> This shall be done in the same effort to disallow other types such as uint8 etc. We need to extend the capability system to be able to check on type usage. I consider this not directly within the scope of wgsl work.

Ok I will extend https://github.com/shader-slang/slang/issues/4947 to include this, and make it non-WGSL specific
