### ISSUE TITLE
slang-test/WGPU: unfilterable-float type sampler used to filter

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5227]
This issue was split from https://github.com/shader-slang/slang/issues/5173.

Affected tests under tests/compute (currently excluded):

1. `func-param-legalize`

Output from slang-test, for `func-param-legalize`:

    ...
    WGPU error: Texture binding (group:0, binding:0) is TextureSampleType::UnfilterableFloat but used statically with a sampler (group:0, binding:1) that's SamplerBindingType::Filtering
     - While validating compute stage ([ShaderModule (unlabeled)], entryPoint: computeMain).
     - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor]).

    WGPU error: [Invalid ComputePipeline (unlabeled)] is invalid.
     - While encoding [ComputePassEncoder (unlabeled)].SetPipeline([Invalid ComputePipeline (unlabeled)]).
     - While finishing [CommandEncoder (unlabeled)].

    WGPU error: [Invalid CommandBuffer] is invalid.
     - While calling [Queue].Submit([[Invalid CommandBuffer]])
    ...

Generated WGSL for `slangc -o test.wgsl -target wgsl -stage compute -entry computeMain %SLANG_SRC%\tests\compute\func-param-legalize.slang`:

    @binding(0) @group(0) var diffuseMap_0 : texture_2d<f32>;
    
    @binding(1) @group(0) var samplerState_0 : sampler;
    
    @binding(2) @group(0) var<storage, read_write> outputBuffer_0 : array<f32>;
    
    struct Param_0
    {
         base_0 : f32,
    };
    
    fn run_0( p_0 : Param_0,  p_tex_0 : texture_2d<f32>,  p_samplerState_0 : sampler) -> vec4<f32>
    {
        return (textureSampleLevel((p_tex_0), (p_samplerState_0), (vec2<f32>(0.0f)), (0.0f))) + p_0.base_0;
    }
    
    @compute
    @workgroup_size(1, 1, 1)
    fn computeMain(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
    {
        var p_1 : Param_0;
        p_1.base_0 = -0.5f;
        var _S1 : vec4<f32> = run_0(p_1, diffuseMap_0, samplerState_0);
        outputBuffer_0[i32(0)] = _S1.x;
        outputBuffer_0[i32(1)] = _S1.y;
        outputBuffer_0[i32(2)] = _S1.z;
        outputBuffer_0[i32(3)] = _S1.w;
        return;
    }

**Comment by aleino-nv** [comment]
Yeah it seems we just return unfilterable-float unconditionally.

https://github.com/shader-slang/slang-rhi/blob/84f8ce13f92e9538b2e15f03d6bdac5ad9af215a/src/wgpu/wgpu-shader-object-layout.cpp#L54

**Comment by jkwak-work** [comment]
As far as I know, textures are not available on compute stage with WGSL. It works only for the fragment shader.

**Comment by skallweitNV** [comment]
I would be super surprised if textures are not available in compute stage ...

**Comment by aleino-nv** [comment]
> ...is TextureSampleType::UnfilterableFloat but used statically with a sampler (group:0, binding:1) that's SamplerBindingType::Filtering

Oh, I think possibly the fix here is to make the sampler not be of type `filtering` -- I don't know where it would get derivatives and such generally used for filtering, in a compute shader.

**Comment by jkwak-work** [comment]
I was surprised too but may be I am reading it wrong.
Please see it for your self, [here](https://www.w3.org/TR/WGSL/#texturesample)

> 16.7.8. textureSample
Samples a texture.
> 
> [Must](https://www.w3.org/TR/WGSL/#shader-creation-error) only be used in a [fragment](https://www.w3.org/TR/WGSL/#fragment) shader stage.

**Comment by aleino-nv** [comment]
> I was surprised too but may be I am reading it wrong. Please see it for your self, [here](https://www.w3.org/TR/WGSL/#texturesample)
> 
> > 16.7.8. textureSample
> > Samples a texture.
> > [Must](https://www.w3.org/TR/WGSL/#shader-creation-error) only be used in a [fragment](https://www.w3.org/TR/WGSL/#fragment) shader stage.

It could also be because you need derivative of screen-to-triangle transformation in order to pick MIP level.

https://www.w3.org/TR/WGSL/#texturesamplelevel seems to be fine. (Check compute.toys samples)

**Comment by jkwak-work** [comment]
Oh. Yes, that must be it.
It makes sense now
