### ISSUE TITLE
WGSL: Passing runtime-sized arrays (RWStructuredBuffer) by value

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5228]
This issue was split from https://github.com/shader-slang/slang/issues/5173.

Affected tests under tests/compute (currently excluded):

- `func-resource-param`

Output from slang-test, for `func-resource-param`:

    ...
    WGPU error: Error while parsing WGSL: :5:25 error: runtime-sized arrays can only be used in the <storage> address space
    fn helper_0( buffer_0 : array<i32>,  index_0 : i32) -> i32
                            ^^^^^^^^^^
    
    :5:14 note: while instantiating parameter buffer_0
    fn helper_0( buffer_0 : array<i32>,  index_0 : i32) -> i32
                 ^^^^^^^^
    
    
     - While validating [ShaderModuleDescriptor]
     - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
    ...

Generated WGSL for `func-resource-param`:

    @binding(1) @group(0) var<storage, read_write> inputBuffer_0 : array<i32>;
    
    @binding(0) @group(0) var<storage, read_write> outputBuffer_0 : array<i32>;
    
    fn helper_0( buffer_0 : array<i32>,  index_0 : i32) -> i32
    {
        return buffer_0[index_0];
    }
    
    fn test_0( val_0 : i32) -> i32
    {
        var _S1 : i32 = helper_0(inputBuffer_0, val_0);
        return _S1 + val_0;
    }
    
    @compute
    @workgroup_size(4, 1, 1)
    fn computeMain(@builtin(global_invocation_id) dispatchThreadID_0 : vec3<u32>)
    {
        var _S2 : u32 = dispatchThreadID_0.x;
        var outVal_0 : i32 = test_0(i32(_S2));
        outputBuffer_0[_S2] = outVal_0;
        return;
    }

**Comment by aleino-nv** [comment]
@csyonghe This is one reason I had that weird logic for `RWStructuredBuffer` (and similar) in the WGSL emitter. This used to work but I guess the pointer overhaul/cleanup broke it.

**Comment by csyonghe** [comment]
I think we should translate `StructuredBuffer` types consistently to `ptr<storage, array<T>>` in all places, including both global and function parameter declarations.

**Comment by aleino-nv** [comment]
> I think we should translate `StructuredBuffer` types consistently to `ptr<storage, array<T>>` in all places, including both global and function parameter declarations.

I don't follow for the global parameter case. WGSL doesn't declare global buffer parameters as `ptr` types -- it declares them just as `array` in storage address space.

When buffers are passed as function parameters, I agree that we should pass them as `ptr` types. When you load from them, I believe they can be either `ptr` or just `array` -- it has no effect on syntax.

**Comment by csyonghe** [comment]
For this, we can completely eliminate this issue if we utilize `slang-ir-specialize-resources.cpp` to legalize all parameter access to be direct global variable references. The `specializeResourceUsage` is already called from `linkAndOptimizeIR`, but it currently does not have the logic to determine what types should be legalized out when producing WGSL. Take a look at `slang-ir-specialize-resource.cpp` line 65,  you need to add the similar logic for wgsl targets to determine which types should be legalized out from function parameters.

**Comment by csyonghe** [comment]
See https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-byteaddressbuffer-load#parameters.

**Comment by aleino-nv** [comment]
> For this, we can completely eliminate this issue if we utilize `slang-ir-specialize-resources.cpp` to legalize all parameter access to be direct global variable references.

What about the similar issue, with struct fields instead of function parameters? E.g. if the user does something like this

    someStruct.buffer = someGlobalBuffer;
    someFunction(someStruct);


I think `someStruct.buffer` needs to be of type `ptr` in WGSL, similarly to function parameters.

**Comment by csyonghe** [comment]
The `legalizeRsourceType` pass that happens before `specializeResourceType` will hoist all such resource fields defined inside structs to top level function parameters.

For example, if you have:
```
struct SomeStruct { int x; StructuredBuffer<int> buffer; };
void test(SomeStruct s) {...}
```

After legalizeResourceType, this will become:
```
struct SomeStruct { int x; }
void test(SomeStruct s, StructuredBuffer<int> s_buffer) {...}
```

**Comment by aleino-nv** [comment]
> The `legalizeRsourceType` pass that happens before `specializeResourceType` will hoist all such resource fields defined inside structs to top level function parameters.
> 
> For example, if you have:
> 
> ```
> struct SomeStruct { int x; StructuredBuffer<int> buffer; };
> void test(SomeStruct s) {...}
> ```
> 
> After legalizeResourceType, this will become:
> 
> ```
> struct SomeStruct { int x; }
> void test(SomeStruct s, StructuredBuffer<int> s_buffer) {...}
> ```

Ok I see, but what about something like this?

    arrayOfBuffers[0] = globalBuffer0;
    arrayOfBuffers[1] = globalBuffer1;
    int idx = someComplicatedFunction(...);
    someFunction(localArrayOfBuffers[idx]);
    
Do we have some pass that flattens out arrayOfBuffers to some list of individual global variables? I guess arrays of buffers need to be of known fixed size then?

**Comment by aleino-nv** [comment]
(In any case, I'm convinced. I'll try out the recommendation in https://github.com/shader-slang/slang/issues/5228#issuecomment-2404140820, thanks!)

**Comment by csyonghe** [comment]
You can try it out with the glsl backend. This will also work, we will pass `idx` as a parameter to the function.

**Comment by csyonghe** [comment]
although wgsl doesn't allow arrays of buffers, so we can't support this anyways.

**Comment by aleino-nv** [comment]
Closed by https://github.com/shader-slang/slang/pull/5483
