### ISSUE TITLE
WGSL: 'operator < (u32, i32)' generated

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5262]
Slang/WGSL generates code comparing signed and unsigned integers.

Affected tests:

- tests\autodiff\bug-1.slang

**Comment by aleino-nv** [comment]
Generated WGSL for tests\autodiff\bug-1.slang:

    ...
    fn unusual_norm_bwd_0( x_0 : ptr<function, DiffPair_arrayx3Cfloatx2C5x3E_0>,  dResult_0 : f32)
    {
        var derivatives_0 : array<f32, i32(5)>;
        var i_0 : u32 = u32(0);
        for(;;)
        {
            if(i_0 < i32(5))
            {
            }
            else
            {
                break;
            }
            derivatives_0[i_0] = 4.0f * dResult_0 * pow((*x_0).primal_0[i_0], 3.0f);
            i_0 = i_0 + u32(1);
        }
        (*x_0).primal_0 = (*x_0).primal_0;
        (*x_0).differential_0 = derivatives_0;
        return;
    }
    ...


WGPU error:


    WGPU error: Error while parsing WGSL: :15:12 error: no matching overload for 'operator < (u32, i32)'
    
    2 candidate operators:
     • 'operator < (T  ✓ , T  ✗ ) -> bool' where:
          ✓  'T' is 'abstract-float', 'abstract-int', 'f32', 'i32', 'u32' or 'f16'
     • 'operator < (vecN<T>  ✗ , vecN<T>  ✗ ) -> vecN<bool>' where:
          ✗  'T' is 'abstract-float', 'abstract-int', 'f32', 'i32', 'u32' or 'f16'
    
            if(i_0 < i32(5))
               ^^^^^^^^^^^^

**Comment by csyonghe** [comment]
I think the fault is I. The autodiff pass that synthesizes the backward loop.

**Comment by aleino-nv** [comment]
I don't think this has anything to do with autodiff.
For example, the following Slang shader

    RWStructuredBuffer<float> g_out;
    
    void fun<let N : uint>(inout Array<float, N> x)
    {
      for(uint i = 0; i < N; i++)
      {
        x[i] = 4.f * pow(x[i], 3);
      }
    }
    
    [shader("compute")]
    [numthreads(1, 1, 1)]
    void computeMain(uint3 dtid : SV_DispatchThreadID)
    {
      Array<float, 5> x = {0, 1, 2, 3, 4};
      fun(x);
      g_out[0] = x[0] + x[1] + x[2] + x[3] + x[4];
    }

...produces code with the same issue (`i_0 < i32(5)` where `i_0` is `u32`):

    @binding(0) @group(0) var<storage, read_write> g_out_0 : array<f32>;
    
    fn fun_0( x_0 : ptr<function, array<f32, i32(5)>>)
    {
        var i_0 : u32 = u32(0);
        for(;;)
        {
            if(i_0 < i32(5))
            {
            }
            else
            {
                break;
            }
            (*x_0)[i_0] = 4.0f * pow((*x_0)[i_0], 3.0f);
            i_0 = i_0 + u32(1);
        }
        return;
    }
    
    @compute
    @workgroup_size(1, 1, 1)
    fn computeMain(@builtin(global_invocation_id) dtid_0 : vec3<u32>)
    {
        var x_1 : array<f32, i32(5)>;
        x_1[i32(0)] = 0.0f;
        x_1[i32(1)] = 1.0f;
        x_1[i32(2)] = 2.0f;
        x_1[i32(3)] = 3.0f;
        x_1[i32(4)] = 4.0f;
        fun_0(&(x_1));
        g_out_0[i32(0)] = x_1[i32(0)] + x_1[i32(1)] + x_1[i32(2)] + x_1[i32(3)] + x_1[i32(4)];
        return;
    }
    
If I change the `fun(x)` call to explicitly specify the template parameter `fun<5>(x)`,
then the integer literal for the loop expression changes to `u32(5)` and the issue goes
away.

It seems that when the template parameter has to be inferred from the array type, then `N` may change interpretation to "signed".

**Comment by aleino-nv** [comment]
Another experiment:


    RWStructuredBuffer<float> g_out;
    
    int g(int x)
    {
        return x + 2;
    }
    
    int g(uint x)
    {
        return x - 3;
    }
    
    void fun<let N : uint>(inout Array<int, N> x)
    {
        x[0] = g(N) + g(0);
    }
    
    [shader("compute")]
    [numthreads(1, 1, 1)]
    void computeMain(uint3 dtid : SV_DispatchThreadID)
    {
      Array<int, 3> x = {0, 1, 2};
      fun(x);
      g_out[0] = x[0];
    }


compiles to

    @binding(0) @group(0) var<storage, read_write> g_out_0 : array<f32>;
    
    fn g_0( x_0 : u32) -> i32
    {
        return i32(x_0 - u32(3));
    }
    
    fn g_1( x_1 : i32) -> i32
    {
        return x_1 + i32(2);
    }
    
    fn fun_0( x_2 : ptr<function, array<i32, i32(3)>>)
    {
        (*x_2)[i32(0)] = g_0(i32(3)) + g_1(i32(0));
        return;
    }
    
    @compute
    @workgroup_size(1, 1, 1)
    fn computeMain(@builtin(global_invocation_id) dtid_0 : vec3<u32>)
    {
        var x_3 : array<i32, i32(3)>;
        x_3[i32(0)] = i32(0);
        x_3[i32(1)] = i32(1);
        x_3[i32(2)] = i32(2);
        fun_0(&(x_3));
        g_out_0[i32(0)] = f32(x_3[i32(0)]);
        return;
    }


Notice that the correct overload (the one taking a `u32`) was chosen for the `g(N)` call, and yet `N` is pasted to produce `g_0(i32(3))` where `g_0` takes a `u32`!


It seems to me that constant propagation is not retaining signedness, which leads to several problems:

-  mixed-signedness comparison in the original example for this issue...
- ...and now mismatching parameter type in the above example.

**Comment by csyonghe** [comment]
That's good knowledge, let me give this a look.
