### ISSUE TITLE
slang-test/WGPU: IR opcode during code emit

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5263]
This output is generated by
`slang-test -bindir %BINDIR% -category full -api wgpu tests/autodiff/custom-intrinsic.slang`

    ...
    error: ERROR:
    EXPECTED{{{
    result code = 0
    standard error = {
    }
    standard output = {
    }
    }}}
    ACTUAL{{{
    result code = 1
    standard error = {
    }
    standard output = {
    abort compilation: tests/autodiff/custom-intrinsic.slang(21): internal error 99999: unimplemented feature in Slang compiler: unexpected IR opcode during code emit
        T myexp(T x);
          ^~~~~
    }
    }}}

    error: ERROR:
    EXPECTED{{{
    type: float
    7.389056
    7.389056
    0.0
    0.0
    0.0}}}
    ACTUAL{{{
    }}}

    ...

Tests:

- tests/autodiff/custom-intrinsic.slang

**Comment by bmillsNV** [comment]
Test needs to be disabled.

**Comment by aleino-nv** [comment]
Fixing might be easy.
