### ISSUE TITLE
Slang release builds on windows has no debug info.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#5267]

**Comment by expipiplus1** [comment]
You can build with the config `RelWithDebInfo` to get this (`cmake --build build --config RelWithDebInfo`, I think in VS there's like a dropdown selection for this?). Would you like for this to be made default for the `release` preset?

**Comment by jkwak-work** [comment]
I see what Ellie says,
![image](https://github.com/user-attachments/assets/786f232d-07cc-46a3-84d1-347a3cbfd28d)
What would be a good way to verify that "RelWithDebugInfo" actually contains the debug info?
