### ISSUE TITLE
Support DXIL libraries

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#528]
When generating DXIL output, we should emit and compile HLSL for all entry points in a translation unit at once. This has the potential to speed up compilation in the multiple-entry-points case, and might also enable use of DXIL-level linking.

The a few main challenges I am aware of are:

* Our IR “linking” step currently selects target-specific callee functions at call sites. If we include the shader stage as part of the definition of a “target” then we need to deal with cases where a call site might resolve to a different concrete caller for vertex vs. fragment stages (for example), such that we would *also* need to make different specialized versions of the caller. This is not something the IR can easily model today.

* If we want to support “exported” symbols other than entry points (so that they can be used for linking at the DXIL level), then we need a way to mark them (e.g., a `public` keyword), and a way to identify those functions in the generated DXIL (e.g., by allowing users to query mangled names). We also need to make sure that generated DXIL in this mode does *not* include definitions for functions that will be provided by some other library at DXIL link time.

* Finally, we need an answer for how Slang generics interact with DXIL libraries. The easiest answer may be that a generated DXIL library only contains fully-specialized symbols from the Slang IR, and if you want to do linking+specialization you do it at the Slang IR level. That raises questions of how to do intelligent linking of Slang+DXIL so that we re-use DXIL definitions of symbols that have already been generated if possible.

The first goal would just be to streamline the compilation when multiple entry points belong to the same translation unit. The other questions can be deferred until they arise in practice.

**Comment by csyonghe** [comment]
This is supported now.
