### ISSUE TITLE
WGSL: Runtime-sized array used as return value

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5288]
Affected tests:

- tests/optimization/func-resource-result/func-resource-result-simple.slang

WGPU error:

    WGPU error: Error while parsing WGSL: :5:26 error: function return type must be a constructible type
    fn getInputBuffer_0() -> array<i32>

**Comment by csyonghe** [comment]
You need to turn on resource specialization pass for this.

**Comment by aleino-nv** [comment]
Closed by https://github.com/shader-slang/slang/pull/5483
