### ISSUE TITLE
Incorrect warning 41017 on groupshared variables

### ISSUE THREAD

**Issue by danginsburg** [shader-slang/slang#5292]
I wasn't able to create a simple reproducer case, but I shared privately with @csyonghe an example that is generating a warning on uninitialized groupshared memory and giving this warning in slang v2024.13:

```
cmaa2.fxc(609): warning 41017: use of uninitialized global variable 'g_groupShared2x2FracEdgesH'
    float4 valH = g_groupShared2x2FracEdgesH [ addr ] ; e00 . y = valH . x ; e10 . y = valH . y ; e01 . y = valH . z ; e11 . y = valH . w ;
           ^~~~
cmaa2.fxc(610): warning 41017: use of uninitialized global variable 'g_groupShared2x2FracEdgesV'
    float4 valV = g_groupShared2x2FracEdgesV [ addr ] ; e00 . x = valV . x ; e10 . x = valV . y ; e01 . x = valV . z ; e11 . x = valV . w ;
```

Filing this bug so we have an issue tracking it.

**Comment by csyonghe** [comment]
@danginsburg I believe you should be able to just disable this warning for your use case. 41017 only applies to global variables, and there is a spearate warning for uninitialized local variables or out parameters. This means that disabling 41017 will still allow you get receive warnings on more common uninitialized var errors.

**Comment by csyonghe** [comment]
I am going to close this issue since separating warnings for global and local variable is the what we've agreed to be the most useful solution right now.
