### ISSUE TITLE
WSGL: Create a shim layer to call slang Compilation API from RUST

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#5293]
Since we probably have to use compute toys https://compute.toys as the tempale for our slang palyground, we need to add support of compiling slang code into WGSL. However, the compile engine of compute toys is written in Rust, we need to add some code to be able to call slang library by Rust.

**Comment by aleino-nv** [comment]
You can also call JS code from Rust, right? That may be another way. I don't know which way is cleaner/faster for this project.

**Comment by kaizhangNV** [comment]
Close this issue as we will not go this way.
