### ISSUE TITLE
Explicitly requesting extensions when compiling using the API

### ISSUE THREAD

**Issue by Dynamitos** [shader-slang/slang#5294]
I am having difficulties manually enabling specific extensions when compiling via the API. So far I have been using the `IgnoreCapabilities` option to turn off capability checking to automatically enable required extensions, but now I get the following error:

    glslang:  shaders/terrain/update_utils.slang(100): error :  '64-bit octal literal' : not supported for this version or the enabled extensions
    glslang:  shaders/terrain/update_utils.slang(100): error :  '64-bit unsigned integer literal' : required extension not requested: Possible extensions include:
    glslang: note : GL_ARB_gpu_shader_int64
    glslang: note : GL_EXT_shader_explicit_arithmetic_types
    glslang: note : GL_EXT_shader_explicit_arithmetic_types_int64

This is the code i use for creating the session when compiling for a Vulkan target:

    if (!globalSession) {
        slang::createGlobalSession(globalSession.writeRef());
    }
    slang::SessionDesc sessionDesc;
    sessionDesc.flags = 0;
    std::vector<slang::CompilerOptionEntry> option = {
        {
            .name = slang::CompilerOptionName::Capability,
            .value =
                {
                    .kind = slang::CompilerOptionValueKind::Int,
                    .intValue0 = globalSession->findCapability("GL_EXT_shader_explicit_arithmetic_types_int64"),
                },
        },
        {
            .name = slang::CompilerOptionName::EmitSpirvViaGLSL,
            .value =
                {
                    .kind = slang::CompilerOptionValueKind::Int,
                    .intValue0 = 1,
                },
        },
        {
            .name = slang::CompilerOptionName::DebugInformation,
            .value =
                {
                    .kind = slang::CompilerOptionValueKind::Int,
                    .intValue0 = SLANG_DEBUG_INFO_LEVEL_NONE,
                },
        },
        {
            .name = slang::CompilerOptionName::DebugInformationFormat,
            .value =
                {
                    .kind = slang::CompilerOptionValueKind::Int,
                    .intValue0 = SLANG_DEBUG_INFO_FORMAT_PDB,
                },
        },
        {
            .name = slang::CompilerOptionName::DumpIntermediates,
            .value =
                {
                    .kind = slang::CompilerOptionValueKind::Int,
                    .intValue0 = info.dumpIntermediate,
                },
        },
    };

    sessionDesc.compilerOptionEntries = option.data();
    sessionDesc.compilerOptionEntryCount = option.size();
    sessionDesc.defaultMatrixLayoutMode = SLANG_MATRIX_LAYOUT_COLUMN_MAJOR;
    Array<slang::PreprocessorMacroDesc> macros;
    for (const auto& [key, val] : info.defines) {
        macros.add(slang::PreprocessorMacroDesc{
            .name = key,
            .value = val,
        });
    }
    sessionDesc.preprocessorMacroCount = macros.size();
    sessionDesc.preprocessorMacros = macros.data();
    slang::TargetDesc targetDesc;
    targetDesc.profile = globalSession->findProfile("spirv_1_6");
    targetDesc.format = target;
    sessionDesc.targetCount = 1;
    sessionDesc.targets = &targetDesc;
    StaticArray<const char*, 5> searchPaths = {"shaders/", "shaders/lib/", "shaders/raytracing/", "shaders/terrain", "shaders/generated/"};
    sessionDesc.searchPaths = searchPaths.data();
    sessionDesc.searchPathCount = searchPaths.size();

    Slang::ComPtr<slang::IBlob> diagnostics;

    CHECK_RESULT(globalSession->createSession(sessionDesc, session.writeRef()));

It probably is documented somewhere how to manually enable extensions for the API, but I couldn't find it, sorry

**Comment by csyonghe** [comment]
These extensions should be automatically declared when 64bit integers are present in the generated code.
Slang currently does not provide a way to manually enable glsl extensions, it should be taken care of automatically by the compiler.

Can you share your shader code so we can reproduce this issue?

**Comment by Dynamitos** [comment]
I am in the process of porting a massive codebase, but here is a snippet i managed to simplify:


    struct ComputeParams
    {
        RWStructuredBuffer<uint> indirectDrawBuffer;
        RWStructuredBuffer<uint64_t> heapIDBuffer;
        RWStructuredBuffer<uint> classificationBuffer;
        RWStructuredBuffer<int> allocateBuffer;
        RWStructuredBuffer<int> memoryBuffer;
        RWStructuredBuffer<int> propagateBuffer;
        RWStructuredBuffer<uint> simplifyBuffer;
    };
    ParameterBlock<ComputeParams> pParams;

    // Split buffer slots
    static const uint64_t SPLIT_COUNTER = 0;
    static const uint64_t SIMPLIFY_COUNTER = 1;
    static const uint64_t CLASSIFY_COUNTER_OFFSET = 2;
    void ResetBuffers()
    {
        pParams.memoryBuffer[0] = 0;
        pParams.memoryBuffer[1] = 0;

        pParams.classificationBuffer[SPLIT_COUNTER] = 0;
        pParams.classificationBuffer[SIMPLIFY_COUNTER] = 0;

        pParams.allocateBuffer[0] = 0;

        pParams.propagateBuffer[0] = 0;
        pParams.propagateBuffer[1] = 0;

        pParams.simplifyBuffer[0] = 0;

        pParams.indirectDrawBuffer[0] = 0;
        pParams.indirectDrawBuffer[1] = 1;
        pParams.indirectDrawBuffer[2] = 0;
        pParams.indirectDrawBuffer[3] = 0;

        pParams.indirectDrawBuffer[4] = 0;
        pParams.indirectDrawBuffer[5] = 1;
        pParams.indirectDrawBuffer[6] = 0;
        pParams.indirectDrawBuffer[7] = 0;

        pParams.indirectDrawBuffer[8] = 0;
    }

    [numthreads(1, 1, 1)]
    void Reset()
    {
        ResetBuffers();
    }

it could most likely be cut down some more
I am currently on commit 456df23cff531566dfe3a6ca7be998f1251b1774, if that helps. I have not tried many other versions

**Comment by csyonghe** [comment]
OK, thank you for providing the details. Are there any reason you need to stay with the glsl backend? I suspect the spirv backend should just work.

**Comment by Dynamitos** [comment]
Because when using `EmitSpirvDirectly` I get the following vulkan validation error:

    VUID-VkShaderModuleCreateInfo-pCode-08737(ERROR / SPEC): msgNum: -1520283006 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282 | vkCreateShaderModule(): pCreateInfo->pCode (spirv-val produced an error):
    Function end cannot be called in blocks
      OpFunctionEnd
    . The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08737)
        Objects: 0

**Comment by Dynamitos** [comment]
I am currently in the process of trying to fix this myself, however with no success. I have tried this:


    /// @category atomic
    [ForceInline]
    void InterlockedOr(__ref  $(T) dest,  $(T) value)
    {
        __target_switch
        {
        case hlsl: __intrinsic_asm "InterlockedOr";
        case glsl:
            __requireGLSLExtension("GL_EXT_shader_atomic_int64");
            __glslInterlocked_or(dest, value);
        case spirv:
            spirv_asm
            {
                OpCapability Int64Atomics;
                result:$$$(T) = OpAtomicOr &dest Device None $value;
            };
        }
    }

    [ForceInline]
    void InterlockedOr(__ref $(T) dest, $(T) value, out $(T) original_value)
    {
        __target_switch
        {
        case hlsl: __intrinsic_asm "InterlockedOr";
        case glsl:
            __requireGLSLExtension("GL_EXT_shader_atomic_int64");
            __glslInterlocked_or(dest, value, original_value);
        case spirv:
            spirv_asm
            {
                OpCapability Int64Atomics;
                %origin:$$$(T) = OpAtomicOr &dest Device None $value;
                OpStore &original_value %origin
            };
        }
    }

which throws the following error:

    hlsl.meta.slang(10382): error 36108: 'InterlockedOr' has dependencies that are not compatible on the required target 'glsl'.
    void InterlockedOr(__ref  int64_t dest,  int64_t value)
         ^~~~~~~~~~~~~
    hlsl.meta.slang(10382): note: see definition of 'InterlockedOr'
    void InterlockedOr(__ref  int64_t dest,  int64_t value)

**Comment by csyonghe** [comment]
Can you use `Atomic<T>` instead? https://shader-slang.com/stdlib-reference/types/atomic-0/or

**Comment by csyonghe** [comment]
As the error suggested, `InterlockedOr` isn't available for glsl or spirv backends.

**Comment by Dynamitos** [comment]
The StructuredBuffer in question is represents a bitfield where i set and erase bits both atomically and through regular access.

Is InterlockedOr not available in general for glsl and spirv, or is this only for 64 bit integers?

Would the atomic equivalent be a StructuredBuffer<Atomic<uint64_t>>? is the memory layout the same as a regular uint64_t or does it need more memory?

**Comment by csyonghe** [comment]
I am fixing this in #5324. `InterlockedOr` wasn't defined for glsl and I added it in the PR.

**Comment by Dynamitos** [comment]
thank you very much! I need this for the project I am currently working on so this helps me a lot
