### ISSUE TITLE
Stdlib: Fill descriptions for stdlib Builtin interfaces

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5304]
Currently the doc generation tool [reports](https://github.com/shader-slang/stdlib-reference/blob/main/summary.txt) that 682 descriptions are missing, which is about 86%.

We need to fill in the descriptions preferably in a priority order.

1. We need clear descriptions for `interface`, because interfaces don't have implementations and they are nothing without documentation.

**Comment by jkwak-work** [comment]
I am leaving related links for this task.

HTML result page: https://shader-slang.com/stdlib-reference/interfaces/index.html
Undocumented items: https://github.com/shader-slang/stdlib-reference/blob/main/summary.txt

**Comment by jkwak-work** [comment]
@bmillsNV , am I allowed to use Coverall for stdlib documentation?
I gave a try and it worked very well, but I like to double check if I am allowed.

**Comment by bmillsNV** [comment]
@jkwak-work yes you can use coveralls here.
