### ISSUE TITLE
document Global Functions - Atomic Derivative, bit operation functions

### ISSUE THREAD

**Issue by bmillsNV** [shader-slang/slang#5307]

**Comment by cheneym2** [comment]
@csyonghe Please confirm how to determine which functions are in scope for this task.

**Comment by cheneym2** [comment]
IIUC, the list of undocumented functions can be found here
https://github.com/shader-slang/stdlib-reference/blob/main/summary.txt but it's still not obvious to me

**Comment by cheneym2** [comment]
I'll document the items already marked with the relevant categories and so are already present in the global declaration sections:
Atomic function, Bit operation, Derivative functions.

**Comment by csyonghe** [comment]
The task here is to use your judgement to document the most important, currently undocumented functions. I don't care which functions you pick, the goal is to reduce the amount of undocumented functions as much as possible. As long as the functions you worked on are belonging to the categories, it is all good!
