### ISSUE TITLE
Swap out all uses of stdlib for core or "standard library" to core module and standard modules throughout docs & code

### ISSUE THREAD

**Issue by bmillsNV** [shader-slang/slang#5335]
Terminology
Slang Standard Modules → the modules you get when you download slang
Slang Core Module — the module that starts every slang file — thing that can’t opt out of that has all our core types/functions/etc that every module starts with

We don’t want to use stdlib or “library” anywhere. Slang does modules. So we should use modules.

**Comment by jkwak-work** [comment]
I have three questions regarding the terminology change.

1. Does it include the name of repo like [shader-slang/stdlib-reference](https://github.com/shader-slang/stdlib-reference)?
If yes, I will rename the repo.

2. Does it include the name of projects?
   There are a few project who name includes `stdlib`.
   Should they be changed too?
   - slang-embedded-stdlib
   - slang-embedded-stdlib-source
   - slang-no-embedded-stdlib
   - slang-no-embedded-stdlib-source
   - generate_stdlib_headers

3. Does it include the name of files?
   There are two files whose name include `stdlib`.
   - slang-stdlib.cpp
   - slang-stdlib-textures.cpp

**Comment by jkwak-work** [comment]
The answer during the meeting yesterday was,
1. No, we don't want to rename the repo yet. And when we rename it later, it will be "standard-reference".
2. Yes, we should rename the project names.
3. Yes, we should rename the file names.
4. Yes, we should rename the enum and constant variable names.

**Comment by jkwak-work** [comment]
I like to share some update, although it may make sense only to myself.

I locally renamed all filenames, enum names and project names.
It compiles and slang-test runs all green.

I still need to do the followings,
- rename `slang-stdlib.bin` to `slang-core-module.bin`.
- rename the command-line arguments that use the keyword `stdlib` such as `-load-stdlib` and `-save-stdlib`
- rename function names that uses the keyword, `stdlib`.
- modify comments to use either "core module" or "standard module" depending on the context.
- modify documents to use either "core module" or "standard module" depending on the context.
- rename `stdlib` in some of python, bash and pwsh scripts.

**Comment by jkwak-work** [comment]
I figured that `compileStdLib()` is just for a core-module, and it should be `compileCoreModule()`.
But `loadStdLib()` and `saveStdLib()` are for multiple modules so it will have to be renamed to be `loadStandardModules()` and `saveStandardModules()`.

`slang_createGlobalSessionWithoutStdLib()` and `slang_getEmbeddedStdLib()` should be renamed to use `CoreModule`, because their implementation handle only the core module.

**Comment by jkwak-work** [comment]
It seems like there will be a lot more changes than I expected.
I am going to prepare multiple PRs for easier reviews.
