### ISSUE TITLE
Add link to shader-slang.com in repo's About

### ISSUE THREAD

**Issue by eliemichel** [shader-slang/slang#5347]
That's a very easy issue! Just setting the URL of the About section to https://shader-slang.com/ would help users navigate to the doc quickly! The GitHub repo is better indexed on search engines than the documentation, so I often end up passing by the repo, then looking for the right link in the README.

![image](https://github.com/user-attachments/assets/19092513-098e-46a9-a310-2b7fa2e96890)

**Comment by csyonghe** [comment]
Done. Thanks for the suggestion!
