### ISSUE TITLE
vector misses implementation for vectors larger 4 for host target

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#5362]
Vector is only implemented for sizes 1, 2, 3, 4. Everything larger results in an error when building host code.

```cpp
// in slang
vector<float, 13> some_vector;
```

```cpp
// generated code
template <typename T, int COUNT>
struct Vector;

template <typename T>
struct Vector<T, 1>
{
....
```

**Comment by csyonghe** [comment]
Please note that support for larger vector sizes is not part of the language. This restriction may be lifted in the future but for now vectors are limited to have size <= 4.

**Comment by fknfilewalker** [comment]
I see. Can you also explain what the difference between `vector` and `Array` is? Array maps to `StaticArray` on the c side? There is also `DynamicArray`, how is this accessed on the slang side?

**Comment by csyonghe** [comment]
In Slang, `int arr[5];` is equivalent to `Array<int, 5> arr;`
`Array` is just the type for arrays, it maps to a stack-allocated static array when generating C++.

There is currently not a builtin type that maps to a dynamic heap-allocated array such as C++'s `std::vector`.

**Comment by bmillsNV** [comment]
@fknfilewalker Slang doesn't current support vectors greater than 4. Is it possible for you to work around this by using arrays instead? Please let us know if you have concerns with closing this issue.

**Comment by jkwak-work** [comment]
> mhm thought so, what speaks against using one array type and then replace everything with N <= 4 and the correct type with the special IR primitive types in the backend

I am not sure what problem your suggestion will solve.
I see some interesting ideas tossed around but it is unclear what the problem is.

**Comment by fknfilewalker** [comment]
I am fine with using arrays, so this is not a road block. Was just wondering about the reasons behind it.
