### ISSUE TITLE
vs2017:syntax highlighter and code suggestion tools required for slang

### ISSUE THREAD

**Issue by bipul-mohanto** [shader-slang/slang#5371]
Hi! I am using VS2017, an earlier version of `slang 0.11.21`. Unfortunately, the `slang` codes look like simple text files, without any syntax highlights or code suggestions. 

I was googling for any tools that can work as code suggestions and syntax highlight but did not find a suitable option. I will appreciate your suggestion.

**Comment by csyonghe** [comment]
We have a visual studio extension for vs2022. Unfortunately we don't have an extension for vs2017 due to lack of language server protocol and necessary framework support there.

Is upgrading to vs2022 not an option?

**Comment by bipul-mohanto** [comment]
For VS2022 (17.11.5), 
- installing the [extension](https://marketplace.visualstudio.com/items?itemName=Asuka.slangvsx), I can see the syntax highlighting but cannot see the code suggestion. 
- I downloaded the `slang-2024.14.2-windows-x86_64.zip` from [slang release](https://github.com/shader-slang/slang/releases) page, added `slangd.exe` under `System variables -> Path`. But this leads to the error message: 
<img width="1069" alt="git" src="https://github.com/user-attachments/assets/623aa140-49e6-4fca-91fa-c262bff7a439">
- if `slangd.exe` is correctly setup, I would see the code completing suggestion, right?

For VS2017, I guess there would be no other solution.
