### ISSUE TITLE
[Doc] Fix the broken markdown syntax in the user guide

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5439]
The second section of the user guide shows the code snippet in a strange way, which appears to be not intended.
https://shader-slang.com/slang/user-guide/conventional-features.html

![image](https://github.com/user-attachments/assets/237d4694-72a4-4ee5-9da7-efc794576a2f)

Also some of item-list doesn't look right.
![image](https://github.com/user-attachments/assets/937e5504-7103-4754-af6b-78bcc6beee9d)

![image](https://github.com/user-attachments/assets/45a0bce5-0081-4495-a6e2-bf9fb90c373c)

**Comment by csyonghe** [comment]
This section should be deleted and replaced with text that is consistent with SP004 after its implementation lands.
