### ISSUE TITLE
atomic sample in playground

### ISSUE THREAD

**Issue by bmillsNV** [shader-slang/slang#5449]
Create a simple demo to demonstrate the usage of the atomic functions in Slang.

We don't have to cover all atomic functions, 2 or 3 of them should be good enough.

Use "Simple Print" as a empty template to start with.
Call some atomic functions and print some results.

**Comment by aleino-nv** [comment]
I spent a bunch of time fixing build script issues, but now I can finally start on the atomic sample.

**Comment by aleino-nv** [comment]
PR: https://github.com/shader-slang/slang-playground/pull/69
