### ISSUE TITLE
SPIR-V/Vulkan specialization constants are not generated in SPIRV when -allow-glsl is set

### ISSUE THREAD

**Issue by andreasschultes** [shader-slang/slang#5463]
SPIR-V/Vulkan specialization constants are not generated in SPIRV when -allow-glsl is set.
```
${SLANGC} ${SHADER_FILE} -target spirv -I${SOURCE_ROOT} ${SHADER_INCLUDE_DIRS} -DdebugPrintfEXT -depfile ${SPIRV}.d -o ${SPIRV}
```
 generates the SpecId  "OpDecorate %a SpecId 5"
```
${SLANGC} ${SHADER_FILE} -target spirv -allow-glsl -I${SOURCE_ROOT} ${SHADER_INCLUDE_DIRS} -DdebugPrintfEXT -depfile ${SPIRV}.d -o ${SPIRV}
```
 uses the default values and the constants are optimised out

**Comment by csyonghe** [comment]
Can you share with us the shader code that canbe used to reproduce this issue?

**Comment by andreasschultes** [comment]
The test case for specialization constants reproduce this with the parameter -target spirv -allow-glsl -o test.spv
https://github.com/shader-slang/slang/blob/master/tests/spirv/specialization-constant.slang
