### ISSUE TITLE
Bug on supporting bit_cast<uint64_t>(double)

### ISSUE THREAD

**Issue by kaizhangNV** [shader-slang/slang#5470]
Following code will cause internal error:
```
RWStructuredBuffer<uint64_t> out;

uint64_t cast(double x)
{
    return bit_cast<uint64_t>(x);
}

[shader("compute")]
[numthreads(1,1,1)]
void computeMain()
{
    double x = 1.0;

    out[0] = cast(x);
}
```

note, there is no problem just doing 
```
  out[0] = bit_cast<uint64_t>(1.0lf);
```

**Comment by kaizhangNV** [comment]
The error message is:
```
test1.slang(6): internal error 99999: unimplemented feature in Slang compiler: unexpected IR opcode during code emit
    return bit_cast<uint64_t>(x);
```

**Comment by kaizhangNV** [comment]
I tried other targets
It has no problem on cpp, cuda, spirv.

**Comment by kaizhangNV** [comment]
on all the shader language targets, we don't handle `double` base type during processing kIROp_BitCast.

**Comment by kaizhangNV** [comment]
There is a TODO in hlsl target
                // TODO: There is an `asdouble` function
                // for converting two 32-bit integer values into
                // one `double`. We could use that for
                // bit casts of 64-bit values with a bit of
                // extra work, but doing so might be best
                // handled in an IR pass that legalizes
                // bit-casts.
                //

**Comment by csyonghe** [comment]
We should work on top of https://github.com/shader-slang/slang/pull/5020 for this issue.
