### ISSUE TITLE
Global shader input parameters shouldn't lower as pointers

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#549]
Right now we are lowering global-scope shader parameters into IR global variables. This has some annoying down-sides:

* Access to these variables is always through `load`/`store`, and in a function that accesses the same shader parameter multiple times we conservatively emit multiple `load`s even though we should know that the parameter's value won't change.

* The only thing that distinguishes a global shader parameter from an ordinary global variable is the presence of a suitable `VarLayout` on the IR variables that represent parameters. This creates opportunities for confusion, and we have previously had bugs around this, with a global `Texture2D` getting interpreted as an ordinary global variable instead of a parameter.

A simple option would be to introduce a distinguished IR instruction to represent shader parameters. Perhaps something like `global_param`. Similar to a function `param`, a `global_param` would directly represent the parameter value instead of a pointer to it (as is the case for `global_var` or `var`).

**Comment by csyonghe** [comment]
This is already implemented.
