### ISSUE TITLE
Option to generate binding and layout information for slangc

### ISSUE THREAD

**Issue by tareksander** [shader-slang/slang#5492]
As far as I understand the documentation, layout and  binding information (unless manually specified) is chosen by the language, and the only way know what was chosen is to use the reflection API. With something like a separate json output file that includes the descriptor set and binding for globals and the type layout, slangc could be used standalone for compilation.

**Comment by csyonghe** [comment]
This is a good suggestion and is what we've been considering to add.
Currently there is already the slang-reflection-test code (that is compiled as a library) that does exactly this, and you can change the code slightly to compile that dll as an exe instead. But it would be useful to package them up directly in slangc.

**Comment by tareksander** [comment]
If no one is working on it I can try implementing it. Shouldn't be that hard with the reflection API already in place.

**Comment by csyonghe** [comment]
That will be fantastic. We appreciate your contribution! You can get started by taking a look at `\tools\slang-reflection-test\slang-reflection-test-main.cpp`, which should already have all the logic we want: reads the refection data, and print them out as json string.

**Comment by tareksander** [comment]
So basically:

- move most of the reflection test code to the main codebase
- hook up the code in slangc with a compiler option
- add the option to the documentation

Right?

**Comment by csyonghe** [comment]
Yes, that should be it.

**Comment by csyonghe** [comment]
You can run `slang-test` from repository root directory without any parameters:
```
slang-test
```

To speed things up you can run tests in parallel with:
```
slang-test -use-test-server -server-count 12
```

To run tests with specific name:
```
slang-test tests/compute/simple.slang
```

To run test using a specific API:
```
slang-test -api d3d12
```
```
slang-test -api all-wgpu # run tests using all apis but wgpu.
```

**Comment by jkwak-work** [comment]
I like to recommend checking out our contribution guide.
https://github.com/shader-slang/slang/blob/master/CONTRIBUTION.md
