### ISSUE TITLE
Support global-scope uniforms

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#550]
The front-end and layout logic should already be able to handle cases where the user declares uniform shader parameters at global scope:

```hlsl
float4 gColor;                // this is a shader parameter
static int gCounter = 0; // this is an "ordinary" per-thread global variable
```

When generating initial IR for a module, we simply emit global shader parameters as individual globals (see #549 for why we might want a distinct IR instruction type instead of just overloading globals to serve as parameters), but this would *not* be guaranteed to preserve declaration order for these global shader parameters. A first step toward a solution would be to group all of the global-scope shader parameters into a module into a single IR-level `struct` type, and then declare a single parameter of that type (so that access to individual parameters becomes access to fields of that `struct` parameter).

As part of "linking" together different IR modules, we would then need to construct a merged `struct` that includes a field for the `struct` of each relevant module, and then wrap that in a `ParameterBlock<>` ahead of type legalization (and apply all the computed layout to it, etc.). Type legalization would then split that parameter block back apart (for resources, etc.) but leave behind a single global constant buffer for the uniform parameters.

This is all do-able, but writing it up makes me wary that the implementation complexity would not pay off in terms of how useful the feature would be.

Two possible simplifications:

1. We could forgo the linking step, and say that each module gets a distinct global parameter block. That might simplify some things, but it would burn through parameter blocks faster.

2.  We could change the logic so that rather than wrap things in a parameter block up front, we instead treat that as a secondary legalization step: any global-scope shader parameter that is *not* of resource type needs to get wrapped up in a `ConstantBuffer<>`. It might be cleaner that way around.

This may still be too much work if we are looking at a long-term plan to discourage abuse of the global scope like this.

**Comment by natduca** [comment]
Lets close and reopen when we have customer use case
