### ISSUE TITLE
WGSL: refresh list of failing tests

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#5505]
After all the recent WGSL fixes, we may be able to run more tests that are previously disabled.

It is time to go through the list of disabled tests again, and make sure we have an updated understanding on each test:
- still failing?
- passing and should be removed from the list?

**Comment by aleino-nv** [comment]
Closed with https://github.com/shader-slang/slang/pull/5513.
Now there are 46 disabled tests that I have verified to be failing.

1. `tests/autodiff/custom-intrinsic.slang`
2. `tests/autodiff/existential-1.slang`
3. `tests/autodiff/existential-2.slang`
4. `tests/autodiff/material/diff-bwd-falcor-material-system.slang`
5. `tests/autodiff/material2/diff-bwd-falcor-material-system.slang`
6. `tests/bugs/atomic-coerce.slang`
7. `tests/bugs/buffer-swizzle-store.slang`
8. `tests/bugs/dxbc-double-problem.slang`
9. `tests/bugs/frexp-double.slang`
10. `tests/bugs/gh-3980.slang`
11. `tests/bugs/gh-518.slang`
12. `tests/bugs/op-assignment-unify-mat.slang`
13. `tests/bugs/shadowed-lookup.slang`
14. `tests/bugs/user-attribute-lookup.slang`
15. `tests/compute/atomics-buffer.slang`
16. `tests/compute/atomics-groupshared.slang`
17. `tests/compute/atomics.slang`
18. `tests/compute/buffer-type-splitting.slang`
19. `tests/compute/compile-time-loop.slang`
20. `tests/compute/constant-buffer-memory-packing.slang`
21. `tests/compute/constexpr.slang`
22. `tests/compute/discard-stmt.slang`
23. `tests/compute/func-cbuffer-param.slang`
24. `tests/compute/interface-shader-param-in-struct.slang`
25. `tests/compute/interface-shader-param.slang`
26. `tests/compute/loop-unroll.slang`
27. `tests/compute/matrix-layout.hlsl`
28. `tests/compute/texture-get-dimensions.slang`
29. `tests/compute/texture-sampling.slang`
30. `tests/compute/texture-simple.slang`
31. `tests/compute/transcendental-double.slang`
32. `tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang`
33. `tests/hlsl-intrinsic/classify-double.slang`
34. `tests/hlsl-intrinsic/classify-float.slang`
35. `tests/hlsl-intrinsic/matrix-float.slang`
36. `tests/hlsl-intrinsic/matrix-int.slang`
37. `tests/hlsl-intrinsic/scalar-double-simple.slang`
38. `tests/hlsl/packoffset.slang`
39. `tests/language-feature/constants/static-const-in-generic-interface.slang`
40. `tests/language-feature/enums/strongly-typed-id.slang`
41. `tests/language-feature/generics/tuple.slang`
42. `tests/language-feature/generics/variadic-0.slang`
43. `tests/language-feature/shader-params/interface-shader-param-ordinary.slang`
44. `tests/language-feature/swizzles/matrix-swizzle-write-array.slang`
45. `tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang`
46. `tests/optimization/func-resource-result/func-resource-result-complex.slang`
