### ISSUE TITLE
Redundant GL_EXT_samplerless_texture_functions?

### ISSUE THREAD

**Issue by Ollhax** [shader-slang/slang#5518]
I'm trying to get dimensions out of a 3d texture:

```
layout(binding=1) Sampler3D sampler;

...

float4 fragmentMain(...)
{
	int sizeX;
	int sizeY;
	int sizeZ;
	sampler.GetDimensions(sizeX, sizeY, sizeZ);
...
}
```

This shader doesn't work for me since it generates `#extension GL_EXT_samplerless_texture_functions : require` at the top, but that extension does not exist in regular OpenGL. I understand that Slang is not prioritizing/supporting GLSL shaders for OpenGL, but unless I'm missing something it's not really required in this situation anyway.

**Comment by csyonghe** [comment]
`\source\slang\slang-core-module-textures.cpp` line 494 needs to be made conditional so we don't emit that extension requirement if we are emitting code for the combined sampler.
