### ISSUE TITLE
Remove out of scope tests from wgsl failed test list.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#5519]
Many of the remaining WGSL "failures" are expected and out of the capability of WGSL, and we should just keep the DISABLED_TEST in the test files, and remove them from expected failure list.

We need to identify these tests. They should all fall into one the following cateogories:
- Integer matrices
- Arrays of textures or buffers
- Use of traditional atomics intrinsics (InterlockedXXX functions)
- Double and other unsupported scalar types

Let's remove the tests that falls into one of the above categories from the list, and work towards reducing that list to 0.

```
tests/autodiff/custom-intrinsic.slang
tests/autodiff/existential-1.slang
tests/autodiff/existential-2.slang
tests/autodiff/material/diff-bwd-falcor-material-system.slang
tests/autodiff/material2/diff-bwd-falcor-material-system.slang
tests/bugs/atomic-coerce.slang
tests/bugs/buffer-swizzle-store.slang
tests/bugs/dxbc-double-problem.slang
tests/bugs/frexp-double.slang
tests/bugs/gh-3980.slang
tests/bugs/gh-518.slang
tests/bugs/op-assignment-unify-mat.slang
tests/bugs/shadowed-lookup.slang
tests/bugs/user-attribute-lookup.slang
tests/compute/atomics-buffer.slang
tests/compute/atomics-groupshared.slang
tests/compute/atomics.slang
tests/compute/buffer-type-splitting.slang
tests/compute/compile-time-loop.slang
tests/compute/constant-buffer-memory-packing.slang
tests/compute/constexpr.slang
tests/compute/discard-stmt.slang
tests/compute/func-cbuffer-param.slang
tests/compute/interface-shader-param-in-struct.slang
tests/compute/interface-shader-param.slang
tests/compute/loop-unroll.slang
tests/compute/matrix-layout.hlsl
tests/compute/texture-get-dimensions.slang
tests/compute/texture-sampling.slang
tests/compute/texture-simple.slang
tests/compute/transcendental-double.slang
tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang
tests/hlsl-intrinsic/classify-double.slang
tests/hlsl-intrinsic/classify-float.slang
tests/hlsl-intrinsic/matrix-float.slang
tests/hlsl-intrinsic/matrix-int.slang
tests/hlsl-intrinsic/scalar-double-simple.slang
tests/hlsl/packoffset.slang
tests/language-feature/constants/static-const-in-generic-interface.slang
tests/language-feature/enums/strongly-typed-id.slang
tests/language-feature/generics/tuple.slang
tests/language-feature/generics/variadic-0.slang
tests/language-feature/shader-params/interface-shader-param-ordinary.slang
tests/language-feature/swizzles/matrix-swizzle-write-array.slang
tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang
tests/optimization/func-resource-result/func-resource-result-complex.slang
```

**Comment by aleino-nv** [comment]
- Not possible to easily support in WGSL:
  - 1D array texture not supported in WGSL:
    - `tests/compute/texture-get-dimensions.slang`
    - `tests/compute/texture-sampling.slang`
    - `tests/compute/texture-simple.slang`
  - Arrays of textures or buffers:
    - `tests/bugs/gh-518.slang`
    - `tests/compute/buffer-type-splitting.slang`
    - `tests/compute/loop-unroll.slang`
    - `tests/optimization/func-resource-result/func-resource-result-complex.slang`
  - Double and other unsupported scalar types:
    - `tests/bugs/dxbc-double-problem.slang`
    - `tests/bugs/frexp-double.slang`
    - `tests/compute/transcendental-double.slang`
    - `tests/hlsl-intrinsic/classify-double.slang`
    - `tests/hlsl-intrinsic/scalar-double-simple.slang`
  - Integer matrices, Double and other unsupported scalar types:
    - `tests/hlsl-intrinsic/matrix-float.slang`
  - Integer matrices:
    - `tests/bugs/op-assignment-unify-mat.slang`
    - `tests/hlsl-intrinsic/matrix-int.slang`
  - Use of traditional atomics intrinsics (InterlockedXXX functions):
    - `tests/bugs/atomic-coerce.slang`
    - `tests/compute/atomics-buffer.slang`
    - `tests/compute/atomics-groupshared.slang`
    - `tests/compute/atomics.slang`
- Now passing!:
  - `tests/compute/constant-buffer-memory-packing.slang`
  - `tests/compute/func-cbuffer-param.slang`
  - `tests/bugs/gh-3980.slang`
  - `tests/bugs/shadowed-lookup.slang`
  - `tests/compute/constexpr.slang`
  - tests/compute/matrix-layout.hlsl
  - `tests/hlsl-intrinsic/classify-float.slang`
  - `tests/hlsl/packoffset.slang`
- Passing, but: slang-test: Test context Slang session is leaking #5610:
  - `tests/compute/interface-shader-param-in-struct.slang`
  - `tests/compute/interface-shader-param.slang`
- Issues for us to focus on:
  - Slang-RHI/WGPU: Invalid bind group layout entry used #5612: `tests/bugs/buffer-swizzle-store.slang`
  - Slang-RHI/WGPU: Too small buffer is bound #5604: `tests/language-feature/shader-params/interface-shader-param-ordinary.slang`
  - WGPU: f16 extension not allowed in current environment #5605:
    - `tests/language-feature/generics/tuple.slang`
    - `tests/language-feature/generics/variadic-0.slang`
  - WGSL: Aim for getting all GFX tests to pass #4943: `tests/compute/texture-sampling-no-1d-arrays.slang`
  - WGSL: Assign to swizzle expression not allowed #5603:
    - `tests/language-feature/swizzles/matrix-swizzle-write-array.slang`
    - `tests/language-feature/swizzles/matrix-swizzle-write-swizzle.slang`
  - WGSL: Functions cannot be called at module scope #5607: `tests/language-feature/constants/static-const-in-generic-interface.slang`
  - WGSL: No matching overload for operator... #5606: `tests/language-feature/enums/strongly-typed-id.slang`
  - WGSL: Runtime-sized arrays not in 'storage' address space are being generated #5613: `tests/autodiff/diff-ptr-type-array.slang`
  - WGSL: Signed int initialized using unsigned int #5283: `tests/hlsl-intrinsic/byte-address-buffer/byte-address-struct.slang`
  - slang-test/WGPU: IR opcode during code emit #5263: `tests/autodiff/custom-intrinsic.slang`

**Comment by aleino-nv** [comment]
Now we have 19 disabled tests that we aren't planning to address, and 14 disabled tests that we should address.
Each of those 14 tests have corresponding issues created.

So totally we have 33 disabled tests.
