### ISSUE TITLE
[shader-playground] Mouse position access

### ISSUE THREAD

**Issue by NBickford-NV** [shader-slang/slang#5522]
In Shadertoy, `uniform vec4 iMouse` stores the pixel coordinate of the mouse the last time either mouse button was held down, along with the current state of the left and right mouse buttons.

When https://github.com/shader-slang/slang-playground/blob/394e6613ff9f587c71289451e70a2243e0d12d4e/demos/ocean.slang was ported to Slang, references to `iMouse` were replaced with a constant value of 0. As a result, this code in `getRay()`:

```glsl
  return createRotationMatrixAxisAngle(vec3(0.0, -1.0, 0.0), 3.0 * ((NormalizedMouse.x + 0.5) * 2.0 - 1.0)) 
    * createRotationMatrixAxisAngle(vec3(1.0, 0.0, 0.0), 0.5 + 1.5 * (((NormalizedMouse.y == 0.0 ? 0.27 : NormalizedMouse.y) * 1.0) * 2.0 - 1.0))
    * proj;
```

now creates two identity matrices (since the angle is 0) and multiplies them together:

```hlsl
  float3x3 mat = mul(createRotationMatrixAxisAngle(float3(0.0, -1.0, 0.0), 0.0),
                     createRotationMatrixAxisAngle(float3(1.0, 0.0, 0.0), 0.0)
                    );
  return mul(mat, proj);
```

If Shader Playground had an intrinsic for the mouse position, this part of the code could be restored.

Thanks!

**Comment by csyonghe** [comment]
This is done.
