### ISSUE TITLE
Test retry logic seems to be masking consistent failures

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5531]
`tests/compute/array-param` is crashing consistently in Slang-RHI/WGPU, yet somehow the test retry logic records a pass for this test.

**Comment by aleino-nv** [comment]
After some debugging, it seems for some reason array-param really isn't crashing on the second run. Strange...

**Comment by aleino-nv** [comment]
The issue is that `DeviceImpl::createBuffer` in Slang-RHI/WGPU for some reason fails to upload init data on the first try, and succeeds on the re-try...

Slang-RHI doesn't handle the failure well, so it just shows up as a nullptr deref when writing the buffer descriptor.

**Comment by aleino-nv** [comment]
This is triggering the "OnSubmittedWorkDone deprecated" messages from WebGPU, so I will try to just use the preferred API instead.

**Comment by aleino-nv** [comment]
> This is triggering the "OnSubmittedWorkDone deprecated" messages from WebGPU, so I will try to just use the preferred API instead.

That seems to help:
https://github.com/shader-slang/slang-rhi/pull/102

**Comment by aleino-nv** [comment]
There are still some MapAsync calls that seem to be causing retries. I saw validation error code from these calls while debugging.

**Comment by bmillsNV** [comment]
@aleino-nv is this issue passing now? Please update
