### ISSUE TITLE
Provide symbols for end user debugging.

### ISSUE THREAD

**Issue by moonheart08** [shader-slang/slang#5562]
I'm currently trying to prepare reproductions for a few issues I ran into attempting to write C# bindings for the slang compiler (including what appears to be incorrect ABI for COM interfaces.), and at this time it looks like in order to get proper stack traces I would need to build all of slang locally. (Something that is beyond the scope of my current project.)

Release builds of slang should at least include a `.pdb` file so windbg and other debuggers can provide proper stack traces. All other DLLs that are shipped as part of the Vulkan SDK include symbols and the lack of them for slang has proven problematic for debugging FFI/interop issues.

**Comment by csyonghe** [comment]
@expipiplus1 It looks like although we are using relWithDebInfo config in our CI process, we are not packaging up the pdb files in the final package. Can you patch this?
