### ISSUE TITLE
fmax3 implemented incorrectly for non-metal targets

### ISSUE THREAD

**Issue by cheneym2** [shader-slang/slang#5581]
By inspection, this appears to have a bug where X is NaN and Y and Z are not specials.

fmin3() has a similar issue as described below for fmax3()

fmax3(NaN, 1, 2) should return 2 but would return 1.

```
__generic<T : __BuiltinFloatingPointType>
[__readNone]
[require(cpp_cuda_glsl_hlsl_metal_spirv, sm_4_0_version)]
T fmax3(T x, T y, T z)
{
    __target_switch
    {
    case metal: __intrinsic_asm "fmax3";
    default:
    {
        bool isnanX = isnan(x);
        bool isnanY = isnan(y);
        bool isnanZ = isnan(z);

        if (isnanX)
        {
            return isnanY ? z : y;
        }
        else if (isnanY)
        {
            if (isnanZ)
                return x;
            return max(x, z);
        }
        else if (isnanZ)
        {
            return max(x, y);
        }

        return max(y, max(x, z));
    }
    }
}
```

**Comment by cheneym2** [comment]
See also https://github.com/shader-slang/slang/issues/5580 which would simplify the implementation of fmax3()

**Comment by cheneym2** [comment]
I think fmax3() could be implemented purely as fmax(x, fmax(y, z)) if fmax() was fixed, per issue 5580

**Comment by jkwak-work** [comment]
As I said on [the other issue](https://github.com/shader-slang/slang/issues/5587#issuecomment-2486947593), I think we should remove fmax3/fmin3 from hlsl.meta.slang
