### ISSUE TITLE
powr() implemented inefficiently for non-metal targets

### ISSUE THREAD

**Issue by cheneym2** [shader-slang/slang#5587]
It seems like powr() is implemented inefficiently on non-metal targets.  If I understand correctly, powr() is only defined for x>=0 but for some reason we coerce x to be abs(x) before delegating to regular pow() for other targets, instead of letting it be undefined.

```
/// @category math
__generic<T : __BuiltinFloatingPointType>
[__readNone]
[require(cpp_cuda_glsl_hlsl_metal_spirv_wgsl, sm_4_0_version)]
T powr(T x, T y)
{
    __target_switch
    {
    case metal: __intrinsic_asm "powr";
    default:
        return pow(abs(x), y);
    }
}
```

**Comment by jkwak-work** [comment]
I think we should simply remove the function `powr`.
When I added it, I misunderstood what needed to be done and I added bunch of Metal only functions in hlsl.meta.slang.
I wasn't meant to add new intrinsics only because Metal has those.

**Comment by cheneym2** [comment]
https://github.com/shader-slang/slang/commit/997f040f48b5c34e20ad6b0f512bb9d1ae6e6128 is Jay's change that introduced the new match functions from Metal.

I'm unsure if it's proper to get rid of these functions.  I know it's a breaking change to remove them at this point though.
