### ISSUE TITLE
[SpecializationConstant] should not cause allocation of descriptor set binding.

### ISSUE THREAD

**Issue by ov-l** [shader-slang/slang#5595]
Hi,

First off, thanks for providing a shader playground.
I was hoping that this could be supported, where all push constants are grouped together into a single constant block 
```hlsl
// Somehow multiple push_constant can be declared !!
// But they dont compile into valid glsl
[vk::push_constant]
ConstBufferPointer<MaterialData> gPushConstants;

[vk::push_constant]
ConstBufferPointer<ObjectData> gObjectData;
```
Instead it generates glsl with two push constant blocks. I believe at-least it should throw an error. [Shader link](https://shader-slang.com/slang-playground/?target=GLSL&code=eJyFVFFv2jAQfs-vuHYvQUMhZXsqpVKBqqvWKhVQNAmhyCQX8JrYyLFZq6n_fZc4IaGo2ksS3333fefP5_R6kMnYpAhjqXAWbTFjA8dZhuGN1oqvjcbnnG3QbdZzpjaoc2_BVGfl7Mw65RHkWplIw4iLmIvNAev8daDIUQwEy3DgvBP7lxgTLhDuHoLRzUM4u52DT5r7l8vLtSVw_W4rSzJhOHkjAh5NMZdGRXh1EvlJpd4dClQsvYZNOMdXbRT-QLZbrki16jRJJdPfIWfZLsUK4xouNGi7uBcxvnYtrg9m3yk3keIBAMMP7O3Clcfyq1lJrvqTa7czoGKFlBd1vWfTLlGTH45TebdARYDA6J3RpWTV6U7mcAmzRfgkc665FIM6V3RHqfntr3EQTCf-oCmKZCoV5cbBQzD1re2VziPTqDhLJ0yzRqdf6JT0QZLkqA9c32DNopeNkkbE44K1LS-4njKxwSJWephIoStrjkSD9W-MdC35iWKB7_VgJjPcyj-QmVRzMgp2Jt-GkRS5ZiQRMQFrhBijlCmM4eysKBoZOp8tvkEsC4zMdpwqqSUJe5byGDZpntoZO6JbOctqaN3z2plzGrhxkR-ZJEH1JIkG1VXbOBqwJ6IZVyz5wPkPtzXgE-bGHeJtFoMPs3Ev6tEotVIZscI-1yfWk2Okw28PzHHFRbuiHKLnhX8K6zewZqRsL9UoFEe2zLcsRuWe78tMscf2LIMNPzIu3NY-qrC9XW1rIWsvhh-M9ujfYy9V4xNIOnlVw5t4jSXwUUOyfBUc9ssrrtiw2qfblveORxS-NlKnKbuhQ7wLvucnXbigZ6clRnYPa6zZtxLW4EMusg43v4-67XfnHwjv9i0)

Thanks in advance.

**Comment by csyonghe** [comment]
The `[vk::push_constant]` attribute is provided for backward compatibility with DXC, which also does not allow multiple push constant blocks.

In Slang, the native way to use push constants is to define them as entrypoint uniform parameters.
All entrypoint uniform parameters are automatically translated to push constants, and they will be merged together too.

For example:
```
void main(uniform MaterialData* material, uniform ObjectData* object) {}
```
will result in SPIRV that puts both `material` and `object` into a single push constant block.

**Comment by ov-l** [comment]
Thanks that works for me. 
One question, I am trying to come up with a way I can ensure a shader can be compiled in bindless and bindful path as per engine mode. Your suggestion would work great for me, as I could put all required parameters in a shader as function parameter. However, if I do not explicitly provide a binding index using `vk::binding`, why does the set start at 1: [Shader](https://shader-slang.com/slang-playground/?target=SPIRV&code=eJyVVNtu2kAQfd-vGCUvJkKEUp5wipRA01RNCsIkqoQQWuwxWcXetfaCklT5945vYEpatS-wnpkzc-bszJ5mmm9SDkqGyNhphLGQCAGmXFoR3qqQW6GkVx9asNg-DQbJkX15hP3OU_TynxYMIP9n7Pwc6qgrIaMEjbkMrdjmlUVMnmNzFZ5xzVMhwUkRK50y-5IhTwQ3BeJiPoRPMD_zG_Zgjs_WaeyNyeWEtD5jBfc1AYTceN02dIn2ajV-kZQ7nKFRTod4cWT5RojOF5SoeTKEzarKfIM8WywpbebWiQghThS3fTA8zRIq6zUY2PL0VUb43C4De-C2LfaTASRo6wCiepi-CVx2uLkIiuy6Nx56LZ_AGskva3yndHuU2mdvjPTDxLwj47v6TXMnWtRXdL1PZKPW_qDnjsX_dH_U-N-5nyLdU5zPTKoilyCMlMYgfKTxoqoNZk7SRPSIVZne_93Vr139HEf5gkeuMYLAahfmlQ1jpjjDVCUvD6iJUW9cUDxahG6LrFUfmTIiNx6O_LSyFtdzhP-Q4yvGbnuIvH_ovg_q7UB9CFWi9CGuZDzKHYRnb_6un9IzcTZztuinuiViTksZPKxqsv6-K2I1gPnnH6PJZDbu-ntQWXkAo8ntZEaORp07TmMjeDLmlu_r7BWaxLFBu8v1EdY8fNpo5WRU0G6Wl8LOuNxgocR-iGIlbfVVll4EGYZUU7wWIo2UNJY0WbIwPwFtPNxwM9cOg_E1jQAx_gfIlBtzLRJqp4SwxWp1aa0Wa2fx3vANevvvOdcbtKZTbA69JdUqVKJclQ_NLroQhnxkA3pf6jbMI49Qeydx_hCjtCeUqFI8N91xIT0CLqp03klaiZ0Hwm6liz1u3sMQ6sA2hTUnAbbFx8ESlqZOecdn-zWuc3Qa-rfr6GpVfwEP9SLH) 

Also I am unsure if the `typealias` with generic is valid, but it seems to be compiling fine, so I guess it is fine ? 

Thanks a lot for the quick reply. Lastly, would you mind giving your opinion if this is a good approach to handle scenario where both bindless and bindful path need to be supported by a shader or is there a better way to do it with slang.

Thanks in advance.

**Comment by csyonghe** [comment]
I think it is a bug for the ParameterBlock to be assigned set 1. This is likely due to the existence of:
```
[SpecializationConstant]
const int HasTrueSDF = 0;
[SpecializationConstant]
const int PassFilter = 0;
```
Slang might be thinking these are normal uniforms and need a uniform buffer binding in set 0, so any future parmaeter blocks got assigned set 1. Removing these the `material` block is now at set 0.

Slang currently does not have a first-class way of doing bindless, so I think your solution should work fine.

**Comment by ov-l** [comment]
Thanks, if you are okay, I keep this issue open to track the bug related to set assignment, or I could open a new issue, as you want.

**Comment by csyonghe** [comment]
We can keep this issue as is, I updated the title to reflect the issue.

**Comment by ov-l** [comment]
Thanks for the patch, however, I am still having issues with a generated shader after applying your patch. The SPIR-V output still contains DescriptorSet index as 1 as the only descriptor set. I will share with you the shader I am using and the SPIR-V generated. [Shader](https://shader-slang.com/slang-playground/?target=SPIRV&code=eJytVltv2kgUfp9fMaIvdhc5lM0ThEhb2LSrbZcoplElhNBgjsko9tg7nkFJV_nve-biW-mFldYSxpz7-b5zxlxc0LzY6wzovJAQJw-Qsykh6-32N6Uk32kFnyp2gKD9vWLyAKqKbplkeTikZ5jeMxluSKl3GU9opaROFH3LxZ6LQ2NL_iHU6FBGBcthSl7OLORGi0TxQpykuGVV9eP4r3i6hxRbSMpMV-ZDXqGAC6AxIiEUTz4UCTPRg_ohPDH5C8MF5oYqyCo4IwZdHx8nk-xEvvlBcDqh5htzIHIpqYs3QGaAnSIIRyBNgNLwwwXVgqeFzAlRzyWwjLPKulytrileM7p6Pe2o4hU8KS1hvECV5kIZEkytO8dXMBrSd1mxY1kMCsvdbhfPCCdP7qAqtEzg6kTyJ3pG70CAZNk1PWx9hvfAyvUGw3vS0qxg6pJWLC8zTB90KlHu6Q-xh6ehMxxTfQwtpxmo2gBL7ofvOm4iVl3FNrocL66DcIrOElAvav_IqQMMjeNBHJv04uKnGH8XXLskoEC-Ra4fUfxdrJvK_gsiJ2D8rB83OW0JWuBojDG9izP9WnVZqy6xLAQifmAS9jS2C4YZKkLqZSuy53uQmHm8sKWcDP8oRKmvtywqboT9Mb_1UkvNif8b4-8L1se-56f70bedxo3TJU2KrJB9P1fx3ChCd-L4dpxiqVWplW3Hk4GF4x7G99u61mnbFBY1oavfP8-Xy7vFaNo6ucQTOl9-WN6Nenk-MhwOzrIFU6zN0wK0TNMKVBPrV7pjyeNBFlrsbdW26XYuaub96RmXkGBw_sWCMS9EpbD3DUnME8Xtpu9ZtZIa4sUNMo2lneFijtUbnmHdZ7usIHkQ_G8NXT-yrh7YHmQwOFqwB3icdGGnTvyRcRFgl2v_xggGNWboQFFRL6FdvC6e1zTv_BqiaXdIfXizN6jpJS7sl4HWPUWG9XoRgm7QqM8T_cVHbeRDOopG6ZC-wXvYiYizMqtt9bGjcLPS6BJHcrvadW24ziB0btmwgwPLkiHCpk1YSSYqxAWEsoNgLRsSnLkfmr11iLk5KNzQ1Kykkh1yjGB4WZs0wcClGC8G-N53kk4mI94QP_K18__JXo8jLvDuyfM53eUA9NfM2dUwUspTGpxM46zFJmpwMQeHAaqO-HrWnsS9EWjOYpfKHraUvhCfrbsuM4ta5KkKbXTPqx8ufAWUgU0YPT1_GfYwiL7a_aGrLGKhnS-b1v7_6IT1jb-QfwFoKFy4) /
[SPIR-V](https://github.com/user-attachments/files/17894324/SimplePoly2D.txt)

**Comment by ov-l** [comment]
My apologies. Indeed, I pulled the latest changes again and clean rebuild everything. Seems to be working after that.

**Comment by ov-l** [comment]
In-fact the issue I was having is not due to SpecializationConstants. I still end up having a descriptor set at index 1. [Updated shader](https://shader-slang.com/slang-playground/?target=SPIRV&code=eJytVltv2kgUfvevGNEXu4sMZfMEIdIWNu1q2xLFNFoJITSYYzKKPfbOBSVd5b_vmYtvZdum0lrCmHM_33fOmNGIFOVB50AWpYAkvYeCzoJgs9v9ppRge63gs6RHCNvfayqOoGR8QwUtoiF5gekdFdE2qPQ-ZymRSuhUkbeMHxg_NrbBPwExOpQRTguYBc8vLORa81Sxkp-luKFSfj_-K5YdIMMW0irX0nyCVyhgHEiCSHDF0g9lSk30sH6Izkw-YbjQ3FAFuYQXxCCb08N0mp_Jt98JTqbEfGMORC4L6uINkDlgpwjCCYImQGX4YZxozrJSFEGgniqgOaPSulyurwhec7J-PeuokjU8Ki1gskSVZlwZEkyte8dXOB6Sd3m5p3kCCsvd7ZZPCCdLb0GWWqRweSb5Ez3jd8BB0PyKHHc-w3ug1WaL4T1pWV5SdUEkLaoc04edSpR7-oMf4HHoDCdEnyLLaQ6qNsCS--G7jtuYysvERheT5VUYzdBZAOp57R87dYihcTwCxyYZjX6I8TfBtUsCCsRb5PoBxd_EuqnsZxA5A-NH_bjJaUvQHEdjguldnNnXqotadYFlIRDJPRVwIIldMMwgg6BetjJ_ugOBmSdLW8rZ8I8jlPp6q1IyI-yP-Y2XWmrO_N8Yf1-wPvU9P9-N_9tp0jhdkLTMS9H3cxUvjCJyJ45vxylWWlVa2XY8GVg47mFyt6trnbVNYVFTsv79r8Vqdbscz1onl3hKFqsPq9txL89HisPBaL6kirZ5WoBWWSZBNbF-JXuaPhxFqfnBVm2bbueiZt7lGI02SQUphmdfLByLkkuF3W9RlZpnghtO3lO5FhqS5TWyjeW90M0cr9csx_p_ym0N6T1nf2vo-gYbeU8PIMLByQI_wKOlSwFx4o-U8RA73vi3Rzio8UMHgop6Ie0SdrG9IkXn1xBNuwPrw5sdQk0vcWm_DMzuKTYTUC9F2A0a9zkjv_iojXxIxvE4G5I3eI86EXFu5rWtPnUUbm4aXeoIb9e8rg1XG7guLCN2iGBVUUTYtAlrQblEXIArOxTWsiHBmfsBOliHhJlDw71-a1YyQY8FRjC8bEyacOBSTJYD_A_gJJ1MRrwN_PjXzv8nez2OGMe7J8_ndJcD0F9zZ1fDSPBgZxkJz-Zx3qITN8iYY8RAVcd8PW_P5d4QNCezS2aPXkKegyZfd23mFrnY0xXZ-J5bP2D4SqhCmzJ-fPoy7OEQf3UWDF1tMY3sjEWuR_uPxDw0oT0Az8G_i5hgZA)

The shader I have should not produce a new DescriptorSet. I was actually having the issue in the GraphicsPipeline creation which was reporting I have no layout in my descriptorSetLayout for DescriptorSet 1, and it had me confused why was there a set at 1 to begin with, because indeed the reflection interface was also not reporting it.

**Comment by csyonghe** [comment]
I think this is due to a bug when compiling both entry points into the same spirv module.

What happens if you compile just the fragment shader EntryPoint?

`slangc shader.slang -target spirv -entry fragmentMain -stage fragment`

**Comment by csyonghe** [comment]
It feels like the entry point parameters some how got duplicated when there are two entry points.

**Comment by ov-l** [comment]
In-fact if I just compile using shader playground for example, by removing either of the entry points, everything is good.

**Comment by ov-l** [comment]
> It feels like the entry point parameters some how got duplicated when there are two entry points.

Another possibility is the TypeLayout is different due to parameter usage, so they are split into two different ParameterGroup.

**Comment by pdjonov** [comment]
> The `[vk::push_constant]` attribute is provided for backward compatibility with DXC, which also does not allow multiple push constant blocks.
> 
> In Slang, the native way to use push constants is to define them as entrypoint uniform parameters. All entrypoint uniform parameters are automatically translated to push constants, and they will be merged together too.

You may be thinking of `[vk:push_constant]` as a back-compat feature, but to me it's actually great way to pull repetitive code that deals with push constant data out of multiple entry point declarations across several files and into a module. Please don't ever deprecate it!😝

**Comment by csyonghe** [comment]
After looking more into this issue, I think we should keep the existing behavior.

Consider the following:
```
[shader("vertex")]
VertexOut vertexShader(uniform ParameterBlock<VertexParams> pv) {...}

[shader("fragment")]
float4 fragmentShader(uniform ParameterBlock<FragmentParams> pf, VertexOut vin) {...}
```

When compiling both shader entrypoints into the same spirv module, we have to put `pv` and `pf` into separate descriptor sets, because it is possible that `vertexShader` and `fragmentShader` are being included in the same graphics pipeline, in which case `pv` and `pf` must be bound to different descriptor sets.

So the current behavior that you are seeing is actually correct. When you have two entrypoints each declaring a ParameterBlock, the compiled spirv module will contain duplicate parameter declarations in different descriptor sets. If you wish to share the parameter binding across different entrypoints, the only solution right now is to declare them in the global scope.

For this reason, I am going to close this issue as won't fix.

**Comment by obhi-d** [comment]
Why is it not possible to match type-name between the two uniform passed to each method ? Does the set/binding assignment happen before linking the two shaders ? if not, I feel like it should be manageable to do the assignment once, if this info is stored in the AST. But anyway, if this is a permanent restriction, I don't see function parameters on entry points as very useful.

**Comment by csyonghe** [comment]
This kind of matching and deduplication is too much magic and may lead to surprises. It is completely possible and valid for different EntryPoint parameters of the same type to mean different instances. In general the compiler shouldn't deduplicate two distinct declarations just because they have the same type.

As said in previous post, if sharing of a parameter among different entry points is intended, then declaring it in global scope is the only viable way currently.
