### ISSUE TITLE
Local functions 

### ISSUE THREAD

**Issue by Ollhax** [shader-slang/slang#5624]
Without checking the manual too closely I tried writing a local function like this:

```
float4 fragmentMain(VertexOutput vertex) : SV_Target
{
  static float GetValue(int val) { return val; } // Simplified example
  float a = GetValue(vertex.Input);

  // etc
}
```

So from what I understand this is not something that's actually supported, there's currently no support for local functions/lambda functions/closures/etc. But it still compiles into correct code - is this parsed as a member function? It has a few problems:

* It crashes the language server in VS Code, i.e. code completion stops working.
* When I tried to use a value from an outer function (thinking closures are supported) it compiled, but generated invalid GLSL.

Unless I'm completely off the mark here, declaring a function like GetValue inside a function should probably just produce an error.

**Comment by csyonghe** [comment]
Yes, this needs to produce an error.
