### ISSUE TITLE
tests/compute/*type-param* tests are broken

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5627]
Output with slangc:

    c:\Users\aleino\environments\slang>C:\Users\aleino\workspaces\slang\build\Debug\bin\slangc.exe -o C:\Users\aleino\targets\hello-webgpu\test_compute.wgsl -target wgsl -stage compute -entry computeMain C:\Users\aleino\workspaces\slang\tests/compute/type-param-varying.slang   || exit 1 
    C:\Users\aleino\workspaces\slang\tests/compute/type-param-varying.slang(53): error 30027: 'ColorSet' is not a member of 'typeof(TVertex)'.
        TVertex.ColorSet    color;
                ^~~~~~~~
    C:\Users\aleino\workspaces\slang\tests/compute/type-param-varying.slang(80): error 30027: 'getPosition' is not a member of 'TVertex'.
        float3 position = input.assembledVertex.getPosition();
                                                ^~~~~~~~~~~
    C:\Users\aleino\workspaces\slang\tests/compute/type-param-varying.slang(82): error 30027: 'getUv' is not a member of 'TVertex'.
        output.coarseVertex.uv = input.assembledVertex.getUv();
                                                       ^~~~~
    C:\Users\aleino\workspaces\slang\tests/compute/type-param-varying.slang(83): error 30027: 'getColorSet' is not a member of 'TVertex'.
        output.coarseVertex.color = input.assembledVertex.getColorSet();
                                                          ^~~~~~~~~~~
    (0): error 30015: undefined identifier 'computeMain'.
    C:\Users\aleino\workspaces\slang\tests/compute/type-param-varying.slang(8): error 38000: no function found matching entry point name 'computeMain'
    interface IColorSet
    ^~~~~~~~~

**Comment by aleino-nv** [comment]
@bmillsNV Yesterday @csyonghe indicated that we should perhaps just close this issue.

**Comment by bmillsNV** [comment]
Closing as we WNF.
