### ISSUE TITLE
Always add vtable to struct?

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#5629]
Is there a way to always add a vtable to structs that implement an interface?

When such a type is directly used (without an interface or second type implementing this interface) in some shader this vtable space is often removed. This makes it hard to reuse buffers in cases with and without vtable. Is there an option to always add the vtable for interface implementations?

```c#
interface IShape {}

struct Sphere : IShape {
    float radius;
};
struct Cube : IShape {
    float size;
};
```

```c#
StructuredBuffer<IShape> shapes;
// if typeconformance includes Sphere and Cube -> radius/size starts at offset 16 bytes (vtable)
// if typeconformance includes just Sphere -> radius starts at offset 0 bytes (no vtable)

StructuredBuffer<Sphere> spheres;
// radius starts at offset 0 bytes (no vtable)
```
This makes it really hard to manage the backend buffer of shapes/spheres, would be nice if interface types would always include the vtable.

**Comment by csyonghe** [comment]
I think this is a bug and the data layout should be stable by always include the 16byte header.

**Comment by fknfilewalker** [comment]
Shouldn't Sphere or Cube also have the header (since they implement an Interface), even if their types are used directly?

Right now something like `StructuredBuffer<Sphere>` does not have the 16 bit header. What if I call a function that wants an IShape with this?

**Comment by csyonghe** [comment]
No, concrete types should not have the header. Interface conformance is not the same as inheritance.

when passing a concrete type value to IShape, slang will”box” the value by appending the header, and pass the composite to the callee.

**Comment by fknfilewalker** [comment]
Ok good to know that this will not change, then I will work around that
