### ISSUE TITLE
Type legalization is skipping some instructions

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#563]
The IR type legalization pass was set up to legalize global functions, variables, and constants, but this ignores other global instructions that might need legalization to be applied.

In particular, an IR `struct` type currently won't be legalized unless it is referenced by some other instruction that does get legalized. If such a type uses an "illegal" type for a field, then it won't get updated even after the "illegal" field type gets removed from the IR module.

The right fix here is for type legalization to apply top-down to the entire module, including intermediate nodes like types (e.g., a `FuncType` instruction that uses an illegal type as a parameter or result should get legalized too).

**Comment by csyonghe** [comment]
Fixed.
