### ISSUE TITLE
Missing macOS in binaries for release v2024.14.5

### ISSUE THREAD

**Issue by eliemichel** [shader-slang/slang#5648]
I noticed the latest release does not include macOS binaries: has macOS support been discontinued? Or more probably a failure of the release process (that maybe needs fixing)?

**Comment by jkwak-work** [comment]
Maybe we should have a Discord/Slack notification when `release.yml` workflow failed.

**Comment by expipiplus1** [comment]
Assigning to @csyonghe as IIRC we use his apple dev account for this

**Comment by csyonghe** [comment]
Re-agreed the apple developer agreement, and release 2024.15 now contains macos builds. Closing.
