### ISSUE TITLE
Add command-line option to specify global generic arguments

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#565]
Once we support generic arguments directly on entry points it makes sense to allow, e.g., `-entry “myShader<MyType>“`, but for global generic arguments we’ll need a distinct syntax, like `-global-generic-arg TMaterial=MyMaterial`.

I think it makes sense to include the parameter names rather than relying on ordering, but for a first version we could just have something like `-global-generic-arg MyMaterial` and assume that the order or arguments must match the bindings for the parameters.

This isn’t likely to be a feature people would need from `slangc` often, but it seems important to strive for parity between the command-line tool and API whenever possible.

**Comment by csyonghe** [comment]
Closing now. We are no longer investing in global generic arguments.
