### ISSUE TITLE
intensive extracting during workflow 

### ISSUE THREAD

**Issue by TheforgottenDreamer** [shader-slang/slang#5657]
"Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at ThirdParty/slang/cmake/FetchedSharedLibrary.cmake:29 (file):
  file failed to extract:
  C:/Users/***/out/build/x64-debug/ThirdParty/slang/slang-llvm.14.5-windows-x86_64.zip		C:\Users\***\ThirdParty/slang/cmake/FetchedSharedLibrary.cmake	29"

everytime the workflow is set the cmake would atempt to get the zpi files and extract it even if it exsist causing this error

**Comment by expipiplus1** [comment]
@TheforgottenDreamer please check if this solves things for you https://github.com/shader-slang/slang/pull/5707

**Comment by expipiplus1** [comment]
Closed by https://github.com/shader-slang/slang/pull/5707
