### ISSUE TITLE
SkyBox.slang GLSL compilation fails with version 0.10.16

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#568]
Steps to reproduce:
- Get Falcor `dev-3.0.3` branch
- Change the Slang version in the dependencies file
- Run the SkyBoxRenderer sample

**Comment by tfoleyNV** [comment]
Somehow Slang is producing IR that declares a local variable after its use sites. This is obviously invalid.

I suspect something in the GLSL legalization step for shader outputs (since the variable in question is being used to write `gl_Position`, so I will investigate that first.
