### ISSUE TITLE
Plans for the reflection API?

### ISSUE THREAD

**Issue by DragosPopse** [shader-slang/slang#5683]
As per https://github.com/shader-slang/slang/pull/5301 and reading on https://github.com/shader-slang/slang/issues/5565 . I understand the plan is to favor COM interfaces and move away entirely from the C API. 

The current reflection API in `slang.h` seems to be wrapper classes around the deprecated C API. 

I am currently writing odin bindings for the Slang API and I wanted to ask what are the plans  (if any) on the reflection API. Will there be COM objects for it? Will the Reflections C API be nuked from existence in the foreseeable future? 

I might be wrong in the following statement, but it seems weird to me to move this particular api to `deprecated.h` when there isn't an ABI-stable alternative to it at the moment. 

Thank you for this project and looking forward to see where things go

**Comment by csyonghe** [comment]
I am OK with keeping language bindings in separate repos if that makes things cleaner to work with. The C api should definitely be maintained here.

Is there a standard for such a json / xml com descriptor file? Are there any existing solutions to produce COM bindings from a json?

**Comment by laurooyen** [comment]
> Is there a standard for such a json / xml com descriptor file?

Not that I know of. As far as I'm aware Vulkans XML schema is custom. The advantage of XML/JSON is that most languages provide plenty of options to read those formats.

> I managed to write manual bindings to `slang.h` in a few hours

That's what I do for the COM interfaces in my bindings too. It's too error prone especially when keeping up with new releases.

By providing the API in a machine readable format, generating bindings from other languages should be much easier. It also lifts the burden of having to maintain all of those bindings here whilst giving implementors of said bindings the freedom generate opinionated wrappers.

**Comment by csyonghe** [comment]
I support the idea to provide a json file for the com bindings to make downstream work of binding generation easier.

**Comment by laurooyen** [comment]
I'll continue work on the binding generator and try to provide C and JSON targets. Will file a separate issue to track that work.
