### ISSUE TITLE
Compiler hangs on recursive functions when targeting Metal

### ISSUE THREAD

**Issue by dbartussek** [shader-slang/slang#5684]
Attempting to compile the following code targeting Metal results in the compiler hanging:
```
[shader("compute")]
func m() {
    r();
}

func r() {
    r();
}
```

I stumbled on this while messing around in the playground: https://shader-slang.com/slang-playground/?target=METAL&code=eJyLLs5ITEkt0lBKzs8tKC1JVdKM5UorzUtWyNXQVKjmUgCCIg1Na65aLohwEZowAHEsEU0

**Comment by jkwak-work** [comment]
Currently the recursive function call is supported only for CPU targets.
Slang-playground is pretty new and it may not be able to handle error message well yet.

When you compile the given shader with slangc.exe, you can see the error message,
```
test.slang(7): error 55201: recursion detected in call to 'r', but the current code generation target does not allow recursion.
    r();
     ^
```

**Comment by dbartussek** [comment]
Did you use the Metal target on slangc? I could also trigger the hang with the current release of slangc, but only when targeting Metal.

You are correct that all other targets show the error message, even on the playground. I also haven't been able to test it with the current head version because I couldn't get slangc to compile, so the issue _may_ already have been fixed.
