### ISSUE TITLE
PR gets stuck when there are only document changes

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#5689]
When PR has only document files changed, the CI gets stuck.
"build"-s are not supposed to be triggered but they are.
I am not sure if it related to the recent change with "licence/cla" action.

![image](https://github.com/user-attachments/assets/ac0dcbae-8dbb-4109-881e-22b9de1a2393)

**Comment by jkwak-work** [comment]
Two examples can be found here:
 - https://github.com/shader-slang/slang/pull/5659
 - https://github.com/shader-slang/slang/pull/5672

**Comment by expipiplus1** [comment]
It is because that CI ignores changes restricted to the docs directory, this is safe to ignore. Or we can unconditionally run such workflows

**Comment by jkwak-work** [comment]
Why does the build workflows are triggered in the first place?
The label checking workflow seems to be doing fine as expected in a way that it is not triggered at all.
They seem to have the same path-ignore settings.

**Comment by csyonghe** [comment]
The tests are showing up because the repo is configured to expect these tests to pass, when in fact they are not triggered. This is just a github display issue, and no tests are actually stuck.
