### ISSUE TITLE
PushConstant gets mistakenly recognized as binding

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#5693]
The following code,  produces the following error
```c++

[[vk::binding(0, 0)]] RWTexture2D<float4> output;
[[vk::push_constant]] RaytracingAccelerationStructure tlas;

[shader("raygeneration")]
void rayGenMain()
{}

```

```
VUID-VkRayTracingPipelineCreateInfoKHR-layout-07988(ERROR / SPEC): msgNum: -859700687 - Validation Error: [ VUID-VkRayTracingPipelineCreateInfoKHR-layout-07988 ] Object 0: handle = 0x4fac1c0000000032, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0xa808d50000000033, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0xccc20231 | vkCreateRayTracingPipelinesKHR(): pCreateInfos[0].pStages[0] SPIR-V (VK_SHADER_STAGE_RAYGEN_BIT_KHR) uses descriptor [Set 0, Binding 1, variable "tlas"] (type VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR) but was not declared in the pipeline layout.
The Vulkan spec states: If a resource variables is declared in a shader, a descriptor slot in layout must match the shader stage (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-VkRayTracingPipelineCreateInfoKHR-layout-07988)
    Objects: 2
        [0] 0x4fac1c0000000032, type: 15, name: NULL
        [1] 0xa808d50000000033, type: 17, name: NULL
```

For some reason the pushconstant is a descriptor binding (set 0, binding 1)

**Comment by csyonghe** [comment]
`RaytracingAccelerationStructure` is an opaque handle and it is not possible to place it as a push constant in SPIRV. Therefore the [vk::push_constant] attribute has no meaning and is ignored by the compiler.

**Comment by fknfilewalker** [comment]
Oh ok but cast from uint64 should work? At least in glsl this worked.

**Comment by csyonghe** [comment]
Casting from uint64 to AccelerationStructure is not valid in HLSL and it is not supported in Slang either. D3D does not specify that AccelerationStructure can be constructed from uint64. If we add such support in Slang, it won't be a cross-platform operation either.

**Comment by fknfilewalker** [comment]
I guess I could hack something together with inline spirv?

**Comment by csyonghe** [comment]
That may be possible and certainly worth a try.

**Comment by bmillsNV** [comment]
@fknfilewalker does the WAR that @csyonghe suggest work for you? If so - are you ok with closing this issue for now?

**Comment by fknfilewalker** [comment]
I did try this
```c++
__glsl_extension(GL_EXT_ray_tracing)
[ForceInline]
RaytracingAccelerationStructure addressToAccelerationStructure(uint64_t address)
{
    return spirv_asm {
        OpCapability RayTracingKHR;
        OpExtension "SPV_KHR_ray_tracing";
        result:$$RaytracingAccelerationStructure = OpConvertUToAccelerationStructureKHR %address
    };
}
```
but it did not work. Maybe you see the error otherwise it is fine for now.

**Comment by natevm** [comment]
> Casting from uint64 to AccelerationStructure is not valid in HLSL and it is not supported in Slang either. D3D does not specify that AccelerationStructure can be constructed from uint64. If we add such support in Slang, it won't be a cross-platform operation either.

This is a temporary constraint in HLSL / DXR spec that will likely be addressed eventually, particularly given that they are moving to adopt SPIR-V for their IR. (Still, I can bring this up to Martin, perhaps we could get some correction to the DXR spec about the sizeof an acceleration structure handle...)

I'd advise against us constraining Slang to cater the restrictions of one particular target backend (DXR) over the others. In both OptiX and in Vulkan, constructing an accel from a pointer (uint64) is the standard way to get accel handles into SBT / push constant structs. 

For the moment, we might want to consider exposing this via an intrinsic that's made available through Slang's compatibility system, similar to how we handle other features that HLSL (or any other target backend API) might not currently support.

**Comment by natevm** [comment]
> @fknfilewalker does the WAR that @csyonghe suggest work for you? If so - are you ok with closing this issue for now?

For the above, we can pivot discussion to issue #5801.

**Comment by csyonghe** [comment]
PR https://github.com/shader-slang/slang/pull/5967 added `RaytracingAccelerationStructure(uint64_t)`.
