### ISSUE TITLE
[SPIR-V] Creating pointers from inline spirv_asm creates invalid types (storage class mismatch)

### ISSUE THREAD

**Issue by nvlduc** [shader-slang/slang#5703]
Hi,

I am trying to create pointers of specific storage classes for an experiment.

Consider the following example:

```
// Compile with: slangc.exe -target spirv storage_class.slang
[shader("compute")]
[numthreads(1, 1, 1)]
void main()
{
    uint *intPtr = spirv_asm {
        result: $$Ptr<uint> = OpVariable Uniform
    };

    intPtr[0] = 0;
}
```

The generated SPIR-V, using slang-2024.14.5-windows-x86_64 build, looks like this:

```
%uint = OpTypeInt 32 0
%_ptr_PhysicalStorageBuffer_uint = OpTypePointer PhysicalStorageBuffer %uint    ; ArrayStride 4
(...)
%intPtr = OpVariable %_ptr_PhysicalStorageBuffer_uint Uniform
```

The OpTypePointer storage class seems to be implicitly forced by Slang to PhysicalStorageBuffer. The resulting OpVariable is invalid, as per the [SPIR-V spec](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpVariable):

> Storage Class is the Storage Class of the memory holding the object. It must not be Generic. It must be the same as the Storage Class operand of the Result Type.

Is this expected? Is there another way for me to create my own types in `spirv_asm` and pass them back to Slang?

Thanks

**Comment by jkwak-work** [comment]
Closing as discussed on the meeting.
