### ISSUE TITLE
link-time constants in reflection API

### ISSUE THREAD

**Issue by PierreEVEN** [shader-slang/slang#5709]
Hi,

As discussed in https://github.com/shader-slang/slang/discussions/5664#discussioncomment-11387114, I think it would be nice to be able to get a list of available link-time constants 'parameters', for example to generate shader permutations.

I'm working on a toy game engine, and I was searching for a convenient way to automatically handle shaders permutations.
Looking at the slang syntax, I thought that using link-time constants would be a good idea as it doesn't requires to compile the modules again like the examples provided [in the user guide](https://shader-slang.com/slang/user-guide/link-time-specialization.html#link-time-constants). I would only need to inject a module that set the value for each constant parameter.

Short example :

Slang code : [PlayGround Link](https://shader-slang.com/slang-playground/?target=SPIRV&code=eJx9kUFrg0AQhe_7K4ZcohCSNj1KD4Hm1rTFGCiUImscdWHdtbtj21Dy3zurSXNKRdQZ3r75nCcWC8gahN6jgy-lNRQIstAIZKHvSkn81SgPnXSyRRpU3DDcRai5BWhqZfhVKrJO4DdrDHiSpPawt8YTFNZqeFmlq02-267zp-d0s3rMs_VrtkvXcA_kekyEYJQUP3rlsARr9AFUdfWU2Mq20-i2FAj9qUpExvN7h8sHMNa1Uuet7Nj6zTeyRBdNKifrFg1N4ndRaSvpDs6taKiXsPv0sfgRAHASjE7MOdbRzQz4vo2ToGHG6BpkDIMNX38WF6r5yByd2WfD4LmriwR4ExfhGIuxFKJx5wX9sxvguDxSSLCS2mNgOIrwZN-yb9sDVL3Zk7IhRUkhfA_TceI06BzyEg2n13Y9Ya5V3ZAydTRK-MePv57-uwA)

Cpp-side :
```cpp

// STEP ONE : use the reflection API to get a list of link-time constant parameters => we store this in a map named "static_switches"

// Example of how I would use the reflection API to populate the static_switches map. This doesn't exists in the current version of slang.
std::unordered_map<std::string, bool> static_switches;
for (const auto& param : module->getLayout()->getLinkTimeConstants())
    static_switches->emplace(param->get_name(), param->get_default_value());


// STEP TWO : each time we need a different combination of static_switches values, we inject the desired values as follows :

// This currently works as expected, no change are required here.
std::vector<slang::IComponentType*> components;
if (!static_switches.keys().empty())
{
    std::string generated_module;
    for (const auto& sw: static_switches)
        generated_module += std::format("export static const bool {} = {};", sw.first, sw.second ? "true" : "false");

    auto permutation_values_src = UnownedRawBlob::create(generated_module.c_str(), generated_module.size());
    components.emplace_back(session->loadModuleFromSource("permutation-values", "permutation-values.slang", permutation_values_src));
}
components.emplace_back(entry_point);
Slang::ComPtr<slang::IComponentType> program;
session->createCompositeComponentType(components.data(), components.size(), program.writeRef());

// then link + getEntryPointCode
```

Currently there is no way to get a list of link-time constants, so I have to manually parse the shader file to retrieve them, which is not a very clean approach. 
Also optionally, it would be nice if we can get the default value (which is probable harder to implement)

**Comment by bmillsNV** [comment]
Feature request. We'll evaluate this next quarter when figuring out our priorities. In the meantime, we welcome contributions if anyone wants to take this one up.

**Comment by jjiangweilan** [comment]
I found a way to get the name of link-time constants
```c++
    auto moduleReflection = module->getModuleReflection();
    for (auto child : moduleReflection->getChildren())
    {
        auto type = child->getKind();
        if (type == slang::DeclReflection::Kind::Variable)
        {
            auto asVariable = child->asVariable();
            bool hasExtern = asVariable->findModifier(slang::Modifier::Extern) != nullptr;
            bool hasStatic = asVariable->findModifier(slang::Modifier::Static) != nullptr;
            bool hasConst = asVariable->findModifier(slang::Modifier::Const) != nullptr;

            // bool hasDefault = asVariable->hasDefaultValue(); // you can know if it has default value, but I haven't find a way to know the exact value assigned

            if (hasExtern && hasStatic && hasConst)
            {
                std::string name = child->getName(); // name of the link-time constants
            }
        }
    }
```

**Comment by PierreEVEN** [comment]
> I found a way to get the name of link-time constants
> 
> ```c++
>     auto moduleReflection = module->getModuleReflection();
>     for (auto child : moduleReflection->getChildren())
>     {
>         auto type = child->getKind();
>         if (type == slang::DeclReflection::Kind::Variable)
>         {
>             auto asVariable = child->asVariable();
>             bool hasExtern = asVariable->findModifier(slang::Modifier::Extern) != nullptr;
>             bool hasStatic = asVariable->findModifier(slang::Modifier::Static) != nullptr;
>             bool hasConst = asVariable->findModifier(slang::Modifier::Const) != nullptr;
> 
>             // bool hasDefault = asVariable->hasDefaultValue(); // you can know if it has default value, but I haven't find a way to know the exact value assigned
> 
>             if (hasExtern && hasStatic && hasConst)
>             {
>                 std::string name = child->getName(); // name of the link-time constants
>             }
>         }
>     }
> ```

Works as expected 

Thanks !
