### ISSUE TITLE
-reflection-json doesnt work?

### ISSUE THREAD

**Issue by Zathyy** [shader-slang/slang#5713]
hello i'm trying to use the -reflection-json specified in the command-line-slangc-reference.md
but it just says: (1): error 17: unknown command-line option '-reflection-json'

or am i just using it wrong?

slangc -reflection-json Reflection.json -target spirv -stage vertex VertShader.slang

i have version 2024.13

**Comment by csyonghe** [comment]
This option is added recently and only available on top of tree builds. We have not yet produced a prebuilt release that includes this feature.
