### ISSUE TITLE
Typo in generated code.

### ISSUE THREAD

**Issue by godofecht** [shader-slang/slang#5714]
While exploring generated Metal code via the 'Simple Print' demo, I noticed a typo: "FormatedStruct" is used, but it should be "FormattedStruct" instead. 

To replicate this issue:

1. Generate Metal code using the 'Simple Print' demo.
2. Review the generated code, where you'll see "FormatedStruct" instead of "FormattedStruct."

It assume that this string might be dynamically constructed through string operations, potentially by appending the suffix `-ed` to descriptive words. However, I can't find anything like that.

**Comment by csyonghe** [comment]
The typo likely comes from the `playground` module defined in the playground. Fixes needs to be made to the `playgroundShader.js` file in the `slang-playground` repo.
