### ISSUE TITLE
Specialization constants need to be supported on all backends

### ISSUE THREAD

**Issue by smarton-sc** [shader-slang/slang#5725]
Specialization constants were implemented for the Vulkan backend here https://github.com/shader-slang/slang/pull/4963, but they need to work for all backends, as detailed here: https://github.com/shader-slang/slang/pull/4963#issuecomment-2505208654

It seems that [SpecializationConstant] is meant to be the Slang first class syntax, and I think it works fine as far as it goes:

```
[SpecializationConstant]
const int specConst = 1; // implicit layout
```

Each backend should get the appropriate syntax, similar to how SPIRV-Cross does it: OpSpecConstant for Vulkan (already implemented), function constants for Metal, #if for GL, etc.

There are some differences between platforms, and I'm not sure if Slang should support the lowest common denominator, or everything each backend could support. Ex: unlike Vulkan and Metal, glsl allows setting uniform array size by function constant (ie: #define --- but it makes reflection non-trivial). Metal allows much more specialization of struct members, function arguments and resource bindings, which might not be representable in Vulkan. Discussion on this is welcome. For our use case, the lowest common denominator will suffice. But for the health of the Slang language it might be worth thinking about this a bit deeper.

**Comment by csyonghe** [comment]
My preference is not to allow specialization constants to be used in ways that can affect parameter layout for simplicity. This is also a safe starting point.

**Comment by csyonghe** [comment]
PR#5780 adds support for specialization constants for metal and wgsl.

For targets without native specialization constant feature, the support is still unimplemented and is left for future work.

I am going to close this issue with #5780 and please feel free to open another issue for generating #ifdef code on HLSL/C++ output, if it is needed.

**Comment by smarton-sc** [comment]
@csyonghe thanks for the amazingly fast turnaround!
