### ISSUE TITLE
GLSL compiler on Vulkan doesn't accept empty structs

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#574]
To repeat run render-test with the following options 

```
tests/bugs/gh-357.slang -vk -slang -compute -o tests/bugs/gh-357.slang.2.actual.txt
```

This generates the following error from glslang compiler

```
ERROR: slang:4: '' :  syntax error, unexpected RIGHT_BRACE
ERROR: 1 compilation errors.  No code generated.
```

The code that slang has generated is 

```
#version 450
struct BaseImpl_0
{
};

float BaseImpl_getVal_0(BaseImpl_0 this_0)
{
    return (1.00000000000000000000);
}

layout(std430) buffer _S1 {
    float outputBuffer_0[];
};
layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;void main()
{
    uint tid_0 = (gl_GlobalInvocationID).x;
    /* unhandled */;
    BaseImpl_0 base_0;
    float rs_0 = BaseImpl_getVal_0(base_0);
    ((outputBuffer_0)[tid_0]) = rs_0;
    return;
}
```

Which looks as if the problem is the glslang compiler as used on Vulkan does not accept structs which have no members. 

Tim suggests  "The right fix is for Slang's "type legalization" pass to completely eliminate empty `struct` types by legalizing them to an empty tuple. It is a bit unfortunate to remove empty `struct` types for HLSL output as well, but it is more consistent to do it everywhere."

**Comment by tfoleyNV** [comment]
The type legalization code already handles a closely related case: when a `struct` type contains only resource fields, then the “ordinary” (non-resource) part of the type gets eliminated (I think in practice it may get replaced with the `void` type, for complex reasons).

A fix for this issue *should* be as simple as treating a type with *no* fields just like a type that has only resource fields.

**Comment by tfoleyNV** [comment]
Reopening because #577 resolved the issues we were seeing with HLSL for DXR when empty `struct`s are nested in fields of other `struct`s, but still leaves behind some top-level declarations of empty `struct`s which trip up the Vulkan GLSL compiler.

**Comment by csyonghe** [comment]
The type legalization pass can already cleanup empty types.
