### ISSUE TITLE
Crash with recursive pointers

### ISSUE THREAD

**Issue by spencer-lunarg** [shader-slang/slang#5745]
In GLSL you are able to go (https://godbolt.org/z/WEcnnYY5q)

```glsl
layout(buffer_reference) buffer Node;
layout(buffer_reference, std430) buffer Node {
    Node next;
    int payload;
};
``` 

The following with `slang-2024.14.6` crashes and/or produces no actual SPIR-V

**NOTE** I am not asking for support of this, but at least an error message to gracefully not blow up

```
struct Outer {
    Outer next; // non-pointer
    int y;
};
RWStructuredBuffer<Outer> Buf;

void csmain() {
     Buf[0].y = 0;
}
```

and

```
struct Outer {
    Outer* next; // pointer
    int y;
};
RWStructuredBuffer<Outer> Buf;

void csmain() {
     Buf[0].y = 0;
}
```

**Comment by csyonghe** [comment]
Recursive pointers are supposed to work in Slang. Your first non pointer snippet won’t work and slang should generate an error, but the second snippet should work, and it is a bug if the compiler crashes in any situation.

**Comment by csyonghe** [comment]
The second shader compiles fine on top of tree. I confirmed and fixed the crash on your first shader.
