### ISSUE TITLE
Simplify structured control-flow join points

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#575]
Sometimes a user will write a two-sided `if` statement that is really one-sided in practice:

```hlsl
if(A)
{
    B;
}
else
{
    C;
    return;
}
D;
```

This code can be transformed into:

```hlsl
if(!A)
{
    C;
    return;
}
B;
D;
```

The transformed code resolves certain scoping problems that can arise for communication between C and D (because in the earlier code C dominated D, but C's scope was not visible to D).

There is an equivalent transformation we can make for a loop with only one `break` path, so that code like the following:

```hlsl
for(;;)
{
    if(A)
    {
        B;
        break;
    }
    C;
}
D
```

can become:

```hlsl
for(;;)
{
    if(A) break;
    C;
}
B;
D;
```

In this case we simplify the scope for values defined in B and used in D, although we possibly create problems for other variables that were defined in the loop and used by B.

(In each of these cases we could go in the other direction and pull the D block into the control-flow structure, but that has semantic consequences for languages like GLSL that specify "uniform control flow" in terms of nesting of structured control-flow statements)

It seems like implementing this transformation in the context of Slang's structured IR control-flow ops should be relatively easy. If we have a structured control-flow instruction (either a `loop`, `ifElse`, or `switch`) where the "joint point" block has only a single predecessor, then we should be able to modify the "join point" of the control-flow op to be that predecessor instead. In the examples above block D is the old join point, and B is its sole predecessor, which becomes the new join point.

**Comment by csyonghe** [comment]
We have a cfg simplification pass now.
