### ISSUE TITLE
Slang version > 2024.13 gives regression

### ISSUE THREAD

**Issue by Zathyy** [shader-slang/slang#5779]
when im trying to get the number of entry points in versions > 2024.13 it's not working

https://github.com/Zathyy/Regression

instructions are listed in the readme

**Comment by kaizhangNV** [comment]
From my end, it just prints 2 entrypoints as expected.

![image](https://github.com/user-attachments/assets/2d487c91-0210-46c8-9edb-acb84d4eb6e4)

**Comment by kaizhangNV** [comment]
Also tried v2024.15, still cannot reproduce.

**Comment by Zathyy** [comment]
it was an issue on my end, i wasnt linking the dll's properly, i am so sorry for this.
i am gonna close this now
