### ISSUE TITLE
glsl bindless descriptors do not compile 

### ISSUE THREAD

**Issue by dmitsuki** [shader-slang/slang#5788]
When using glsl compatibility mode, bindless descriptor set usage does not compile. For example

```
struct RenderObject
{
    mat4 Model; 
    mat4 Position; 
    mat4 Rotation; 
    mat4 Scale; 
    uint MaterialIndex;
};


layout(set = 0, binding = 0, std430) buffer RenderObjects 
{
    RenderObject Objects[]; 
} renderObjects[]; 

struct Material
{
    uint Diffuse;
}; 

layout(set = 0, binding = 0, std430) buffer Materials
{
    Material Mats[];
} materials[];

```
will return the error 

`TexturedMesh.vert(55): error 39999: declaration does not declare anything
} renderObjects[];
  ^~~~~~~~~~~~~
TexturedMesh.vert(65): error 39999: declaration does not declare anything
} materials[];
`

**Comment by bmillsNV** [comment]
Thank you for filing this issue. This is worth resolving, but we don’t have current available bandwidth – moving to the backlog for now. Please do feel welcome to propose a solution if you’re able to before it makes it out of the backlog!
