### ISSUE TITLE
Slang crash when compiling a simple shader.

### ISSUE THREAD

**Issue by Lumengine** [shader-slang/slang#5799]
Hi,
I am transitioning towards the new "module" "implementing" of my slang codebase and I have a weird crash. I did the smallest repro I could. With the pdb, it seems that the m_searchDirectories ptr of the includeSystem is broken. I hope I didn't do anything stupid in my shader. In that case, just tell me. You can try to compile the hellotriangleFS.slang. I tried both with my compile code and slangc.exe.
Thanks,

Baptiste
[Example.zip](https://github.com/user-attachments/files/18049268/Example.zip)

**Comment by cheneym2** [comment]
I reproduced the issue locally
