### ISSUE TITLE
Support matrix swizzles

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#580]
Is the zero-based M._mij and one-based M._ij element access not supported (for vector/matrix types M)?

I get errors for these, but opreator [] access works.

This was on Slang 0.10.14 I think.

**Comment by tfoleyNV** [comment]
Yes. Those were intentionally left out because they are seldom used. We can add them if there is demand, and if it ever rises toward the top of the priority list.

**Comment by tfoleyNV** [comment]
I believe that the syntax you are referring to ("matrix swizzles") is only applicable to matrix types, not vectors, but I'd be interested if I'm wrong.

Obviously Slang already supports ordinary vector swizzle syntax.
