### ISSUE TITLE
Support constructing a `RaytracingAccelerationStructure` handle by device pointer

### ISSUE THREAD

**Issue by natevm** [shader-slang/slang#5801]
SPIR-V has the instruction `OpConvertUToAccelerationStructureKHR`, which allows users to construct a `RayTracingAccelerationStructure` handle from a Vulkan device address. 

At the moment, I have a little helper function to let me tap into this feature:
```
RaytracingAccelerationStructure getAccelHandle(uint64_t address) {
  return spirv_asm {
    result: $$RaytracingAccelerationStructure = OpConvertUToAccelerationStructureKHR $address
  };
}
```

But it would be better if this was officially supported, either through a constructor, `RaytracingAccelerationStructure(uint64_t address)`, or perhaps even better, by `RaytracingAccelerationStructure *accelPtr;`

Is this something we support already? If not, could we add it?

**Comment by fknfilewalker** [comment]
Connected issue can be found here #5693. The problem is that HLSL does not support pointers to RaytracingAccelerationStructure s.

Interesting that you spirv_asm works, I wrote the same but mine did not work

**Comment by natevm** [comment]
Perhaps this is something that could be addressed with slangs compatibility system?

**Comment by csyonghe** [comment]
This can be achieved by adding a `__init` declaration to `RaytracingAccelerationStruture` type in `hlsl.meta.slang`, with `[require(glsl_spirv, raytracing)]` attribute and `[__readNone]` attribute:
```
struct RaytracingAccelerationStructure {

[require(glsl_spirv, raytracing)]
[__readNone]
__init(uint64_t address)
{
  __target_switch
  {
  case spirv:
    return spirv_asm {
      OpExtension "SPV_KHR_ray_tracing";
      OpCapability RayTracingKHR;
      result: $$RaytracingAccelerationStructure = OpConvertUToAccelerationStructureKHR $address;
    };
  case glsl:
     __requireGLSLExtension("GL_EXT_ray_tracing");
     __intrinsic_asm "accelerationStructureEXT($0)";
  }
}

[require(glsl_spirv, raytracing)]
uint64_t getDeviceAddress() {... similar definitions }
}
```
