### ISSUE TITLE
Access to COM Attribute GUID via Reflection API

### ISSUE THREAD

**Issue by HamiltonHuaji** [shader-slang/slang#5811]
For a `TypeReflection` object, there are only methods like `getUserAttributeByIndex` to access user defined attributes. However, for purposes such as generating COM binding from slang source, it is necessary to extract the GUID from the COM interface declaration.

**Comment by csyonghe** [comment]
We can add a general `SlangResult TypeReflection::getBuiltinAttributeArgString(SlangBuiltinAttribute attrName, int argIndex, const char** outStr)` function to query for any builtin attributes.

**Comment by HamiltonHuaji** [comment]
Thank you, this looks good to me.

For the same COM binding generating purpose, it would be more convenient to have an API for enumerating functions declared in type. Currently, there exists only a method `findFunctionByNameInType`. But in cases where the function name is unknown, obtaining the corresponding `FunctionReflection` object is difficult. Please consider adding methods like `TypeReflection::getFunctionByIndex` and `TypeReflection::getFunctionCount`.

**Comment by csyonghe** [comment]
For enumeration, you can use experimental APIs:
```
spReflectionDecl_getChild
spReflectionDecl_getChildrenCount
spReflectionDecl_getName
spReflectionDecl_getKind
spReflectionDecl_castToFunction
```

You can pass a `SlangReflectionType*` directly to a `SlangReflectionDecl*` parameter (downcast), and use `spReflectionDecl_castToFunction` to cast from `SlangReflectionDecl*` to `SlangReflectionFunction*` (upcast).

**Comment by csyonghe** [comment]
Fixed. See the test case code for usage:

```
    const char* userSourceBody = R"(
        public enum E
        {
            V0,
            V1,
        };

        [__AttributeUsage(_AttributeTargets.Struct)]
        public struct NormalTextureAttribute
        {
            public E Type;
        };

        [COM("042BE50B-CB01-4DBB-8367-3A9CDCBE2F49")]
        interface IInterface { void f(); }

        [NormalTexture(E.V1)]
        struct TS {};
        )";
    String userSource = userSourceBody;
    ComPtr<slang::IGlobalSession> globalSession;
    SLANG_CHECK(slang_createGlobalSession(SLANG_API_VERSION, globalSession.writeRef()) == SLANG_OK);
    slang::TargetDesc targetDesc = {};
    targetDesc.format = SLANG_HLSL;
    targetDesc.profile = globalSession->findProfile("sm_5_0");
    slang::SessionDesc sessionDesc = {};
    sessionDesc.targetCount = 1;
    sessionDesc.targets = &targetDesc;
    ComPtr<slang::ISession> session;
    SLANG_CHECK(globalSession->createSession(sessionDesc, session.writeRef()) == SLANG_OK);

    ComPtr<slang::IBlob> diagnosticBlob;
    auto module = session->loadModuleFromSourceString(
        "m",
        "m.slang",
        userSourceBody,
        diagnosticBlob.writeRef());
    SLANG_CHECK(module != nullptr);

    auto reflection = module->getLayout();

    auto interfaceType = reflection->findTypeByName("IInterface");
    SLANG_CHECK(interfaceType != nullptr);

    auto comAttribute = interfaceType->findAttributeByName("COM");
    SLANG_CHECK(comAttribute != nullptr);

    size_t size = 0;
    auto guid = comAttribute->getArgumentValueString(0, &size);
    UnownedStringSlice stringSlice = UnownedStringSlice(guid, size);
    SLANG_CHECK(stringSlice == "\"042BE50B-CB01-4DBB-8367-3A9CDCBE2F49\"");

    auto testType = reflection->findTypeByName("TS");
    SLANG_CHECK(testType != nullptr);

    auto normalTextureAttribute = testType->findAttributeByName("NormalTexture");
    SLANG_CHECK(normalTextureAttribute != nullptr);

    int value = 0;
    normalTextureAttribute->getArgumentValueInt(0, &value);
    SLANG_CHECK(value == 1);
```

**Comment by HamiltonHuaji** [comment]
> For enumeration, you can use experimental APIs:
> 
> ```
> spReflectionDecl_getChild
> spReflectionDecl_getChildrenCount
> spReflectionDecl_getName
> spReflectionDecl_getKind
> spReflectionDecl_castToFunction
> ```
> 
> You can pass a `SlangReflectionType*` directly to a `SlangReflectionDecl*` parameter (downcast), and use `spReflectionDecl_castToFunction` to cast from `SlangReflectionDecl*` to `SlangReflectionFunction*` (upcast).

I did try it, and it doesn't work. My test code:
```cpp
// ... append after your test code, remove unnecessary user attribute parts, test with release v2024.15.2

// slang::TypeReflection is exactly SlangReflectionType.
SlangReflectionDecl * casted = (SlangReflectionDecl *)interfaceType;
printf("Type: %s [%d children]\n", interfaceType->getName(), spReflectionDecl_getChildrenCount(casted));
```
got output `Type: IInterface [0 children]`, which is supposed to have 1 child(`void f()`). Also, `casted->getName()` gives nullptr.

It seems that `SlangReflectionDecl` can be directly cast to `ContainerDecl` (if it passed runtime type checks), which has a field `members` containing its children. And a `SlangReflectionType` only holds a reference to underlying declaration and has no inheritance relationship with `SlangReflectionDecl`. They just share a common base class `NodeBase`.
