### ISSUE TITLE
Adding Interface member to struct crashes compiler

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#5835]
The following code makes slang crash inside slang-glslang.dll.  Target is spirv-direct.
Removing the line `IBsdf *bsdf;` makes it compile. Using `IBsdf bsdf;` also crashes slang.

```csharp
interface IBsdf {};

struct Mesh {
    float4 *vertices;
    IBsdf *bsdf;
}
[[vk::push_constant]] Mesh* mesh;
RWStructuredBuffer<float4> outputBuffer;

[shader("compute")]
[numthreads(1, 1, 1)]
void main(uint3 dispatchThreadID: SV_DispatchThreadID)
{
    outputBuffer[0] = mesh.vertices[0];
}
```

Edit: 
GLSL target crashes with `message = 0x0000029528ea4ce0 "(0): internal error 99999: unexpected condition encountered in Slang compiler: unhandled type"`
HLSL target seems to work

**Comment by csyonghe** [comment]
Slang is producing invalid SPIRV.

Note that pointers are not supported for GLSL and HLSL backend.
