### ISSUE TITLE
render-test should support slang reflection for binding 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#584]
render-test currently uses bindings specified as indices within the tests themselves. For example 

```
//TEST_INPUT:Texture2D(size=4, content = one) : dxbinding(0),glbinding(0)
//TEST_INPUT: Sampler : dxbinding(0),glbinding(0,1,2,3,4,5,6)
//TEST_INPUT: ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out
```

With dxbinding and glbinding specifying how the inputs map to a binding on a particular render target. The render test has been expanded to support dx12 and vulkan. The vulkan binding allows multiple textures to bound under a single register - which differs from other targets. Dx12s binding is not quite the same as Dx11 either. 

When writing tests the burden of getting the binding indices correct has grown considerably with 4 render APIs. It requires knowing how the mapping to other apis actually works. If we support yet more apis then this problem will only get worse.

Therefore it is suggested that we use slangs reflection to drive the binding of test resources, thus removing the need to specify bindings in tests.

One way to do this would be through using the name of the thing being bound. For example in gh-518.slang we have 

```
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out
RWStructuredBuffer<int> gBuffer;

//TEST_INPUT: Texture2D(size=4, content=one):dxbinding(0),glbinding(0)
//TEST_INPUT: Texture2D(size=4, content=one):dxbinding(1),glbinding(1)
Texture2D gTextures[2];
```

We could perhaps do something like

```
//TEST_BIND: gBuffer = ubuffer(data=[0 0 0 0], stride=4)
RWStructuredBuffer<int> gBuffer;
//TEST_BIND: gTextures = {  Texture2D(size=4, content=one), Texture2D(size=4, content=one) }
Texture2D gTextures[2];
```

Additionally we might want to just define resources such they can be accessed by name

```
//TEST_RESOURCE: oneTex = Texture2D(size=4, content=one)
//TEST_BIND: gBuffer = ubuffer(data=[0 0 0 0], stride=4)
RWStructuredBuffer<int> gBuffer;
//TEST_BIND: gTextures = { oneTex, oneTex }
Texture2D gTextures[2];
```

**Comment by csyonghe** [comment]
We are already using reflection based binding for render-test.
