### ISSUE TITLE
Slang generates not spec compliant sequence of NonSemantic.DebugInfo instructions

### ISSUE THREAD

**Issue by kleints** [shader-slang/slang#5859]
For very long shaders, when the source strings are split up in DebugSource and DebugSourceContinued, Slang produces a sequence of instructions that is not following the spec for DebugSourceContinued. That says: "The previous instruction must be a DebugSource or DebugSourceContinued instruction.". However, for the first DebugSource/DebugSourceContinued the DebugCompilationUnit instruction is interleaved.

For example:
          %4 = OpExtInst %void %2 DebugSource %5 %1
         %10 = OpExtInst %void %2 DebugCompilationUnit %uint_100 %uint_5 %4 %uint_11
         %51 = OpExtInst %void %2 DebugSourceContinued %50
         %53 = OpExtInst %void %2 DebugSourceContinued %52
         %67 = OpExtInst %void %2 DebugSourceContinued %66

**Comment by csyonghe** [comment]
I tried this with a simple shader and unable to reproduce the interleaving. The interleaving could have been introduced by spirv-opt instead of slang. Have you tried `-O0` to disable spirv-opt?

**Comment by csyonghe** [comment]
We will need a reproducer to proceed with this issue.

**Comment by cheneym2** [comment]
I filed a Khronos issue with a minimal repro: https://github.com/KhronosGroup/SPIRV-Tools/issues/5950

**Comment by csyonghe** [comment]
We should try a top of tree build of spirv-opt and see if that addresses the issue.

**Comment by cheneym2** [comment]
Oh, my mistake. While the SDK is from 1/13/2025, the Spirv-tools binaries are from 12/5/2024, so there is a bigger gap, and in fact the change that fixed this issue was identified as one that was submitted on 12/13/2024.

**Comment by cheneym2** [comment]
Update slang to use newer spirv-tools: https://github.com/shader-slang/slang/pull/6145
