### ISSUE TITLE
Compile failure without any output

### ISSUE THREAD

**Issue by koubaa** [shader-slang/slang#5861]
When I attempt to compile the following `foo.slang` file, it fails and I don't get any output (warning or error). I am running on windows11 and I tried with both the 2024.13 that came with my vulkan SDK and the latest release of 2024.17.

My command line is:
`/path/to/slangc foo.slang -stage compute -target spirv -o foo.slang.spv`

```
#extension GL_EXT_debug_printf : enable

// row major, 12*N size
[[vk::binding(0)]] RWStructuredBuffer<float> strain;
[[vk::binding(1)]] RWStructuredBuffer<float> stress;

struct MyData
{
    int a;
    float[9] c; // row major C matrix
}

[[vk::constant_id(0)]] const MyData pcs;

matrix<float, 3, 3> getCMatrix(float[9] cvec) {
    matrix<float, 3, 3> result = {
        cvec[0], cvec[1], cvec[2],
        cvec[3], cvec[4], cvec[5],
        cvec[6], cvec[7], cvec[8]
    };
    //vector<float, 3> foo = { 0., 0, 0.0 };
    //vector<float, 3> bar = mul(result, foo);
    return result;
}

[shader("compute")]
[numthreads(32, 1, 1)]
void main(uint3 threadId : SV_DispatchThreadID)
{
    int index = threadId.x;
    int max_element_number = pcs.a;

    if (index >= max_element_number)
        return;

}
```

simply removing the two lines at the bottom:
```
if (index >= max_element_number)
        return;
```

leads to a successful compile.

**Comment by fairywreath** [comment]
Actually specialization constants should only support scalar types and not structs, so an error should be printed out regarding invalid spec constant usage.

**Comment by koubaa** [comment]
@fairywreath these are push constants, not specialization constants. Since both are supported in both HLSL and GLSL, is this on the roadmap?

**Comment by koubaa** [comment]
GLSL and HLSL both support structs for specialization constants (although I've seen the layouts get thrown off in spv).  Is this going to be on the roadmap or is there a reason never to support it?

**Comment by fairywreath** [comment]
`vk::constant_id(x)` is used for `layout(constant_id=x)`, i.e. specialization constants.
For push constants use `vk::push_constant`, with no value assigned.

**Comment by koubaa** [comment]
Something seems broken with push constants too, actually.

I have a float array with 10 members that I pass to an equivalent glsl and slangc shader as a push constant using vulkan.

In glsl I do: 

```
layout (push_constant) uniform PushConstants {
	float numElements;
	float[9] c; //row major C matrix
} pcs;
```

In slangc I've tried both

A:
`[[vk::push_constant]] const float[10] pcs;`

and 

B:
```
struct MyData
{
    float a;
    float[9] c; // row major C matrix
}

[[vk::push_constant]] const MyData pcs;

```

With the glsl shader, I can read the floats and they have the same values as those I passed into vulkan.  

glsl:
```
printf("Const: %f %f %f,%f %f %f,%f %f %f\n",
    pcs.c[0], pcs.c[1], pcs.c[2], pcs.c[3], pcs.c[4], pcs.c[5], pcs.c[6], pcs.c[7], pcs.c[8]
);
```
Output:
`Const: 878.378357 810.810791 0.000000,810.810791 878.378357 0.000000,0.000000 0.000000 33.783783`

With the slangc shader (option B from above),
```
float[] pcsc = {
    pcs[1], pcs[2], pcs[3], pcs[4], pcs[5], pcs[6], pcs[7], pcs[8], pcs[9]
};
printf("Const: %f %f %f,%f %f %f,%f %f %f\n",
    pcsc[0], pcsc[1], pcsc[2], pcsc[3], pcsc[4], pcsc[5], pcsc[6], pcsc[7], pcsc[8]
);
```
Output: 
`Const: 810.810791 0.000000 0.000000,0.000000 0.000000 0.000000,0.000000 0.000000 0.000000`

**Comment by fairywreath** [comment]
> GLSL and HLSL both support structs for specialization constants (although I've seen the layouts get thrown off in spv). Is this going to be on the roadmap or is there a reason never to support it?

I do not recall GLSL and HLSL supporting this, I just tested with both glslc and dxc and  I got errors stating that individual spec constant variables should only be scalars. How did you manage to make this work?

**Comment by koubaa** [comment]
I take it back... I actually didn't try HLSL yet. Here was my glsl command line:
`glslangvalidator.exe -e main --target-env vulkan1.2 -V foo.comp -o foo.comp.spv`

and version:
```
$ glslangvalidator.exe --version
Glslang Version: 11:15.0.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 15.0.0
GLSL Version: 4.60 glslang Khronos. 15.0.0
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 11
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```

**Comment by fairywreath** [comment]
I get `ERROR: foo.comp:18: 'constant_id' : can only be applied to 'const'-qualified scalar`. The [ GLSL specs](https://github.com/KhronosGroup/GLSL/blob/main/extensions/khr/GL_KHR_vulkan_glsl.txt) also only allows scalars or vectors made of spec const scalars.

Regarding struct support, SPIRV does have `OpSpecConstantComposite` where its members all have to be spec constants themselves, but `OpDecorate` with `SpecId` only works for scalar values and not composites. This means we cannot have a composite spec const with a dedicated constant id.

**Comment by fairywreath** [comment]
You can try using the latest slangc release for your push constant data problem. I see that release 2024.13 uses std140 by default while the current TOT uses std430. The correct one should be std430

**Comment by koubaa** [comment]
> You can try using the latest slangc release for your push constant data problem. I see that release 2024.13 uses std140 layout by default for push constants while the current TOT uses std430. The correct one should be std430

I'll wait till the next release is out on github. I jus tried with 2024.17 and it still doesn't look right.

> The [GLSL specs](https://github.com/KhronosGroup/GLSL/blob/main/extensions/khr/GL_KHR_vulkan_glsl.txt) also only allows scalars or vectors made of spec const scalars.

I'm referring to push constants, the spec says the following:

```
Push Constants
    --------------

    Push constants reside in a uniform block declared using the new
    layout-qualifier-id "push_constant" applied to a uniform-block declaration.
    The API writes a set of constants to a push-constant buffer, and the shader
    reads them from a push_constant block:

        layout(push_constant) uniform BlockName {
            int member1;
            float member2;
            ...
        } InstanceName; // optional instance name

        ... = InstanceName.member2; // read a push constant

    The memory accounting used for the push_constant uniform block is different
    than for other uniform blocks:  There is a separate small pool of memory
    it must fit within.  By default, a push_constant buffer follows the std430
    packing rules.
```

So in the glsl syntax, the push constants are defined in the same way a struct is. I don't see any equivalent syntax in slang without defining the type as a struct.

**Comment by csyonghe** [comment]
I checked the compile result of:
```
struct MyData
{
    float a;
    float[9] c; // row major C matrix
}

[[vk::push_constant]] const MyData pcs;

[numthreads(1,1,1)]
void main()
{
    printf("%f", pcs.c[1]);
}
```
on playground, and nothing comes out suspicious:  https://shader-slang.com/slang-playground/?target=SPIRV&code=eJxFjsEKgzAQRO_7FYtQSEAqHmuO7dUvCKEssWLamkiy2pbivzeC0NnDzsK-YRLH2TK2nwsxwRcwq38GYiT1P_TJoFVYVRjDC0e6h4jnvDm6N6wAWi-PppnmNFxt8InJs8nEZvdonGxS-dHPIw_xRl0SdZlHGliC63KW80LuBaboPPeiOPRFuYFHq2sjFaw_4uU2Uw

The generated SPIRV looks correct to me.

**Comment by csyonghe** [comment]
Oh, the problem might be `printf` is emitted incorrectly. If you write the output to a buffer it should work just fine,

I need to fix how `printf` is emitted.

**Comment by csyonghe** [comment]
(or for now, print just one element at a time before the printf issue is fixed.)
