### ISSUE TITLE
MSL Backend does not respect the location used in [[vk::location(x)]]

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang#5883]
Filed on behalf of a client developer:

The following slang code:
```
slang
struct VSInput
{
    [[vk::location(0)]] float3 inPositions;
#ifdef HAS_NORMAL
    [[vk::location(1)]] float3 inNormals;
#endif
#ifdef HAS_TANGENT
    [[vk::location(2)]] float4 inTangents;
#endif
#ifdef HAS_TEXCOORD0
    [[vk::location(3)]] float2 inTexCoords0;
#endif
};
```
Would translate with HAS_NORMAL and HAS_TEXCOORD0 defined to:
```
msl
struct VSInput_0
{
    float3 inPositions_0;
    float3 inNormals_0;
    float2 inTexCoords0_0;
};
```
We wanted to use fixed attribute locations and expected to have for the `inTexCoords0` attribute the [[attribute(3)]] where the msl code would need to bind this attribute at [[attribute(2)]], leading to a crash in the metal validation layers or an invalid output.
We need to rely on the reflection to have the location where we should be confident on the attribute to use
You already have this interop feature for `[[vk::constant_id]]` maybe the translation from `[[vk::location(x)]]` to `[[attribute(x)]]` could be added as well?

**Comment by csyonghe** [comment]
Is there a reason why you need to wrap the input attributes in a `#ifdef`?

If you remove all the `#ifdef`s, you will always get the consistent layout. I don't think this will lead to any actual runtime performance issues.

**Comment by bmillsNV** [comment]
@csyonghe looks like this needs to be documented clearly.
