### ISSUE TITLE
Incorrect size computed for non-square matrices

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#591]
A row-major `float4x3` should be laid out as 4 `float3`s, with each `float3` starting at a 16-byte aligned offset. That means the overall layout is something like:

```
X Y Z _ X Y Z _ X Y Z _ X Y Z
```

The `_` entries there indicate padding between the different vectors. It is worth noting that there is *not* supposed to be padding at the end, so the total size of this type should be 60 bytes. The type will have an alignment of 16 bytes, so when you make an array of them the *stride* should be 64 bytes.

Slang currently seems to incorrectly report the *size* of this type as 64 bytes, which isn't quite right. I suspect the same thing would happen for an array of any type that isn't a multiple of 16 bytes in size.

**Comment by csyonghe** [comment]
Fixed.
