### ISSUE TITLE
Derivatives fail to propagate through __subscript in interfaces

### ISSUE THREAD

**Issue by tunabrain** [shader-slang/slang#5921]
The following code fails to compile with `error 41020: derivative cannot be propagated through call to non-backward-differentiable function ``, use 'no_diff' to clarify intention.` on the line `return arg[0];`.

However, using `float test(Test arg)` or even `float test<T : ITest>(T arg)` compiles correctly.

```
interface ITest
{
    __subscript(int i) -> float
    {
        [BackwardDifferentiable] get;
    }
}
struct Test : ITest
{
    __subscript(int i) -> float
    {
        [BackwardDifferentiable] get { return 5.0f * i; }
    }
}

[Differentiable]
float test(ITest arg)
{
    return arg[0];
}
```

**Comment by bmillsNV** [comment]
@kaizhangNV can you help to look into this one?
