### ISSUE TITLE
Support synthesized properties in specialization's `=` sugar syntax

### ISSUE THREAD

**Issue by cezneluk** [shader-slang/slang#5942]
According to the User's guide, the `=` sugar syntax in the type definition creates a wrapper on the underlying inner type (https://shader-slang.com/slang/user-guide/link-time-specialization.html). However, properties defined in the interface and implemented by a field are not properly wrapped.

I know that automatically synthesized `getter` and `setter` methods are not supported (based on the User's guide https://shader-slang.com/slang/user-guide/convenience-features.html#properties), but a code like this works pretty well:
```
public interface ITest {
    public property int val;
};

public struct TestImpl : ITest {
    public int val;
}
```

### Current result:

The problem occurs if I want to use this structure as part of shader specialization:
```
public interface ITest {
    public property int val;
};

public struct TestImpl : ITest {
    public int val;
}

public struct Test : ITest = TestImpl;

StructuredBuffer<Test> data;

[shader("compute")]
[numthreads(1,1,1)]
void computeMain()
{
    int val = data[0].val;
}
```

This source code is compiled with an error:
```
(0): error 30027: '$syn_property_val' is not a member of 'TestImpl'.
```

Tested on binaries from the latest release (v2024.17) and the build from the current master (7cecc51).

### Expected result:

The shader will be successfully compiled and the code above will load the `val` field into the local variable.

**Comment by csyonghe** [comment]
The synthesis logic for properties and subscript operators in link-time wrapper types are missing.
This is a known implementation gap that we should fix.
