### ISSUE TITLE
terminateRayEXT & ignoreIntersectionEXT not recognized in GLSL compatibility mode

### ISSUE THREAD

**Issue by juliusikkala** [shader-slang/slang#5946]
When attempting to compile the following any-hit shader in GLSL compatibility mode (e.g. `slangc -allow-glsl -target spirv -entry main -O2 test.rahit -o test.spv`), the terminateRayEXT and ignoreIntersectionEXT keywords are not recognized by slangc.

```glsl
// test.rahit
#version 460
#extension GL_EXT_ray_tracing : require

void main()
{
    terminateRayEXT;
    ignoreIntersectionEXT;
}
```

Output:
```
test.rahit(7): error 30015: undefined identifier 'terminateRayEXT'.
    terminateRayEXT;
    ^~~~~~~~~~~~~~~
test.rahit(8): error 30015: undefined identifier 'ignoreIntersectionEXT'.
    ignoreIntersectionEXT;
    ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by juliusikkala** [comment]
These two are conspicuously missing from glsl.meta.slang, probably because they're statement keywords and not functions.

Based on a quick look at the internals, the options are:

1. Add `#define terminateRayEXT AcceptHitAndEndSearch()` to `glsl.meta.slang`
2. Expand `parseSyntaxDecl` to allow a new keyword map to a function call, then add `syntax terminateRayEXT = AcceptHitAndEndSearch;` to `glsl.meta.slang`
3. Add new AST nodes and parse in `Parser::ParseStatement` similar to `discard`

Considering terminateRayEXT and ignoreIntersectionEXT map directly to function calls (AcceptHitAndEndSearch() & IgnoreHit()) and this is just a compatibility feature, the third option seems a bit overkill. Option 1 is trivial to implement but would leak terminateRayEXT to all shader stages. To me, option 2 seems fairly clean and could be useful for other stuff as well.

I'm pretty confident I can fix this myself and submit a PR with any of the three options, but I'm not sure which one's the best from your POV.

**Comment by csyonghe** [comment]
I believe you should be able to (ab)use global property for this:
```
property int terminateRayEXT { [ForceInline] get { AcceptHitAndEndSearch(); return 0; } }

void test()
{
     terminateRayEXT;
}
```
