### ISSUE TITLE
Support low-overhead runtime "shader cache" lookups

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#595]
This is mostly a design note for when we finally get around to implementing the serialized module format (see also #214 for other work on that front).

The whole premise behind using generics for shader specialization is that you can write something like:

```hlsl
interface IMaterial { ... }
struct A : IMaterial { ... }
struct B<T : ITexture> : IMaterial { ... }

void myShader<M : IMaterial>(...) { ... }
```

and then at runtime, based on the content you've loaded into a scene, you might invoke `myShader<A>`, `myShader<B<X>>`, etc.

This means that any application that is trying to efficiently render using Slang's generics will need to implement a cache that is keyed on a combination of an entry point (`myShader`) and type parameters (`A`, `B<X>`, etc.). This could be a cache they build at runtime, or one they pre-populate and load from disk.

Ideally, the Slang implementation should provide support for a simple implementation of such a shader cache that can work with the same container format used for Slang's serialized modules. Ideal design points for such a default implementation include:

* Ships as a single-file library as part of the Slang distribution (e.g., a `slang-shader-cache.h` file that sits alognside `slang.h`)

* For the pre-populated cache case, supports pulling its data directly from a memory-mapped view of a shader cache file on disk without any additional heap allocation

* For the case where dynamic compilation is allowed, supports invoking Slang compilation on-demand behind the same API

* When doing dynamic compilation, supports the hooks needed to make hot reload work (perhaps with the application providing the file watching/invalidation step)

A straw-man API design follows:

First, there would be a non-opaque `struct` type that holds the required state for the shader cache, so that the application can allocate/place it wherever they want:

```c++
struct SlangShaderCache { ... };
```

Next, there would need to be a way to initialize the shader cache with a pointer to the on-disk data for a shader cache file (which would use the same container format a `*.slang-module` file):

```c++
SlangResult SlangShaderCache_initialize(SlangShaderCache*, void const* data, size_t dataSize, SlangLinkage* linkage);
```

That routine would parse the header structure of the Slang bytecode container, and find the sections/tables it needs for the subsequent lookup steps. The `linkage` parameter would be optional: if it is provided then that linkage can be used to do dynamic loads/compiles when cache lookup fails.

The first thing a client would want to do is to be able to look up modules, and then types and entry points inside them by name, and map them to small integer IDs to speed up later runtime lookup steps.

```c++
int SlangShaderCache_getModuleID(SlangShaderCache*, char const* moduleName);
int SlangShaderCache_getEntryPointID(SlangShaderCache*, int moduleID, char const* entryPointName);
int SlangShaderCache_getTypeID(SlangShaderCache*, int moduleID, char const* typeName);
```

In the case where there is a pre-populated cache, this can just be a quick hash-table lookup in a string table stored in the cache. In the dynamic-loading case, these might trigger dynamic load and compilation of modules, and/or add new types and entry points to the cache (so that they get the next available ID).

In order to describe specialized types like `B<X>`, we need a way to take an ID for a type and then look up a specialization of it:

```c++
int SlangShaderCache_specializeType(SlangShaderCache*, int typeID, int argCount, int const* args);
```

and a similar routine is needed for entry points:

```c++
int  SlangShaderCache_specializeEntryPoint(SlangShaderCache*, int entryPointID, int argCount, int const* args);
```

The `args` here can be either types (which always have IDs) or simple values (since an ID is just an integer after all). Just like with the above routines, this would perform a hash-table lookup based on the type and argument IDs, and return the found ID if present. In the dynamic lookup case, this could of course trigger runtime routines to specialize a type on-demand.

The resulting ID from this call is just another type or entry-point ID, and so it could be passed into further calls.

The IDs for specialized (or non-generic) entry points should all be densely indexed from 0 to N-1 (where N is the number of kernels that have been compiled). At any time after loading the cache, the user can query the total number of compiled kernels and get the code for each:

```c++
int SlangShaderCache_getKernelCount(SlangShaderCache*);
void const* SlangShaderCache_getKernelCode(SlangShaderCache*, int index, size_t* outSize);
```

In the case where an application uses a pre-populated cache, it could iterate over all the kernels and load time and pass them through the API for low-level compilation.

As a final convenience routine, in the dynamic case it would be good to be able to request a serializable "blob" representation of the current state of the cache.

Outside of the dynamic case, all of the above queries amount to simple hash-table lookups and can use pre-computed hash tables without needing additional allocations. All of the IDs can just be indices into pre-allocated arrays in the shader cache's binary representation.

**Comment by inversepixel** [comment]
I would love to have a cache so the startup time would be minimized.

**Comment by WeakKnight** [comment]
This would be very useful in my cases. I implemented a simple one to speed up the runtime kernel creation.

**Comment by natduca** [comment]
Putting Q3 with other language features as that seems roughly the same bucket as we'd consider binding api improvements

**Comment by csyonghe** [comment]
Closing this issue now given that the `IFoo` based specialization is probably not going to be adopted by users anytime soon, and the recent link time specialization work offers a poor man's way of slang ir caches.
