### ISSUE TITLE
Support arguments with non-`in` direction in link-time wrapper types.

### ISSUE THREAD

**Issue by cezneluk** [shader-slang/slang#5960]
Functions that contain arguments with directions other than `in` (i.e. `out`, `inout`, `__ref`) lead to compilation errors about non-compliance l-value.

### Current result:
```
public interface ITest {
    public int testDir(inout int a);
};

public struct TestImpl : ITest {
    public int testDir(inout int a) {
        int oldA = a;
        a = 5;
        return a;
 }
}

public struct Test : ITest = TestImpl;

[shader("compute")]
[numthreads(1,1,1)]
void computeMain()
{
    Test data;
    int a = 516;
    int b = data.testDir(a);
}
```

Compilation of this source code produces an error:
```
(0): error 30047: argument passed to parameter '0' must be l-value.
```

Tested on binaries from the latest release (v2024.17), a build from the current master (89dd2b1), and just in case against PR #5955.

### Expected result:

The shader will be successfully compiled, `a` will have the value `5` and `b` will have the value `516` at the end of the function.

**Comment by csyonghe** [comment]
I amended #5955 to also include a fix for this issue.
