### ISSUE TITLE
Allow uniform parameters on entry points

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#614]
## Basic Idea

Code like the following is allowed by fxc:

```hlsl
SamplerState s;
float4 main(float2 uv : UV, uniform Texture2D t) : SV_Target
{
    return t.Sample(s, uv);
}
```

This shader has three input parameters:

* `s`, declared at global scope is a uniform input
* `uv`, declared as a function parameter is a varying input
* `t`, declared as a function parameter is a uniform input

The intended semantics of this code are clear in context. It should behave the same as:

```hlsl
SamplerState s;
Texture2D t;
float4 main(float2 uv : UV) : SV_Target
{
    return t.Sample(s, uv);
}
```

The main difference between the two for fxc is that it reflects the parameter as `$t` in the first case, and just `t` in the second.

Furthermore, fxc allows `uniform` parameters with ordinary (non-resource) types as well, and packages them up in an implicit constant buffer (reflected as a `$Params` constant buffer, akin to the implicit `$Globals` constant buffer it creates for global-scope `uniform`s).

## Why we might actually want this

There are two main reasons why we should get around to supporting this in Slang (beyond the obvious point of wanting to handle everything that is valid in HLSL).

The first reason is that in the context of DXR, it might be useful to have a policy where the parameters that will go into the "global" root signature are declared globally (visible to all entry points), while those that will be in the "local" root signature of a particular entry point will be declared as entry-point parameters instead. A policy like that can only be implemented if the compiler supports `uniform` parameters on entry points.

The second, related, reason is that allowing explicit `uniform` parameters on entry points could be a useful stepping stone to supporting declaring entry points as member functions, e.g.:

```hlsl
struct MyForwardPass
{
    Texture2D diffuseTex; ...
    float3 lightDir; ...

    struct V2F { ... }

    [shader("vertex")]
    V2F vs(VertexAttrs attrs)
    { ... }

    [shader("fragment")]
    float4 fs(V2F v2f)
    { ... }
}
```

This kind of scoping can help make working with "local" parameters a bit simpler (the user can declare other helper routines inside the same `struct` and they will enjoy implicit access to `lightDir`, `diffuseTex`, etc.), and it also avoids polluting the global scope so that there can be only One True Definition of the `V2F` type.

In my mind, the above code is obvious syntax sugar for the following:

```hlsl
struct MyForwardPass
{
    Texture2D diffuseTex; ...
    float3 lightDir; ...
}
struct V2F { ... }

[shader("vertex")]
V2F vs(uniform MyForwardPass this, VertexAttrs attrs)
{ ... }

[shader("fragment")]
float4 fs(uniform MyForwardPass this, V2F v2f)
{ ... }
```

Note how I've made the `this` parameter explicit, but also note how the `this` parameter is also (implicitly) `uniform`. (TBD whether it should be just `uniform MyForwardPass this` or alternatively `uniform ParameterBlock<MyForwardPass> this`).

Declaring entry points as member function is a gateway to some other nice-to-have features, like declaring a DXR "hit group" conveniently as a single `struct` type that conforms to an `IHitGroup` interface.

## Why this is a bit tricky?

When looking at a single isolated shader entry point, it seems like the semantics of `uniform` entry point parameters are clear: just lay out all the global stuff first (so its layout doesn't depend on the chosen entry point) and then lay out the parameters for the chosen entry point. Furthermore, we can safely apply a flag to note that such parameters are stage-specific, since there is no way for code running in another stage to "see" them... (or so it seems superficially).

For a D3D11 back-end, that is really the long and short of the story. Resource parameters are bound per-stage anyway, so it is fine if different stages have different parameters, and the `register` assignment code needs to be aware of this.

For any other API (GL, D3D12, Vulkan) that isn't enough. The question becomes: should each entry point assign locations to its entry-point parameters *as if* no other entry point exists (so that distinct entry points used together might conflict), or should we compile a set of entry points *together* and ensure that the per-entry-point parameter binding never overlap.

While D3D12 and Vulkan let the app specify per-parameter visibility for stuff in a descriptor table/set, the actual tables/sets themselves are shared across all stages (you can't have a vertex and fragment shader disagree on what is bound to descriptor `set` number 3).

There is also the problem of what to do if two different entry points declare the "same" `uniform` parameter. Should both be given the same binding? What if they have the same type and position in the parameter list, but not the same name?

This leads me to conclude that maybe the only reasonable way to handle things is to compile all the entry points that need to agree on layout together (which was already needed for the global scope if your entry points were in different files...).

## Having walked through all of that...

I'm now left wondering if we maybe should rule out entry-point `uniform` parameters because of their confusing semantics in a D3D12/Vulkan world, and instead *only* support the case of entry points as methods on a `struct` type, where the semantics are a lot more clear (you should only use such an entry point together with other methods of the same type).

**Comment by csyonghe** [comment]
We allo uniform parameters now.
