### ISSUE TITLE
RWTexture2D doesn't work in Compute.hlsl

### ISSUE THREAD

**Issue by kenchen3000** [shader-slang/slang#615]
In latest slang ComputeShader sample doesn't work on ubuntu anymore. It seems to be problem when writing into RWTexture2D. 
The error output is listed below:

ERROR: /home/ANT.AMAZON.COM/chenka/Falcor3IntegrationWS/src/Falcor/.dex_project/compute.hlsl:66: '[]' : scalar integer expression required 
ERROR: /home/ANT.AMAZON.COM/chenka/Falcor3IntegrationWS/src/Falcor/.dex_project/compute.hlsl:66: 'gOutput_0' :  left of '[' is not of type array, matrix, or vector  
ERROR: /home/ANT.AMAZON.COM/chenka/Falcor3IntegrationWS/src/Falcor/.dex_project/compute.hlsl:66: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

Can this be fixed? thanks.

**Comment by tfoleyNV** [comment]
Can you link or attach the source HLSL file you are using?

Those error messages come from the downstream glslang compiler that we invoke to generate SPIR-V, so it seems as though Slang is generating invalid GLSL for this input.

**Comment by tfoleyNV** [comment]
I've been able to repro this with the `compute.hlsl` file out of the main Falcor distribution, so I no longer need a copy of the source file. I will try to work on a fix.

**Comment by kenchen3000** [comment]
thanks! FYI i am also working on a shader that need 8 bit int 1 channel RWTexture, and 32 bit float 1 channel RWTexture. which have similar problems.
