### ISSUE TITLE
Array of structured buffers fails for GLSL based targets

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#617]
The following code when compiling to glsl based targets (including spir-v) doesn't work...

```
RWStructuredBuffer<int> outputBuffer[3];
Buffer<float> anotherBuffer;
RWStructuredBuffer<int> outputBuffer2[2];

void writeArray(inout float3 a[4])
{
   a[0] = float3(1, 1, 1);
   a[1] = float3(1, 1, 1);
   a[2] = float3(1, 1, 1);
   a[3] = float3(1, 1, 1);
}
[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
   float3 b[4];
   writeArray(b);
   b[0] += anotherBuffer[dispatchThreadID.x];

   int index = b[0].y > 0 ? 1 : 0;
   outputBuffer[index][dispatchThreadID.x] = b[0].x;
   outputBuffer2[index][dispatchThreadID.x] = b[0].x + 1;
}
```

An error is produced 'left of '[' is not of type array, matrix, or vector ' for line 22. 

The problem is that RWStructuredBuffer<int> outputBuffer[3]; being output as 

```
layout(std430) buffer _S1 {
   int outputBuffer_0[];
};
```

And then accessed as ```(((outputBuffer_0[index_0]))[(_S3.x)]) = _S7;``` - one level of arrayness has been lost so the indexing can't work. 

Tim points out...

In emit.cpp:

```
            // When outputting GLSL, we need to transform any declaration of
            // a `*StructuredBuffer<T>` into an ordinary `buffer` declaration.
            if( auto structuredBufferType = as<IRHLSLStructuredBufferTypeBase>(unwrapArray(varType)) )
            {
                emitIRStructuredBuffer_GLSL(
                    ctx,
                    varDecl,
                    structuredBufferType);
                return;
            }
```

The `unwrapArray(...)` there is taking a `Foo[][][]...[]` and turning it into just `Foo`, which is what we *want* to do for detecting the structured buffer. But then we pass it into `emitIRStructuredBuffer_GLSL` unwrapped, and lose the array-ness.

The right thing to do is to pass in both the structured-buffer type at the "leaf" as well as the full type, and then have `emitIRStructuredBuffer_GLSL` emit something like:

```
buffer _S1 { int outputBuffer_0[]; } _someNameHere[3];
```

But then a use site that used to be `outputBuffer[a][b]` in the original HLSL code needs to be emitted as `_someNameHere[a].outputBuffer[b];` so other parts of the emit logic need to deal with it.

**Comment by natduca** [comment]
Closing as obsolete. We will have to deal with this in the glsl project, but maybe we should get to that through the fresh top down look at the feature.
