### ISSUE TITLE
imageStore of RWTexture2D<float>

### ISSUE THREAD

**Issue by KaChen3000** [shader-slang/slang#620]
Hi, this is a follow up issue of 
https://github.com/shader-slang/slang/issues/615
I can't find a good way to write to a one channel RWTexture2D/3D anymore in the new slang version.
When slang was still supporting glsl, the following code works to write one channel RWTexture:
layout(set = 0, binding = 2, r32f) uniform image3D gOccupancyTex;
imageStore(gOccupancyTex, ivec3(crd), ivec4(outputId, 0,0,0));

But with the depreciation of glsl, I can't find a way to write to one channel RWTexture anymore. I tried:

-----------------------------------------------------------------------------------------------------------
RWTexture3D<float> gOccupancyTex;
float outputId = 1;
gOccupancyTex[uint3(crd)] = (float4)(outputId, 0,0,0);

It has the error:

Program Linkage failed.
Program with Shaders:
ComputeOccupancy.hlsl/*main*/

/MyProject/ComputeOccupancy.hlsl(147): error 30019: expected an expression of type 'float', got 'float4'
-----------------------------------------------------------------------------------------------------------

I also tried
RWTexture3D<float> gOccupancyTex;
float outputId = 1;
gOccupancyTex[uint3(crd)] = outputId;

It has the error:

Program Linkage failed.

Program with Shaders:
ComputeOccupancy.hlsl/*main*/

ERROR: /MyProject/ComputeOccupancy.hlsl:147: 'imageStore' : no matching overloaded function found 
ERROR: /MyProject/ComputeOccupancy.hlsl:147: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
-----------------------------------------------------------------------------------------------------------

None of them works.

This happens during the upgrade from Falcor2 to Falcor3 and I integrated the latest fix from slang. thank you very much!

**Comment by tfoleyNV** [comment]
One note is that the expression `(float4)(outputId, 0,0,0)` doesn’t do what you might expect. Written that way it is interpreted as a cast of the expression `(outputId, 0,0,0)` to the type `float4`. The expression `(outputId, 0,0,0)` is a valid expression using the “comma operator” and evaluates to zero. Hopefully rewriting to `float4(outputId, 0,0,0)` will work for you.

On the other stuff, we definitely have a bug where we don’t support `RWTexture2D<float>` or `RWTexture2D<uint>` etc. As you might have noticed, we don’t output a correct GLSL `format` for them. I can try to look at this, but turnaround may not be great with the upcoming SIGGRAPH conference getting close.

**Comment by kenchen3000** [comment]
Thanks Tim. You are right about(float4)(outputID, 0,0,0). It was a typo. But removing () surrounding float4 has the same error in slang. We were able to write ImageStore(gOccupancyTex, ivec3(crd), ivec4(outputId, 0,0,0) and it works before glsl is supported. This is currently blocking us. thanks.

**Comment by tfoleyNV** [comment]
To make sure I understand. The issue here is that a 4-component image works fine, but you need a 1-component image format (e.g., Slang must output `layout(r32f)` for the GLSL declaration of the image).

Otherwise, it would seem like using `RWTexture3D<float4>` (aka, just `RWTexture3D`) would be usable for a workaround.

**Comment by KaChen3000** [comment]
That's correct. 
RWTexture3D<float4> would work for shader compilation, but it uses 4 times more memory and bandwidth affecting performance, and code patches in cpp which i am trying to avoid doing that.

**Comment by tfoleyNV** [comment]
PR #622 should implement a fix for this issue.

**Comment by KaChen3000** [comment]
thanks!

**Comment by tfoleyNV** [comment]
A fix has been merged in #622, and is now released as part of Slang `v0.10.31`.

I'm closing this out, but please feel free to re-open or file a new issue if something doesn't work as needed.
