### ISSUE TITLE
Cannot use RasterizerOrdered objects

### ISSUE THREAD

**Issue by kyaoNV** [shader-slang/slang#627]
`error 300015: undefined identifier`

There is a list of all the types on this [page](https://docs.microsoft.com/en-us/windows/desktop/direct3d12/rasterizer-order-views)

**Comment by tfoleyNV** [comment]
Thanks. What is the priority for a fix?

**Comment by kyaoNV** [comment]
High, but not needed until after next week.

**Comment by tfoleyNV** [comment]
Okay. I will fix this early next week.

**Comment by tfoleyNV** [comment]
Note: this issue only applies to `RasterizerOrderedByteAddressBuffer` and `RasterizerOrderedStructuredBuffer`. The texture types and plain old `RasterizerOrderedBuffer` all seem to pass through the front-end (at least).
