### ISSUE TITLE
Add support for GLSL imageBuffer/1D/2D

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#63]

**Comment by tangent-vector** [comment]
The *types* should be supported (have you run into an issue with them), so I'm guessing this issue relates to reflection. Is that correct?

**Comment by tangent-vector** [comment]
Also, were you able to confirm if changing `<TextureType>` to `<TextureTypeBase>` in `reflection.cpp` gave you the behavior you wanted?

**Comment by tfoleyNV** [comment]
Is the current level of support enough (as of the `v0.5.2` tag)?

**Comment by tangent-vector** [comment]
I think the basics are covered, so I'm closing this for now. Please open new issues for more detailed feature requests.
