### ISSUE TITLE
Refactor of List 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#632]
List could do with some refactoring. Some ideas...

* Change name from List to Array
* Use method naming conventions more consistent with other parts of library (like lower camel) and more in line with other array like containers
* Use a signed integral type for index, and for return type from indexOf
  + Such that can use  < 0 as test for valid index
  + Arguably the integral should be int - as it has fast multiply and an array of larger sizes should perhaps be done another way
* For really large blocks of memory perhaps use a different type - that is more limited like MemoryBuffer<T>. It doesn't have indexing (cos its huge right!) etc
* Life time of contents of List is odd. On creation of List the whole contents is initialized. Stuff is only deleted when the List itself is destroyed (!). We should only have used elements in known state.
* We should support reallocing, and _requiring_ types in Array can be shifted in place (removes need to move)
* FastRemoveAt is not clear why it's fast - I know it does a swap by looking at source, but not by name
* Remove the use of Exceptions and use asserts
* Not use new T[size] to allocate, or delete [] ptr - because has poor memory layout usage, as it stores a size along with the array, and we know what the size is - it's stored in the list. Depending on alignment of T could be quite wasteful. 
* Move some of the more esoteric methods out and put into util/utils (say like sort)
* Split out code that can be shared across template instantiation
* Make members explicit (with m_ prefix)
* Array size doubles if there isn't enough space - might be okay for smallish sizes, but probably wants something a bit more modest 
* The initial size, is arguably too big for many types, the initial size should be based on some math around sizeof(T)
* Methods should be commented
* Implementation should probably be split from interface to make easier to read 
* FastRemoveAt tests for idx of -1 which seems needless

**Comment by csyonghe** [comment]
We have done a lot of refactors to our corelib since this issue opened. If there are any remaining cleanups we should open them as separate issues.
