### ISSUE TITLE
Reflect GLSL PS interpolation qualifiers

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#64]
Required for Falcor to explicitly enable super-sampling in Vulkan

**Comment by tangent-vector** [comment]
Are you just referring to things like the `sample` qualifier on fragment shader varying inputs:

    sample vec2 whatever;
    centroid vec4 somethingElse;

Or are there more requirements beyond that? E.g. do you need to be able to test if the shader uses the `gl_SampleIndex` built-in variable, or anything like that?

How does the situation for Vulkan differ from D3D?

**Comment by nbenty** [comment]
I need to know if the shader requires us to use super-sampling, similar to [ID3D12ShaderReflection::IsSampleFrequencyShader()](https://msdn.microsoft.com/en-us/library/windows/desktop/dn933719(v=vs.85).aspx)

In DX12, supersampling is enabled automatically if the PS use any inputs that are evaluated at sample location or SV_SampleIndex is used.

**Comment by tfoleyNV** [comment]
There is now a basic version of this in place thanks to PR #79.

Leaving this open in case it doesn't meet requirements.
