### ISSUE TITLE
Support 16-bit floats

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#640]
https://github.com/Microsoft/DirectXShaderCompiler/wiki/16-Bit-Scalar-Types

Based on the conversation we had, this requires:
- Add support for the new/aliased data types
- Support `float16` in CBs (including the reflection)

No priority for this yet, just documenting the request

**Comment by tfoleyNV** [comment]
PR #643 should add the required support, although I haven't done any real testing (other than being sure it doesn't break the existing tests).
