### ISSUE TITLE
Add link to Yong's thesis?

### ISSUE THREAD

**Issue by kayvonf** [shader-slang/slang#654]
In addition to the SIGGRAPH paper, does it make sense to add a link to Yong's final thesis from README.md?

I linked in the document from the paper page:
http://graphics.cs.cmu.edu/projects/slang/

A stable direct link is:
http://graphics.cs.cmu.edu/projects/renderergenerator/yong_he_thesis.pdf

**Comment by csyonghe** [comment]
Done.
