### ISSUE TITLE
Add compile flag to enable IEEE strictness

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#656]
Add `SlangCompileFlags` to enable IEEE strictness.

It'd be useful even if it only works with fxc.

For fxc use `D3DCOMPILE_ENABLE_STRICTNESS` to `D3DCompile`

dxc has a `ShaderFlags.SetDisableMathRefactoring()` -- not sure that's the right one though.

**Comment by csyonghe** [comment]
This is implemented.
