### ISSUE TITLE
Float operation is in 16 bit precision?

### ISSUE THREAD

**Issue by KaChen3000** [shader-slang/slang#658]
Hi,
In slang shader I write:
```
float computeRoot(float b, float c, int2 uv)
{
    float d = b * b - 4 * c;
    gDebugTexture[uv] = float4(b*b,4*c,d,0);
    return d;
}
```
upon inspecting in renderdoc, the input of b = 0.016f; c = 0.00006f;
I would expect ```b*b = 0.000256f, 4 * c = 0.00024, and d = 0.000016f;```
But in renderdoc it actually shows that ```gDebugTexture[uv] = ( 0.00026, 0.00026, 0, 0).```
Which means that ```b*b``` is calculated into 0.00026 with the same value as 4 * c becoming 0.00026.
In turns the d becomes 0.

This doesn't seems to be executing at 32 bit floating point precision. Looks more like half floating point precision.  If I look at the spir-v code in renderdoc, i don't see any converting into half floating point. 

Any idea why this is happening?

thanks.

**Comment by KaChen3000** [comment]
It is on ubuntu with vulkan. thanks.

**Comment by KaChen3000** [comment]
If I run some vulkan sdk samples and add same instruction, it works: d = 0.000016f. instead of 0.
I suspect that i need to specific highp float for the variable. In compute shader all float is default to lowp i think. Is there a way to do it in slang?

**Comment by tfoleyNV** [comment]
Can you point me to a reference that shows the default precision being `lowp`? My understanding had been that desktop GLSL (for OpenGL and Vulkan) only has precision qualifiers for compatibility with OpenGL ES, and ignores them.

I could easily tweak Slang's output to specify `highp` precision, but it doesn't seem like it should be necessary.

**Comment by KaChen3000** [comment]
You are right highp/lowp seems to be es only. At this point i am not sure why slang shader used in my compute shader is having low precision for floating point.

**Comment by tfoleyNV** [comment]
You mentioned that this is on Ubuntu with Vulkan. Do you have any information on the hardware/driver combination that could be used to help narrow down the issue?

It might also help to compare the SPIR-V that Slang is generating against what the Vulkan SDK examples are generating. It is possible that there is some difference there that could help in tracking down the issue. Even if this ends up being a driver bug, it is possible that Slang can work around it.

**Comment by KaChen3000** [comment]
thanks for checking this. I am using nvidia titan x(pascal) with driver 390.87.
vulkan 1.0.61.1
