### ISSUE TITLE
Mangled names for generics should not include generic parameter names

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#661]
It looks like we currently emit generic declarations with mangled names that include the generic parameter names, which means that changing the name of a generic type parameter is a binary breaking change. It also means that when writing target-specific overloads for a generic, all of the overloads need to agree on the names of generic parameters, or they won't be recognized as declarations of the "same" function.

This currently only has consequences for the standard library, where we can try to be careful about these issues, but it could potentially break user code once we start exposing these features to users.

**Comment by natduca** [comment]
Lets close and reopen if we hit this again given age of issue.
