### ISSUE TITLE
Parser should prefer to associate modifiers with an inner declaration over an outer generic

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#662]
Right now something like this:

```hlsl
[attr] void foo<T>(T x);
```

associates the `[attr]` attribute with the generic declaration and not the inner function. It is as if the user wrote the following (using our more ugly syntax):

```hlsl
[attr] __generic<T>
void foo(T x);
```

instead of:

```hlsl
__generic<T>
[attr] foo(T x);
```

Right now the only workaround is to rewrite declarations that need modifiers into this last form, and you can see many examples of this in the Slang standard library. A better fix would be to modify the parser to not attach modifiers blindly to generic declarations.

**Comment by natduca** [comment]
Lets drop for issue-age. Can reopen for Q3 if we think this is imporant and mistriaged.
