### ISSUE TITLE
Initializing parameter with const-qualified value produces invalid HLSL code

### ISSUE THREAD

**Issue by mmp** [shader-slang/slang#666]
Given:
```
static const uint foo = 1;
static const uint bar = 1 << foo;
```

Then for `bar`, slang seems to generate:
```
static const uint bar_0 = /* unhandled */;
```
which HLSL isn't happy with. :-)

It'd be nice to be able to do this in general, but lacking the functionality, it'd be nice to have a direct compiler error issued.

**Comment by tfoleyNV** [comment]
Thanks for reporting this issue! I'll start looking at this now. It seems like it should be a simple/obvious problem, but we'll see how it goes.

**Comment by tfoleyNV** [comment]
I tried to repro this with the fragment of HLSL given, but it seems like for the bug to repro I need this case instead:

```hlsl
static const uint foo = 1;
static const uint bar = foo;
```

That is, the second constant is defined to be exactly the first.
