### ISSUE TITLE
Statement that does nothing in slang/check.cpp

### ISSUE THREAD

**Issue by mmp** [shader-slang/slang#678]
This line of check.cpp seems to be a no-op: https://github.com/shader-slang/slang/blob/f9710d50bc675ddba51cc6d94b125ba1549708a8/source/slang/check.cpp#L5194

Stray code, or was something supposed to be happening there?

**Comment by tfoleyNV** [comment]
My guess is that I'd previously been moving that sub-expression into a temporary, and then somebody eliminated the temporary and just repeated the sub-expression anyway?

Probably worth cleaning up. Thanks for spotting it. I assume you are debugging something else if you are poking around in the code like this?

**Comment by mmp** [comment]
I was trying to build it on OSX and clang gave a warning there, so I
figured I'd report it.

(PR coming with a few small cleanups on that front.)

**Comment by csyonghe** [comment]
Fixed.
