### ISSUE TITLE
Support BuiltInIntersectionAttributes for DXR

### ISSUE THREAD

**Issue by kyaoNV** [shader-slang/slang#684]
The spec document mentions it, but doesn't appear to define it though...

**Comment by tfoleyNV** [comment]
I believe the identifier is (or at least *was*) `BuiltinTriangleIntersectionAttribites`.

**Comment by kyaoNV** [comment]
Ah `BuiltinTriangleIntersectionAttributes` works. the documentation called it `BuiltInIntersectionAttributes`
