### ISSUE TITLE
Global generic value parameters

### ISSUE THREAD

**Issue by tangmi** [shader-slang/slang#693]
I'm wondering if it's possible to do something like:

```hlsl
type_param someFloat : float;
type_param someCondition : bool;

float4 main(CoarseVertex coarseVertex : CoarseVertex) : SV_Target
{
    float3 color = someCondition ? coarseVertex.color : float3(0, 0, 0);
    return float4(color, someFloat);
}
```

And then "specialize" our shader with something like:

```c++
std::vector<const char*> genericArgs;
genericArgs.push_back("0.5");
genericArgs.push_back("true");
int fragmentIndex = spAddEntryPointEx(
    /* … */
    genericArgs.size(),
    genericArgs.data());
```

When I try and compile the shader, I end up with some error message like:
```
shaders.slang(74): error 39999: no overload applicable to arguments of type (typeof(someCondition), vector<float,3>, float3)
core(51): note 39999: candidate: ?:<float, 3>(vector<bool,3>, vector<float,3>, vector<float,3>)
core(50): note 39999: candidate: ?:<vector<float,3>>(bool, vector<float,3>, vector<float,3>)
shaders.slang(75): error 39999: no overload for 'float4' applicable to arguments of type (vector<float,3>, typeof(someFloat))
slang\source\slang\slang-stdlib.cpp(232): note 39999: candidate: $init(vector<float,3>, float)
slang\source\slang\slang-stdlib.cpp(233): note 39999: candidate: $init(vector<float,2>, vector<float,2>)
```

…which makes sense, as I want `someFloat` to be a float, and not some type that implements `float` as an interface. It's possible to use primitives as generic parameters, like in the `LightArray` example:

```hlsl
struct LightArray<L : ILightEnv, let N : int> : ILightEnv { /* … */ }
```

Where one can specify the `genericArgs` for an `ILightEnv` as e.g. `LightArray<PointLight, 5>`.

Is it possible to use primitives for the global `type_param` generic arguments? I'd like to author shaders that can be "specialized" a la SPIR-V's specialization constants. Is there a better way to do this in slang?

Many thanks!

**Comment by tfoleyNV** [comment]
What you are asking for amounts to global generic *value* parameters to go along with the global generic *type* parameters we have today. As you note, SPIR-V already has a similar concept with specialization constants, and it turns out that the Metal Shading Language has some similar ideas.

We are very interested in supporting generic value parameters more broadly in Slang, but unfortunately this isn't something we expect to get to right away, just because of other development priorities.

One important question is whether it would be better to add support for such parameters at the global scope (to match `type_param`) or simply move toward a model of having all such parameters on the entry point function. For example:

```hlsl
float4 main<let someFloat : float, let someCondition: bool>(
    CoarseVertex coarseVertex : CoarseVertex) : SV_Target
{
    float3 color = someCondition ? coarseVertex.color : float3(0, 0, 0);
    return float4(color, someFloat);
}
```

There is already some support for this kind of syntax (as you note with `LightArray`) but the compiler implementation for entry points with direct generic parameters (instead of just global generic parameters) hasn't been completed.

If somebody was excited about this kind of feature and wanted to work on contributing it to the Slang codebase, I would be happy to provide them with assistance along the way. Otherwise I can only say that we would like to implement what you are asking for, but don't currently have it scheduled for implementation.

**Comment by tangmi** [comment]
Thanks for the fast response. I think I agree that moving towards a more uniform way of defining generic parameters across types, functions, and entrypoints is a good idea.

For now, it seems like there's a "workaround" by defining an interface and empty type like so:

```hlsl
interface IFoo {
    bool someCondition();
    float someFloat();
}

struct Foo<let a : bool, let b : float> : IFoo {
    bool someCondition() { return a != 0; }
    float someFloat() { return b; }
}

type_param TFoo : IFoo;
ParameterBlock<TFoo> foo;

float4 fragmentMain(
    CoarseVertex coarseVertex : CoarseVertex) : SV_Target
{
    float3 color = foo.someCondition() ? coarseVertex.color : float3(0, 0, 0);
    return float4(color, foo.someFloat());
}
```

And then passing something like `Foo<1,1>` into the `spAddEntryPointEx` call. Although, this has some shortcomings:
 1. Lots of boilerplate
 2. `spAddEntryPointEx` seems to only accept integral values (the compiler fails with `entry-point type parameter 'Foo<1,0.5>' must be declared as a type` if I try and use `true` or `0.5` as a generic argument)

It seems like both can be solved by implementing global generic value parameters, but 2. might be able to be worked around by using `0` and `1` for bools and some fixed-point normalized value for floats...

I'll take a look at the Slang source more closely to see if this is something I might be able to tackle.

**Comment by tfoleyNV** [comment]
Your workaround would indeed work, but I agree that it isn't ideal.

As you've found, generic value parameters are not a fully realized feature, so they are currently limited to `int` values in practice. As you note you can emulate the `bool` case using `0` and `1`, but there is no support for specializing to a floating-point value.

I'd question whether specializing to a floating-point value is going to give you much benefit, though. Except in very specific cases where, e.g., a floating-point constant is zero and therefore allows a large and expensive computation to be skipped, there is going to be little to no benefit in static specialization. Even then, you can get much of the benefit by doing a conditional branch on the value (`if(someFloat > 0) { ... }`). Unless you have a very strong reason to believe that specializing to floating-point values is important for your application, I would encourage you to pass such data along ordinary channels (e.g., in `cbuffer`s or `ParameterBlock`s).

The Slang project has not made enough effort to make itself welcoming to new contributors, so don't be surprised if things are a bit confusing when you first look at the code. I am happy to answer questions here on GitHub, if you decide to take a look.

**Comment by tangmi** [comment]
You got me stumped on the purpose of having floating point values here... but I think being able to pass enum values by name would be great, as opposed to keeping a parallel enum definition on the C++ side and casting to and from and int on both sides.

```hlsl
enum Foo { Yes, No, MaybeSo, };
float4 main<let foo : Foo>(/* … */) { /* … */ }

// and use e.g. "Yes"/"No"/"MaybeSo" in `spAddEntryPointEx`
```

If you wouldn't mind helping me get an idea for how big of a project this would be, I'd like to get an idea for how feasible it is to do. My guess is that the steps to complete this would be:
 1. Update the parsing logic to accept `bool` and enum types (I get the feeling that this is already implemented as I'm not getting any errors compiling shaders with these)
 2. Update `spAddEntryPointEx`:
   - To accept entry points that are generically parameterized functions (there's currently an error saying `spAddEntryPointEx` needs to refer to a "function" it I point it to a generically parameterized one)
   - To parse the `genericTypeNames` string array for `true` and `false` for boolean inputs and identifiers(?) for enum inputs
 3. Write tests

I know I'm missing some steps in the process...

Some questions I have:
 - Should this only work for value parameters (i.e. only allow `let a : A` generic arguments on an entry point function)?
 - How would this work with global `type_param`/`ParameterBlock` arguments, if at all?
 - What indices do the value parameters on an entry point get in the `genericTypeNames` list if there are `type_param`s also (do they go at the end, should there be a way to set them by name, etc.)?

**Comment by tfoleyNV** [comment]
This feature is coming up now as a priority for the Falcor research framework, so I’ll be trying to start implementation on global generic value parameters soon.

**Comment by csyonghe** [comment]
Closing now as this is no longer considered a relavent feature.
