### ISSUE TITLE
Interlocked targets must be groupshared - InterlockedMin HLSL

### ISSUE THREAD

**Issue by vasumahesh1** [shader-slang/slang#699]
Hi,

I have an issue which seems like a bug to me.

```sh
X:/Azura/Source/Samples/2_DeferredRenderer/Shaders/ForwardPlusComputePass2.cs.slang(86,5-35): error X3549: interlocked targets must be groupshared or UAV elements
```

Tested on:
0.11.6 & 0.11.1
Compiling to HLSL

Target Slang Code:
(For Forward+ Renderer)
```hlsl
groupshared uint minDepthInt;
groupshared uint maxDepthInt;



// ....

InterlockedMin(minDepthInt, depthInt);
InterlockedMax(maxDepthInt, depthInt);
```

Output code:
```hlsl
#line 81
    float _S5 = attachmentBlock_depthBuffer_0.Load((vector<int,3>) vector<uint,3>(dispatchThreadId_0.xy, (uint) 0));
    uint depthInt_0 = asuint(_S5.x);

    GroupMemoryBarrierWithGroupSync();

    uint _S6;

#line 86
    _S6 = minDepthInt_0;

#line 86
    InterlockedMin(_S6, depthInt_0);

#line 86
    minDepthInt_0 = _S6;
    InterlockedMax(maxDepthInt_0, depthInt_0);
```

It replaced the groupshared variable with a temporary? When I removed the temporary and assigned it `minDepthInt_0`, FXC was able to compile it again.

[Link to main compute shader](https://github.com/vasumahesh1/azura/blob/dev/Source/Samples/2_DeferredRenderer/Shaders/ForwardPlusComputePass2.cs.slang) (dev branch)

**Comment by tfoleyNV** [comment]
Thanks for filing this. I’ll look into it.

**Comment by tfoleyNV** [comment]
This looks like it is a copy-paste typo in the standard library declarations for `InterlockedMin` and `InterlockedMax`. The other `Interlocked*` functions don’t seem to be affected. This should be a quick fix.

Thanks again for reporting the issue!

**Comment by vasumahesh1** [comment]
No problem 👍
