### ISSUE TITLE
Support globallycoherent storage for RWTexture2D

### ISSUE THREAD

**Issue by ikryukov** [shader-slang/slang#729]
I got error during compilation hlsl code:
`globallycoherent RWTexture2D<float> Result : register( u0 );`
error:
 `error 20001: unexpected identifier, expected '(' `
More info about globallycoherent:
https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/sm5-object-rwtexture2d

**Comment by tfoleyNV** [comment]
This should be implemented in PR #732 and deployed in the `v0.11.4` release.
