### ISSUE TITLE
Specifying a "tag" type for an enum

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#780]
Syntatically, the Slang compiler supports declaring an `enum` type with an assocaited "tag" type:

```
enum Color : uint { Red, Green, Blue }
```

There is some logic in place to try to support this use case, but other checks in the compiler are currently enforcing that any "base" declarations must be interface types and not concrete types. We should add a carve-out for cases where a "base" is actually specifying the tag type for an `enum` so that users can actually take advantage of the support we tried to add.

The workaround for now is for users to just live with all `enum` types implicitly having `int` as their tag type.

**Comment by csyonghe** [comment]
We already support tag types.
