### ISSUE TITLE
HLSL: Parse and reflect user-specified root signature

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#8]
HLSL allows a shader entry point to specify the root signature to use as an attribute:

    [RootSignature("...")] void main(...) { ... }

The string literal there is expected to be provided via a `#define`, and in fact fxc seems to have special support for compiling a `#define`d string into a root signature (so it is a `#define` that gets linkage? what happens if I `#undef` it or have multiple definitions over the course of one file?).

The string literal that specifies a root signature encloses some syntax that looks more or less like a bunch of constructor calls with a bit of `key = value` argument-passing sugar.

See [this page][hlsl-root-sig] for the MSDN documentation of the feature.

[hlsl-root-sig]: https://msdn.microsoft.com/en-us/library/windows/desktop/dn913202(v=vs.85).aspx)

Slang's current approach is to pass through attributes it doesn't understand, so shaders using this feature shouldn't be rejected today (modulo support for implicit concatenation of string literals, which we need to add).

A more complete implementation would require:

1. Add the `RootSignature` attribute as a known attribute we actually parse/check
2. Add a dedicated sub-parser (we can probably leverage the existing lexer and related infrastructure) to handle root signatures and parse them into some kind of AST.
3. Figure out an appropriate reflection interface for querying this data (maybe a satellite library that just returns the raw D3D data structures)
4. Maybe consider a feature to allow attaching root signature names to a compile request, without need for any entry points

**Comment by tangent-vector** [comment]
I'm not aware of any users who actually need/want this feature, and it kind of goes against the essence of Slang's value proposition.
I'm going to close this, but we can re-open it if a user of Slang ever decides they need it (they won't).

**Comment by szihs** [comment]
Claude Code is working… <img src="https://github.com/user-attachments/assets/5ac382c7-e004-429b-8e35-7feb3e8f9c6f" width="14px" height="14px" style="vertical-align: middle; margin-left: 4px;" />

I'll analyze this and get back to you.

[View job run](https://github.com/shader-slang/slang/actions/runs/1)

**Comment by szihs** [comment]
Claude Code is working… <img src="https://github.com/user-attachments/assets/5ac382c7-e004-429b-8e35-7feb3e8f9c6f" width="14px" height="14px" style="vertical-align: middle; margin-left: 4px;" />

I'll analyze this and get back to you.

[View job run](https://github.com/shader-slang/slang/actions/runs/1)

**Comment by szihs** [comment]
Claude Code is working… <img src="https://github.com/user-attachments/assets/5ac382c7-e004-429b-8e35-7feb3e8f9c6f" width="14px" height="14px" style="vertical-align: middle; margin-left: 4px;" />

I'll analyze this and get back to you.

[View job run](https://github.com/shader-slang/slang/actions/runs/1)

**Comment by szihs** [comment]
Claude Code is working… <img src="https://github.com/user-attachments/assets/5ac382c7-e004-429b-8e35-7feb3e8f9c6f" width="14px" height="14px" style="vertical-align: middle; margin-left: 4px;" />

I'll analyze this and get back to you.

[View job run](https://github.com/shader-slang/slang/actions/runs/1)

**Comment by szihs** [comment]
Claude Code is working… <img src="https://github.com/user-attachments/assets/5ac382c7-e004-429b-8e35-7feb3e8f9c6f" width="14px" height="14px" style="vertical-align: middle; margin-left: 4px;" />

I'll analyze this and get back to you.

[View job run](https://github.com/shader-slang/slang/actions/runs/1)
