### ISSUE TITLE
Empty global parameter blocks do not occupy binding slots in layout

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#803]
Slang removes empty global parameters after type legalization. This results in incorrect layout for subsequent global parameters.

Test case:
```
struct T
{
	float a;
};

struct E
{
	float get() {return 1.0;}
};

ParameterBlock<E> p0; 
ParameterBlock<T> p1; // expect binding 1 instead of 0


float4 main(float4 vin : SV_POSITION)
{
	return float4(p0.get() + p1.a);
}
```

**Comment by tfoleyNV** [comment]
We can discuss whether the policy is the right one, but I want to note that what you describe is the intended behavior of the implementation work I did.

Parameter binding/layout happens before all this legalization, and there is no way for legalization to affect the bindings associated with other parameters. There is explicit logic in the type layout algorithm to deal with empty constant buffers and parameter blocks.

Once you start thinking about the problem of a `ParamterBlock<X>` where `X` has a field that is a `ParamterBlock<Y>` you find that you can’t assume a one-to-one mapping from parameter blocks to, e.g., descriptor sets.

**Comment by csyonghe** [comment]
I see. Yeah, I believe we discussed this issue before, but I forgot it.
