### ISSUE TITLE
Cross compiling SampleCmp to GLSL/SPIRV

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#804]
Consider a call to `SampleCmp` in the example below:
```
Texture2D shadowMap;
SamplerComparisonState sampler;
float4 main(float4 p : SV_POSITION)
{
    return shadowMap.SampleCmp(sampler, float2(0.0), 0.0);
}
```

Slang cannot translate the above code into the following GLSL:
```
#version 450
layout(row_major) uniform;
layout(row_major) buffer;

#line 3 0
layout(binding = 0)
uniform texture2D shadowMap_0;


#line 5
layout(binding = 1)
uniform samplerShadow sampler_0;

layout(location = 0)
out vec4 _S1;


#line 3
void main()
{
    float _S2 = shadowMap_0.SampleCmp(sampler_0, vec2(0.00000000000000000000), 0.00000000000000000000);
    _S1 = vec4(_S2);
    return;
}
```

The call to `SampleCmp` is not being translated correctly.

**Comment by csyonghe** [comment]
Hmm, I just realized that GLSL for vulkan does support constructing a sampler object in shader code. That means there should not be any issues. So this is probably just due to Slang is not generating the current type of sampler object.

**Comment by tfoleyNV** [comment]
Yeah, I had thought that we could construct the right type in GLSL code, but I admit to not knowing the details. If you want to try to dig into it that would be a welcome fix.

**Comment by csyonghe** [comment]
Yeah, that is true. I am looking at core.meta.slang and there seemed to be many cases where we are not providing a `__target_intrisnic(glsl,`

**Comment by tfoleyNV** [comment]
Yes, almost all of those have been done on an as-needed basis because we could never justify the time expenditure to do them all systematically. If you’ve got the time and inclination, it would be great to get a PR that starts chipping away at the gaps in our cross-compilation coverage there.

**Comment by tfoleyNV** [comment]
Did #806 cover everything from this issue?

**Comment by csyonghe** [comment]
Yes, it does.

________________________________
