### ISSUE TITLE
Add support for `image` memory qualifiers

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#81]
`coherent`, `volatile`, `restrict`, `readonly`, `writeonly`

Slang reports an error if I use any of them.
Simple compute-shader to reproduce the problem:

layout(set = 0, binding = 1, rgba32) uniform writeonly image2D gOutput;
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main()
{
    imageStore(gOutput, gl_LocalInvocationID.xy, vec4(1,1,1,1));
}

**Comment by tfoleyNV** [comment]
This will be easy enough to add. If you only need them to be parsed, and don't need reflection, you should be able to do it yourself as a workaround until I can get to it.

In `source/slang/slang-stdlib.cpp`, near the end, you will find these lines:

```
        sb << "__modifier(SimpleModifier)           flat;\n";
        sb << "__modifier(SimpleModifier)           highp;\n";
```

You should be able to do the same thing to add as many qualifiers as you like, that Slang will parse, ignore, and then spit back out. E.g.:

```
        sb << "__modifier(SimpleModifier)           coherent;\n";
        sb << "__modifier(SimpleModifier)           volatile;\n";
...
```

I'll try to do a more thorough survey of GLSL qualifiers soon.
