### ISSUE TITLE
Translating HLSL "Wave" operations to GLSL "subgroup" operations

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#813]
The `Wave*` operations introduced in HLSL SM 6.0 largely map over to the `subgroup*` operations added to Vulkan (I'd need to double check the exact version/extensions). There is a [presentation](https://www.khronos.org/assets/uploads/developers/library/2018-vulkan-devday/06-subgroups.pdf) that covers the details, including a table of how the HLSL operations map to the GLSL equivalents.

We should add `__target_intrinsic` modifiers as needed to map these functions over.

**Comment by csyonghe** [comment]
Done.
