### ISSUE TITLE
Overhaul Slang API to something "COM-lite"

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#823]
We've slowly been introducing more "COM-lite" interfaces into the API (mostly for user-supplied "callback" cases), which reflects an undocumented decision that we'd like to expose a more COM-like API overall.

We eventually need to go through and write up an overhauled API that exposes all the current (non-deprecated) functionality through COM-lite interfaces instead of free functions. There should be a single free function with `extern "C"` linkage for loading up an instances of the API (probably the equivalent of a `SlangSession`).

There are some large-scale changes to how compilation is structured that we would like to make, but we will probably need to be conservative about what major API changes we introduce during a refactor, to avoid potential breakage.

One sticking point for a refactor is that some of the opaque types we expose through the API today are actually internal compiler types (e.g., AST nodes) that we wouldn't want to complicate by adding COM-lite interfaces into their inheritance (multiple inheritance in core data types worries me). We can either make the refactored API continue to manipulate these types indirectly via opaque handles, or we can introduce explicit COM-friendly wrapper objects around them instead.

A final note for implementers: we should retain the existing C API as-is (probably having it be a thing wrapper around the COM API), so that we maintain source and binary compatibility for existing clients. We can/should deprecate that API eventually, but we'll need to establish the plan and timeline for that later.

**Comment by natduca** [comment]
@csyonghe should we keep this issue open? Which milestone?

**Comment by csyonghe** [comment]
This is important as it affects our compiler API. However, it doesn't affect the language design so not as urgent as others. My preference is for  this  to be a nice-to-have Q3, most likely something we will get  to next year.

**Comment by csyonghe** [comment]
Closing, done.
