### ISSUE TITLE
Add option to configure the target language version

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#83]
Currently it embeds `#version 420` into the shaders. I'd like to use 4.5, but in general we should allow the user to choose(the user of Slang)

**Comment by tfoleyNV** [comment]
Putting a `#version` at the top of your GLSL will do what you expect for GLSL input files.

When cross-compiling from Slang, I currently use version `420`, and I've recently added a provision for the compiler to add `#extension` lines when it sees code using functionality only provided by extensions.

You are right, though, that there should probably be a catch-all way to specify this, and it can probably be folded into the notion of a "profile." Slang already understands, e.g. `vs_5_0` for HLSL code, and has a `glsl_vertex` profile, but we really need something like `glsl_vertex_450`.

This seems like a good feature request.
