### ISSUE TITLE
Test runner should be robust against crashes

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#847]
The work that has been done to speed up `slang-test` has the unfortunate drawback that a crash in one of the test cases can bring down the test runner.

One annoying consequence is that when running the test script, it can be easy to assume that the last message that was printed has to do with the test that caused the crash, when in fact it is the test *after* that which is to blame. We could change the format from:

```
[pass/fail result] test name
```

over to something like:

```
test name ... [pass/fail result]
```

so that we can at least print out the `test name...` part before running a test so that the log message on crashes is more useful, but I think this is not the ideal fix.

Instead it would make a lot of sense if by default the `slang-test` executable when invoked would re-invoke itself as a sub-process to run the actual testing. Note that this is not one process per test, but a fixed two processes: one to run the tests, and a parent "watchdog" process to see if the child process crashes.

An initial implementation could just report that a crash occurred and ensure that a reasonable result code is returned. A more advanced implementation could use a pipe to communicate test names to be run to the sub-process and read back results to report. That would allow the parent process to detect a crash or infinite loop (using a suitable timeout) and re-invoke the child process to pick up where it left off, so that crashes in individual test cases would be, more or less, like any other failure.

**Comment by jsmall-nvidia** [comment]
There is a development advantage to have the option of running everything in process. It means when running the slang-test, if there is a crash, it crashes out into the debugger where that occurs. In the past (when the tools were subprocesses) there were multiple fiddly steps - I'd run the test suite, and if there was a problem output what the command line is, and then run the actual tool. This was somewhat tedious. So we should at a minimum keep a mechanism to to run everything in process.

As it stands we do build the code base with exceptions enabled. That whilst not as all encompassing as a separate process, (optionally) trapping exceptions across the dll boundary would probably capture a large majority of these issues. Doing it this way would be much simpler than a protocol communicating with separate process.

None of this is to say having running in a separate process shouldn't be an option.

**Comment by csyonghe** [comment]
We have test server now.
