### ISSUE TITLE
Support tessellation shaders on Vulkan

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#854]
Demand for tessellation support is not especially high, but we should get to it before users start asking for it, rather than making them wait when it is a priority.

Translation domain shaders into "tessellation evaluation shaders" should be straightforward, since the approach is quite similar across the D3D and OpenGL/Vulkan.

Translating a hull shader to a "tessellation control shader" is more interesting. An HLSL hull shader comprises two functions, one invoked for each output control point (this is the nominal entry point) and a "patch constant function" that is invoked once for the whole patch. For example, we might have:

```hlsl
struct MyCoarseVertex { ... }; // coming from VS
struct MyControlPoint { ... };
struct MyPatch { ... };

MyPatch myPatchConstantFunc(
    InputPatch<MyCoarseVertex, COARSE_VERTEX_COUNT> inputPatch,
    OuputPatch<MyControlPoint, CONTROL_POINT_COUNT> outputPatch,
    out float tessFactors[4] : SV_TessFactor,
    out float insideTessFactors[2] : SV_InsideTessFactor)
{
    return ...;
}

[domain("quad")]
[outputtopology("triangle_ccw")]
[outputcontrolpoints(CONTROL_POINT_COUNT)]
[patchconstantfunc("myPatchConstantFunc")]
MyControlPoint myControlPointFunc(
    InputPatch<MyCoarseVertex, COARSE_VERTEX_COUNT> inputPatch,
    uint id : SV_ControlPointID)
{
    return ...;
}
```

A sort-of-equivalent GLSL tessellation control shader would look something like:

```glsl
// Types as before
struct MyCoarseVertex { ... }; // coming from VS
struct MyControlPoint { ... };
struct MyPatch { ... };

// Previous entry point functions as ordinary subroutines
MyPatch myPatchConstantFunc(...) { ... }
MyControlPoint myControlPointFunc(...) { ... }

in MyCoarseVertex inputPatch[];
out MyControlPoint outputPatch[];
patch out MyPatch outputPatchConstants;

layout(vertices = CONTROL_POINT_COUNT) out;
void main()
{
    outputPatch[gl_InvocationID] = myControlPointFunc(inputPatch, gl_InvocationID);
    barrier();
    if(gl_InvocationID == 0)
    {
        outputPatchConstants = myPatchConstantFunc(
            inputPatch,
            outputPatch,
            gl_TessLevelOuter,
            gl_TessLevelInner);
    }
}
```

Note how in this case we have synthesized a new `main` entry point that coordintes the calling of the original entry-point functions. Because only one invocation of `myPatchConstantFunc` is desired, we limit it to the first invocation/thread of the group. This choice limits the opportunities for parallelization of the patch-constant function (which might, e.g., loop over all corners, edges, etc. of the patch in a data-parallel fashion), but at least supports the semantics of the original HLSL.

There are many details that this example is leaving out, but the main point is that translation of hull shaders to GLSL/Vulkan is primarily a matter of synthesizing a new entry point function that both wraps up the old one and invokes the patch-constant function appropriately.

**Comment by natduca** [comment]
Lets re-discover/open this in context of spirv backen but close this for old-ness.
