### ISSUE TITLE
Identity cases for asuint, asfloat, etc.

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#857]
Subtle errors can arise when users apply, e.g., the `asfloat` function to a value that is already a `float`:

```hlsl
float f = ...;
float g = asfloat(f);
```

The above code will select between the two available overloads of `asfloat` that are implemented in Slang (which follows what is documented on MSDN):

```hlsl
float asfloat(uint val);
float asfloat(int val);
```

Supposing that the `int` variation gets chosen, this means the code compiled like:

```hlsl
float g = asfloat(int(f));
```

That means we convert `f` from `float` to `int`, and then convert the bit pattern of that `int` to a `float`. This is not what the user would expect/want: they just want `asfloat` on a `float` to be an identity.

Indeed, it seems that both fxc and dxc support additional overloads of `asfloat`, etc. to handle the identity cases, and these just aren't documented on MSDN.

**Comment by tfoleyNV** [comment]
@jsmall-nvidia I think you implemented all these, right?

**Comment by jsmall-nvidia** [comment]
Yes these are in.
