### ISSUE TITLE
Investigate memory usage for multiple compile requests per session

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#859]
In testing we have observed the memory usage of a `SlangSession` slowly creep up as multiple `SlangCompileRequest`s are run through it. This isn't acceptable, and the memory usage of a `SlangSession` should remain flat over time.

**Comment by natduca** [comment]
I think Ashwin is going to get us set up with some perf monitoring infra from his team so this should start getting discovered that way. Closing for now.
