### ISSUE TITLE
Support a simple zip-based container format

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#860]
Using `slangc` to generate multiple output kernels in one pass is kind of painful today, since the user needs to specify multiple output paths with `-o`. It would be better if `slangc` could write out a single `.zip` file that contains all the kernels generated in a compile request, with an embedded manifest (probably JSON) to help document what kernels landed where.

Over time the Slang library interface should be updated to be able to use such a `.zip` file (or a directory tree matching its layout) as a runtime shader cache, but for a first-pass implementation we should start with just generating the format.

Similarly, on a longer time scale we should put serialized Slang IR/AST modules into the same container file, so that we can use it as a deployment format for compiled shader libraries.

**Comment by csyonghe** [comment]
We have container artifact formats now.
