### ISSUE TITLE
Segfault in "hello-world" example (gfx::windowProc)

### ISSUE THREAD

**Issue by ennis** [shader-slang/slang#874]
I was trying to run the "hello-world" example after compiling it, but it segfaulted at https://github.com/shader-slang/slang/blob/69d2651056137eb7c6e542491ae5fd59af095022/tools/gfx/window.cpp#L158

The `window` pointer is invalid, and appears to contain only the first 32 bits of the original pointer.

I'm on Windows 10 x64, compiling with MSVC 17.

At first glance, the issue seems to be here:
https://github.com/shader-slang/slang/blob/69d2651056137eb7c6e542491ae5fd59af095022/tools/gfx/window.cpp#L176

`window` is cast to `LONG` before being passed to `SetWindowLongPtr`, truncating it to 32 bits (long is 32 bits on win64). Replacing `LONG` with `LONG_PTR` seemed to fix the issue.

**Comment by tfoleyNV** [comment]
Thanks for catching this.

**Comment by tfoleyNV** [comment]
Fixed via #887
