### ISSUE TITLE
Vector comparison returns wrong type

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#892]
Vector comparison operators such as `operator ==(float3, float3)` should return `bool3`, which shouldn't be allowed directly as `if` condition or in branching(`x?y:z`) expressions.

Currently Slang does not issue any diagnostic message when source code does this, and generates invalid HLSL/GLSL that fails downstream compilation.

**Comment by tfoleyNV** [comment]
Can you confirm that we are returning a scalar `bool`? Or are we returning a vector and then truncating it silently?

Either way we need to investigate and fix this. The declarations of `operator==` in the stdlib should be clear about our intent, so I wonder if we declared them wrong, or if overload resolution is somehow getting confused.

**Comment by tfoleyNV** [comment]
Note that the ternary `?:` operator *is* allowed on vectors, and simply does a component-wise selection between the operands. This is fine because HLSL doesn’t have short-circuiting in conditional expressions.

**Comment by tfoleyNV** [comment]
Looking at the stdlib generation code, it looks like we properly declare vector comparisons to return vectors of `bool` and I seem to recall that @jsmall-nvidia has done work on making sure those translate to correct GLSL.

You may have found a new case, or maybe the current code is broken in ways we didn’t understand. Can you produce a small repro shader?

**Comment by csyonghe** [comment]
GLSLang reports error for both if and ternary expression conditions though. I will check and confirm what we generate.

**Comment by tfoleyNV** [comment]
Yeah, GLSL has different rules than HLSL here, but I thought we generated correct code for `?:` in a recent fix (translate it to a call to `mix`). I assume you are on top-of-tree Slang?

As for `if`, we really shouldn’t be allowing an `if` on a vector condition, so that makes me worry that we have a bug.

**Comment by csyonghe** [comment]
I am at top of tree, but this following test failed:
```
// vector-comparison.slang

//TEST:CROSS_COMPILE:-target spirv-assembly -entry main -stage fragment

// This test ensures that we cross-compile vector comparison operators
// correctly to GLSL

struct Param
{
    float4 a, b;
};
ParameterBlock<Param> params;
float4 main() : SV_Target
{
    float4 v0 = params.a;
    float4 v1 = params.b;
    float4 result = v0 == v1 ? float4(2.0f) : float4(3.0f);
    result += v0 < v1 ? float4(2.0f) : float4(3.0f);
    result += v0 > v1 ? float4(2.0f) : float4(3.0f);
    result += v0 <= v1 ? float4(2.0f) : float4(3.0f);
    result += v0 >= v1 ? float4(2.0f) : float4(3.0f);
    result += v0 != v1 ? float4(2.0f) : float4(3.0f);
    return result;
}
```

**Comment by tfoleyNV** [comment]
Great. This looks actionable. We need to make the `kIROp_Select` case map to a `mix` call in these cases. I’m a bit surprised it doesn’t already.

Were you able to confirm if the same problem can occur with `if`?

**Comment by csyonghe** [comment]
`if` actually works fine now. Slang correctly issues an error saying `bool4` cannot be used in `if`.

**Comment by tfoleyNV** [comment]
I just checked `emit.cpp` and `kIROp_Select` isn’t implemented correctly for GLSL output. We should have it emit an appropriate call to the `mix` function when we are targeting GLSL.
