### ISSUE TITLE
Support 16-bit floating point on Vulkan/SPIR-V

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#906]
The Slang compiler currently allows `half` types in the front end and reproduces those `half` types in GLSL (including vector types like `hvec4`). That isn't quite enough to support generating SPIR-V with 16-bit floating point, though.

A few other items we need to tackle include:

- [x] When emitting GLSL code for a shader that uses `half`s, we should add on appropriate `#extension`s or tweak the GLSL `#version` based on what gets used. This could be heavy-handed at first (requesting more than what we actually need) and get refined over time.

- [x] When working with "typed" views (SRVs or UAVs in D3D-speak) like `Texture2D<half2>` or `RWTexture2D<half4>`, we need to somehow deal with the fact that the GLSL `image2D` type always traffics in `vec4`s (which use 32-bit `float`s). At the very least we need to emit conversion operations to get out the right component type (similar to how the `$z` in our intrinsics is used to get out the right component count).

It is probable that there are other items I'm missing, so we should update this issue as we go.

**Comment by csyonghe** [comment]
This is now implemented as `$c` emit control character and used in our glsl intrinsic definitions.
