### ISSUE TITLE
Compile fails with matrix type in hlsl

### ISSUE THREAD

**Issue by jdswebb** [shader-slang/slang#933]
Hi,

Using the latest version of slang, a cbuffer containing a 'matrix' fails to compile whereas 'float4x4' compiles fine.

The failure occurs in slang/syntax.cpp at Type::GetCanonicalType().

I am normally compiling using the API but the failure can be observed via slangc not outputting a file with the following command and example file:

`slangc.exe test_shader.hlsl -target hlsl -profile sm_6_3 -stage compute -entry main -o test.dxil`

test_shader.hlsl:
```
cbuffer CBuffer : register(b0)
{
    matrix mat;
}

[numthreads( 8, 8, 1 )]
void main( uint3 id : SV_DispatchThreadID )
{ }
```

Changing test_shader.hlsl to the following then does produce output:

```
cbuffer CBuffer : register(b0)
{
    float4x4 mat;
}

[numthreads( 8, 8, 1 )]
void main( uint3 id : SV_DispatchThreadID )
{ }
```

Thanks

**Comment by tfoleyNV** [comment]
Thanks for reporting this. It appears to be a regression since that syntax was supported before.

**Comment by tfoleyNV** [comment]
Note for whoever tries to fix this: the same basic logic that should default `matrix` to `matrix<float,4,4>` is also responsible for turning `Texture2D` into `Texture2D<float4>`, so if one of these isn’t working right it makes me worry about the other.

**Comment by csyonghe** [comment]
Fixed.
