### ISSUE TITLE
Duplicate non-aggregate type declarations, Opcode: TypeAccelerationStructureNV

### ISSUE THREAD

**Issue by Nimanf** [shader-slang/slang#937]
A lot of shaders written for `DXR`/`VK_NV_ray_tracing` produces the following validation error.
Even though the shader works, we are probably declaring TypeAccelerationStructureNV twice in SPIR-V.

```
SPIR-V module not valid: Duplicate non-aggregate type declarations are not allowed. 
Opcode: TypeAccelerationStructureNV id: 10734
  %10734 = OpTypeAccelerationStructureNV
````

**Comment by tfoleyNV** [comment]
This is probably a glslang issue, given that our output GLSL only declares things once. We’ll need to investigate and contribute a fix upstream.

**Comment by jeffbolznv** [comment]
This should have been fixed by https://github.com/KhronosGroup/glslang/pull/1645

**Comment by tfoleyNV** [comment]
Thanks @jeffbolznv. We will be updating the version of glslang that we depend on soon, so we should pick up the fix as part of that.

Hopefully once we have a new Slang release that incorporates the fix @Nimanf can confirm that the issue he's seeing is addressed and we can close this out.

**Comment by chuckgenome** [comment]
I can confirm that this issue has been addressed with the latest glslang changes incorporated into #940. Closing this issue out.
