### ISSUE TITLE
Not emitting sample and centroid qualifiers in GLSL

### ISSUE THREAD

**Issue by philcn** [shader-slang/slang#942]
I noticed that the `sample` and `centroid` qualifiers for interpolants are not being emitted in GLSL.

For example:

```
struct RasterVertex
{
    sample float c;
    centroid uint u;
};
```

will produce the following GLSL section:

```
layout(location = 0)
in float _S4;

flat layout(location = 1)
in uint _S5;
````

Note that the flat qualifier works (https://github.com/shader-slang/slang/pull/842)

These qualifiers work in HLSL output. Can Slang support emitting them in GLSL?

**Comment by tfoleyNV** [comment]
This sounds like it is just an oversight in the implementation. We can survey the handling of these qualifiers in the GLSL back-end and see if these would be easy to add.

**Comment by csyonghe** [comment]
This is fixed.
