### ISSUE TITLE
Does it support mobile platform ?

### ISSUE THREAD

**Issue by nvcken** [shader-slang/slang#948]
OpenGL ES

**Comment by tfoleyNV** [comment]
The Slang compiler currently has a good level of support for Direct3D 12 and Vulkan, with a lower level of support for Direct3D 11.

We don't currently have a usable level of support for any OpenGL targets (the GLSL we generate can include Vulkan-specific features), whether desktop or ES/WebGL.

This isn't something fundamental to the compiler, but just a matter of what the priorities have been for Slang's current users and contributors. If somebody wanted to work on improving our support for OpenGL (ES), we would be interested in merging those changes.

If somebody wanted to use Slang and deploy to an OpenGL ES target in the near term, I might encourage them to consider generating SPIR-V for Vulkan from the Slang compiler, and then using a project like spirv-cross to translate the SPIR-V into GLSL for OpenGL ES. I haven't tried out a compilation pipeline like that, but the pieces should exist.

**Comment by tangmi** [comment]
I've had success with taking the output of `slang` and piping it into [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross).

Note if you're targeting iOS, Apple doesn't implement separable shader objects quite right and requires the varying names to match (https://stackoverflow.com/questions/24267069/opengl-mac-osx-vertex-shader-not-linking-to-fragment-shader). SPIRV-Cross appends `[in|out]_var_` to varying names, which can be easily stripped.
