### ISSUE TITLE
Implement HLSL clip() intrinsic in GLSL

### ISSUE THREAD

**Issue by chuckgenome** [shader-slang/slang#950]
HLSL shaders can use the clip() intrinsic (https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-clip)

There is no equivalent intrinsic in GLSL so we should implement it similar to:
```
void clip(T x)
{
  if (any(x < 0))
    discard;
}
```

**Comment by csyonghe** [comment]
Already implemented.
