### ISSUE TITLE
`SLANG_hack_samplerForTexelFetch` binding collides with user declared objects

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#96]
Is `SLANG_hack_samplerForTexelFetch` hardcoded to use `set=0, binding=0`?
It collides with other user declarations.

`TextRenderer.fs.slang` is one example

**Comment by tangent-vector** [comment]
Hard-coded yes. Does it lead to compilation failures?
I can compute a non-colliding binding for it.

Have you found that if needs a sampler bound?

**Comment by nbenty** [comment]
No, is successfully compiles to SPIR-V.
I don't see anything in the Vulkan spec that forbids such behavior. `vkUpdateDescriptorSets` accepts the descriptor type, so perhaps a bind-location is defined by the index *and* the type, but I couldn't find it in the spec.

The problem is that the debug layer spits an error. Perhaps it's a bug in their code.

As for the other question - I don't see it in the reflection and I don't bind anything to that slot, so I guess it's not an issue

**Comment by tangent-vector** [comment]
We now generate a unique binding for this "hack" sampler, and report it through reflection.

I'm going to close this specific issue, but it is clear that long term we need to eliminate the need for this sampler altogether, which requires work inside glslang (see glslang issue 1003)
