### ISSUE TITLE
Shaders with variable size arrays crash

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#98]
Declare this in the shader
```C++
layout(set = 0, binding = 0) buffer gLightIn
{
    vec3 val[];
};
```
Slang crashes inside `GetIntVal()` (syntax.cpp, line 937)

**Comment by tangent-vector** [comment]
I think I've fixed the crash in my own branch, but this was done by handling unknown-size arrays as if they were zero-element arrays, and this runs the risk of breaking a lot of downstream logic.

The right fix is to have an explicit notion of something taking up an unbounded amount of storage of a particular resource kind, but that will be a nuanced thing that could be tricky to get right.

**Comment by tangent-vector** [comment]
Closing. This issue is ancient and doesn't reflect the current Slang language/compiler any more (we no longer support GLSL syntax).
