### ISSUE TITLE
HLSL's StructuredBuffer to GLSL conversion issues

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#99]
Unrelated to the release, just documenting some issues I encountered.

Our initial thought was to use variable-size arrays. That doesn't map well to HLSL - and by extension to Falcor. The problem is how to reflect things correctly. 
For example 
```C++
struct Foo {float3 bar;};
StructuredBuffer<Foo> gFoo;
```
(1) Falcor looks for the buffer using `gFoo`.
(2) Falcor is not aware of the `Foo`. It gets the struct size from `gFoo`.
(3) Reading/writing variables from the host side is done using the fields on `Foo` directly - `mpFoo[0]["bar"]` (the first index is the struct index

I don't know how to translate that to GLSL. We can do something like
```
struct Foo {float3 bar;};
layout(set = 1, binding = 4) buffer gFoo
{
    Foo foo[];
};
```
HLSL (1) Will work just fine
HLSL (2) Doesn't. We will need to get the size of `gFoo.foo`
HLSL(3) Doesn't work as well. `foo` gets in the way

This isn't necessarily just a cross-compilation issue. Even for hand-written code, I have no idea how to make Falcor's DX abstractions work with GLSL

**Comment by tangent-vector** [comment]
For cross-compilation, the reflection data should be the same as for HLSL, so you don't have to care about what it would translate to in GLSL.

For the raw GLSL case, it is going to reflect as a buffer with an array in it, yeah. I would assume the user would bind things just as they would for an array in a `cbuffer` today.

**Comment by tfoleyNV** [comment]
A bit of follow-up on this (mostly for my own benefit). Part of the question here is about a convention that Falcor can use to have hand-written GLSL that appear "the same" to its reflection system as a `StructuredBuffer<T>`. That is an interesting problem, but out of scope for Slang to solve. Slang's job would be to report the global-scope `buffer` block to you as accurately as possible (I'm not sure how I do on that right now...).

There actual Slang issue is what to do with a `StructureBuffer<T>` type when used in Slang code.
Given a global-scope declaration like you show:

```
struct Foo { float3 bar; };
StructuredBufer<Foo> gFoo;
```

There are two big issues:
1. What to do with the actual global-scope shader parameter declaration
2. What to do with uses of `StructuredBuffer<Foo>` at other locations (e.g., as a function parameter)

For (1) the ideal answer is a translation like Nir shows above (with a bit of name-change sleight-of-hand):

```
struct Foo { vec3 var; };
layout(..) buffer SLANG_buffer_gFoo {
    Foo gFoo[];
};
```

In this case, the name `gFoo` does not refer to the whole `buffer`, but to the array member inside it. Simple expressions like `gFoo[i]` in HLSL translate naturally over to GLSL.

The tricky bit, then, is that when the type `StructuredBuffer<Foo>` appears in any other context, we need to translate it as `Foo[]` - an unsized array of `Foo`s. This should make it semantically okay to pass `gFoo` as a parameter to a function.

The big problem with that last bit is that the GLSL semantics for function calls are pass-by-value-result, which means we would technically copy the whole array, which might not even be legal. So thinking about it further, this would probably rely on an implementation that can specialize the callee function based on the known identity of resource parameters passed in. That is something we'll need to get to eventually on Slang, but isn't at the top of my to-do list any time soon.

**Comment by tfoleyNV** [comment]
The IR-based code generator has an initial implementation of this conversion, so I think we can close this specific issue.

`StructureBuffer` variables declared as global shader parameters should work when cross-compiled to GLSL. We currently don't do a correct conversion when a `StructuredBuffer<X>` type is used for a function parameter (or a type passed as part of a function parameter), so that would still leave more work...
